### ISSUE TITLE
Ca't open .RTF or .TXT files with Collabora Online

### ISSUE THREAD

**Issue by deneb-alpha** [nextcloud/richdocuments#10]
### Steps to reproduce
1. Disable the official Text editor 2.2 by Tom Needham, Björn Schießle 
2. Upload a .RTF/TXT file
3. Try to open it

### Expected behaviour
Collabora Office OnLine opens the file

### Actual behaviour
Nextcloud download the file

### Server configuration
**Operating system**: Ubuntu 16.04.1 LTS

**Web server:** nginx/1.10.0 (Ubuntu)

**Database:** Maria DB

**PHP version:** php 7.0

**Nextcloud version:** 11

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** manual installation

**Comment by timar** [comment]
Fixed in version 1.11.27 (for NC 11), and in version 1.12.27 (for NC 12).
