### ISSUE TITLE
Printing with Vivaldi and Chrome results in blank pages

### ISSUE THREAD

**Issue by hftl-kalle** [nextcloud/richdocuments#100]
### Steps to reproduce
1. Install Collabora as described
2. Create Document and enter text
3. Print document

### Expected behaviour
Preview window as well as printed page should show entered text.

### Actual behaviour
Preview window as well as printed page are blank

### Server configuration

**Operating system**:
Ubuntu Server 16.04.2 LTS
**Web server:**
Apache2
**Database:**
MaraiDB
**PHP version:**
PHP7
**Nextcloud version:** (see Nextcloud admin page)
12
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh
**Where did you install Nextcloud from:**
download.nextcloud.com
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - admin_notifications: 1.0.0
  - announcementcenter: 3.1.0
  - audioplayer: 2.0.1
  - bookmarks: 0.10.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - camerarawpreviews: 0.0.1
  - circles: 0.10.0
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - deck: 0.1.4
  - drawio: 0.8.8
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.4
  - files_automatedtagging: 1.2.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.2.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - previewgenerator: 1.0.6
  - provisioning_api: 1.2.0
  - rainloop: 5.0.0
  - richdocuments: 1.12.32
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_email: 1.0.1
  - spreed: 2.0.1
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.0
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - ojsxc
  - user_external
  - user_ldap

```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oc1hknumvhbj",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "REMOVED"
        ],
        "datadirectory": "\/media\/ServerData\/nextcloud",
        "overwrite.cli.url": "https:\/\/REMOVED",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "REMOVED",
        "mail_domain": "REMOVED",
        "mail_smtpauth": 1,
        "mail_smtphost": "REMOVED",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OCA\\CameraRawPreviews\\RawPreview",
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Movie"
        ],
        "maintenance": false,
        "loglevel": 0
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Vivaldi 1.9.818.50 (Stable channel) (32-bit)
Chrome Version 58.0.3029.110 (64-bit)
**Operating system:**
Win 10
#### Web server error log
<details>
<summary>Web server error log</summary>
```
Does not show anything relevant
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Does not show anything when printing
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

bundle.js:14294 Resource interpreted as Document but transferred with MIME type application/pdf: "blob:https://Removed/385fcfea-c8af-4558-a7b6-20625091e8b2".

385fcfea-c8af-4558-a7b6-20625091e8b2:1 Refused to load plugin data from 'blob:https://Removed/385fcfea-c8af-4558-a7b6-20625091e8b2' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'object-src' was not explicitly set, so 'default-src' is used as a fallback.

</details>

**Comment by pranavk** [comment]
Hi,

Thanks for the report. Indeed, it was a problem which is now fixed here
https://gerrit.libreoffice.org/gitweb?p=online.git;a=commit;h=54ea43602604a1d111e35e6efef3d76cc8386e70

and backported to appropriate release branch. It should be available with the next update of the docker image.

By the way, it was not really a richdocuments bug, it was directly related to online repository, bugs for which should be filed in bugs.documentfoundation.org, but its okay :)

**Comment by hftl-kalle** [comment]
Thanks! 
I am having a hard time distinguishing though where the app ends and the docker image starts
