### ISSUE TITLE
NC 19 unable to Use Build in Code Server

### ISSUE THREAD

**Issue by apg1980** [nextcloud/richdocuments#1009]
**Describe the bug**
NC 19 stable with Collabora Online - Built in CODE Server throws errors in Apache error.log:

`AH01071: Got error 'en(): unable to connect to localhost:9982 (Connection refused) in /var/www/nextcloud/apps/richdocumentscode/proxy.php on line 246PHP message: PHP Warning:  fsockopen(): unable to connect to localhost:9982 (Connection refused) in /var/www/nextcloud/apps/richdocumentscode/proxy.php on line 246PHP message: PHP Warning:  fsockopen(): unable to connect to localhost:9982 (Connection refused) in /var/www/nextcloud/apps/richdocumentscode/proxy.php on line 246PHP message: PHP Warning:  fsockopen(): unable to connect to localhost:9982 (Connection refused) in /var/www/nextcloud/apps/richdocumentscode/proxy.php on line 246PHP message: PHP Warning:  fsockopen(): unable to connect to localhost:9982 (Connection refused) in /var/www/nextcloud/apps/richdocumentscode/proxy.php on line 246PHP message: PHP Warning:  fsockopen(): unable to connect to localhost:9982 (Connection refused) in /var/www/nextcloud/apps/richdocumentscode/proxy.php on line 246PHP message: PHP Warning:  fsockopen(): unable to connect to localhost:9982 (Connection refused) in /var/www/nextcloud/apps/richdocumentscode/proxy.php on line 246PHP message: PHP Warning:  fsockopen(): unable to connect to localhost:9982 (Connection refused) in /var/www/nextcloud/apps/richdocumentscode/proxy.php on line 246PHP message: PHP Warning:  fsockopen(): unable to connect to localhost:9982 (Connection refused) in /var/www/nextcloud/apps/richdocumentscode/proxy.php on line 246'
`
Nextcloud is displaying error: Connection to Documentserver lost.
New or existing Documents arent opened, white screen appears (see log above).

Settings are correct to use internal CODE Server:

![Unbenannt](https://user-images.githubusercontent.com/9514965/83636454-4cced900-a5a6-11ea-924e-671689a0a5c3.JPG)

**To Reproduce**
1. Klick New Document
2. see
![Unbenannt2](https://user-images.githubusercontent.com/9514965/83636594-81429500-a5a6-11ea-85e1-033910cd44a7.JPG)

**Expected behavior**
Document is opening for editiing

**Client details:**
 - Browser Latest Firefox

## Server details

**Operating system**: Ubuntu 18.04 LTS

**Web server:** Apache2

**Database:** Postgresql

**PHP version:** PHP7.3-fpm

**Nextcloud version:** 19

**Version of the richdocuments app** 3.7.0

**Version of Collabora Online**  4.2.403

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
No entrys available
```

</details>

**Comment by Ecphrasis** [comment]
Same problem for me, on 19 released this morning. I can't even connect to the built-in CODE
![000037](https://user-images.githubusercontent.com/11899009/83642280-eac6a180-a5ae-11ea-8841-8e34781aa207.png)

Apche log : tons of PHP Warning:  fsockopen(): unable to connect to localhost:9982 (Connection refused) in /var/www/nextcloud/apps/richdocumentscode/proxy.php on line 246PHP

Server details
Operating system: Debian Buster

Web server: Apache2

Database: MySQL

PHP version: PHP7.4-fpm

Nextcloud version: 19

Version of the richdocuments app 3.7.0

Version of Collabora Online 4.2.403

**Comment by juliushaertl** [comment]
This issue seems to be related to the CODE built-in server that is located in a different repo: https://github.com/CollaboraOnline/richdocumentscode

Please head over to that to report the issue you are encountering.

@kendy @timar FYI :wink:
