### ISSUE TITLE
After updating the Richdocuments (Collabora Online) from 3.6.0 to 3.7.0, the application cannot be enabled

### ISSUE THREAD

**Issue by lvarnava** [nextcloud/richdocuments#1012]
After updating the Richdocuments (Collabora Online) from 3.6.0 to 3.7.0, the application cannot be enabled; after trying to enable it, it remains disabled.
In the case of Nextcloud server 17.0.6, there was no problem.
When I downgraded to 3.6.0, it worked again.

Nextcloud server: 16.0.10.2
Ubuntu server:18.04.4
PHP: 7.2.24
Apache: 2.4.29

**Comment by DevDorrejo** [comment]
hello how can i downgrade to 3.6.0?, the 3.7.0 is not working:

![image](https://user-images.githubusercontent.com/7697566/83707329-bf13dd80-a5e7-11ea-8344-2286cf44ef8d.png)

but when i click save it said that reach the server.

**Comment by lvarnava** [comment]
HI @DevDorrejo!
Here are the steps to downgrade app:
```
cd /var/www/nextcloud/
sudo -u www-data php occ app:remove richdocuments
cd /tmp
wget https://github.com/nextcloud/richdocuments/releases/download/v3.6.0/richdocuments.tar.gz
tar xvzf richdocuments.tar.gz
mv richdocuments /var/www/nextcloud/apps/
rm richdocuments.tar.gz
chown -R www-data:www-data /var/www/nextcloud/apps/richdocuments
cd /var/www/nextcloud/
sudo -u www-data php occ app:enable richdocuments
```
But probably in your case the problem can be solved here #949

**Comment by juliushaertl** [comment]
Please check both the nextcloud as well as your collabora log for errors.

**Comment by lvarnava** [comment]
nextcloud log:

[no app in context] Error: OCP\AppFramework\QueryException: Could not resolve OCP\EventDispatcher\IEventDispatcher! Class OCP\EventDispatcher\IEventDispatcher does not exist at <<closure>>

 0. /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 119
    OC\AppFramework\Utility\SimpleContainer->resolve("OCP\\EventDispatcher\\IEventDispatcher")
 1. /var/www/html/nextcloud/lib/private/ServerContainer.php line 150
    OC\AppFramework\Utility\SimpleContainer->query("OCP\\EventDispatcher\\IEventDispatcher")
 2. /var/www/html/nextcloud/apps/richdocuments/lib/AppInfo/Application.php line 67
    OC\ServerContainer->query("OCP\\EventDispatcher\\IEventDispatcher")
 3. /var/www/html/nextcloud/lib/private/Route/Router.php line 373
    OCA\Richdocuments\AppInfo\Application->__construct()
 4. /var/www/html/nextcloud/lib/private/Route/Router.php line 351
    OC\Route\Router->setupRoutes({routes: [{name: ... ]}, "richdocuments")
 5. /var/www/html/nextcloud/lib/private/Route/Router.php line 151
    OC\Route\Router->requireRouteFile("/var/www/html/n ... p", "richdocuments")
 6. /var/www/html/nextcloud/lib/private/Route/Router.php line 331
    OC\Route\Router->loadRoutes()
 7. /var/www/html/nextcloud/lib/private/Route/CachingRouter.php line 60
    OC\Route\Router->generate("mail.page.index", [], false)
 8. /var/www/html/nextcloud/lib/private/URLGenerator.php line 79
    OC\Route\CachingRouter->generate("mail.page.index", [])
 9. /var/www/html/nextcloud/apps/mail/appinfo/app.php line 42
    OC\URLGenerator->linkToRoute("mail.page.index")
10. /var/www/html/nextcloud/lib/private/legacy/app.php line 265
    undefinedundefinedrequire_once("/var/www/html/n ... p")
11. /var/www/html/nextcloud/lib/private/legacy/app.php line 155
    OC_App::requireAppFile("mail")
12. /var/www/html/nextcloud/lib/private/legacy/app.php line 128
    OC_App::loadApp("mail")
13. /var/www/html/nextcloud/ocs/v1.php line 56
    OC_App::loadApps()
14. /var/www/html/nextcloud/ocs/v2.php line 24
    undefinedundefinedrequire_once("/var/www/html/nextcloud/ocs/v1.php")

GET /ocs/v2.php/core/navigation/apps?format=json

---
[no app in context] Error: OCP\AppFramework\QueryException: Could not resolve OCP\EventDispatcher\IEventDispatcher! Class OCP\EventDispatcher\IEventDispatcher does not exist at <<closure>>

 0. /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 119
    OC\AppFramework\Utility\SimpleContainer->resolve("OCP\\EventDispatcher\\IEventDispatcher")
 1. /var/www/html/nextcloud/lib/private/ServerContainer.php line 150
    OC\AppFramework\Utility\SimpleContainer->query("OCP\\EventDispatcher\\IEventDispatcher")
 2. /var/www/html/nextcloud/apps/richdocuments/lib/AppInfo/Application.php line 67
    OC\ServerContainer->query("OCP\\EventDispatcher\\IEventDispatcher")
 3. <<closure>>
    OCA\Richdocuments\AppInfo\Application->__construct([])
 4. /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 81
    ReflectionClass->newInstanceArgs([[]])
 5. /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 98
    OC\AppFramework\Utility\SimpleContainer->buildClass(ReflectionClass  ... "})
 6. /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 119
    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Richdocume ... n")
 7. /var/www/html/nextcloud/lib/private/ServerContainer.php line 150
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\Richdocume ... n")
 8. /var/www/html/nextcloud/apps/richdocuments/appinfo/app.php line 62
    OC\ServerContainer->query("OCA\\Richdocume ... n")
 9. /var/www/html/nextcloud/lib/private/legacy/app.php line 265
    undefinedundefinedrequire_once("/var/www/html/n ... p")
10. /var/www/html/nextcloud/lib/private/legacy/app.php line 155
    OC_App::requireAppFile("richdocuments")
11. /var/www/html/nextcloud/lib/private/legacy/app.php line 128
    OC_App::loadApp("richdocuments")
12. /var/www/html/nextcloud/apps/dav/appinfo/app.php line 30
    OC_App::loadApps(["dav"])
13. /var/www/html/nextcloud/lib/private/legacy/app.php line 265
    undefinedundefinedrequire_once("/var/www/html/n ... p")
14. /var/www/html/nextcloud/lib/private/legacy/app.php line 155
    OC_App::requireAppFile("dav")
15. /var/www/html/nextcloud/lib/private/legacy/app.php line 128
    OC_App::loadApp("dav")
16. /var/www/html/nextcloud/remote.php line 148
    OC_App::loadApps(["filesystem","logging"])

PROPFIND /remote.php/dav/files/r.sekretariat/

[no app in context] Error: OCP\AppFramework\QueryException: Could not resolve OCP\EventDispatcher\IEventDispatcher! Class OCP\EventDispatcher\IEventDispatcher does not exist at <<closure>>

 0. /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 119
    OC\AppFramework\Utility\SimpleContainer->resolve("OCP\\EventDispatcher\\IEventDispatcher")
 1. /var/www/html/nextcloud/lib/private/ServerContainer.php line 150
    OC\AppFramework\Utility\SimpleContainer->query("OCP\\EventDispatcher\\IEventDispatcher")
 2. /var/www/html/nextcloud/apps/richdocuments/lib/AppInfo/Application.php line 67
    OC\ServerContainer->query("OCP\\EventDispatcher\\IEventDispatcher")
 3. <<closure>>
    OCA\Richdocuments\AppInfo\Application->__construct([])
 4. /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 81
    ReflectionClass->newInstanceArgs([[]])
 5. /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 98
    OC\AppFramework\Utility\SimpleContainer->buildClass(ReflectionClass  ... "})
 6. /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 119
    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Richdocume ... n")
 7. /var/www/html/nextcloud/lib/private/ServerContainer.php line 150
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\Richdocume ... n")
 8. /var/www/html/nextcloud/apps/richdocuments/appinfo/app.php line 62
    OC\ServerContainer->query("OCA\\Richdocume ... n")
 9. /var/www/html/nextcloud/lib/private/legacy/app.php line 265
    undefinedundefinedrequire_once("/var/www/html/n ... p")
10. /var/www/html/nextcloud/lib/private/legacy/app.php line 155
    OC_App::requireAppFile("richdocuments")
11. /var/www/html/nextcloud/lib/private/legacy/app.php line 128
    OC_App::loadApp("richdocuments")
12. /var/www/html/nextcloud/apps/dav/appinfo/app.php line 30
    OC_App::loadApps(["dav"])
13. /var/www/html/nextcloud/lib/private/legacy/app.php line 265
    undefinedundefinedrequire_once("/var/www/html/n ... p")
14. /var/www/html/nextcloud/lib/private/legacy/app.php line 155
    OC_App::requireAppFile("dav")
15. /var/www/html/nextcloud/lib/private/legacy/app.php line 128
    OC_App::loadApp("dav")
16. /var/www/html/nextcloud/ocs/v1.php line 56
    OC_App::loadApps()
17. /var/www/html/nextcloud/ocs/v2.php line 24
    undefinedundefinedrequire_once("/var/www/html/nextcloud/ocs/v1.php")

GET /ocs/v2.php/core/navigation/apps?format=json

**Comment by DevDorrejo** [comment]
> HI @DevDorrejo!
> Here are the steps to downgrade app:
> 
> ```
> cd /var/www/nextcloud/
> sudo -u www-data php occ app:remove richdocuments
> cd /tmp
> wget https://github.com/nextcloud/richdocuments/releases/download/v3.6.0/richdocuments.tar.gz
> tar xvzf richdocuments.tar.gz
> mv richdocuments /var/www/nextcloud/apps/
> rm richdocuments.tar.gz
> chown -R www-data:www-data /var/www/nextcloud/apps/richdocuments
> cd /var/www/nextcloud/
> sudo -u www-data php occ app:enable richdocuments
> ```
> 
> But probably in your case the problem can be solved here #949

thank you, adding the capabilities fix the problem on 3.7.0

**Comment by juliushaertl** [comment]
Ah, IEventDispatcher is Nextcloud 17+ only, so we should handle that properly of course as long as older Nextcloud versions are still supported.

**Comment by DevDorrejo** [comment]
adding capabilities on the vhost of the collaboraoffice, will fix this problem

**Comment by karfianto** [comment]
I manage to fix this by these steps:

1. Add this (new) path in proxy config
```
    # WOPI capabilities URL
    location ^~ /hosting/capabilities {
        proxy_pass https://your-collabora-online-host:port; 
        proxy_set_header Host $http_host;
    }

```
2. Manually enable the `disable_certificate_verification` if needed (somehow it didn't updated)
```
UPDATE `oc_appconfig` SET
`configvalue` = 'true'
WHERE `appid` = 'richdocuments' AND `configkey` = 'disable_certificate_verification' ;
```

**Comment by ClCfe** [comment]
hello bug is here
https://github.com/nextcloud/richdocuments/blob/2a29bc214ac88d36614fb3387c4bfe3af995f41f/lib/Controller/SettingsController.php#L150

should be 
`$disable_certificate_verification === true ? 'yes' : ''`
you receive it as bool, not string

**Comment by juliushaertl** [comment]
All those are not related to the original log message that @lvarnava posted, so please check if the issue is actually the same before posting and otherwise open a new one.
