### ISSUE TITLE
Too many processes after performing search

### ISSUE THREAD

**Issue by grossherr** [nextcloud/richdocuments#1013]
**Describe the bug**
When clicking on search results with richdocuments/collaboraonline - 3.6. and 3.7 - activated a couple of processes are started, like loolwsd, forkit, a lot of kit_*** as well as mysqld ramping up. This leads to  full utilization of cpu and hdd, making the server unusable for some time, so a couple of minutes. 

I use NC 19 and the newest version of the plugins, but this happened before with NC 18 too.

Unfortunately that makes collabora unusable for me, because the only solution is to deactivate the plugin.

**To Reproduce**
1. Perform search
2. Click on search result
3. Watch processes go wild

**Expected behavior**
Not overloading the server 

### Server details

**Operating system**:
Ubuntu 18.04
**Web server:**
1.14
**Database:**
mysql 14.14
**PHP version:**
7.4
**Nextcloud version:**
19
**Version of the richdocuments app**
3.7.0
**Version of Collabora Online**
6.2

### Logs

The collabora_error.log is empty.

**Comment by juliushaertl** [comment]
This tracker is for the Nextcloud connector app named Collabora Online. For issues in the product, please open a bug report at: https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online

**Comment by grossherr** [comment]
@juliushaertl Ok. This connector app is activating the behavior. It works just fine with it disabled and using Onlyoffice.
