### ISSUE TITLE
Could not establish connection to the Collabora Online server

### ISSUE THREAD

**Issue by domchrgit** [nextcloud/richdocuments#1016]
I made a fresh install of Nextcloud 19 from scratch, and Collabora Online doesn't work

**To Reproduce**
If I try to open a document like the default one in Documents folders "Welcome to Nextcloud Hub.docx", there is a turning circle and after few seconds I obtain the error message "Failed to load Collabora Online - please try again later"
If I look into the settings  of Collabora Online, the built-in CODE server is checked but a red cross indicate "Could not establish connection to the Collabora Online server"

**Expected behavior**
I expect that Collabora Online works ...

**Client details:**
 - OS: Linux Centos7
 - Browser:  Chrome
 - Version:  83
 - Device: desktop

## Server details
**Operating system**:
Linux h2web20 4.9.0-0.bpo.12-amd64 #1 SMP Debian 4.9.210-1~deb8u1 (2020-02-21) x86_64 GNU/Linux

**Web server:**
Apache 2.4.34

**Database:**
MySQL 5.7

**PHP version:**
7.3

**Nextcloud version:**
19.0.0

**Version of the richdocuments app**
Text	3.0.1

**Version of Collabora Online**
Collabora Online 3.7.0
Collabora Online - Built-in CODE Server 4.2.403

**Comment by declanmarks** [comment]
I also have this issue. 

Operating system:
20.04 LTS (Focal Fossa)

Web server:
 Apache/2.4.41 (Ubuntu)

Database:
10.3.22-MariaDB-1ubuntu1 Ubuntu 20.04

PHP version:
7.4.3

Nextcloud version:
18.0.5

Version of the richdocuments app
Text 3.0.7

Version of Collabora Online
Collabora Online 3.7.0
Collabora Online - External CODE Server 4.2.3

**Comment by juliushaertl** [comment]
For problems regarding the built-in CODE server, please open an issue in the apps repo at https://github.com/CollaboraOnline/richdocumentscode

@declanmarks Please check your log files and open a separate ticket.
