### ISSUE TITLE
Fresh install error in collabora.sh #260

### ISSUE THREAD

**Issue by enoch85** [nextcloud/richdocuments#102]
@timar https://github.com/nextcloud/vm/issues/260

What's up with the release?

**Comment by timar** [comment]
https://github.com/nextcloud/richdocuments/releases/download/1.12.32/richdocuments.tar.gz works now. Accidentally the file was uploaded as a file not as a binary, and ended up at different URL.

**Comment by enoch85** [comment]
cc @aaaskew
