### ISSUE TITLE
Improve "Is the server online"

### ISSUE THREAD

**Issue by till** [nextcloud/richdocuments#1028]
**Describe the bug**

When you have Collabora running, you have to put in a URL to it in the Admin settings of Richdocuments (btw, why is it called Richdocuments and "Collabora Online" in the UI?). I copy-pasted the URL from my browser which was "https://office.example.org/". This did not work, took me a while of watching logs to find the "//hosting/discovery" call (which failed), and I corrected the URL to "https://office.example.org" (no trailing slash).

**To Reproduce**
1. Go to Admin UI > Collabora Online
2. Enter URL with trailing "/"
3. Click save

**Expected behavior**

I would expect the plugin to strip the trailing slash. Alternative — display a helpful error message with the request and response. :) 

## Server details

**Operating system**: `nextcloud:19.0-fpm`

**Web server:** Nginx

**Nextcloud version:** 19.0

**Version of the richdocuments app** 3.7.0

**Version of Collabora Online** Collabora Office 6.2-12

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)

![image](https://user-images.githubusercontent.com/27003/84422639-9c07b000-ac1d-11ea-884c-e582ec29acb9.png)

</details>

**Comment by joshtrichards** [comment]
Fixed in #1412
