### ISSUE TITLE
Make sidebar hidden by default 

### ISSUE THREAD

**Issue by rollanders** [nextcloud/richdocuments#1037]
When I open a document in Collabora the sidebar hides part of the document, and the icon for closing the sidebar is outside the visible window. I have to scroll to the right to find it and turn it off. This is very annoying.

**Comment by juliushaertl** [comment]
There is onging work in https://github.com/nextcloud/richdocuments/pull/1033

**Comment by jancborchardt** [comment]
This has been fixed since some time, no? Can you confirm @juliushaertl?

**Comment by juliushaertl** [comment]
Yes, this has been implemented with https://github.com/nextcloud/richdocuments/pull/1211
