### ISSUE TITLE
collabora 3.7.1 broken

### ISSUE THREAD

**Issue by peteman52** [nextcloud/richdocuments#1050]
**Describe the bug**
aborts with error

**Client details:**
 - Nextcloud 18.0.6, collabora 3.7.1
 - Firefox
 - latest
 - Desktop

## Server details

ubuntu 18.0.4

apache

mysql

php 7.3

nextcloud 18.0.6

3.7.1
4.2.4 loolwsd, Collabora Office 6.2-17

**Comment by BraindeadBZH** [comment]
#1051 Probably related.

**Comment by kiki78** [comment]
I confirm 3.7.1 doesn't work.
May I help with some log ?
I downgrade to 3.7.0 fir now.

**Comment by BraindeadBZH** [comment]
> I confirm 3.7.1 doesn't work.
> May I help with some log ?
> I downgrade to 3.7.0 fir now.
Check your logs if you have `Undefined index: watermark_text at /var/www/html/custom_apps/richdocuments/lib/Controller/SettingsController.php#237`

**Comment by kiki78** [comment]
May you give in which log file I must find ?

**Comment by BraindeadBZH** [comment]
> May you give in which log file I must find ?

You can either see that in Settings > Administration > Logging or in the data/nextcloud.log file.

**Comment by kiki78** [comment]
Sorry, I never found occurrence of this in nextcloud.log file

**Comment by BraindeadBZH** [comment]
Thanks, so the issue is somewhere else.

**Comment by jakedaytona** [comment]
Mine's not working with 3.7.1 either. Was ok on previous version. 
Docker Compose, Ubuntu 20.04. Nextcloud 19.

**Comment by juliushaertl** [comment]
Thanks for reporting everyone. 3.7.1 has been withdrawn and 3.7.2 is now available with a fix for the issue.

**Comment by s3ppo** [comment]
i installed 3.7.2 but i still cannot use collabora.. in chrome dev console i see an error like this:
VM778 main.js:190 Uncaught TypeError: Cannot read property 'substring' of undefined
    at Object.i [as filePath] (VM104 main.js:190)
    at Object.<anonymous> (VM127 main.js:22)
    at o (VM127 main.js:1)
    at VM127 main.js:1
    at VM127 main.js:1

**Comment by juliushaertl** [comment]
@s3ppo Please open a new issue since this seems unrelated to the one here.

**Comment by kiki78** [comment]
Thank you julius, I confirm 3.7.2 solve the issue.
