### ISSUE TITLE
Latest update is not responsive in web-window

### ISSUE THREAD

**Issue by rollanders** [nextcloud/richdocuments#1053]
1. Open a document
2. Shrink the window
3. The content in the window is not responsive. 

Windows 10, Collabora Online 3.7.2, NC 19.0

![image](https://user-images.githubusercontent.com/36486009/85436159-df044480-b588-11ea-9c8e-1df3c6715f59.png)

**Comment by juliushaertl** [comment]
Which version of Collabora are you running, as it seems the frame is resized properly just the document resizing is not working, so it might be a collabora bug.

**Comment by rollanders** [comment]
Yes - the window can be resized but the content does not respond.  

As far as I know I have the latest version

![image](https://user-images.githubusercontent.com/36486009/85610773-98c9e680-b657-11ea-8bbb-3534eca8a01d.png)

    
    
  
  
    To paste outside Collabora Online Development Edition (CODE), please first click the 'download' button

**Comment by juliushaertl** [comment]
Please update to the latest 4.2.6 version. If the issue still persists please open a bug report for Collabora directly at: https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online
