### ISSUE TITLE
After last update to 3.7.2. in NC 18.0.6 - no editing possible for not logged in users

### ISSUE THREAD

**Issue by skillz-xx** [nextcloud/richdocuments#1058]
**Describe the bug**
a document is shared with option to edit for a user outside of nextcloud
user opens url and gets a "Not Found
The requested URL was not found on this server."

happens since update to 3.7.2. from last version, running NC 18.0.6

**Comment by juliushaertl** [comment]
I cannot reproduce, please fill out the full issue template. 

> Not Found. The requested URL was not found on this server.

This usually indicates that the share link is not valid

**Comment by juliushaertl** [comment]
Fixed with #1061

**Comment by skillz-xx** [comment]
ok super, when will this be available as an update for the plugin in nextcloud?
