### ISSUE TITLE
Active document without input jumps back to abslute Home position after 2:25 min

### ISSUE THREAD

**Issue by RuudschMaHinda** [nextcloud/richdocuments#106]
Whenever I just read through a document after 2 minutes and about 25 seconds the cursor jumps back to the very top left position (like hitting CTRL+Home). This only happens when there is no input at all. Scrolling is enough to prevent that. But sometimes you are just too focused on reading and suddenly you jump from page 42 back to page 1. The time is pretty consistent as well.

This can get pretty annoying when just looking over a document someone wrote.

May be related:
https://bugs.documentfoundation.org/show_bug.cgi?id=108713

**Comment by thebearon** [comment]
Is there anything that could be relevant in the logs/browser console? The linked issue could've been something else, and it seems to be hard to reproduce.

**Comment by RuudschMaHinda** [comment]
I made a short [Video](https://steinibox.de/index.php/s/sBFuwntFkPHzhG2) of it. The share will be gone on sunday automatically.

The first 6 minutes everything works fine. No jumping back to top left. But then I stop moving the cursor (imagine getting a phone call, or a colleague coming in to talk) and at around 6:40 the connection gets reestablished and boom: absolute home.

At around 7 minutes I open the console, well the network tab at first. The console can be seen at 7:40 and not shortly after at 8:35 it again reconnects and jumps back to the top.

I updated to the latest CODE docker image only minutes before making this video. It seems like, as soon as there is no input, it only takes a short while for it to do this.

**Comment by thebearon** [comment]
Hm... what seems to be happening is that the server disconnects you, and the client reconnects right away. There is a timeout for inactive sessions, but that is 1 hour or so.
It would be interesting to see the docker logs (for service loolwsd), but first in /etc/loolwsd/loolwsd.xml the log level should be increased to "trace".
Logs from the close proximity of this event should be enough.
