### ISSUE TITLE
Error opening shared file with collabora while loged in nextcloud 

### ISSUE THREAD

**Issue by SiJux** [nextcloud/richdocuments#1062]
When you share odt-files per share link with other Users in the same nextcloud and they are opening the link while their are logged in with their user in nextcloud the following error-message occurs in collabora when collabora try to open the file:
"Failed to read document from storage. Please contact your storage server () administrator."
The workaround for this problem is now to log out from the nextcloud and then open the shared file per share link again.

Steps to reproduce:

1. You need nextcloud with collabora
2. Generate odt-File in collabora and save it in nextcloud
3. Generate share link for this document
4. Log in with another User and open the shared link
5. now collabora is opening in the browser and you can see the error-message

We are using nextcloud 18.0.3 with collabora online 3.5.2 and on the collabora server we are using loolwsd 4.0.11 (git hash: ff7fc02) and Collabora Office 6.0-29 (git hash: 5c5e764). We can also reproduce the problem while using nextcloud 18.0.4 with Collabora Online 3.5.2 and on the collabora server loolwsd 4.2.3 (git hash: 6144a6c) and Collabora Office 6.2-12 (git hash: 8dce0b1). We can reproduce it with different nextcloud and collabora versions on different setups.

This is an error message i found in the loolwsd.log when i open the share-link:
...
_wsd-01052-08644 2020-06-25 13:47:27.419792 [ docbroker_105 ] ERR  WOPI::CheckFileInfo failed with 403 Forbidden| wsd/Storage.cpp:495
wsd-01052-08644 2020-06-25 13:47:27.420190 [ docbroker_105 ] ERR  loading document exception: WOPI::CheckFileInfo failed| wsd/DocumentBroker.cpp:1194
wsd-01052-08644 2020-06-25 13:47:27.420366 [ docbroker_105 ] ERR  Failed to add session to [/index.php/apps/richdocuments/wopi/files/124601_ocfbc9c1eac3] with URI [https://<nextcloud>.de/index.php/apps/richdocuments/wopi/files/124601_ocfbc9c1eac3?access_token=oYiyRu4u0HUlmecYdRo3IWopZMRBT2N6&access_token_ttl=0&reuse_cookies=_ga%3DGA1.2.344845106.1571221565%3Aexperimentation_subject_id%3DIjlhNDliMWYxLTExNjktNDZiOS1iMmFmLTVmZDU1YWZjMWQxNCI%3D--4d826c3acdcb7537c8c24eee4d722a21d1309225%3Aajs_user_id%3D%22dbazkhxsntymtpiwtqq5u1tooe%22%3Aajs_group_id%3Dnull%3Aajs_anonymous_id%3D%2200000000000000000000000000%22&permission=edit]: WOPI::CheckFileInfo failed| wsd/DocumentBroker.cpp:1156
wsd-01052-08644 2020-06-25 13:47:27.420772 [ docbroker_105 ] WRN  Child session [12ce] not found to forward message: load url=https://<nextcloud>.de/index.php/apps/richdocuments/wopi/files/124601_ocfbc9c1eac3?access_token=oYiyRu4u0HUlmecYdRo3IWopZMRBT2N6&access_token_ttl=0&reuse_cookies=_ga%3DGA1.2.344845106.1571221565%3Aexperimentation_subject_id%3DIjlhNDliMWYxLTExNjktNDZiOS1iMmFmLTVmZDU1YWZjMWQxNCI%3D--4d826c3acdcb7537c8c24eee4d722a21d1309225%3Aajs_user_id%3D%22dbazkhxsntymtpiwtqq5u1tooe%22%3Aajs_group_id%3Dnull%3Aajs_anonymous_id%3D%2200000000000000000000000000%22&permission=edit readonly=0 lang=en-de| wsd/DocumentBroker.cpp:1809
kit-08295-01289 2020-06-25 13:47:29.421792 [ kit_spare_105 ] WRN  Setting TerminationFlag due to 'exit' command from parent.| kit/Kit.cpp:2081
kit-08295-01289 2020-06-25 13:47:29.421949 [ kit_spare_105 ] WRN  Kit connection lost without exit arriving from wsd. Setting TerminationFlag| kit/Kit.cpp:2117
wsd-01052-08644 2020-06-25 13:47:27.424274 [ docbroker_105 ] ERR  Invalid or unknown session [12ce] to remove.| wsd/DocumentBroker.cpp:1230_
...

**Comment by juliushaertl** [comment]
> collabora online 3.5.2 

Please update to the latest release
