### ISSUE TITLE
"Not Found" when editing a shared document

### ISSUE THREAD

**Issue by Linuxfabrik** [nextcloud/richdocuments#1063]
**Describe the bug**
Editing a document shared via a share link fails with:
```
Not Found.
The requested URL /index.php/apps/richdocuments/''WOPISrc=https://nextcloud.example.com/index.php/apps/richdocuments/wopi/files/53434_ocx06m725up&title=test.odt&lang=en&closebutton=1&revisionhistory=1 was not found on this server.
```
The problem did not occur with the richdocuments app version 3.7.0.

**To Reproduce**
1. Create a new document when logged in.
2. Share the document (or the folder containing that document) via share link with the `Allow upload and editing` option.
3. Log out.
4. Try to edit the document using the share link.

**Expected behavior**
The document should be opened for editing.

**Client details:**
 - OS: Fedora 32
 - Browser: Firefox 
 - Version: 77.0.1
 - Device: Desktop

## Server details

**Operating system**: CentOS 7

**Web server:** Apache HTTPd 2.4.6 (running behind an Apache HTTPd reverse proxy)

**Database:** MariaDB 10.3.23

**PHP version:** PHP 7.3.19

**Nextcloud version:** 18.0.6

**Version of the richdocuments app** 3.7.2

**Version of Collabora Online** loolwsd 4.2.4, collaboraoffice6.0 6.0.10.29-20191127

**Comment by MAT-WEISS-2017** [comment]
Same here, after updating to richdocuments app version 3.7.2.

Downgrade to 3.7.0 solves the problem.

**Comment by luceole** [comment]
I confirm !

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/richdocuments/releases/tag/v3.7.3
