### ISSUE TITLE
richdocuments stop working after version 3.5.3

### ISSUE THREAD

**Issue by rpelissi** [nextcloud/richdocuments#1065]
**Describe the bug**
Hi,
I have nextcloud 18.0.6 and latest version with richdocuments/collabora installed.
I have collabora setup as a workload in rancher. I have a valid let's encrypt certificate. If I update richdocument to a version higher than 3.5.3, I always have the same issue:
Opening a document lead to having an error message:
"Collabora Online is not setup yet.
Click here to configure your own server or connect to a demo server.
"
If I go to the collabora setting I see the error "Impossible d'établir la connexion au serveur Collabora Online." (Sorry it's in french)
If I try to do to the setup and click on the save button, then all is green but I will got the same issue as soon as I try to open a document

So in order to have it working, I do
- wget  https://github.com/nextcloud/richdocuments/releases/download/v3.5.3/richdocuments.tar.gz
- cd  <nextcloud>/apps
- sudo -u apache php /www/html/prod/nextcloud/occ app:remove richdocuments
- tar xzvf richdocuments.tar.gz
- chown -R apache:apache richdocuments
- sudo -u apache php /www/html/prod/nextcloud/occ app:enable richdocuments

After that everything works as expected

**To Reproduce**
1. Install nextcloud 18.0.6 with collabora latest plugin
2. Install rancher and setup a workload for collaroba
3. Opening a document fails
4. Go back to version 3.5.3, it works

**Expected behavior**
IT should still works after version 3.5.3

**Screenshots**

**Client details:**
 - OS: Windows, all browsers

## Server details

**Operating system**:
Centos 7.8.2003

**Web server:**
Apache 2.4.6
Nginx 1.16.1 as reverse proxy

**Database:**
Madiadb

**PHP version:**
7.4.6

**Nextcloud version:**
18.0.6

**Version of the richdocuments app**
3.7.3

**Version of Collabora Online**
6.2-16
<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
No logs in nextcloud.log are showing during the issue
```

nginx reverse proxy logs:
xx.xx.7.7 - - [26/Jun/2020:23:06:02 +0000] "POST /nextcloud/apps/text/session/sync HTTP/1.1" 200 482 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:07 +0000] "POST /nextcloud/apps/text/session/sync HTTP/1.1" 200 482 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:10 +0000] "GET /nextcloud/settings/admin/richdocuments HTTP/1.1" 200 42238 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - user.user [26/Jun/2020:23:06:11 +0000] "PROPFIND /nextcloud/remote.php/dav/files/user.user/ HTTP/1.1" 207 407 "-" "Mozilla/5.0 (Windows) mirall/2.6.4stable-Win64 (build 20200303) (Nextcloud)"
xx.xx.7.7 - - [26/Jun/2020:23:06:11 +0000] "GET /nextcloud/css/icons/icons-vars.css?v=1592885448 HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:12 +0000] "GET /nextcloud/avatar/user.user/32?v=0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:12 +0000] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1242 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:13 +0000] "GET /nextcloud/apps/passman/api/v2/settings HTTP/1.1" 200 243 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:13 +0000] "GET /nextcloud/apps/passman/admin/delete-requests HTTP/1.1" 200 2 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.6.2 - - [26/Jun/2020:23:06:16 +0000] "GET /hosting/discovery HTTP/1.1" 200 19734 "-" "Nextcloud Server Crawler"
xx.xx.6.2 - - [26/Jun/2020:23:06:16 +0000] "GET /hosting/capabilities HTTP/1.1" 404 153 "-" "Nextcloud Server Crawler"
xx.xx.7.7 - - [26/Jun/2020:23:06:16 +0000] "POST /nextcloud/index.php/apps/richdocuments/ajax/admin.php HTTP/1.1" 200 57 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:22 +0000] "GET /nextcloud/apps/files/ HTTP/1.1" 200 62383 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:23 +0000] "GET /nextcloud/apps/files_rightclick/css/app.css?v=5e585c9e-2 HTTP/1.1" 200 412 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:23 +0000] "GET /nextcloud/apps/ocr/css/chunk-common.css?v=5788d967-2 HTTP/1.1" 200 3809 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:23 +0000] "GET /nextcloud/apps/ocr/css/chunk-app-vendors.css?v=5788d967-2 HTTP/1.1" 200 7585 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:23 +0000] "GET /nextcloud/apps/ocr/css/app.css?v=5788d967-2 HTTP/1.1" 200 1107 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:23 +0000] "GET /nextcloud/apps/files_markdown/css/preview.css?v=70e2b24f-2 HTTP/1.1" 200 9352 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:23 +0000] "GET /nextcloud/apps/files_markdown/build/styles.css?v=70e2b24f-2 HTTP/1.1" 200 23670 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:23 +0000] "GET /nextcloud/css/text/d233-d276-icons.css?v=90939b40f7b2512e17c84ec2f91d86ed-d233662f-2 HTTP/1.1" 200 417 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"

xx.xx.7.7 - - [26/Jun/2020:23:06:23 +0000] "GET /nextcloud/css/files_sharing/c5f2-d276-icons.css?v=90939b40f7b2512e17c84ec2f91d86ed-c5f24915-2 HTTP/1.1" 200 102 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:23 +0000] "GET /nextcloud/css/activity/6c1e-d276-style.css?v=90939b40f7b2512e17c84ec2f91d86ed-6c1e7ede-2 HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:23 +0000] "GET /nextcloud/apps/recommendations/l10n/fr.js?v=e628fdb4-2 HTTP/1.1" 200 606 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:24 +0000] "GET /nextcloud/avatar/user.user/32?v=0 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:24 +0000] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1242 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:25 +0000] "PROPFIND /nextcloud/remote.php/dav/files/user.user/ HTTP/1.1" 207 13069 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:25 +0000] "GET /nextcloud/ocs/v2.php/apps/text/workspace?path=%2F HTTP/1.1" 200 167 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:25 +0000] "GET /nextcloud/apps/systemtags/lastused HTTP/1.1" 200 2 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:25 +0000] "GET /nextcloud/apps/ocr/api/personal/languages HTTP/1.1" 200 7 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:25 +0000] "GET /nextcloud/index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 234 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:25 +0000] "GET /nextcloud/apps/recommendations/api/recommendations HTTP/1.1" 200 1485 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:25 +0000] "GET /nextcloud/ocs/v1.php/apps/files_external/api/v1/mounts?format=json HTTP/1.1" 200 108 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:26 +0000] "GET /nextcloud/core/preview?fileId=3372&c=5538580e083460f0ae52cc03558b7912&x=250&y=250&forceIcon=0 HTTP/1.1" 404 2 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:27 +0000] "GET /nextcloud/apps/theming/icon/files?v=2 HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:27 +0000] "GET /nextcloud/apps/theming/favicon/files?v=2 HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:27 +0000] "GET /nextcloud/apps/text/session/create?fileId=3372&guestName=null&forceRecreate=false HTTP/1.1" 200 373 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:28 +0000] "GET /nextcloud/apps/text/session/fetch?documentId=3372&sessionId=16&sessionToken=bCntqr1qQish9%2FFp8C1n8z5Pj4f%2FYqNK5Te9DMdHfkvu%2Fe96BulIeP4uRM60eJl7 HTTP/1.1" 200 1 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"
xx.xx.7.7 - - [26/Jun/2020:23:06:29 +0000] "POST /nextcloud/apps/text/session/sync HTTP/1.1" 200 626 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0

Apache logs
xx.xx.2.30 - - [26/Jun/2020:17:07:40 -0600] "POST /nextcloud/apps/text/session/sync HTTP/1.0" 200 626
xx.xx.2.30 - - [26/Jun/2020:17:07:45 -0600] "POST /nextcloud/apps/text/session/sync HTTP/1.0" 200 626
xx.xx.2.30 - user.user [26/Jun/2020:17:07:47 -0600] "PROPFIND /nextcloud/remote.php/dav/files/user.user/ HTTP/1.0" 207 407
xx.xx.2.30 - - [26/Jun/2020:17:07:49 -0600] "GET /nextcloud/settings/admin/richdocuments HTTP/1.0" 200 42238
xx.xx.2.30 - - [26/Jun/2020:17:07:50 -0600] "GET /nextcloud/apps/theming/img/app-dark.svg HTTP/1.0" 200 611
xx.xx.2.30 - - [26/Jun/2020:17:07:51 -0600] "GET /nextcloud/avatar/user.user/32?v=0 HTTP/1.0" 304 -
xx.xx.2.30 - - [26/Jun/2020:17:07:51 -0600] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.0" 200 1242
xx.xx.2.30 - - [26/Jun/2020:17:07:51 -0600] "GET /nextcloud/apps/passman/api/v2/settings HTTP/1.0" 200 243
xx.xx.2.30 - - [26/Jun/2020:17:07:51 -0600] "GET /nextcloud/apps/passman/admin/delete-requests HTTP/1.0" 200 2
xx.xx.2.30 - - [26/Jun/2020:17:07:54 -0600] "POST /nextcloud/index.php/apps/richdocuments/ajax/admin.php HTTP/1.0" 200 57
xx.xx.2.30 - - [26/Jun/2020:17:07:57 -0600] "GET /nextcloud/apps/files/ HTTP/1.0" 200 62385
xx.xx.2.30 - - [26/Jun/2020:17:07:59 -0600] "GET /nextcloud/avatar/user.user/32?v=0 HTTP/1.0" 304 -
xx.xx.2.30 - - [26/Jun/2020:17:07:59 -0600] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.0" 200 1242
xx.xx.2.30 - - [26/Jun/2020:17:08:00 -0600] "GET /nextcloud/apps/ocr/api/personal/languages HTTP/1.0" 200 7
xx.xx.2.30 - - [26/Jun/2020:17:08:00 -0600] "PROPFIND /nextcloud/remote.php/dav/files/user.user/ HTTP/1.0" 207 13034
xx.xx.2.30 - - [26/Jun/2020:17:08:00 -0600] "GET /nextcloud/apps/systemtags/lastused HTTP/1.0" 200 2
xx.xx.2.30 - - [26/Jun/2020:17:08:00 -0600] "GET /nextcloud/ocs/v2.php/apps/text/workspace?path=%2F HTTP/1.0" 200 167
xx.xx.2.30 - - [26/Jun/2020:17:08:00 -0600] "GET /nextcloud/apps/recommendations/api/recommendations HTTP/1.0" 200 1485
xx.xx.2.30 - - [26/Jun/2020:17:08:02 -0600] "GET /nextcloud/apps/theming/icon/files?v=2 HTTP/1.0" 200 8597
xx.xx.2.30 - - [26/Jun/2020:17:08:02 -0600] "GET /nextcloud/index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.0" 200 234
xx.xx.2.30 - - [26/Jun/2020:17:08:02 -0600] "GET /nextcloud/core/preview?fileId=3372&c=5538580e083460f0ae52cc03558b7912&x=250&y=250&forceIcon=0 HTTP/1.0" 404 2
xx.xx.2.30 - - [26/Jun/2020:17:08:03 -0600] "GET /nextcloud/ocs/v1.php/apps/files_external/api/v1/mounts?format=json HTTP/1.0" 200 108
xx.xx.2.30 - - [26/Jun/2020:17:08:03 -0600] "GET /nextcloud/apps/theming/img/core/filetypes/x-office-spreadsheet.svg?v=2 HTTP/1.0" 200 327
xx.xx.2.30 - - [26/Jun/2020:17:08:03 -0600] "GET /nextcloud/apps/theming/img/core/filetypes/x-office-document.svg?v=2 HTTP/1.0" 200 295
xx.xx.2.30 - - [26/Jun/2020:17:08:04 -0600] "GET /nextcloud/core/preview?fileId=3901&x=32&y=32 HTTP/1.0" 200 5219
xx.xx.2.30 - - [26/Jun/2020:17:08:04 -0600] "GET /nextcloud/apps/text/session/create?fileId=3372&guestName=null&forceRecreate=false HTTP/1.0" 200 371
xx.xx.2.30 - - [26/Jun/2020:17:08:04 -0600] "GET /nextcloud/apps/text/session/fetch?documentId=3372&sessionId=17&sessionToken=PFbUa%2FDlASks%2B5%2BkBrdN%2ByXzhUOm8xqMW0yqsbSQ106zSs1yANbL35K6gqE%2BMyW3 HTTP/1.0" 200 1
xx.xx.2.30 - - [26/Jun/2020:17:08:04 -0600] "POST /nextcloud/apps/text/session/sync HTTP/1.0" 200 770

Here is my nginx reverse proxy config
        server {
                listen       443 ssl;
                server_name  collabora.domain.org;
    ssl_certificate /etc/letsencrypt/live/collabora.domain.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/collabora.domain.org/privkey.pem; # managed by Certbot

                # static files
                location ^~ /loleaflet {
                        proxy_pass https://xx.xx.2.9:9980;
                        proxy_set_header Host $http_host;
                }

                # WOPI discovery URL
                location ^~ /hosting/discovery {
                        proxy_pass https://xx.xx.2.9:9980;
                        proxy_set_header Host $http_host;
                }

                # main websocket
                location ~ ^/lool/(.*)/ws$ {
                        proxy_pass https://xx.xx.2.9:9980;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "Upgrade";
                        proxy_set_header Host $http_host;
                        proxy_read_timeout 36000s;
                }

                # download, presentation and image upload
                location ~ ^/lool {
                        proxy_pass https://xx.xx.2.9:9980;
                        proxy_set_header Host $http_host;
                }

                # Admin Console websocket
                location ^~ /lool/adminws {
                        proxy_pass https://xx.xx.2.9:9980;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "Upgrade";
                        proxy_set_header Host $http_host;
                        proxy_read_timeout 36000s;
                }

**Comment by halrun** [comment]
found two approaches:

Migration issue: 
Column template_id missing --> Remove richdocument tables and reinstall app:
https://github.com/nextcloud/richdocuments/issues/917

Reverse proxy configuration
Capabilities configuration in Apache/Nginx missing when using reverse proxy
https://github.com/nextcloud/richdocuments/issues/949

Second approach solved the issue for me.

**Comment by rpelissi** [comment]
Hi!
Yes! Exactly! My nginx error log show me this:

`"/usr/share/nginx/html/hosting/capabilities" failed (2: No such file or directory)`

So I have added the section
```

                # Capabilities
                location ^~ /hosting/capabilities {
                        proxy_pass https://192.168.2.9:9980;
                        proxy_set_header Host $http_host;
                }
```

To my nginx proxy and now everything is working fine!
Thanks a lot for your help!
