### ISSUE TITLE
Collabora Online is not setup yet.

### ISSUE THREAD

**Issue by chandapettie** [nextcloud/richdocuments#1070]
**Describe the bug**
Collabora was working fine until an update, now it doesn't open documents. In settings, the URL is showing "Collabora Online server is reachable"  but when I try to open a document I get the error: Collabora Online is not setup yet.

I also can't get Nextcloud to update.  My version is 15.0.2.  When I try to update, I get an error: Check for expected files, The following extra files have been found:
.rnd
CustomModifications_ReadMe.UpdateLock

Desktop version is the issue, I've tried all browsers.  It works in iOS.

**Comment by davidrei** [comment]
Same here and still an issue after upgrading to the latest version of the app.

Additional info:
On first opening the settings for the app, the connection status message says 'no connection'. Simply hitting the 'save' button next to the URL of the Collabora server changes the icon the green. Navigating away from this page and then returning to it again says 'no connection'.

**Comment by shrimpza** [comment]
I'm having the same issues, Nextcloud version 18.0.6, Collabora Online app version 3.7.3 (just updated from an older version to see if it would help), with Collabora latest (also updated from an older version to see if it would help) running in a Docker container.

The setup was working well until just recently (I don't know exactly when, I've probably updated Nextcloud between last use and now).

Not seeing any server, Nextcloud, or Collabora logs doing anything when saving the URL, or attempting to access a document. Also receiving no JS/client errors in any console logs.

**Comment by shrimpza** [comment]
Found on the Support forum at https://help.nextcloud.com/t/collabora-problem-after-upgrade-to-3-6-0/81434/19

Additional reverse proxy configuration is required for app version 3.6.0+ with Collabora hosted behind a reverse proxy, such as with Docker.

If you're using nginx:
```
    location ^~ /hosting/capabilities {
        proxy_pass https://127.0.0.1:9980;
        proxy_set_header Host $http_host;
    }
```

Apache:
```
ProxyPass           /hosting/capabilities https://127.0.0.1:9980/hosting/capabilities retry=0
ProxyPassReverse    /hosting/capabilities https://127.0.0.1:9980/hosting/capabilities
```

Adding the above new configuration to my nginx config resolved my problem.

**Comment by WNYmathGuy** [comment]
Fuk! I'm now having this problem and no solutions are clicking for me. I wasn't messing the prooxypass statements in my Apache files. I think their's something fucked up with the way Ubuntu or Virtualmin handled that `127.0.0.1` address.
