### ISSUE TITLE
Collabora does not send "loading finished"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/richdocuments#1071]
- start Android files app
- open document with Collabora
- see loading spinner

--> there is no "documentLoaded" message, so loading spinner is shown all the time…

@juliushaertl

**Comment by juliushaertl** [comment]
Works fine for me, any details in setup and version?

**Comment by tobiasKaminsky** [comment]
NC 19.0 and latest daily Android version.

**Comment by juliushaertl** [comment]
And which collabora Version? Does editing work in the Browser?

**Comment by tobiasKaminsky** [comment]
After upgrading and restarting Collabora it seems to work.
