### ISSUE TITLE
Connection with trailing slash not possible

### ISSUE THREAD

**Issue by jackadam1981** [nextcloud/richdocuments#1076]
when i run collabora/code in docker.
test in chrome or other browser，copy URL from browser,it is http://192.168.1.3:9980/

in nextcloud set requires a seperate server Should be http://192.168.1.3:9980
 

No hint  ，
No automatic processing，

Sorry, my English is not good, with the help of Google translation.

**Comment by juliushaertl** [comment]
There is no way we can automatically set the url of the collabora server as it depends on the setup. 

The installation is described in detail at https://collabora-online-for-nextcloud.readthedocs.io/en/latest/install/ If anything is unclear from that, please be a bit more precise on what we should describe more in detail.

**Comment by jackadam1981** [comment]
I mean the last slash of the URL

**Comment by juliushaertl** [comment]
Ah I see, yes we should probably just strip that trailing slash :+1:

**Comment by joshtrichards** [comment]
Fixed in #1412
