### ISSUE TITLE
Cannot display presentation with Fontwork in full screen

### ISSUE THREAD

**Issue by csware** [nextcloud/richdocuments#1084]
**Describe the bug**
Cannot display presentation with Fontwork in full screen

**To Reproduce**
1. Upload an ODP presentation which contains a fontwork object (e.g., [Fontwork.zip](https://github.com/nextcloud/richdocuments/files/4931256/Fontwork.zip))
2. Open it with Collabora
3. Click on Menu Slide and select Full Screen Presentation
4. See an XML error in Firefox

**Expected behavior**
See the presentation in full screen mode

**Client details:**
 - OS: Win 10
 - Browser Firefox
 - Version 78
 - Device:  Desktop

## Server details

**Operating system**: Debian 9

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** 7.3.20-1

**Nextcloud version:** 18.0.6

**Version of the richdocuments app** 3.7.3

**Version of Collabora Online** collaboraoffice6.2 (6.2.10.18-18)

**Comment by juliushaertl** [comment]
> See an XML error in Firefox

Can you share the error?

**Comment by csware** [comment]
Firefox network log shows me that a 0 byte file was transferred,

**Comment by thebearon** [comment]
I'm guessing this bug report should go to https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online instead, @juliushaertl, if you agree please close the issue here, and @csware, in that case please open a bug report there.

**Comment by csware** [comment]
Can't you report it upstream?

**Comment by thebearon** [comment]
Aren't you interested in following up on the issue you encountered?
On a sidenote, this repo is for the connector app between Collabora Online/LibreOffice Online, the TDF bugzilla isn't upstream to it.

**Comment by csware** [comment]
Cross-ref: https://bugs.documentfoundation.org/show_bug.cgi?id=134870

**Comment by thebearon** [comment]
Great, thank you! Let's close this one, then.
