### ISSUE TITLE
Creating document in publicly shared folder gets created in Nextcloud Root

### ISSUE THREAD

**Issue by andyboeh** [nextcloud/richdocuments#110]
### Steps to reproduce
1. Share a folder via public link
2. Create a new document in the publicly shared folder

### Expected behaviour
The new document is created and it is possible to open it

### Actual behaviour
The new document is created in the share owner's root folder, an error message (Access forbidden) is displayed.

I'm quite certain the problem is the function create() in the DocumentController.php: https://github.com/nextcloud/richdocuments/blob/master/lib/Controller/DocumentController.php#L227

**Comment by thebearon** [comment]
How do you create a document in a publicly shared folder? I can only upload file and create folder.

**Comment by andyboeh** [comment]
I click the "+"-icon as usual, the DropDown contains "Spreadsheet", "Document" and "Presentation". 

Should it not be there!? TBH, my app has this patch applied: https://github.com/nextcloud/richdocuments/pull/109 but IMHO that shouldn't affect creating new documents.

**Comment by thebearon** [comment]
Ok, I can see New Document/New Spreadsheet/New Presentation options under "+" once I'm logged in with a user, but nothing happens if I create a new of any of those. Still a bug, but seems different.
