### ISSUE TITLE
Collabora online error - ERR WOPI::CheckFileInfo failed with 302 Found| wsd/Storage.cpp:588

### ISSUE THREAD

**Issue by hermandpessek** [nextcloud/richdocuments#1103]
Hi everyone,

I am trying to add collabora online to my privation social network.
So I installed collabora online by following this tutorial. (https://www.collaboraoffice.com/code/docker/).
Because I am in development environment, I disabled ssl from both app (my web app and collabora online).

I implemented getFile and CheckFileInfo.

But when I try to access file, I got the following error.

```
wsd-00006-00078 2020-08-08 00:27:39.726353 [ docbroker_010 ] ERR  WOPI::CheckFileInfo failed with 302 Found| wsd/Storage.cpp:588
wsd-00006-00078 2020-08-08 00:27:39.726474 [ docbroker_010 ] ERR  loading document exception: WOPI::CheckFileInfo failed| wsd/DocumentBroker.cpp:1380
wsd-00006-00078 2020-08-08 00:27:39.726507 [ docbroker_010 ] ERR  Failed to add session to [/wopi/files/57] with URI [http://pessek-elggfinal338.com/wopi/files/57?access_token=hfpfrrtrtrtf1225zz%3Freuse_cookies%3Djwt%3DeyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsb29sIiwic3ViIjoiYWRtaW4iLCJhdWQiOiJhZG1pbiIsIm5tZSI6ImFkbWluIiwiZXhwIjoiMTU5NjgwNDI0NSJ9.ztD3RISaH9EdgDJFcmFPBHJYk71hSgaoz24TzhPgrey6kisuem8xw1H3prfvc0t1zcKT2H1_CZvr49H3BGq-wEjy4ENPXX3goMrQhzpQ4jQhruyxG_d9Gbl2KWsRkH-3cpBU_weTJsTf8iucgHo5jgkxVDAB1YO4X9rdNVwydR6Ux6M7_Ig3kWALcvLnDhNlka3qz-4QSxmKFf4Xw_q4UO5SRR8zA8yXfXDLJVJwES_oKLUTwV_pyExAgnY6-1UF7K-pt3jraGYDZE8G_AXQ0qdQGvG2yfojDNVBMn6rz_pMYvByB4hoiBZ1kQ7EyDR0FJj3FbPQtIdIW-ObkphRhQ]: WOPI::CheckFileInfo failed| wsd/DocumentBroker.cpp:1342
wsd-00006-00078 2020-08-08 00:27:39.726565 [ docbroker_010 ] ERR  No DocBroker found, or DocBroker marked to be destroyed. Terminating session ToClient-02c| wsd/ClientSession.cpp:330
wsd-00006-00078 2020-08-08 00:27:39.726604 [ docbroker_010 ] ERR  No DocBroker found, or DocBroker marked to be destroyed. Terminating session ToClient-02c| wsd/ClientSession.cpp:330
wsd-00006-00078 2020-08-08 00:27:39.898742 [ docbroker_010 ] ERR  Invalid or unknown session [02c] to remove.| wsd/DocumentBroker.cpp:1418
```

But when I click on the that appears on the above error file, CheckFileInfo returns the following json.

`{"BaseFileName":"Lettre de motivation.docx","OwnerId":"pessek","UserId":"49","UserFriendlyName":"Hermand Pessek","UserCanWrite":true,"UserCanNotWriteRelative":true,"UserCanRename":false,"LastModifiedTime":"2020-08-07T23:15:22+00:00","Size":6278}`

So I dont know what's is going wrong.

Could someone help me ?

regards,

**Comment by juliushaertl** [comment]
Please fill out the complete issue template. There seems to be a lot missing from the checkFileInfo response though I'm not sure what is happening there.
