### ISSUE TITLE
Input of 2-byte characters isn't correct.

### ISSUE THREAD

**Issue by Bables55** [nextcloud/richdocuments#111]
### Steps to reproduce
1. Start rich document type application of nextcloud.
2. Switch to 2-byte character input mode with iOS.
    *It seems to be normal on Android OS.
3. Enter 2-byte characters.

It is Collabora apps that it is easy for symptoms.

### Expected behaviour
Unlike English characters, double-byte character input has a correct character candidate selection operation before letters are confirmed. I will select the appropriate character from the candidate dialog and fix the character input. It is entered exactly in the application.

### Actual behaviour
There is a function of character guess conversion. When I enter the first letter I can enter a word or phrase like an operation to call a template. Even if I select the template sentence and fix the input, the characters actually input are different. Only the characters entered first will be entered.

Example: _*This is an extreme example._

String to be finally entered.:
ABCD

Double-byte character input operation:
[Conversion rules] A='ha', B='ie', C='wt', D='op'.

In order to confirm with such 2-byte character input as such, enter "haeiwtop". 
Actually, when I input the first one letter or two letters, the guess candidate is displayed and I can be selected. "haeiwtop" is displayed in the guessing candidate dialogue. I select candidate characters at this timing.

Characters to be displayed:
ha
-or-
haei

Probable cause prediction:
Ignoring this speculation candidate and entering all manually, I can input until the end.
When I express this in English it is like this.
I enter "THANK YOU".
--> T   H   A   N   K   Y   O   U 
I just wait 1 second every time I enter a single character.

The application simply does not correspond to 2-byte character area(country).
Another thing I can think of is the auto save function. Although this is not always the case, automatic saving works every time one character(2-byte) is input. This may be influenced by server performance.

### Server configuration
**Operating system**:
CentOS 7.3
**Web server:**
nginx 1.11.10
**Database:**
MariaDB 5.5.52
**PHP version:**
PHP 7.1.7
**Nextcloud version:** (see Nextcloud admin page)
12.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
nextcloud.com
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - deck: 0.2.1
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_automatedtagging: 1.2.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.4
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - richdocuments: 1.12.33
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - firstrunwizard
  - user_external
  - user_ldap```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

    "system": {
        "instanceid": "INSTANCEID",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "MYDOMAIN"
        ],
        "datadirectory": "\/var\/www\/vhosts\/NEXTCLOUD\/data",
        "overwrite.cli.url": "https:\/\/MYDOMAIN",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "DBNAME",
        "dbhost": "localhost:3306",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_type": "owncloud",
        "logfile": "nextcloud.log",
        "loglevel": "3",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "timezone": "Asia\/Tokyo",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "USER",
        "mail_domain": "DMAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "SMTP",
        "mail_smtpport": "PORTNO",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "auth.bruteforce.protection.enabled": false,
        "versions_retention_obligation": "7,auto",
        "trashbin_retention_obligation": "auto",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ]
    }
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
Encryption in app is on. Server side encryption is off.
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Safari, Chrome, iCab mobile
**Operating system:**
iOS 10.3.2, 10.3.3
### Logs
There is no error log on this.

**Comment by Bables55** [comment]
This issue is also being acclaimed even in the latest version. No matter how long I enter a sentence with double-byte characters, only one word of the first double-byte character is entered into Collabora. This is a problem with using iPhone.

**Comment by juliushaertl** [comment]
This is actually an issue of collabora. Please head over to https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online to file a bug there.

**Comment by thebearon** [comment]
The issue is reported upstram as [tdf#122329](https://bugs.documentfoundation.org/show_bug.cgi?id=122329).
