### ISSUE TITLE
Failed to load Collabora Online Development Edition - please try again later

### ISSUE THREAD

**Issue by felmey** [nextcloud/richdocuments#1124]
### Steps to reproduce
1. Click create new document
2. Select file name
3. After delay the pop up "Failed to load Collabora Online Development Edition - please try again later" appears briefly

### Expected behaviour
I expect to be able to open/edit a document

### Actual behaviour
Nothing happens and only an error message "Failed to load Collabora Online Development Edition - please try again later" pops up.

### Server configuration

**Operating system**: 
Debian 10

**Web server:**
Apache2

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 19.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**Comment by thebearon** [comment]
How did you set up Nextcloud and CODE? Are they on the same server or different servers or in containers? Are they connected directly or is there a reverse proxy in between?

**Comment by juliushaertl** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

**Comment by felmey** [comment]
> How did you set up Nextcloud and CODE? Are they on the same server or different servers or in containers? Are they connected directly or is there a reverse proxy in between?

Nextcloud and CODE are installed on the same Debian server.  CODE is installed in a docker container following the instructions on the nextcloud site.  The Nextcloud Settings>Admin>Collabora Online Development Edition area has the green circle with the check mark and "Collabora Online server is reachable." message.  But it still fails when you try to open any documents.

**Comment by felmey** [comment]
> As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

That's fine.  I was just trying to make sure someone was aware of the issue and that it isn't working.  I was just checking out the project to see if it was worthwhile using.

**Comment by juliushaertl** [comment]
> Additionally. /hosting/discovery endpoint on my collabora installation is properly reachable and returns proper xml data.

> {"convert-to":{"available":true},"hasMobileSupport":true,"hasProxyPrefix":false,"hasTemplateSaveAs":false,"hasTemplateSource":true,"productName":"Collabora Online Development Edition","productVersion":"4.2.6","productVersionHash":"ed4f732"}

Well that is not the proper data for /hosting/discovery but for /hosting/capabilities. Maybe you have some misconfiguration in your reverse proxy forwarding then.

**Comment by felmey** [comment]
> > Additionally. /hosting/discovery endpoint on my collabora installation is properly reachable and returns proper xml data.
> 
> > {"convert-to":{"available":true},"hasMobileSupport":true,"hasProxyPrefix":false,"hasTemplateSaveAs":false,"hasTemplateSource":true,"productName":"Collabora Online Development Edition","productVersion":"4.2.6","productVersionHash":"ed4f732"}
> 
> Well that is not the proper data for /hosting/discovery but for /hosting/capabilities. Maybe you have some misconfiguration in your reverse proxy forwarding then.



> > Additionally. /hosting/discovery endpoint on my collabora installation is properly reachable and returns proper xml data.
> 
> > {"convert-to":{"available":true},"hasMobileSupport":true,"hasProxyPrefix":false,"hasTemplateSaveAs":false,"hasTemplateSource":true,"productName":"Collabora Online Development Edition","productVersion":"4.2.6","productVersionHash":"ed4f732"}
> 
> Well that is not the proper data for /hosting/discovery but for /hosting/capabilities. Maybe you have some misconfiguration in your reverse proxy forwarding then.

Thanks.  I fixed the typo in the post...  It was /hosting/capabilities:

{"convert-to":{"available":false},"hasMobileSupport":true,"hasProxyPrefix":false,"hasTemplateSaveAs":false,"hasTemplateSource":true,"productName":"Collabora Online Development Edition","productVersion":"4.2.6","productVersionHash":"ed4f732"}

**Comment by felmey** [comment]
Even after updating to Collabora Online 3.7.4 this error is still present when you try to open any documents and fails with the following message:

"Failed to load Collabora Online Development Edition - please try again later"

**Comment by WindfallProphet** [comment]
Are you getting any errors in your browser log?
