### ISSUE TITLE
Default save configuration causes save issues

### ISSUE THREAD

**Issue by perillo3ro** [nextcloud/richdocuments#1132]
**Describe the bug**
When someone is editing a document, and a second person clicks on "save" button, the first person loses his changes

**To Reproduce**

-Install NextCloud
-Install Collabora
-ask 2 persons to edit the same document
-ask one of them to click "save"

**Expected behavior**
Save all changes when clicking on save

**Workarround**

insert this lines in -nextcloud location-/config/config.php :
...
'memcache.locking' => \\OC\\Memcache\\redis',
'filesystem_check_changes' => 1,
...

**Client details:**
 - Debian Linux
 - Google Chrome (firefox quantum and newer for example)
 - 75 or newer
 - Desktop PC

## Server details
Centos 8

Apache (CEntos 8 version)

php 7.2.11

NextCloud 19

Collabora Online (NC connector) 3.6.0

Collabora CODE 4.2.3

**Comment by thebearon** [comment]
> **Describe the bug**
> When someone is editing a document, and a second person clicks on "save" button, the first person loses his changes

How can this happen? The two users are editing in the same session, are they not?

**Comment by thebearon** [comment]
Yes, I'm talking about same document session, ie. both users can see each other editing the document, and I don't think it's possible that one user's edits would be lost in that case, either:
- the changes made in the session are saved, regardless of who made them, or
- if there's some strange error preventing save, no changes are saved from either of them.

**Comment by perillo3ro** [comment]
Yes, the changes saves automatically if no one touch anything and close the docs. The problem happen when the save icon (or File > Save) is clicked. I don't know why but some people tend to click that button instead of close the document, but it happened in my workplace. I know it sounds weird, but this case occurred until I added those 2 lines in the config file.
