### ISSUE TITLE
Cant connect to Collabora online

### ISSUE THREAD

**Issue by jookk** [nextcloud/richdocuments#1136]
**Describe the bug**
I have installed CODE Collabora server Nextcloud app and Collabora document server. But I cant find problem.

## Server details

**Debian buster 64bit**:

**nginx 1.19.2:**

**mariadb 10.3:**

**php7.4-fpm:**

**20b3:**

**4.2.602**

**3.7.4**

`

Error | PHP | Array to string conversion at /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#81 |  
-- | -- | -- | --

Error | PHP | simplexml_load_string():  tY2dpYz0=&quot; defer  src=&quot;/apps/files_rightclick/js/files.js?v=e6ee9715-32&quot;&gt;&lt;/script  at /var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php#43
-- | -- | --

Error | PHP | simplexml_load_string():  Entity: line 32: parser error : Specification mandates value for  attribute defer at  /var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php#43
-- | -- | --

`

**Comment by juliushaertl** [comment]
Please fill out the complete issue template

**Comment by juliushaertl** [comment]
Also the full log entries in json data would be interesting here

**Comment by jookk** [comment]
{"reqId":"l0s7YEDo4ZqcnDSLAt6w","level":3,"time":"2020-09-04T10:24:54+02:00","remoteAddr":"192.168.2.2","user":"korenisko","app":"index","method":"POST","url":"/index.php/apps/richdocuments/ajax/admin.php","message":{"Exception":"Exception","Message":"Call to a member function xpath() on bool","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"Error","Message":"Call to a member function xpath() on bool","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/richdocuments/lib/Controller/SettingsController.php","line":177,"function":"getUrlSrc","class":"OCA\\Richdocuments\\WOPI\\Parser","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"setSettings","class":"OCA\\Richdocuments\\Controller\\SettingsController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/netcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php","Line":46},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0","version":"20.0.0.5","id":"5f51f9dbe44e2"}

**Comment by juliushaertl** [comment]
Is the /hosting/discovery endpoint on your collabora installation properly reachable?

You can try using `curl https://collabora-domain/hosting/discovery' This should return some proper xml data then.

**Comment by jookk** [comment]
I didnt setup any collabora domain, I installed that two apps meaning it 
will be working out of the box

Dňa 4. septembra 2020 12:55:39 používateľ Julius Härtl 
<notifications@github.com> napísal:

**Comment by Luticus** [comment]
I'm not sure if this is related to my issue, but I figured I'd ask here before posting a new issue because it seems like it might be. I've had collabora office installed for a long time and it has worked fine up until recently. Now when I upgrade from version 3.5.x to anything 3.7.x when I click an office document it says my collabora isn't set up. When I go into settings to view the collabora settings it says "Could not establish connection to the Collabora Online server", but then if I simply click "save" without changing any settings, it says Collabora Online server is reachable and it appears to work. Unfortunately if I leave the page and try to open a document again it says it's not reachable. When I go back into the settings view, the server is apparently unreachable again. I'm not seeing anything in the logs that looks relevant to this problem, but if there's anything specific I should look for or any logs that would be helpful I'd be happy to share.

**Comment by runout-at** [comment]
same issue here, as @Luticus describes it above.

**Comment by mannp** [comment]
Same issue for me, been working great, now this issue.

My endpoints are accessable and return an XML.

I can open my collabora server and it correctly returns 'OK'.

Admin is also accessable.

Nextcloud 19.03 no longer sees it as a valid server.

**Comment by hoffie** [comment]
What @Luticus described happened to me after updating to Nextcloud v19. https://github.com/nextcloud/richdocuments/issues/1070#issuecomment-653914755 solved this for me (adding additional paths to reverse proxy config).

**Comment by Luticus** [comment]
Yep, just tested it and the fix @hoffie suggested worked out!

very specifically, in my case I used these lines in my office.example.com.conf file:
`# Endpoint with information about availability of various features
ProxyPass           /hosting/capabilities https://office.example.com:9980/hosting/capabilities retry=0
ProxyPassReverse    /hosting/capabilities https://office.example.com:9980/hosting/capabilities`

**Comment by runout-at** [comment]
for me, this **does not** solve it completely on nc19.0.4 with richdocuments 3.7.5.
but i found in the latest collabora office (loolwsd 6.4.0-7, debian 10 stable) a line in _/etc/loolwsd/loolwsd.xml_

```
      <capabilities desc="Should we require capabilities to isolate processes into chroot jails" type="bool" default="true">true</capabilities>
```

it works when i set this to **false**

maybe somebody can explain what this is for and if this is a security problem?

**Comment by juliushaertl** [comment]
I cannot see any clear bug in the app itself from the log. As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

**Comment by premiumprivacy** [comment]
Hey i know that this is closed but i have been having the same issues. Turns out it was an issue with my NGINX config. Have a look at this: https://www.collaboraoffice.com/online/connecting-collabora-online-built-in-code-server-with-nginx/
Helped me get mine up and running! It's not a Nextcloud issue
