### ISSUE TITLE
blank document and incomplete interface

### ISSUE THREAD

**Issue by gcala** [nextcloud/richdocuments#114]
Hi,
I configured nextcloud/richdocuments/collabora docker image but when opening a document I got a blank body and collabora gui is not complete, lacking a menubar and items in comboboxes:

![actual collabora online gui](http://i.imgur.com/9PfwB2D.png)

nextcloud and docker logs show no interesting output.

Do you have any idea about the problem?

This is my nextcloud.conf:

```
Alias /nextcloud "/usr/share/webapps/nextcloud"
    
<Directory /usr/share/webapps/nextcloud/>
    Options +FollowSymlinks
    AllowOverride All
    Require all granted

    <IfModule mod_dav.c>
            Dav off
    </IfModule>

    SetEnv HOME /usr/share/webapps/nextcloud
    SetEnv HTTP_HOME /usr/share/webapps/nextcloud

    php_admin_value open_basedir "/srv/http/:/usr/share/webapps/:/tmp:/dev/urandom"
</Directory>

# Encoded slashes need to be allowed
AllowEncodedSlashes NoDecode

# Container uses a unique non-signed certificate
SSLProxyEngine On
SSLProxyVerify None
SSLProxyCheckPeerCN Off
SSLProxyCheckPeerName Off

# keep the host
ProxyPreserveHost On

# static html, js, images, etc. served from loolwsd
# loleaflet is the client part of LibreOffice Online
ProxyPass           /loleaflet https://127.0.0.1:9980/loleaflet retry=0
ProxyPassReverse    /loleaflet https://127.0.0.1:9980/loleaflet

# WOPI discovery URL
ProxyPass           /hosting/discovery https://127.0.0.1:9980/hosting/discovery retry=0
ProxyPassReverse    /hosting/discovery https://127.0.0.1:9980/hosting/discovery

# Main websocket
ProxyPassMatch "/lool/(.*)/ws$" wss://127.0.0.1:9980/lool/$1/ws nocanon

# Admin Console websocket
ProxyPass   /lool/adminws wss://127.0.0.1:9980/lool/adminws

# Download as, Fullscreen presentation and Image upload operations
ProxyPass           /lool https://127.0.0.1:9980/lool
ProxyPassReverse    /lool https://127.0.0.1:9980/lool
```

this is the command for docker image

```
docker run -t -d -p 127.0.0.1:9980:9980 -e 'domain=mysite\.it' --net host --restart always --cap-add MKNOD collabora/code
```

### General server configuration

**Operating system:** Linux vps315875.ovh.net 4.12.4-1-ARCH #1 SMP PREEMPT Fri Jul 28 18:54:18 UTC 2017 x86_64

**Web server:** Apache/2.4.27 (Unix) OpenSSL/1.1.0f PHP/7.1.8 mod_wsgi/4.5.17 Python/3.6 (apache2handler)

**Database:** mysql 10.1.25

**PHP version:** 7.1.8
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - ctype
 - dom
 - fileinfo
 - filter
 - hash
 - json
 - mbstring
 - SPL
 - PDO
 - bz2
 - posix
 - Reflection
 - session
 - SimpleXML
 - standard
 - tokenizer
 - xml
 - xmlreader
 - xmlwriter
 - mysqlnd
 - apache2handler
 - bcmath
 - Phar
 - curl
 - exif
 - gd
 - gettext
 - iconv
 - intl
 - mcrypt
 - mysqli
 - pdo_mysql
 - soap
 - tidy
 - xmlrpc
 - zip
 - apcu
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.1 - 12.0.1.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from an older Nextcloud

**Where did you install Nextcloud from:**  archlinux repository

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OC\Files\Storage\DAV
    [2] => \OCA\Files_External\Lib\Storage\OwnCloud
    [3] => \OCA\Files_External\Lib\Storage\SFTP
    [4] => \OCA\Files_External\Lib\Storage\AmazonS3
    [5] => \OCA\Files_External\Lib\Storage\Dropbox
    [6] => \OCA\Files_External\Lib\Storage\Google
    [7] => \OCA\Files_External\Lib\Storage\Swift
    [8] => \OCA\Files_External\Lib\Storage\SFTP
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** YOUR ANSWER HERE (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - deck: 0.2.1
 - encryption: 1.6.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_external: 1.3.0
 - files_markdown: 1.0.1
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - news: 11.0.5
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - passman: 2.1.4
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - richdocuments: 1.12.34
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - audioplayer
 - bookmarks
 - notes
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "ocyavvfi0fb0",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "cuteworks.it"
    ],
    "datadirectory": "\/usr\/share\/webapps\/nextcloud\/data",
    "overwrite.cli.url": "http:\/\/localhost\/nextcloud",
    "dbtype": "mysql",
    "version": "12.0.1.5",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "loglevel": 2,
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "appstore.experimental.enabled": true
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Operating system:** YOUR ANSWER HERE

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by jonabasque** [comment]
**Hi, I have a some problem.** 

**I have checked the Nextcloud log and I do not see any problem, however in the proxy log (Nginx) I see that I receive an error 400 in the following request:**

93.59.45.238 - - [27/Dec/2017:20:52:53 +0000] “GET /lool/https%3A%2F%2Fcloud.mydomain.foo%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F42_ociq0wuinnaa%3Faccess_token%3DlfVzC4H6skhX4pHGt95NtF62qkSNyXwT%26access_token_ttl%3D0%26permission%3Dedit/ws?WOPISrc=https%3A%2F%2Fcloud.mydomain.foo%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F42_ociq0wuinnaa&compat=/ws HTTP/1.1” **400** 0 “-” “Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0” “-”

Browser console (in spanish sorry):

- JQMIGRATE:  Migrate is installed, version 1.4.0 core.js:7:542
- JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
- Deprecation warning: tipsy is deprecated. Use tooltip instead.
- Waiting for page to render…
- Content Security Policy: Se ignora ‘x-frame-options’ por la directiva ‘frame-ancestors’.
- Content Security Policy: La directiva 'frame-src' está desaprobada. Use la directiva 'child-src' en su lugar.
- Un XMLHttpRequest síncrono en el hilo principal está desaprobado por sus efectos negativos en la experiencia del usuario final. Para más ayuda vea  http://xhr.spec.whatwg.org/
bundle.js:55742:1
- Content Security Policy: Se ignora ‘x-frame-options’ por la directiva ‘frame-ancestors’.
- Firefox no puede establecer una conexión con el servidor en wss://collabora.mydomain.foo/lool/https%3A%2F%2Fcloud.mydomain.foo%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F546_ociq0wuinnaa%3Faccess_token%3Dkiywkbez0b7NY4Lz2aFrIDHI3dT5bCiY%26access_token_ttl%3D0%26permission%3Dedit/ws?WOPISrc=https%3A%2F%2Fcloud.mydomain.foo%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F546_ociq0wuinnaa&**compat=/ws**.
- Error en el mapeo fuente: request failed with status 404
- URL del recurso: https://cloud.mydomain.foo/core/vendor/core.js?v=10ec3e233002881fc4f9182d4661272e-4
- URL del mapa fuente: purify.min.js.map

I am testing the same request from the browser and I get the same:

https://collabora.mydomain.foo/lool/https://cloud.mydomain.foo/index.php/apps/richdocuments/wopi/files/42_ociq0wuinnaa?access_token=84pSYvq8ajtiu3QosvWhjpKU0vNGqlIT&access_token_ttl=0&permission=edit/ws?WOPISrc=https://cloud.mydomain.foo/index.php/apps/richdocuments/wopi/files/42_ociq0wuinnaa&**compat=/ws**

**Comment by jonabasque** [comment]
**I think that I have the same problem:**

**I checked the Nextcloud log and everything goes fine and the proxy (Nginx) shows an error 400 in the following request:**

93.59.45.238 - - [27/Dec/2017:20:52:53 +0000] “GET /lool/https%3A%2F%2Fcloud.mydomain.foo%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F42_ociq0wuinnaa%3Faccess_token%3DlfVzC4H6skhX4pHGt95NtF62qkSNyXwT%26access_token_ttl%3D0%26permission%3Dedit/ws?WOPISrc=https%3A%2F%2Fcloud.mydomain.foo%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F42_ociq0wuinnaa&compat=/ws HTTP/1.1” 400 0 “-” “Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0” “-”

**Maybe the browser log can tell us something.**
When the files are ready:

- Content Security Policy: La directiva 'frame-src' está desaprobada. Use la directiva 'child-src' en su lugar.
- JQMIGRATE: Migrate is installed, version 1.4.0
- Error en el mapeo fuente: request failed with status 404 
URL del recurso: https://cloud.mydomain.foo/core/vendor/core.js?v=10ec3e233002881fc4f9182d4661272e-4
URL del mapa fuente: purify.min.js.map
- window.controllers/Controllers está desaprobado. No lo use para detectar el agente de usuario.
- Ha fallado la carga del <script> con origen "https://1480876790.rsc.cdn77.org/172d0221a49352fdb1.js".
- Content Security Policy: Las opciones para esta página han bloqueado la carga de un recurso en https://1480876790.rsc.cdn77.org/172d0221a49352fdb1.js (script-src 'nonce-T2JHajE3ZE9oTGIzc1gvVHJiUks2WkNpQlVyWFduVFVhRkNYWFNXRWVocz06VmYvc285RUs5OSsreFNxeDUrQWhyK2FRWFR1VU16YXNIZ0hUZG5IdU1Faz0=' 'unsafe-eval').

When I try to open a file:

- Content Security Policy: Ingrando "'unsafe-inline'" en script-src o style-src: se ha especificado nonce-source o hash-source
- Content Security Policy: La directiva 'frame-src' está desaprobada. Use la directiva 'child-src' en su lugar.
- JQMIGRATE: Migrate is installed, version 1.4.0
- Deprecation warning: tipsy is deprecated. Use tooltip instead.
- Waiting for page to render…
- Content Security Policy: Se ignora ‘x-frame-options’ por la directiva ‘frame-ancestors’.
- Content Security Policy: La directiva 'frame-src' está desaprobada. Use la directiva 'child-src' en su lugar.
- Un XMLHttpRequest síncrono en el hilo principal está desaprobado por sus efectos negativos en la experiencia del usuario final. Para más ayuda vea  http://xhr.spec.whatwg.org/
- Content Security Policy: Se ignora ‘x-frame-options’ por la directiva ‘frame-ancestors’.
- Firefox no puede establecer una conexión con el servidor en wss://collabora.mydomain.foo/lool/https%3A%2F%2Fcloud.mydomain.foo%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F546_ociq0wuinnaa%3Faccess_token%3DxRMqyXvjCp8rlKsjuW2F3dMmcqt0C47E%26access_token_ttl%3D0%26permission%3Dedit/ws?WOPISrc=https%3A%2F%2Fcloud.mydomain.foo%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F546_ociq0wuinnaa&compat=/ws.

**Comment by jonabasque** [comment]
This is the image of the last log, which shows me that the error is in the construction of the "socket" object.

![error-consola-browser](https://user-images.githubusercontent.com/1707606/34544426-7b304cec-f0e6-11e7-995f-3c2e668fdf97.png)
d.

Is it possible that the route is forming badly as I say in the previous message?

Does anyone know what the route should be like? I can not find the loolwsd code repository or its documentation to understand how the route should be create

Can someone help us with this?

Thanks

**Comment by jonabasque** [comment]
@gcala Have you been able to solve the problem?

you have the same problem as me in the browser ?

regards

**Comment by gcala** [comment]
@jonabasque unfortunately it is still not working...

**Comment by thebearon** [comment]
If anyone's encountering no or incomplete UI, check the browser console logs. @jonabasque's logs are telling me there's a problem setting up the websocket connection between the browsers and Collabora Online server. This seems to be an issue with the setup, and not with the software itself.
