### ISSUE TITLE
Nextcloud does not open Collabora (LibreOffice) files

### ISSUE THREAD

**Issue by Night-Train-666** [nextcloud/richdocuments#1148]
Hi Guys,

I have a Nextcloud installation on Ubuntu Server in Virtualbox and everything worked perfectly.

Now I have decided to add Collabora to test file sharing.

I added the Docker repositories, installed the collabora/code container, suitably modified the Nginx server configuration and added the richdocuments app.

Software versions:
- Ubuntu 20.04.1 LTS
- Nginx 1.19.2-1
- Nextcloud 19.0.2.2
- Richdocuments 3.7.3
- Docker 19.03.12, build 48a66213fe
("DockerVersion": "19.03.11")
- Collaboraoffice 4.2.5
(Loolwsd version details: 4.2.6 - ed4f732 - id 60aaaaaa - on "Ubuntu 18.04.1 LTS"| wsd/LOOLWSD.cpp:3664)

Now I keep accessing my documents, I can create folders and all types of files, but I can open all types of files except LibreOffice (odt, ods, etc.)

When I try to open a LibreOffice document (odt, ods, etc.) I get the message: failed to read document from storage ...

In the Nextcloud log I only see this:
(see file)
log-nextcloud

I also attach the docker/collabora logs:
(see files)
- when starting the virtual machine --> log-collabora-open
- after trying to open LibreOffice files --> log-collabora-open-document-libreoffice

How can I find a solution?

Many thanks

**Comment by juliushaertl** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

There is most likely an issue connecting from your Collabora instance back to the Nextcloud server.

**Comment by Night-Train-666** [comment]
Hi Julius,
You were right, it was a configuration problem.
The solution is posted here:
https://help.nextcloud.com/t/solved-nextcloud-does-not-open-collabora-libreoffice-files/91373
Thanks again.
