### ISSUE TITLE
Cannot create new OOXML document

### ISSUE THREAD

**Issue by haffmans** [nextcloud/richdocuments#118]
Using the NextCloud Docker image, if the "Use OOXML by default for new files" setting is enabled, creating new rich documents fails. It seems some configuration for the templates is wrong, given this error on the Nextcloud log:

> file_get_contents(apps/richdocuments/assets/docxtemplate.docx): failed to open stream: No such file or directory at /var/www/html/lib/private/Files/Type/TemplateManager.php#57
> file_get_contents(/var/www/html/custom_apps/richdocuments/lib/assets/odttemplate.odt): failed to open stream: No such file or directory at /var/www/html/custom_apps/richdocuments/lib/Controller/DocumentController.php#272

I checked and the docxtemplate.docx file does exist. However, the app is installed in /var/www/html/custom_apps/ and it seems to be looking at 'apps' (instead of custom_apps) first.

After disabling "Use OOXML by default for new files" creating ODF documents works fine.

### Steps to reproduce
1. Set up NextCloud(+Collabora) in a Docker environment
2. Install richdocuments through the Apps interface, this installs it to the custom_apps directory
2. Check "Use OOXML by default for new files" setting
3. In the Files app, try to create a new rich text document (docx)

### Expected behaviour
A file with the given name should be created in the current directory.

### Actual behaviour
No file is created and mentioned logs appear in the NextCloud log.

### Server configuration
**Operating system**: Ubuntu 16.04 / Docker 17.06.1-ce
**Web server:** nginx 1.13
**Database:** MariaDB 10.2.8
**PHP version:** 7.1.8 (bundled in Docker image)
**Nextcloud version:** 12.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:** Database+data updated from ancient ownCloud install, to NextCloud 9 on to the current version. Application code retrieved using Docker image.

**Where did you install Nextcloud from:** nextcloud:fpm Docker image

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
```
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - admin_notifications: 1.0.0
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.4
  - checksum: 0.3.5
  - contacts: 1.5.3
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_markdown: 2.0.0
  - files_opds: 0.8.2
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 11.0.5
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - qownnotesapi: 17.5.0
  - richdocuments: 1.12.34
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_email: 1.0.1
  - socialsharing_facebook: 1.0.1
  - socialsharing_twitter: 1.0.1
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - comments
  - survey_client
  - templateeditor
  - user_external
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "installed": true,
        "dbtype": "mysql",
        "dbname": "***REMOVED***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "mariadb",
        "dbtableprefix": "nc_",
        "forcessl": true,
        "theme": "",
        "3rdpartyroot": "",
        "3rdpartyurl": "",
        "defaultapp": "files",
        "appstoreenabled": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED***",
        "appcodechecker": "",
        "log_type": "owncloud",
        "logfile": "\/var\/www\/html\/data\/nextcloud.log",
        "loglevel": 1,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "updatechecker": true,
        "writable_appsdir": false,
        "datadirectory": "\/var\/www\/html\/data",
        "version": "12.0.2.0",
        "instanceid": "510d7f224671c",
        "ldapIgnoreNamingRules": false,
        "trusted_domains": [***REMOVED*** ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Shared",
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "mail_from_address": "***REMOVED***",
        "mail_domain": "***REMOVED***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "redis",
            "port": 6379
        },
        "updater.release.channel": "stable",
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Epub",
            "OC\\Preview\\PDF"
        ],
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "overwrite.cli.url": "***REMOVED***",
        "mysql.utf8mb4": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "mail_smtpauthtype": "LOGIN",
        "trusted_proxies": [
        ]
    }
}

```
</details>

**Are you using external storage, if yes which one:** local only

**Are you using encryption:** no file encryption

### Client configuration
**Browser:** Firefox 55.0.3
**Operating system:** Arch Linux

#### Web server error log
<details>
<summary>Web server error log</summary>
```
172.16.122.240 - - [12/Sep/2017:22:21:09 +0000] "POST /index.php/apps/richdocuments/ajax/documents/create HTTP/1.1" 200 52 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
file_get_contents(apps/richdocuments/assets/docxtemplate.docx): failed to open stream: No such file or directory at /var/www/html/lib/private/Files/Type/TemplateManager.php#57
file_get_contents(/var/www/html/custom_apps/richdocuments/lib/assets/odttemplate.odt): failed to open stream: No such file or directory at /var/www/html/custom_apps/richdocuments/lib/Controller/DocumentController.php#272
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Response body of create request (Status 200):
{"status":"error","message":"Can't create document"}

```
</details>

**Comment by DerFetzer** [comment]
I have exactly the same problem.

**Comment by haffmans** [comment]
@DerFetzer I changed the settings to use ODF for new documents instead of OOXML, that works fine as posted in the original comment.

**Comment by DerFetzer** [comment]
Thank you very much! Now I realized that you can create OOXML-files with ODF as default, too.

**Comment by Gymnae** [comment]
Facing the same issue
