### ISSUE TITLE
Collabora app install : occ commands are not enough, GUI must be used to activate config

### ISSUE THREAD

**Issue by mmallejac** [nextcloud/richdocuments#1181]
**Describe the bug**

**To Reproduce**
1. use occ commands to install and configure richdocuments : 
```
php occ app:install richdocuments
php occ config:app:set richdocuments public_wopi_url --value="https://ourCollaboraServer"
php occ config:app:set richdocuments wopi_url --value="https://ourCollaboraServer"
php occ config:app:set richdocuments enabled --value="yes"
```
2. try to open a file : it doesn't work ("Collabora Online is not setup yet. Click here to configure your own server or connect to a demo server.✖")
3. go to Settings, Collabora Online, an error message shows "Could not establish connection to the Collabora Online server."
4. just click Save, message turns to "Collabora Online server is reachable."
4. now working good !

**Expected behavior**
Collabora is setup and working without clicking Save, oly with `occ`commands

## Server details

**Operating system**: Debian GNU/Linux 10

**Web server:** Apache

**Database:** official Mariadb Docker image `mariadb:10.4`

**PHP version:** : 7.4.10

**Nextcloud version:** 19.0.3

**Version of the richdocuments app** 3.7.4

**Version of Collabora Online** 6.2-25

**Comment by juliushaertl** [comment]
This will be possible with the next release through https://github.com/nextcloud/richdocuments/pull/1137
