### ISSUE TITLE
scripted configuration

### ISSUE THREAD

**Issue by schiessle** [nextcloud/richdocuments#1196]
I would like to automate the configuration of the rich documents app with a script. Right now I do the following:

````
occ config:app:set --value "https://my-collabora-server.com" richdocuments wopi_url
occ config:app:set --value "https://my-collabora-server.com" richdocuments public_wopi_url
````

Looking at the database everything looks like when I configure it manually:

````
+---------------+-------------------+------------------------------------------+
| appid         | configkey         | configvalue                              |
+---------------+-------------------+------------------------------------------+
| richdocuments | enabled           | yes                                      |
| richdocuments | installed_version | 3.7.4                                    |
| richdocuments | public_wopi_url   | https://my-collabora-server.com          |
| richdocuments | types             | filesystem,dav,prevent_group_restriction |
| richdocuments | wopi_url          | https://my-collabora-server.com          |
+---------------+-------------------+------------------------------------------+
````

But when I try to open a document with Nextcloud I get this error message:

> Collabora Online is not setup yet.
> Click here to configure your own server or connect to a demo server.

Looking at the settings I see:

![image](https://user-images.githubusercontent.com/1589737/95988749-a505c980-0e29-11eb-8255-b0e0fd0db080.png)

Once I press the save button it changes to green and Collabora works.

But the database entries still look exactly the same

````
+---------------+-------------------+------------------------------------------+
| appid         | configkey         | configvalue                              |
+---------------+-------------------+------------------------------------------+
| richdocuments | enabled           | yes                                      |
| richdocuments | installed_version | 3.7.4                                    |
| richdocuments | public_wopi_url   | https://my-collabora-server.com          |
| richdocuments | types             | filesystem,dav,prevent_group_restriction |
| richdocuments | wopi_url          | https://my-collabora-server.com          |
+---------------+-------------------+------------------------------------------+
````

Is there something else I need to set outside of the oc_appconfig table?

**Comment by juliushaertl** [comment]
We will have an `occ richdocuments:activate-config` command with the maintenance release I'm just preparing to make sure that manual config changes can be applied properly by invalidating caches.

**Comment by juliushaertl** [comment]
Release is out.

**Comment by schiessle** [comment]
Just tested it... Works great! :+1:  Thanks a lot for the super quick update @juliushaertl :smiley:
