### ISSUE TITLE
Edit PDFs support

### ISSUE THREAD

**Issue by HLFH** [nextcloud/richdocuments#120]
Hi,

Two years ago, PDF support [has been dropped](https://github.com/nextcloud/richdocuments/commit/8010839279610c598f33b17e3b299acb15809b05) from `richdocuments` in favour of `PDF.js` own Nextcloud implementation.

PDF editing is out of scope within `PDF.js` project.
Can you now consider adding an option that allows to enable PDF support (viewing & editing & signing) within `richdocuments`?

**Comment by juliushaertl** [comment]
@thebearon Is that something that collabora online can already to? In that case we could allready add the option to edit the pdf file in collabora, but we shouldn't make it the default opener I think.

**Comment by thebearon** [comment]
No, it can open PDFs for viewing, but not for editing. And let's move this ticket to where it belongs, @HLFH, please open a bug report categorized as enhancement for LibreOffice Online: https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online

Sure, if this feature is added, richdocuments has to be adapted to it, but it's enough to open a ticket on that part once the feature is there in LibreOffice/Collabora Online.
