### ISSUE TITLE
Can't edit document when parent folder containing the folder that contains the file is read-only and the containing folder itself is shared as editable

### ISSUE THREAD

**Issue by Dominik-Tils** [nextcloud/richdocuments#1212]
# Describe the bug
A document can't be saved after editing when the folder which contains it is shared with edit permission + the superior/parent folder is shared as read-only.

This bug is nearly the same as bug #554 . Seems likely to be connected.

# Steps to reproduce
1. Share a folder A as read-only with user A with the following structure
folder A
*******|---folder B
*****************|---Document A.docx
2. Share the folder B with edit permission also with user A
( 3. user A can now create a new document in folder B )
4. Open the Document A with collabora as user A
4. File can be edited.
5. When trying to save file (click save button or wait for auto-save) following error message appears: 

> "Document cannot be saved to storage. Check your permissions or contact the storage server administrator."

### Expected behaviour
File should be editable and save properly

### Actual behaviour
File seems to be editable but throws error when saved

### Server configuration
**Operating system**: Windows 10

**Web server:** Debian 9

**Database:** MySQL

**PHP version:** 7.2

**Nextcloud version:** 19.0.1

**Comment by juliushaertl** [comment]
Yes, actually seems to be the same underlying issue as in https://github.com/nextcloud/richdocuments/issues/554 so let's continue over there.
