### ISSUE TITLE
Copy and Paste to and from MS Office doesn't work

### ISSUE THREAD

**Issue by QuentinBibas** [nextcloud/richdocuments#1218]
**Describe the bug**
Copy, cuting, and pasting do not work between any Collabora integration (NextCloud and Mattermost) from any MS Office application, at least on Windows 10 v2004
The puzzling thing is that drag n drop seems to work, and seems to keep most of the text formatting, except some things like "text squares".
I've also tried copy pasting to other apps and it works there : Discord, Notepad, or an other browser than the one running the Collabora instance works

**To Reproduce**
1. Open a document in collabora either in NextCloud or MatterMost
2. Open a document in MS Office Word (.docx or .odt) on the same PC
3. Try copy pasting via right click menu or shortcuts
4. Nothing happens, no error in logs

**Expected behavior**
Copy Pasting should work ?

**Screenshots**
cannot share the text square exemple publicly

**Client details:**
 - Windows 10 PRO v2004
 - tested in (latest versions of) Firefox ESR / Firefox / Google Chrome / Opera GX
 - any machine running Windows 10

## Server details

**Operating system**:
Debian 10

**Web server:**
Server version: Apache/2.4.46 (Debian)
Server built:   2020-08-10T08:44:40

**Database:**
mysql  Ver 15.1 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**
PHP 7.4.11 (cli) (built: Oct 18 2020 19:44:48) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies

**Nextcloud version:**
19.0.4

**Version of the richdocuments app**
no idea how to find that one !

**Version of Collabora Online**
6.4-10

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
This tracker is for the Nextcloud connector app named Collabora Online. For issues in the Collabora product itself, please open a bug report at: https://github.com/collaboraonline/online
