### ISSUE TITLE
Visio Files do not open in Collabora Online

### ISSUE THREAD

**Issue by pulkitkrishna00** [nextcloud/richdocuments#1219]
**Describe the bug**
Collabora advertises that Collabora Online can read Visio files, but when I click on a visio file in nextcloud, it starts to download instead of opening in Collabora Online.

**To Reproduce**
1. Upload a visio file to nextcloud.
2. Click on the file.
4. The file will start to download.

**Expected behavior**
The file should open in Collabora Online.

**Client details:**
 - OS: Ubuntu 20.10
 - Browser: Firefox, Chrome, Edge
 - Version: Chrome - 86, Firefox - 82.0, Edge - 88.0dev
 - Device: desktop

## Server details

**Operating system**: Ubuntu 20.10

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4.9

**Nextcloud version:** 20.0.1

**Version of the richdocuments app** 3.7.5

**Version of Collabora Online** 6.4.14

**Comment by juliushaertl** [comment]
The mime type is already in the supported mime type list https://github.com/nextcloud/richdocuments/blob/ef3ec7483d52edfa23c61c6389905b620b317cf0/lib/Capabilities.php#L44 Not sure why this doesn't work. Do you have an example visio file you could share so I can test this?

**Comment by pulkitkrishna00** [comment]
Sorry, but I am unable to attach a visio file here. I have uploaded it here - https://nd.nl.tab.digital/s/pPFJimKsRQ4eAfs

**Comment by timar** [comment]
The header has the MIME type 'application/vnd.ms-visio.drawing'.
