### ISSUE TITLE
Make URL always reflect currently opened file

### ISSUE THREAD

**Issue by fwolfst** [nextcloud/richdocuments#1225]
**Is your feature request related to a problem? Please describe.**
Users often copy the current URL (as shown in their web-browser accessing the file) and share that although there is the possibility to copy a file url via the Details Sidebar.

The current URL however does not always reflect the current document.

**Describe the solution you'd like**
I should be able to copy the current URL (e.g. CTRL+L CTRL+C in Firefox) and be confident that other logged in users with same file permissions can open the URL directly access the document upon visiting it.

**Additional context**
I am not sure in which contexts the current URL changes and this might well be a issue in nextcloud core and not the plugin itself - please tell me if that is the cas and I will file a bug there.
This happens on NC 19.0.4 with "Collabora online" Plugin version 3.7.6 (collabora self hosted via docker).

Maybe related is https://github.com/nextcloud/richdocuments/issues/1011 .

**Comment by thebearon** [comment]
#133 was opened previously on this, and it depends on the following: https://github.com/nextcloud/server/issues/12470
