### ISSUE TITLE
unable to edit file on encrypted share (but downloadable)

### ISSUE THREAD

**Issue by TeddyKopernikus** [nextcloud/richdocuments#123]
### Steps to reproduce
1. enable and activate default encryption module (incl. login of both users for init of keys etc.)
2. user 1 creates a folder x
3. user 1 creats an office file y in folder x (e.g. a docx from word or a odt from libreoffice)
4. user 1 shares folder x to user 2 (directly, no group share)

### Expected behaviour
5. user 2 opens file y in shared folder x with collabora app

### Actual behaviour
5. user 2 tries to open file y in shared folder x with collabora app and get's the error message:
"Lesen des Dokuments vom Speicher fehlgeschlagen. Bitte kontaktieren Sie den Administrator Ihres Speicherservers (<NEXTCLOUD-DOMAIN>)."
(translation: Reading of the document from storage failed. Please contact your storage administrator.)

Here comes the fun part:

6. user 2 downloads the file y in shared folder x and can open it locally
7. user 2 can sync the folder via client software and can open it locally
8. user 2 can reshare the folder x via link and anybody could open the link shared folder x and open the file y and everything works like a charm

Any idea, what this is about?

If any further information is needed, I'll be happy to provide, since I could reproduce the issue on two completely different nextcloud-instances.

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
no file key found, we assume that the file "/folderx/filey.docx" is not encrypted
Loaded WOPI Token record: {"id":"70","owner_uid":"user1","editor_uid":"user2","fileid":"12345","version":"0","canwrite":"0","server_host":"<NEXTCLOUD-URL>","token":"<SOME TOKEN>","expiry":"1506382406"}.
Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.
</details>

### Server configuration
**Nextcloud version:**
12.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
both - once updated from NC 12.0.X and once updated from NC 11.0.X
**Where did you install Nextcloud from:**
once official php-installer and once official tarball

**List of activated apps:**
<details>
<summary>App list</summary>
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.5
  - contacts: 1.5.3
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - richdocuments: 1.12.34
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
</details>

**Are you using encryption:** yes
**Are you using an external user-backend:** no
**Are you using external storage:** no

### Client configuration
any browser, any OS

**Comment by Ninos** [comment]
Same problem. Opening file with collabora app does not work with encryption enabled. Hope this can be fixed soon, main reason for NC is encryption and collaboration :-)

**Comment by cybermeme** [comment]
Hi, I actually had the same problem, for me, it was a DNS problem.

//you can use iptraff-np to easily look at the traffic to your docker interface from your host server//

The collabora's docker tried to connect my public IP and no the local one. According to my configuration, requests where blocked by the firewall.

To fix that, i log in the docker image:
   "docker exec -ti <your container name> bash"
then i installed vi to edit file
   "apt install vi"        <= bad bad idea for a production server, good enough for debug
   "vi /etc/hosts"
       in the /etc/hosts i add the nextcloud server IP and the nextcloud name
   "G"
   "o"
   <your local nextcloud server's IP> <example.nextcloud.change.me>
   Esc
   ":wq"
   "exit"

I hope this helps.

**Comment by chrsch** [comment]
Any news on this? Got this problem also with recent nc13 and richdocuments app...

**Comment by Croydon** [comment]
Didn't test in a while but it's likely still relevant.

**Comment by Ninos** [comment]
Please reopen. It's still not working.

See also:
https://nextcloud.com/collaboraonline/ -> Troubleshooting

> Issue: Collabora Online doesn't work with Encryption.
Yes, this is currently unsupported.

CC @juliushaertl :-)

**Comment by schiessle** [comment]
This problem only exists for shared files, right? You can open your own (encrypted) files with Collabora? This PR indicate that it should work: https://github.com/nextcloud/richdocuments/pull/52

If you use encryption with the master key, which is the default since Nextcloud 15 (at least) it should also work for shared files. But I didn't tested it.

**Comment by TeddyKopernikus** [comment]
Normally, opening own files does work but the full point in collaborative working is to share files, right?

But since the server-side encryption is buggy like nothing else I've seen for a while (including data loss!), let's just drop this issue for good, since it's based on my wrong assumption that the encryption is usable. As long as there are these severe issues resulting in permanent issue handling for shared folders (like group shares, missing key generation, etc.), I had sadly no choice but to decrypt all nextcloud instances I had and luckily I lost nearly no data since I collected the failed files from at least one machine directly to assemble a overall dataset. This additional efforts contained the understanding of the office plugin issues as well as general issues and the deployment of the recovery keys per user before the decryption process could be deployed which of course needed to be tested over and over to determine all files being yet unable to decrypt due to missing keys, which was as well an issue with the office plugin. (Don't try to guess, how much time these efforts took.)

Since the plugin wrote from the start, that it is not compatible with encryption (as written above) and will not be, let's just skip the still in beta state stuck server-side encryption even though the new stuff ain't better (at least yet). Wake me up, when something post-beta arrives...

Thanks for the fish, but please close this issue!

**Comment by Ninos** [comment]
I've disabled encryption on my NC instances (because of that reason). If wished, I can test it for you.
