### ISSUE TITLE
Zoom factor for spreadsheets seems off on macOS Big Sur

### ISSUE THREAD

**Issue by accolon** [nextcloud/richdocuments#1255]
**Describe the bug**
I just updated my MacBook Pro to macOS Big Sur, and now the zoom factor in spreadsheets seems to be off. At the standard 100%, the contents are barely readable, switching to 200% looks like the old default. See attached screenshots and compare the table contents with the menu bar. At first I supposed this was a problem with the new Safari 14 that is bundled with Big Sur, but the same problem exists in Firefox.

This might have to do with the screen resolution scaling on MacBooks. My display has a native resolution of 3072 × 1920 but is scaled to look like 1792 x 1120 in the default setting for this device. There are other applications (like VMware Fusion) which sometimes have scaling problems that look quite similar.

**To Reproduce**
1. Use MacBook with Retina display and screen scaling (in my case: MBP 16" 2019) with macOS Big Sur
2. Open or create a new ODS file with Collabora in Nextcloud
3. Leave zoom level at 100%

**Expected behavior**
At 100%, the table contents are clearly readable and correctly sized in comparison to the Collabora menu bar and other control elements. 

**Screenshots**
See attached, 100% and 200% zoom level of a newly created ODS file.

**Client details:**
 - OS: macOS Big Sur 11.0.1
 - Browser: Safari 14.0.1, Firefox 82.0.3
 - Device: MacBook Pro 16" 2019

## Server details

**Operating system**:
Ubuntu 20.04

**Web server:**
Apache 2.4.46

**Database:**
MariaDB 10.3

**PHP version:**
7.4.12

**Nextcloud version:**
20.0.1

**Version of the richdocuments app**
3.7.9

**Version of Collabora Online**
CODE 6.4-10

I did not find anything relevant in the Nextcloud and browser log referring to this issue.

<img width="891" alt="collabora_1x" src="https://user-images.githubusercontent.com/126886/99151140-6b7ae500-2699-11eb-9a26-33ed13877dbd.png">
<img width="891" alt="collabora_2x" src="https://user-images.githubusercontent.com/126886/99151141-6ddd3f00-2699-11eb-93bb-f02f9aa358ca.png">

**Comment by juliushaertl** [comment]
This issue tracker is only for the Nextcloud connector app named Collabora Online. For issues with Collabora Online itself, please open a bug report at: https://github.com/collaboraonline/online
