### ISSUE TITLE
.odt files only open in collabora when opend from dashboard 

### ISSUE THREAD

**Issue by peduso** [nextcloud/richdocuments#1265]
Steps to reproduce
1. Nexctcloud on server 1
2. Collabora Online Development Edition on server 2
3. Collabora App in Nextcloud activated, URL server 2 inserted in >Administration>Collabora
4. green dot appears, wenn "save" ist clicked
5. when leaving Administration and coming back, the dot appers red

### Expected behaviour
files schould open with collabora, from nextcloud directories

### Actual behaviour
files only open with collabora, when opened from Nextcloud dashboard (app installed), then Collabora works fine and fast

### Server configuration

**Operating system**:

Operating System: | Linux 5.4.0-45-generic x86_64
-- | --
 

**Web server:**

**Database:**

Type: mysql

Version: 10.3.26

Size: 1.9 MB

**PHP version:**

Version: 7.4.12

Memory Limit: 1 GB

Max Execution Time: 10800

Upload max size: 10 GB

**Nextcloud version:** (see Nextcloud admin page)
20.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
new installation by host hetzner.de storage share 
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here. No errors have been found
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
 Accessibility
1.6.0
Featured
Activity
2.13.2
Featured
Collabora Online
3.7.9
Featured
Collaborative tags
1.10.0
Featured
Comments
1.10.0
Featured
Contacts Interaction
1.1.0
Featured
Dashboard
7.0.0
Featured
Deleted files
1.10.1
Featured
Federation
1.10.1
Featured
File sharing
1.12.0
Featured
First run wizard
2.9.0
Featured
Log Reader
2.5.0
Featured
Monitoring
1.10.0
Featured
Nextcloud announcements
1.9.0
Featured
Notifications
2.8.0
Featured
Password policy
1.10.1
Featured
PDF viewer
2.0.1
Featured
Photos
1.2.0
Featured
Privacy
1.4.0
Featured
Recommendations
0.8.0
Featured
Right click
0.17.0
Featured
Share by mail
1.10.0
Featured
Support
1.3.0
Featured
Text
3.1.0
Featured
Time Tracker
0.0.45
TimeManager
0.1.4
Update notification
1.10.0
Featured
Usage survey
1.8.0
Featured
User status
1.0.0
Featured
Versions
1.13.0
Featured
Video player
1.9.0
Featured
Weather status
1.0.0
Featured
Auditing / Logging
1.10.0
Featured
Collabora Online - Built-in CODE Server
6.4.14
Default encryption module
2.8.1
Featured
LDAP user and group backend
1.10.2
Featured
ONLYOFFICE
6.1.0
Featured
Theming
1.11.0
Featured

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by juliushaertl** [comment]
Could you check your browser console for errors in the files app?

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by peduso** [comment]
Hi, 

thanks for your answer. I hope I catched the right logs and I hope they help in solving my problem

[log after succesfully opening a file from dashboard.log](https://github.com/nextcloud/richdocuments/files/5615885/log.after.succesfully.opening.a.file.from.dashboard.log)

[Log after trying to open a file from directories.log](https://github.com/nextcloud/richdocuments/files/5615886/Log.after.trying.to.open.a.file.from.directories.log)

[log dashboard before opening a file from dashboard.log](https://github.com/nextcloud/richdocuments/files/5615887/log.dashboard.before.opening.a.file.from.dashboard.log)

**Comment by juliushaertl** [comment]
I cannot see anything specific there, but I'd assume this is some issue with your hoster since they mention that the built-in collabora app is not supported:

https://docs.hetzner.com/konsoleh/storage-share/faq/additional-apps/#collabora
