### ISSUE TITLE
3.7.11 Powerpoint Presentation Mode not using special Font

### ISSUE THREAD

**Issue by apg1980** [nextcloud/richdocuments#1281]
**Describe the bug**
Hello, i am using Collabora Docker very well, and i am able to edit documents with additional fonts as well.
The only thing i am facing is the fact that the fonts i am using within the editor are not used while using powerpoint in presentation mode. In this case a default font is used.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client details:**
 - Device: [e.g. iPhone6, desktop]

## Server details

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:**

**Version of the richdocuments app**

**Version of Collabora Online**

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by thebearon** [comment]
This issue tracker is for the Nextcloud connector app named Collabora Online, please report issues with CODE/Collabora Online itself at https://github.com/CollaboraOnline/online/issues
