### ISSUE TITLE
CHANGELOG.md not maintained for 1.12.35

### ISSUE THREAD

**Issue by heinrichmartin** [nextcloud/richdocuments#129]
### Steps to reproduce
1. view CHANGELOG.md of the 1.12.35 tag at https://github.com/nextcloud/richdocuments/blob/1.12.35/CHANGELOG.md

### Expected behaviour
This file should summarize the changes between 1.12.35 and previous versions.

### Actual behaviour
The most recent version mentioned near the top of the file is 1.12.34.

**Comment by TP75** [comment]
The [Changelog.md](https://github.com/nextcloud/richdocuments/blob/master/CHANGELOG.md) should include all changes since 1.12.34 and should address 1.12.39 as the current version. This file should be updated regularily.
