### ISSUE TITLE
View -- Full screen does not work.

### ISSUE THREAD

**Issue by timar** [nextcloud/richdocuments#13]
### Steps to reproduce
1. Select View -- Full screen from Collabora Online's menu
2.
3.

### Expected behaviour
iframe goes full screen. It's convenient on mobile devices. 

### Actual behaviour
Nothing happens.
Firefox says: Request for fullscreen was denied because at least one of the document’s containing elements is not an iframe or does not have an “allowfullscreen” attribute.  loleaflet.htm
It works with ownCloud, that's why I think that it's a bug in Nextcloud's richdocuments or in Nextcloud.

**Comment by meliezer** [comment]
You probably have the same problem with other browsers.
I have never used nextcloud, but looking at the code I see that allowfullscreen is missing from the iframe tag...
I hope it helps,
Menashè

**Comment by DanScharon** [comment]
I'm not sure if 100% related, but Fullscreen presentation of .odp files doesn't work as well:

-> Slide -> Fullscreen presentation

I can't see anything related in the logs.

Versions used:

Nextcloud: 11.0.1
Collabora Online: 1.1.25
collabora/code:
`loolforkit version details: 2.0.3 - 2.0.3`
`office version details: { "ProductName": "Collabora Office", "ProductVersion": "5.1", "ProductExtension": ".10.18", "BuildId": "586626676b0aa697e153c6693a1e1407f7746989" }`

**Comment by THS-on** [comment]
@DanScharon 
I had the same problem. Have a look at this: https://help.nextcloud.com/t/libreofficeonline-proxy-problems-after-upgrading-to-version-2-0-1/6619/8
This fixed my problems with Fullscreen presentations. I have a bug in Firefox that the left side is not completely shown, but in Chrome/Chromium  works fine. 

THS-on
