### ISSUE TITLE
Collabora ARM slowing down Nextcloud (v20.0.4)

### ISSUE THREAD

**Issue by HeyWatchOutDude** [nextcloud/richdocuments#1307]
Hi,

I noticed that when I have "Collabora ARM" and "Collabora Online" enabled in my Nextcloud .... that each request in NC taking like 45-60s.

Check the following issue:
https://github.com/nextcloud/server/issues/24868

**Comment by juliushaertl** [comment]
Duplicate of https://github.com/nextcloud/richdocuments/issues/1282
