### ISSUE TITLE
Cannot provide deeplinks to Collabora-edited documents

### ISSUE THREAD

**Issue by matthijskooijman** [nextcloud/richdocuments#1313]
**Describe the bug**
When I use Collabora to edit a document and then pass the url form the address bar to someone else, that url opens the *folder* the document is in, rather than the document itself.

I realize that I can use "link sharing" to get a deeplink to the document, but:
 - I do not want to have a public share url for documents, I just want to send links to people that I know have access to a particular file through regular group-based sharing.
 - If I do not enable editing for the share url, these users just get a read-only view rather than an editing interface (this might be an issue on its own, though).
 - Getting that share link involves extra steps (going back to the dirlisting, and getting the share url there), which I know how to do, but a lot of others in my organization do not.

In general, I expect that the URL in the address bar will take me to whatever is shown in the browser now. So when looking at the collabora editor for some document, the URL should take me to that editor for that document.

With the current behavior I end up telling people "Please look at <name of document> in https://nextcloud.somewhere/apps/files/?dir=/ContainingDir&fileid=93824", which is more work for both parties than just a single deeplink to the document.

**To Reproduce**
1. Create an .odt document
2. Click it to start the collabora editor
3. Copy the url from the address bar into a new tab
4. This opens the *directory* view that contains the filename.

**Expected behavior**
I would expect the Collabora editor to open for the same file.

**Relevant context**

For text files within nextcloud, the behavior is already as expected. If you create a textfile and then click it to edit, you end up in a text editor with an url like: 

https://nextcloud.domain/apps/files/?dir=/Somdir&openfile=114061

Opening that URL in a new tab opens the editor again.

Looking at Collabora files it seems that:
 - In the directory listing, the same `openfile=` urls are used as well. You can see that if you mouseover a file, then the browser shows an `openfile=` link.
 -  Using ctrl-rightclick (add ctrl to get the browser right-click menu instead of the Nextcloud one) and "Copy link location" gives access to the url with `openfile=`, which *does* behave as expected (so this can be used as a workaround now).
 - When clicking a file to edit it, the address bar also initially shows the `openfile=` url.
 - However, when using this URL, the address bar URL is updated to replace the `openfile=` with `fileid=` (and the id of the direc tory, rather than the file itself).
 - I've also seen cases where using this URL would offer a zip download of the directory rather than opening the file for editing, but I could not reliably reproduce this.

## Client details

 - OS: Linux (Ubuntu)
 - Browser Firefox 
 - Version 84
 - Device: Laptop

## Server details

**Operating system**: Linux / docker

**Web server:** Apache

**Database:** Mysql

**PHP version:** 7.0.33

**Nextcloud version:** 20.0.4 (from docker)

**Version of the richdocuments app**:  3.7.11

**Version of Collabora Online**:  LOOLWSC 6.4.3 LOKIT 6.4-19

**Comment by matthijskooijman** [comment]
Ah, I just discovered that there is an "Internal link" in the "Sharing" tab of the sidebar for a file, which is pretty much what I'm looking for. However, this is slightly less intuitive for Collabora-files, since those are edited when you click them rather than showing the sidebar (so you need to use the share icon for a file in the directory listing view).

![image](https://user-images.githubusercontent.com/194491/104449403-d9ab2d80-559e-11eb-93ce-080bf052939a.png)

Still, the request here is valid: ideally, the URL in the address bare shown while editing should work (and maybe should be replaced by this "internal link"?).

**Comment by jospoortvliet** [comment]
Hi, the link would be:
https://cloud.yourcloud.com/apps/files/?dir=/folder&view=-shared&openfile=(file-ID)

The Nextcloud Text file can insert these links, it'd be a nice feature if Collabora could, too. Right now, you can insert URL's and insert local images - a next step would be creating a link to a file.

**Comment by juliushaertl** [comment]
This should work now as Jos mentioned with the server side implementation with using the viewer app in Nextcloud 23.
