### ISSUE TITLE
Collabora Online Development Edition (CODE) - ARM(64) Support? (dedicated server)

### ISSUE THREAD

**Issue by HeyWatchOutDude** [nextcloud/richdocuments#1314]
Hi,

is it possible to install "Collabora Online Dev. Edition (CODE) - ARM(64)" on a raspberry pi without nextcloud?

So in my case I have two raspberry pi 4 on one is running nextcloud and other stuff. The second one I want to use as "dedicated server".

(OS: Ubuntu 20.04.1 LTS - 64bit)

If its not possible is there a support in the near future?

Thanks!

**Comment by juliushaertl** [comment]
This issue tracker is only for the Nextcloud connector app named Collabora Online. For issues with Collabora Online itself, I'd suggest to raise a question about that at https://forum.collaboraonline.com/

I think running the arm appimage which is shipped as part of the CODE app should also work fine in standalone mode, but maybe there are also plans for distribution packages for arm by Collabora.

**Comment by HeyWatchOutDude** [comment]
How can I install the "appimage"?
