### ISSUE TITLE
User list popup z-order

### ISSUE THREAD

**Issue by timar** [nextcloud/richdocuments#1321]
**Describe the bug**
The user list popup appears underneath of the "Discuss" side panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/290614/105346693-41d4c180-5be6-11eb-8187-3fe6428fd701.png)

## Server details

**Nextcloud version:** 19.0.7

**Version of the richdocuments app** 3.7.11

**Version of Collabora Online** 6.4.4

**Comment by eszkadev** [comment]
It happens only when file is shared and I enter as a guest.
See comparison when opened the same document as regular user and by shared link:
![nc21-guest](https://user-images.githubusercontent.com/5307369/125942982-f71ccc49-c309-472c-bb39-98eae759748a.png)
