### ISSUE TITLE
Upgrading from 3.7.11 to 3.7.13 breaks Collabora

### ISSUE THREAD

**Issue by expert-geeks** [nextcloud/richdocuments#1330]
**Describe the bug**
Upgrading 'Collabora Online' app in nextcloud 19.6, from v3.7.11 to v3.7.13 breaks Collabora. Warning that Collabora Online cannot connect. Downgrade to 3.7.11 fixes the issue and Collabora works again.

**To Reproduce**
1. Upgrade a working Collabora Online from 3.7.11 to 3.7.13
2. Collabora doesn't work, complaining that it's not set up.
3. Downgrade to 3.7.11
4. Collabora works.

**Expected behavior**
I expected that upgrading the app, wouldn't break it.

## Server details
**Operating system**:
 - OS: Debian 10.
**Web server:**
nginx
**Database:**
mariadb
**PHP version:**
7.3
**Nextcloud version:**
19.6
**Version of the richdocuments app**
3.7.11 / 3.7.13
**Version of Collabora Online**

**Comment by juliushaertl** [comment]
Anything in the logs / browser error log?

**Comment by joergmschulz** [comment]
no, at least not here. Here, the only thing that's broken is the creation of documents from templates.

The log of the libreoffice instance doesn't show too interesting things; maybe a reverse proxy warning Poco::Net::DNS::resolve("192.168.176.1") failed: Host not found: 192.168.176.1| wsd/LOOLWSD.cpp:2215


But: the browser console log says: 
```
Uncaught TypeError: n.$file is undefined
    onEdit files.js:75
    openWithTemplate files.js:268
    _createDocumentFromTemplate NewFileMenu.js:107
    jQuery 4
        l
        fireWith
        M
        t
files.js:75:48

```

**Comment by juliushaertl** [comment]
Ah I can reproduce that now with creating new files. https://github.com/nextcloud/richdocuments/pull/1339 should fix but I'll verify when finishing that up for the stable3.7 branch.

**Comment by joergmschulz** [comment]
If there is a prerelease up for testing, and if I happen to have a minute, I'll install that one. Just give a ping here.

**Comment by DanScharon** [comment]
as there is no sane way to downgrade a Nextcloud app, this prevents us from upgrading to Nc 19

**Comment by RTrave** [comment]
deactivate, de-install, and then reinstall from file in apps/, from here, and re-activate:
https://apps.nextcloud.com/apps/richdocuments/releases?platform=19#19

in my case, templates and configs are not deleted.

**Comment by joergmschulz** [comment]
using the .11 version is also possible in NC20. The issue starts with .12!

**Comment by joergmschulz** [comment]
the newly released version 4.0 behaves differently. While the document is created correctly witht the template, richdocuments app  doesn't open. A click on the new file will result in the same crash a second time. A next click will open the document.

**Comment by joergmschulz** [comment]
it seems https://github.com/nextcloud/richdocuments/pull/1385 fixes this one. The .15 release contains this fix. Probably you can close this one.

**Comment by RTrave** [comment]
Tested, fixed for me.
thanks !!!

**Comment by juliushaertl** [comment]
Yes, this should have been fixed by https://github.com/nextcloud/richdocuments/pull/1385 for Nextcloud 21 with 4.0.1 and https://github.com/nextcloud/richdocuments/pull/1339 for older Nextcloud releases with richdocuments 3.7.15.

**Comment by expert-geeks** [comment]
I can confirm 3.7.15 fixes this for me too. Thanks.
