### ISSUE TITLE
Dark theme colors

### ISSUE THREAD

**Issue by drikqlis** [nextcloud/richdocuments#1334]
**Describe the bug**
When using dark theme or breeze-dark theme menus are unreadable. See https://github.com/mwalbeck/nextcloud-breeze-dark/issues/183 and https://github.com/nextcloud/richdocuments/issues/1270

**To Reproduce**
1. Enable dark theme or breeze-dark
2. Open any document in Collabora.

**Screenshots**

**Client details:**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome, Firefox
 - Device: [e.g. iPhone6, desktop]

## Server details

**Operating system**: Ubuntu 18.04 LTS

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** 20.0.6

**Version of the richdocuments app**

**Version of Collabora Online**

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by Fuseteam** [comment]
screenshot showcasing the bug on version 20
![image](https://user-images.githubusercontent.com/10421851/108228752-eda5fa00-711d-11eb-9315-0c595e56f7d5.png)

**Comment by elpraga** [comment]
I am having the same issue, it happens also on Android and when using the Android app. It is especially bad when selecting fonts since their names cannot be seen. 

Should this issue be reported here or on the Breeze Dark issue tracker?

**Comment by juliushaertl** [comment]
A fix was already proposed in https://github.com/nextcloud/richdocuments/pull/1394
