### ISSUE TITLE
Modified field in file list isn't updated after editing and closing file

### ISSUE THREAD

**Issue by thebearon** [nextcloud/richdocuments#134]
### Steps to reproduce
1. Edit a file, then close Collabora Online to get back to the file list.

### Expected behaviour
Modified field should show the file was edited a few seconds ago.

### Actual behaviour
Modified field isn't updated until the directory listing is refreshed.

**Comment by rullzer** [comment]
@skjnldsv any idea how we could do this?

**Comment by skjnldsv** [comment]
@rullzer I guess you need to edit the file model?
Not sure you can from the outside :(

**Comment by rullzer** [comment]
I guess the easy approach is to force a reload once collabora is closed.
