### ISSUE TITLE
Opening Documents returns an empty screen and a HTTP 400 error

### ISSUE THREAD

**Issue by Steffen75** [nextcloud/richdocuments#1340]
The server is running Nextcloud 20.0.6 on Debian 10 and Apache as webserver. Now I've tried to get the built-in CODE-Sever and Collabora Online from the app store running at it failed.

Everything is the latest version from the official repositries in case of the Debian. The version of CODE is 6.4.4 and Collabora Online is 3.7.14 both from Nextcloud's app store.

The Nextcloud installation is completely in a tradional way. No Docker involved.

Looking at the setup page of Collabora Online it tells me that the built-in CODE app is reachable.

Now when I try to open a document I only get the menu with File and so on on the top and the rest of the screen remains empty. I doesn't matter if I try it using Firefox or Safari on my Mac.

Looking at the browser console of my Firefox I can see a HTTP 400 error when the file should be loaded. I can also see this error in the log of the Apache.

However when I switch from the internal CODE to a demo server in Collabora Online opening a file works fine.

**Comment by mohe2015** [comment]
I myself had issues while the Circles App was enabled. So maybe check if that helps although I'm not sure you have the exact same problem as me.

**Comment by rikkaonline** [comment]
I have a VPS running Debian 9, nginx, php7.4, and nextcloud 20. Collabora worked fine at first, but after a reboot to resize the server, I got the same behavior. There are two 400 errors for https://[server]/apps/richdocumentscode/proxy.php?req=/lool/[etc], followed by "Uncaught TypeError: Cannot read property 'split' of null at proxy.php?req=/loleaflet/1296047/loleaflet.html?WOPISrc=[etc]"

I eventually gave up and created a new VPS running Debian 10, php8.0, and nextcloud 21, with everything else the same except as a clean install, and now I am immediately experiencing exactly the same issue.

**Comment by juliushaertl** [comment]
> Uncaught TypeError: Cannot read property 'split' of null at proxy.php?req=/loleaflet/1296047/loleaflet.html?WOPISrc=[etc]"

Please report this to https://github.com/CollaboraOnline/richdocumentscode as the error is happening over there.
