### ISSUE TITLE
Editor is not started on creation of a new document

### ISSUE THREAD

**Issue by y0va** [nextcloud/richdocuments#1343]
When I press on *New Document* in the files view of nextcloud, only a new filename with empty icon appears in the list and lool is not started. When I reload the page, a standard icon is displayed for the file, and when I click on it lool starts.

**Expected behavior**
lool shall start when I create a new document.

**Screenshots**
![image](https://user-images.githubusercontent.com/21321805/106811245-58f7c280-666e-11eb-812f-1b1e67110974.png)

**Client details:**
 - OS: Manjaro
  - Browser firefox 85
 - Device: desktop

## Server details

**Operating system**:  debian 10

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.3

**Nextcloud version:** 20.0.7.1

**Version of the richdocuments app** 3.7.14

**Version of Collabora Online** 6.4.10.20-20

<details>
<summary>Logs</summary>
#### Browser log

a) The javascript console log
```
Uncaught TypeError: n.$file is undefined
    onEdit files.js:75
    openWithTemplate files.js:268
    _createDocumentFromTemplate NewFileMenu.js:107
    jQuery 7
    _createDocumentFromTemplate NewFileMenu.js:99
    _openTemplatePicker NewFileMenu.js:129
    jQuery 7
    _openTemplatePicker NewFileMenu.js:123
    actionHandler NewFileMenu.js:41
    _promptFileName merged-index.js:11208
    jQuery 9
    _promptFileName merged-index.js:11185
    jQuery 10
    _promptFileName merged-index.js:11182
    _onClickAction merged-index.js:11118
    jQuery 2
files.js:75:48
    onEdit files.js:75
    openWithTemplate files.js:268
    _createDocumentFromTemplate NewFileMenu.js:107
    jQuery 7
    _createDocumentFromTemplate NewFileMenu.js:99
    _openTemplatePicker NewFileMenu.js:129
    jQuery 7
    _openTemplatePicker NewFileMenu.js:123
    actionHandler NewFileMenu.js:41
    _promptFileName merged-index.js:11208
    jQuery 9
    _promptFileName merged-index.js:11185
    jQuery 10
    _promptFileName merged-index.js:11182
    _onClickAction merged-index.js:11118
    _onClickAction self-hosted:1176
    jQuery 2
```
```
GEThttps://cld.freedomhost.de/index.php/core/preview.png?file=%2F%2Ftest_document3.odt&c=5ccf4f122742ae5ff3c2add958d3e38f&x=250&y=250&forceIcon=0
[HTTP/1.1 404 Not Found 1246ms]

	
GET
	https://cld.freedomhost.de/index.php/core/preview.png?file=//test_document3.odt&c=5ccf4f122742ae5ff3c2add958d3e38f&x=250&y=250&forceIcon=0
Status404
Not Found
VersionHTTP/1.1
Transferred695 B (2 B size)
Referrer Policyno-referrer

    	
    Cache-Control
    	no-cache, no-store, must-revalidate
    Connection
    	keep-alive
    Content-Length
    	2
    Content-Security-Policy
    	default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
    Content-Type
    	application/json; charset=utf-8
    Date
    	Wed, 03 Feb 2021 21:29:16 GMT
    Expires
    	Thu, 19 Nov 1981 08:52:00 GMT
    Feature-Policy
    	autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
    Pragma
    	no-cache
    Referrer-Policy
    	no-referrer
    Server
    	nginx/1.14.2
    X-Download-Options
    	noopen
    X-Frame-Options
    	SAMEORIGIN
    X-Permitted-Cross-Domain-Policies
    	none
    X-Robots-Tag
    	none
    X-Robots-Tag
    	none
    X-XSS-Protection
    	1; mode=block
    	
    Accept
    	image/webp,*/*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    Cookie
---redacted---
    Host
    	cld.freedomhost.de
    User-Agent
    	Mozilla/5.0 (X11; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0
```

</details>

**Comment by tellustheguru** [comment]
I have the same problem as @y0va.

**Comment by DecaTec** [comment]
Same here.
Workaround: You can open the document by opening it in a new browser tab (middle mouse button).

**Comment by RTrave** [comment]
Confirmed here too.

**Comment by dan-elevate** [comment]
same problem, this sucks

**Comment by Bables55** [comment]
I have the same problem too. Users can use Collabora by creating a file and reloading their browser.
I'm having a similar problem with calls from ownCloud. I think the problem is not with the NC Collabora Online app but with Collabora itself. In the case of ownCloud, it is not even possible to create a new Collabora file.

---
Lolkit 6.4.22-22, loolwsd 6.4.5, (NC)Collabora Online 3.7.14, (OC)Collabora Online 2.4.1

**Comment by DmDS** [comment]
workaround is to downgrade to 3.7.11
download https://github.com/nextcloud/richdocuments/releases/download/v3.7.11/richdocuments.tar.gz
and replace everything in /nextcloud/apps/richdocuments **excluding all files in the root and the appinfo folder**

**Comment by RTrave** [comment]
reinstall 3.7.11 is my way for now, because replacing a single file can conflict in a future file sanity check no ?

**Comment by y0va** [comment]
I needed to remove `apps/richdocuments` and do a `tar xf /tmp/richdocuments.tar.gz` in `apps`.

**Comment by Stufo76** [comment]
Same issue here, nothing working for me.

Hardware: RaspBerry pi4b 8GB
Debian 10
Server version: Apache/2.4.38
mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (aarch64) using readline 5.2
PHP-FPM 7.3.19-1~deb10u1
Nextcloud 20.0.7
Collabora Online	3.7.14
Collabora Online - Built-in CODE Server (ARM64)	6.4.601

**Comment by maxdrfr** [comment]
Resolved by editing /etc/hosts to the real public entry point (in case of reverse proxying with https offload) instead of loopback or local interface.
Ping #1282

**Comment by y0va** [comment]
Works for me without editing `/etc/hosts` with richdocuments 3.7.17.
