### ISSUE TITLE
Creating document from template doesn't work

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/richdocuments#1344]
**Describe the bug**
I use templates in ott format. When creating a new document from a template, the template isn't applied.

May be related to https://github.com/nextcloud/richdocuments/issues/1343

**To Reproduce**
1. Add a template (either in the admin settings section, or by adding a template folder in the personal settings). E.g. just add a custom footer/header in this template.
2. Create a new document (odt)
3. Chose a template
4. Open the document > the template isn't applied

**Expected behavior**
The template should be applied to the newly created document

**Client details:**
 - OS: Linux/Windows/macOS
 - Browser Firefox/Chrome(ium)/Safari

## Server details

**Operating system**:
Ubuntu Server 20.04

**Web server:**
nginx

**Database:**
MariaDB

**PHP version:**
PHP 7.4

**Nextcloud version:**
20.0.7

**Version of the richdocuments app**
Collabora App: 3.7.14

**Version of Collabora Online**
6.4.4.
Docker version, not integrated version

#### Nextcloud log (data/nextcloud.log)
no logs

#### Browser log
```
Uncaught TypeError: n.$file is undefined
    onEdit files.js:75
    openWithTemplate files.js:268
    _createDocumentFromTemplate NewFileMenu.js:107
    jQuery 7
    _createDocumentFromTemplate NewFileMenu.js:99
    click NewFileMenu.js:145
    jQuery 26
    _openTemplatePicker NewFileMenu.js:150
    jQuery 6
```

</details>

**Comment by RTrave** [comment]
Confirmed here too.

**Comment by joergmschulz** [comment]
This is a duplicate of #1330 - fix seems to be on the way. You can as well close this one.

**Comment by joergmschulz** [comment]
it seems #1385 fixes this one. The .15 release contains this fix. Probably you can close this one.

**Comment by DecaTec** [comment]
Yes, seems to be fixed finally.
