### ISSUE TITLE
php -d memory_limit=512M occ app:install richdocumentscode creating openbase_dir error

### ISSUE THREAD

**Issue by francoisPE** [nextcloud/richdocuments#1352]
Hello,

When I install by cli : php -d memory_limit=512M occ app:install richdocumentscode, I have open_basedir issue : 
PHP Warning:  file_exists(): open_basedir restriction in effect. File(/proc/307746) is not within the allowed path(s): (allmyopenbasedirpath) in /mysitepath/web/apps/richdocumentscode/proxy.php on line 62

**Steps to reproduce the behavior**
1. Nextcloud 20.0.7 full install by CLI : php occ maintenance:install (with adequate data)
2. Apps installed by CLI : php -d memory_limit=512M occ app:install richdocuments and php -d memory_limit=512M occ app:install richdocumentscode
3. Log error : PHP Warning:  file_exists(): open_basedir restriction in effect. File(/proc/307746) is not within the allowed path(s): (allmyopenbasedirpath) in /mysitepath/web/apps/richdocumentscode/proxy.php on line 62
4. As a result, impossible to open nextcloud site

When I run same install without richdomentscode by CLI, and, install manually, it works well : no openbasedir issue !

## Server details
 - ubuntu 20.04
 - Apache2.4
 - MariaDB
 - Php 7.4 (php-fpm)
 - Nextcloud version: 20.0.7
 - Version of the richdocuments app : latest
 - Version of Collabora Online : latest
 php occ config:list gives :
           "richdocuments": {
            "disable_certificate_verification": "yes",
            "enabled": "yes",
            "installed_version": "3.7.14",
            "types": "filesystem,dav,prevent_group_restriction",
            "wopi_url": "https:\/\/vhost\/apps\/richdocumentscode\/proxy.php?req="
        },
        "richdocumentscode": {
            "enabled": "yes",
            "installed_version": "6.4.503",
            "types": ""

<details>
#### Nextcloud log (data/nextcloud.log)
 PHP Warning:  file_exists(): open_basedir restriction in effect. File(/proc/307746) is not within the allowed path(s): (allmyopenbasedirpath) in /mysitepath/web/apps/richdocumentscode/proxy.php on line 62

#### Browser log
NA

</details>

**Comment by francoisPE** [comment]
Today, I have same error with web interface installation of richdocumentscode !

**Comment by francoisPE** [comment]
Any idea ?

**Comment by blocksebastian** [comment]
how did you solve this issue?

**Comment by francoisPE** [comment]
I am testing a solution. I'll let you know.

**Comment by francoisPE** [comment]
I propose to replace that line : [code]return file_exists('/proc/' . getLoolwsdPid());[/code] byt that line [code]return posix_kill(getLoolwsdPid(),0);[/code]
It has exactly the same effect, but, it doesn't resquest webuser access to /proc, what is quite dangerous...
See https://stackoverflow.com/questions/9874331/how-to-check-whether-specified-pid-is-currently-running-without-invoking-ps-from

**Comment by juliushaertl** [comment]
Feel free to open an issue or a pr with the proposed changed directly in the richdocumentscode app: 
https://github.com/nextcloud/richdocuments

**Comment by francoisPE** [comment]
I already did : issue + pr
