### ISSUE TITLE
Release for NC 21?

### ISSUE THREAD

**Issue by sebalis** [nextcloud/richdocuments#1367]
Hi, Nextcloud 21 is out and after updating one instance somewhat carelessly, Collabora is no longer active on that installation. I see that a beta version is out. Should I install that or is a release upcoming soon or would it be recommended that I just wait?

**Comment by knfoo** [comment]
Yeah I have the same problem.

**Comment by juliushaertl** [comment]
Sorry, that totally slipped through, I'll take care of pushing out a release asap.

**Comment by juliushaertl** [comment]
The beta should already work fine for that in the meantime.

**Comment by sebalis** [comment]
Thanks. I have now removed Collabora Online using the Apps settings, then downloaded and extracted https://github.com/nextcloud/richdocuments/releases/download/v4.0.0-beta1/richdocuments.tar.gz in the custom_apps directory and found the new version listed in the Apps settings where I could enable it. This seems to work, great.

Are you by any chance also involved with the Group Folders app, @juliushaertl​? The need is actually greater there, because there is no beta that could be used and the loss of functionality is more fundamental. See https://github.com/nextcloud/groupfolders/issues/1305​.

**Comment by knfoo** [comment]
Thanks - I upgraded already :+1:

**Comment by sebalis** [comment]
I’ve only now seen that 4.0.0 was released yesterday – thank you!
