### ISSUE TITLE
Could not establish connection to the Collabora Online server when URL has a trailing slash /

### ISSUE THREAD

**Issue by nebulade** [nextcloud/richdocuments#1395]
**Describe the bug**
When configuring the collabora office connector, it asks for the collabora server URL (`URL (and Port) of Collabora Online-server`)

If this URL due to copy and paste for example contains a trailing slash, then the error "Could not establish connection to the Collabora Online server." is shown, while it works fine after removing the slash.

**Expected behavior**
The code should be smart enough to remove trailing slashes automatically.

## Server details

**Operating system**: Cloudron

**Web server:** Apache

**Database:** Postgres

**PHP version:** 7.4

**Nextcloud version:** 20.0.8

**Version of the richdocuments app** 3.7.15

**Version of Collabora Online** 6.4-11

**Comment by juliushaertl** [comment]
A fix is proposed in https://github.com/nextcloud/richdocuments/pull/1412

Testing is very welcome :)
