### ISSUE TITLE
Lesen des Dokuments von Speicher fehlgeschlagen, Bitte kontaktieren Sie den Administrator Ihres Speicherservers

### ISSUE THREAD

**Issue by apg1980** [nextcloud/richdocuments#1398]
Collabora Online App 4.0.1
Collabora Server as Docker (Latest Image docker pull collabora/code)
PHP 7.4
Apache2 
Ubuntu 20.04
Nextcloud 21

This issue appears after Upgrade to Nextcloud 21.
Before everything was working well.

![grafik](https://user-images.githubusercontent.com/9514965/109616670-c09e1200-7b35-11eb-9950-c8e1f42db771.png)

Similar Issue is postet in.
https://github.com/CollaboraOnline/richdocumentscode/issues/104

**Comment by marco-aa** [comment]
Same here:

Collabora Online App 4.0.1
Collabora Server standalone CODE
PHP 7.4
Apache2
Ubuntu 18.04 LTS
Nextcloud 21

Some addition information:

If i use a odt template i can not save the file.
If i use a plain new one i can safe the file.
If i use a previous edited tempalte file i can change it.

In old issues i found that create a local file and upload it, you can edit and save it.

If i try to open a spreadsheet - it opens a text document.

The Errormessage message in nextcloud is the same.

on loowsd deamon in the systemlog of the loowsd server i found more or less the with every save operation this error
`Mar  7 12:24:21 clxxxxx loolwsd[14487]: wsd-14487-14693 2021-03-07 11:24:21.322426 [ docbroker_001 ] ERR  Cannot save docKey [/index.php/apps/richdocuments/wopi/files/70622_oc5xxxxxx], the .uno:Save has failed in LOK.| wsd/DocumentBroker.cpp:850
`

**Comment by mohe2015** [comment]
Do you use the Circles app? AFAIR I had issues with it.

**Comment by freechelmi** [comment]
Can you translate the title in english please ? thanks.

**Comment by marco-aa** [comment]
> Do you use the Circles app? AFAIR I had issues with it.

I gave it a short try - i deactivated the circle app - but the problems remain.

**Comment by marco-aa** [comment]
> Can you translate the title in english please ? thanks.

I'm not the issue owner - but i tried to translate it

"Failed to read the document from storage, Please contact the administrator of your storage server"

**Comment by marco-aa** [comment]
Today i found this issue #1424 
It guess it could be related ...
https://github.com/nextcloud/richdocuments/issues/1424

**Comment by joshtrichards** [comment]
Per https://github.com/CollaboraOnline/richdocumentscode/issues/104#issuecomment-1488452159 this may have been addressed.

@apg1980 Thoughts?

**Comment by joshtrichards** [comment]
Closing due to no further response after >6 months.
