### ISSUE TITLE
Back button in browser not working

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#14]
### Steps to reproduce
1. Open a document in collabora online
2. Hit the back button in your browser

### Expected behaviour
Collabora online should close and the files view should be back

### Actual behaviour

![2017-01-12-134229_142x370_scrot](https://cloud.githubusercontent.com/assets/3404133/21890272/398a7c04-d8cd-11e6-9019-b12898a80234.png)

**Comment by pandusen** [comment]
Confirmed, same issue in our side, as well as all users on the server.

**Comment by juliushaertl** [comment]
The same overlaying icons appear when opening a document from the favorites view in the files app.

**Comment by latebeat** [comment]
Same issue for me

**Comment by usanjar** [comment]
how fix it?

**Comment by timar** [comment]
Fixed by #183 in app version 2.0.4, I suppose.
