### ISSUE TITLE
Capitalized Extensions are Read-Only

### ISSUE THREAD

**Issue by mikshepard** [nextcloud/richdocuments#141]
### Steps to reproduce
1. Upload an Excel document and edit.
2. Rename extension from .xlsx to .XLSX
3. File is read-only in Collabora

### Expected behaviour
File should still be editable

### Actual behaviour
File is read-only

### Server configuration

**Operating system**:
Debian Jessie

**Web server:**
Apache 2.4.10

**Database:**
Mysql 5.7.20

**PHP version:**
5.6.30

**Nextcloud version:** (see Nextcloud admin page)
12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
Tarball

### Client configuration
**Browser:**
Chrome, Firefox, Vivaldi

**Operating system:**
Windows 7

**Comment by timar** [comment]
It's not a bug in the app. I fixed it in loolwsd (master).
See https://gerrit.libreoffice.org/#/c/49867/

**Comment by fifh** [comment]
Great ! I think this fix closes my bug here : https://bugs.documentfoundation.org/show_bug.cgi?id=115595
