### ISSUE TITLE
Not saving and saving message NextCloud + Collabora Online + Built-in CODE Server  + Group folders

### ISSUE THREAD

**Issue by jorge-vitrubio** [nextcloud/richdocuments#1424]
related to https://github.com/nextcloud/richdocuments/issues/70 and https://github.com/nextcloud/richdocuments/issues/98 and https://github.com/nextcloud/groupfolders/issues/58

**Describe the bug**
Installation has NextCloud and Collabora and CODE and Group folder.
We create a new file and add some content (text), first time on saving or closing no message is given but nothing is saved.

Opening it again does allow to save content but a message saying the opposite shows up "Document can not be saved. Check your permissions or contact the storage server administrator" and actually does save the changes.

It does happen within files created inside Group Folders and in non group folders. It happens in personal folders also.

**To Reproduce**
1. Create a new file odt by clicking the (+) symbol 
2. add some content
3. save it and/or wait to be saved
4. close the collabora app window
5. open the file again by clicking on it
6. the file is empty
7. create more content inside, write text
8. save the document
9. windows saying "Document can not be saved. Check your permissions or contact the storage server administrator" is shown
10. close file
11. open it again
12. content was saved

**Expected behavior**

The content has to be saved when no warnings are shown.
If warning is shown then no modifications should have happended.

**Screenshots**

**Client details:**
 - OS: FireFox and Chrome/chromium
 - NextCloud 20.0.7 
 - Collabora Online 3.7.16
 - Built-in CODE Server 6.4.607
 -  Group folders	8.2.0
 - 
## Server details

**Operating system**:
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        testing
Codename:       bullseye

**Web server:**
 apache2 -v
Server version: Apache/2.4.46 (Debian)
Server built:   2021-01-11T10:58:23

**Database:**
Server version: 10.5.8-MariaDB-3 Debian buildd-unstable
Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

**PHP version:**
 php -v
PHP 7.4.15 (cli) (built: Feb  7 2021 11:36:49) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.15, Copyright (c), by Zend Technologies

**Nextcloud version:**
 NextCloud 20.0.7 

**Version of the richdocuments app**
 - Built-in CODE Server 6.4.607

**Version of Collabora Online**
 - Collabora Online 3.7.16

<details>
<summary>

```
[Wed Mar 10 00:00:24.743583 2021] [ssl:warn] [pid 168] AH01909: aaa.bbb.ccc.org:443:0 server certificate does NOT include an ID which matches the server name
[Wed Mar 10 00:01:03.302894 2021] [php7:warn] [pid 365] [client 192.168.xxx.xxx:56540] PHP Warning:  fopen(/tmp/loolwsd.lock): failed to open stream: File exists in /var/www/nextcloud/apps/richdocumentscode/proxy.php on line 75
[Wed Mar 10 00:01:03.308370 2021] [php7:warn] [pid 365] [client 192.168.xxx.xxx:56540] PHP Warning:  fclose() expects parameter 1 to be resource, bool given in /var/www/nextcloud/apps/richdocumentscode/proxy.php on line 87 
[Wed Mar 10 00:13:10.133159 2021] [ssl:warn] [pid 168] AH01909: aaa.bbb.ccc.org:443:0 server certificate does NOT include an ID which matches the server name
[Wed Mar 10 12:25:59.771808 2021] [ssl:warn] [pid 168] AH01909: aaa.bbb.ccc.org:443:0 server certificate does NOT include an ID which matches the server name
[Wed Mar 10 12:45:38.464879 2021] [ssl:warn] [pid 168] AH01909: aaa.bbb.ccc.org:443:0 server certificate does NOT include an ID which matches the server name
[Wed Mar 10 12:50:04.488321 2021] [ssl:warn] [pid 168] AH01909: aaa.bbb.ccc.org:443:0 server certificate does NOT include an ID which matches the server name
[Wed Mar 10 13:17:16.245586 2021] [access_compat:error] [pid 5448] [client 192.168.xxx.xxx:33372] AH01797: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Wed Mar 10 13:54:31.026208 2021] [access_compat:error] [pid 6711] [client 192.168.xxx.xxx:49028] AH01797: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Wed Mar 10 14:10:29.780435 2021] [ssl:warn] [pid 168] AH01909: aaa.bbb.ccc.org:443:0 server certificate does NOT include an ID which matches the server name
[Wed Mar 10 14:14:41.378240 2021] [ssl:warn] [pid 168] AH01909: aaa.bbb.ccc.org:443:0 server certificate does NOT include an ID which matches the server name
[Wed Mar 10 14:15:40.014184 2021] [ssl:warn] [pid 168] AH01909: aaa.bbb.ccc.org:443:0 server certificate does NOT include an ID which matches the server name
[Wed Mar 10 14:16:28.582558 2021] [ssl:warn] [pid 168] AH01909: aaa.bbb.ccc.org:443:0 server certificate does NOT include an ID which matches the server name
```

</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by dan-elevate** [comment]
my users report the same problem and it is very bad

**Comment by kohlenstoff** [comment]
I discovered the same error. About 2 months ago and now again.

Nextcloud: 27.1.2
Collabora Online - Built-in CODE Server: 23.5.402
Nextcloud Office: 8.2.0

Operating System: Linux 6.5.8-arch1-1 x86_64
PHP Version: 8.1.23
Database: PostgreSQL 15.4


Noticeable is the fact that in the details of the file, the file versions show some revisions of empty files. It seems that the saving was attempted but without the changed content.

**Comment by joshtrichards** [comment]
Hi @jorge-vitrubio - Is this still an issue for you today? Cleaning out some old bug reports and lots has changed since this was reported.

To troubleshoot this or determine if there is a bug we'd need:

- Collabora Online (CODE) logs (e.g. with the Built-in Server it logs to /tmp/coolwsdSOMETHING IIRC)
- Nextcloud server logs

Unfortunately the only logs above are from Apache.

@kohlenstoff It's a relatively generic error. Given the age of this issue, your matter is likely unrelated other than having that message pop up. Please either try the Nextcloud Help Forum - https://help.nextcloud.com or create a dedicated Issue here if you think there is a bug to report.

**Comment by jorge-vitrubio** [comment]
> Hi @jorge-vitrubio - Is this still an issue for you today? Cleaning out some old bug reports and lots has changed since this was reported.

hello @joshtrichards , 

seems to be resolved as for today   2023 11 15:
   - Nextcloud 27.1.2
   - Collabora Online - Built-in CODE Server 23.5.503
   - Nextcloud Office 8.2.2
 
server: VPS
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
Linux vitrubio.net 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux
