### ISSUE TITLE
AutoFilter / Header Menu opens outside view area on small screens

### ISSUE THREAD

**Issue by baldrianbandit** [nextcloud/richdocuments#1427]
Opening the filter menu at the header of a table with AutoFilter on small screens, the menu is sometimes rendered outside the viewing area.

Steps to reproduce:
1) Have a small screen or reduce the browser size
2) Apply AutoFilter to a line in the middle of the screen
3) Click on any header element to open the filter menu

Client details:
Nextcloud 21 / richdocuments 4.0.2
Notebook with resolution 1366x768, Chromium browser version 89

I have to admit that there are no issues on larger screens. Even when having a AutoFilter header on the bottom of the viewable area, the menu opens fine above the header.

I can only reproduce if the space both above and below the AutoFilter header is smaller than the menu's heigth. Sometime, the menu isn't rendered at all or outside the viewing area.

**Comment by baldrianbandit** [comment]
![screenshot-1615478925](https://user-images.githubusercontent.com/12493502/110820846-c3b0a500-828f-11eb-9f5f-f44d0f2f7493.png)

**Comment by baldrianbandit** [comment]
Another screenshot from a client. See the clipped filter menu at bottom left of the view area. The filter menu appears and disappears by clicking the button in the associated column (B1). The screenshot is clipped horizontally but reflects the actual height of the browser window.

![screenshot-1615497440](https://user-images.githubusercontent.com/12493502/110856375-db038880-82b7-11eb-8be3-ab1aa713e36f.png)

**Comment by thebearon** [comment]
This looks like a bug within Collabora Online/CODE, please report over at: https://github.com/CollaboraOnline/online/issues

Please also add the version from Help -> About, but first upgrade CODE if you don't have 6.4.7 installed, yet.
