### ISSUE TITLE
User circle overlapping with Download all files buttons in Polish language

### ISSUE THREAD

**Issue by drikqlis** [nextcloud/richdocuments#1429]
**Describe the bug**
In link share mode Download all files button is overlapping with user circle.

**To Reproduce**
1. Share folder by link share.
2. Open link share in private window.
3. Open any document in Collabora.

**Expected behavior**
User circle should not overlap.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/19647553/110921478-dde59400-831e-11eb-844f-4c1399444c24.png)

**Client details:**
 - OS: Windows
 - Browser [e.g. chrome, safari] Chrome, Firefox
 - Device: [e.g. iPhone6, desktop]

## Server details

**Operating system**:
Ubuntu 18.04 LTS
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
7.3
**Nextcloud version:**
20.0.8
**Version of the richdocuments app**
3.7.17

**Comment by juliushaertl** [comment]
Should be fixed with the latest supported releases.
