### ISSUE TITLE
Data loss with the use of copy/paste with multiple users

### ISSUE THREAD

**Issue by ohmer1** [nextcloud/richdocuments#143]
We discovered that NextCloud+Collabora can lose data. After using it for a few days, we found how to reproduce the bug.

### Steps to reproduce
1. User A creates a new ODS document and open it.
2. User B opens the same shared ODS document.
3. User A enters text in A1, B1, A2, B2.
4. User A selects A1:B2 and does Ctrl+c.
5. User A does Ctrl+v in A3.
6. User A does Ctrl+v in A5.
7. User A does Ctrl+v in A7.
8. User B does noting, he just idles all this time.
9. User A closes the document with Ctrl+w or close the browser's tab.
10. User B still see the data entered in A1:B8.
11. User A opens again the document.
12. Data is gone for user A.
13. Spreadsheet is automatically refreshed for user B, data is now also gone.

All steps should be done relatively quickly in order to reproduce the bug.

### Expected behaviour
Data should not be lost.

### Actual behaviour
We have data lost.

## Server configuration detail

**Operating system:** Linux 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64

**Webserver:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** pgsql PostgreSQL 10.0 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit

**PHP version:** 7.0.22-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mcrypt, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, ssh2, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** tarball archive on nextcloud.com

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.6
 - circles: 0.13.6
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.7.5
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - richdocuments: 1.12.39
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreed: 2.0.2
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - gallery
 - user_external

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***removed***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.xxxx.ca"
    ],
    "datadirectory": "\/var\/web\/nextcloud.xxxx.ca\/data",
    "overwrite.cli.url": "https:\/\/nextcloud.xxxx.ca",
    "dbtype": "pgsql",
    "version": "12.0.3.3",
    "dbname": "nextcloud",
    "dbhost": "sql.xxxx.ca",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "updater.release.channel": "production",
    "mail_from_address": "nepasrepondre.nextcloud",
    "mail_smtpmode": "php",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "xxxx.ca",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "htaccess.RewriteBase": "\/",
    "app.mail.transport": "php-mail",
    "app.mail.accounts.default": {
        "email": "%USERID%@xxxx.ca",
        "imapHost": "mail.xxxx.ca",
        "imapPort": 143,
        "imapSslMode": "tls",
        "imapUser": "%USERID%"
    },
    "skeletondirectory": "\/var\/web\/nextcloud.xxxx.ca\/data\/SKELETON",
    "loglevel": 2,
    "maintenance": false
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
Bug not relative to LDAP/AD.
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/62.0.3202.89 Chrome/62.0.3202.89 Safari/537.36

**Operating system:** Ubuntu 16.04

**Comment by thebearon** [comment]
I could reproduce this, it's not related to the connector in Nextcloud, but to the Collabora Online application. Will look into it further.
