### ISSUE TITLE
The row display of the spreadsheet is wrong

### ISSUE THREAD

**Issue by Bables55** [nextcloud/richdocuments#144]
### Steps to reproduce
1. Create a new spreadsheet file in Nextcloud 12.0.4.

### Expected behaviour
Rows are displayed one by one row.

### Actual behaviour
The second and subsequent rows are grouped together, and the row number becomes a large numerical value such as 37. *It is not necessarily this number.
When I drag the bottom of the row header (leftmost), the row of "Row 2" appears. I repeat the same thing, the next row will be displayed.
I select all the cells, right click on the row header and display the context menu. Even if I adjust the row height from that menu numerically, disappearing rows are not displayed. Of course, it is not displayed even if "Show rows" is selected from the menu. In order to display hidden rows, I have to drag under the corresponding row.
The line does not change one by one next to the summarized row, and it changes with a big step, for example 5 or 10.

This also adversely affects existing files. The row display of the existing file also goes wrong.

### Server configuration

**Operating system**:
CentOS7.3
**Web server:**
nginx 1.11.10
**Database:**
MariaDB 5.5.56
**PHP version:**
PHP 7.1.12
**Nextcloud version:** (see Nextcloud admin page)
12.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
from 12.0.3
**Where did you install Nextcloud from:**
Official
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - announcementcenter: 3.1.1
  - apporder: 0.4.1
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.7
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - deck: 0.2.8
  - drawio: 0.8.8
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_automatedtagging: 1.2.2
  - files_clipboard: 0.6.4
  - files_external: 1.3.0
  - files_frommail: 0.1.0
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.5
  - nextcloud_announcements: 1.1
  - notes: 2.3.2
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - ransomware_protection: 1.0.5
  - richdocuments: 1.12.39
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - sharepoint: 1.0.2
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_external: 0.4
  - workflowengine: 1.2.0

```

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```

  'dbtype' => 'mysql',
  'version' => '12.0.4.3',
  'dbname' => 'xxxxxxxxx',
  'dbhost' => 'localhost:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'xxxxxxxxx',
  'dbpassword' => 'xxxxxxxxx',
  'installed' => true,
  'log_type' => 'owncloud',
  'logtimezone' => 'Asia/Tokyo',
  'logfile' => 'nextcloud.log',
  'loglevel' => 2,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'filelocking.enabled' => true,
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'xxxxxxxxx,
    'port' => 6379,
    'password' => 'xxxxxxxxx',
  ),
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpsecure' => 'ssl',
  'mail_from_address' => 'xxxxxxxxx',
  'mail_domain' => 'xxxxxxxxx',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'xxxxxxxxx',
  'mail_smtpport' => '465',
  'mail_smtpname' => 'xxxxxxxxx',
  'mail_smtppassword' => 'xxxxxxxxx',
  'maintenance' => false,
  'auth.bruteforce.protection.enabled' => false,
  'versions_retention_obligation' => '7,auto',
  'trashbin_retention_obligation' => 'auto',
"nc/config/config.php" 64L, 1903C
  'versions_retention_obligation' => '7,auto',
  'trashbin_retention_obligation' => 'auto',
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\MP3',
    6 => 'OC\\Preview\\TXT',
    7 => 'OC\\Preview\\MarkDown',
  ),
  'defaultapp' => 'mail',
  'theme' => '',

```
</details>

### Client configuration
**Browser:**
Firefox 57, Vivaldi 1.13
**Operating system:**
Windows10, macOS High Sierra

The state immediately after creating a new file.
![error-collabora-calc](https://user-images.githubusercontent.com/30524004/33813672-ae7bb3ba-de68-11e7-94cb-3004d3eb58fd.png)
It will be explained in the screenshot above.
I input "1" in cell A1 and I press the return key. Then the focus of the cell moves under it. This behavior is normal.
The cell focus moves to the leftmost column (A), the second row from the top. The header of the row is indicated as "37". When I focus on the second cell from the top, its header part is highlighted. There is only one cell.

![error-collabora-calc2](https://user-images.githubusercontent.com/30524004/33814262-6b19277a-de6c-11e7-9582-de7ddf5a9fb9.png)

I drag the bottom of "row 1". Then row 2 appears at the top of row 37. It is the same behavior after row 3 etc.
I drag the top of this 37 rows, sometimes the 2nd and 3rd rows are displayed.

**Comment by thebearon** [comment]
The repos have been downgraded to the previous working version, please reinstall the collaboraoffice* packages (version in Help -> About should say LOKit Collabora Office 5.3-31 afterwards). The issue itself will be fixed in the next update.
