### ISSUE TITLE
Collabora Online stopped working

### ISSUE THREAD

**Issue by adi-dev** [nextcloud/richdocuments#1442]
I'm not sure when the error occurred first time as I don't use this feature very often. My Nextcloud is updated to 21.0.0, PHP 8.0.3 with fpm. Today I noticed that I cannot open any office document. It only shows `Failed to load Collabora Online - please try again later`. I keep my apps always up to date:
Collabora Online 4.0.3
Collabora Online - Built-in CODE Server 6.4.703
already installed.
Error log:

Level | App | Message
---|---|---
Fatal | no app in context | Error: Call to undefined method OC\AllConfig::isGlobalScaleEnabled()/var/www/nextcloud/apps/richdocuments/lib/AppInfo/Application.php - line 154: OCA\Richdocuments\AppInfo\Application->updateCSP("*** sensiti ... *")/var/www/nextcloud/lib/private/AppFramework/Bootstrap/FunctionInjector.php - line 68: OCA\Richdocuments\AppInfo\Application->OCA\Richdocuments\AppInfo\{closure}("*** sensiti ... *")/var/www/nextcloud/lib/private/AppFramework/Bootstrap/BootContext.php - line 52: OC\AppFramework\Bootstrap\FunctionInjector->injectFn()/var/www/nextcloud/apps/richdocuments/lib/AppInfo/Application.php - line 156: OC\AppFramework\Bootstrap\BootContext->injectFn()/var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php - line 176: OCA\Richdocuments\AppInfo\Application->boot()/var/www/nextcloud/lib/private/legacy/OC_App.php - line 197: OC\AppFramework\Bootstrap\Coordinator->bootApp()/var/www/nextcloud/lib/private/legacy/OC_App.php - line 137: OC_App::loadApp()/var/www/nextcloud/apps/dav/lib/AppInfo/Application.php - line 124: OC_App::loadApps()/var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php - line 176: OCA\DAV\AppInfo\Application->boot()/var/www/nextcloud/lib/private/legacy/OC_App.php - line 197: OC\AppFramework\Bootstrap\Coordinator->bootApp()/var/www/nextcloud/lib/private/legacy/OC_App.php - line 137: OC_App::loadApp()/var/www/nextcloud/lib/base.php - line 979: OC_App::loadApps()/var/www/nextcloud/index.php - line 37: OC::handleRequest() |  
Error | richdocuments | Exception: Could not find urlsrc in WOPI/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php - line 217: OCA\Richdocuments\WOPI\Parser->getUrlSrc()/var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php - line 256: OCA\Richdocuments\TokenManager->getToken("*** sensiti ... *")/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218: OCA\Richdocuments\Controller\DocumentController->index()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127: OC\AppFramework\Http\Dispatcher->executeController()/var/www/nextcloud/lib/private/AppFramework/App.php - line 157: OC\AppFramework\Http\Dispatcher->dispatch()/var/www/nextcloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main()/var/www/nextcloud/lib/base.php - line 993: OC\Route\Router->match()/var/www/nextcloud/index.php - line 37: OC::handleRequest()
Error | PHP | Error: Function libxml_disable_entity_loader() is deprecated at /var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php#44/var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php - line 44: OC\Log\ErrorHandler::onError()/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php - line 217: OCA\Richdocuments\WOPI\Parser->getUrlSrc()/var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php - line 256: OCA\Richdocuments\TokenManager->getToken("*** sensiti ... *")/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218: OCA\Richdocuments\Controller\DocumentController->index()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127: OC\AppFramework\Http\Dispatcher->executeController()/var/www/nextcloud/lib/private/AppFramework/App.php - line 157: OC\AppFramework\Http\Dispatcher->dispatch()/var/www/nextcloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main()/var/www/nextcloud/lib/base.php - line 993: OC\Route\Router->match()/var/www/nextcloud/index.php - line 37: OC::handleRequest()
Error | PHP | Error: Function libxml_disable_entity_loader() is deprecated at /var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php#42/var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php - line 42: OC\Log\ErrorHandler::onError()/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php - line 217: OCA\Richdocuments\WOPI\Parser->getUrlSrc()/var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php - line 256: OCA\Richdocuments\TokenManager->getToken("*** sensiti ... *")/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218: OCA\Richdocuments\Controller\DocumentController->index()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127: OC\AppFramework\Http\Dispatcher->executeController()/var/www/nextcloud/lib/private/AppFramework/App.php - line 157: OC\AppFramework\Http\Dispatcher->dispatch()/var/www/nextcloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main()/var/www/nextcloud/lib/base.php - line 993: OC\Route\Router->match()/var/www/nextcloud/index.php - line 37: OC::handleRequest()

**Comment by timar** [comment]
richdocuments throws this exception here: https://github.com/nextcloud/richdocuments/blob/51c924a960d7d1f3f2f1d4d5a792e0e0653e330f/lib/WOPI/Parser.php#L54
This means that there is no hosting/discovery info. But I wonder why? Why is it not in the cache? If it is not there, why is it not refetched? Maybe there is something in the cache, but corrupted.
I encountered this issue myself, after updating richdocumentscode. Built-in CODE server was green in settings. When I waited long enough (max 1h, the lifetime of hosting/discovery in cache), the problem was gone. 
@juliushaertl your help would be highly appreciated. :)

**Comment by adi-dev** [comment]
I restarted apache2 and php-fpm services but no different, error remains. @timar, you mentioned cache, I guess you're not talking about browsers cache. Is it something stored in NC directory or database?
Btw. database is pgsql 12.6

**Comment by timar** [comment]
@adi-dev yes, I talked about NC cache.

**Comment by tcitworld** [comment]
Fixed in #1430

**Comment by tcitworld** [comment]
And already fixed in 96489d3e9de69da8fa713de57f0cebc54ab5e2f5 anyway

**Comment by adi-dev** [comment]
Well, thank you for closing this issue, but it still doesn't work, Collabora Online 4.0.4 and Collabora Online - Built-in CODE Server 6.4.704. Do I need to do anything on the server side?

**Comment by tcitworld** [comment]
In that case the issue is indeed what @timar noted.

**Comment by jfig** [comment]
It wasn't working, not even after a server restart, after I went to Settings > Collabora Online and re-selected "Use built in server" it started working again.

**Comment by adi-dev** [comment]
Thank you, it's working now, straight after update Collabora Online - Built-in CODE Server  to 6.4.705 🥃🥂
Btw. The server is on Ubuntu, not RPi, but I think it has the same roots ;)

**Comment by timar** [comment]
> It wasn't working, not even after a server restart, after I went to Settings > Collabora Online and re-selected "Use built in server" it started working again.

We have #1441 for this. Or at least I think it is related. I don't think that this workaround is as good as a proper fix would be. As @adi-dev reported in the last comment, the bug did not occur for them with Collabora Online - Built-in CODE Server 6.4.705, but I'm not convinced. The bug does not occur every time. Anyhow, I'm glad that it's not a serious blocker and I hope #1441 will be fixed eventually.

**Comment by ppascher** [comment]
I also ran into this issue on nextcloud 20.0.8 ("Could not find urlsrc in WOPI"). At first I tried downgrading Collabora Online - Built-in CODE Server from 6.4.705 down to 6.4.608 release by release but Collabora Online was not working. Next I upgraded the CODE Server back to 6.4.705 and tried downgrading Collabora Online from version 3.7.17. And right away version 3.7.16 was working again.

**Comment by dspoel** [comment]
Running CODE server 6.4.705 and Collabora Online 4.0.4 on latest Nextcloud still gives me the time out message. Downgrading as suggested by some does not work due to automatic upgrading. Other suggestions welcome.

**Comment by DJIronic** [comment]
ALso having the same issue after installing clean NextCloud with Collabora online.

```
[richdocuments] Error: Exception: Could not find urlsrc in WOPI at <<closure>>

0. /web/nextcloud/apps/richdocuments/lib/TokenManager.php line 217
   OCA\Richdocuments\WOPI\Parser->getUrlSrc("application/vnd ... t")
1. /web/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php line 256
   OCA\Richdocuments\TokenManager->getToken("*** sensitive parameters replaced ***")
2. /web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 218
   OCA\Richdocuments\Controller\DocumentController->index("*** sensitive parameter replaced ***", null)
3. /web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 127
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Richdocument ... {}, "index")
4. /web/nextcloud/lib/private/AppFramework/App.php line 157
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Richdocument ... {}, "index")
5. /web/nextcloud/lib/private/Route/Router.php line 302
   OC\AppFramework\App::main("OCA\\Richdocume ... r", "index", OC\AppFramework\ ... {}, {_route: "richdocuments.document.index"})
6. /web/nextcloud/lib/base.php line 993
   OC\Route\Router->match("/apps/richdocuments/index")
7. /web/nextcloud/index.php line 37
   OC::handleRequest()

GET /index.phpdocuments/index?fileId=16&requesttoken=EoMFmPNJzcE9bicTlM%2FDnnjlPlIenMD6obeYEW0o0k8%3D%3ASuRGzqksnPZzP05GwqeGqzKtDCdK2qOs1vT6dloYtxw%3D
from 46.39.166.73 by admin at 2021-04-27T15:48:01+00:00
```

Any idea?

**Comment by dspoel** [comment]
@DJIronic where do you find this log information?

**Comment by DJIronic** [comment]
Nextcloud/settings/Logging

**Comment by dspoel** [comment]
Thanks, but my installation looks different. Not using the docker version.
