### ISSUE TITLE
Clicking links in shared document

### ISSUE THREAD

**Issue by NathanRussellUK** [nextcloud/richdocuments#1444]
**Describe the bug**
When opening a shared link, the document is read-only as I'd expect, however I cannot click on hyperlinks

**To Reproduce**
1. Create a document containing a hyperlink to a web page
2. Create a share link to the document with "Allow editting" unchecked
2. Follow the share link
3. Click on the blue, underlined link
4. See that nothing happens

**Expected behavior**
The link should open in your web browser

**Screenshots**

**Client details:**
 - OS: MacOS
 - Browser Firefox
 - Version 86.0.1

## Server details

**Nextcloud version:** 20.0.7

**Version of the richdocuments app** 3.7.17

**Version of Collabora Online** 6.4.4

**Comment by juliushaertl** [comment]
Closing as an upstream issue already reported in https://github.com/CollaboraOnline/online/issues/1248
