### ISSUE TITLE
Built-in CODE Server (ARM64) 6.4.705 breaks Collabora Online

### ISSUE THREAD

**Issue by Stufo76** [nextcloud/richdocuments#1445]
**Describe the bug**
New version 6.4.705 on rpi4b breaks Collabora Online.
Revert back to 6.4.601 restore normal function

**To Reproduce**
1) Install Collabora Online latest version on rpi4b
2) Built-in CODE Server normally works, but Collabora Online cannot reach built-in code server

**Expected behavior**
6.4.705 normally works as 6.4.601

**Client details:**
 - All updated Browser
 - Device: Windows 10 and Debian 10 desktop

## Server details

**Operating system**:
`Debian GNU/Linux 10 (buster) 5.10.11-v8+ on rpi4b`

**Web server:**
```
Server version: Apache/2.4.38 (Debian)
Server built:   2020-08-25T20:08:29
```

**Database:**
Server version: 10.3.27-MariaDB-0+deb10u1 Debian 10

**PHP version:**
```
PHP 7.3.27-1~deb10u1 (cli) (built: Feb 13 2021 16:31:40) ( NTS )
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies with Zend OPcache v7.3.27-1~deb10u1
```

**Nextcloud version:**
`Nextcloud 20.0.8`

**Version of the richdocuments app**
```
Collabora Online - Built-in CODE Server (ARM64)
6.4.601 -> works
6.4.705 -> doesn't work
```

**Version of Collabora Online**
`Collabora Online	3.7.17`

**Comment by juliushaertl** [comment]
I could not reproduce any issue with the recent versions of the built-in code server, but in case this is still an issue, please report it at https://github.com/CollaboraOnline/richdocumentscode
