### ISSUE TITLE
Newly created documents (OOXML or Legacy format OD*) cannot be saved

### ISSUE THREAD

**Issue by msilvoli** [nextcloud/richdocuments#1449]
**Describe the bug**
Installation of Nextcloud on Bare Metal, Collabora Online + Built in CODE (not ARM/64).
New documents created directly in collabora cannot be saved independently of the type of file extension (OOXML or OD*).

We create a new file and add some content, first time on saving NO message is given and nothing is saved.
Opening it again does NOT allow to save content with a message "Document can not be saved. Check your permissions or contact the storage server administrator" 

Other documents originally created in Open/LibreOffice and syncronized to nextcloud can be edited and saved without any problems.

**To Reproduce**
1. Create a new file (od*whatever or ooxml depending of your server config) by clicking the (+) symbol
2. Add some content
3. Save it (no error is given)
4. Close the document window
5. Open the file again by clicking on it (the file is empty)
6. Add/Create new content inside
7. Save the document
8. Windows saying "Document can not be saved. Check your permissions or contact the storage server administrator" is shown
9. Close file
10. Open it again (the file is empty)

**Expected behavior**
The content has to be saved and no warnings are shown

**Screenshots**
![image](https://user-images.githubusercontent.com/32803973/112675545-e49afd80-8e2c-11eb-975f-555e4d1d38ff.png)

**Client details:**
 - OS: openSuse LEAP 
 - Browser Firefox 78.8.0esr (64-bit) / Chrome 89.0.4389.90 (Official Build) (64-bit)
 - Version 15.3 kernel 5.3.18-lp152.66-default
 - Device: Laptop

## Server details

**Operating system**:
NAME="openSUSE Leap"
VERSION="15.2"
kernel 5.3.18-lp152.63-default

**Web server:**
Server version: Apache/2.4.43 (Linux/SUSE)
Server built:   2021-01-27 09:11:10.000000000 +000

**Database:**
Mysql/Mariadb 10.4.17-MariaDB for Linux on x86_64 (MariaDB package)

**PHP version:**
PHP 7.2.5 (cli) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.5, Copyright (c) 1999-2018, by Zend Technologies

**Nextcloud version:**
20.0.8.1

**Version of the richdocuments app**
3.7.17

**Version of Collabora Online**
6.4.705

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
No Nextcloud Log related to the error
```

#### Browser log

Insert your browser log here, this could for example include:

a) Browser log upon opening the blank file (which cannot be saved)
```
excludeClickOutsideClasses.js:22 Uncaught TypeError: Cannot read property 'contains' of undefined
    at a.hasNodeOrAnyParentClass (excludeClickOutsideClasses.js:22)
    at a.clickOutsideMiddleware (excludeClickOutsideClasses.js:22)
    at r (v-click-outside.umd.js:1)
    at v-click-outside.umd.js:1
hasNodeOrAnyParentClass @ excludeClickOutsideClasses.js:22
clickOutsideMiddleware @ excludeClickOutsideClasses.js:22
r @ v-click-outside.umd.js:1
(anonymous) @ v-click-outside.umd.js:1
setTimeout (async)
el @ v-click-outside.umd.js:1
handler @ v-click-outside.umd.js:1
focus @ proxy.php?req=/loleaflet/8979e63/bundle.js:1
focus @ proxy.php?req=/loleaflet/8979e63/bundle.js:1
_activate @ proxy.php?req=/loleaflet/8979e63/bundle.js:1
_onSocketOpen @ proxy.php?req=/loleaflet/8979e63/bundle.js:1
(anonymous) @ proxy.php?req=/loleaflet/8979e63/loleaflet.html?WOPISrc=https%3A%2F%2Fmydomain.tld%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F504908_oc5mkyd9hdo5&title=apagar-1.xlsx&lang=en-GB&closebutton=1&revisionhistory=1:225
load (async)
getSessionId @ proxy.php?req=/loleaflet/8979e63/loleaflet.html?WOPISrc=https%3A%2F%2Fmydomain.tld%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F504908_oc5mkyd9hdo5&title=apagar-1.xlsx&lang=en-GB&closebutton=1&revisionhistory=1:225
global.ProxySocket @ proxy.php?req=/loleaflet/8979e63/loleaflet.html?WOPISrc=https%3A%2F%2Fmydomain.tld%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F504908_oc5mkyd9hdo5&title=apagar-1.xlsx&lang=en-GB&closebutton=1&revisionhistory=1:225
global.createWebSocket @ proxy.php?req=/loleaflet/8979e63/loleaflet.html?WOPISrc=https%3A%2F%2Fmydomain.tld%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F504908_oc5mkyd9hdo5&title=apagar-1.xlsx&lang=en-GB&closebutton=1&revisionhistory=1:225
(anonymous) @ proxy.php?req=/loleaflet/8979e63/loleaflet.html?WOPISrc=https%3A%2F%2Fmydomain.tld%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F504908_oc5mkyd9hdo5&title=apagar-1.xlsx&lang=en-GB&closebutton=1&revisionhistory=1:225
(anonymous) @ proxy.php?req=/loleaflet/8979e63/loleaflet.html?WOPISrc=https%3A%2F%2Fmydomain.tld%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F504908_oc5mkyd9hdo5&title=apagar-1.xlsx&lang=en-GB&closebutton=1&revisionhistory=1:225
```
</details>

![image](https://user-images.githubusercontent.com/32803973/112679407-c388db80-8e31-11eb-9587-1c6233616cfb.png)
![image](https://user-images.githubusercontent.com/32803973/112679475-d3a0bb00-8e31-11eb-92b1-31ea08eafb58.png)

**Comment by StarSmasher44** [comment]
Same issue, this software is quite useless if all it does is not save my work and delete it..

**Comment by dgtadmin** [comment]
Same issue as well, using a slightly newer version of Collabora Online version 6.4.705 and nextcloud 20.0.9.

**Comment by joshtrichards** [comment]
Hi @msilvoli - Are you still experiencing this? I'm cleaning up old issues. If so, I'll work it with you. If not, let's close this.

**Comment by msilvoli** [comment]
Not anymore Josh.

You guys can close it.
Thanks for contacting me

Best regards
