### ISSUE TITLE
Allow to create a new Draw document

### ISSUE THREAD

**Issue by schiessle** [nextcloud/richdocuments#1450]
With version 6.4.7 Collabora now also supports Draw! See: https://www.collaboraoffice.com/release-news/code-6-4-7-enables-macros-and-provides-draw-online/

It would be nice if the "create document" action would also allow the user to create a new Draw document. At the moment you can only create a text document, spreadsheet or presentation:

![image](https://user-images.githubusercontent.com/1589737/112701154-2e68ff80-8e90-11eb-9c4b-f31751a77cc6.png)

**Comment by meichthys** [comment]
If this is implemented, we should make sure that it is differentiated from the current Draw.io app for Nextcloud which adds an option to create a new 'diagram':
![image](https://user-images.githubusercontent.com/10717998/130798228-b2904385-992b-4e4f-acb3-79298d38c058.png)
