### ISSUE TITLE
Collabora doesn't open when clicking the sidebar preview

### ISSUE THREAD

**Issue by muchachagrande** [nextcloud/richdocuments#1454]
**Describe the bug**
When opening a document clicking on the file name, it opens and Collabora shows the editor interface but if I click on the preview image of the 'Details' side panel, Collabora doesn't start and Nextcloud shows the error "Failed to load Collabora Online Development Edition - please try again later"

**To Reproduce**
1. Go to files app
2. Select any document file
3. Click on '...' file menu
4. Select 'Details'
5. See the details panel appearing on the right side
6. Click on the preview image on the top of the side panel
7. The document should be opened on Collabora

**Expected behavior**
The document should be opened on Collabora as when you click on the file name

**Client details:**
 - OS: [Windows 8.1]
 - Browser [Firefox] also tested on Brave 1.22.70
 - Version [87]
 - Device: [desktop]

## Server details

**Operating system**: Ubuntu 18.04

**Web server:** Apache 2

**Database:** Postgre SQL

**PHP version:** 7.4

**Nextcloud version:** 21.0.0

**Version of the richdocuments app** 4.0.4

**Version of Collabora Online** 6.4.7

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"YF6RmOW3PHvRbi6XtmZTYwAAAAM","level":3,"time":"2021-03-26T22:59:53-03:00","remoteAddr":"xxxx:xxxx:xxxx:xxxx::2d56","user":"fjm","app":"richdocuments","method":"GET","url":"/apps/richdocuments/index?fileId=%7BfileId%7D&requesttoken=SKlg7l5xSaoLQLiIsiyZFMOq%2FU0t%2BAABmVKNH3FAA8k%3D%3AJsBTtjwlOYU%2FGYjl9VTVP5LNqwtigFk40BrURRIaVpk%3D","message":{"Exception":"Exception","Message":"","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"index","class":"OCA\\Richdocuments\\Controller\\DocumentController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php","Line":245,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36","version":"21.0.0.18","id":"605e91993dbb8"}
```
</details>

NOTE: I noticed the "fileId=%7BfileId%7D" in the URL. Looking at the apache log I see a difference when clicking at the file name comparing to clicking at the preview image. When clicking the file name the URL shows "fileId=1877314" and when clicking the preview image "fileId=%7BfileId%7D".

**Comment by drakes00** [comment]
Same problem here with Mysql backend and built-in CODE server.

**Comment by dspoel** [comment]
Still the same problem with richdocuments app 4.1.0 and Collabora Onlin 6.4.705. Previouslt with 4.0.4 as well.

**Comment by steffen-moser** [comment]
We can confirm this bug with the following configuration:

- **Operating system:** Oracle Solaris 11.4 SRU 34
- **Web server:** Apache 2.4.46
- **Database:** MySQL 5.7.33
- **PHP version:** 7.4.15
- **Nextcloud version:** 20.0.10
- **Version of the Collabora Online App:** 3.8.2
- **Version of Collabora Online:** 6.4.9

**Comment by juliushaertl** [comment]
This is not the case for any other file types these days. If this is still wanted please open a general issue in the server repository to make this work globally.
