### ISSUE TITLE
ODT templates shown twice

### ISSUE THREAD

**Issue by JAKuhr** [nextcloud/richdocuments#1468]
If I click the the "plus" symbol in the files app to create an "New Document", the template picker opens and the available templates are shown. While for plain text, presentations and spreadsheets everything looks alright, the odt templates are shown twice. 

Client:
 - OS: Debian Bullseye
 - Browser: Firefox
 - Version: 78.9.0
 - Device: Desktop

Server:
Operating system: Debian Bullseye
Web server: Apache 
Database: MariaDB: 10.5.9
PHP version: 7.4.15
Nextcloud version: 21.0.0
Version of the richdocuments app: 4.0.4
Version of Collabora Online: 6.4.7

![Bildschirmfoto](https://user-images.githubusercontent.com/9527705/113710358-dd54d900-96e3-11eb-8bd8-f4af001c2ccb.png)

**Comment by juliushaertl** [comment]
Possible fix is in https://github.com/nextcloud/richdocuments/pull/1471 Testing is very welcome :)

**Comment by JAKuhr** [comment]
> 
> 
> Possible fix is in #1471 Testing is very welcome :)

The fix works for me. Thank you very much!
