### ISSUE TITLE
Extension typo in new spreadsheet (.xslx) 

### ISSUE THREAD

**Issue by angerized** [nextcloud/richdocuments#1472]
**Describe the bug**
When clicking the + sign to create new spreadsheet, using OOXML format, the extension is .xslx instead of .xlsx.

**To Reproduce**
1. Go to 'Files'
2. Click on '+'
3. Scroll down to 'New spreadsheet.'

**Expected behavior**
.xlsx extension

**Screenshots**
![image](https://user-images.githubusercontent.com/24433153/114205508-a5a39680-995a-11eb-8107-f71135def215.png)

**Client details:**
Any

## Server details

**Operating system**: Debian 10

**Web server:** Apache 2

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud version:** 21.0.1

**Version of the richdocuments app** 4.0.4

**Version of Collabora Online** 4.0.4

**Comment by juliushaertl** [comment]
Already fixed with https://github.com/nextcloud/richdocuments/pull/1465 which will be part of the next maintenace relase.
