### ISSUE TITLE
Nextcloud 20.09 Collabora Office dont open ODS-Files

### ISSUE THREAD

**Issue by lupinerolf** [nextcloud/richdocuments#1484]
After the update to 20.09, no more coloabora ods files are opened

Nextcloud 20.09

LOOLWSD
6.4.7 (git hash: 4f68c25)
Angeboten von: c41ee17b
LOKit
Collabora Office 6.4-33 (git hash: bec78a8)
"Ubuntu 18.04.4 LTS"

**Comment by top-logic** [comment]
This is maybe the bad short description of this issue:
https://github.com/nextcloud/richdocuments/issues/1497

**Comment by thebearon** [comment]
Right, I haven't encountered such a problem that you can't open ODS files, @lupinerolf, do you have more details?

**Comment by lupinerolf** [comment]
The update to Collabora Online 3.7.19 has solved the problem
