### ISSUE TITLE
NC 21 error saving file

### ISSUE THREAD

**Issue by piti-diablotin** [nextcloud/richdocuments#1500]
**Describe the bug**
On NC21 with richdocuments 3.7 or 4.0 beta when I open an odt file, modify it and try to save it, I got the following errors (one after each click on the save button)
![Capture d’écran de 2021-04-21 13-45-00](https://user-images.githubusercontent.com/27724801/115566479-90aff700-a2ba-11eb-8959-83532bf77f85.png)
![Capture d’écran de 2021-04-21 13-45-06](https://user-images.githubusercontent.com/27724801/115566502-94dc1480-a2ba-11eb-80b0-3c8abddc53e0.png)
![Capture d’écran de 2021-04-21 13-45-17](https://user-images.githubusercontent.com/27724801/115566529-99083200-a2ba-11eb-90de-c22d114ba335.png)

Though the file seems to be saved. Exiting the app with unsaved changes works without error.

The errors I can see in the docker are (First warning is when I open a file)
```
wsd-00006-00042 2021-04-21 14:07:30.987271 [ websrv_poll ] WRN  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/4aa2794/undefined].| wsd/FileServer.cpp:487
wsd-00006-00286 2021-04-21 14:07:50.743487 [ docbroker_00e ] ERR  Unexpected response to WOPI::PutFile. Cannot upload file to WOPI storage uri [https://XXXXXXXXXX/index.php/apps/richdocuments/wopi/files/3831009_ocvalmhyoihj/contents?access_token=BRxoEx9qLDPeLZnrq5E7uh1QccWKvJo8&access_token_ttl=0&reuse_cookies=__Host-nc_sameSiteCookielax%3Dtrue%3A__Host-nc_sameSiteCookiestrict%3Dtrue%3Anc_username%3Ddiablotin%3Anc_token%3DzpHCmRyQye51haWGEQGzTl355Q3tJ5sW%3Anc_session_id%3D8pfkrtq4vda6pirh32ocqnmctq%3APHPSESSID%3Dnc9h6028317m7oigvjm18vi0pt%3Aoc_sessionPassphrase%3DLc7pOAWVkJ8hZP1OkjJJHTqXpfi2hdYUgFNFMh1uAd24FK79osh7TNeeMmdeFbkRArQznqslPdJND%2BSX2TG7lumsc99x1q1Z%2FDPdxyzwoWARoAui1s4wKbSgpIdjuVBd%3Ai18next%3Den%3Aocvalmhyoihj%3D8pfkrtq4vda6pirh32ocqnmctq]: 500 Internal Server Error: []| wsd/Storage.cpp:1259
wsd-00006-00286 2021-04-21 14:07:50.743943 [ docbroker_00e ] ERR  Failed to save docKey [/index.php/apps/richdocuments/wopi/files/3831009_ocvalmhyoihj] to URI [https://XXXXXXXXX/index.php/apps/richdocuments/wopi/files/3831009_ocvalmhyoihj?access_token=BRxoEx9qLDPeLZnrq5E7uh1QccWKvJo8&access_token_ttl=0&reuse_cookies=__Host-nc_sameSiteCookielax%3Dtrue%3A__Host-nc_sameSiteCookiestrict%3Dtrue%3Anc_username%3Ddiablotin%3Anc_token%3DzpHCmRyQye51haWGEQGzTl355Q3tJ5sW%3Anc_session_id%3D8pfkrtq4vda6pirh32ocqnmctq%3APHPSESSID%3Dnc9h6028317m7oigvjm18vi0pt%3Aoc_sessionPassphrase%3DLc7pOAWVkJ8hZP1OkjJJHTqXpfi2hdYUgFNFMh1uAd24FK79osh7TNeeMmdeFbkRArQznqslPdJND%2BSX2TG7lumsc99x1q1Z%2FDPdxyzwoWARoAui1s4wKbSgpIdjuVBd%3Ai18next%3Den%3Aocvalmhyoihj%3D8pfkrtq4vda6pirh32ocqnmctq]. Notifying client.| wsd/DocumentBroker.cpp:1173
```
Is my Apache proxy wrongly configure ? It was working before (cannot tell when I don't remember)  Here it is with last docker collabora/code:latest (pulled today) and richdocuments 3.7.19

I tried to disable Version app but did not work.

**To Reproduce**
1. Click + button in Files app
2. Select New document
3. Type text in collabora
4. Click the save button

**Expected behavior**
The red dot on the save button should disappear and the file should be saved

**Screenshots**
![Capture d’écran de 2021-04-21 13-45-00](https://user-images.githubusercontent.com/27724801/115566479-90aff700-a2ba-11eb-8959-83532bf77f85.png)
![Capture d’écran de 2021-04-21 13-45-06](https://user-images.githubusercontent.com/27724801/115566502-94dc1480-a2ba-11eb-80b0-3c8abddc53e0.png)
![Capture d’écran de 2021-04-21 13-45-17](https://user-images.githubusercontent.com/27724801/115566529-99083200-a2ba-11eb-90de-c22d114ba335.png)

**Client details:**
 - OS: Ubuntu 20.04.2 LTS
 - Browser firefox
 - Version 87
 - Device: laptop

## Server details

**Operating system**: Ubuntu 20.04.2 LTS server

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4

**Nextcloud version:** 21.0.1

**Version of the richdocuments app** 3.7.19

**Version of Collabora Online** collabora/code:latest from 2021/04/21

**Comment by dan-elevate** [comment]
same here

**Comment by joergmschulz** [comment]
also with version 4.0.8 in nc21.
It doesn't matter which collabora version we use (code, libreoffice 7.0, libreoffice 6.4).
 
Here the log file of collabora; 
```

ERR  #29: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1172
libreoffice-master    | wsd-00008-00035 2021-05-18 20:12:26.741516 [ websrv_poll ] ERR  #29: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1172
libreoffice-master    | wsd-00008-00038 2021-05-18 20:12:41.934188 [ docbroker_001 ] ERR  Cannot store docKey [/index.php/apps/richdocuments/wopi/files/1342285_oc2577a033c1] as .uno:Save has failed in LOK.| wsd/DocumentBroker.cpp:981
libreoffice-master    | wsd-00008-00038 2021-05-18 20:12:41.934268 [ docbroker_001 ] ERR  error: cmd=storage kind=savefailed| ./common/Session.hpp:125 
```
here what might be relevant from the browser console:
```
Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://nct.faudin.de:8443/custom-apps/richdocuments/js/viewer.js?v=7f78dbef-15
Source-Map-Adresse: viewer.js.map
```

**Comment by thebearon** [comment]
@joergmschulz I see no indication that your issue is related to what is reported here, and I commented in the other issue.

@piti-diablotin note the `500 Internal Server Error` in the log snipped you pasted in the issue, you will have to dig into your web server logs (or Nextcloud logs) and find why it returned error 500 to the request from CODE/Collabora Online.

**Comment by piti-diablotin** [comment]
@thebearon Ok strange enough, but good news ... 

I have updated my NC to 21.0.2 and collabora app to 4.1.1 and wanted to dig the 500 internal error, but the procedure I described above worked like a charm so the bug did not show up ... 

The only error I can see in the log of nextcloud is
![gnome-shell-screenshot-2UDR30](https://user-images.githubusercontent.com/27724801/119252396-546b0180-bbac-11eb-82c3-f1b30b8b2760.png)

which may be or not related to collaborate app ?? Not sure.

and in docker code/collaborate the one I have is
```
sh: 1: /usr/bin/loolmount: Operation not permitted
frk-00046-00046 2021-05-23 07:45:17.384604 [ forkit ] ERR  Failed to unmount [/opt/lool/child-roots/dPz5s9bne0rxnWFp].| common/JailUtil.cpp:68
```
which also does not seem to break anything... ?

Conclusion: Seems to work now, I'll come back if I see any related issue.
Thx
