### ISSUE TITLE
user info leak on demo server

### ISSUE THREAD

**Issue by phunn1e2** [nextcloud/richdocuments#151]
### Steps to reproduce
1. Collabora EU/US demo log in from mobile browser (Android)
2. Tap the contacts icon on right top
3. All email addresses of the users are leaked

### Expected behaviour
Shouldn't give me a list of all email addresses ever logged in, eh?

### Actual behaviour
Shows everyone.

### Server configuration

**Operating system**: Android 7.1

**Web server:** Demo server

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by phunn1e2** [comment]
Got a screenshot but not uploading due to security concerns. Can share privately if necessary.

**Comment by pranavk** [comment]
Sounds scary. But doesn't sound like richdocuments bug. Rather, it's a server bug I think. You don't need to open a document in Collabora to see the contact list, correct?

**Comment by phunn1e2** [comment]
the issue was opened with haste after a quick google search, sorry if it's not the right place. Opening a document is not necessary as I just confirmed that the mail Nextcloud screen already populates all the information.
