### ISSUE TITLE
30 minutes limit on office online server documents

### ISSUE THREAD

**Issue by SteelPC** [nextcloud/richdocuments#1526]
**Describe the bug**

If a document is left open or being modified for more than 30 minutes we get an error (file not found or accessible) and all modifications made after the 30 minutes mark are gone.

**To Reproduce**
1. Create a new document
2. Modify or leave it open for 30 minutes
3. Try to modify it after the 30 minutes mark

**Expected behavior**
Document should be editable after 30 minutes

**Client details:**
 - OS: Linux Mint 20, Windows 10
 - Browser Chrome
 - Version 90.0.4430.93
 - Device: desktop

## Server details

**Operating system**:

Nginx 1.19.6
10.5.9-MariaDB
PHP : 7.4.16
Nextcloud 20.0.9
Wopi app 3.5.6

**Comment by thebearon** [comment]
Can you please add your Nextcloud and Collabora Online connector app (the app in Nextcloud) version?

**Comment by SteelPC** [comment]
Done :)

**Comment by thebearon** [comment]
Thanks! That is a different app, which has nothing to do with Nextcloud or with Collabora. This repository and issue tracker is for the Collabora Online app, and I'd suggest using this app.

**Comment by SteelPC** [comment]
Oh my bad ! Posted the issue on the right repo :)
