### ISSUE TITLE
Bug when creating a new Collabora Online file from NC21 web interface

### ISSUE THREAD

**Issue by RodSeq** [nextcloud/richdocuments#1541]
**Describe the bug**
Collabora Online files created from NC21 web interface can’t be opened next, generating the error “Failed to load the document. Please ensure the file type is supported and not corrupted, and try again”.

This bug was not present in my NC 20 instance and happened since I have upgraded to NC 21.

**To Reproduce**
1. Create a new a Collabora Online file from NC web interface
2. The file is automatically opened, gerenating an error message

**REPRODUCIBILITY**
100%

**Expected behavior**
The new empty file should be opened with no error message

**Screenshots**
![Bug when creating a new Collabora Online file from NC21 web interface](https://user-images.githubusercontent.com/10270156/117574344-f71b7e80-b0dc-11eb-9701-dd5bac28a3c1.png)

**Client details:**
 - Browser [e.g. chrome, safari]: all 

## Server details

**Operating system**:
Ubuntu 16.04.7 LTS

**Database:**
mysql 10.4.18

**PHP version:**
7.4.18

**Nextcloud version:**
21.0.1

**Version of the richdocuments app**
4.0.4

**Version of Collabora Online**
Collabora Office 6.4-20

**Comment by juliushaertl** [comment]
Fix is in https://github.com/nextcloud/richdocuments/pull/1546 and a new release is being prepared.
