### ISSUE TITLE
Rich Workspace error when linking to a Collabora Online file - NC 21.0.1

### ISSUE THREAD

**Issue by RodSeq** [nextcloud/richdocuments#1542]
**Describe the bug**
Linking to a Collabora Online file in Rich workspace doesn’t work, generating a pop-up error message “There is no plug-in available to display this file type”.

**To Reproduce**
1. Create a link to a Collabora Online file on Rich workspace
2. Click on the link: the file can't be opened generating the error message

**REPRODUCIBILITY**
100%

**Expected behavior**
Linking to whatever file in Rich Workspace should work, even for Collabora Online files

**Screenshots**
![Rich Workspace error when linking to a Collabora Online file - NC 21 0 1](https://user-images.githubusercontent.com/10270156/117574463-7c9f2e80-b0dd-11eb-92a2-7badaae2e05a.png)

**Client details:**
 - Browser [e.g. chrome, safari]: all 

## Server details

**Operating system**:
Ubuntu 16.04.7 LTS

**Database:**
mysql 10.4.18

**PHP version:**
7.4.18

**Nextcloud version:**
21.0.1

**Version of the richdocuments app**
4.0.4

**Version of Collabora Online**
Collabora Office 6.4-20

**Comment by juliushaertl** [comment]
This has been implemented now with Nextcloud 23 / richdocuments 5.0.0
