### ISSUE TITLE
App does not start, Log says "Could not find urlsrc in WOPI"

### ISSUE THREAD

**Issue by hul51u** [nextcloud/richdocuments#1562]
**Describe the bug**
Collabora Online does not start.
My NC instance tells me "Collabora Online konnte nicht geladen werden - Bitte versuche es später noch einmal" (Collabora Online could not be startet - Please try again later)
Android App: "Das Laden dauert sehr lange" (Loading takes a lot of time)

**To Reproduce**

I don't know exactly....
I'm not quite shure, but maybe this problem is present since the last richdocuments update.
A few days ago collabora still ran fine.
Reinstall collabora(server+client)+reboot had no effect.

**Expected behavior**
App should start.

**Client details:**
 - Browser Chrome/Edge, Firefox, Android App
 - Version up to date

## Server details

**Operating system**:
Ubuntu 20.04.2 

**Web server:**
Apache2

**Database:**
mysql 10.3.29

**PHP version:**
7.4.3

**Nextcloud version:**
21.0.1

**Version of the richdocuments app**
Collabora Online	4.1.0

**Version of Collabora Online**
Collabora Online - Built-in CODE Server (ARM64)	6.4.705	

<details>

#### Nextcloud log (data/nextcloud.log)
Exception: Could not find urlsrc in WOPI
    0. /media/nextcloud/apps/richdocuments/lib/TokenManager.php - line 208:
       OCA\Richdocuments\WOPI\Parser->getUrlSrc()
    1. /media/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php - line 226:
       OCA\Richdocuments\TokenManager->getToken("*** sensiti ... *")
    2. /media/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218:
       OCA\Richdocuments\Controller\DocumentController->index()
    3. /media/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127:
       OC\AppFramework\Http\Dispatcher->executeController()
    4. /media/nextcloud/lib/private/AppFramework/App.php - line 157:
       OC\AppFramework\Http\Dispatcher->dispatch()
    5. /media/nextcloud/lib/private/Route/Router.php - line 302:
       OC\AppFramework\App::main()
    6. /media/nextcloud/lib/base.php - line 993:
       OC\Route\Router->match()
    7. /media/nextcloud/index.php - line 37:
       OC::handleRequest()

</details>

**Comment by juliushaertl** [comment]
Is there any change if you switch over to "Use your own server" and save the settings again? There should be an url containing proxy.php inside of the input field then.
