### ISSUE TITLE
documents created from templates are broken and cannot be saved

### ISSUE THREAD

**Issue by joergmschulz** [nextcloud/richdocuments#1563]
odt documents created from template cannot be saved 
---

(edited to reflect current status)

Environment: 
NC 22, any collabora server, any richdocuments 4.1.0 and more recent

How to reproduce the issue
---

1) create a document from a template, using name1.odt 
2) a document with this name is saved.
3) edit this document
4) try to save it. Saving will fail.
5) save it using another name using name2.odt. 
6) close richdocuments.
7) open and edit name1.odt 
8) save name1.odt, saving will fail.
9) open and edit name2.odt 
10) save name2.odt, saving will succeed.
11) open a local copy of name1.odt with libreoffice. It will be opened unnamed and can only be saved-as a new dockument. 
12) issue the command > file name1.odt: The result will be: ` OpenDocument Text Template`
13) unzip the file name1.odt
mimetype: `application/vnd.oasis.opendocument.text-template`

--> all documents created from templates are broken, the others work.

 
Here the log file of collabora; 
```

ERR  #29: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1172
libreoffice-master    | wsd-00008-00035 2021-05-18 20:12:26.741516 [ websrv_poll ] ERR  #29: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1172
libreoffice-master    | wsd-00008-00038 2021-05-18 20:12:41.934188 [ docbroker_001 ] ERR  Cannot store docKey [/index.php/apps/richdocuments/wopi/files/1342285_oc2577a033c1] as .uno:Save has failed in LOK.| wsd/DocumentBroker.cpp:981
libreoffice-master    | wsd-00008-00038 2021-05-18 20:12:41.934268 [ docbroker_001 ] ERR  error: cmd=storage kind=savefailed| ./common/Session.hpp:125 
```

Update
---
the last known working configuration is NC 20.0.9 and richdocuments 3.7.19

_Originally posted by @joergmschulz in https://github.com/nextcloud/richdocuments/issues/1500#issuecomment-843528961_

**Comment by thebearon** [comment]
@joergmschulz please update your CODE, that will get rid of the JSON parse error. The other issue might be related to what #1559 is supposed to fix.

**Comment by joergmschulz** [comment]
probably the same as https://github.com/nextcloud/richdocuments/issues/1541

**Comment by joergmschulz** [comment]
hmmm, just installed the brand new 4.1.1 - no change in this behavior.

**Comment by StefanKuh** [comment]
I am having the same issue with nextcloud instances ( Nextcloud 21, Collabora 4.1.1 ).

Last month I opened a support ticket on the nextcloud help forums:
https://help.nextcloud.com/t/cannot-save-templated-created-files/113656

**Comment by joergmschulz** [comment]
more info: 
when such a document is repliicated to the client, it stays broken: It carries no NAME (Unbekannt 1.odt). When you press 'Save', the 'Save-as' dialogue comes up.Conclusion: Something goes wrong right in the start, where the document is created. The document name is somehow not attrtibuted to the internal document structure.

**Comment by joergmschulz** [comment]
implementing #1504 would resolve this one as well

**Comment by joergmschulz** [comment]
even more info. 
Using NC21.0.2 and richdocuments 4.1.1 along with co-6.4.9 (and others, among them LO 7.1, the name of the new-to-be-created file will be displayed. But it still can't be saved.
When I download the file and issue
```file fromdefaultodt.odt ```
the result is 
```fromdefaultodt.odt: OpenDocument Text Template```
while other files display correctly as OpenDocument Text.

This might mean that on file creation the file gets a wrong file type as well?

More: 
Using the Demo server Ireland, the document doesn't open at all, but a msg "Document name" is displayed.
Attached the (empty) document.

[fromdefaultodt.odt](https://github.com/nextcloud/richdocuments/files/6580140/fromdefaultodt.odt)
@rullzer @thebearon

**Comment by t-markmann** [comment]
Still present in NC 21.0.3
Only spreadsheets (.ODS) are created correctly --> 21 kb.
ODT + ODP are 0 kb which result in the error.

**Comment by JB1985** [comment]
Yes, this bug is still in NC 21.0.3 with richdocuments 4.1.2 for odt Files.

Spreadsheets files work for me too.

`{"reqId":"ztKGLr1Myss7bOFyRMHX","level":3,"time":"2021-07-05T12:20:40+00:00","remoteAddr":"XX.XXX.XXX.XXXX","user":"XXXXX","app":"PHP","method":"GET","url":"/apps/richdocuments/index?fileId=%7BfileId%7D&requesttoken=1BPYGAytXL30l8PcqwkV6RejtLZwCX0q7pnls9FqV4U%3D%3AsVqzWUSdL%2FPC%2B63tmVlRvSP78ZlJRQtnuc%2BT4Z0lYuA%3D","message":{"Exception":"Error","Message":"Undefined offset: 0 at /var/customers/webs/web44/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php#208","Code":0,"Trace":[{"file":"/var/customers/webs/web44/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php","line":208,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/customers/webs/web44/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"index","class":"OCA\\Richdocuments\\Controller\\DocumentController","type":"->"},{"file":"/var/customers/webs/web44/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/customers/webs/web44/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/customers/webs/web44/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/customers/webs/web44/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/customers/webs/web44/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/customers/webs/web44/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"21.0.3.1","id":"60e2fb86a7a48"}`

**Comment by joergmschulz** [comment]
same with 4.2 - we don't even get a banner that the text can't be saved when trying to save the text manually.

**Comment by joergmschulz** [comment]
did a bit of fiddling around and found out: The template function really is broken if the new document is created from ott files.
What I did to find out this conclusion:
- removed all templates from the global configuration 
- removed the template directory from my personal configuration (oc_preferences, appid=richdocuments, set configkey templateFolder to NULL
- removed all .ott files from my template folder
- added odt files to my template folder
- added the value of my template folder to  appid=core, configkey=templateDirectory (this is legacy, from an ancient version of richdocuments as far as I remember)

Now these template files show up during document creation and can be used properly  - the files are saved.

No, ODT files cannot be added to the global template collection. Works as designed, and is correct IMHO

@juliushaertl do you think you can have a look?

**Comment by joergmschulz** [comment]
no change with 4.2.2 and the current CODE versions.

**Comment by JB1985** [comment]
It has been fixed for me since CODE version 6.4.10.

**Comment by AngelMatilla** [comment]
This is still happening to me with: 
LOKit Collabora Office 6.4-46 "Ubuntu 18.04.5 LTS"
LOOLWSD 6.4.10-10

**Comment by joergmschulz** [comment]
@JB1985 : Can you tell us what else you did to fix it - even 6.4.11 doesn't fix it.

**Comment by JB1985** [comment]
@joergmschulz 
i dont know! I am using a self compiling collabora Online 6.4.11-1 and it works fine.

**Comment by joergmschulz** [comment]
no - I'm using 6.4.11-1 on the test server and it doesn't work either. Which core version do you use? I have 6.4-47. Did you add any special compiler flags? Or something special in loolwsd.xml?

**Comment by JB1985** [comment]
I am using Libreoffice cp-6.4-47.

**Comment by joergmschulz** [comment]
Hmmm, same here. We still have it with 4.2.3 ... Still poking in the dark. Did you do something with the mimetypes - can you open .ott files directly in richdocuments?

**Comment by thebearon** [comment]
This is a regression somewhere in richdocuments 4.0, as it works fine with NC 20 and richdocuments 3.8.2. I tried it with a couple of 4.0.x versions, and 4.1.0, but couldn't get Collabora Online to load with those.

**Comment by gjongenelen** [comment]
We are experiencing the same problem after upgrading to NC22. I think it is concerning that this issue is open since May and there is no root cause diagnosed. Is it fixable?

**Comment by joergmschulz** [comment]
sure it is fixable - we need somebody js/php capable. HeShe needs to find the point where the document is created and change the internal filetype from ott to odt and create a PR from that. It's not me, sorry. Beyond my capabilities. 
The only other workaround is described above:eliminate all otts from your system and use the legacy odt folder for your corporate templates.

**Comment by leuedaniel** [comment]
After announcing collabora online as the new nextcloud office we want to change from onlyoffice to collabora but this is a show-stopper for us

**Comment by michaelhwalther** [comment]
This is indeed showstopper: after using a template, the (new) content is simply never saved. No warning, nothing.
--> perceived as "Data loss"

**Comment by AngelMatilla** [comment]
This issue is still reproducible using Richdocuments 5.0.1 on NC 23 and a collabora server using docker collabora/code:21.11.0.6.1

**Comment by joergmschulz** [comment]
HOORRAY, it seems the current master doesn't have this issue any longer.
Lets wait for the release!

**Comment by joergmschulz** [comment]
the current master stable23 resolves this issue.

**Comment by juliushaertl** [comment]
> With Nextcloud Office 5.0.3, Nextcloud 23.0.3 and Collabora 21.11.2.4.1
> The problem is still there.
> Is the current branch stable23 still in 5.0.3?

Can you open a separate issue then with the exact steps to reproduce, logs, description on how the template was added to Nextcloud and ideally also with the example template file used?
