### ISSUE TITLE
'Save as' modal loses focus

### ISSUE THREAD

**Issue by siccovansas** [nextcloud/richdocuments#1570]
**Describe the bug**
When I click on File > Save as, the modal pops up as expected and starts out with the 'New filename' field having focus which allows me to edit the filename. Shortly thereafter though without doing anything the focus goes back to the document behind the modal. So if I press backspace, instead of editing the filename, the contents of the selected cell are deleted. Once you click on the filename field you can edit the filename, but the focus is again lost sometimes.

This issue is also noticeable on a smartphone because after you click on File > Save as the keyboard shortly opens and then closes again. Even if you click on the field again the keyboard opens shortly and closes again. It is thus impossible to change the filename on mobile.

**To Reproduce**
1. Open a file using Collabora in Nextcloud (I used .ods and .xlsx files)
2. Click on File > Save As
3. Wait and see how the focus goes from the modal filename field back to the document behind it

**Expected behavior**
I expect the focus to stay at the filename field which allows me to directly change the filename using my keyboard

**Client details:**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: 88.0.1
 - Device: desktop

## Server details

**Nextcloud version:** 21.0.2

**Version of the richdocuments app:**  4.1.1

**Version of Collabora Online:** 6.4.806

**Comment by Raudius** [comment]
I think this has been fixed, possibly from an upstream dialog change.
