### ISSUE TITLE
clicking on a document should optionally open a new tab or window

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/richdocuments#1598]
**Is your feature request related to a problem? Please describe.**
currently collabora is opened in the current tab/window

**Describe the solution you'd like**
open a new tab/window 
make it configurable in settings (similar to onlyoffice IIRC)

**Comment by juliushaertl** [comment]
Opening files in the same window is the default behavior of Nextcloud and we are not planning to add a setting for that. You can already open a file in a new tab with Ctrl+click as mentioned in https://github.com/nextcloud/richdocuments/issues/31#issuecomment-720581638

**Comment by ferdiga** [comment]
Hi,
Thanks for the hint,
I obviously respect the decision "Opening files in the same window is the default behavior of Nextcloud ", nevertheless I want to point out that other "file browsers" like google drive, konqueror, finder etc do open files in a separate window/tab. 
And probably for a good reason.
