### ISSUE TITLE
Error: simplexml_load_string() + Exception: Call to a member function xpath() on bool

### ISSUE THREAD

**Issue by Night-Train-666** [nextcloud/richdocuments#1599]
I have updated, after a few months, my server for NextCloud and, with the 4.1.1 version of richdocuments, I get the following errors:
```
Error: simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found at /var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php#47

Error: simplexml_load_string(): Permissions-Policy: interest-cohort=() at /var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php#47

Error: simplexml_load_string(): ^ at /var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php#47

```

for all three the description is as follows:
```
    <<closure>>

    OC\Log\ErrorHandler::onError()

    /var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php - line 47:

    simplexml_load_string()

    /var/www/nextcloud/apps/richdocuments/lib/Controller/SettingsController.php - line 175:

    OCA\Richdocuments\WOPI\Parser->getUrlSrc()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218:

    OCA\Richdocuments\Controller\SettingsController->setSettings()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 157:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 302:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 993:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 37:

    OC::handleRequest()


```
and then again:
```
Exception: Call to a member function xpath() on bool

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 157:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 302:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 993:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 37:

    OC::handleRequest()

Generato daError: Call to a member function xpath() on bool

    /var/www/nextcloud/apps/richdocuments/lib/Controller/SettingsController.php - line 175:

    OCA\Richdocuments\WOPI\Parser->getUrlSrc()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218:

    OCA\Richdocuments\Controller\SettingsController->setSettings()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 157:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 302:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 993:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 37:

    OC::handleRequest()


```
The consequence is that, while everything else works, Collabora Online is no longer reachable.

The link https://my-site/loleaflet/dist/admin/admin.html displays the empty dashboard with the writing:
Server has been shut down; please reload the page.

In NextCloud, on the page https://my-site/settings/admin/richdocuments, the message appears:
Could not establish connection to the Collabora Online server

The configurations are the same as when the site was working.

Server details

Operating system:
Ubuntu 20.04.2

Web server:
Nginx 1.21.0

Database:
MariaDB 10.5.10

PHP version:
8.0.7

Nextcloud version:
21.0.2

Version of the richdocuments app
Collabora Online 4.1.1

collabora/code:latest

DockerVersion
19.03.11

curl -k https://localhost:9980
OK

**Comment by juliushaertl** [comment]
Could you chek the output of `curl -k localhost:9980/hosting/discovery` when executing that on the nextcloud server?

**Comment by daCaPo** [comment]
Seems I face a related issue (NC 25.0.5.1, standalone CODE 22.05.12.4). `simplexml_load_string($discovery)` in line 47 of `lib/WOPI/Parser.php` returns `false`, obviously because `$discovery` contains JSON data (returned from the CODE server, so networking connections is not an issue), not XML.

**Comment by daCaPo** [comment]
Well, I found my mistake: There was the path `/hosting/capabilities` given in the server address field on `/settings/admin/richdocuments` - copy-paste error, not so obviuos as not visible in the narrow text box - sorry for this false alarm.

**Comment by joshtrichards** [comment]
> The link https://my-site/loleaflet/dist/admin/admin.html displays the empty dashboard with the writing:
Server has been shut down; please reload the page.

This suggests something was going on with the CODE server. This app (`richdocuments`) is just the integration app. You'd have to troubleshoot your CODE server installation: https://sdk.collaboraonline.com/docs/installation/Collabora_Online_Troubleshooting_Guide.html#troubleshooting

> In NextCloud, on the page https://my-site/settings/admin/richdocuments, the message appears:
Could not establish connection to the Collabora Online server

Which is what I'd expect given the described circumstances.

The errors in the logs are merely symptoms of the above problem. 

The logging in this area is a bit better today than it was at the time of your original report, but we're still not going to be able to overcome the CODE server not functioning.
