### ISSUE TITLE
English UI (loleaflet exception) when switching to german formal (Förmlich - Sie - de_DE)

### ISSUE THREAD

**Issue by astachowski** [nextcloud/richdocuments#16]
### Steps to reproduce
1. Switch from "German informal (Du)" to "German formal (Sie)"
2. Open any document with richdocuments

### Expected behaviour
UI should show a german UI

### Actual behaviour
English UI is displayed

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4.18

**Database:** MySQL  5.7.16

**PHP version:** 7.0.8

**Nextcloud version:** 11.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** nextcloud.com tarball

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - richdocuments: 1.1.25
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.1.2
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - user_ldap: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - files_trashbin
  - survey_client
  - updatenotification
  - user_external
  - user_saml
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "oc78671032b9",
        "installed": true,
        "dbtype": "mysql",
        "dbname": "nextcloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "blacklisted_files": [
            ".htaccess"
        ],
        "htaccess.RewriteBase": "\/",
        "overwrite.cli.url": "https:\/\/cloud.marum.de\/",
        "check_for_working_wellknown_setup": true,
        "check_for_working_webdav": true,
        "check_for_working_htaccess": true,
        "trusted_domains": [
            "cloud.marum.de"
        ],
        "default_language": "en",
        "defaultapp": "files",
        "mail_domain": "marum.de",
        "mail_from_address": "cloud",
        "mail_smtpdebug": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "smtp.marum.de",
        "mail_smtpport": "465",
        "mail_smtptimeout": 10,
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "cron_log": true,
        "datadirectory": "\/var\/lib\/nextcloud\/data",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "version": "11.0.0.10",
        "maintenance": false,
        "debug": false
    }
}
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Chrome 55.0.2883.87

**Operating system:** Windows 10 1607

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
loleaflet.html?WOPISrc=https%3A%2F%2Fcloud.marum.de%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F160_oc7…:1 GET https://webapps.marum.de/loleaflet/2.0.2/node_modules/jquery-ui/themes/ui-lightness/images/ui-bg_highlight-soft_100_eeeeee_1x100.png 404 ()
bundle.js:5 focus:
bundle.js:5 focus: focussing
toolbar.js:738 Uncaught RangeError: Invalid language tag: de_DE
    at new NumberFormat (native)
    at Number.toLocaleString (native)
    at toLocalePattern (https://webapps.marum.de/loleaflet/2.0.2/toolbar/toolbar.js:738:86)
    at e.<anonymous> (https://webapps.marum.de/loleaflet/2.0.2/toolbar/toolbar.js:1197:11)
    at e.fire (https://webapps.marum.de/loleaflet/2.0.2/bundle.js:4:6417)
    at e._onStateChangedMsg (https://webapps.marum.de/loleaflet/2.0.2/bundle.js:6:29726)
    at e._onMessage (https://webapps.marum.de/loleaflet/2.0.2/bundle.js:6:16053)
    at e._onMessage (https://webapps.marum.de/loleaflet/2.0.2/bundle.js:4:18100)
toLocalePattern @ toolbar.js:738
(anonymous) @ toolbar.js:1197
fire @ bundle.js:4
_onStateChangedMsg @ bundle.js:6
_onMessage @ bundle.js:6
_onMessage @ bundle.js:4
toolbar.js:738 Uncaught RangeError: Invalid language tag: de_DE
    at new NumberFormat (native)
    at Number.toLocaleString (native)
    at toLocalePattern (https://webapps.marum.de/loleaflet/2.0.2/toolbar/toolbar.js:738:86)
    at e.<anonymous> (https://webapps.marum.de/loleaflet/2.0.2/toolbar/toolbar.js:1201:11)
    at e.fire (https://webapps.marum.de/loleaflet/2.0.2/bundle.js:4:6417)
    at e._onStateChangedMsg (https://webapps.marum.de/loleaflet/2.0.2/bundle.js:6:29726)
    at e._onMessage (https://webapps.marum.de/loleaflet/2.0.2/bundle.js:6:16053)
    at e._onMessage (https://webapps.marum.de/loleaflet/2.0.2/bundle.js:4:18100)
</details>

**Comment by JSoko** [comment]
> Nextcloud 11 sends 'de_DE' which is considered as invalid

Any news on repairing that?

**Comment by timar** [comment]
See https://apps.nextcloud.com/apps/richdocuments. The 1.1.26-nc11 release, which is marked as Unstable for a reason I don't understand, contains the fix.
