### ISSUE TITLE
Bit of file list visible after resizing window

### ISSUE THREAD

**Issue by thebearon** [nextcloud/richdocuments#1608]
- Open a document, and increase the height of the window a bit.

=> There is a bit of gap between Collabora Online and the bottom edge of the browser.

Screencast:
https://user-images.githubusercontent.com/19438782/121974252-4a898800-cd7f-11eb-9d8c-1a73029b3907.mp4

In Safari on macOS this gap is shown right away after opening a file:
![file_list_shown_Safari](https://user-images.githubusercontent.com/19438782/121974352-799ff980-cd7f-11eb-9781-3f0292edc3c4.png)

Nextcloud 20.0.10
richdocuments 3.8.2

Observed with Chrome and Firefox on Linux, and with Safari on macOS.

Possibly a regression from e927ce1bdbb41887fc3149431760f95631c98207? (at least in non-Safari browsers)
CC @eszkadev, @juliushaertl.

**Comment by thebearon** [comment]
Seems like Safari on an iPad is affected, too:
![file_list_shown_iPad](https://user-images.githubusercontent.com/19438782/121974903-bb7d6f80-cd80-11eb-8cab-ed6dd08308a1.png)

**Comment by eszkadev** [comment]
@juliushaertl do you have an idea how to fix this? I tried to find some code related to resizing but didn't find anything interesting.

**Comment by Andreas-Kainz** [comment]
On mobile devices the gap is even bigger first cause on mobile you don't have a big screen and you see a bigger area.

It's visible on all browser's on mobile.

The issue come when the virtual keyboard was on and go off. So I think it's related to the keyboard code.

**Comment by Andreas-Kainz** [comment]
@juliushaertl I have also an sizing issue see https://github.com/CollaboraOnline/online/issues/2454 which wasn't fixed by this PR.

However I think the issue is within /css/viewer.scss at 

```
#richdocumentsframe {
  height: calc(100vh - 50px);
}
```

what's the reason for - 50px cause if I remove the 50px the iframe use the full screen see screenshots at https://github.com/CollaboraOnline/online/issues/2454#issuecomment-922827141.
