### ISSUE TITLE
Public links to documents with write access allow "save as"

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/richdocuments#164]
### Steps to reproduce
1. Create a new document
2. Create a link to share it with the option "allow editing" set
3. Log out
4. Open the shared link
5. Save the document using File > Save As...

### Expected behaviour
It should not be possible to save a public shared document under a different name. The "Save As" menu item should not be visible or usable

### Actual behaviour
A document shared by a public link with editing can be saved under a different name. This can cause a lot of confusion.

### Server configuration

**Operating system**:
Ubuntu Linux 16.04

**Web server:**
Apache 2.4

**Database:**
MariaDB

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
12.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
https://nextcloud.com/install/

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>
</details>

**Comment by thebearon** [comment]
Confirmed.

**Comment by timar** [comment]
Fixed in app version 2.0.1

**Comment by arnowelzel** [comment]
Works for me - thanks for the fast fix!
