### ISSUE TITLE
using Collabora with CODE standalone only shows empty webpages

### ISSUE THREAD

**Issue by starlays** [nextcloud/richdocuments#1650]
I have installed nextcloud fallowing the [oficial documentation](https://docs.nextcloud.com/server/20/admin_manual/installation/example_ubuntu.html) and collabora fallowing the [oficial documentation](https://www.collaboraoffice.com/code/linux-packages/).

Nextclodu is running on https://nextcloud.localdev with self signed cert, Collabora is running under https://collabora.nextcloud.localdev under [nginx reverse proxy](https://www.collaboraoffice.com/code/nginx-reverse-proxy/) with self signed cert.

The software is running on a VM. My VM is running on Vmware and it has Ubuntu server 20.04 installed.

    $ uname -a
    Linux server01 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

The Collabora online extension from nextcloud shows that it has establieshed the connection to collabora server.

    Collabora online app version: 4.0.3

https://imgur.com/a/DDIoaya

I have changed the log level for collabora daemon, `loolwsd` to debug, all logs are looking ok, no error there.

[Here is a sample](https://pastebin.com/raw/K4SQ5yaJ) of collabora loolwsd daemon log when trying to open .docx file.

Nginx reverse proxy for Collabora server [log file](https://pastebin.com/raw/gYxrkS8n). From here I have found out that for whaterever reason Nextcloud is terminating the connection. Other request before, with the discovery and capabilities get OK respons no termination.

After this connection termination I get redirected to the same nextcloud server but it is somehow in a sub-frame.

https://imgur.com/3PugTym

I have changed the log level in Nextcloud config to debug, unfortunately there are absolutely no error entry in to the log on this matter for further investigation.

Also I have tried to access a document with the browser debug console enabled and Nextcloud log level set to debug. In here I see a lot of errors that are pumping. [This is a sample log](https://pastebin.com/raw/MTYVKVpq) from the browser debug console. There is an error message that the richdocument WOIP got blocked by security content restriction. 

If some one can help me solve this problem would be great.

Thank you in advance.

P.S: I have opened [this issue](https://github.com/nextcloud/server/issues/25127) here as it seems is a more proper place for it.

**Comment by a575606** [comment]
throwing my hat in the ring with exactly the same problem. Using a linuxserver.io NC docker and a collabora code docker container. both on same docker network and behind an nginx proxy. running code without ssl creates mixed content browser errors, but running with ssl creates the alternate security policy issue described above

**Comment by juliushaertl** [comment]
The browser console output would be interesting here, I guess it is more a setup related issue, but we should be able to detect and warn about mixed content here before it happens. Though the redirect seems a bit odd, I've never encountered that so far.

**Comment by jetadidas** [comment]
Same problem here with the blank screen. Below are my specs and error logs.

NextcloudPI with raspberry4 
Nextcloud 22 with php8.08
<html>
<body>


Error: Trying to access array offset on value of type null at /var/www/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php#125/var/www/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 125:OC\Log\ErrorHandler::onError()/var/www/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 80:OCA\Richdocuments\WOPI\DiscoveryManager->isProxyStarting()/var/www/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 56:OCA\Richdocuments\WOPI\DiscoveryManager->fetchFromRemote()/var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php - line 41:OCA\Richdocuments\WOPI\DiscoveryManager->get()/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php - line 208:OCA\Richdocuments\WOPI\Parser->getUrlSrc()/var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php - line 226:OCA\Richdocuments\TokenManager->getToken("*** sensiti ... *")/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:OCA\Richdocuments\Controller\DocumentController->index()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:OC\AppFramework\Http\Dispatcher->executeController()/var/www/nextcloud/lib/private/AppFramework/App.php - line 156:OC\AppFramework\Http\Dispatcher->dispatch()/var/www/nextcloud/lib/private/Route/Router.php - line 301:OC\AppFramework\App::main()/var/www/nextcloud/lib/base.php - line 1000:OC\Route\Router->match()/var/www/nextcloud/index.php - line 36:OC::handleRequest()
--



</body>
</html>


<html>
<body>


Error: Trying to access array offset on value of type null at /var/www/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php#124/var/www/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 124:OC\Log\ErrorHandler::onError()/var/www/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 80:OCA\Richdocuments\WOPI\DiscoveryManager->isProxyStarting()/var/www/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 56:OCA\Richdocuments\WOPI\DiscoveryManager->fetchFromRemote()/var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php - line 41:OCA\Richdocuments\WOPI\DiscoveryManager->get()/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php - line 208:OCA\Richdocuments\WOPI\Parser->getUrlSrc()/var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php - line 226:OCA\Richdocuments\TokenManager->getToken("*** sensiti ... *")/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:OCA\Richdocuments\Controller\DocumentController->index()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:OC\AppFramework\Http\Dispatcher->executeController()/var/www/nextcloud/lib/private/AppFramework/App.php - line 156:OC\AppFramework\Http\Dispatcher->dispatch()/var/www/nextcloud/lib/private/Route/Router.php - line 301:OC\AppFramework\App::main()/var/www/nextcloud/lib/base.php - line 1000:OC\Route\Router->match()/var/www/nextcloud/index.php - line 36:OC::handleRequest()
--



</body>
</html>

<html>
<body>


Error: Trying to access array offset on value of type null at /var/www/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php#123/var/www/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 123:OC\Log\ErrorHandler::onError()/var/www/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 80:OCA\Richdocuments\WOPI\DiscoveryManager->isProxyStarting()/var/www/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 56:OCA\Richdocuments\WOPI\DiscoveryManager->fetchFromRemote()/var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php - line 41:OCA\Richdocuments\WOPI\DiscoveryManager->get()/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php - line 208:OCA\Richdocuments\WOPI\Parser->getUrlSrc()/var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php - line 226:OCA\Richdocuments\TokenManager->getToken("*** sensiti ... *")/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:OCA\Richdocuments\Controller\DocumentController->index()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:OC\AppFramework\Http\Dispatcher->executeController()/var/www/nextcloud/lib/private/AppFramework/App.php - line 156:OC\AppFramework\Http\Dispatcher->dispatch()/var/www/nextcloud/lib/private/Route/Router.php - line 301:OC\AppFramework\App::main()/var/www/nextcloud/lib/base.php - line 1000:OC\Route\Router->match()/var/www/nextcloud/index.php - line 36:OC::handleRequest()
--



</body>
</html>

_**Thats about all the logs i Have so far tried everything to get it  back up with no results**_

**Comment by joshtrichards** [comment]
Hi folks. I'm attempting to clean up older Issues. Are you still experiencing this situation? If so, I'll attempt to work on it. Otherwise I'd like to close this issue. Let me know!

**Comment by sirdrakeistda** [comment]
I still get the same error:
```
[PHP] Error: Trying to access array offset on value of type null at /var/www/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php#132
```
The settings page I get following info:
Collabora server is rechable.

Not sure why it is still not working.

**Comment by joshtrichards** [comment]
Closing due to insufficient information to follow-up on further. Unfortunately the original logs were linked off-site so they're gone as well.

@sirdrakeistda That looks unrelated. Please post your details over at at Nextcloud Help Forum - https://help.nextcloud.com or create a dedicated bug report with the details of your environment.
