### ISSUE TITLE
403 Forbidden (Sabre\DAV\Exception\Forbidden).

### ISSUE THREAD

**Issue by TheToto318** [nextcloud/richdocuments#1651]
Hey 

So i get a forbidden message when I try to upload in local external storage. Witch is a bind mount in an lxc container (previligied) in proxmox. The www-data user and group are the owners of the mounted folder (same uid and gid as the ones on the host). I can write to the folder in cli with the www-data user.

I managed to get the upload working by setting the particular permission to the folder (0755). Now everything is working, EXECPT writting in the root of the folder, I can write into the subfolder of this folder but not into the folder himself.

I can't also delete folder into the mounted folder but can erase subdirectories into these folder.

Regards

### Steps to reproduce
1. Create a bind mount in proxmox lxc.
2. Give the www-data user full acces of this mount 
3. Try to upload a file into the root of the folder.

### Expected behaviour
Upload successfuly

### Actual behaviour
"Forbidden" message

### Server configuration

**Operating system:** Debian 9

**Web server:** Apache 

**Database:** Mysql

**PHP version:** 7.4

**Nextcloud version:** 21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
External storage
Talk
Onlyoffice
Calendar
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'ocp1doe25f5g',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '',
  ),
  'datadirectory' => '/var/www/nextcloud-data',
  'dbtype' => 'mysql',
  'version' => '21.0.1.1',
  'overwrite.cli.url' => '',
  'htaccess.RewriteBase' => '/',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'memcache.local' => '\OC\Memcache\Redis',
  'memcache.distributed' => '\OC\Memcache\Redis',
```
</details>

**Are you using external storage, if yes which one:** Local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No log about the issue
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No log about this specific issue except into the nextcloud sync client "Sabre\DAV\Exception\Forbidden"
```
</details>

**Comment by juliushaertl** [comment]
Closing as this should be fixed as reported already with #1559
