### ISSUE TITLE
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

### ISSUE THREAD

**Issue by davidwuest** [nextcloud/richdocuments#1653]
SQL server ok. All other nextcloud functions ok.

Getting error "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away" only when trying to install Collabora Online

**Comment by juliushaertl** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
