### ISSUE TITLE
Create new spreadsheet or presentation

### ISSUE THREAD

**Issue by maniutekk** [nextcloud/richdocuments#1657]
**Describe the bug**
When creating a new spreadsheet or presentation , the file is create but it is always a document writer

**To Reproduce**
Go to 'Files'
Click on '+'
Scroll down to 'New spreadsheet.'

Expected behavior
.xlsx extension

**Client details:**
Any

## Server details

**Operating system**: ubuntu focal

**Web server:**
Web server: Apache 2

**PHP version:**
PHP 7.4

**Nextcloud version:**
Nextcloud 22.0.0

**Version of the richdocuments app**
Collabora online 4.2.0

**Version of Collabora Online**
LibreOffice 7.0.7.0.0 (git hash: 626ea4e)

LOOLWSD
7.0.1 (git hash: a9d8a533)

**Comment by resoli** [comment]
Same happens under NC 21.0.4 and richdocuments v4.1.2

**Comment by resoli** [comment]
In my case it has been fixed fixed upgrading `collabora/code` image to latest.

**Comment by Samhamsam** [comment]
Same with NC 22 and richdocuments v6.4.0.*

**Comment by juliushaertl** [comment]
Please retest this with the latest code release 6.4.11.3
