### ISSUE TITLE
NC13, Cannot edit Files with Collabora in shared folders

### ISSUE THREAD

**Issue by rgl1234** [nextcloud/richdocuments#167]
Hi
I just upgraded to NC13 from NC12.05. No when I try to edit a file inside a folder shared with me by another user, I always get the following error: Document cannot be saved. Check your permissions or contact the storage server administrator.
File can be deleted within Nextcloud but cannot be edited within Collabora.

Editing of documents does not work, when they are shared with internal NC-Users. When Files/Folders are shared with an external user per e-mail-address, the external user can edit and save the documents.

Problem is maybe related to #150 

René

**Comment by skid9000** [comment]
Similar issue there.

"Échec de la lecture du document à partir du stockage. Veuillez contacter votre administrateur de serveur de stockage (cloud.nsa.ovh)."

I can't open a file shared to me, but fun fact, if the owner open the file, and i open it at the same time, it works ...

**Comment by thebearon** [comment]
Is this an external storage as well, similar to #150?

**Comment by skid9000** [comment]
Nope

**Comment by thebearon** [comment]
No issue here, then.

**Comment by AlexMaj** [comment]
have you tried to disable Versions App? it worked for me.

**Comment by rgl1234** [comment]
Thanks for this information. It works when I disable versioning app.....So might this be a bug in the versioning app?

**Comment by skid9000** [comment]
I tried to disable versioning app on my side but it still dosen't work :s

**Comment by rgl1234** [comment]
I still have the same problem after upgrading to VC 13.0.4
Nobody is in charge of this bug in the versioning or richdocuments app?

**Comment by andrimont** [comment]
Hello, I have this issue since Nextcloud  14.0.0
`Document cannot be saved to storage. Check your permissions or contact the storage server administrator.`
I tried to disable the **Versions** application. No success.

**Comment by juliushaertl** [comment]
I cannot reproduce this on Nextcloud 13-15 with the latest collabora/richdocuments. Please try with the newest versions. If the issue still persists, please reopen a new issue with a complete issue template filled out, so we have some more details about your setup.
