### ISSUE TITLE
Old text string in Transifex

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/richdocuments#1670]
There was an old text string again in Transifex today which was corrected in the commit: https://github.com/nextcloud/richdocuments/commit/9cbc840266ccd1e56b711876944c6e6efdce80ef .

![obraz](https://user-images.githubusercontent.com/47037905/125786926-bb62b474-84cc-490a-a7d4-bda00dc7a394.png)

**Comment by juliushaertl** [comment]
Thanks for pointing out. Translations are also pulled in for stable branches (https://github.com/nextcloud/richdocuments/blob/master/.tx/backport) 

Once backported with https://github.com/nextcloud/richdocuments/pull/1671 this should be fixed on the next sync.
