### ISSUE TITLE
Save document does not work.  - Strange behaviour random does not save. 

### ISSUE THREAD

**Issue by tobefrank1** [nextcloud/richdocuments#1675]
**Describe the bug**
Files will not be saved randomly:

Creating a doc file e.g. test.doc. 
Opening test.doc (with collabora online), edit (change) and save file.
No error, and file looks saved. 
Exit collabora online.
Open the docfile, nothing has been saved!!!!!!    
Opening the test.doc, edit (change) and save file.
No error, and file looks saved. 
Exit collabora online.
File is saved! Reopen saved file is OK,
Reopen test.doc, edit (change) and save file.
No error, and file looks saved. 
Exit collabora online.
Open the docfile, nothing has been saved!!!!!!    
Repeating does show it is random!?
I did not find out the pattern, when it is saved and when not.  

**To Reproduce**
see above.
Multiple users testet, local directory tested, external share testet. 

**Expected behavior**
File should be saved.

**Screenshots**

**Client details:**
 - OS: Win 10
 - Browser chrome, firefox, vivaldi 
 - Device: [e.g. iPhone6, desktop]

## Server details

**Operating system**:
Ubuntu 21.04
**Web server:**
nginx 
**Database:**
MariaDB
**PHP version:**
8.0
**Nextcloud version:**
Nextcloud 21.0.0.18 (21,0.3) / Nextcloud 21.0.2  - 2 different Servers 
**Version of the rich documents app**

**Version of Collabora Online**

6.4.1004 internal Version and external docker-version

No-problem with the open with libre office app.

**Comment by joergmschulz** [comment]
yes, a me-too here. NC21, PHP7.3 or 7.4 on several instances.
Files created from templates cannot be saved regularly, this is another issue (#1563).
Additionally, when copying data from .doc documents via the clipboard into an odt file that has been created using a template online or offline, the document cannot be saved, but we have an error telling something about not having enough disk space. Will look for traces in the log files later. The ugly workaround is to save-as the file locally.
What would be the best way to narrow / test the conditions for this failure?

**Comment by thebearon** [comment]
Please test with latest CODE 4.6.10-6, and if you're still experiencing issue, report it at the following URL, as I don't think these are related to the richdocuments app:
https://github.com/CollaboraOnline/online/issues

**Comment by tobefrank1** [comment]
Just like to confirm that de bug is solved in the CODE 6.4.10-6. I noticed a significant speed increase also :) !
Thank you
