### ISSUE TITLE
Feature Request: PDF Annotation / Commenting (as possible with odf documents)

### ISSUE THREAD

**Issue by ToxicDragon** [nextcloud/richdocuments#168]
I do not know whether this question fits into here or rather the collabora online project.

Anyway, I want to request the feature of PDF annotation (as already possible with odf files such as odt) My usecase: I want to share a pdf document with a group of people and have the ability to comment on the pdf directly from the web browser (as possible in e.g. the dropbox-, google docs or the collabora online web interface).

It were really nice, if you could implement this feature or at propose a workaround to my use case mentioned above. Thank you!

P.S.: As I have seen from the set of issues, the following feature request may be related to this one: #120

**Comment by thebearon** [comment]
Please open a bug report categorized as enhancement for LibreOffice Online: https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online
