### ISSUE TITLE
[QUESTION] Libreoffice needed?

### ISSUE THREAD

**Issue by neoacevedo** [nextcloud/richdocuments#1687]
Do I need to have LO installed in the server or in the client?

**Comment by juliushaertl** [comment]
Yes, the app needs a Collabora Online server to connect to. See https://nextcloud.com/collaboraonline/ for more details.

**Comment by neoacevedo** [comment]
@juliushaertl my question is about to have installed Libre Office in the server or the app, but your answer doesn't answer my question.

**Comment by thebearon** [comment]
@neoacevedo the client only needs a browser.
