### ISSUE TITLE
Enhancement: Local development environment

### ISSUE THREAD

**Issue by nithom** [nextcloud/richdocuments#171]
This is not an issue with the app, but maybe interesting for people getting started with the project.

While working on the app, I've created a little test environment which allows to run Collabora and Nextcloud locally on your machine. It is based on Docker compose.

It also works on platforms where Docker does not run natively. In this case, a Vagrant box is used.

You can find it at <https://github.com/nithom/nextcloud-collabora-env>.

**Comment by thebearon** [comment]
A discussion board might be a better place to mention this. Thanks!
