### ISSUE TITLE
[Feature] Multi insert of nextcloud images

### ISSUE THREAD

**Issue by freechelmi** [nextcloud/richdocuments#1717]
When you want to create a photo album from your nextcloud photos , you would like to be able to insert several pictures at once.

Right now you have to insert the pictures one by one.

The best would be to be able to select a folder and to say how many images you would like per page.

**Comment by juliushaertl** [comment]
Such a feature would need to be provided by Collabora, before we would be able to pass multiple files from Nextcloud to it. Please head over to https://github.com/collaboraonline/online for this first.
