### ISSUE TITLE
nextcloud collabora online error

### ISSUE THREAD

**Issue by despicable33** [nextcloud/richdocuments#172]
So I got Collabora runningon my cloud. but when I i.e. open an .xml, it showes me an error message instead of opening the file in web.
 The error displays the following:

Interner Serverfehler

Der Server konnte die Anfrage nicht fertig stellen.

Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an Deinen Server-Administrator.

Weitere Details können im Server-Protokoll gefunden werden.
Technische Details

    Entfernte Adresse: 
    Anfragekennung: kLfRIxb6KRqT0xlM9nrl

**Comment by patschi** [comment]
Can you see any relevant messages in your `data/nextcloud.log` file why this error is occuring?

**Comment by despicable33** [comment]
I solved the issue another way now, without having to use collabora
