### ISSUE TITLE
Built-in CODE not compatible with debian 11

### ISSUE THREAD

**Issue by SimplyCorbett** [nextcloud/richdocuments#1722]
The built in CODE server does not appear to be compatible with debian 11 from my initial testing. It works for me on debian 10, so I don't feel this is a configuration issue on my end.

If I'm wrong you can close the ticket.

**Comment by juliushaertl** [comment]
The built-in CODE server is maintained at https://github.com/CollaboraOnline/richdocumentscode so please open an issue there.
