### ISSUE TITLE
Using Collabora - Mouse click Bold, Italic, ... button when no highlighted text, writing is not possible anymore

### ISSUE THREAD

**Issue by pi317** [nextcloud/richdocuments#1736]
**Describe the bug**
Without having any text highlighted, if you use the mouse to change to Bold the toolbar indicates this action, but you can‘t carry on typing as the keyboard is not reacting anymore, if you mouse-click back to where you were typing the B button remains highlighted but un-highlights when typing resumes and the typed text is not bold. It is the same for Italics, Underline, Strikethrough, Subscript, Superscript, Increase Size and Decrease Size.

It is specific when using Collabora with Nextcloud. It does not appens when using collabora either with Alfresco ou Owncloud.

.

**To Reproduce**
1. Create a New Document using collabora from Nextcloud
2. Type a word
3. without selecting (no highlighted text) clic on Bold button
4. Try to continue writing - keyboard is not responsive
5. If you clic on the document where you want to write, you can keyboard become reactive again but not in Bold
6. The same happen whith other Button link italic, underline, ...

**Expected behavior**
I would expect to be able ton continue writing in bold after clicking on Bold button

**Screenshots**

**Client details:**
 - OS: windows
 - Browser : chrome, edge or firefox
 

## Server details

**Operating system**:
Ubuntu Linux
Type : mysql
Version : 10.3.29
PHP: Version : 7.3.29
**Nextcloud version:**
Nextcloud 22.1.1

**Version of the richdocuments app**
4.2.2

**Version of Collabora Online**
6.4.10-10

**Comment by thebearon** [comment]
Let's close this here, and track it over at https://github.com/CollaboraOnline/online/issues/3004 .
