### ISSUE TITLE
"Edit" button is positioned too low on mobile devices

### ISSUE THREAD

**Issue by scroom** [nextcloud/richdocuments#1738]
**Describe the bug**
As described above. Unfortunately, the button is positioned so low that you can hardly click it. Attached is a screenshot from an iPad and the Safari browser. However, the problem also occurs on other browsers. On chrome on the iPad the button isn't even visible.

**To Reproduce**
1. If logged in to Nextcloud click on an Office file
2. Collabora is loading
3. the "edit" button is positioned so low that is hardly clickable or even invisible and so Collabora Office could not be used to edit documents.

**Expected behavior**
Button should be visible and clickable

**Screenshots**
<img width="810" alt="2021-08-29 20-48-55-0" src="https://user-images.githubusercontent.com/5347731/131410414-e5364341-d7f1-4298-8511-dd829ea6c8df.png">
![IMG_0079](https://user-images.githubusercontent.com/5347731/131410430-696a61b5-9f7b-4ccb-a257-b4ab270fd77d.PNG)

**Client details:**
 - OS: IOS 
 - Browser: Safari and even worse Chrome
 - Version Chrome 92.0.4515.90
 - Device: iPad

## Server details

**Operating system**: Ubuntu 20.04

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7.4

**Nextcloud version:** 21.0.4

**Version of the richdocuments app** 4.2.2

**Version of Collabora Online** 6.4

**Comment by juliushaertl** [comment]
Can you maybe share where exactly you opened the document, e.g. if it was on Talk or the Dashboard or the regular files app?

**Comment by scroom** [comment]
It has been the files app.

**Comment by thebearon** [comment]
Based on the screenshots, it looks like the files have been opened from the dashboard to me.

**Comment by scroom** [comment]
> Based on the screenshots, it looks like the files have been opened from the dashboard to me.

Oops. You're right. I thought I had opened the files from the Files app. But after a test I just did, I can confirm that the Edit button in Safari and in Chrome on the iPad are displayed properly when Collabora is launched from the Files app.
However, when the app is launched from the Dashboard, the button is displayed too low.

**Comment by scroom** [comment]
Is it more of a bug in the Dashboard app then? @rullzer

**Comment by rullzer** [comment]
Why am I tagged here?

**Comment by scroom** [comment]
> Why am I tagged here?

I've seen that you are one of the main developers of the dashboard, and I didn't knew where it would be best to post this bug.

**Comment by Lebernd** [comment]
I have this issue now on the latest nextcloud office.

Server:
- nextcloud 23.0.1
- richdocuments 5.0.1
- collabora/code (docker) 21.11.1.4

Client:
- iPadOS 15.3
- Nextcloud-App 4.2.0.5

If I wouldn't look for the round button I would not see it. Just some pixels at the button of the window, I can't click. I am not able to edit the document.

The same client with a different/ older server works. 
- nextcloud 21.0.7
- richdocuments 4.2.3
- collabora/code (docker) 6.4.10 

IPad is iPad Pro 10,5 (MPME2FD/A 1709)

**Comment by hagak** [comment]
I also am having the same issue running the same versions of NC, richdocs and code as Lebernd.

Also I had no issues with NC 22

**Comment by X4Applegate** [comment]
I had same issues on samsung tab S8 plus 

Can anyone move button move like middle page. Instead way bottom? Or if you want preview then open file then add tab on top just like Google did that is most stable and viewable and editable

**Comment by andyxheli** [comment]
Still an issue on 

Server Config
- NC 25.0.1 
- Nextcloud Office 7.0.1 
- COOLWSD version: 22.05.7.3

Mobile Device S22 Ultra 

![image](https://user-images.githubusercontent.com/59488153/200054477-cb27f114-99e6-461f-b65f-8beabdc6e602.png)
