### ISSUE TITLE
Right to Left button is greyed out

### ISSUE THREAD

**Issue by SpecifiedNull** [nextcloud/richdocuments#1775]
![image](https://user-images.githubusercontent.com/83514712/134144415-d63cecac-5bc9-4892-a469-14c8f741bdbd.png)
 
### Steps to reproduce
1. Create a new document
2. Right to Left and Left to Right buttons are instantly grayed out when document is opened
3. Write with RTL languages but they are written from left to right making editing impossible as cursor jumps to the right when writing on the left.

### Expected behaviour
Tell us what should happen
RTL and LTR buttons should not be grayed out and should be able to click on them

### Actual behaviour
Tell us what happens instead
LTR and RTL buttons don't work and also the "Character" option under the "Format" setting doesn't include RTL fonts and spelling settings at all.
### Server configuration

**Operating system**:
Ubuntu 20.04
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
22.1.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install
**Where did you install Nextcloud from:**
Got the zip file from nextcloud.com website
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>
No errors have been found.
**List of activated apps:**
<details>
<summary>App list</summary>
- accessibility: 1.7.0
activity: 2.15.0
admin_audit: 1.11.0
bruteforcesettings: 2.2.0
cloudfederationapi: 1.4.0
comments: 1.11.0
dav: 1.18.0
duplicatefinder: 0.0.12
extract: 1.3.2
federatedfilesharing: 1.11.0
files: 1.16.0
files_downloadactivity: 1.11.1
files_mindmap: 0.0.25
files_pdfviewer: 2.3.0
files_rightclick: 1.1.0
files_sharing: 1.13.2
files_trashbin: 1.11.0
files_versions: 1.14.0
files_videoplayer: 1.11.0
files_zip: 1.0.0
logreader: 2.7.0
lookupserverconnector: 1.9.0
maps: 0.1.9
notes: 4.1.1
notifications: 2.10.1
oauth2: 1.9.0
password_policy: 1.12.0
photos: 1.4.0
privacy: 1.6.0
provisioning_api: 1.11.0
ransomware_protection: 1.11.0
richdocuments: 4.2.3
serverinfo: 1.12.0
settings: 1.3.0
sharebymail: 1.11.0
suspicious_login: 4.0.0
systemtags: 1.11.0
text: 3.3.0
theming: 1.12.0
theming_customcss: 1.9.0
twofactor_backupcodes: 1.10.1
twofactornextcloudnotification: 3.2.1
twofactor_totp: 6.1.0
video_converter: 1.0.3
viewer: 1.6.0
workflowengine: 2.3.1
Disabled:
calendar
circles
contacts
contactsinteraction
dashboard
encryption
federation
files_external
firstrunwizard
nextcloud_announcements
passwords
recommendations
side_menu
support
survey_client
updatenotification
user_ldap
user_status
weather_status
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
{

"system": {

    "instanceid": "\***REMOVED SENSITIVE VALUE**\*",

    "passwordsalt": "\***REMOVED SENSITIVE VALUE**\*",

    "secret": "\***REMOVED SENSITIVE VALUE**\*",

    "trusted_domains": [

        "nextcloud.mydomain.com",

    ],

    "datadirectory": "\***REMOVED SENSITIVE VALUE**\*",

    "dbtype": "mysql",

    "version": "22.1.1.2",

    "overwrite.cli.url": "https:\\/\\/cloud.goldenspade.ir",

    "dbname": "\***REMOVED SENSITIVE VALUE**\*",

    "dbhost": "\***REMOVED SENSITIVE VALUE**\*",

    "dbport": "",

    "dbtableprefix": "oc_",

    "mysql.utf8mb4": true,

    "dbuser": "\***REMOVED SENSITIVE VALUE**\*",

    "dbpassword": "\***REMOVED SENSITIVE VALUE**\*",

    "installed": true,

    "default*phone*region": "IR",

    "filelocking.enabled": true,

    "memcache.local": "\\\\OC\\\\Memcache\\\\Redis",

    "memcache.locking": "\\\\OC\\\\Memcache\\\\Redis",

    "redis": {

        "host": "\***REMOVED SENSITIVE VALUE**\*",

        "port": 6379

    },

    "mail_smtpmode": "smtp",

    "mail_smtpsecure": "ssl",

    "mail_sendmailmode": "smtp",

    "mail*from*address": "\***REMOVED SENSITIVE VALUE**\*",

    "mail_domain": "\***REMOVED SENSITIVE VALUE**\*",

    "mail_smtpauthtype": "LOGIN",

    "mail_smtpauth": 1,

    "mail_smtphost": "\***REMOVED SENSITIVE VALUE**\*",

    "mail_smtpport": "465",

    "mail_smtpname": "\***REMOVED SENSITIVE VALUE**\*",

    "mail_smtppassword": "\***REMOVED SENSITIVE VALUE**\*",

    "htaccess.RewriteBase": "\\/",

    "enable_previews": true,

    "enabledPreviewProviders": {

        "1": "OC\\\\Preview\\\\Movie",

        "2": "OC\\\\Preview\\\\MKV",

        "3": "OC\\\\Preview\\\\MP4",

        "4": "OC\\\\Preview\\\\AVI",

        "5": "OC\\\\Preview\\\\PNG",

        "6": "OC\\\\Preview\\\\JPEG",

        "7": "OC\\\\Preview\\\\GIF",

        "8": "OC\\\\Preview\\\\BMP",

        "9": "OC\\\\Preview\\\\Image",

        "10": "OC\\\\Preview\\\\HEIC"

    },

    "maintenance": false

}


}
or 

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO
**Are you using encryption:** yes/no
NO
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
FireFox
**Operating system:**
Windows 10
#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by thebearon** [comment]
I'm not seeing this problem, for me the buttons work. Nevertheless, this isn't a richdocuments issue, and should be reported over at: https://github.com/CollaboraOnline/online/issues
Please attach a sample document there as well.
