### ISSUE TITLE
Closing version history should return to the original editing view

### ISSUE THREAD

**Issue by thebearon** [nextcloud/richdocuments#1776]
**Describe the bug**
The version history has two close buttons, one in Collabora Online, and one in the Nextcloud sidebar. Clicking each closes that particular view (the additional "history" view of the document, or the sidebar with the list of versions), but the other still has to be closed to return to the editing view as it was before opening the history.

**To Reproduce**
1. Open a document,
2. Open File -> See history,
3. Close the history by either of the two (X)-es.

**Expected behavior**
You should get back to the editor, and the Nextcloud sidebar should disappear.
(note: currently the history view is editable, that's a separate bug in online, normally it's read-only)

**Client details:**
Normal desktop OS/browser, eg Linux + Firefox.

**Server details:**
Nextcloud 21 + richdocuments 4.2.3.

For the record, this used to work in old versions, but changed a few years ago. At that point it was still worked as expected if you closed the Collabora Online history view, and you only had to close them separately if you closed the NC sidebar first (or vice versa, I can't rememeber exactly), but now you have to close both.
@juliushaertl @eszkadev, what are your thoughts, what needs to be done for this to work again?

**Comment by juliushaertl** [comment]
Version preview is now handled differently through the viewer. Will close this.
