### ISSUE TITLE
Overrides OOXML file association with OnlyOffice

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/richdocuments#1783]
**Describe the bug**

I have Collabora and OnlyOffice installed in parallel.  A while back, Collabora has started registering itself as the default application for all office formats regardless of whether these apps are supposed to be handled by OnlyOffice (In /settings/admin/onlyoffice you can check boxes for all those file types for which OnlyOffice should be the default)

Until recently, the division of labour between both office suits was fine, Collabora was the default for OpenDocument files while OnlyOffice handled OOXML file. But a couple of weeks ago, Collabora has started to usurp everything. 

**To Reproduce**
1. Install both the OnlyOffice and Collabora connectors (and their respective backends)
2. Go to /settings/admin/onlyoffice and ensure that OnlyOffice is the default for OOXML files
3. Click a OOXML file (.docx, .xmlx., pptx)
4. See it opening in Collabora

**Expected behavior**
Should open in OnlyOffice

**Client details:**
 - OS: Linux, Windows
 - Browser: Firefox, Chrome
 - Version Firefox 91
 - Device: Desktop

## Server details

**Operating system**: Ubuntu 20.04

**Web server:**
Nginx

**Database:**
Mariadb

**PHP version:**
php-fpm 7.4

**Nextcloud version:**
22
**Version of the richdocuments app**
4.2.3
**Version of Collabora Online**
6.4.11

 

</details>

**Comment by vasyugan** [comment]
While this is a more specific issue, this is closely related to #1400

**Comment by juliushaertl** [comment]
Lets track this in #1400, currently running multiple office apps at the same time has some known limitations in that regard as there is no option to choose the default file opener per mimetype.

**Comment by vasyugan** [comment]
> Lets track this in #1400, currently running multiple office apps at the same time has some known limitations in that regard as there is no option to choose the default file opener per mimetype.

The proper solution would be a file association configuration applet just as in any desktop environment as [this report](https://github.com/nextcloud/server/issues/8105) suggests.
