### ISSUE TITLE
slow down index.php call stack DnsPinMiddleware.php

### ISSUE THREAD

**Issue by idreamerhx** [nextcloud/richdocuments#1791]
**Describe the bug**

**To Reproduce**
1. Go to 'new installed nextcloud 22.1.1'

**Expected behavior**

**Screenshots**

**Client details:**
 - Device: [e.g. iPhone6, desktop]

## Server details

**Operating system**:

**Web server:**
nginx

**Database:**
mysql (mariadb)

**PHP version:**
php7

**Nextcloud version:**
 22.1.1
**Version of the richdocuments app**
4.2.3
**Version of Collabora Online**
4.2.3

**Collabora Online - Built-in CODE Server	6.4.1103		 **

<details>
<summary>
(mys-homemedia) [root@mystorage /]# tail -n 100 /var/log/php-fpm7-www.log.slow
[0x00007f83b4014260] invokeWaitList() /opt/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php:226
[0x00007f83b40141e0] waitIfPending() /opt/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php:62
[0x00007f83b4014150] wait() /opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php:187
[0x00007f83b40140c0] request() /opt/nextcloud/lib/private/Http/Client/Client.php:223
[0x00007f83b4014010] get() /opt/nextcloud/apps/richdocuments/lib/Service/CapabilitiesService.php:102
[0x00007f83b4013f10] refetch() /opt/nextcloud/apps/richdocuments/lib/Service/CapabilitiesService.php:65
[0x00007f83b4013e40] getCapabilities() /opt/nextcloud/apps/richdocuments/lib/Capabilities.php:91
[0x00007f83b4013db0] getCapabilities() /opt/nextcloud/lib/private/CapabilitiesManager.php:69

[05-Oct-2021 12:15:18]  [pool www] pid 886
script_filename = /opt/nextcloud/index.php
[0x00007f83b4015b30] curl_exec() /opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php:44
[0x00007f83b4015a90] __invoke() /opt/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php:113
[0x00007f83b4015930] OC\Http\Client\{closure}() /opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php:35
[0x00007f83b4015850] __invoke() /opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php:31
[0x00007f83b40157a0] GuzzleHttp\{closure}() /opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php:71
[0x00007f83b4015700] __invoke() /opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php:99
[0x00007f83b4015640] checkRedirect() /opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php:73
[0x00007f83b40155b0] GuzzleHttp\{closure}() /opt/nextcloud/3rdparty/guzzlehttp/promises/src/FulfilledPromise.php:41
[0x00007f83b40154a0] GuzzleHttp\Promise\{closure}() /opt/nextcloud/3rdparty/guzzlehttp/promises/src/TaskQueue.php:48
[0x00007f83b4015410] run() /opt/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php:248
[0x00007f83b4015370] invokeWaitFn() /opt/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php:224
[0x00007f83b40152f0] waitIfPending() /opt/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php:269
[0x00007f83b4015260] invokeWaitList() /opt/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php:226
[0x00007f83b40151e0] waitIfPending() /opt/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php:62
[0x00007f83b4015150] wait() /opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php:187
[0x00007f83b40150c0] request() /opt/nextcloud/lib/private/Http/Client/Client.php:223
[0x00007f83b4015010] get() /opt/nextcloud/apps/richdocuments/lib/Service/CapabilitiesService.php:102
[0x00007f83b4014f10] refetch() /opt/nextcloud/apps/richdocuments/lib/Service/CapabilitiesService.php:65
[0x00007f83b4014e40] getCapabilities() /opt/nextcloud/apps/richdocuments/lib/Capabilities.php:91
[0x00007f83b4014db0] getCapabilities() /opt/nextcloud/lib/private/CapabilitiesManager.php:69

</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) 502
```

</details>

**Comment by juliushaertl** [comment]
Please share the full error message from your Nextcloud log. However if you are using a local ip or address please checkout the allow_local_remote_servers config.php option.

**Comment by idreamerhx** [comment]
thanks.

nextcloud.log seems nothing about this:

{"reqId":"Qcg7gJtJ1DSfvAwSjoOR","level":2,"time":"2021-10-05T08:44:18+00:00","remoteAddr":"192.168.1.10","user":"admin","app":"appstoreFetcher","method":"GET","url":"/settings/apps","message":"Could not connect to appstore: cURL error 28: Operation timed out after 60000 milliseconds with 741386 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://apps.nextcloud.com/api/v1/apps.json","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36","version":"22.1.1.2","id":"615c48e7c79ac"}

{"reqId":"mD4VD7ttut0SA9oHfZMm","level":3,"time":"2021-10-05T04:17:31+00:00","remoteAddr":"192.168.1.10","user":"admin","app":"settings","method":"POST","url":"/settings/apps/enable","message":"could not enable apps","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36","version":"22.1.1.2","exception":{"Exception":"GuzzleHttp\\Exception\\ConnectException","Message":"cURL error 28: Operation timed out after 120000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://github.com/nextcloud-releases/files_automatedtagging/releases/download/v1.12.0/files_automatedtagging-1.12.0.tar.gz","Code":0,"Trace":[{"file":"/opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":158,"function":"createRejection","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::"},{"file":"/opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":110,"function":"finishError","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::"},{"file":"/opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php","line":47,"function":"finish","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::"},{"file":"/opt/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php","line":146,"function":"__invoke","class":"GuzzleHttp\\Handler\\CurlHandler","type":"->"},{"file":"/opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php","line":35,"function":"OC\\Http\\Client\\{closure}","class":"OC\\Http\\Client\\DnsPinMiddleware","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":31,"function":"__invoke","class":"GuzzleHttp\\PrepareBodyMiddleware","type":"->"},{"file":"/opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php","line":71,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":63,"function":"__invoke","class":"GuzzleHttp\\RedirectMiddleware","type":"->"},{"file":"/opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php","line":75,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":331,"function":"__invoke","class":"GuzzleHttp\\HandlerStack","type":"->"},{"file":"/opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":168,"function":"transfer","class":"GuzzleHttp\\Client","type":"->"},{"file":"/opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":187,"function":"requestAsync","class":"GuzzleHttp\\Client","type":"->"},{"file":"/opt/nextcloud/lib/private/Http/Client/Client.php","line":223,"function":"request","class":"GuzzleHttp\\Client","type":"->"},{"file":"/opt/nextcloud/lib/private/Installer.php","line":297,"function":"get","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/opt/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":444,"function":"downloadApp","class":"OC\\Installer","type":"->"},{"file":"/opt/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/opt/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/opt/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/opt/nextcloud/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/opt/nextcloud/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/opt/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/opt/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","Line":210,"CustomMessage":"could not enable apps"},"id":"615c48e7c7a7a"}

{"reqId":"n6tjI0PDBfnxSofXsyhp","level":3,"time":"2021-10-05T04:12:57+00:00","remoteAddr":"192.168.1.10","user":"--","app":"core","method":"GET","url":"/cron.php","message":"Error while running background job (class: OCA\\Circles\\Cron\\Maintenance, arguments: )","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36","version":"22.1.1.2","exception":{"Exception":"TypeError","Message":"Argument 1 passed to ArtificialOwl\\MySmallPhpTools\\Model\\Request::setHost() must be of the type string, null given, called in /opt/nextcloud/apps/circles/vendor/artificial-owl/my-small-php-tools/lib/Model/Request.php on line 304","Code":0,"Trace":[{"file":"/opt/nextcloud/apps/circles/vendor/artificial-owl/my-small-php-tools/lib/Model/Request.php","line":304,"function":"setHost","class":"ArtificialOwl\\MySmallPhpTools\\Model\\Request","type":"->"},{"file":"/opt/nextcloud/apps/circles/lib/Service/ConfigService.php","line":665,"function":"basedOnUrl","class":"ArtificialOwl\\MySmallPhpTools\\Model\\Request","type":"->"},{"file":"/opt/nextcloud/apps/circles/lib/Service/FederatedEventService.php","line":421,"function":"configureLoopbackRequest","class":"OCA\\Circles\\Service\\ConfigService","type":"->"},{"file":"/opt/nextcloud/apps/circles/lib/Service/FederatedEventService.php","line":181,"function":"initBroadcast","class":"OCA\\Circles\\Service\\FederatedEventService","type":"->"},{"file":"/opt/nextcloud/apps/circles/lib/Service/SyncService.php","line":302,"function":"newEvent","class":"OCA\\Circles\\Service\\FederatedEventService","type":"->"},{"file":"/opt/nextcloud/apps/circles/lib/Service/SyncService.php","line":265,"function":"syncNextcloudGroup","class":"OCA\\Circles\\Service\\SyncService","type":"->"},{"file":"/opt/nextcloud/apps/circles/lib/Service/SyncService.php","line":174,"function":"syncNextcloudGroups","class":"OCA\\Circles\\Service\\SyncService","type":"->"},{"file":"/opt/nextcloud/apps/circles/lib/Service/MaintenanceService.php","line":251,"function":"sync","class":"OCA\\Circles\\Service\\SyncService","type":"->"},{"file":"/opt/nextcloud/apps/circles/lib/Service/MaintenanceService.php","line":165,"function":"runMaintenance4","class":"OCA\\Circles\\Service\\MaintenanceService","type":"->"},{"file":"/opt/nextcloud/apps/circles/lib/Cron/Maintenance.php","line":97,"function":"runMaintenance","class":"OCA\\Circles\\Service\\MaintenanceService","type":"->"},{"file":"/opt/nextcloud/apps/circles/lib/Cron/Maintenance.php","line":82,"function":"runMaintenances","class":"OCA\\Circles\\Cron\\Maintenance","type":"->"},{"file":"/opt/nextcloud/lib/private/BackgroundJob/Job.php","line":51,"function":"run","class":"OCA\\Circles\\Cron\\Maintenance","type":"->"},{"file":"/opt/nextcloud/lib/private/BackgroundJob/TimedJob.php","line":58,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/opt/nextcloud/cron.php","line":149,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->"}],"File":"/opt/nextcloud/apps/circles/vendor/artificial-owl/my-small-php-tools/lib/Model/Request.php","Line":214,"CustomMessage":"Error while running background job (class: OCA\\Circles\\Cron\\Maintenance, arguments: )"},"id":"615c48e7c7b17"}

this is because show internet speed to github in china. i download manually.

I set 'allow_local_remote_servers' => true,   still blocking.

Is this about dns resolve? How should I try to found the problems behind this.

**Comment by juliushaertl** [comment]
Those are not related to the richdocuments app. Could you check if there is any change if you save the Collabora server url in the settings once again after changing the config.php value?

**Comment by idreamerhx** [comment]
Hi,
I could only print the blocking (may be) vars by add print_r in DnsPinMiddleware.php:113

GuzzleHttp\Psr7\Request Object
(
    [method:GuzzleHttp\Psr7\Request:private] => GET
    [requestTarget:GuzzleHttp\Psr7\Request:private] => 
    [uri:GuzzleHttp\Psr7\Request:private] => GuzzleHttp\Psr7\Uri Object
        (
            [scheme:GuzzleHttp\Psr7\Uri:private] => https
            [userInfo:GuzzleHttp\Psr7\Uri:private] => 
            [host:GuzzleHttp\Psr7\Uri:private] => 192.168.1.17
            [port:GuzzleHttp\Psr7\Uri:private] => 
            [path:GuzzleHttp\Psr7\Uri:private] => /richdocumentscode/proxy.php
            [query:GuzzleHttp\Psr7\Uri:private] => req=/hosting/capabilities
            [fragment:GuzzleHttp\Psr7\Uri:private] => 
        )

    [headers:GuzzleHttp\Psr7\Request:private] => Array
        (
            [Host] => Array
                (
                    [0] => 192.168.1.17
                )

            [User-Agent] => Array
                (
                    [0] => Nextcloud Server Crawler
                )

            [Accept-Encoding] => Array
                (
                    [0] => gzip
                )

        )

    [headerNames:GuzzleHttp\Psr7\Request:private] => Array
        (
            [host] => Host
            [user-agent] => User-Agent
            [accept-encoding] => Accept-Encoding
        )

    [protocol:GuzzleHttp\Psr7\Request:private] => 1.1
    [stream:GuzzleHttp\Psr7\Request:private] => GuzzleHttp\Psr7\Stream Object
        (
            [stream:GuzzleHttp\Psr7\Stream:private] => Resource id #58
            [size:GuzzleHttp\Psr7\Stream:private] => 0
            [seekable:GuzzleHttp\Psr7\Stream:private] => 1
            [readable:GuzzleHttp\Psr7\Stream:private] => 1
            [writable:GuzzleHttp\Psr7\Stream:private] => 1
            [uri:GuzzleHttp\Psr7\Stream:private] => php://temp
            [customMetadata:GuzzleHttp\Psr7\Stream:private] => Array
                (
                )

        )

)

**Comment by idreamerhx** [comment]
Sorry and Thanks for your help, I found after a long time wait for setting of richdocuments in nextcloud. it points out  Collabora Online server ... reachable ...
And finally I set as it as here:
https://www.collaboraoffice.com/online/connecting-collabora-online-built-in-code-server-with-nginx/
