### ISSUE TITLE
Application activation freezes Nextcloud instance

### ISSUE THREAD

**Issue by Ollie89** [nextcloud/richdocuments#1817]
### Steps to reproduce
1. Installing and Activating via Store or via OCC (app:install richdocuments)

### Expected behaviour
After the installation and activation of the richdocuments application from the store, I expect to access the settings in order to perform the configuration. 

### Actual behaviour
The installation and activation of the richdocuments application from the store works, however, the Nextcloud instance then times out. Accessing the instance isn't possible anymore until the application is disabled via OCC. 

### Server configuration
**Operating system**:
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
22.2.0 (also affected 21.* Versions)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from older Nextcloud

**Where did you install Nextcloud from:**
Nextcloud

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.4
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.3
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - facerecognition: 0.8.3
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - mail: 1.10.5
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.3
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.1.2
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

**The content of config/config.php:**
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '1.1.1.1',
    1 => 'domain1',
    2 => 'domain2',
  ),
  'datadirectory' => '/mnt/drive/nextcloud',
  'dbtype' => 'mysql',
  'version' => '22.2.0.2',
  'dbname' => 'database',
  'dbhost' => '0.0.0.0',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'dbuser',
  'dbpassword' => 'dbpassword',
  'installed' => true,
  'maintenance' => false,
  'data-fingerprint' => '',
  'trusted_proxies' => 
  array (
    0 => '0.0.0.0',
  ),
  'default_phone_region' => 'DE',
  'loglevel' => 3,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'cloud',
  'mail_domain' => 'domain.com,
  'mail_smtphost' => '123.server.com',
  'mail_smtpport' => '587',

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration 1
**Browser:**
Opera
Firefox
Safari

**Operating system:**
macOS 11.6

### Client configuration 2
**Browser:**
Opera
Firefox
Edge
Chrome

**Operating system:**
Windows 10 1909 (ENT)

#### Web server error log
[Tue Oct 19 10:06:25.189751 2021] [mpm_prefork:notice] [pid 153986] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f configured -- resuming normal operations
[Tue Oct 19 10:06:25.189780 2021] [core:notice] [pid 153986] AH00094: Command line: '/usr/sbin/apache2'

#### Nextcloud log (data/nextcloud.log)
Cleared all entries, changed debug to 1. Restarted apache2 service = empty logs

Removing/renaming file nextcloud/apps/richdocuments/lib/AppInfo/Applications.php makes instance responsive, therefore seems to be related.

#### Browser log
N(index):1370 crbug/1173575, non-JS module files deprecated.
(anonymous) @ (index):1370

**Comment by HeyWatchOutDude** [comment]
I found out that issue only occurs when "Collabora Online - Built-in CODE Server" is enabled/installed, any idea?

**Comment by Ollie89** [comment]
> I found out that issue only occurs when "Collabora Online - Built-in CODE Server" is enabled/installed, any idea?
> 
> Collabora Online GUI output: Could not establish connection to the Collabora Online server.
> 
> Nextcloud Logs:
> 
> GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 45000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://cloud.domain.com/apps/richdocumentscode/proxy.php?req=/hosting/discovery

Hi @HeyWatchOutDude, 
I can't confirm that, as I didn't have the Built-in CODE Server installed when this issue rose up.

**Comment by nikdale** [comment]
> * occ config:app:delete richdocuments wopi_url

For anyone wondering, this solved the issue for me also!
Thanks!

If you did not use docker, simple as this:
`sudo -u www-data php /var/www/nextcloud/occ config:app:delete richdocuments public_wopi_url`
and
`sudo -u www-data php /var/www/nextcloud/occ config:app:delete richdocuments wopi_url`
