### ISSUE TITLE
Improve setup checks

### ISSUE THREAD

**Issue by juliusknorr** [nextcloud/richdocuments#1835]
- Check discovery/capabilities on the backend and return a proper status with additional details if something failed (connection issue/timeout)
- Check protocol to be equal between discovery response and the requesting URL of the admin page https://github.com/nextcloud/richdocuments/pull/2095
- Validate discovery response in the frontend, so that Collabora can be reached in the browser
- Have a way to validate connectivity from Online to Nextcloud through https://github.com/CollaboraOnline/online/pull/4353

@kendy I think it would be quite nice if we could have some kind of validation endpoint in online that would perform wopi operations during setup with a test file and report back possible error messages that might have happened. Then we could directly show the user a hint that e.g. if Collabora could not reach Nextcloud when configuring. What do you think about that?

**Comment by juliushaertl** [comment]
Started hacking on a check endpoint on the collabora side - WIP at https://github.com/CollaboraOnline/online/pull/4353
