### ISSUE TITLE
No preview for OOXML documents in nextcloud/files

### ISSUE THREAD

**Issue by RTrave** [nextcloud/richdocuments#1837]
In Nextcloud21/22 with RichDocuments 4.2.3, OOXML documents don't show anymore preview in nextcloud/files, like ODF documents do.

**To Reproduce**
1. Go to a folder containing OOXML and ODF documents in File App
2. See ODF previews of documents, but default icon for OOXML ones

**Expected behavior**
As far as Nextcloud20, both formats display previews.

**Comment by juliushaertl** [comment]
I cannot reproduce any issue with the preview generation. For ODF files the Nextcloud server provides a default preview generator. If preview generation from Collabora is not working I'd suggest to check if your Nextcloud server is part of the post_allow list in the loolwsd.xml config of Collabora Online.

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
