### ISSUE TITLE
Opening document results in "Document Name" - Nextcloud 22 + Collabora Online + Built-in CODE Server 

### ISSUE THREAD

**Issue by Maingron** [nextcloud/richdocuments#1851]
I just updated my Nextcloud to 22.2 and installed CODE and the integrated CODE Server.
There weren't any issues during upgrades or when installing the CODE apps and I did those procedures multiple times professionally, already. In other configurations it just worked at this stage.
Anyway:

## Expected behaviour:
Being able to edit a document

## Actual behaviour:
Document kinda opens but only states `Document Name`
![grafik](https://user-images.githubusercontent.com/47825439/140742568-13f4188e-c3f0-4328-98cb-482d1e4f2cbf.png)

## Steps to reproduce
1. Create Document
2. Try to open document

## Errors, ...
There are no related server-side errors visible to me, only some contacts-related stuff.

Within the browser console though, I was able to find some errors:
```
Uncaught TypeError: sheets[i].href is null
    <anonymous> https://█████.de/cloud/apps/richdocumentscode/proxy.php?req=/loleaflet/078e8b8/loleaflet.html?WOPISrc=https://█████.de/cloud/index.php/apps/richdocuments/wopi/files/68913_ocbxl3qdqrga&title=New Test Document.odt&lang=en&closebutton=1&revisionhistory=1:230
    EventListener.handleEvent* https://█████.de/cloud/apps/richdocumentscode/proxy.php?req=/loleaflet/078e8b8/loleaflet.html?WOPISrc=https://█████.de/cloud/index.php/apps/richdocuments/wopi/files/68913_ocbxl3qdqrga&title=New Test Document.odt&lang=en&closebutton=1&revisionhistory=1:230
    <anonymous> https://█████.de/cloud/apps/richdocumentscode/proxy.php?req=/loleaflet/078e8b8/loleaflet.html?WOPISrc=https://█████.de/cloud/index.php/apps/richdocuments/wopi/files/68913_ocbxl3qdqrga&title=New Test Document.odt&lang=en&closebutton=1&revisionhistory=1:230
```
![grafik](https://user-images.githubusercontent.com/47825439/140743220-ae206f63-8030-40fd-88f1-d901215f3306.png)

## Testing done
I do not want to completely reconfigure my cloud for testing right now, but I think it might be related to the Nextcloud setting that removes index.php from the Nextcloud Uri. In the errors I can see that it tries to access */cloud/index.php, but I think it's supposed to access */cloud/apps/rich...  
Using a file name without a space didn't change anything.  
Tried Chrome and Firefox on Windows 10

## System Information
Everything should be at the latest version as of today, 2021-11-08.
Using apache2, mariadb and php.  
File encryption is enabled.  
According to the Nextcloud System page:
Operating System: | Linux 4.19.0-17-amd64 x86_64
-- | --
CPU: | Intel Xeon E312xx (Sandy Bridge, IBRS update) (2 cores)
Memory: | 3.85 GB

vda1
Mount: /
Filesystem: ext4
Size: 42.94 GB
Available: 19.37 GB
Used: 55%

**PHP**
8.0.11  
Memory Limit: 1 GB  
Max Execution Time: 3600  
Upload max size: 4 GB  

**Database**
mysql  
10.3.31  
35.6 MB  

## config.php
```php
<?php
$CONFIG = array (
  'instanceid' => '█████',
  'passwordsalt' => '█████',
  'secret' => '█████',
  'trusted_domains' => 
  array (
    0 => '█████',
  ),
  'datadirectory' => '█████',
  'dbtype' => 'mysql',
  'version' => '22.2.0.2',
  'overwrite.cli.url' => 'https://█████/cloud',
  'dbname' => '█████',
  'dbhost' => '█████',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '█████',
  'dbpassword' => '█████',
  'installed' => true,
  'skeletondirectory' => '',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'logfile' => '/var/log/█████/█████.log',
  'default_phone_region' => 'DE',
  'default_language' => 'en',
  'default_locale' => 'en_US',
  'knowledgebaseenabled' => false,
  'lost_password_link' => 'disabled',
  'htaccess.RewriteBase' => '/cloud',
  'versions_retention_obligation' => 'auto, 40',
  'trashbin_retention_obligation' => 'auto, 40',
  'cache_path' => '/var/cache/apache2/█████/nc',
  'blacklisted_files' => 
  array (
    0 => '.dontcloudme',
  ),
  'simpleSignUpLink.shown' => false,
  'updater.release.channel' => 'stable',
  'objectstore.multibucket.preview-distribution' => true,
  'updater.secret' => '█████',
);

```

If you need more information or a test user, make sure to let me know.

**Comment by juliushaertl** [comment]
The console error seems to be coming from https://github.com/CollaboraOnline/richdocumentscode so maybe you can check if there is an update available (i couldn't find which version you are using in your report) and otherwise report the issue over there.
