### ISSUE TITLE
Global tempaltes

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/richdocuments#1868]
Add one or more global templates
The 3 empty ones will be shown additional:
Tested with the latest stable and the latest beta, no difference
![image](https://user-images.githubusercontent.com/24530680/142603065-d6c33b81-d940-4cca-9923-b143511b43ed.png)

**Comment by juliushaertl** [comment]
Yes, it is not possible to remove the empty templates, also with the new template creation in the server there will always be the option to create an empty file.
