### ISSUE TITLE
Support for coolwsd(.service)

### ISSUE THREAD

**Issue by Bables55** [nextcloud/richdocuments#1876]
**Is your feature request related to a problem? Please describe.**
Yes. I can't connect to the server.

**Describe the solution you'd like**
Since loolwsd has been replaced by coolwsd, I would like to see support for it.

 **Describe alternatives you've considered**
none

**Comment by szimszon** [comment]
Me too...

I got coolwsd working. I migrated SSL and IP settings and domain name settings from loolwsd.xml to coolwsd.xml so I can connect to the service.

From nextcloud I got just a blank page when I click on a document.

code-brand                21.11-9

```
$ dpkg -l *coolwsd*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  coolwsd        21.11.0.3-1  amd64        Collabora Online WebSocket Daemon
```

**Comment by Bables55** [comment]
I rewrote the nginx reverse proxy using [this](https://sdk.collaboraonline.com/docs/installation/Proxy_settings.html) as a reference. I believe that there is probably no problem on the collabora.example.com side.

**Comment by szimszon** [comment]
I adjusted the Apache2.

The fancy thing is that I didn't get any request on Apache side at all...

**Comment by Bables55** [comment]
There was also a flaw in my file structure. I did not have the necessary files in my /etc/coolwsd, so I copied the files from /etc/loolwsd. I was then able to take the connection to Collabora one step further in Nextcloud.

While the screen is trying to transition to Collabora, I will see "The server has been disconnected." at the bottom.
coolwsd.service is in the active state.

**Comment by szimszon** [comment]
@Bables55 sorry for a noob question. 
Do you have now a working solution?

**Comment by Bables55** [comment]
@szimszon 
Excuse me. I don't know that much about it either. I'm just trying to find the error and deal with it.

**Comment by szimszon** [comment]
Okay. I was not sure if your last message about to correct the file structure solved the issue or not...

Interesting [cool search](https://github.com/nextcloud/richdocuments/search?q=cool) vs. [lool search](https://github.com/nextcloud/richdocuments/search?q=lool)

**Comment by Bables55** [comment]
At any rate, I have succeeded in "connecting to the Collabora server". At first I was not able to. 

The following message appears momentarily and then disappears.
1. "Document name" in the upper left corner.
2. "The server has been disconnected." at the bottom.

![image](https://user-images.githubusercontent.com/30524004/143577952-8fb4d916-d400-40b6-ac47-81c6d68f4f9d.png)

**Comment by juliushaertl** [comment]
There is no need for additional support to be implemented within Nextcloud itself. You will need to uninstall loolwsd and install coolwsd from the code packages and make sure that your previous loolwsd.xml config is adapted in the coolwsd.xml as well. What also needs adjustments is the possible reverse proxy configuration to basicall replace any occurence of loleaflet with browser and lool with cool.

@kendy @pedropintosilva I guess you already have this on your list to update the documentation accordingly? 

https://www.collaboraoffice.com/code-install-and-test/
https://www.collaboraoffice.com/code/linux-packages/

Still seem to point to loolwsd. Probably might be nice to have some sort of upgrade guide as well, to tell people to switch the loolwsd to coolwsd package.

**Comment by juliushaertl** [comment]
Ah we should of course also update the docs in https://github.com/nextcloud/richdocuments/blob/81b09056fdcc7d3a845bf1ba0c2e7f4d179d1c10/docs/install.md

**Comment by szimszon** [comment]
I _think_ I did every step successfully and still I get an empty page if I click on the document.

**Comment by Bables55** [comment]
> There is no need for additional support to be implemented within Nextcloud itself. You will need to uninstall loolwsd and install coolwsd from the code packages and make sure that your previous loolwsd.xml config is adapted in the coolwsd.xml as well. What also needs adjustments is the possible reverse proxy configuration to basicall replace any occurence of loleaflet with browser and lool with cool.

Thanks!
I had rewritten nginx reverse proxy referring to the [site](https://sdk.collaboraonline.com/docs/installation/Proxy_settings.html) I wrote above. I stopped doing that and simply replaced "lool" and "loleaflet" with "cool" and "browser" in the nginx reverse proxy I was using for loolwsd. Then my Collabora was revived.

**Comment by szimszon** [comment]
Then I have still a config error somewhere... :(

**Comment by Bables55** [comment]
This site offered the following sample, but I seem to have been foiled by it.
`location ~ ^/(c|l)ool {`

I wrote the following and it worked for Collabora.
`location ^~ /cool {`

**Comment by juliushaertl** [comment]
If you get an empty site, you may try to save the Collabora URL in the nextcloud settings again and see if that changes anything.

**Comment by szimszon** [comment]
```
[26/Nov/2021:13:44:15 +0100] "GET /apps/richdocuments/index?fileId=4&requesttoken=Km74UNYfnG...mwh6B0%3D HTTP/2.0"
```
I get only this in my apache log and nothing for the code ;(

![image](https://user-images.githubusercontent.com/745542/143583250-2ceade3a-7219-42dc-86b8-b07eae37f01c.png)

Checked and re-enabled, disabled and enabled the app multiple times. Nothing changed.

**Comment by szimszon** [comment]
When I reconfigure the app then I see a discovery query:
```
[26/Nov/2021:13:46:43 +0100] "GET /hosting/capabilities HTTP/1.1" 200 5757 "-" "Nextcloud Server Crawler"
```

This is working.

And no addition request when I click on a odt.

**Comment by Bables55** [comment]
I specify the port number as in "https://office.example.com:443".

**Comment by szimszon** [comment]
I found something in the discovery response:

http://office.oregpreshaz.eu:443/browser/b5534c4/cool.html

http:// instead of https:// ... :(

**Comment by szimszon** [comment]
I missed the line in coolwsd.xml

<termination desc="Connection via proxy where coolwsd acts as working via https, but actually uses http." type="bool" default="true">**true**</termination>


It was set to false by default (not the default= instead the actual value)

Thanks for the help!

**Comment by gabor-ig** [comment]
I had the same issue, to me the solution was changing
`<listen type="string" default="any" desc="Listen address that coolwsd binds to. Can be 'any' or 'loopback'.">all</listen>
`
to

`<listen type="string" default="any" desc="Listen address that coolwsd binds to. Can be 'any' or 'loopback'.">IPv4</listen>
`
I do not understand the details, but with loolwsd it also used to be just IPv4. Hope this helps someone else as well!
