### ISSUE TITLE
Writer: Field "Time" always shows the time in UTC

### ISSUE THREAD

**Issue by GitWidi** [nextcloud/richdocuments#1878]
When I insert a field of type "Time" it always shows the time in UTC, no matter which time zone is chosen on the system.

### Steps to reproduce the behavior:
1. Create a "New document"
2. Insert > Field > Document
   - Type: Time
   - Select: Time
   - Format: 13:37:46
   - [Insert]
3. The current time is inserted but shown as UTC, not the current local time.

Screenshot:
![image](https://user-images.githubusercontent.com/4623128/143609070-b4f26231-1b46-45f6-8e59-fda3b3c42199.png)

### Expected behavior
I excpect the local time, as it works in the desktop variant of LibreOffice.

### Client details:
 - OS: Windows 10 Version 20H2 (Build 19042.1348)
 - Browser: Vivaldi 4.3.2439.65 (Stable channel) (64-Bit)
### Server details:
 - OS: Linux cloud 4.9.0-16-amd64 SMP Debian 4.9.272-2 (2021-07-19) x86_64 GNU/Linux
 - Nextcloud: 22.2.3
 - PHP: 8.0.13
 - App **Collabora Online**: V4.2.3
 - Collabora Online server: 
     - Docker image: collabora/code, 21.11.0.3.1
     - Collabora Office 21.06.8.1
     - COOLWSD: 21.11.0.3

### Further information
This issue occurs not at the desktop editions (standalone) of LibreOffice.
But I don't know if it is due to the software package LibreOffice-Online (LOOL), the package Collabora Online Development Edition (CODE) or rather the integration in Nextcloud (App: Collabora Online). 

see also: https://bugs.documentfoundation.org/show_bug.cgi?id=136347

Regards,
Friedbert

**Comment by juliushaertl** [comment]
This seems to be a bug in Collabora Online itself, could you please head over to https://github.com/collaboraonline/online and open the issue there? :)
