### ISSUE TITLE
Missing icons in the Add dialog

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/richdocuments#1891]
richdocuments 5.0.0
latest docker collabora
![image](https://user-images.githubusercontent.com/24530680/144594816-ed99f10c-43a4-4e0e-98df-2b947b1b5dda.png)

**Comment by juliushaertl** [comment]
Seems it misses to include the css/viewer.css file when loading the viewer.js bundle

**Comment by joshtrichards** [comment]
Haven't seen this problem in awhile. Closing. Let me know if you're still seeing it and will look into it.
