### ISSUE TITLE
1st row in excel document is hidden

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/richdocuments#1892]
richdocuments 5.0.0
latest docker collabora
Can't scroll further up, I'm on top:

![image](https://user-images.githubusercontent.com/24530680/144595069-182f2a05-26b2-4a12-b9a3-98ee12eae54d.png)

On mobile it's shown

**Comment by juliushaertl** [comment]
Could you tell which exact version of Collabora you are running into that? Ideally with the git hash from the Help > About dialog?

**Comment by jakobroehrl** [comment]
COOLWSD version:
21.11.0.3
git hash: 
b5534c4
LOKit version:
Collabora Office 21.06.8.1
git hash: 
68738ca

and on 

COOLWSD version:
21.11.0.5
git hash: 
15dc78e
LOKit version:
Collabora Office 21.06.9.1
git hash: 
e60ec9f

**Comment by juliushaertl** [comment]
I cannot reproduce on latest master abc15917 online nor on the mentioned 15dc78e Is it maybe related to a specific browser?

**Comment by jakobroehrl** [comment]
It seams your are right. 
With cromium it's not working.
Edge eg is working

**Comment by juliushaertl** [comment]
Seems also fine here with Version 96.0.4664.45
![image](https://user-images.githubusercontent.com/3404133/144986785-b7fe99e6-06d9-430b-bffe-1639a639e413.png)

**Comment by jakobroehrl** [comment]
this is gone
