### ISSUE TITLE
header: filename is over timestamp

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/richdocuments#1893]
richdocuments 5.0.0
latest docker collabora

![image](https://user-images.githubusercontent.com/24530680/144595360-33204eaa-ec3c-46b2-9438-49dd5301493d.png)

**Comment by juliushaertl** [comment]
@luka-nextcloud Could you maybe check that?

**Comment by juliushaertl** [comment]
OK I cannot reproduce this:

![image](https://user-images.githubusercontent.com/3404133/144982948-b12798b5-9619-4a9b-b9e0-34c53f1debf0.png)

@jakobroehrl Maybe you could also tell which browser was in use and which exact collabora version ;)

**Comment by jakobroehrl** [comment]
Resize your browser window. 
Tested with chromium.

COOLWSD version:
21.11.0.5
git hash: 
15dc78e
LOKit version:
Collabora Office 21.06.9.1
git hash: 
e60ec9f

**Comment by juliushaertl** [comment]
Yes, I have an overlap on the name/menu, looking into that right now:
![image](https://user-images.githubusercontent.com/3404133/144985712-3d2a8952-5d28-4a30-a5ca-c0b75e3fe99a.png)

 but the last modified date should be right aligned and also adapts to too small viewports by hiding the title then:
![image](https://user-images.githubusercontent.com/3404133/144985769-26e30828-a89c-4743-a603-5e9317005d04.png)

The thing I cannot reproduce is the filename over timestamp

**Comment by jakobroehrl** [comment]
Gone with the latest docker
