### ISSUE TITLE
Edit pdf files with Collabora Online isn't available any more

### ISSUE THREAD

**Issue by Andreas-Kainz** [nextcloud/richdocuments#1894]
**Describe the bug**
In the past there was the option to open a pdf file with collabora online which isn't possible any more.

**Comment by Andreas-Kainz** [comment]
Issue with NextCloud Hub II where you switch to nextcloud office

**Comment by sebastiaanveld** [comment]
Just ran into this, hope this gets fixed.

**Comment by brtptrs** [comment]
This regression breaks a number of internal administrative workflows for us, and many users are complaining. To help moving this forward, I'll be happy to do some testing once some code is available.
