### ISSUE TITLE
Feature request: Possibility to add menu item to NC menu

### ISSUE THREAD

**Issue by scroom** [nextcloud/richdocuments#19]
### Steps to reproduce
1. Configure your server e.g. following this guide: https://nextcloud.com/collaboraonline/
2. Add the collabora app to NC and configure it

### Expected behaviour
I've expected at least the possibility to add a Collabora app menu item to the NC menu

### Actual behaviour
I just can open the app by clicking on an office document. If I want to create a new file I have to create new file, choose a name and then I have to click on it to open it in the Collabora app. Known usage pattern from desktop office documents is regularly vice versa (click on the app, create new file etc.).

**Comment by oparoz** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
@scroom we made it so that it’s well-integrated in Files. It’s like on the desktop, where you can open files straight from there, and you can create documents also. You don’t need an extra app to switch to as it would offer no added benefit. :)

**Comment by AlfredSK** [comment]
But, but there is this picture on apps.nextcloud.com... :)

![screenshot_2017-03-30-00-43-59](https://cloud.githubusercontent.com/assets/3656054/24480011/7f9518c0-14e2-11e7-8790-fae283796f2b.png)

@jancborchardt

**Comment by jancborchardt** [comment]
@timar can you remove that outdated picture from https://apps.nextcloud.com/apps/richdocuments ? :)

**Comment by jancborchardt** [comment]
@timar can you remove that outdated picture from https://apps.nextcloud.com/apps/richdocuments ? :)

**Comment by jancborchardt** [comment]
@timar @nextcloud/appstore  can you remove that outdated picture from https://apps.nextcloud.com/apps/richdocuments ? :)

**Comment by BernhardPosselt** [comment]
Screenshots are read from the info.xml so its the devs responsibility to update them :)

**Comment by timar** [comment]
I released 1.11.28 and 1.12.28 with updated screenshots.

**Comment by jancborchardt** [comment]
@timar thanks a lot! :)
