### ISSUE TITLE
[Feature Request] Support end-to-end encryption

### ISSUE THREAD

**Issue by DreamFlasher** [nextcloud/richdocuments#190]
It's great that nextcloud now supports end-to-end encryption. Unfortunately, collaborative editing is not possible with encrypted folders.
https://nextcloud.com/blog/encryption-in-nextcloud/

> However, it comes with a feature loss as any type of online file editing and access to encrypted data as well as public sharing and sharing to groups is not possible for data in folders that are end-to-end encrypted.

Please add the possibility to edit documents end-to-end encrypted.

**Comment by rullzer** [comment]
This is not possible.

You'd need to hand over your private keys to collabora which would make the whole end to end encrypted useless.

**Comment by DreamFlasher** [comment]
That's BS. There is no technological reason preventing e2e with collaborative editing. OX Documents is apparently supporting it: https://oxpedia.org/wiki/index.php?title=AppSuite:OX_Guard

**Comment by rullzer** [comment]
Well explain to me how it will work then without giving collabora access to your private key? You can't even access your end to end encrypted files from the nextcloud web interface.

The whole point of end to end encryption is that you don't trust the server. So you don't want to provide the server with your unlocked private key. This of course also holds true for any other service that is controlled by the same admin (like collabora here).

**Comment by DreamFlasher** [comment]
Well I'd recommend reading up a bit on encryption then. This is a standard scheme that has been in use with PGP for email for ages, and is by now adopted all over the place. 
Have a public key exchange between users, transfer the symmetric key for document encryption via that.

**Comment by rullzer** [comment]
That is not an answer to my question at all.

The problem here is that you don't download the file to your computer to edit. You open the file on your collabora server. So you need to give the collabora server access to the decryption key. However, the whole point of the end to end encryption is that the data is never unencrypted on the server.

But if you think there is a secure way please open a pull request.

**Comment by DreamFlasher** [comment]
It is exactly an answer to your question. Just don't encrypt on the server side (that's the whole point of end to end encryption), but do it on the client. There is PGP and Omemo for JavaScript.

**Comment by rullzer** [comment]
Collabora is not just javascript. It runs libreoffice on the server.

But as said feel free to submit a PR that can do this
