### ISSUE TITLE
"New graphic" wording enhancement

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/richdocuments#1903]
Small wording issue about Draw: In the "New" menu it says "New graphic" which stumped me a bit since "graphic" is also a word for "gruesome". A better word seems to be "New diagram".

As discussed @juliushaertl :)

**Comment by juliushaertl** [comment]
@luka-nextcloud should be a quick fix, could you have a look into that?

**Comment by brtptrs** [comment]
The new wording conflicts with the fantastic drawio module.
https://apps.nextcloud.com/apps/drawio
![image](https://user-images.githubusercontent.com/8102905/162756608-f401b794-6f86-4f17-b84b-076a95198e3a.png)
Maybe "New drawing" would be better?

**Comment by juliushaertl** [comment]
What do you think @jancborchardt ?
