### ISSUE TITLE
Color and alignment issues in merged menu bar (v5/NC23)

### ISSUE THREAD

**Issue by ya-d** [nextcloud/richdocuments#1905]
**Describe the bug**

- Some of the icons in the new merged menu bar in NC23 have wrong coloring: thick grey lines and shapes for Collabora-icons, dark instead of light for NC-icons (sidebar, close).
- Also alignment of file name and hover effect for Collabora-icons is off (wrong style too).
- The icon for Nextclouds sharing sidebar should probably appear right of Collaboras sidebar as the sidebar itself is more to the right as well. Next to close button.
- Looks awesome otherwise ❤️ 

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/30781876/145406085-c81d09ca-126a-4df5-8f4c-bbe04b2f0866.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/30781876/145406007-5c84e66a-f975-47de-bba9-90b393d5d089.png">

**Client details:**
NC23
richdocuments 5.0.0
COOLWSD 21.11.0.5 via official docker image

**Comment by jancborchardt** [comment]
Thanks @ya-d! :) All of this will be addressed and fixed with the NotebookBar design refresh: https://github.com/nextcloud/richdocuments/issues/1976 (in progress screenshot, see the text for further fixes which will be done)
