### ISSUE TITLE
Collabora Online won't open app through web browser. Only within Android app.

### ISSUE THREAD

**Issue by wangcow** [nextcloud/richdocuments#1906]
**Describe the bug**
Installed Collabora Online - Built-in CODE Server (arm64) then Collabora Online within my Nextcloud Server. When opening an .ods or .odt file within any browser (tried chromium, chromium on android, firefox, edge, and gnome web), I am stuck with a 'Loading Example.ods...' or 'Loading Example.odt...' with a spinning loading wheel that goes on infinitely above the text and a cancel button below the text. I've tried opening both existing files and creating new files (spreadsheets, documents). 

The weird thing is that if I use the Android Nextcloud App, I can access the file and edit without issue as it was prior to reinstalling and setting up my server. 

Chromium Console shows:
"Opening viewer for file  /Documents/Example.ods" then "oc_defaults is deprecated: use OC.theme instead, this will be removed in Nextcloud 20" then "Fetching additional files..." then "OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment" then "No new notification data received" and "Polling interval updated to 30000". 

**To Reproduce**
1. Go to Files
2. Open any .ods or .odt file
3. See error

**Expected behavior**
Expecting the spreadsheet or document to load when clicked as it currently does within my Nextcloud Android app.

**Screenshots**
Sorry, nothing really pertinent.

**Client details:**
 - OS: Windows 10 (i7-9700k Desktop), Arch Linux(Thinkpad x230t), and Android 11 (Oneplus 6t)
 - Browser: Chrome, Firefox, Edge, Gnome Web, Chromium Android

## Server details

**Operating system**: Debian Bullseye (DietPi)

**Web server**: DietPi on an Odroid N2 ARMv8 

**Database**: mariadb v 15.1

**PHP version**: 7.4

**Nextcloud version**: 23.0.0

**Version of the richdocuments app**: ?

**Version of Collabora Online**: v5.0.0

**Comment by joshtrichards** [comment]
What do your server-side logs indicate?

**Comment by joshtrichards** [comment]
Closing due to insufficient info.
