### ISSUE TITLE
Office integration doesn't work for folders with edit permissions shared via link/email with external users

### ISSUE THREAD

**Issue by tgurr** [nextcloud/richdocuments#1914]
**Describe the bug**
Shared files via URL, e.g. manually done or via share by email adress results in the office integration not working.

First it's loading
![Screenshot_20211213_101015](https://user-images.githubusercontent.com/414984/145784097-61e8b2b9-0f12-4394-86e9-0f7d3727663c.png)
Then just showing an error:
![Screenshot_20211213_101034](https://user-images.githubusercontent.com/414984/145784105-c7de2295-ec9b-403a-a9ca-d3e1bc760915.png)

Note that the office integration works just fine when using it via a user that logged in to Nextcloud via username and password, just the "external" shares appear to be affected.

**To Reproduce**
1. Share document via Link
2. External user tries to open the document for online editing
3. See error

**Expected behavior**
Be able to view/edit files like it worked before and still does for logged in users.

**Screenshots**
See above.

**Client details:**
 - OS: Linux/Windows
 - Browser: Chrome/Firefox
 - Version Latest stable versions
 - Device: Desktop

## Server details

**Operating system**: Linux

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 8.0.13

**Nextcloud version:** 23

**Version of the richdocuments app** 5.0.0

**Version of Collabora Online** 21.06.9.1

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
No errors logged.
```

#### Browser log
When the actual errors "Document loading failed" appears:
```
Office.vue:198 FAILED
(anonymous)	@	Office.vue:198
setTimeout (async)		
load	@	Office.vue:197
mounted	@	Office.vue:184
await in mounted (async)		
We	@	vue.runtime.esm.js:1863
un	@	vue.runtime.esm.js:4235
insert	@	vue.runtime.esm.js:3158
D	@	vue.runtime.esm.js:6390
vo.nodeOps	@	vue.runtime.esm.js:6609
e._update	@	vue.runtime.esm.js:3963
r	@	vue.runtime.esm.js:4081
bn.get	@	vue.runtime.esm.js:4495
bn.run	@	vue.runtime.esm.js:4570
yn	@	vue.runtime.esm.js:4326
(anonymous)	@	vue.runtime.esm.js:1989
et	@	vue.runtime.esm.js:1915
Promise.then (async)		
Xe	@	vue.runtime.esm.js:1942
it	@	vue.runtime.esm.js:1999
(anonymous)	@	vue.runtime.esm.js:4418
bn.update	@	vue.runtime.esm.js:4560
de.notify	@	vue.runtime.esm.js:730
set	@	vue.runtime.esm.js:1055
Cn.set	@	vue.runtime.esm.js:4644
(anonymous)	@	Viewer.vue:406
u	@	runtime.js:63
(anonymous)	@	runtime.js:294
(anonymous)	@	runtime.js:119
Ba	@	viewer-main.js?v=a6cfa508-18:2
a	@	viewer-main.js?v=a6cfa508-18:2
Promise.then (async)		
Ba	@	viewer-main.js?v=a6cfa508-18:2
a	@	viewer-main.js?v=a6cfa508-18:2
(anonymous)	@	viewer-main.js?v=a6cfa508-18:2
(anonymous)	@	viewer-main.js?v=a6cfa508-18:2
openFile	@	Viewer.vue:364
file	@	Viewer.vue:278
We	@	vue.runtime.esm.js:1863
bn.run	@	vue.runtime.esm.js:4584
yn	@	vue.runtime.esm.js:4326
(anonymous)	@	vue.runtime.esm.js:1989
et	@	vue.runtime.esm.js:1915
Promise.then (async)		
Xe	@	vue.runtime.esm.js:1942
it	@	vue.runtime.esm.js:1999
(anonymous)	@	vue.runtime.esm.js:4418
bn.update	@	vue.runtime.esm.js:4560
de.notify	@	vue.runtime.esm.js:730
set	@	vue.runtime.esm.js:1055
value	@	Viewer.js:183
ra	@	FilesActionHandler.js:36
action	@	fileactions.js?v=a6cfa508-18:136
_onClickFile	@	filelist.js?v=a6cfa508-18:926
Xe	@	_executeBound.js:8
(anonymous)	@	bind.js:10
(anonymous)	@	restArguments.js:16
dispatch	@	jquery.js:5183
g.handle	@	jquery.js:4991
```

When accessing the share via URL the following is logged (note sure if relevant or not) as apart from the office integration things appear to work fine.
```
xhr.js:177 GET https://nextcloud.host.com/ocs/v2.php/apps/text/public/workspace?path=%2F&shareToken=5Zxtacga7nzJUif 404
5Zxtacga7nzJUif:1 GET https://nextcloud.host.com/apps/files_sharing/publicpreview/5Zxtac…&file=%2FNeue%20Tabelle.ods&c=d1c8466…&x=250&y=250 404
```

</details>

**Comment by cetcondor** [comment]
Can confirm. Same issues here.

**Comment by tgurr** [comment]
Still the same for 5.0.1 released today...

**Comment by juliushaertl** [comment]
Thanks for the hint on the shared folder with edit permissions, I can reproduce this and will be looking into a fix. 

Findings:
- When the viewr integration is used on shared folders, the loading indicator is not hidden for the guest name input
- The guest name input should be moved into a vue component that can be shown upfront, to then stick with the existing loading behaviour

**Comment by hermann1514** [comment]
any news here?
