### ISSUE TITLE
Some UI things

### ISSUE THREAD

**Issue by dodedodo** [nextcloud/richdocuments#1915]
I love the new notebook style UI collabora [released](https://www.collaboraoffice.com/press-releases/code-6-4-0-release/)! And I love the fact that nextcloud did the work to integrate it UI wise. 
That being said, I still think there are a few odd things here and there. None of these bugs are breaking functionality. You just go "Huh, that's odd..." when you see them. 

## Toggle sidebar
There are 2 buttons, one for the nextcloud file properties, and one for collabora text formatting. The collabora button is a toggle, meaning you can close the sidebar with the same button. The nextcloud sidebar button does not work in that same way, even though they both open side menu's.
![image](https://user-images.githubusercontent.com/3252036/145906355-d5f39893-ca66-4ab3-be0d-6366b2d32397.png)

## File name placement
Maybe this should be centred vertically? It's a bit out-of-place as it is right now. 
![image](https://user-images.githubusercontent.com/3252036/145906039-9c82caff-9787-4787-9f31-b12f1a4b4202.png)

## File renaming displaces UI
When renaming a file from the UI element described above, all the items in the blue bar shift to the right. This is 'fixed' by reloading. Before (bottom) and after (top)
![image](https://user-images.githubusercontent.com/3252036/145904496-a5b9c833-f4d0-4981-9fed-96e8b5cb4ba8.png)

## Anonymous editing
There's a double blue bar which looks odd. There are 2 sidebar menu buttons, one of which does not work. For anonymous users, the file name text color is barely readable.
![image](https://user-images.githubusercontent.com/3252036/145907830-ff404a85-ab65-4054-a2cd-16c578b2d54e.png)

## Button theming
Button colors, hover styles and tags are sometimes inconsistent. This is a bit too much to screenshot, so I'll try to explain instead:

The nextcloud sidebar button and close button are black with a white hover background, while most other buttons are white with a black hover background. Most other buttons also show a tooltip while these 2 don't. 

The collabora sidebar button is gray-ish (looks grayed out!) with a spherical blue hover outline when the menu Is closed, and a rectangular one when the menu is closed. It also has no hover background, and changes the icon when the menu state changes.

EDIT: The button theming issue is already covered by #1905

**Comment by Kevin8675** [comment]
For me, even when normally editing, my filename is barely visible. Was there something you had to set to make that white bar appear around it?

**Comment by ya-d** [comment]
In classic toolbar the filename can show in front of the last edited string:
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/30781876/148527342-e1a5f377-06ca-4039-aec4-627dd1f956e0.png">

**Comment by jancborchardt** [comment]
@dodedodo a lot of these issues will be addressed and fixed with the NotebookBar design refresh: https://github.com/nextcloud/richdocuments/issues/1976

For the remaining ones you don’t see addressed, can I ask you to open separate issues for the requests? :) This will help track and fix them as they are distinct from each other. Thank you!

**Comment by juliushaertl** [comment]
This is mostly addressed with #1976 as Jan mentioned, so lets close this one.
