### ISSUE TITLE
Mobile visualization of LOOL

### ISSUE THREAD

**Issue by Franny203** [nextcloud/richdocuments#193]
Nextcloud integration app - implementation of mobile LOOL app

Hello there!

Thank you very much for your effort in creating this application. We are very happy and proud to use it. 
During the usage, we realized an unfortunate behavior on smartphones and tablets and we were wondering if you could implement a functionality to allow for better visualization on mobile devices.

Currently the visualization of lool in browsers of mobile devices is not responsive enough for mobile devices. It rather stays in the desktop version. But that visualization doesn‘t allow for proper reading of the text.

As screenshots are not being transferred, I attached a DOCX-File that contains the screenshots, I'm referring to.

Please see the following screenshots taken from an iPhone 7  iOS 11.3 in Firefox, Collabora Nextcloud App  2.0.3; Collabora/LOOL 3.0:

These are the views, visible when you open LOOL in a browser on a smartphone. It is almost impossible to scroll to the middle of the screen to look at the text even with horizontal layout.

The visualization suffers unfortunately even more when the keyboard is opened.

Almost no text is visible then and you can‘t click on the close button as it is not in sight on the screen. 

This behavior presents itself on every platform. On an Android device, it is not as difficult  as you’re able to scroll there but reading and even editing is almost impossible.
Another behavior is the auto adjustment. Occasionally this behavior causes the text window to minimize extremely as it doesn’t only adjust the width of the window but also the height. See the following screenshot for that behavior:

This can be seen on a tablet. The browser window has been minimized and the text window adjusted like in picture 5. Once you maximize the browser window, the text has still the size of the previous picture, even though the zoom says it’s at 100%. 

In conlusion the auto adjustment doesn’t really work for handhelds but this is an important feature and I hope this can be addressed by you. 

For comparison: There's an implementation for Only Office for the mobile visualization. The screen looks like this:

Do you think it’s possible to implement something similar for LOOL?

I would appreciate that a lot. 

Thank you very much for your effort.

Best regards,

Franny

**Comment by thebearon** [comment]
Please file this bug report upstream at [LibreOffice Bugzilla](https://bugs.documentfoundation.org/) under project LibreOffice Online.  The issue refers an attachment with screenshots that's missing, don't forget to attach that.
