### ISSUE TITLE
Internal link for sharing a file cannot be copied to a file via a browser on iOS

### ISSUE THREAD

**Issue by Gianni154** [nextcloud/richdocuments#1931]
**Describe the bug**
This problem concerns a Collabora Online instance that has been installed with Nextcloud. 
Using iOS (Apple iPad), an internal link of a file, which is located in Nextcloud, cannot be inserted into a document (the link can, however, be copied successfully). This was tried with two different browsers. The same thing happens with both the Safari app and the Firefox app, and the internal link of a file cannot be added to a document. After trying to paste the internal link, it looks like the document freezes (you can't write anything anymore). I have added a gif which should describe this better. If you try to add the link in the iOS Notes app, for example, it works.

The funny thing is that on a PC (I tested it with a Linux Client) it works without any problem. This means that something is wrong with the "mobile version" of Collabora Web. I also have a recording here.

**To Reproduce**
1. Open a browser (e.g. Safari, Firefox) on an iOS device (Apple iPad).
2. Open Nextcloud in the browser (not the Nextcloud iOS app but via a URL) and click on the sharing symbol (or on the three dots) for a document.
3. Click on "internal link" in the "Sharing" tab of the file so that the link is copied to the clipboard.
4. Open any other file in Nextcloud
5. Try to add the link in this file (will not work)

**Expected behavior**
The copied internal link should be able to be copied in another document without any problem.

**Screenshots**
iOS:
![ios](https://user-images.githubusercontent.com/78140364/146751251-8b8d8e3e-7552-462e-880a-6c99a8a21b70.gif)

On PC it works (Linux Client):
![pc](https://user-images.githubusercontent.com/78140364/146751652-74df8fd9-935e-4e70-82c0-f496242a743e.gif)

**Client details:**
 - OS: iOS 15.1
 - Browser Safari, Firefox
 - Version Nextcloud Version 23
 - Device: iPad 6th generation

## Server details

**Operating system**: RHEL 7.9

**Web server:** Apache

**Database:** MariaDB (MySQL)

**PHP version:** 7.3

**Nextcloud version:** 23.0.0

**Version of the richdocuments app** 5.0.0

**Version of Collabora Online** 6.2-32

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)

Unfortunately I could not find any usable log entries

</details>

**Comment by joshtrichards** [comment]
Multiple paste related issues have been fixed in Collabora Online. Can you confirm you're no longer experiencing this in newer versions of CO?

**Comment by joshtrichards** [comment]
Closing due to no further follow-up.
