### ISSUE TITLE
Can't edit or delete some files after recovering from an unexpected DHCP IP address change

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/richdocuments#194]
### Steps to reproduce
1. Have a power failure
2. Shutdown the server properly then restart it after the power failure. Also, have your ISP change the IP address of your router without you noticing it at first.
3. Try to use any file related to Collabora

### Expected behavior
Files should open for editing

### Actual behavior
They don't load and problem message posts instead

### Workaround and/or solution with a new problem
My situation may be unique, but here we go... 
I manage my own server using Virtualmin/Webmin. It automates a lot of things like BIND entries and so on. Virtualmin wasn't designed for cheap-bastards like me behind DHCP so I'm a little on my own here. 

First I updated my domain registrar (not on my servers) with the new IP address. I thought things were better after that, but I was getting weird responses when trying to open files that were left open in a client's browser before the power failure shutdown. I assumed that having them open during a power-failure cutting off the Internet was the problem, but when the file was downloaded an opened it was not corrupt. I tried to create a new spreadsheet, and it didn't appear. I tried it again in another subfolder and the same results, no error message, but no visible file.

I thought maybe the Collabora Docker container had some stored IP data that it didn't renew after rebooting. It seemed that was correct because after a `docker kill ___` and re-running the docker image the response to trying to open a file in NextCloud changed, but now it was telling me there was a file error. Before the Collabora window frame didn't load, now it did but the file it was accessing didn't. Also, after restarting the Docker image, the files I created earlier were listed in the directories I created them in. They also wouldn't open for editing.

I realized I didn't look at my BIND records. They had the old IP address in a bunch of places. I updated all the old IP's to the new IP, then rebooted. Now I'm able to open all my existing files as normal (documents, spreadsheets, presentations), but the two test files I created earlier are immovable objects. They are not editable by the user ID that created them during this recovery fiasco, and they cannot be moved or deleted. The only error I saw that made sense as I was getting a permission message suggesting that I didn't have the priveledges to delete them. I haven't tried to get to them as the admin of NextCloud or as the admin of the Ubuntu server.

I'm really hoping to hear what I should do to remove these test files, and also that my mini-catastrophe can suggest improvements that are more fault tolerant in DHCP scenarios.

## Server configuration detail

**Operating system:** Linux 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64

**Webserver:** Apache/2.4.18 (cgi-fcgi)

**Database:** mysql 10.0.34

**PHP version:** 7.0.28-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, readline, redis, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.1 - 13.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_notifications: 1.0.1
 - announcementcenter: 3.2.1
 - apporder: 0.4.1
 - audioplayer: 2.2.5
 - bookmarks: 0.11.0
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.1
 - checksum: 0.3.5
 - circles: 0.13.6
 - comments: 1.3.0
 - contacts: 2.1.3
 - dashboard: 4.0.6
 - dav: 1.4.6
 - deck: 0.3.1
 - drawio: 0.8.9
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_downloadactivity: 1.2.0
 - files_pdfviewer: 1.2.1
 - files_reader: 1.2.3
 - files_retention: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - flowupload: 0.0.7
 - gallery: 18.0.0
 - gpxedit: 0.0.8
 - gpxmotion: 0.0.6
 - gpxpod: 2.2.2
 - groupfolders: 1.2.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.7.10
 - metadata: 0.6.0
 - news: 12.0.1
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - ocr: 3.3.6
 - ocsms: 1.12.2
 - password_policy: 1.3.0
 - phonetrack: 0.2.7
 - polls: 0.8.1
 - provisioning_api: 1.3.0
 - quota_warning: 1.2.0
 - radio: 0.6.1
 - rainloop: 5.0.6
 - ransomware_protection: 1.1.0
 - richdocuments: 2.0.4
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - socialsharing_diaspora: 1.0.2
 - socialsharing_email: 1.0.3
 - socialsharing_facebook: 1.0.2
 - socialsharing_googleplus: 1.0.2
 - socialsharing_twitter: 1.0.2
 - spreed: 3.1.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - telephoneprovider: 1.0.1
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - weather: 1.5.1
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - orcid
 - user_external
 - user_ldap
 - user_saml
 - zenodo

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "13.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "theme": "",
    "updater.secret": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 2
}
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0

**Operating system:**

**Comment by WNYmathGuy** [comment]
Quick update here, despite editing all the BIND entries to update the new IP address, I discovered the virtual servers for my Virtualmin managed system had the old IP address hardcoded in their settings. I corrected that but it didn't solve the undeletable file problem.

**Comment by WNYmathGuy** [comment]
FAI, a newer error message I didn't notice before was `"folder1/folder2/folder3/folder4/shit.xlsx" is locked` which came after an attempt to move `folder1/folder2/folder3/Shit.xlsx` to  `folder1/folder2/folder3/folder4`. 

the two named files were never successfully edited after creation. Any attempted action on either of the files throws the standard message for the current action `Could not move "Shit.xlsx"` `Could not rename "Shit.xlsx"` and so on, which doesn't help diagnose the problem.

**Comment by rullzer** [comment]
This issue does not seem related to the richdocuments app. Please use the forums or open an issue in the server if you can reproduce the locking issues reliably
