### ISSUE TITLE
Cannot copy and paste the text from outside

### ISSUE THREAD

**Issue by fastdevops** [nextcloud/richdocuments#1940]
**Describe the bug**
Open the word editor, it cannot copy and paste the text from desktop or other tab of the browser. 

**To Reproduce**
1. Open the word file in the chrome;
2. Copy something from outside and the right click on the word editor and select paste;
4. It shows your browser has very limited access to the clipboard, so use these keyboard shortcuts;
5. ctrl v can only paste the content from the word except the content from the outside of the word editor.

**Expected behavior**
When I copy any text or image from outside and then ctrl v in the word editor, it should paste the content of the clipboard into the word.

**Client details:**
 - OS: Windows
 - Browser Chrome
 - Version 96.0.4664.110 
 - Device: Windows

## Server details

**Operating system**: Docker https://hub.docker.com/_/nextcloud

**Database:** MySQL 5.7

**Nextcloud version:** 23.0.0

**Version of Collabora Online**
Collabora Online5.0.1
Collabora Online - Built-in CODE Server	21.11.6

**Comment by juliushaertl** [comment]
Please fill out the issue template to provide some more information about your setup and the browsers in use.

**Comment by fastdevops** [comment]
updated.

**Comment by tech-nickel** [comment]
Same issue as described from @fastdevops. Already checked my security headers, that's not the problem.

**Comment by tech-nickel** [comment]
possible same issue in the CollaboraOnline repo as described here: https://github.com/CollaboraOnline/richdocumentscode/issues/148

**Comment by amuehle** [comment]
Same issue here, we have:
Nextcloud 22.2.3
Collabora Online 4.2.3
Collabora Online - Built-in CODE Server 21.11.103

When pasting (Tried Word and Excel) via CTRL+V nothing happens. I checked the Browser Console, no errors. Under the Network activity i see when i press CTRL+V that a POST is made:

![image](https://user-images.githubusercontent.com/92323925/151362591-ad1a9634-7faf-43f2-84c3-d7ea45c2df63.png)
But the text in the clipboard does not arrive in the editor.

**Comment by markginter31** [comment]
I'm also seeing the same behavior.  I can cut and paste within a document - but I cannot copy/paste from any outside source.  This began after the most recent updates.  Nextcloud 23, Collabora Online 5.0.1, built in code server 21.11.103
