### ISSUE TITLE
Apache reverse proxy with coolwsd fails if NextCloud instance use TLSv1.3 only

### ISSUE THREAD

**Issue by zynexiz** [nextcloud/richdocuments#1942]
For a while now I had problem with getting Collabora Online working. I'm running my Apache web server in a VM (KVM) on Arch Linux, have both NextCloud and coolwsd installed on the same machine (no docker). NextCloud is working, and is detecting coolwsd without issue. The problem I had is that it didn't load when trying to open a document.

After many, many hours of troubleshooting tons of different approaches I noticed something in the logs related to SSL version. Since I try to harden my server as much as possible, I only use TSLv1.3. This made the connection between NextCloud and coolwsd break for some reason. Adding TSLv1.2 to my VirtualHost config for NextCloud fixed this. I can still use TSLv1.3 only on the VirtualHost config for the reverse proxy though, but not on both.

```
<VirtualHost *:443>
    ServerName <nextcloud domain>
    ........

    # HTTP over TLS
    Include /etc/letsencrypt/options-ssl-apache.conf
    SSLHonorCipherOrder on
    SSLProtocol -all +TLSv1.3 TLSv1.2
    SSLCertificateFile <cert>
    SSLCertificateKeyFile <key>
</VirtualHost>
```

Although it works, I'm a bit curious why this is. I use HTTPS to my reverse proxy, and HTTP to coolwsd, and Let's encrypt for both NextCloud and Collabora Online domain, so the termination is with Apache.

**Comment by juliushaertl** [comment]
@zynexiz In case you are using the following aur PKGBUILD I could imagine this is an issue with the openssl 1.0 which is being used there: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=collabora-online-server-nodocker#n93

TLS 1.3 requires at least 1.1.1 if i remember correctly

The failing request is issued by the coolwsd process and directed to your Nextcloud instance, which would explain the failure if the openssl version in use does not support TLS 1.3.

**Comment by zynexiz** [comment]
I do use that PKGBUILD from AUR, but I have both openssl 1.1.1 and 1.0 installed in my system, so that's not the issue. I have TSLv1.3 only on all my sites without any issue, so I know that it works. It's then I try open documents from NextCloud the issue arises.

**Comment by juliushaertl** [comment]
I guess coolwsd is still linked with openssl-1.0 then. `ldd /usr/bin/coolwsd`could give a hint. So I guess this is something that can only be fixed in the actual PKGBUILD, to make sure it is built with the newer openssl

**Comment by zynexiz** [comment]
Seems like that's the case: `libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0`

Not sure if it's coolwsd itself that depends on it, or just a matter of rebuild it. Need to post a note to the maintainer of the build.

**Comment by juliushaertl** [comment]
Let me close this then here, as this is nothing related to the richdocuments app itself.
