### ISSUE TITLE
with newest code docker and nc plugin 2.0.5 no keyboard in safari

### ISSUE THREAD

**Issue by WagenerHAW** [nextcloud/richdocuments#195]
I can not write in any document with the safari browser. Chrome and Firefox are working...

On every keypress nothing happens. Writing a comment with Insert->Comment is working. No errors in the browser - just nothing.

Anyone else with this problem.

**Comment by timar** [comment]
It's a known bug, and it has been fixed already. New CODE docker will be released soon.
