### ISSUE TITLE
Viewer handler registration is done too late

### ISSUE THREAD

**Issue by eneiluj** [nextcloud/richdocuments#1958]
It seems that
https://github.com/nextcloud/richdocuments/blob/368fd1e887c7688fded9d6883f49855cfebd0705/src/viewer.js#L31-L41
is done too late and is not effective with latest server master branch, viewer and richdocument master branches.

For example, in my dev setup, browser debug logs mention 4 registered handlers but when browsing the handlers array, 6 are actually added after the object has been printed:
![riri](https://user-images.githubusercontent.com/11291457/147951781-303b4fc3-739e-43f6-9ced-901e0b8f1c38.png)
The failing ones are `richdocuments` and `pdf`.

I'll check if recent changes in server caused that.

As a temporary fix (or even definitive if it makes sense), we can register the handler without waiting for `DOMContentLoaded`

``` js
document.addEventListener('DOMContentLoaded', function(event) {
```

**Comment by eneiluj** [comment]
@mejo- When going back to https://github.com/nextcloud/server/commit/a37909f61c5850bfba9df42cb69d18ecce9710bc (right before your https://github.com/nextcloud/server/commit/491bd6260c4070ecc74811425dd55ac7dd812cf0) the `richdocument` handler is correctly registered in the Viewer but the `pdf` one is still done too late (Viewer sees 5 handlers and we can see the `pdf` one appears in the array afterwards:
![pdf](https://user-images.githubusercontent.com/11291457/147952999-1c0adb98-4b11-43f6-9a83-51054094ec22.png)

Any idea?

**Comment by jernst** [comment]
What's the actual user-observed behavior here? Does that mean the viewer doesn't show up when it should, e.g. when clicking on an .odp document? (Because that's my problem ...)

**Comment by juliushaertl** [comment]
@jernst Yours is most likely different, since this seems to be a regression on master only and the linked commits were not released yet. Can you open a separate issue with a full issue template filled out?

**Comment by juliushaertl** [comment]
@eneiluj I can now also reproduce, seems my server pull was not updating. 
Basically the reason this has worked before the server change was mostly luck in the loading order. Viewer does register file actions for the registered handlers in a DOMContentLoaded event callback. Now before the sorting of scripts, this was probably registered as the last handler and the richdocuments one registering with viewer was called first.

https://github.com/nextcloud/viewer/blob/12d97dc100a880a5beb213507f8eeecc667c6fd0/src/views/Viewer.vue#L298

Registering the viewer component should be called in a synchronous way with the loading of the richdocuments-viewer.js script as now with the script loading order we can be sure that the viewer service is already available for registration:

https://github.com/nextcloud/viewer/blob/master/src/main.js#L51
 
In the end we should drop the waiting for DOMContentLoaded on the richdocuments side.

**Comment by eneiluj** [comment]
@jernst Clicking on a file in Files does not open the viewer and the file is downloaded by the browser.

Are you using a development setup with Nextcloud 24? This issue does not affect NC 23 and lower.
