### ISSUE TITLE
[Feature Request] View > Freeze Cells > Freeze Rows and Columns

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/richdocuments#196]
I might be acting like a whiny baby, but I can't believe how much I liked having the ability to work in a spreadsheet with the freeze feature available. I've used the freeze feature in many ways for specific applications. Often I freeze an arbitrary number of rows because I have subtotal type formulas above the column names for the auto-filter. Sometimes I have rows above the formulas doing things that I don't want to see so I'll freeze the rows in a way that I freeze rows 4 & 5 but 1-3 are up out of sight.

Not like I'm going to stop using Collabora because of this, but it definitely bugs me and I think it would bug people I used to make managerial spreadsheets for.

**Comment by thebearon** [comment]
Please file this request upstream at [LibreOffice Bugzilla](https://bugs.documentfoundation.org/) under project LibreOffice Online.
