### ISSUE TITLE
idle mode makes menu's get stuck.

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/richdocuments#1964]
**Describe the bug**
A menu gets stuck in the bottom of the window, decreasing the working size of the document. I can not click the buttons in the below area. The menu is stuck on the bottom.
**To Reproduce**
1. Open a document
2. Open the 'insert special character' menu
3. Walk away until the document goes idle
4. Come back and see the problem
5. you can't re-open the dialog, other dialogs largely seem to work

**Expected behavior**
menu still works, or is closed.

**Screenshots**
<img width="1445" alt="Screenshot_20220105_100656" src="https://user-images.githubusercontent.com/551757/148191020-93de06d3-77cd-476a-a3ca-2259e89b1621.png">

**Client details:**
 - OS: Linux
 - Browser: Chrome
 - Version: 96.0.4664.110
 - Device: desktop

## Server details

Nextcloud 23.0.0 on cloud.nextcloud.com

**Comment by thebearon** [comment]
@jospoortvliet this is a bug in Collabora Online, can you please open an issue over at:
https://github.com/CollaboraOnline/online/issues ?
