### ISSUE TITLE
Notebook bar design refresh

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#1976]
Notes from our design review call:

See [Microsoft Office design refresh](https://insider.office.com/en-us/blog/visual-refresh-of-office-apps-for-windows) for reference
Ref https://github.com/collaboraOnline/online/issues/3741

* [x] Color to regular page background
  * [x] Align similar boxed layout like MS Office, with rounded corners
  * [x] Possibly align with Nextcloud Sidebar hover/focus feedback (like list item in talk)
* [x] No app specific colors (blue, green, orange), just use primary for theming
* [x] Tabs
  * [x] Separate sections like MS Office without indication at the bottom
  * [x] Align to new tabs design like for sidebar tabs
* [ ] Header bar
  * [x] Fullscreen -> View menu
  * [ ] Save -> Give feedback in top right, as in normal view
  * [x] Undo/Redo -> Home, first block on left
  * [ ] Save button possibly in same group as undo redo, definitely on Home tab
  * [ ] Menu entries need to move elsewhere, should only show on mobile
    * [ ] Select all → Should be same group as cut copy paste?
    * [x] Fullscreen → Already in Layout tab
    * [x] Show ruler → Already in Layout tab
    * [x] Track changes → Already in Review tab
    * [x] Find and replace → Already in Home tab
    * [x] Repair → Already in File tab
    * [x] Tools (spelling, word count) → Already in Review tab
* [x] Sidebar
  * [x] Background color should be same as document background
  * [x] Dividing border can be much lighter
  * [x] Little bit of vertical whitespace between sections
* [ ] Font style selector
  * [x] Borders are too dark
  * [x] Active font style should use our default active state (and hover/focus should use the default hover/focus states)
  * [x] Box should have rounded corners
  * [ ] Scrollbar is strange– instead should use scroll buttons
  * [x] Doesn’t need to show "Heading 1" etc twice, just show "AaBbCc" in formatted way and title below. Or directly "Heading 1" formatted, like Apple Pages does
    * [x] If we use 2 lines: Line height between the 2 lines are too much

![Quick mockup happend during the call](https://user-images.githubusercontent.com/3404133/149131711-5a3bc413-6a7b-4992-a653-40ad257f3332.png)

**Comment by pedropintosilva** [comment]
Generally I like it and it shares many things that I already liked from @Andreas-Kainz 's https://github.com/CollaboraOnline/online/issues/3741 and goes a bit beyond. 

- The shortcuts parent (that has save, full-screen, undo and redo): hiding it makes sense if we have other way to show the some actions:
  - As discussed with @jancborchardt I think moving undo/redo to home tab is fine. Sure, now the user cannot access those icons at all times and that's an disadvantage (plus an extra click) but if we are ok with that it should be fine (specially when those actions are very commonly triggered via keyboard shortcut)
    - We could also add undo and redo icons to the right click context menu (so to provide a way to wherever the tab is the user can simply right click the document and undo the change) 
- Hamburger: I think, and as discussed with @Andreas-Kainz, we can hide it provided that all icons are present within the notebookbar (and maybe one or two should be duplicated to be also present in the home tab, I need to check that)
- I like this floating direction : )
  - Wonder about contrast for the active tab (probably easily solvable by experimenting with a bit of color)
  - The sidebar: I wonder, if the floating concept is to be kept, how to solve this:
    - The way the left bezel end abruptly doesn't look so good
      - Maybe the bezel can keep going up under the floating element
      - Or maybe we could somehow combine statusbar and sidebar ..hm.. this is what it comes to my mind (draft, we would need to think what we want to be visible in that mini status bar as well ) 
![image](https://user-images.githubusercontent.com/65948705/149946524-c8c10753-c628-49a1-a5ad-148dc6c86407.png)

**Comment by Andreas-Kainz** [comment]
I would like to bring in mind the mockups from here to discuss with, cause I think with tricky alignment we maybe can group our toolbars full with commands https://github.com/CollaboraOnline/online/issues/3871

**Comment by Andreas-Kainz** [comment]
for me the bigger question is the layout and behaviour of the sidebar (which could be a separate issue).

would it be possible to combine the NC sidebar with the COOL sidebar? I'm thinking of have the NC sidebar (if cool run within a NC) where you have in general defferent tabs and add there one tab for office properties.

![photo5956181258373542906](https://user-images.githubusercontent.com/8517736/149953857-4b6c814a-0b00-49a2-987a-a2128c273433.jpg)

**Comment by pedropintosilva** [comment]
> would it be possible to combine the NC sidebar with the COOL sidebar? I'm thinking of have the NC sidebar (if cool run within a NC) where you have in general defferent tabs and add there one tab for office properties.

That's exactly what I want as well to avoid having too many sidebars (ideally just one that changes its content when NC stuff is needed) I already discussed with @eszkadev and @juliushaertl some time ago and very recently with @jancborchardt 

Probably the best would be to use JSON thing and postmessages for events (less iframes and sizing problems) and then working on trying to keep everything unified style-wise etc. So yes that would be the direction to take : )

**Comment by Andreas-Kainz** [comment]
When the sidebar color use the page background color to be less focused, the select color is different than for the toolbar/notebookbar.

What if use for the notebookbar and sidebar the background color of the page (light gray) AND the area of the commands will have white background with box-shadow, ... So we have the same design language for the toolbar/notebookbar and the sidebar. 

![image](https://user-images.githubusercontent.com/8517736/153671086-f67d66ab-c153-4935-ae6f-ccaf41d5ed6d.png)

**Comment by jancborchardt** [comment]
Additional points from our design review call:

**Menu bar**
- [ ] "Save" action doesn’t need to be in the menu bar

**Toolbar**
- [ ] "Save" action should also be in "Home" section, on the far left
- [ ] Active icon (e.g. Bold) is not black
- [ ] In "View" section, the ruler and status bar icons are permanently black
- [ ] Lighter color for the paragraph styles box → use actual `color-border`, `#ededed`
- [ ] Table tab needs some icons: https://materialdesignicons.com/ → search for "table", Text also has those icons
- [ ] "Accessibility check" needs Material Design icon: https://fonts.google.com/icons?selected=Material%20Icons%3Aaccessibility_new%3A

**Right sidebar**
- [ ] Possibly remove horizontal line below Style/Character/Paragraph headings as it splits headings from content and is barely visible anyway

**Comment by juliushaertl** [comment]
Moving to smaller tickets to have a better overview and making it more easy to tackle individual items:

- https://github.com/nextcloud/richdocuments/issues/2331
