### ISSUE TITLE
"Security: coolmount incorrect user-name, other than 'cool'"

### ISSUE THREAD

**Issue by jernst** [nextcloud/richdocuments#1978]
**Describe the bug**

Apache error log shows repeated messages: `Security: coolmount incorrect user-name, other than 'cool'`.

I'm not certain where this comes from, but I guess it is `richdocumentscode` and it comes from the AppImage. At least that's the only place I can find anything named like it on my system (`/tmp/systemd-private-678ebbbe7af04fdaa4f804981fa06019-httpd.service-x6X513/tmp/appimage_extracted_a0405c848762a96f5e39514c5fe1f870/usr/bin/coolmount`)

If I invoke that very executable I get: 
```
# /tmp/systemd-private-678ebbbe7af04fdaa4f804981fa06019-httpd.service-x6X513/tmp/appimage_extracted_a0405c848762a96f5e39514c5fe1f870/usr/bin/coolmount 
Security: coolmount incorrect user-name, other than 'cool'
Aborting.
```
Varying command-line arguments does not appear to change anything. `grep` fails to find anybody actually invoking this.

**To Reproduce**

Freshly installed OS and Nextcloud 23.0.0 with `audioplayer`, `bookmarks`, `cache-redis`, `calendar`, `contacts`, `deck`, `forms`, `group-everyone`, `groupfolders`, `mail`, `markdown`, `news`, `notes`, `richdocuments`, `richdocumentscode`, `spreed`,`tasks`

1. With a fresh install, attempt to open a new rich document. It opens, but the message is printed to the log.

**Client details:**
 - Device: [e.g. iPhone6, desktop]

## Server details

UBOS (like Arch) on x86_64, Nextcloud 23, Apache, mariadb, php 8.0.7, richdocuments 5.0.1, richdocumentscode 21.11.6

Nothing remarkable in the nextcloud log. This is from the Apache error log.

**Comment by juliushaertl** [comment]
Closing as a duplicate of the report in richdocumentscode https://github.com/CollaboraOnline/richdocumentscode/issues/135
