### ISSUE TITLE
zombie process

### ISSUE THREAD

**Issue by Bables55** [nextcloud/richdocuments#198]
### Steps to reproduce
1. Start or restart loolwsd
2.
3.

### Expected behaviour
A zombie process is not born

### Actual behaviour
When loolwsd starts, a zombie process is always created.
When I stop loolwsd, the zombie process disappears.
*loolwsd-3.1.0-8.el7.centos.x86_64

ps -ef | grep defunct
lool     10725 10723  0 15:53 ?        00:00:00 [lo_startmain] <defunct>

The use of Collabora itself has no problem.

### Server configuration

**Operating system**:
CentOS 7.3
**Web server:**
nginx 1.11.10
**Database:**
MariaDB 5.5.56
**PHP version:**
PHP 7.1.16
**Nextcloud version:** (see Nextcloud admin page)
13.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
12.0
**Where did you install Nextcloud from:**
nextcloud.com
</details>

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Webdav

### Client configuration
**Browser:**
Firefox, Vivaldi
**Operating system:**
Windows10

**Comment by dt64** [comment]
Same here on Ubuntu 18.04 with Nextcloud 130.5.2, php7,2, NGINX 1.14.0, MariaDB 10.1, Collabora Office 5.3-53 in docker and LOOLWSD 3.3.1 fresh install

**Comment by juliushaertl** [comment]
Thanks for your bug report. This issue tracker is only targeting the collabora integration inside Nextcloud. Your issue is actually related to Collabora/LibreOffice Online, so please head over to bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online for reporting.

**Comment by dt64** [comment]
https://bugs.documentfoundation.org/show_bug.cgi?id=122805
