### ISSUE TITLE
Excel file is saved with about 250% zoom when edited on mobile

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/richdocuments#1981]
**Describe the bug**
![image](https://user-images.githubusercontent.com/24530680/149338164-63fb8af5-000b-466c-8ed3-3f72fbdb08d8.png)

**To Reproduce**
1. Create a new Excel file
2. Edit it on mobile
3. Open it with excel when the nextcloud client synced it on desktop
4. See error (in the browser it's fine)

**Comment by juliushaertl** [comment]
Closing as this is an upstream issue already reported at https://github.com/CollaboraOnline/online/issues/4250
