### ISSUE TITLE
input area stays empty for Excel sheets

### ISSUE THREAD

**Issue by schiessle** [nextcloud/richdocuments#1991]
Tried on c.nc.com (Nextcloud 23.0.0)

When open a xlsx file and navigate to a folder the input field where I expect the content of the cell stays empty which makes it impossible to edit the cell if it is more than just text which could be edited directly in the cell:

![grafik](https://user-images.githubusercontent.com/1589737/150106094-6a11230a-2632-447d-acd6-23cdcdd66add.png)

**Comment by juliushaertl** [comment]
I cannot reproduce this anymore on our instance, do you still see this problem? Is it related to only specific documents or column formats like dates maybe?

**Comment by schiessle** [comment]
I also can't reproduce it anymore
