### ISSUE TITLE
config not accessable

### ISSUE THREAD

**Issue by nextgen-networks** [nextcloud/richdocuments#2]
After Upgrading from [https://github.com/owncloud/richdocuments](url) the config page disappeared.

It was located at: https://YOURDOMAIN.tld/index.php/settings/admin/additional

**Comment by LukasReschke** [comment]
It is now in it's own tab on the left page.

**Comment by nextgen-networks** [comment]
... hmm - i need new goggles, i cant's see it in menu :-/

![2016-12-15_searchforcollaboraconfig](https://cloud.githubusercontent.com/assets/21206978/21223078/a60fd95a-c2c5-11e6-9774-f8f272ff9ba3.JPG)

**Comment by nextgen-networks** [comment]
OK it seems to be an bug in upgrade process.

Just deactivate AND uninstall the updated app and then reactivate it.
Now you'll find the config option as new entry in left side menu.
