### ISSUE TITLE
Failed to get LoKitDocument instance support collabora

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/richdocuments#20]
### Steps to reproduce
1. Start a CoreoOS machine
2. Try collabora

There is a more detailed report at:
https://help.nextcloud.com/t/failed-to-get-lokitdocument-instance/

### Expected behaviour
Collabora should work

### Actual behaviour
Collabora js client will hang for ever
on the collabora server side, there is a fatal error.

### Server configuration

docker info:

```
Containers: 103
 Running: 94
 Paused: 0
 Stopped: 9
Images: 194
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.7.3-coreos-r2
Operating System: CoreOS 1185.3.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.44 GiB
Name: k5
ID: DMZF:QW5P:LYYA:ELTB:BBK3:LTJK:ADPJ:EAZP:YWSY:EBRV:AFP2:OT4M
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

### Logs

```
collabora_1  | wsd-00029-07 00:02:45.805964 [ prison_ws_0003 ] Message to admin console: adddoc 53 test.odt 0003 115756
collabora_1  | wsd-00029-07 00:02:45.805988 [ prison_ws_0003 ] SocketProcessor starting.
collabora_1  | kit-00053-04 00:02:45.602043 [ kit_queue_0003 ] Document::DocumentCallback STATUS_INDICATOR_START [].
collabora_1  | kit-00053-04 00:02:45.609742 [ kit_queue_0003 ] Document::DocumentCallback STATUS_INDICATOR_SET_VALUE [33].
collabora_1  | kit-00053-04 00:02:45.614988 [ kit_queue_0003 ] Document::DocumentCallback STATUS_INDICATOR_SET_VALUE [33].
collabora_1  | kit-00053-04 00:02:45.615014 [ kit_queue_0003 ] Document::DocumentCallback STATUS_INDICATOR_SET_VALUE [66].
collabora_1  | kit-00053-04 00:02:45.615488 [ kit_queue_0003 ] Document::DocumentCallback STATUS_INDICATOR_SET_VALUE [100].
collabora_1  | kit-00053-04 00:02:45.616332 [ kit_queue_0003 ] Document::DocumentCallback STATUS_INDICATOR_FINISH [].
collabora_1  | kit-00053-04 00:02:45.631630 [ kit_queue_0003 ] Returned lokit::documentLoad.
collabora_1  | kit-00053-04 00:02:45.631669 [ kit_queue_0003 ] Failed to load: file:///user/docs/53/test.odt, error: loadComponentFromURL returned an empty reference
collabora_1  | kit-00053-04 00:02:45.631679 [ kit_queue_0003 ] Failed to get LoKitDocument instance.
collabora_1  | kit-00053-04 00:02:45.631704 [ kit_queue_0003 ] ToMaster-0003 Send: error: cmd=load kind=faileddocloading
collabora_1  | kit-00053-02 00:02:45.631704 [ kit_callback ] CallbackWorker::callback [ToMaster-0003]: STATUS_INDICATOR_START [(nil)].
```

### What next?

First before solving, I'd like to update the "documentation" to warn CoreOS users like me that this would fail.

then, I'd like to know if CoreOS support would be added?

Thanks a lot!

**Comment by StuartIanNaylor** [comment]
Debian Jessie wouldn't work with AUFs swapped to device-mapper, nags but works.

Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.0
Storage Driver: devicemapper
 Pool Name: docker-254:0-2097729-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.306 GB
 Data Space Total: 107.4 GB
 Data Space Available: 70.57 GB
 Metadata Space Used: 1.81 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.90 (2014-09-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: nextcloud
ID: NEB7:ADC7:63ZI:6YB7:RY7Z:WKTK:XCKU:EKNN:ON6B:4Q6K:H3GL:MOK7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by tailtwo** [comment]
Any news on this issue? I'm also using CoreOS stable with overlay and I have the same problem.

**Comment by juliushaertl** [comment]
Please try again with the latest version of collabora. In case this still happens please head over to the upstream project for reporting https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online
