### ISSUE TITLE
problem to open documents with tags and file access rules

### ISSUE THREAD

**Issue by andreasmalta** [nextcloud/richdocuments#202]
Steps to reproduce
1. Install apps: "Collabora Online" and "Collaborative tags" and "File access control"
2. Under Workflow settings, create a tag named "restricted"
3. Under File access control settings, create a new group with following rules: "User group membership is not a member of admin" and "File system tag is tagged with 'restricted'"
4. Create a document with the tag "restricted" and open it for editing with Collabora

Expected behaviour
An admin user (part of the admin group) should be able to open the file

Actual behaviour
The Collabora toolbar opens but with the message "Failed to read document from storage"

Server configuration
Operating system: Centos7

Web server: Apache

Database: MariaDB

PHP version: 7.1 (ius)

Nextcloud version: 13.0.1

Collabora version: CODE 3.1.0 (tested with both Docker and package installation)

Where did you install Nextcloud from: https://download.nextcloud.com

Signing status: No errors have been found.

List of activated apps:
Collabora Online
Collaborative tags
File access control
Zimbra Drive

**Comment by andreasmalta** [comment]
Compared to when I open a document successfully, these extra lines are logged when I open a document with a tag (/var/log/messages of the collabora server)
Apr 20 09:15:51 collabora loolwsd: wsd-01773-01890 07:15:51.982773 [ docbroker_00a ] ERR  WOPI::GetFile failed with 403 Forbidden| wsd/Storage.cpp:631
Apr 20 09:15:51 collabora loolwsd: wsd-01773-01890 07:15:51.983089 [ docbroker_00a ] ERR  Failed to add session to [/index.php/apps/richdocuments/wopi/files/829_ocdkoc7ooxro] with URI [https://drive.domain.com/index.php/apps/richdocuments/wopi/files/829_ocdkoc7ooxro?access_token=EwvczVjmCLexs9yo6qGU7Zt36nQCxe4z&access_token_ttl=0&permission=edit]: WOPI::GetFile failed| wsd/DocumentBroker.cpp:1000
Apr 20 09:15:51 collabora loolwsd: wsd-01773-01890 07:15:51.983373 [ docbroker_00a ] WRN  Child session [0015] not found to forward message: load url=https://drive.domain.com/index.php/apps/richdocuments/wopi/files/829_ocdkoc7ooxro?access_token=EwvczVjmCLexs9yo6qGU7Zt36nQCxe4z&access_token_ttl=0&permission=edit authorid=admin author=admin authorextrainfo=%7B%0A%20%20%22avatar%22%20:%20%22https:%5C/%5C/drive.domain.com%5C/index.php%5C/avatar%5C/admin%5C/32%22%0A%7D readonly=0 lang=en-GB| wsd/DocumentBroker.cpp:1482
Apr 20 09:15:51 collabora loolwsd: wsd-01773-01890 07:15:51.991087 [ docbroker_00a ] ERR  Invalid or unknown session [0015] to remove.| wsd/DocumentBroker.cpp:1067
Apr 20 09:15:52 collabora loolwsd: wsd-01773-01792 07:15:52.984433 [ prisoner_poll ] WRN  Prisoner connection disconnected but without valid socket.| wsd/LOOLWSD.cpp:1541

**Comment by thecube13** [comment]
same issue with Nextcloud 16. Any workaround?

**Comment by alderson59** [comment]
Issue is NOT stale.

Nextcloud 19.0.1

Trying to access documents inside a folder with a Restricted Tag that Blocks File Access (using Flow) to certain users.

I accessed the folder as a privileged user and was unable to open the document. 

Error message:
![image](https://user-images.githubusercontent.com/69715968/93667467-c688c500-fab8-11ea-8fb2-de7372ca7e62.png)

Nextcloud logs as Admin
![image](https://user-images.githubusercontent.com/69715968/93667415-377bad00-fab8-11ea-913b-44bdc2b23f53.png)

**Comment by alderson59** [comment]
Refer to #1168 - Problem is not stale.
