### ISSUE TITLE
CSP error when opening documents

### ISSUE THREAD

**Issue by greenbourne277** [nextcloud/richdocuments#2026]
**Describe the bug**
When opening a document the content is not loaded. The webconsole shows a CSP error.
This error occured with the update to Nextcloud v23. 

```
Content Security Policy: The page’s settings blocked the loading of a resource at http://mydomain.com/custom_apps/richdocumentscode/proxy.php?status (“connect-src”).
```
I think it shoudl use **https** instead of **http**

**To Reproduce**
1. Install **Collabora Online - Built-in CODE Server** 
2. Use the Built-in server
3. Select a document

**Expected behavior**
I expect to be able to edit documents

**Screenshots**
![2022-02-07_21-23-52](https://user-images.githubusercontent.com/82470038/152865777-da17cc27-fb28-4030-af42-303d22dbd526.png)

**Client details:**

 - OS: Linux
 - Browser: Firefox, Chromium
 - Version , 96.0.3  and 98.0.4758.80 Arch Linux
 - Device: desktop

## Server details

**Operating system**:

**Web server:**
Ubuntu 20.04, but everything runs in docker containers

**Database:**
Maria DB

**Nextcloud version:**
23.0.1

**Version of the richdocuments app**
5.0.1

**Version of Collabora Online**
 21.11.103

**My docker-compose setup**
https://gist.github.com/greenbourne277/99190585dc3afeff53cbbc5d823767dd

<details>

#### Nextcloud log (data/nextcloud.log)
No errors in the logs.

#### Browser log

```js
Content Security Policy: The page’s settings blocked the loading of a resource at http://my-cloud.de/custom_apps/richdocumentscode/proxy.php?status (“connect-src”).
```

</details>

Edit: Added Gist to my docker-compose file

**Comment by juliushaertl** [comment]
Looks like this is an issue with the richdocumentscode app,  already reported over there https://github.com/CollaboraOnline/richdocumentscode/issues/80

Just out of curiosity, since you have a CODE docker container started, any reason to not use that instead of the built-in code server?

**Comment by greenbourne277** [comment]
@juliushaertl  thanks for the link. When I try to edit the collabora settings in nextcloud it doesn't seem to save it when i choose my own server. After refreshing the site it always selects the built-in code server. I'm really not sure if the changes are applied in the end.
