### ISSUE TITLE
Horizontal scroll is allowed on touch screen

### ISSUE THREAD

**Issue by tintou** [nextcloud/richdocuments#2038]
**Describe the bug**
On my computer I'm able to scroll horizontally using the touch screen in a point where the document is not visible anymore, note that it is not possible to scroll using the touchpad

**To Reproduce**
1. Go to a text document
2. Unzoom to make sure that the document left and right margin are inside the viewport
3. Use the touch screen to scroll left or right
4. See that it's even possible to scroll so that the document is out of the viewport

**Expected behavior**
It shouldn't be possible to scroll out of the viewport

**Screenshots**

https://user-images.githubusercontent.com/745535/153646895-066443d1-8f90-4fbe-a576-df056c746cba.mp4

**Client details:**
 - OS: Linux
 - Browser Chrome
 - Version 98.0.4758.80
 - Device: laptop

**Comment by juliushaertl** [comment]
The scroll area is purely within Collabora Online, so maybe you could open an issue about this at https://github.com/CollaboraOnline/online

**Comment by tintou** [comment]
Moved to https://github.com/CollaboraOnline/online/issues/4189
