### ISSUE TITLE
coolwsd 21.11.1.4 layout corrupted in ffox

### ISSUE THREAD

**Issue by resoli** [nextcloud/richdocuments#2045]
**Describe the bug**
Under some circumstances, the CODE editor layout is corrupted.

**To Reproduce**
1. When showing the second slide of the Welcome pane (see screenshot)
2. When creating and opening the contextual chat in collaborative editing

In both cases, the editor pane appears shifted up, with the upper tool panel  no more accessible, and part of "files" app user interface  shown at the bottom of the document.

**Screenshots**
![immagine](https://user-images.githubusercontent.com/9579173/153833071-bbfc8ae9-e9ab-4a9b-bbc9-5f35fb7ba1d9.png)

**Client details:**
 - OS: ubuntu 20.04
 - Browser ffox 96.0 (64 bit)
 - Device: desktop

## Server details

**Operating system**:
Debian 10

**Web server:**
Apache 2.4

**Database:**
Mysql

**PHP version:**
7.3

**Nextcloud version:**
22.2.3

**Version of the richdocuments app**
4.2.4

**Version of Collabora Online**
21.11.1.4

**Comment by juliushaertl** [comment]
This occurred in the past already, though I'm still not sure how this could be triggered. My assumption is that the file is being opened while the files app frontend code is still running and might jump to a different scroll position later on.

- [ ] Check which OCA.Files methods we call during document loading and if they could cause a scroll change

**Comment by resoli** [comment]
I confirm that the issue disappears if the editor is triggered from another app (recent files in dashboard, for instance.)

**Comment by resoli** [comment]
> the issue disappears if the editor is triggered from another app

By the way this made me think it was a ffox-only issue. It is not; I have updated the issue report and title.

**Comment by juliushaertl** [comment]
This has been fixed in the meantime.
