### ISSUE TITLE
Comment avatars lost after user leaves document

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#2049]
When a user leaves a document, currently there is no trace about the avatar of that user anymore e.g. for showing it next to already written comments.

After discussion with @kendy this would require a way to store the avatar within the document either the URL or maybe even the base64 encoded image in order to always show it.

Also related to #1380

**Comment by juliushaertl** [comment]
As per discussion this is mostly an issue within Collabora about persisting the avatar information in the file itself https://github.com/CollaboraOnline/online/issues/4590

**Comment by ananyak19** [comment]
Hey, can I work on this issue?

**Comment by juliushaertl** [comment]
Closing as there is an upstream issue
