### ISSUE TITLE
4.2.4 breaks Collabora on NC 22.2.5

### ISSUE THREAD

**Issue by schniepp** [nextcloud/richdocuments#2052]
**Describe the bug**
After upgrading to 4.2.4 I only see a white browser window after clicking on an ODT document. Downgrading to 4.2.3 invokes the full, working Collabora editor window as expected.

**To Reproduce**
(Already explained above)

**Expected behavior**
(Already explained above)

**Screenshots**
(No screenshot needed for a white browser window.)

**Client details:**
 - OS: linux
 - Browser: chrome
 - Device: desktop

## Server details

**Operating system**:
Linux (ubuntu 18.04)

**Web server:**
Apache2

**Database:**
MySQL 8

**PHP version:**
7.4

**Nextcloud version:**
22.2.5

**Version of the richdocuments app**
4.3.4

**Version of Collabora Online**
21.06.13-1

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
No error message shown, no related NC log events!
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
This appears to be the critical error that only appears after the upgrade to 4.2.4 (domain name in URLs anonymized):

jquery.js:510 Refused to send form data to 'https://***.com:9980/browser/739da71/cool.html?WOPISrc=https%3A%2F%2F***.com%2Fowncloud%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F11927687_ocpgrep9qdhg&title=asdf.odp&lang=en&closebutton=1&revisionhistory=1' because it violates the following Content Security Policy directive: "form-action 'self'".



b) The network log
c) ...
```

</details>

**Comment by Kieltux** [comment]
After updating to richdocuments 4.2.4 I get exact the same result: Loading documents gives only a white page. No error coolwsd logs, even if I set the log level to debug.

After a downgrade to 4.2.3 everything is working again.

Server details

Operating system:
openSUSE Leap1.53

Web server:
Apache 2.4.51

Database:
MariaDB 10.5.13

PHP version:
7.4

Nextcloud version:
21.0.7

Version of the richdocuments app
4.2.4 -> downgrade to 4.2.3

Version of Collabora Online
Collabora Online Development Edition
21.11.1.4 | 739da71

**Comment by Kieltux** [comment]
After reading https://github.com/nextcloud/richdocuments/pull/2033/commits
I added to config.php
```
'gs.trustedHosts' => [
	'mydomain1.com',
	'mydomain2.com'
]
```
but it makes no difference.

**Comment by do1fmd** [comment]
Same problem here.
May I ask you, how you downgraded 4.2.3?
I cannot find any occ command or tutorial how to downgrade apps.

**Comment by schniepp** [comment]
@do1fmd : 

This is how I did it. It worked reproducibly (more than once) and without any problems I am aware of. Not sure whether this is supported or documented:

1. Disable the app in your app store. This is to avoid that the app will automatically be upgraded again after installing 4.2.3. 
2. Move the folder containing the app out of the Nextcloud tree. In my case, the nextcloud installation sits here `/opt/nextcloud/`. The folder with the app might be `/opt/nextcloud/apps/richdocuments/`. I moved that entire folder to a safe location. 
3. Download the old version of the app. This can be done from "All Releases" in the NC appstore. Try this one: [link](https://github.com/nextcloud-releases/richdocuments/releases/download/v4.2.3/richdocuments.tar.gz). 
4. Unpack that folder and move it where the folder of the 4.2.4 version was before you moved it. 
5. Make ownership and permissions of that folder to what the 4.2.4 was. In my case, all I needed to do was change ownership to `www-data:www-data`. (`sudo chown -R www-data:www-data richdocuments`). 
6. Enable the app in NC again and remember not to accidentally upgrade the app again :)
Good luck!

**Comment by schniepp** [comment]
If anything goes wrong, all you need to do is delete the new `richdocuments` folder you created and move the old folder back (revert step 2). This should restore everything exactly as it was.

**Comment by do1fmd** [comment]
Perfect! Downgrade worked and the App is running again! :smile:

**Comment by t-markmann** [comment]
Fixed in 4.2.5

**Comment by Kieltux** [comment]
For me 4.2.5 fixes the problem. Thank you.

**Comment by juliushaertl** [comment]
Let me close this then, thanks for reporting back everyone.

**Comment by t-markmann** [comment]
Open again. Does not work with Android and iOS App.

**Comment by schniepp** [comment]
I have in the meanwhile upgraded to NC 23, where 4.2.3 still worked, and the previous upgrade to 5.0.2 did not work in a Brave (Chrome) browser. Updating to the latest version 5.0.3 made it work in the browser. 

However, I see the same problem that @t-markmann has pointed out: it does not work in Android for me. I confirmed that 4.2.3 did work in Android.

**Comment by brtptrs** [comment]
We also have this probelem and could "solve" it with:
sudo -u adm php ./occ  config:app:set --value https://collabora.example.org richdocuments public_wopi_url

This was more or less a trail-and-error solution. Can someone explain this, or better, suggest a better configuration setup.



sudo -u adm php ./occ  config:list

------

        "richdocuments": {
            "disable_certificate_verification": "",
            "doc_format": "odf",
            "enabled": "yes",
            "installed_version": "4.2.5",
            "public_wopi_url": "https:\/\/collabora.example.org",
            "types": "prevent_group_restriction",
            "wopi_url": "https:\/\/collabora.example.org"
        },
