### ISSUE TITLE
Documents do not open (white Screen) Document loading failed - NGINX (Reverse Proxy)

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/richdocuments#2058]
Hi,
documents are not loading, when I click them in my Nextcloud
Ubuntu 20.04 LTS
NGINX 1.21.5
PHP 8.0.15
Nextcloud 23.0.2
Richdocuments 5.0.2

That's a snippet from my webserver-config:
```
### Start Collabora Online ###
 # static files
 location ^~ /browser {
   proxy_pass https://127.0.0.1:9980;
   proxy_set_header Host $http_host;
 }
 # WOPI discovery URL
 location ^~ /hosting/discovery {
   proxy_pass https://127.0.0.1:9980;
   proxy_set_header Host $http_host;
 }
 # Capabilities
 location ^~ /hosting/capabilities {
   proxy_pass https://127.0.0.1:9980;
   proxy_set_header Host $http_host;
 }
 # main websocket
 location ~ ^/cool/(.*)/ws$ {
   proxy_pass https://127.0.0.1:9980;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection "Upgrade";
   proxy_set_header Host $http_host;
   proxy_read_timeout 36000s;
 }
 # download, presentation and image upload
 location ~ ^/(c|l)ool {
   proxy_pass https://127.0.0.1:9980;
   proxy_set_header Host $http_host;
 }
 # Admin Console websocket
 location ^~ /cool/adminws {
   proxy_pass https://127.0.0.1:9980;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection "Upgrade";
   proxy_set_header Host $http_host;
   proxy_read_timeout 36000s;
 }
### End Collabora Online ###
```

Error by docker logs

```
wsd-00001-00039 2022-02-17 13:53:44.398793 +0000 [ websrv_poll ] ERR  #24 Exception while processing incoming request: [GET /cool/https%3A%2F%2Fcloud.escher.cc%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F203576_ocf86kk5j466%3Faccess_token%3DboFLRx3rqUWxSyOkeBt539q5IGdK65X7%26access_token_ttl%3D0/ws?WOPISrc=https%3A%2F%2Fcloud.escher.cc%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F203576_ocf86kk5j466&compat=/ws HTTP/...]: Invalid or unknown request.| wsd/COOLWSD.cpp:2832
wsd-00001-00039 2022-02-17 13:53:44.535537 +0000 [ websrv_poll ] ERR  Socket #24 SSL BIO error: closed unexpectedly (-1) (0: Success)| ./net/SslSocket.hpp:330
wsd-00001-00039 2022-02-17 13:53:44.535661 +0000 [ websrv_poll ] ERR  Error while handling poll for socket #24 at 0 in websrv_poll: SSL Socket closed unexpectedly.| net/Socket.cpp:465
wsd-00001-00039 2022-02-17 13:53:44.964258 +0000 [ websrv_poll ] ERR  #24 Exception while processing incoming request: [GET /cool/https%3A%2F%2Fcloud.escher.cc%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F203576_ocf86kk5j466%3Faccess_token%3DboFLRx3rqUWxSyOkeBt539q5IGdK65X7%26access_token_ttl%3D0%26permission%3Dedit/ws?WOPISrc=https%3A%2F%2Fcloud.escher.cc%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F203576_ocf86kk5j...]: Invalid or unknown request.| wsd/COOLWSD.cpp:2832
wsd-00001-00039 2022-02-17 13:53:45.814416 +0000 [ websrv_poll ] ERR  #24 Exception while processing incoming request: [GET /cool/https%3A%2F%2Fcloud.escher.cc%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F203576_ocf86kk5j466%3Faccess_token%3DboFLRx3rqUWxSyOkeBt539q5IGdK65X7%26access_token_ttl%3D0%26permission%3Dedit/ws?WOPISrc=https%3A%2F%2Fcloud.escher.cc%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F203576_ocf86kk5j...]: Invalid or unknown request.| wsd/COOLWSD.cpp:2832
```

**Comment by juliushaertl** [comment]
Can you check if you can properly reach the nextcloud server from the collabora one by issuing a request like:

curl -v https://cloud.escher.cc/status.php

**Comment by kangaroo72** [comment]
Hi Julius,
it's the same machine...

`root@sv-lx-te-01:/# curl -v https://cloud.escher.cc/status.php
*   Trying 79.246.153.215:443...
* TCP_NODELAY set
* Connected to cloud.escher.cc (79.246.153.215) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=escher.cc
*  start date: Feb 15 22:09:17 2022 GMT
*  expire date: May 16 22:09:16 2022 GMT
*  subjectAltName: host "cloud.escher.cc" matched cert's "cloud.escher.cc"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55ce70399e30)
> GET /status.php HTTP/2
> Host: cloud.escher.cc
> user-agent: curl/7.68.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200
< server: nginx
< date: Fri, 18 Feb 2022 11:42:11 GMT
< content-type: application/json
< expires: Thu, 19 Nov 1981 08:52:00 GMT
< cache-control: no-store, no-cache, must-revalidate
< pragma: no-cache
< set-cookie: oc_sessionPassphrase=AG4LrbUsQQTSYA1qbRnaD8cfmQX7hlyCy%2BMuRW9Z3NS5E3vBkneAEaz14pbMJF35JNSYbhSAWFguj1rWOeWU%2BGtdZG09j34RUUTRILYT%2FHZCFrde05Uymcr8Uxlv0b0R; path=/; secure; HttpOnly; SameSite=Lax
< set-cookie: ocf86kk5j466=v6ov8pah3gke739msfk9ogqdur; path=/; secure; HttpOnly; SameSite=Lax
< content-security-policy: default-src 'self'; script-src 'self' 'nonce-TzVvMzk4RUFHOXVVeDBqbmFCZUFacVJPNDluQlBJcW1URjkzZDNVelI2az06V2NCRW4vWllkcjZqaWdhZ0NYbkhEZGNHcUlDcmFmTEVCaWs5SVV3RGJOdz0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
< set-cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
< set-cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
< access-control-allow-origin: *
< strict-transport-security: max-age=15768000; includeSubDomains; preload;
< x-robots-tag: none
< x-download-options: noopen
< x-frame-options: SAMEORIGIN
< x-permitted-cross-domain-policies: none
< x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
< referrer-policy: no-referrer
<
* Connection #0 to host cloud.escher.cc left intact
{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"23.0.2.1","versionstring":"23.0.2","edroot@sv-lx-te-01:/#
`

**Comment by schniepp** [comment]
I also have the phenomenon of a white screen, as reported here: #2052 .
I am on NC 22, so the latest version for me is 4.2.4. The problem goes away if I downgrade to 4.2.3. Would there be a version you could downgrade to, to see if they are related?

**Comment by kangaroo72** [comment]
I'm not directly getting a "white screen". It results in "document failed" (see attached video

https://user-images.githubusercontent.com/6906390/154797593-b0f604c3-fce8-4696-9c6e-48516b36fc97.mp4

)

**Comment by manu-p** [comment]
Reading the docker logs in the 1st post makes me think of [this](https://github.com/tiredofit/docker-collabora-online/issues/3). Could it be related?

**Comment by kangaroo72** [comment]
sadly not solving my problem :-(
I'm working on a complete reinstall of my system... let's see then.
But this takes a while....

**Comment by joshtrichards** [comment]
> it's the same machine...

@kangaroo72 It's not though, at least from a network perspective, since you're using Docker.

Did you run that `curl` command *inside* your Collabora Online app container? (The prompt suggests you may have run it from your host inadvertently).

This seems like more of a config issue than a bug report. Have you tried posting for help on the Nextcloud Help Forum - https://help.nextcloud.com?

I'm going to close this issue out on that basis, but don't hesitate to come back if you have an actionable bug report. I'm sorry you ran into difficulty.
