### ISSUE TITLE
Sidebar is showing old file info after save as

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#2073]
When using save as the sidebar and folder don't refresh properly to represent the new document.

This might be a bit tricky as currently viewer does not assume that an open document will change, so we might need to extend its API to properly solve that. Likely a regression from the move to viewer.

**Comment by pedropintosilva** [comment]
Thanks @juliushaertl for being super fast on reporting it :)

**Comment by juliushaertl** [comment]
We close the sidebar now when using saveAs https://github.com/nextcloud/richdocuments/blob/e0b52724237ad35f9e10146cb0c152fce91ca74f/src/view/FilesAppIntegration.js#L124
