### ISSUE TITLE
CSP Error still exists in iOS and Android App

### ISSUE THREAD

**Issue by t-markmann** [nextcloud/richdocuments#2089]
The bug from https://github.com/nextcloud/richdocuments/issues/2052 and https://github.com/nextcloud/richdocuments/issues/2060 is fixed in the current versions of richdocuments, but it still occurs in the iOS and Android App.

**Comment by schniepp** [comment]
I confirmed that 4.2.3 did work on Android, but 5.0.3 does not. 

Trying to open it, the document appears to load forever. After a few seconds, I get the message "Loading takes very long...". From that it never advances.

**Comment by brtptrs** [comment]
At the moment we can not edit/open any files on android:
Mobile:
NC 3.19.1
Android 10

NC 22.x
Collabora/Richdocuments 4.2.5

Collabora Online :
COOLWSD
21.11.2.4 (git hash: e8ac597)
LOKit
Collabora Office 21.06.20.1 (git hash: 1bc9bd4)

**Comment by juliushaertl** [comment]
Potential fix is in https://github.com/nextcloud/richdocuments/pull/2126 testing is very welcome :)

**Comment by brtptrs** [comment]
Yes this seems to work.
Thank you!

**Comment by t-markmann** [comment]
Will there soon be a release with this fix? Thanks!
