### ISSUE TITLE
collabora online "does not work"

### ISSUE THREAD

**Issue by lemmy04** [nextcloud/richdocuments#209]
### Steps to reproduce
1. install nextcloud 13.0.2 from openSUSE repositories
2. install collabora online app from nextcloud appstore
3. install collabora on the same host as nextcloud but in a docker container, following instructions on https://nextcloud.com/collaboraonline/
4. "try to use it"

### Expected behaviour
I expect to be able to access documents stored inside my cloud in something similar to google docs or the likes

### Actual behaviour
I get a view that looks like word or excel but with all functions disabled and the content of the document not showing, i.e. the "About.odt" file that exists inside every new nextcoud account looks like this:
https://gyazo.com/64fb54a8eb163484ca548333262d80c4

## Server configuration detail

**Operating system:** Linux 4.4.132-53-default #1 SMP Wed May 23 06:57:07 UTC 2018 (036cd2f) x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.0.34

**PHP version:** 7.0.7
Modules loaded: Core, date, libxml, pcre, filter, hash, Reflection, SPL, session, SimpleXML, standard, xml, mysqlnd, apache2handler, apcu, ctype, curl, dom, fileinfo, gd, iconv, imagick, imap, json, mbstring, mysqli, openssl, pcntl, PDO, pdo_mysql, pdo_sqlite, posix, redis, sqlite3, tokenizer, xmlreader, xmlwriter, zip, zlib, Zend OPcache

**Nextcloud version:** 13.0.2 - 13.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** opensuse build service repository provided rpm packages

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_notifications: 1.0.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.1
 - circles: 0.13.6
 - comments: 1.3.0
 - contacts: 2.1.3
 - dav: 1.4.6
 - deck: 0.3.1
 - encryption: 2.0.0
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_opds: 0.8.8
 - files_pdfviewer: 1.2.1
 - files_reader: 1.2.3
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - groupfolders: 1.2.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mindmaps: 0.1.0
 - music: 0.6.1
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - piwik: 0.4.1
 - provisioning_api: 1.3.0
 - quota_warning: 1.2.0
 - richdocuments: 2.0.8
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - socialsharing_diaspora: 1.0.2
 - socialsharing_email: 1.0.3
 - socialsharing_googleplus: 1.0.2
 - socialsharing_twitter: 1.0.2
 - spreed: 3.2.1
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - twofactor_backupcodes: 1.2.3
 - twofactor_totp: 1.4.1
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - announcementcenter
 - dashboard
 - files_external
 - mail
 - theming
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.eregion.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/nextcloud.eregion.de\/",
    "htaccess.RewriteBase": "\/",
    "dbtype": "mysql",
    "version": "13.0.2.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "sendmail",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 1,
    "filelocking.enabled": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "maintenance": false
}
```
</details>

**Are you using external storage, if yes which one:** **NO**

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** **NO**

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

nothing stands out in the apache logs
</details>

<details><summary>Nextcloud log</summary>

nothing stands out in the nextcloud logs
</details>

<details><summary>Browser log</summary>

nothing special in the browser logs either
</details>

<details><summary>collabora online container log</summary>
In the logs of the docker container that runs my collabora online server instance I see a lot of "File not found" errors:

wsd-00026-00036 10:36:32.795347 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/dist/bootstrap/js/bootstrap.min.js].| wsd/FileServer.cpp:424
wsd-00026-00036 10:36:32.805833 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/dist/bootstrap/assets/js/vendor/holder.min.js].| wsd/FileServer.cpp:424
wsd-00026-00036 10:36:32.837532 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/dist/bootstrap/assets/js/ie10-viewport-bug-workaround.js].| wsd/FileServer.cpp:424
wsd-00026-00036 10:36:33.493324 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/dist/bootstrap/js/bootstrap.min.js].| wsd/FileServer.cpp:424
wsd-00026-00036 10:36:33.551397 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/dist/bootstrap/assets/js/vendor/holder.min.js].| wsd/FileServer.cpp:424
wsd-00026-00036 10:36:33.614770 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/dist/bootstrap/assets/js/ie10-viewport-bug-workaround.js].| wsd/FileServer.cpp:424
wsd-00026-00036 10:38:00.130419 [ websrv_poll ] WRN  WOPI host did not pass optional access_token_ttl| wsd/FileServer.cpp:583

This is from trying to open one file as a document...

</details>

**Comment by thebearon** [comment]
What does the browser console show?

**Comment by lemmy04** [comment]
something that looks like a connection issue:
Firefox kann keine Verbindung zu dem Server unter wss://collabora.eregion.de/lool/https%3A%2F%2Fnextcloud.eregion.de%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F169661_oclj240nar9s%3Faccess_token%3Dmr669OPWdLKHyKUWKqaNxtcWcjmqIVuI%26access_token_ttl%3D0%26permission%3Dedit/ws?WOPISrc=https%3A%2F%2Fnextcloud.eregion.de%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F169661_oclj240nar9s&compat=/ws

**Comment by lemmy04** [comment]
ok so google suggests that wss:// uses port 443 unless there is a port in the url, so i tried the same url with https:// and that got me 404. But: i can access the admin pages of my collabora container from the outside just fine, on the same hostname as in this url...

**Comment by lemmy04** [comment]
anyone got any ideas?

**Comment by lemmy04** [comment]
**facepalm** my vhost had one line in its configuration missing.

I **did** copy&paste from the collabora website so back then that vhost config example must have been wrong too, but now it's correct.
The missing bit was this:

```
# Encoded slashes need to be allowed
AllowEncodedSlashes NoDecode
```

now it works as expected.
