### ISSUE TITLE
add  richdocuments.tar.gz to latest release asset

### ISSUE THREAD

**Issue by dkebler** [nextcloud/richdocuments#2096]
unlike all the other releases this one is missing the
`richdocuments.tar.gz`
asset.
can you please add this to 5.0.3 (and all future releases).  I use this asset for custom installs.
Thx

**Comment by joshtrichards** [comment]
This looks like it was corrected:

https://apps.nextcloud.com/apps/richdocuments/releases?platform=23#23

https://github.com/nextcloud/richdocuments/releases/tag/v5.0.3

**Comment by juliushaertl** [comment]
Make sure to rather take the release from the separate release organization https://github.com/nextcloud-releases/richdocuments/releases or better even the download link from the app store directly https://apps.nextcloud.com/apps/richdocuments/releases?platform=27#27
