### ISSUE TITLE
Collabora CODE 3.2.2 intermittent issues with nextcloud

### ISSUE THREAD

**Issue by deajan** [nextcloud/richdocuments#210]
Hello,

I get a lot of random errors from Collabora Online.
I'm not really sure they're Nextcloud related, but here we go:

### Steps to reproduce
1. Setup fresh CentOS 7 x64 server
2. Install Collabora CODE 3.2.2 from RPM
3. Integrate with NextCloud 13.0.4 (installed on same server, setup with SSL certificate and all DNS entries)
4. Work with sheets

### Expected behaviour
Flawless working condition :-)

### Actual behaviour
Random issues like:
![image](https://user-images.githubusercontent.com/4681318/41854441-8ee55a84-7890-11e8-8ab8-e1124889e461.png)

Also random issue from the Lool admin page, maybe not related ?
![image](https://user-images.githubusercontent.com/4681318/41854504-b254b690-7890-11e8-8edc-8fbc04bbb185.png)

Server logs:
```
Jun 25 15:58:59 server loolwsd: wsd-02459-12203 13:58:59.450228 [ docbroker_003 ] WRN  Attempted ping on non-upgraded websocket!| ./net/WebSocketHandler.hpp:280
Jun 25 15:58:59 server loolwsd: wsd-02459-12203 13:58:59.450276 [ docbroker_003 ] WRN  Attempted ping on non-upgraded websocket!| ./net/WebSocketHandler.hpp:280
Jun 25 15:59:17 server loolwsd: wsd-02459-12203 13:59:17.484449 [ docbroker_003 ] WRN  Attempted ping on non-upgraded websocket!| ./net/WebSocketHandler.hpp:280
Jun 25 15:59:17 server loolwsd: wsd-02459-12203 13:59:17.484539 [ docbroker_003 ] WRN  Attempted ping on non-upgraded websocket!| ./net/WebSocketHandler.hpp:280
```
Actually I don't get any errors in the server logs from Collabora, just that big pile of warnings about the websocket. Btw, anyone knows why ?
Nextcloud logs are errorless too.

### Server configuration

**Operating system**:
CentOS 7 x64 uptodate
**Web server:**
Apache HTTP 2.4.6-80
**Database:**
MariaDB 5.5.56-2
**PHP version:**
PHP-FPM 7.0.27-1
**Nextcloud version:** (see Nextcloud admin page)
13.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
Well.. updated from owncloud 8 to 8.2, then used the nextcloud upgrade path
**Where did you install Nextcloud from:**
www.nextcloud.com
**Signing status:**
SHA256 checksums match with downloaded file.

Sorry if this isn't the right place for the bug report.

**Comment by pieter-groeneweg** [comment]
I have collabora installed on a debian. I also had trouble as my service would not start. 
https://help.nextcloud.com/t/native-debian-9-collabora-package-does-not-install-correctly/21191
You write you did setup domain, dns and certs... so I assume the following propably missing.

I cannot tell for CentOS install, but the Debian install needed editing of the loolwsd.xml file
Your nextcloud (sub)domain is to be added and you need to add the cert locations.... then (re)start the loolwsd service.

In debian you can find it here /etc/loolwsd/loolwsd.xml

in the <ssl> block (somewhere around line 70) ... edit:
```
<cert_file_path desc="Path to the cert file" relative="false">/path/to/ssl.cert</cert_file_path>
<key_file_path desc="Path to the key file" relative="false">/path/to/ssl.key</key_file_path>
<ca_file_path desc="Path to the ca file" relative="false">/path/to/ssl.ca</ca_file_path>
```
In the <wopi> block (somehwere round line 90) ...  add to the list:
`<host desc="Regex pattern of hostname to allow or deny." allow="true">sub\.domain\.com</host>`
note the slashed to escape the dots.

If this works, save a copy as on collabora update (not the nextcloud app) this gets overwritten by an empty one in some cases....

**Comment by deajan** [comment]
Thanks, but your solution is for another issue, which wasn't mine.
Yours made collabora work or not, mine was random.
Anyway, thanks for your help.
