### ISSUE TITLE
Firefox displays unexpected blue nextcloud logo.

### ISSUE THREAD

**Issue by dodedodo** [nextcloud/richdocuments#2103]
**Describe the bug**
Firefox shows an out-of-place blue logo in the notebookbar. Chromium based browsers do not. 

**To Reproduce**
1. Open a collabora text document in nextcloud
2. Observe the top-left of the page. You'll see a blue nextcloud logo here This may not be visible if you use the default nextcloud theme color. 

**Expected behavior**
I expect consistency between firefox/chrome. I would strongly prefer to show no logo because it does not match my nextcloud colors and also looks less cluttered. Alternatively richdocuments could follow the nextcloud theming/branding logo I configured in settings. 

**Screenshots**
Firefox: 
![image](https://user-images.githubusercontent.com/3252036/159349158-a40505e8-053c-4208-8712-87c89bc67470.png)
Edge chromium: 
![image](https://user-images.githubusercontent.com/3252036/159349268-ff878ab1-84b5-40b9-84b5-4fc2ef1a4ee8.png)

**Technical**
Diving through the firefox and chrome dev-tools I found out that `#document-header` in chrome based browsers has `class="hidden"` which applies `display: none !important` to the element. In firefox that same element has `class=""`. I'm not sure where this discrepancy comes from, nor do I know which behaviour would be 'correct'.

I've tried styling the element myself through the custom css app, but it didn't show up. My guess is that's because `#document-header` is inside an iframe. 

The full selector is `html.ng-csp body#body-user.theme--light div#viewer.modal-mask.viewer.modal-mask--dark.theme--light div.modal-wrapper.modal-wrapper--full.modal-wrapper--spread-navigation div.modal-container div.viewer__content div#richdocuments-wrapper.viewer__file.viewer__file--active iframe#collaboraframe html.ng-csp body#body-public.layout-base.theme--light.claro div#mainContainer.claro iframe#loleafletframe html body nav.main-nav.hasnotebookbar.text-color-indicator div#document-header`.

**Client details:**
 - OS: Manjaro Gnome
 - Browsers: 
   - Edge(chromium) 100.0.1181.0
   - Firefox 98.0.1
   - chromium 99.0.4844.74
 - Device: Laptop

## Server details

**Operating system**:
Docker nextcloud:23.0.2

**Web server:**
Docker (apache2 ?)

**Database:**
Docker mariadb:10.7.1

**PHP version:**
8.0.16

**Nextcloud version:**
23.0.2

**Version of the richdocuments app**
5.0.3

**Version of Collabora Online**
collabora/code:21.11.2.2.1

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
This has been fixed with the latest design adjustments.
