### ISSUE TITLE
Back button on mobile is invisible

### ISSUE THREAD

**Issue by delightfuldude** [nextcloud/richdocuments#2115]
The back button is invisible on android and ios:

![Screenshot_20220401-164813](https://user-images.githubusercontent.com/41424438/161287612-41022c59-aa91-4279-8f27-1db589b01679.png)

**Comment by dodedodo** [comment]
@delightfuldude My collabora does not have that problem. What versions of nextcloud, collabora and richdocuments(office) do you have installed?

**Comment by delightfuldude** [comment]
The problem seems to have been fixed with one of the latest updates (Nextcloud 24, offical docker image)!
