### ISSUE TITLE
Error proxy.php line 346 and 347

### ISSUE THREAD

**Issue by markginter31** [nextcloud/richdocuments#2119]
I put my nextcloud instance behind an nginx reverse proxy.  The overview in nextcloud doesn't show any errors.  Nextcloud acts as expected, Office opens and allows for editing of documents.  Copying/Pasting inside the document works.  When I try to copy from an external source and paste into the document I get the following errors in my log:
[Sat Apr 02 05:31:06.608557 2022] [php7:notice] [pid 17683] [client 192.168.x.x:58058] PHP Notice:  Undefined index: Content-Type in /var/www/html/gintersdrive/apps/richdocumentscode/proxy.php on line 346
[Sat Apr 02 05:31:06.608650 2022] [php7:notice] [pid 17683] [client 192.168.x.x:58058] PHP Notice:  Undefined offset: 1 in /var/www/html/gintersdrive/apps/richdocumentscode/proxy.php on line 347

**Expected behavior**
Copy and paste from external sources should continue to work - even behind a reverse proxy.

## Server details

**Operating system**:
Ubuntu 20.04
**Web server:**
Apache2
**Database:**
Mariadb
**PHP version:**
7.4
**Nextcloud version:**
23.0.3
**Version of the richdocuments app**
5.0.3

**Version of Collabora Online**
21.11.204

[Sat Apr 02 05:31:06.608557 2022] [php7:notice] [pid 17683] [client 192.168.76.6:58058] PHP Notice:  Undefined index: Content-Type in /var/www/html/gintersdrive/apps/richdocumentscode/proxy.php on line 346
[Sat Apr 02 05:31:06.608650 2022] [php7:notice] [pid 17683] [client 192.168.76.6:58058] PHP Notice:  Undefined offset: 1 in /var/www/html/gintersdrive/apps/richdocumentscode/proxy.php on line 347

**Comment by juliushaertl** [comment]
Plese report this issue in the richdocumentscode app at https://github.com/CollaboraOnline/richdocumentscode
