### ISSUE TITLE
The button text not visible

### ISSUE THREAD

**Issue by snetat** [nextcloud/richdocuments#2140]
**Describe the bug**
The button text not visible

**To Reproduce**
1. Activate in Personal - Settings Accessibility - Dark Theme
2. Set true "Use theme from the integrator" in coolwsd.xml
3. Open a document and navigate to the view menu for example, and activate "toogle ruler" or other buttons that snap to it.

**Expected behavior**
The button text should be visible.

**Screenshots**
![Screenshot from 2022-04-10 11-37-06](https://user-images.githubusercontent.com/5556794/162615364-993276ab-45fc-44ad-829d-b5f0d3d568b8.png)

**Client details:**
 - OS: Linux, Windows
 - Browser Chrome / Firefox 
 - Version 23.03
 - Device: Desktop

## Server details

**Operating system**:
Linux

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
8.0 fpm

**Nextcloud version:**
23.03

**Version of the richdocuments app**
latest

**Version of Collabora Online**
21.11.3.6

**Comment by thebearon** [comment]
This isn't a richdocuments bug, but in Collabora Online, please open an issue over here:
https://github.com/CollaboraOnline/online/issues

It seems you have a very dark Nextcloud theme color, which Collabora Online takes, but it doesn't take into account that if the background color gets too dark, the original colors should be inverted.
