### ISSUE TITLE
Infinite loop of: OCP\Share\Exceptions\ShareNotFound: The requested share does not exist anymore

### ISSUE THREAD

**Issue by dotKokott** [nextcloud/richdocuments#2145]
**Describe the bug**
Richdocuments is spamming my error log with:
OCP\Share\Exceptions\ShareNotFound: The requested share does not exist anymore
Stack trace:
```
/var/www/html/custom_apps/richdocuments/lib/Controller/WopiController.php - line 708:

OC\Share20\Manager->getShareByToken("dRjw4ioPEG2xjgm")

/var/www/html/custom_apps/richdocuments/lib/Controller/WopiController.php - line 495:

OCA\Richdocuments\Controller\WopiController->getFileForWopiToken(OCA\Richdocu ... 1})

/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 217:

OCA\Richdocuments\Controller\WopiController->putFile("7554", "gvvgrZAM3Ir ... R")

/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 126:

OC\AppFramework\Http\Dispatcher->executeController(OCA\Richdocu ... {}, "putFile")

/var/www/html/lib/private/AppFramework/App.php - line 157:

OC\AppFramework\Http\Dispatcher->dispatch(OCA\Richdocu ... {}, "putFile")

/var/www/html/lib/private/Route/Router.php - line 302:

OC\AppFramework\App::main("OCA\\Richdo ... r", "putFile", OC\AppFramew ... {}, { fileId: "7 ... "})

/var/www/html/lib/base.php - line 1006:

OC\Route\Router->match("/apps/richd ... s")

/var/www/html/index.php - line 36:

OC::handleRequest()
```

Even after disabling the app it keeps going. It seems to be stuck in some infinite loop as these errors are coming in at a super fast rate.

**To Reproduce**
I do not know when or how it started. Collabora has been used to edit some documents at some point but is currently not used by any users.

**Expected behavior**
Errors should not happen, especially not when the app is not being used.

**Screenshots**

**Client details:**
OS: Windows and OSX
Browser brave
Version: latest
Device: Desktop and Macbook

## Server details

Operating system:
Ubuntu 20

Web server:
whatever is configured in nextcloud:latest

Database:
mariadb

PHP version:
whatever is configured in nextcloud:latest

Nextcloud version:
nextcloud:latest

Version of the richdocuments app
COOLWSD version:
21.11.2.4

Version of Collabora Online
21.06.20.1

**Comment by shalak** [comment]
Did you ever found a way to fix/workaround this?

I'm having the same issue with nextcloud-aio 25.0.3. I (hopefully) stopped the loop by restarting the Collabora container.

**Comment by joshtrichards** [comment]
These look like upload (save) attempts from CODE/Collabora Online. Those apps/services save _to_ us.

> Even after disabling the app it keeps going

When you say you disabled the app, which app?

- richdocuments?
- richdocumentscode?
- a dedicated CODE/Collabora Online server/container?

The last two are where the upload would have been coming from. This app (richdocuments) is just handling what it's being given.

@shalak You didn't provide logs so I can't say it's the same with certainty, but the fact that restarting the Collabora Online/CODE container fixed it makes me think it probably was similar.

**Comment by juliushaertl** [comment]
There has been a bug in Collabora some time ago that could have caused retry spam of requests to save, but should be fixed with their latest version. I'll close this.

**Comment by juliushaertl** [comment]
Upstream reference issue https://github.com/CollaboraOnline/online/issues/5870
