### ISSUE TITLE
Nextcloud freeze after aktivating "Nextcloud Office" App (richdocuments)

### ISSUE THREAD

**Issue by Marco-Total** [nextcloud/richdocuments#2146]
### Steps to reproduce
1.sudo -u www-data /var/www/nextcloud/occ app:enable  richdocumentscode_arm64 -> all good
2. sudo -u www-data /var/www/nextcloud/occ app:enable richdocuments
3. Nextcloud freeze -> I can't load any nextcloud site, other applications (webmail, phpmyadmin) works

First I read, that this is possible a problem with max sql connections, but my monitoring looks fine:
```
MariaDB [(none)]> SHOW VARIABLES LIKE 'max_connections';
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| max_connections | 1024  |
+-----------------+-------+
1 row in set (0.003 sec)

MariaDB [(none)]> show status where variable_name = 'threads_connected';
+-------------------+-------+
| Variable_name     | Value |
+-------------------+-------+
| Threads_connected | 54    |
+-------------------+-------+
1 row in set (0.001 sec)
```

Then I try the helpful link here: https://github.com/nextcloud/richdocuments/issues/1817
```
My guess would be that there is an old configuration in place that tries to connect to the Collabora server but the connection would be pending and only reaching a timeout at some point. You can check that with occ config:list richdocuments and possibly remove the existing values with:

    occ config:app:delete richdocuments public_wopi_url
    occ config:app:delete richdocuments wopi_url
```
For me this help doesn't work. In the nextcloud log i can't find special error logs, only depreaded-messages:
`{"reqId":"dAZmHbm6hFRN2PW0ZGhp","level":0,"time":"2022-04-12T18:26:31+02:00","remoteAddr":"127.0.0.1","user":"--","app":"files_linkeditor","method":"GET","url":"/apps/richdocumentscode_arm64/proxy.php?req=/hosting/capabilities","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Nextcloud Server Crawler","version":"23.0.3.2"}`

In the php log I see some warnings like this:
`[12-Apr-2022 17:13:21] WARNING: [pool www] server reached pm.max_children setting (52), consider raising it`

so i set the max_children setting to 95, but the freeze error is still the same.

in the nginx log i can't see a error message.

I use a raspberry pi 4 with 8GByte RAM and raspberry pi os (arm64) with Debian 11 (Bullseye)

Can someone help me please? Thanks!

Marco

**Comment by kojid0** [comment]
This might be related to https://github.com/nextcloud/richdocuments/issues/1282

**Comment by Marco-Total** [comment]
ok, sorry, duplicate -> close
#1282

**Comment by kojid0** [comment]
Still tagging @juliushaertl since this info might be relevant for solving the issue.
Please re-open #1282 so that info regarding the same issue doesn't get spread everywhere. It makes solving the issue harder.
