### ISSUE TITLE
False failure message when trying to restore an older version of a file

### ISSUE THREAD

**Issue by gokaysatir** [nextcloud/richdocuments#2148]
**Describe the bug**
Have a few versions of a file. Then open it. Restore a previous version. The previous version is restored. There is a false failure message on top right corner.

**Expected behavior**
There should be a success message.

**Screenshots**

![failed_to_revert](https://user-images.githubusercontent.com/28108660/163146090-976e89ac-2c72-4ad8-aab8-ac084f5954c5.png)

**Nextcloud version:**
Latest.

**Comment by juliushaertl** [comment]
Fixed nowadays
