### ISSUE TITLE
Unable to install (Invalid Architecture: x86_64)

### ISSUE THREAD

**Issue by Anaerin** [nextcloud/richdocuments#2186]
**Describe the bug**
Attempting to install the CODE server, I get the an error saying the architecture is not supported.

**To Reproduce**
1. Open Nextcloud Apps as admin
2. Click "Install" on 

**Expected behavior**
The app installs.

**Screenshots**
`App "Collabora Online - Built-in CODE Server" cannot be installed because the following dependencies are not fulfilled: The following architectures are supported: x86_64`

**Client details:**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 100.0
 - Device: [e.g. iPhone6, desktop]

## Server details

**Operating system**: FreeBSD 12.0/TrueNAS 12 jail

**Web server**: nginx

**Database**: MySQL 8.0.26

**PHP version**: 7.4.25

**Nextcloud version**: 23.0.4

**Version of the richdocuments app**: N/A yet

**Version of Collabora Online**: N/A

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by Raudius** [comment]
Hi Anaerin

Looks like this is an issue when installing the CODE server and not the richdocuments app.  
Please report in: https://github.com/CollaboraOnline/richdocumentscode/issues (you may also want to include details on your server hardware)

It is also possible to install the CODE server manually: 
https://www.collaboraoffice.com/code/linux-packages/
