### ISSUE TITLE
Getting http error 500 if I try to activate the collabora server connection

### ISSUE THREAD

**Issue by cryptomilk** [nextcloud/richdocuments#2189]
**Describe the bug**

If I go to `index.php/settings/admin/richdocuments` and enter my collabora server instance url and click on Save I get error 500 back.

This happes after the upgrade from nextcloud 23 to 24. It worked just fine before.

https://office.xxxxxx.org/hosting/discovery works probably.

I find it strange that I don't have a log entry about the 500 error in the nextcloud.log.

Help to debug that is much appreciated!

**To Reproduce**
1. Go to `index.php/settings/admin/richdocuments`
2. Click on 'Save' with the collabora server url entered
3. Doesn't connect

**Expected behavior**
Should connect to collabora server.

**Client details:**
 - OS: Linux
 - Browser Firefox
 - Version 99

## Server details

**Operating system**:

**Web server:**
Apache

**Database:**
Postgres

**PHP version:**
7.4.6

**Nextcloud version:**
24

**Version of the richdocuments app**
6.0

**Version of Collabora Online**

```json
{"convert-to":{"available":false},"hasMobileSupport":true,"hasProxyPrefix":false,"hasTemplateSaveAs":false,"hasTemplateSource":true,"productName":"Collabora Online Development Edition","productVersion":"21.11.4.2","productVersionHash":"3eff190"}
```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
No log entries
```

#### Browser log
```
XHR POST https://cloud.cryptomilk.org/index.php/apps/richdocuments/ajax/admin.php
[HTTP/2 500 Internal Server Error 66ms]

	
POST
	https://cloud.cryptomilk.org/index.php/apps/richdocuments/ajax/admin.php
Status
500
Internal Server Error
VersionHTTP/2
Transferred896 B (78 B size)
Referrer Policyno-referrer

    	
    cache-control
    	no-cache, no-store, must-revalidate
    content-length
    	78
    content-security-policy
    	default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
    content-type
    	application/json; charset=utf-8
    date
    	Fri, 06 May 2022 11:41:44 GMT
    expires
    	Thu, 19 Nov 1981 08:52:00 GMT
    feature-policy
    	autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
    pragma
    	no-cache
    referrer-policy
    	no-referrer
    server
    	Apache
    strict-transport-security
    	max-age=15768000; includeSubDomains
    x-content-type-options
    	nosniff
    X-Firefox-Spdy
    	h2
    x-frame-options
    	SAMEORIGIN
    x-permitted-cross-domain-policies
    	none
    x-powered-by
    	PHP/7.4.6
    x-request-id
    	Ez7G78fQxLe0ialYIzAd
    x-robots-tag
    	none
    x-xss-protection
    	1; mode=block
    	
    Accept
    	application/json, text/plain, */*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    Content-Length
    	44
    Content-Type
    	application/json
    Cookie
    	__Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=asn; nc_token=XXXXXXXXXXXXXXXXXXXXXXXXX; nc_session_id=XXXXXXXXX; oc_sessionPassphrase=XXXXXXXXXXXXXXXx
    DNT
    	1
    Host
    	cloud.cryptomilk.org
    Origin
    	https://cloud.cryptomilk.org
    requesttoken
    	XXXXXXXXXXXXXXXXXXXXXXXXXx
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    Sec-GPC
    	1
    TE
    	trailers
    User-Agent
    	Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0

Error: Request failed with status code 500
    exports createError.js:16
    exports settle.js:17
    x xhr.js:66
    exports xhr.js:78
    exports xhr.js:15
    exports dispatchRequest.js:58
    request Axios.js:112
    t Axios.js:147
    exports bind.js:9
    n AdminSettings.vue:587
    u runtime.js:288
    _invoke runtime.js:262
    C runtime.js:84
    oi toast.scss:13
    i toast.scss:13
    ii toast.scss:13
    ii toast.scss:13
    updateSettings AdminSettings.vue:584
    e AdminSettings.vue:570
    u runtime.js:288
    _invoke runtime.js:262
    C runtime.js:84
    oi toast.scss:13
    i toast.scss:13
    ii toast.scss:13
    ii toast.scss:13
    updateServer AdminSettings.vue:567
    submit AdminSettings.vue:1
    VueJS 3
AdminSettings.vue:576
```
</details>

**Comment by juliushaertl** [comment]
> I find it strange that I don't have a log entry about the 500 error in the nextcloud.log.

Yes, there should be definitely be something logged in that case. Anything special about your log configuration maybe that would lead to the logs landings somewhere else?

**Comment by Raudius** [comment]
Hi thanks for the report. 

Github is not the ideal place to track configuration issues. I am in the process of cleaning up the repository to keep only the relevant issues (bugs, security issues and feature requests).

Here you can find some resources which should allow you to fix your issue:
 * [Installation guide](https://collabora-online-for-nextcloud.readthedocs.io/en/latest/install/)
 * [Collabora proxy configs (scroll down for NGINX)](https://sdk.collaboraonline.com/docs/installation/Proxy_settings.html)
 * [Nextcloud support forum for questions](https://help.nextcloud.com/c/support/)
