### ISSUE TITLE
Cannot disable 'compact view' once enabled

### ISSUE THREAD

**Issue by dodedodo** [nextcloud/richdocuments#2195]
Hello reader! Please react with a 👍 if you are experiencing the same issue. Thx! 

**Describe the bug**
In notebookbar, there's a "compact view" button under the "view" tab. It seemingly switches between classic and notebookbar ui. Once clicked, I am unable to disable compact view again. The corresponding button in the now-dropdown-menu is simply not there. This only affects the user that clicked it and is persistent across documents, but not across browsers (sessions). Logging out/in does not matter.

**To Reproduce**
1. Create a new text document
2. Click on 'view' -> 'compact view'
3. Try to go back to the original view
4. The 'compact view' button is not present in the corresponding 'view' dropdown menu. 

**Expected behavior**
I expect the 'compact view' button to be accessible through view -> compact view, regardless of UI style (notebookbar or classic)

**Screenshots**
This is the button I'm talking about. My own translations might not match up exactly with the official English wording. I could not find any reference online on this particular button. 
![image](https://user-images.githubusercontent.com/3252036/167491276-2b543cb0-e4cb-44d0-9110-50c3c2d443e6.png)
![image](https://user-images.githubusercontent.com/3252036/167492441-a71661bb-60be-4a18-a260-e4d07f1c4258.png)

**Client details:**
 - OS: Linux (gnome)
 - Browser: Edge (chromium)
 - Version v100.0.1181.0
 - Device: Laptop

## Server details

**Operating system**: Docker nextcloud:23.0.4

**Database:** mariadb:10.7.1

**PHP version:** 8.0.18

**Nextcloud version:** 23.0.4

**Version of the richdocuments app** 5.0.4

**Version of Collabora Online** collabora/code:21.11.4.2.1

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by pedropintosilva** [comment]
Hi @dodedodo hm maybe there is some confusion here (probably mine :p since I do not understand German (?)) but there was a renaming of the "modes" so now:

* Notebookbar mode is **Tabbed* view 
  *  In this view you will see the button to switch to the other view (compact) 
* Classic mode is **Compact** view
  *  In this view you will see the button to switch to the other view (tabbed) 

So to go back to the tabbed view you would click in the `Tabbladen weergave gebruiken` visible on your screenshot in that dropdown menu

**Comment by dodedodo** [comment]
Hey @pedropintosilva,

You're completely right. I did not identify that translation as being the opposite of 'compact view'. I really should've been able to figure this out myself though... 🙈

Thanks for pointing this out. I'll close this issue now.

**Comment by pedropintosilva** [comment]
no problem :) thanks for taking the time to test these things out :+1:

**Comment by sorenwacker** [comment]
I am also trapped in the compact view. Maybe add an item in the View menu to leave the compact view.
