### ISSUE TITLE
Add a comment not work when usename details profil nextcloud contain (é, è, ...)

### ISSUE THREAD

**Issue by netadm001** [nextcloud/richdocuments#2196]
Hello,
I'm new, if you want more information about de "bug" I post here, no problem and thanks you in advance.

I think it's a simple and little "bug", but : 

If you want to add a commentary on a file (writer, calc, etc...) whit collabora online CODE from package nextcloud, the commentary is not added, not saved.

To Reproduce
Create a profile with username Frédéric and check a file to add a commentary, --> comment not added
Modifie your username details profile from Frédéric to Frederic and check a file to add a commentary, --> comment added and you can save your file

I find this bug after many hours tests (sorry for my english)

Now it's work, but 1 time of 10, the comment not save anymore...

Desktop : 

    OS: Linux Mint
    Firefox, Chrome
    Last update for all components

![github001](https://user-images.githubusercontent.com/104864455/167578915-f326844d-1b00-4341-b0fc-5773024f9fbd.png)
l

**Comment by juliushaertl** [comment]
I cannot reproduce any issue with having `Frédéric` as the display name of a user, for the user id it shouldn't be possible to have special characters anyways due to https://github.com/nextcloud/server/blame/78e90b69ba0d241c0d72d7c52817bad6d7d3cf20/lib/private/User/Manager.php#L425-L429

Do you see any errors on the browser console, Nextcloud or Collabora log? Also could you please report which versions of the individual components you are using?

**Comment by netadm001** [comment]
Hello, thanks for your response and test.
I think I found a new direction to this bug, **see the attached video**.

Perhap on my first test, I don't see this, sorry, the bug is perhaps not on the username charachter, but inside the content text of a comment... ?!
1) When insert a comment with special character, the comment not save/adding
2) When insert a comment without  special character, the comment is saving/adde

https://user-images.githubusercontent.com/104864455/168802631-f146143b-7142-46a1-a24d-3ca4d6439481.mp4

d

**Comment by netadm001** [comment]
In addition, I find no error on logs about this issue.
You can see all version and actives apps at this time on my installation (4 images)
![actives_apps_01](https://user-images.githubusercontent.com/104864455/169247570-f61e43c7-6ef1-458e-8c0c-ceae95529e3c.png)
![actives_apps_02](https://user-images.githubusercontent.com/104864455/169247578-10d4e40a-ba6b-4309-999b-237610cb9f14.png)
![actives_apps_03](https://user-images.githubusercontent.com/104864455/169247590-129ea0a4-e906-4528-85d9-7ffab11d15e4.png)
![actives_apps_04](https://user-images.githubusercontent.com/104864455/169247596-107ab488-ed38-4368-8545-7a105e22018c.png)

**Comment by pedropintosilva** [comment]
interesting, thanks for the additional info @netadm001. I have tested writing those characters and other into comments and it saved ( tested, é è ô ç ã )

**Comment by pedropintosilva** [comment]
to paste the logs you can:
1. insert those comments 
2. then go to  avatar -> settings of your Nextcloud  and then logging 
![image](https://user-images.githubusercontent.com/65948705/169261231-585b6c89-52a5-4eb0-bc4b-f1c981c5177e.png)

**Comment by pedropintosilva** [comment]
you can also try:
1. to press f12 and then click in the console tab
2. Then insert comment with those characters
3. copy paste paste what it appears in the console here

**Comment by netadm001** [comment]
> you can also try:
> 
> 1. to press f12 and then click in the console tab
> 2. Then insert comment with those characters
> 3. copy paste paste what it appears in the console here

Thanks for your reply :-)
No new log when I insert thoses comments, but I see this (I don't know if it's in relation with my bug)

{"reqId":"h3BatRQH8Pct7ijGge6i","level":3,"time":"2022-05-19T10:00:08+00:00","remoteAddr":"","user":"--","app":"files","method":"","url":"--","message":"Backends provided no user object for ","userAgent":"--","version":"23.0.4.1","id":"628615e380d60"}

{"reqId":"muU29LYSzkY9TPyigA1g","level":3,"time":"2022-05-19T09:59:21+00:00","remoteAddr":"185.25.193.226","user":"fred","app":"PHP","method":"GET","url":"/nc/index.php/css/icons/icons-vars.css?v=1652937827","message":"Module 'sqlite3' already loaded at Unknown#0","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36","version":"23.0.4.1","id":"628615e380d6b"}

Sorry if my informations are not good :-(

**Comment by mmeeks** [comment]
How do you install and run COOL ? is it via the app-image ? there could be some PHP oddity in the php proxy around encoding (I guess) as an outside guess.

Can you give a screenshot of what happens when it doesn't save ? also as many logs as we can get from the server would be good.

**Comment by netadm001** [comment]
COOL is coolwsd ? If yes, I install it via the application store inside Nextcloud (Collabora CODE)
You can see what happend on the video I post 2 days ago, that's better than a screenshot I guess :-)

**Comment by netadm001** [comment]
I make a new test, I rename my profile name from Frederic to Frédéric.
I made a new test, and whith this config, a commentary without special charachter like (é, à, ç) dosen't save...
I think (but I'm a simple user), there is a correlation with special character, but I don't know where and why.
Many thanks for the time you accord to this bug, but if I'm the only one with this bug, don't waste your time on it if you can't reproduce the situation.

**Comment by juliushaertl** [comment]
All right, haven't tested yet with the built-in CODE server, but maybe this is only reproducible with that.

**Comment by thebearon** [comment]
In the end I confirmed this is related to the Built-in CODE server, so let's continue tracking this in https://github.com/CollaboraOnline/online/issues/4732 .

**Comment by mmeeks** [comment]
Ah - interesting; so I wonder what proxy.php is doing to our UTF-8 encoded strings =) I would expect that we should have a header() call of the form:

header('Content-Type: text/html; charset=utf-8');

in the PHP proxy.php called - and that this would be based on the Content-Type: we just proxy from coolwsd itself.

@thebearon can you try testing this https://github.com/CollaboraOnline/online/pull/4793 ?

**Comment by netadm001** [comment]
Can I help for testing anything ?

**Comment by timar** [comment]
In fact, this bug was fixed by 29d7937a466895dd0f2b85d97fa145b7d3403ecf in richdocumentscode 22.5.1301 release today.
