### ISSUE TITLE
Documentation and procedure: Adding more fonts to the office environment

### ISSUE THREAD

**Issue by noseshimself** [nextcloud/richdocuments#2200]
**Is your feature request related to a problem? Please describe.**
Adding fonts to Collabora is one of the most frustrating experiences. Currently none of the guess-work solutions that can be found via Google (usually "put your fonts into /usr/(local/)share/fonts, run fc-cache (or the likes) is currently working for me. And with Nextcloud in a Docker container things are not getting better.

**Describe the solution you'd like**
Provide some Nextcloud-internal way to upload fonts that will arrive in the right place, preferably with the subdirectory structure intact. Erasing fonts might be nice, too.

**Describe alternatives you've considered**
Provide document templates that contain the fonts you want to use (but do NOT optimize them on saving in LibreOffice or you will only get the characters the templates really use -- a good idea for PDFs but a very bad idea for a document template that might be modified later) does work. But it seems to be rather clumsy.

**Comment by juliushaertl** [comment]
Thanks for your feature request, there has been some work to make this work for the next release with #2032 There are some steps left to ease the configuration, but the actual feature will come with the next major release.
