### ISSUE TITLE
Blank configuration screen

### ISSUE THREAD

**Issue by Igortorrente** [nextcloud/richdocuments#2211]
**Describe the bug**
The Nextcloud office configuration screen is blank.

**To Reproduce**
1. Install Nextcloud office with `podman exec --user www-data nextcloud-fpm php occ app:enable richdocuments`
2. Access the Nextcloud office configuration screen.
3. See a blank screen instead of the configurations.

**Expected behavior**
A screen with all configurations

**Screenshots**
![Screenshot from 2022-05-14 22-15-10](https://user-images.githubusercontent.com/18224386/168453222-89294f50-1175-4cd3-8ef9-0c04d562ecaf.png)

**Client details:**
 - OS: Debian 11 (bullseye)
 - Browser Firefox (64-bit)
 - Version  91.9.0esr 
 - Device: Desktop

## Server details

**Operating system**:  Debian 11 (bullseye)

**Web server:** nginx/1.20.2

**Database:** Postgresql 14.2

**PHP version:** 8.0.18

**Nextcloud version:** 24.0.0

**Version of the richdocuments app** 6.0.0

**Version of Collabora Online** 21.11.4.2.1

#### Browser log

**The javascript console log**:
![Screenshot from 2022-05-14 22-26-54](https://user-images.githubusercontent.com/18224386/168453595-13f1c473-c3fb-4f56-ae49-848728556a5a.png)

**Comment by juliushaertl** [comment]
The blocked request seems odd as it tries to load dashboard. Can you check the network console if the script in js/richdocuments-admin.js gets loaded properly?

**Comment by Igortorrente** [comment]
Hopefully the screenshot below is what you are asking for...


![Screenshot from 2022-05-16 17-47-07](https://user-images.githubusercontent.com/18224386/168680064-cfa8a921-ca86-4c18-8c93-5e5c966eee85.png)

**Comment by juliushaertl** [comment]
Ok, so it doesn't get loaded but the icon of the settings is also not showing up nicely. I would assume there is an issue with loading the files. Could you check if the files are properly deployed inside of the container? Maybe you can try to remove the app directory and reinstall it again?

**Comment by Igortorrente** [comment]
``` console
podman run --rm -it -v $PWD/nextcloud/html:/var/www/html -v $PWD/nextcloud/apps:/var/www/html/custom_apps -v $PWD/configs/nextcloud/:/var/www/html/config/ -v $PWD/log/php-fpm-nextcloud/:/usr/local/var/log/ -v $PWD/configs/php-fpm.conf:/usr/local/etc/php-fpm.conf -v $PWD/nextcloud/data/:/var/www/html/data --pod nextcloud-pod --name nextcloud-fpm nextcloud:24-fpm bash

root@nextcloud-pod:/var/www/html# ls -lha custom_apps/richdocuments/
total 1.7M
drwxr-xr-x 13 www-data www-data 4.0K May 17 20:27 .
drwxr-xr-x  4 www-data root     4.0K May 17 20:27 ..
-rw-r--r--  1 www-data www-data  151 May 17 20:27 .eslintrc.js
drwxr-xr-x  4 www-data www-data 4.0K May 17 20:27 .github
-rw-r--r--  1 www-data www-data  242 May 17 20:27 .nextcloudignore
-rw-r--r--  1 www-data www-data  132 May 17 20:27 .scrutinizer.yml
-rw-r--r--  1 www-data www-data  680 May 17 20:27 .stylelintrc.js
drwxr-xr-x  2 www-data www-data 4.0K May 17 20:27 .tx
-rw-r--r--  1 www-data www-data  30K May 17 20:27 CHANGELOG.md
-rw-r--r--  1 www-data www-data 4.0K May 17 20:27 README.md
drwxr-xr-x  2 www-data www-data 4.0K May 17 20:27 appinfo
-rw-r--r--  1 www-data www-data   85 May 17 20:27 babel.config.js
drwxr-xr-x  2 www-data www-data 4.0K May 17 20:27 css
drwxr-xr-x  2 www-data www-data 4.0K May 17 20:27 docs
drwxr-xr-x  2 www-data www-data 4.0K May 17 20:27 emptyTemplates
drwxr-xr-x  2 www-data www-data 4.0K May 17 20:27 img
drwxr-xr-x  2 www-data www-data 4.0K May 17 20:27 js
drwxr-xr-x  2 www-data www-data 4.0K May 17 20:27 l10n
drwxr-xr-x 16 www-data www-data 4.0K May 17 20:27 lib
-rw-r--r--  1 www-data www-data 1.6M May 17 20:27 package-lock.json
-rw-r--r--  1 www-data www-data 3.5K May 17 20:27 package.json
-rw-r--r--  1 www-data www-data 1.7K May 17 20:27 psalm.xml
drwxr-xr-x  2 www-data www-data 4.0K May 17 20:27 templates
-rw-r--r--  1 www-data www-data  219 May 17 20:27 tsconfig.json
```
>  Maybe you can try to remove the app directory and reinstall it again?

I reinstall the app through the web page, which for my surprise deleted the `richdocuments`folder, but no luck so far.

I tried the custom-menu and polls apps. Custom-menu is working. but polls isn't. 

The icons of all apps are not showing up in any "custom_app". Not sure what could be.

**Comment by Igortorrente** [comment]
Actually, there's a deep problem with my installation. For some reason all app installed in `custom_apps` aren't working properly.

**Comment by Igortorrente** [comment]
@juliushaertl Thanks for your help :)
