### ISSUE TITLE
Fix endless redirect on CSP detection

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#2223]
There are a few issues with the way we try to automatically detect if a proper CSP is set for federated editing, leading to issues causing an endless reloading.

- [ ] Drop option that dynamically injects the CSP since we only have a allow list these days anyways
- [ ] Pass trusted domains as a initial state value
- [ ] Validate against the list of trusted domains in the frontend
  - [ ] Show a useful error if list doesn't match
  - [ ] Otherwise just open the document without reload

**Comment by joshtrichards** [comment]
Did #2234 address this, @juliushaertl? (Not gonna lie - I was too lazy to dig into the PR in this case; figured you'd know off the top of your head more quickly 😂).

**Comment by juliushaertl** [comment]
Yes, this is obsolete. The faulty redirect handling was dropped with this exact PR.
