### ISSUE TITLE
No menu

### ISSUE THREAD

**Issue by snetat** [nextcloud/richdocuments#2227]
**Describe the bug**
No menu with richdocuments 6.1.0

**To Reproduce**
Open or create an new Document

**Expected behavior**
A Menu with File, Home, etc

**Screenshots**
![Screenshot from 2022-05-18 21-20-54](https://user-images.githubusercontent.com/5556794/169141104-e74c6ac8-c570-442a-b637-2ad00334dccd.png)

**Client details:**
 - OS: Linux, Windows
 - Browser Latest Chrome, Firefox 
 - Version 24
 - Device: Desktop

## Server details

**Operating system**: Linux

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 8.0

**Nextcloud version:** 24

**Version of the richdocuments app** 6.1.0

**Version of Collabora Online** 21.11.4.3

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by kkofler** [comment]
Same here, probably a regression from:
> Fixed viewer styling @juliushaertl #2221 #2212

**Comment by JoshuaPettus** [comment]
Happens to me as well.

Ironic that instead of fixing an issue that supposedly affected 1 web browser some of the time (Never had an issue with firefox myself), suddenly there is an issue with all browsers all the time.  Was this tested?

**Comment by XueSheng-GIT** [comment]
I got the same issue on a instance with NC24.0.0 and Nextcloud Office 6.1.0.
But on another instance with NC24.0.1rc1 and Nextcloud Office 6.1.0 everything seems to be fine!

**Comment by oreinert** [comment]
I get this behaviour, too, in Firefox with NC 24.0.0 and 24.0.1, as soon as I update to Nextcloud Office 6.1.0.

The weird blank area along the bottom of the window (where the previous page can be dimly seen) can be used to close the office editor - just click in it.

**Comment by himpierre** [comment]
hello devs? 6.1.0 is delivered to anyone. should you guys not at least pull 6.1.0 untill this issue is fixed?

**Comment by ASchmidt71** [comment]
Since today 24.0.1 is available to me as well, so I assume the prob will be resolved to anyone else very soon. Despite this issue, NC is a great piece of SW, thanks to all contributors!

**Comment by kkofler** [comment]
Does 24.0.1 actually fix the issue for you? @oreinert wrote that this also happens with 24.0.1.

**Comment by ASchmidt71** [comment]
To be honest I don't know and I haven't tried, yet. I just assumed that because of the related issues on that topic where it was mentioned several times that 6.1.0 works well on 24.0.1

**Comment by himpierre** [comment]
24.0.1 solves the issue for me. Cheers!

Am 23. Mai 2022 11:20:00 MESZ schrieb Kevin Kofler ***@***.***>:
>Does 24.0.1 actually fix the issue for you? @oreinert wrote that this also happens with 24.0.1.
>

**Comment by snetat** [comment]
looks good for me, thanks

**Comment by kkofler** [comment]
Nextcloud 24.0.1 solves the issue for me too.

**Comment by oreinert** [comment]
Now it also works for me on NC 24.0.1. Not sure what has changed, but I guess the separate CODE server has been upgraded in the meantime.
