### ISSUE TITLE
In 6.1.0 the toolbar gets cut off on writer/calc documents

### ISSUE THREAD

**Issue by Luticus** [nextcloud/richdocuments#2228]
**Describe the bug**

Since updating to 6.1.0 the top of the application gets clipped off where I can only see about 1/2 of any given icon on the toolbar across the top. I can click the X but it doesn't close the application. This takes place under the latest version of Firefox as far as I've tested. I have not tested other browsers.

This does not occur when I down grade to my previous version:  5.0.4

**To Reproduce**
1. Install version 6.1.0 on nextcloud 24 and open any document.

**Client details:**
 - OS: Debian 11
 - Browser Firefox 100
 - Device: Desktop

## Server details

**Operating system**: Debian 11

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** 24

**Version of the richdocuments app** 6.1.0

**Version of Collabora Online** collaboraoffice6.4/now 6.4.10.50-50

**Comment by Luticus** [comment]
Since updating to Nextcloud 24.0.1 the problem seems to have gone away when using office 6.1.0, will keep testing and report back.

**Comment by JoshuaPettus** [comment]
That's good to hear... Shame Nextcloud won't let me patch to 24.0.1 yet...  Stupid partial releases... Major releases are one thing but I'll never understand why patch releases aren't immediate for everyone.   

- [ ]

**Comment by juliushaertl** [comment]
@JoshuaPettus There is no staged rollout of patch releases. If you are on 24 you should get 24.0.1 immediately: https://github.com/nextcloud/updater_server/blob/master/config/config.php#L111-L113

In regards to the issue this is indeed fixed by 24.0.1 as stated with https://github.com/nextcloud/richdocuments/issues/2227#issuecomment-1134817166

**Comment by JoshuaPettus** [comment]
You sure there is no staged rollout?  I only got the ability to update today

**Comment by Luticus** [comment]
I'm not sure about the staged rollout thing, I update by downloading the .zip/.tar.gz from nextcloud.com and running it manually. I don't allow the auto updater to do it's thing because my instance has historically been very complex and I micromanage it.
