### ISSUE TITLE
disable add new documents

### ISSUE THREAD

**Issue by u443871** [nextcloud/richdocuments#2229]
**Describe the bug**
I disable the edit capabilities and user only could view, but user could add new documents, I want to disable it.  
  
I try to edit  
```
/lib/AppInfo/Application.php
```
  
line 87~89  
```
if (empty($capabilitiesService->getCapabilities())) {
    return;
}
```
edit the nest like this  
```
$workaround = $capabilitiesService->getCapabilities()
if (empty($workaround)) {
    return;
}
```
and it work as I want,    
  
I think it's something wrong in get $capabilitiesService in my enviroment, please help to fix it,   
thanks!  

**Client details:**
 - OS: Windows
 - Browser chrome
 - Version
Nextcloud: 23.04
Nextcloud Office: 5.05
 - Device: desktop

**Comment by Raudius** [comment]
You can already disable users from editing the docs from the administration page. Using the "Restrict edit to specific groups" option:

![image](https://user-images.githubusercontent.com/3178979/193583073-dbe73b9e-b199-4cbe-a3c2-8df1527f00b6.png)


Hope this helps
