### ISSUE TITLE
no scrolling possibility on smartphone browser for the collabora online demo wellcome popup

### ISSUE THREAD

**Issue by dinodino2022** [nextcloud/richdocuments#2243]
**Describe the bug**
after clicking with a a mobile phone (Iphone, browser edgeor firefox) on a share file collabora online demo Document. there is no scrolling possibility on smartphone browser for the collabora online demo wellcome popup. It is also not possible to click on the accept the risks button for this popup window.

**To Reproduce**
1. click on a share file (online Demo Version) with your browser
2. the welcome demo pop up warning will be show
3. there is no possibility to scroll down within the popup window to the accept button
4. the user cannot use the file and is blocked at this stage

**Expected behavior**
it should be able to scroll down on this pop up window

**Screenshots**
behavior on a laptop, behavior is fine, accept button is accessible. see below:
![grafik](https://user-images.githubusercontent.com/106167780/170061778-fbfc348d-af42-488c-be44-55a67d4ccdc2.png)

behavior on a mobile phone (Iphone, Browser firefox). it is not possible to click on the button or to scroll down within the popup window
![20220524_143547000_iOS](https://user-images.githubusercontent.com/106167780/170062482-aff96cf8-81a5-445e-a603-475580323369.png)

**Client details:**
 - OS: IOS 15.5
 - Browser: Firefox, Edge
 - Version 100.1
 - Device: Iphone 11

## Server details

**Operating system**: nextcloud: www.northkiez.net

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:**

**Version of the richdocuments app**

**Version of Collabora Online**

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
Should be addressed by https://github.com/CollaboraOnline/online/pull/4619
