### ISSUE TITLE
The button for creating a new diagram file remains "New diagram" (english words) in the non-English interface (at least in French)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/richdocuments#2262]
_I have opened this issue in nextcloud/richdocuments, but I may be wrong. Maybe the problem is with nextcloud/server. To be confirmed._

**Describe the bug**
In Nextcloud Files, after clicking on the "+" button, the button for creating a new diagram file remains "New diagram" in the non-English interfaces (at least in French).

**To Reproduce**
- Turn your user in french (user settings)
- Go to Nextcloud files
- Click on "+"

**Then, 2 problems to notice after clicking on "+" :** 
- Note that "New diagram" is always "New diagram" and not "Nouveau diagramme" (although the translation (in /l10n) does exist.
- Also the default suggested file name is "New diagram.odg" (instead of "Nouveau diagramme.odg")

**Expected behavior**
"Nouveau diagramme" should appear instead of "New diagram"

**Screenshots**
![2022-06-03_14-24](https://user-images.githubusercontent.com/33763786/171854021-684a9f15-14ac-4285-aa78-2c6c1d115eb9.png)

**Client details:**
 - OS: GNU/Linux Ubuntu 20.04 LTS
 - Browser Mozilla Firefox 100.0.2
 - Device: Laptop

## Server details

**Operating system:** CentOS 7

**Web server:** nginx/1.21.6

**Database:** mysql 10.4.22

**PHP version:** 7.4.21

**Nextcloud version:** 23.0.5

**Version of the richdocuments app:** 5.0.5

**Version of Collabora Online:**
Version COOLWSD : 21.11.4.2 
Collabora Office 21.06.28.1 

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
I don't think this is necessary, especially as the file is large, but I can provide them if required.

#### Browser log
I don't think this is necessary, especially as the file is large, but I can provide them if required.

</details>

**Comment by juliushaertl** [comment]
Should be fixed with the next maintenance release as translations now also get back ported to stable branches with https://github.com/nextcloud/richdocuments/pull/2232
