### ISSUE TITLE
Does not copy cells when filtering.

### ISSUE THREAD

**Issue by x4IPx** [nextcloud/richdocuments#2266]
**Describe the bug**
Doesn't copy cells while filtering a column. If all filters are disabled, the data is copied without problems.

**To Reproduce**
1. Create excel file
2. Create a simple table like :

Name | Price
-- | --
one | 300
two | 2000
three | 39999
four | 2000
five | 300
six | 300
seven | 200

3. Filter Price by 300 (Data -> Autofilter.)

4. Try to copy text

![image](https://user-images.githubusercontent.com/58852253/172174644-737ae895-6003-4e06-9128-6a268fe5d584.png)

Collabora Online Development Edition
Version COOLWSD:
21.11.4.2
LOKit:
Collabora Office 21.06.28.1
Version COOLWSD:
21.11.4.2
Version LOKit:
Collabora Office 21.06.28.1
Works for:
 Ubuntu 18.04.6 LTS

**Comment by juliushaertl** [comment]
This seems to be a bug related to Collabora Online. Could you please open a report for that at https://github.com/CollaboraOnline/online ?
