### ISSUE TITLE
There is no possibility to search for content containing Cyrillic

### ISSUE THREAD

**Issue by sazanof** [nextcloud/richdocuments#2275]
**Describe the bug**
There is no possibility to search for content containing Cyrillic

**To Reproduce**
1. Open xls(x) File, that contains cyrillyc word anywhere, ex **"Раз два три"**
2. Click on 'Edit->Find and Replace' or Ctrl+F
3. Type for ex. **"два"**
4. Nothing happens...

**Expected behavior**
The search should search by different characters

**Client details:**
 - OS: Ubuntu, Windows, Mac OS
 - Browser different

**Comment by thebearon** [comment]
I assume this happend with Built-in CODE Server, in which case this is a duplicate of https://github.com/CollaboraOnline/online/issues/4732 .
