### ISSUE TITLE
Nextcloud Office not working after upgrade from 23.0.3 to 24.0.2

### ISSUE THREAD

**Issue by fredtep** [nextcloud/richdocuments#2282]
### Steps to reproduce
1. Click on Use built-in CODE

After an upgrade from 23.0.3 > 23.0.6 > 24.0.2 Nextcloud Office is not working anymore. 
 In setting > Nextcloud Office I've got this error : Could not establish connection to the Collabora Online server.

Trying to debut I've got a 500 error 

in firefox debugger / Network clicking on setting > Nextcloud > use built-in CODE, I've got a POST request to /index.php/apps/richdocuments/ajax/admin.php which does not exist on the server resulting in a 500 error

### Server configuration
Operating System: Linux 5.15.0-1006-raspi aarch64
CPU: Raspberry Pi 4 Model B Rev 1.1 (4 cores)
Memory: 3.70 GB
PHP version: 8.0
Nextcloud version: 24.0.2
Updated from 23.0.3

**Comment by natrius** [comment]
If you had an old version its quite possible that some stuff has changed. If you read through https://www.linuxbabe.com/ubuntu/integrate-collabora-onlinenextcloud-without-docker you see a lot of `coolwsd` and it was `loolwsd` in older versions. Check your nginx for example if there is something with `lool` and so on. I am working on this right now and now my Nextcloud can connect again to Collabora but the files do not open currently.

**Comment by Raudius** [comment]
Github is not the ideal place to track configuration issues. I am in the process of cleaning up the repository to keep only the relevant issues (bugs, security issues and feature requests).

Here you can find some resources which should allow you to fix your issue:

   - [Installation guide](https://collabora-online-for-nextcloud.readthedocs.io/en/latest/install/)
   - [Collabora proxy configs (scroll down for NGINX)](https://sdk.collaboraonline.com/docs/installation/Proxy_settings.html)
   - [Nextcloud support forum for questions](https://help.nextcloud.com/c/support/)
   - [Collabora support forum for questions](https://forum.collaboraonline.com/c/user-support/11/)

**Comment by natrius** [comment]
@fredtep 
You might check out https://github.com/CollaboraOnline/online/issues/4966#issuecomment-1238720448 where i solved the issue and tried to write down an explanation.
