### ISSUE TITLE
Issues with Nextcloud 23.0.3 and Nextcloud Office 5.0.5

### ISSUE THREAD

**Issue by mleikin-gh** [nextcloud/richdocuments#2289]
It is noted that the Word online application does not allow merging cells, and if a document generated on desktop with a merged cell is uploaded, it cannot be split.
At the same time, if the table inserted in Word contains a row with merged cells, it does not allow rows to be deleted and the same happens with columns.
If a table is inserted, it allows you to insert rows and columns but does not perform a specific cell treatment.
Is there any functionality missing?

Regards,
mleikin-gh

**Comment by Raudius** [comment]
Cell merging seems to be possible when using Collabora 22.05.5.2 (this is the one included in the latest Nextcloud Office CODE Server release)

Also closing this issue because it is not related to this repository (see: https://github.com/CollaboraOnline/online)
