### ISSUE TITLE
[Feature] Make NC theming match Collabora theme

### ISSUE THREAD

**Issue by Alquh** [nextcloud/richdocuments#229]
**Steps to reproduce**
Install NC and theming app with Collabora
Navigate to settings and enable theming (if not enabled)
Change logo and color theme
Navigate to Collabora

**Expected behaviour**
Collabora's logo and color theme should match Theming settings

**Actual behaviour**
Collabora's default logo and theme are appearing

Rational for change: Theming for Collabora would be nice if it matched Nextcloud

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/richdocuments/pull/1211
