### ISSUE TITLE
Buttons are unreadable in firefox with Windows dark theme enabled

### ISSUE THREAD

**Issue by hartsberger** [nextcloud/richdocuments#2300]
**Describe the bug**
Buttons are not readable, because of dark background color. Only in Firefox. 
I am using the "Collabora Online - Built-in CODE Server". Nextcloud is running in Docker. 

**To Reproduce**
1. Activate the dark theme in Windows 10 settings
2. Open a collabora document from Nextcloud in the Firefox browser
3. See the dark background color on all bars and buttons

**Expected behavior**
Either: Lighten the background color
Or: Use the default (white) background color like it is used in the Edge browser. 

**Screenshots**

Activate dark theme in Windows: 

![2022-07-06 11_21_23-Window](https://user-images.githubusercontent.com/60740965/177517494-2d1083df-4ed0-445a-a226-5cc80b48c3c5.png)

Firefox: 

![2022-07-06 11_21_57-Window](https://user-images.githubusercontent.com/60740965/177517489-ee0d3556-f8a2-4d18-9c4d-46f66c5a6912.png)

Edge: 

![2022-07-06 11_22_47-Window](https://user-images.githubusercontent.com/60740965/177517483-230ec8fc-5701-45dc-ad6e-c049d6428367.png)

**Client details:**
 - OS: Windows 10
 - Browser Firefox ESR 91.11.0esr (64-Bit)
 - Version 22.2.9
 - Device: Desktop

## Server details

**Operating system**: Linux 4.14.35-2047.508.3.3.el7uek.x86_64

**Web server:**

**Database:** 	mysql 10.4.8

**PHP version:** 8.0.20

**Nextcloud version:** 22.2.9

**Version of the richdocuments app** 

**Version of Collabora Online**4.2.7

Collabora Online - Built-in CODE Server: 22.5.301

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by Raudius** [comment]
Fixed with https://github.com/nextcloud/richdocuments/pull/2550
