### ISSUE TITLE
@juliushaertl isn't this solved in the meantime? :)

### ISSUE THREAD

**Issue by goerbs** [nextcloud/richdocuments#2305]
@juliushaertl isn't this solved in the meantime? :)

_Originally posted by @szaimen in https://github.com/nextcloud/richdocuments/issues/1282#issuecomment-1149694063_

i think not. i have the same Problem with 5.0.6

**Comment by Niclas-sol** [comment]
I have the same problem with NC 24.0.3, richdocuments 6.1.1 and richdocumentscode 22.5.401. After enabling of richdocuments the cloud freezes.

**Comment by 27632** [comment]
same here with NC 24.0.4 richdocuments 6.2.0 and richdocumentscode 22.5.502

**Comment by juliushaertl** [comment]
Closing as a duplicate of https://github.com/nextcloud/richdocuments/issues/1282#issuecomment-1293838295
