### ISSUE TITLE
Video/music integration

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/richdocuments#2314]
**Is your feature request related to a problem? Please describe.**
I am looking for an alternative to PowerPoint and NC Office as far as I can tell does not have the ability to insert music and video files.

**Describe the solution you'd like**
The function to be able to add video and audio files

**Comment by juliushaertl** [comment]
This is something that would need to be implemented in Collabora Online, so maybe you could open a feature request at https://github.com/CollaboraOnline/online
