### ISSUE TITLE
Update screenshots on apps.nextcloud.com

### ISSUE THREAD

**Issue by schiessle** [nextcloud/richdocuments#2339]
The screenshots on apps.nextcloud.com look quite outdated. Would be nice to have some up-to-date Nextcloud Office screenshots (compact view and tabbed view)

**Comment by juliushaertl** [comment]
Will self update with the next release https://github.com/nextcloud/richdocuments/commit/da91a2c249ac79ee7ceee589504684e73c6edf7e
