### ISSUE TITLE
Collabora Online broken in Nextcloud14

### ISSUE THREAD

**Issue by schiessle** [nextcloud/richdocuments#237]
Collabora Online broken with Nextcloud 14 beta3 on public pages

![image](https://user-images.githubusercontent.com/1589737/44033082-83bfdc02-9f09-11e8-9627-92512d98334e.png)

probably related to some template changes we did for Nextcloud 14: https://github.com/nextcloud/server/pull/9982

cc  @skjnldsv

**Comment by skjnldsv** [comment]
@schiessle the bottom padding?

**Comment by schiessle** [comment]
@skjnldsv bottom padding and the icon bar at the top is missing

**Comment by skjnldsv** [comment]
For the icons, this is coming from the iframe, so I'm really not sure this is related to the layout update.
Also, the toolbar is hidden because the file is in readonly:
```
#toolbar-wrapper.readonly {
	display: none;
}
```

For the padding: https://github.com/nextcloud/server/issues/10641

**Comment by rullzer** [comment]
Missing toolbar seems to indeed be just ebcause the document was read-only ;)

Other stuff fixed in server with https://github.com/nextcloud/server/pull/10691

**Comment by schiessle** [comment]
@rullzer right, the toolbar is back if I add write permissions. But I noticed something else which again is more likely because of our layout changes:


![image](https://user-images.githubusercontent.com/1589737/44151539-2b69333c-a0a3-11e8-83c1-5352789eb483.png)

I assume that this looked nicer on Nextcloud 13 :wink:
