### ISSUE TITLE
Default templates not working - blank.ott and blank.dotx

### ISSUE THREAD

**Issue by nooblag** [nextcloud/richdocuments#2376]
Posting as a suspected bug after this discussion on forum: https://help.nextcloud.com/t/how-to-set-default-language-for-all-collabora-nextcloud-office-files/142762

**Describe the bug**
Can't overwrite `Blank` template in `Settings > Office` nor `appdata_[instanceid]/richdocuments/empty_templates/`

I am trying to change default template files so that the dictionary/language and default font we desire is set in all new documents.

We have this set in the Nextcloud config.php:

```
        "default_phone_region": "AU",
        "default_locale": "en_AU",
        "force_locale": "en_AU",
        "default_language": "en",
        "force_language": "en",
```

It works great. However, Collabora doesn’t seem to follow this, nor is the AU language even available. It always defaults to American English:

![de7aaa8c244ee1690167ee772340b8958d9a491e](https://user-images.githubusercontent.com/1122344/182637681-dfe38b7a-810e-46a0-8d18-2a202a5757ac.png)

So I tried adding a `Blank.ott` file with our desired language and font set in `Settings > Office`, which appears as a template but does not overwrite the default. "Blank" still appears, as well as our desired "Blank":

![e69ad878cb78ae61c5fff3ecc9b38fe2d53e61f9](https://user-images.githubusercontent.com/1122344/182638324-e18304ce-608b-4d3d-9edd-ebb01adf05a2.png)

After more searching, I found the [Collabora documentation](https://collabora-online-for-nextcloud.readthedocs.io/en/latest/templates/) which states to replace `document.ott` with our desired template in `appdata_[instanceid]/richdocuments/empty_templates/` but that didn’t work either unfortunately. The `Blank` template does not pick up our desired language and default font in this case either.

We are using Collabora Online - Built-in CODE Server version 22.5.401 and Nextcloud Office 6.1.1 on Nextcloud 24.0.3.

**Expected behavior**
To be able to replace `Blank` template in `Settings > Office`

## Server details

**Operating system**:
Ubuntu 20.04.4 LTS

**Web server:**
nginx/1.18.0

**Database:**
psql (PostgreSQL) 12.11

**PHP version:**
PHP 8.0.14 (cli) (built: Dec 20 2021 21:22:38)

**Nextcloud version:**
24.0.3

**Version of the richdocuments app**
Nextcloud Office 6.2.0

**Version of Collabora Online**
Collabora Online - Built-in CODE Server 22.5.502

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"vqtPs3nOafJSNdaJEhZk","level":3,"time":"2022-08-11T08:15:02+10:00","remoteAddr":"","user":"--","app":"integration_whiteboard","method":"","url":"--","message":"[ERROR] Spacedeck is unreachable, it might not be running. cURL error 7: Failed to connect to localhost port 9666: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:9666/api/spaces","userAgent":"--","version":"24.0.3.2","data":{"app":"integration_whiteboard"},"id":"62f43b11ef294"}
```
</details>

**Comment by juliushaertl** [comment]
Spell checking depends on the languages available on the system and the configured allow list in the collabora config:
https://sdk.collaboraonline.com/docs/installation/Configuration.html#allowed-dictionary-languages

For the built-in CODE server maybe @timar can tell if the app image is shipping the spell check libraries itself or picking up from the underlying system, however I fear that adding even more languages would not be very suitable as it all adds up the the growth of the appimage and richdocumentscode app. You may want to install Collabora Online from distribution packages to have more control over this https://sdk.collaboraonline.com/docs/installation/Installation_from_packages.html#spelling-dictionaries-and-thesauri

Other than that it also seems like there is no dedicated collaboraoffice-dict-* package for en_AU, but it might be that installing hunspell-en_au could help. I'd suggest to maybe reach out in the Collabora forum about this: https://forum.collaboraonline.com/top?period=quarterly

**Comment by nooblag** [comment]
Thanks for getting back. I appreciate the detailed response.

For simplicity (and other reasons at the moment that I won't bore people with), it'll be easier for me to use bundled apps with Nextcloud, and as I say in OP, we could use `en_GB` in the interim to fix the language part of our problem. But how do I configure that? Is there a conf setting?

And just to clarify then, the behaviour also described in OP, where `blank` template not working (and also the same with templates from `appdata_[instanceid]/richdocuments/empty_templates/` not working either) that's not a bug? Just wondering why it's closed as "not planned."

Thanks

**Comment by nooblag** [comment]
Hi there, just a polite ping on above.

> ... the behaviour also described in OP, where `blank` template not working (and also the same with templates from `appdata_[instanceid]/richdocuments/empty_templates/` not working either) that's not a bug? Just wondering why it's closed as "not planned."

Please confirm because both of those methods are not working.
