### ISSUE TITLE
Loss of Administration/Office settings

### ISSUE THREAD

**Issue by LsPjvVzszDt** [nextcloud/richdocuments#2387]
**Describe the bug**

After upgrade Administration/Office settings are no longer visible to edit.

Not sure if this while upgrading from 24.0.2 to 24.0.3 or 24.0.3 to 24.0.4.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Sites Settings
2. Click on Administration/Office

**Expected behavior**

![Screenshot from 2022-08-15 11-29-11](https://user-images.githubusercontent.com/30001047/184621601-23fd53be-2223-4f12-bdf3-e7c96f7a93c0.png)

**Screenshots**

![Screenshot from 2022-08-15 11-30-21](https://user-images.githubusercontent.com/30001047/184621624-12563f2b-de60-4568-ba35-ef6fce218896.png)

**Client details:**
 - Device: [e.g. iPhone6, desktop]

## Server details

Of 4 servers 2 are showing the expected config, 2 are not.

**Comment by kwaun** [comment]
Same bug here. I've got a blank Nextcloud Office configuration page.

**Comment by Raudius** [comment]
Hi, thanks for the reports.

I have not been able to reproduce on 24.0.4 with the latest richdocuments release (6.2.0).

> Of 4 servers 2 are showing the expected config, 2 are not.

What version of Nextcloud/Nextcloud Office are running on the different servers?

**Comment by LsPjvVzszDt** [comment]
They are all running Nextcloud 24.0.4 with Nextcloud Office 6.2.0

Of the 2 that no longer display the office config, 1 is a VM (Proxmox), the other is a ProLiant MicroServer Gen10

The OK servers are ProLiant MicroServer Gen10 Plus'

**Comment by Raudius** [comment]
I'll try digging a bit deeper.

Do you have any more information (maybe something on the browser console or on nextcloud.log that might help)?

> 3. See error
What exactly is the error shown?

**Comment by LsPjvVzszDt** [comment]
I have found two things:

1) That there is a dependency on which admin account logs in. I checked with a different browser (Firefox) to rule out the browser as the issue, but used a different user account from the admin group. This user was able to see the office config. I checked again using the original admin account and that had the same result as with the original browser (Brave) - as per the screenshot above. I do not see a log message written in logging when either account loads the Settings/Office page.

2) Both the non-working systems do have a php error relating to richdocuments:

[PHP] Error: Undefined index: richdocuments at /var/www/nextcloud/apps/richdocuments/lib/Preview/Office.php#50

 0. /var/www/nextcloud/apps/richdocuments/lib/Preview/Office.php line 50
    OC\Log\ErrorHandler::onError()
 1. <<closure>>
    OCA\Richdocuments\Preview\Office->__construct()
 2. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 108
    ReflectionClass->newInstanceArgs()
 3. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 116
    OC\AppFramework\Utility\SimpleContainer->buildClass()
 4. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 133
    OC\AppFramework\Utility\SimpleContainer->resolve()
 5. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 465
    OC\AppFramework\Utility\SimpleContainer->query()
 6. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 437
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
 7. /var/www/nextcloud/apps/richdocuments/lib/AppInfo/Application.php line 170
    OC\AppFramework\DependencyInjection\DIContainer->query()
 8. /var/www/nextcloud/lib/private/Preview/GeneratorHelper.php line 83
    OCA\Richdocuments\AppInfo\Application->OCA\Richdocuments\AppInfo\{closure}("*** sensitive parameters replaced ***")
 9. /var/www/nextcloud/lib/private/PreviewManager.php line 282
    OC\Preview\GeneratorHelper->getProvider()
10. /var/www/nextcloud/apps/recommendations/lib/Service/RecommendationService.php line 76
    OC\PreviewManager->isAvailable()
11. /var/www/nextcloud/apps/recommendations/lib/Service/RecommendationService.php line 96
    OCA\Recommendations\Service\RecommendationService->addPreviews()
12. /var/www/nextcloud/apps/recommendations/lib/Controller/RecommendationController.php line 70
    OCA\Recommendations\Service\RecommendationService->getRecommendations()
13. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Recommendations\Controller\RecommendationController->index()
14. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()
15. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
16. /var/www/nextcloud/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
17. /var/www/nextcloud/lib/base.php line 1023
    OC\Route\Router->match()
18. /var/www/nextcloud/index.php line 36
    OC::handleRequest()

**Comment by Raudius** [comment]
I think I have been able to reproduce the issue. Are you limiting the usage of the app by user groups? 

This can be checked with:

```
occ config:app:get richdocuments use_groups
```

If this is the case, and the admin user is not in one of these group, then you will get the issue. I will look into fixing this behaviour in a future patch. But as a current workaround you can make sure the administrator group has access to the app via:

```
occ config:app:set richdocuments use_groups --value "group1|group2|group3|admin"
```

**Comment by LsPjvVzszDt** [comment]
Yes. It is a permissions issue. The admin account did not previously need to be in the group used to control user access,  when in settings.

Resolved by adding the user to said group.

Thank you for your time.
