### ISSUE TITLE
document name overlaps dropdown bar (in presentations)

### ISSUE THREAD

**Issue by Jannik44** [nextcloud/richdocuments#2388]
When i use it it cant click the dropdowns because the document name overlaps it, when i resize my browser windows to the wisth where the document name dissapears i can click them but its annoying to make my screen smaller just to add a new Slide

## Server details

**Linux**:
**apache2**
**mysql**
**php 8**
**Nextcloud version 24**
**Version of the richdocuments app: latest**
**Version of Collabora Online: latest**

**Comment by Raudius** [comment]
Closing this issue because it overlaps with 

https://github.com/nextcloud/richdocuments/issues/2429

Can you confirm whether you have a language different than English set on your instance?
