### ISSUE TITLE
Content Security Policy block

### ISSUE THREAD

**Issue by Tealk** [nextcloud/richdocuments#2389]
**Describe the bug**
Since the update to collaboraoffice 22.05.5-3 I cannot edit any documents.
The update initially also ran on error: https://forum.collaboraonline.com/t/apt-returns-forbidden-ip-46-235-227-219-443-on-code-install/1299/2?u=tealk

**To Reproduce**
1. Open a text document
2. long wait at "Loading test.docx ..."
3. then the message appears "Document loading failed Failed to load Nextcloud Office - please try again later"

**Expected behavior**
The document opens and can be edited

**Screenshots**
New is also that when I want to save the domain again the following message comes:
![image](https://user-images.githubusercontent.com/12276250/184830814-49e202cf-7665-42a4-9029-3cfb7421b0bd.png)

**Client details:**
 - OS: Linux
 - Browser Firefox
 - Version 103.0.2
 - Device: Laptop

## Server details

**Operating system**: Debian 11

**Web server:** nginx

**Database:** Mariadb

**PHP version:** 8.1

**Nextcloud version:** 24.0.4

**Version of the richdocuments app** 6.2.0

**Version of Collabora Online** 22.05.5-3

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
No Warning or Error
```

#### Browser log
```
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Uncaught 
Exception { name: "", message: "", result: 2153381986, filename: "https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49", lineNumber: 2, columnNumber: 0, data: null, stack: "trigger@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5866139\n19755/</trigger/<@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5866425\neach@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5796894\neach@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5795374\ntrigger@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5866400\n49226/a</Y</<@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5510450\n49226/a</s/e[n]@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5501466\nshowEditor@https://rollenspiel.cloud/apps/richdocuments/js/richdocuments-document.js?v=68b090fa-49:2:238810\nshowEditor/<@https://rollenspiel.cloud/apps/richdocuments/js/richdocuments-document.js?v=68b090fa-49:2:233998\nsetTimeout handler*showEditor@https://rollenspiel.cloud/apps/richdocuments/js/richdocuments-document.js?v=68b090fa-49:2:233980\nloadDocument@https://rollenspiel.cloud/apps/richdocuments/js/richdocuments-document.js?v=68b090fa-49:2:239778\ninitSession/<@https://rollenspiel.cloud/apps/richdocuments/js/richdocuments-document.js?v=68b090fa-49:2:239708\nl@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5822535\nadd@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5822815\ninitSession@https://rollenspiel.cloud/apps/richdocuments/js/richdocuments-document.js?v=68b090fa-49:2:239689\n@https://rollenspiel.cloud/apps/richdocuments/js/richdocuments-document.js?v=68b090fa-49:2:240803\nc@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5824253\n19755/</Deferred/then/o/</u<@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5824555\nsetTimeout handler*19755/</Deferred/then/o/<@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5824764\nl@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5822535\nfireWith@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5823283\nfire@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5823319\nl@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5822535\nfireWith@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5823283\nready@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5826269\nsetTimeout handler*19755/<@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5826395\n19755/<@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5794004\n19755@https://rollenspiel.cloud/dist/core-common.js?v=68b090fa-49:2:5794117\na@https://rollenspiel.cloud/dist/core-main.js?v=68b090fa-49:2:135809\n13084@https://rollenspiel.cloud/dist/core-main.js?v=68b090fa-49:2:1348\na@https://rollenspiel.cloud/dist/core-main.js?v=68b090fa-49:2:135809\nr<@https://rollenspiel.cloud/dist/core-main.js?v=68b090fa-49:2:137528\na.O@https://rollenspiel.cloud/dist/core-main.js?v=68b090fa-49:2:136211\n@https://rollenspiel.cloud/dist/core-main.js?v=68b090fa-49:2:137544\n@https://rollenspiel.cloud/dist/core-main.js?v=68b090fa-49:2:137549\n" }
core-common.js:2
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
Content Security Policy: The page’s settings blocked the loading of a resource at http://office.rollenspiel.cloud/browser/bacb4ed/cool.html?WOPISrc=https%3A%2F%2Frollenspiel.cloud%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F23699791_ocohsr9ftdgy&title=test.docx&lang=en&closebutton=1&revisionhistory=1 (“form-action”). jquery.js:8725:4
PostMessageService.sendPostMessage loolframe {"MessageId":"Host_PostmessageReady","SendTime":1660638674093,"Values":{}} postMessage.tsx:57:10
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
```

</details>

content-security-policy
`default-src 'none';base-uri 'none';manifest-src 'self';script-src 'nonce-QWg0c2cvR1cxWFpoMzFmSHhqdzlLWHhmRU9uR1NVM2VtMFkzY0RHM2NRcz06YjFSRnNjZWprd0l1OUFTQmtuSnBFUnNsU0pPV0tpR0U2aUFQS25md1BHRT0=' blob:;style-src 'self' 'unsafe-inline';img-src 'self' data: blob: * https://office.rollenspiel.cloud https://*.tile.openstreetmap.org;font-src 'self' data:;connect-src 'self' https://nominatim.openstreetmap.org/ blob: stun.nextcloud.com:443 meet.rollenspiel.monster;media-src 'self' blob:;frame-src https://www.openstreetmap.org/ prezi.com player.vimeo.com vine.co www.youtube.com 'self' https://office.rollenspiel.cloud;child-src blob: 'self';frame-ancestors 'self' https://office.rollenspiel.cloud;worker-src 'self' blob:;form-action 'self' https://office.rollenspiel.cloud`

**Comment by juliushaertl** [comment]
Your Collabora server is likely advertising itself to be serving without SSL, please check https://sdk.collaboraonline.com/docs/installation/Configuration.html?highlight=termination#ssl-configuration in that regards especially if the ssl > termination option is set if you use a reverse proxy to terminate the SSL connection.

**Comment by Tealk** [comment]
Thank you, I have probably overlooked after the update

**Comment by joho1968** [comment]
> Thank you, I have probably overlooked after the update

Did you get this working? I'm running into a similar problem, having Collabora on one sub.domain.com and Nextcloud on another sub2.domain.com, and I constantly see the CSP (form-action) message in the console logs. Though I have included both domains (https://sub.domain.com/*, etc) in the CSP (nginx) on both servers.

**Comment by Tealk** [comment]
I have the whole thing running on different servers with a virtual network, there were only a few settings missing as far as I can remember back.

**Comment by joho1968** [comment]
> I have the whole thing running on different servers with a virtual network, there were only a few settings missing as far as I can remember back.

OK, thanks. Well, I have "edit.domain.com" (Collabora Online) and "docs.domain.com" (Nextcloud), and I cannot for the life of me seem to figure out why I'm getting CSP violation messages in the console, both of them are in "form-action" and "frame-ancestors".

**Comment by Tealk** [comment]
have you read through the instructions linked above and checked the ssl?

**Comment by joho1968** [comment]
#2621

(and https://help.nextcloud.com/t/collabora-and-nextcloud-25/149981)
