### ISSUE TITLE
"Restrict usage to specific groups" does not work properly (Buggy choices remain when clicking on [+])

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/richdocuments#2397]
**Describe the bug**
When you activate the "Restrict usage to specific groups" setting to allow only certain user groups to use Collabora Online / Nextcloud Office, the user group(s) concerned cannot effectively use the office suite anymore. However, in Nextcloud Files, when you click on the [+] button, you still have the Collabora Online / Nextcloud Office document creation options. By clicking on it, we can see that : 
- it is not possible to create a file (Collabora does not open)
- that the choices no longer have a blue, green, orange icon...
So I think it's a bug; assuming I understood the purpose of the "Restrict usage to specific groups" setting, these choices should no longer be available when clicking on the [+] button.

**To Reproduce**
1. Enable "Restrict usage to specific groups" (and select a user group)
2. Log as a user belonging to the declared group
3. Notice the described problem

**Expected behavior**
"New document", "New spreadsheet" and "New presentation" shouldn't appear.

**Screenshots**
Settings : 
![2022-08-22_13-34](https://user-images.githubusercontent.com/33763786/185912018-7d1033d4-5517-4158-a36d-9739f0272714.png)
What you get after in the [+] button : 
![2022-08-22_13-33](https://user-images.githubusercontent.com/33763786/185912051-6304f846-ada0-4ce9-99ad-5d1a9b08bd1c.png)
What you get after trying to create a Collabora document : 
![2022-08-22_13-36](https://user-images.githubusercontent.com/33763786/185912122-99f777d5-8d89-480a-a458-b3d6eaf9c4ab.png)
What you only should have : 
![2022-08-22_13-38](https://user-images.githubusercontent.com/33763786/185912546-edf902c7-736b-4827-93ea-1432677882ba.png)

**Client details:**
 - OS: Ubuntu 20.04 LTS
 - Browser : Firefox 103
 - Device: Laptop

## Server details

**Operating system**: Ubuntu 20.04 LTS

**Web server:**Apache

**Database:** MySQL

**PHP version:** 8.0.22

**Nextcloud version:** 20.0.4

**Version of the richdocuments app** 
COOLWSD / Collabora Office 22.05.5.2
Nextcloud Office 6.2.0

**Version of Collabora Online**
Collabora Online - Built-in CODE Server 22.5.502

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Can be provided if necessary
```

#### Browser log
```
Can be provided if necessary
```

</details>

**Comment by juliushaertl** [comment]
I have a fix from #2374
