### ISSUE TITLE
Add occ-command to set URL in Collabora App settings

### ISSUE THREAD

**Issue by enoch85** [nextcloud/richdocuments#24]
I have just [scripted the Collabora install](https://github.com/nextcloud/vm/blob/master/static/collabora.sh), and the only missing piece to make it perfect is to add the URL in Collabora App settings.

Would be great if someone could add a occ command for it.

Ref: https://github.com/nextcloud/server/issues/3377

**Comment by nickvergessen** [comment]
As mentioned in the server you should simply check it first:
https://github.com/nextcloud/richdocuments/blob/master/lib/Controller/SettingsController.php#L58

So the following should work
`./occ config:app:set richdocuments wopi_url --value="https://localhost/"`

**Comment by enoch85** [comment]
Thanks @nickvergessen Didn't check tbh.

**Comment by robjuffermans** [comment]
This sets the url indeed, but I have to manualy click on the save button in the collabora settings to get the green light so collabora can be used. Is there solution for this?
