### ISSUE TITLE
fix RichDocuments 

### ISSUE THREAD

**Issue by Alerinos** [nextcloud/richdocuments#2416]
https://github.com/nextcloud/richdocuments/issues/1282

All day I was looking for a solution to the problem, I tried to install Collabora Online on my server. Everything went well, but unfortunately I could not start the interface and connect to the nextcloud. After many unsuccessful attempts, I found that it will use the built-in CODE. Suddenly it worked magically and no problem, I think you need to manually install the service on the server and then install the plugin. The guide from which I installed:
https://www.linuxbabe.com/ubuntu/integrate-collabora-onlinenextcloud-without-docker

The only thing I haven't done here is generate the certificate, I'm using CF so I don't need it.
Take a look if my theory actually works.

**Comment by Alerinos** [comment]
Anyway, is this config correct?
Unfortunately, it returned me 504.
I also tried ``https://localhost::9980``
It didn't work either ...
```
server {
	listen 443      ssl;
	listen [::]:443 ssl;
	server_name  collaboraonline.*.com;

	error_log /var/log/nginx/collabora.error;

	ssl_certificate     /etc/ssl/cloud.pem;
	ssl_certificate_key /etc/ssl/cloud.key;


 # static files
 location ^~ /browser {
   proxy_pass http://localhost:9980;
   proxy_set_header Host $http_host;
 }


 # WOPI discovery URL
 location ^~ /hosting/discovery {
   proxy_pass http://localhost:9980;
   proxy_set_header Host $http_host;
 }


 # Capabilities
 location ^~ /hosting/capabilities {
   proxy_pass http://localhost:9980;
   proxy_set_header Host $http_host;
 }


 # main websocket
 location ~ ^/cool/(.*)/ws$ {
   proxy_pass http://localhost:9980;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection "Upgrade";
   proxy_set_header Host $http_host;
   proxy_read_timeout 36000s;
 }


 # download, presentation and image upload
 location ~ ^/(c|l)ool {
   proxy_pass http://localhost:9980;
   proxy_set_header Host $http_host;
 }


 # Admin Console websocket
 location ^~ /cool/adminws {
   proxy_pass http://localhost:9980;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection "Upgrade";
   proxy_set_header Host $http_host;
   proxy_read_timeout 36000s;
 }
}
```

![image](https://user-images.githubusercontent.com/42449535/187289078-03fe9ac4-16d6-421f-b4ef-cdc799e24320.png)

**Comment by Raudius** [comment]
Hi thanks for the report. 

Github is not the ideal place to track configuration issues. I am in the process of cleaning up the repository to keep only the relevant issues (bugs, security issues and feature requests).

Here you can find some resources which should allow you to fix your issue:
 * [Installation guide](https://collabora-online-for-nextcloud.readthedocs.io/en/latest/install/)
 * [Collabora proxy configs (scroll down for NGINX)](https://sdk.collaboraonline.com/docs/installation/Proxy_settings.html)
 * [Nextcloud support forum for questions](https://help.nextcloud.com/c/support/)

**Comment by lfom** [comment]
@Raudius Actually it is not a configuration problem, please see #1486.
