### ISSUE TITLE
Richdocuments plugin slowing nextcloud to close to complete halt

### ISSUE THREAD

**Issue by tildezero** [nextcloud/richdocuments#2431]
**Describe the bug**
The second I install the richdocuments plugin, either via `occ` or the app menu, my nextcloud is unusable, everything is stuck at less than 1/4 loading until i disable the plugin via occ

**To Reproduce**
1. Install CODE via `occ`
2. Install Collabora plugin on app store
3. Click on anything
4. it won't load

**Expected behavior**
The app should work as normal, and documents load properly

**Client details:**
 - OS: MacOS
 - Browser: Safari, tested on Chromium, FF, Chrome
 - Device: Laptop

## Server details

**Operating system**: Ubuntu 20.04

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud version:** 24.0.5

**Version of the richdocuments app** Latest on app store

**Version of Collabora Online** 22.5.502	

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
https://ttm.sh/qLJ.log

</details>

**Comment by AJMitev** [comment]
Did you manage to resolve this issue? I have the same problem.

**Comment by tildezero** [comment]
i reinstalled the plugin manually (wget the tar.gz from releases, untar in NEXTCLOUD_DIR/apps/richdocuments and refresh nextcloud

**Comment by AJMitev** [comment]
It didn't worked for me :(
