### ISSUE TITLE
What is v6.2.0? It is not listed in Releases

### ISSUE THREAD

**Issue by OneAceGuy** [nextcloud/richdocuments#2469]
I updated Nextcloud Office to version 6.2.0 from within Admin pages, and then Nextcloud Office stopped working. Documents would not open, I could not create new documents, and the Collabora configuration page did not display configuration settings (i.e., 'Nextcloud Office' section or 'Advanced settings' section). The only section of the page that displayed was 'Global templates'. 

Here is a screenshot of what I see on Apps page (after disabling and uninstalling the module): 

![image](https://user-images.githubusercontent.com/69665596/193094884-5f2570c6-4b23-45a8-9335-bbd63f61d9b6.png)

I do not see version 6.2.0 available here in Releases. What did I download and install?

**Expected behavior**
Update to the latest version of Nextcloud Office without breaking Collabora/Nextcloud integration.

To resolve this issue, I reverted to v6.1.1 of the module. 

## Server details
**Operating system**: Debian 11 (Linux v5.10.0-14)
**Web server:** Apache 
**Database:** MariaDB
**PHP version:** 7.4
**Nextcloud version:** 24.0.5
**Version of the richdocuments app** 6.1.1
**Version of Collabora Online** 22.05.6.3-1

**Comment by Raudius** [comment]
Hi,

It appears we forgot to create the 6.2.0 release on this repo but you can see the tag: 
https://github.com/nextcloud/richdocuments/releases/tag/v6.2.0

What issue exactly were you experiencing with 6.2.0?

**Comment by OneAceGuy** [comment]
I just did the upgrade again, looks like things are sort-of working now.  
After upgrading to 6.2.0 I tested opening a Word document, but got the following error in the browser:  

![image](https://user-images.githubusercontent.com/69665596/193101487-cbd2d99d-791e-4eb8-9c8f-091765f4457c.png)

Miraculously, after about 10 seconds, the document suddenly opened. I did not refresh the browser. 

I have numerous errors in the logs, here is one of the entries: 
```
[PHP] Error: Error: copy(/var/www/nextcloud/apps/richdocuments/richdocuments/tsconfig.json): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#155 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError()
 1. /var/www/nextcloud/lib/private/legacy/OC_Helper.php line 155
    copy()
 2. /var/www/nextcloud/lib/private/legacy/OC_Helper.php line 151
    OC_Helper::copyr()
 3. /var/www/nextcloud/lib/private/legacy/OC_Helper.php line 151
    OC_Helper::copyr()
 4. /var/www/nextcloud/lib/private/Installer.php line 374
    OC_Helper::copyr()
 5. /var/www/nextcloud/lib/private/Installer.php line 194
    OC\Installer->downloadApp()
 6. /var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php line 535
    OC\Installer->updateAppstoreApp("*** sensitive parameters replaced ***")
 7. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Settings\Controller\AppSettingsController->updateApp("*** sensitive parameters replaced ***")
 8. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()
 9. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
10. /var/www/nextcloud/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
11. /var/www/nextcloud/lib/base.php line 1030
    OC\Route\Router->match()
12. /var/www/nextcloud/index.php line 36
    OC::handleRequest()

GET /settings/apps/update/richdocuments
from ##.##.##.## by admin at 2022-09-29T17:14:22+00:00
```
Notice the path to file is `/var/www/nextcloud/apps/richdocuments/richdocuments`. I have several errors like this, but I guess whatever variable that was repeating the directory name `richdocuments/richdocuments/` fixed itself because there are no more errors and documents are opening as expected now.  

I will look into this more later and share if I find what happened, but for now, Collabora seems to be functioning. Thanks.

**Comment by OneAceGuy** [comment]
Looks like this was a local environment issue, closing ticket. Thanks.
