### ISSUE TITLE
Shared editable docs: no guest access to chat

### ISSUE THREAD

**Issue by rriemann** [nextcloud/richdocuments#2489]
**Describe the bug**
I have installed Nextcloud Hub 3 25.0.0 RC3 and the latest version of COOL.

Guests receiving an invite to edit a document cannot access the document chat.

**To Reproduce**
1. go to an odt document and create share link with editing enabled
2. open another browser and open the link.
3. wait until the document is fully loaded
4. click on the burger menu to open the sidebar to the right
5. see that nothing happens. console delivers an error message (otherwise silent fail)

**Expected behavior**
Guests can see also the chat. If there is no agreement if this is a good idea, please make it configurable when sharing (editable, chattable, etc)

**Screenshots**

![Screenshot_20221007_120812](https://user-images.githubusercontent.com/111932/194530349-88c79f83-e5fa-47ef-a567-ecb628d601f0.png)

**Client details:**
 - OS: Linux
 - Browser Firefox 104.0.2 64bit
 - Device: desktop

## Server details

**Operating system**:

 - Nextcloud version Hub 3 25.0.0.0 RC3

**Version of the richdocuments app**

 7.0.0-beta.2

**Version of Collabora Online** 

Collabora Office 22.05.6.3 git hash: 
[4fad249](javascript:void(window.open('https://hub.libreoffice.org/git-core/4fad249'));)
Served by: Ubuntu 18.04.6 LTS 

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
richdocuments part of the fix is in https://github.com/nextcloud/richdocuments/pull/2503 

branding change in progress

**Comment by malinkb** [comment]
I have the same issue with Nextcloud 26

**Comment by joshtrichards** [comment]
So the bug is fixed where it was being offered on public shares even it wasn't really loadable (#2503).
But it seems the remaining part of this Issue is an enhancement request to support a "chattable" mode for guests.
@juliushaertl What's your branding comment about? Is adding chatting dependent the sidebar integration?

**Comment by juliushaertl** [comment]
There is no option to chat within the document itself but Nextcloud Talk offers a file chat function. Having per file permissions for that sounds an edge case feature to me but is probably something to be filed separately in talk.
