### ISSUE TITLE
Can't c/p text in doc to WordPress draft [Bug]: "Stub HTML Message Copying from the document disabled"

### ISSUE THREAD

**Issue by schne137** [nextcloud/richdocuments#2534]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud 25
Working on PC with Microsoft Edge
On a Nextcloud document I am copying text to a draft on Wordpress, however when I try to c/p there is an error message: "Stub HTML Message Copying from the document disabled"
Thanks!

![image](https://user-images.githubusercontent.com/98105430/192486264-67921c79-d2ff-4d10-94d1-2ae3921048dc.png)

### Steps to reproduce

1. Copy / paste any text in a Nextcloud document
2. C / p in a WordPress draft (post)
3. You will see the error 

### Expected behavior

I expected my c/p to work as normal.

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
cloud.nc.com / not sure
```

### Additional info

Using Microsoft Edge on PC (don't have other browsers)

**Comment by joshtrichards** [comment]
Probably fixed by #2511.

Can you confirm this behavior is gone for you, @schne137, since you're the original reporter?

**Comment by schne137** [comment]
Hi, yes this is resolved now. Thanks to everyone involved.
