### ISSUE TITLE
custom logo is not shown

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/richdocuments#2538]
![grafik](https://user-images.githubusercontent.com/24530680/196637816-cdaeef6b-3121-4c45-a0c2-127d55abb1a3.png)
If it was set here:
![grafik](https://user-images.githubusercontent.com/24530680/196637910-b35f210f-eab6-441a-a593-f0900aa772ae.png)

**Comment by juliushaertl** [comment]
We fixed that quite some time ago, so maybe double check that you are using the latest CODE release. Closing as I cannot reproduce but if it is still an issue, please provide the exact versions in use for richdocuments and Collabora. :)

**Comment by jimbojim** [comment]
I have tried a PNG and SVG logo with the same results.
