### ISSUE TITLE
Preview is not watermarked on hide download links

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/richdocuments#2561]
**Describe the bug**
The secure watermarked view announced for Nextcloud 25 / Hub 3 can be hacked. See reproduction steps below.

**To Reproduce**
1. Go to Nextcloud Office Admin Settings and set the watermark options to have a custom watermark in read-only shares, without a download button.
2. For example, create a read-only public share link without a download button.
3. Go to the created public URL and see that there is as expected a watermark on the read-only document and no download button. For now, everything is OK.
4. Then notice that there is the close document cross at the top right. IMO, this cross should not exist because when you click on it, the document reappears behind, without the watermark. Even though the document appears smaller, I think this is risky and goes against the privacy purpose of this feature shown in Berlin.

**Expected behavior**
The close button should not appear at the top right in order to keep the recipient of the share captive in this view of the document. I go further in my explanation by saying that if the share is a single file share and not a folder share, the close button should never appear, because the share recipient is not supposed to access an upstream folder, but just be able to view the file (and edit it if he has write permission), nothing else.

**Screenshots**
Here is the closing button : 
![2022-10-21_14-29](https://user-images.githubusercontent.com/33763786/197195931-1e55f569-de6c-4527-be30-6e584a847468.png)
Here is what we get after clicking on it : 
![2022-10-21_14-39](https://user-images.githubusercontent.com/33763786/197197843-fb0eba78-17f7-4b71-8eca-0254b0e80af1.png)

**Client details:**
 - OS: Ubuntu 20.04 LTS
 - Browser : Tester and Firefox 106 and Chromium 106
 - Device: Laptop

## Server details

**Operating system**: Linux 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64

**Web server:** nginx/1.23.2 (fpm-fcgi)

**Database:** mysql 10.4.22

**PHP version:** 8.0.19

**Nextcloud version:** 25.0.0 - 25.0.0.18

**Nextcloud Office app** 7.0.0

![Capture d’écran de 2022-10-21 14-35-05](https://user-images.githubusercontent.com/33763786/197197150-f81316ed-38af-4d5d-981a-aa50dc42a2f5.png)

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Can be provided if necessary
```

</details>

**Comment by juliushaertl** [comment]
This has been addressed with 
- https://github.com/nextcloud/server/pull/34799
- https://github.com/nextcloud/richdocuments/pull/2579

Thanks for reporting again @Jerome-Herbinet 

In the future if there is anything security related please make sure to report that according to https://github.com/nextcloud/server/security/policy
