### ISSUE TITLE
Allow specifying the timeout period for the connection to the CODE server

### ISSUE THREAD

**Issue by tanty** [nextcloud/richdocuments#2569]
This is related to #2566 

As described there, the CODE server container instance is only running when needed. This means that, when invoked, there is some time needed before the instance is up and running. Sometimes, my very constrained server takes longer than the timeout period and an error is offered from the NextCloud application. It would be great if the timeout period for the connection to the CODE server could be tuned so we could set a longer period when we know that the server is slow, for example.

**Comment by joshtrichards** [comment]
I just discovered that per #1237 we already support configuring the timeout. If defaults otherwise to 15s.
