### ISSUE TITLE
Copying internal link from share sidebar doesn't work with CODE opened

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/richdocuments#2578]
**Describe the bug**
Copying internal link from share sidebar doesn't work with CODE opened, even though it works properly in files. I'm guessing CODE conflicts with that somehow.

**To Reproduce**
1. Open a file in CODE
2. Open the NC sidebar
3. Select the Sharing tab
4. Try to copy the internal link

**Expected behavior**
The internal link is copied to the clipboard, just like in files

**Client details:**
 - OS: [e.g. iOS] Ubuntu/Fedora
 - Browser [e.g. chrome, safari] Firefox 106 and 108, Chrome 108
 - Device: [e.g. iPhone6, desktop] desktop

## Server details

**Operating system**: Debian

**Web server:** nginx

**Database:** PostgreSQL

**PHP version:** 7.4

**Nextcloud version:** 25.0.0

**Version of the richdocuments app** 7.0.0

**Version of Collabora Online** 22.05.7.2

<details>
<summary>Logs</summary>

#### Browser log
Unfortunately, nothing relevant.

</details>

**Comment by juliushaertl** [comment]
Maybe a server issue if this also happens with images?

**Comment by tcitworld** [comment]
Oh, you meant the preview app? That's right, it doesn't work either!

**Comment by maximelehericy** [comment]
I can reproduce :)

**Comment by nuokh** [comment]
I encountered this bug on 25.0.2 today, too. All apps are up2date.

**Comment by juliushaertl** [comment]
Should be fixed by https://github.com/nextcloud/server/pull/36450
