### ISSUE TITLE
GuzzleHttp 404 Not Found Response Client error

### ISSUE THREAD

**Issue by JohnFarl** [nextcloud/richdocuments#2583]
I use Nexcloud 25 configured on Debian Bullseye with Apache/PHP/MariaDb server, 
I have installed `richdocument` and `richdocumentcode_arm64` today, everything updated to latest version available 
- Nextcloud Office 7.0.0
- Collabora Online - Built-in CODE Server (ARM64)	22.5.702

It seemed to work (documents are opened and saved) but unfortunately something isn't going properly and this caused an explosion of log file size due to this continuous error repeated indefinitely:

```
GuzzleHttp\Exception\ClientException: Client error: `GET http://localhost/nextcloud/apps/richdocumentscode_arm64/proxy.php?req=/hosting/capabilities` resulted in a `404 Not Found` response: <!DOCTYPE html> <html lang="it-IT" class="ut-no-js"> <head> <meta charset="UTF-8"> <meta name="viewport" content="widt (truncated...)
/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php - line 69:

GuzzleHttp\Exception\RequestException::create()

/var/www/html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 204:

GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")

/var/www/html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 153:

GuzzleHttp\Promise\Promise::callHandler()

/var/www/html/nextcloud/3rdparty/guzzlehttp/promises/src/TaskQueue.php - line 48:

GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}("*** sensiti ... *")

/var/www/html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 248:

GuzzleHttp\Promise\TaskQueue->run()

/var/www/html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 224:

GuzzleHttp\Promise\Promise->invokeWaitFn()

/var/www/html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 269:

GuzzleHttp\Promise\Promise->waitIfPending()

/var/www/html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 226:

GuzzleHttp\Promise\Promise->invokeWaitList()

/var/www/html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 62:

GuzzleHttp\Promise\Promise->waitIfPending()

/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 187:

GuzzleHttp\Promise\Promise->wait()

/var/www/html/nextcloud/lib/private/Http/Client/Client.php - line 218:

GuzzleHttp\Client->request()

/var/www/html/nextcloud/apps/richdocuments/lib/Service/CapabilitiesService.php - line 131:

OC\Http\Client\Client->get()

/var/www/html/nextcloud/apps/richdocuments/lib/AppInfo/Application.php - line 203:

OCA\Richdocuments\Service\CapabilitiesService->refetch()

/var/www/html/nextcloud/apps/richdocuments/lib/AppInfo/Application.php - line 135:

OCA\Richdocuments\AppInfo\Application->checkAndEnableCODEServer()

/var/www/html/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php - line 190:

OCA\Richdocuments\AppInfo\Application->boot()

/var/www/html/nextcloud/lib/private/legacy/OC_App.php - line 208:

OC\AppFramework\Bootstrap\Coordinator->bootApp()

/var/www/html/nextcloud/lib/private/legacy/OC_App.php - line 141:

OC_App::loadApp()

/var/www/html/nextcloud/cron.php - line 55:

OC_App::loadApps()
```

**Comment by juliushaertl** [comment]
This looks like a configuration problem where your webserver is not properly passing the requests to proxy.php to the actual file.

> GuzzleHttp\Exception\ClientException: Client error: `GET http://localhost/nextcloud/apps/richdocumentscode_arm64/proxy.php?req=/hosting/capabilities` resulted in a `404 Not Found` response: <!DOCTYPE html> <html lang="it-IT" class="ut-no-js"> <head> <meta charset="UTF-8"> <meta name="viewport" content="widt (truncated...)

If you are using apache, make sure that your .htaccess is applied properly if you use nginx you may want to check your config against https://www.collaboraoffice.com/online/connecting-collabora-online-built-in-code-server-with-nginx/

Fur further assistance in regards to the setup please check back on the forums at help.nextcloud.com

**Comment by JohnFarl** [comment]
@juliushaertl This is strange. I have htaccess override enabled for whole Nextcloud path and already followed official documentation for the host configuration also my Nextcloud setup hasn't shown any problem with any other app (and is everything marked as green also in the "Nextclout checkup"). The link you have posted seems a Nginx specific issue but I don't use Nginx.

**Comment by juliushaertl** [comment]
That should usually be added when Nextcloud sets the htaccess:

https://github.com/nextcloud/server/blob/914df4e228900bd6a0aae81110951c9852b8eeb7/lib/private/Setup.php#L536
