### ISSUE TITLE
Nextcloud 25 : The Nextcloud Office settings page disappears after clicking on some checkboxes (see video)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/richdocuments#2584]
**Describe the bug**
The settings page disappears after clicking on some checkboxes (see video)

**To Reproduce**

https://user-images.githubusercontent.com/33763786/197995189-4dc7fefc-3079-4f2d-ba1c-9f8146b13096.mp4

**Expected behavior**
It shouldn't disappear.

**Client details:**
 - OS: Ubuntu 20.04 LTS
 - Browser : Firefox 106
 - Device: Laptop

**Server details**

Operating system: Linux 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64

Webserver: nginx/1.23.2 (fpm-fcgi)

Database: mysql 10.4.22

PHP version: 8.0.19

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, xmlreader, xmlrpc, zip, apcu, imagick, msgpack, smbclient, igbinary, memcached, redis, libsmbclient, Zend OPcache

Nextcloud version: 25.0.0 - 25.0.0.18
Version COOLWSD : 22.05.6.3 
Versison LOKit : Collabora Office 22.05.6.3
richdocuments: 7.0.0

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Can be provided if necessary
```

#### Browser log
```
Can be provided if necessary
```

</details>

**Comment by juliushaertl** [comment]
Could you check the browser console for errors and paste them here if there are any?

**Comment by Raudius** [comment]
I managed to reproduce it (FF 104.0.2), no console errors.

But strangely, resetting (unticking and ticking in the DOM inspector) the height property of `#content` seems to fix it.

**Comment by juliushaertl** [comment]
Interesting, clicking the checkbox seems to trigger a scroll on `#content` while it should be on `#app-content` with the new design in 25.

**Comment by juliushaertl** [comment]
![Screenshot 2022-10-27 at 12 59 50](https://user-images.githubusercontent.com/3404133/198267395-e2f7494f-3bf6-407a-8eb6-8e938b29821c.png)

**Comment by Jerome-Herbinet** [comment]
@juliushaertl no error in my browser console.

**Comment by juliushaertl** [comment]
I've pushed a fix to https://github.com/nextcloud/server/pull/37417 Testing is welcome :)
