### ISSUE TITLE
Hide close button on single file shares that have hide download enabled

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#2585]
Only thing I noticed is that you close a read-only watermarked file, you get a pretty bare view. 

<details>
<summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/3178979/198075564-14448299-a7a1-45b7-bee0-e62849420b04.png)

</details>

Might be something to look into with the design team after this PR is merged :)

_Originally posted by @Raudius in https://github.com/nextcloud/richdocuments/pull/2579#pullrequestreview-1156838022_

**Comment by ananyak19** [comment]
Hey, can i work on this issue?

**Comment by ananyak19** [comment]
Hey, I want to work on this.. can you give some more insight about what exactly needs to be done.
