### ISSUE TITLE
App nextcloud office doesn't work on docker image nextcloud:stable-fpm-alpine

### ISSUE THREAD

**Issue by LeoMeinel** [nextcloud/richdocuments#2602]
**Describe the bug**
When trying to open existing or creating new documents I get an infinite loading screen. I am using docker.
The images are:
- nginx:stable-alpine (reverse proxy with ssl)
- nginx:stable-alpine (web server)
- nextcloud:stable-fpm-alpine (nextcloud app)
- yobasystems/alpine-mariadb (database)

This setup works pretty well so far, the only real issue I have is with the Nextcloud Office app and the built-in CODE server. 

**To Reproduce**
1. Install my setup as mentioned above
2. Install apps: "Collabora Online - Built-in CODE Server" and "Nextcloud Office"
3. See in .../settings/admin/richdocuments that "Collabora Online server is reachable."
4. Try to load or create document
5. See an infinite loading screen

**Expected behavior**
Nextcloud office loading the document and office suite.

**Client details:**
 - OS: Arch Linux
 - Browser: Firefox, Chrome, Waterfox, Bromite
 - Device: Desktop, Android

## Server details

**Operating system**: Fedora Linux 36

**Web server:** nginx:stable-alpine (Docker) 1.22.1

**Database:** yobasystems/alpine-mariadb (Docker) 10.6.10

**PHP version:** 8.0.25

**Nextcloud version:** nextcloud:stable-fpm-alpine (Docker)  24.0.7.1

**Version of the richdocuments app:** 6.3.1

**Version of Collabora Online:** 22.5.702

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
not relevant
```

#### Browser log
```
not relevant
```

#### Webserver log
```
2022/11/06 22:57:43 [error] 24#24: *97 FastCGI sent in stderr: "PHP message: richdocumentscode (proxy.php) error exit, PID: 24, Message: no_glibc" while reading upstream, client: 10.2.0.x, server: foo, request: "POST /custom_apps/richdocumentscode/proxy.php?req=/lool/convert-to/png HTTP/1.1", upstream: "fastcgi://10.2.0.y:bar", host: "foo"
2022/11/06 22:57:43 [error] 24#24: *101 FastCGI sent in stderr: "PHP message: richdocumentscode (proxy.php) error exit, PID: 21, Message: no_glibc" while reading upstream, client: 10.2.0.x, server: foo, request: "POST /custom_apps/richdocumentscode/proxy.php?req=/lool/convert-to/png HTTP/1.1", upstream: "fastcgi://10.2.0.y:bar", host: "foo"
```

</details>

**My conclusion:** Either Nextcloud office or CODE require glibc which is not supported by nextcloud:stable-fpm-alpine. I don't know if this is known/intended but I wanted to make you at least aware and would kind of want to ask for a fix.

Fixing it should be possible by not having either of those binaries linked to glibc!

**Comment by LeoMeinel** [comment]
[This](https://www.collaboraoffice.com/online/connecting-collabora-online-built-in-code-server-with-nginx/) seems to be related. AppImages might be the problem here.

**Comment by LeoMeinel** [comment]
I will leave this open for now, feel free to close it if you think that it is not relevant to your software because of the linked issues.
However I'm not sure if this is actually the cause of the issue.

**Comment by LeoMeinel** [comment]
A solution might also be [setting up CODE in another docker container](https://sdk.collaboraonline.com/docs/installation/CODE_Docker_image.html)

**Comment by joshtrichards** [comment]
The *Collabora Online - Built-in CODE Server* is a separate app. This app (here) works both with the Built-in edition as well as in the independent - i.e. own Docker container - edition. The repository relevant to your Issue is this one:

https://github.com/CollaboraOnline/richdocumentscode

And its system requirements state it requires glibc (alpine is musl based):

https://github.com/CollaboraOnline/richdocumentscode#system-requirements

If you want to advocate for an enhancement, check/open an issue here: https://github.com/CollaboraOnline/richdocumentscode

**Comment by leomeinel** [comment]
> The _Collabora Online - Built-in CODE Server_ is a separate app. This app (here) works both with the Built-in edition as well as in the independent - i.e. own Docker container - edition. The repository relevant to your Issue is this one:
> 
> https://github.com/CollaboraOnline/richdocumentscode
> 
> And its system requirements state it requires glibc (alpine is musl based):
> 
> https://github.com/CollaboraOnline/richdocumentscode#system-requirements
> 
> If you want to advocate for an enhancement, check/open an issue here: https://github.com/CollaboraOnline/richdocumentscode

Thank you very much for clarifying. I should have specified, why I have closed this issue because I already figured out that this is the wrong place to ask and then just gave up on the issue. If I find the time (I will probably not) I might report this in the right place with more details.
