### ISSUE TITLE
Nextcloud session timing out while editing a document using Nextcloud Office

### ISSUE THREAD

**Issue by elhananjair** [nextcloud/richdocuments#2618]
**Describe the bug**
Hello there, 
I have set session_timeout to 5 Minutes on nextcloud config.php, the problem is when I am editing a document file on Nextcloud Office it will log out while I am typing or doing some activity. 
**To Reproduce**
1. Go to nextcloud config.php file, and add this config parameters, `'session_lifetime' => 300, 'session_keepalive' => false, 'auto_logout' => true`
2. Click on any document and keep editing for more than 5 Minutes
3. Nextcloud will log you out

**Expected behavior**
Nextcloud should have to see editing of documents as an activity and should extend the session lifetime. 

**Screenshots**

**Client details:**
 - OS: Fedora 
 - Browser: Firefox
 - Version: 106.0.4
 - Device: Laptop

## Server details

**Operating system**: Fedora Server

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:** 8.0.25

**Nextcloud version:** 25.0.1

**Version of the richdocuments app**  7.0.1

**Version of Collabora Online: ** CODE 22.05.8.2

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"Y3JNBRgQ1-c-yAL2i0olRQAAyhQ","level":3,"time":"2022-11-14T14:13:26+00:00","remoteAddr":"192.168.22.106","user":"--","app":"PHP","method":"GET","url":"/logout?requesttoken=EOtl1pZKLlZaRDm3VPRIXFxYDFsKS0SSiMu3LkTf1mw%3D%3Aetgz%2Fc44Yy89JWrnF456KnMCVAgzLS%2F%2F2a%2FtRh7thzg%3D","message":"session_start(): Ignoring session_start() because a session is already active at /var/www/html/nextcloud/lib/private/Session/Internal.php#219","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0","version":"25.0.1.1","data":{"app":"PHP"}}

```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
The document being edited outside of the Nextcloud session through Collabora directly so there is no way that we can detect that the session is still active when `session_keepalive` is disabled. This is something we don't consider implementing.

You might want to checkout the `auto_logout` option though which should give you the desired behaviour:
https://github.com/nextcloud/server/blob/master/config/config.sample.php#L284-L291

**Comment by elhananjair** [comment]
@juliushaertl if `session_keepalive` what is the importance of using `auto_logout`? because session_keeplive will make the session not time out, right?

**Comment by juliushaertl** [comment]
Yes, but any request would extend the keepalive (e.g. long polling of talk mesages) which are not really user interaction. For that purpose auto_logout was introduced to make the session ending process independent of potential requests but bound to actual activity in the browser.

**Comment by elhananjair** [comment]
@juliushaertl omg, so what option do I have here? I set timeout to 5 minutes and while everyone is editing a document it is ending the session and logging out everyone, which is really weird.

**Comment by Antreesy** [comment]
@juliushaertl I'd like to return to this issue again.

From the browser console, there are some events logged from time to time (see details):

<details>

```js
sentry.js?v=08154cc3-1764:2 [getWopiUrl] https://cloud.nextcloud.com/index.php/apps/richdocuments/wopi/files/7871802_instanceid
sentry.js?v=08154cc3-1764:2 [viewer] Received post message App_LoadingStatus {Status: 'Frame_Ready', Features: {…}} false
sentry.js?v=08154cc3-1764:2 [viewer] Received post message Action_Load_Resp {success: true, result: '', errorMsg: ''} false
sentry.js?v=08154cc3-1764:2 PostMessageService.sendPostMessage FRAME_DOCUMENT {"MessageId":"Host_PostmessageReady","SendTime":1695907190078,"Values":{}}
sentry.js?v=08154cc3-1764:2 PostMessageService.sendPostMessage FRAME_DOCUMENT {"MessageId":"Insert_Button","SendTime":1695907190079,"Values":{"id":"Open_Local_Editor","imgurl":"https://cloud.nextcloud.com/apps/richdocuments/img/launch.svg","mobile":false,"label":"Open in local editor","hint":"Open in local editor","insertBefore":"print"}}
sentry.js?v=08154cc3-1764:2 [viewer] Received post message App_LoadingStatus {Status: 'Document_Loaded', DocumentLoadedTime: 1695907190320} false
sentry.js?v=08154cc3-1764:2 PostMessageService.sendPostMessage FRAME_DOCUMENT {"MessageId":"Host_PostmessageReady","SendTime":1695907190398,"Values":{}}
sentry.js?v=08154cc3-1764:2 PostMessageService.sendPostMessage FRAME_DOCUMENT {"MessageId":"Insert_Button","SendTime":1695907190398,"Values":{"id":"Open_Local_Editor","imgurl":"https://cloud.nextcloud.com/apps/richdocuments/img/launch.svg","mobile":false,"label":"Open in local editor","hint":"Open in local editor","insertBefore":"print"}}
sentry.js?v=08154cc3-1764:2 PostMessageService.handlePostMessage Ignoring deprecated post message View_Added
sentry.js?v=08154cc3-1764:2 [viewer] Received post message Views_List [{…}] false
sentry.js?v=08154cc3-1764:2 [viewer] Received post message Doc_ModifiedStatus {Modified: false} false
sentry.js?v=08154cc3-1764:2 [viewer] Received post message Doc_ModifiedStatus {Modified: true} false
sentry.js?v=08154cc3-1764:2 [viewer] Received post message UI_Save {source: 'toolbar'} false
sentry.js?v=08154cc3-1764:2 [viewer] Received post message Doc_ModifiedStatus {Modified: false} false
sentry.js?v=08154cc3-1764:2 [viewer] Received post message Doc_ModifiedStatus {Modified: true} false
sentry.js?v=08154cc3-1764:2 PostMessageService.handlePostMessage Ignoring deprecated post message rev-history
sentry.js?v=08154cc3-1764:2 [viewer] Received post message UI_FileVersions {} false
sentry.js?v=08154cc3-1764:2 [FilesAppIntegration] Versions are not supported
(anonymous) @ sentry.js?v=08154cc3-1764:2
showRevHistory @ FilesAppIntegration.js:428
postMessageHandler @ Office.vue:355
sentry.js?v=08154cc3-1764:2 [viewer] Received post message UI_Save {source: 'toolbar'} false
sentry.js?v=08154cc3-1764:2 [viewer] Received post message Doc_ModifiedStatus {Modified: false} false
sentry.js?v=08154cc3-1764:2 [viewer] Received post message Doc_ModifiedStatus {Modified: true} false
```
</details>

Could it be possible to track them from Nextcloud core?

There is also an open Websocket to Collabora server, messages from which we may try to intercept

**Comment by juliushaertl** [comment]
> There is also an open Websocket to Collabora server, messages from which we may try to intercept

We cannot as it runs isolated in an iframe, but there is some WIP to implement extending the Nextcloud session while editing online in https://github.com/nextcloud/richdocuments/pull/3224
