### ISSUE TITLE
Nextcloud, or richdocuments, seems to be overriding the Content Security Policy

### ISSUE THREAD

**Issue by joho1968** [nextcloud/richdocuments#2621]
**Describe the bug**
docs.server.com is Nextcloud 25, edit.server.com is Collabora Online. Both running Ubuntu 22.04. Both running Nginx.

**To Reproduce**
1. Simply attempt to open an "Office" document (that is meant to be handled by COO)
2. I get a Content Security Policy violation

**Expected behavior**
I would expect either my previously configured headers (Nginx) to be honored, or I would expect Nextcloud to output the correct headers.

## Server details

**Operating system**: Ubuntu 22.04.LTS

**Web server:** Nginx

**Database:** n/a

**PHP version:** 8.1

**Nextcloud version:** 25.0.1

**Version of the richdocuments app** Whatever the latest is

**Version of Collabora Online** Whatever the latest is

## Summary

I have added both servers as "trusted servers" in NC, but that doesn't make any difference in the CSP output by NC when it goes to load the COO edit URL. I still only see the URL of the NC server in the CSP.

There are some fragments of hints in other GH issues, like #2471, but this is, IMHO, far too hard to find.

What I ended up doing was to re-install Nginx, from the Ubuntu 22.04 distribution and use the "more headers" module to override headers, even after the proxy response is returned for Nginx to pass onto the visitor. That was the only way I could get this working.

https://help.nextcloud.com/t/collabora-and-nextcloud-25/149981

**Comment by juliushaertl** [comment]
When configuring edit.server.com in the Office settings within Nextcloud edit.server.com should be added to the CSP automatically. This works fine here on, so there should be no need to set the CSP manually in the webserver or add any trusted servers.

https://github.com/nextcloud/richdocuments/issues/2471 is only about federated editing which does not seem to be what you are reporting.

Maybe you can share what headers get added and the output of `occ config:list richdocuments` as well as the response of docs.server.com/hosting/discovery

**Comment by joho1968** [comment]
OK. Fair enough. I couldn't get it working. When I looked at it in the Chromium console, it told me that the edit... was not an allowed URL. No matter what I tried to configure. Doing the override, as I described, worked perfectly.

```
{
    "apps": {
        "richdocuments": {
            "doc_format": "ooxml",
            "enabled": "yes",
            "installed_version": "7.0.1",
            "public_wopi_url": "https:\/\/docs.server.com:443",
            "types": "prevent_group_restriction",
            "wopi_url": "https:\/\/edit.server.com"
        }
    }
}
```

I did not put :443 anywhere.

The edit.server.com/hosting/discovery (not docs) looks fine, without :443 anywhere. Collabora staff looked at it too.

I don't know where it went south, but this is what I ended up with.

The Chromium console message was this:

```
Refused to send form data to 'https://edit.server.com/browser/0b42b3e/cool.html?WOPISrc=https%3A%2F%2Fdocs.server.com%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F454_oceyj87157zl&title=test.docx&lang=en&closebutton=1&revisionhistory=1' because it violates the following Content Security Policy directive: "form-action 'self' https://docs.server.com:443".

core-common.js?v=29357e0c-3:2 Refused to frame 'https://edit.server.com/' because it violates the following Content Security Policy directive: "frame-src 'self' nc: https://docs.server.com:443".
```

I have no idea what "nc:" means, but I haven't been able to find it in any context.

**Comment by joshtrichards** [comment]
Wait, why is your `public_wopi_url` not `https://edit.server.com`? 

Normally the only reason they'd be different is if one is an internal only address and the other is an external only address. But both should should point at your CO server one way or another in any case.

Seeing your config, it makes sense to me you're getting CSP problems: `https://edit.server.com` won't ever end up on the policy. The `public_wopi_url` will always override it.

**Comment by joshtrichards** [comment]
Closing due to insufficient information to follow-up on further. Assuming addressed.
