### ISSUE TITLE
Update Github action scripts

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/richdocuments#2663]
**Is your feature request related to a problem? Please describe.**
Fixing #2661 was not possible to by means of a `mixed` return value.

**Describe the solution you'd like**
Currently, the psalm test in the GitHub actions uses a PHP version 7.4. This version is no longer supported officially. I suggest moving to 8.0.

**Describe alternatives you've considered**
None, at some point, the upgrade needs to be done.

**Additional context**
See the [supported versions](https://www.php.net/supported-versions.php) of PHP.

**Comment by juliushaertl** [comment]
We currently use the lowest supported PHP version so this depends on when 7.4 is being dropped by server.

If that is the case the GitHub action template should be updated while then would propagate to richdocuments as well: https://github.com/nextcloud/.github/blob/master/workflow-templates/psalm.yml#L32

Closing in favour of https://github.com/nextcloud/server/issues/35025
