### ISSUE TITLE
richdocuments built-in CODE not compatible with CentOS7

### ISSUE THREAD

**Issue by bigio** [nextcloud/richdocuments#2667]
On CentOS 7.9 richdocuments built-in CODE doesn't start and an error related to curl is displayed.  
Error is:  
```
cURL error 28: Operation timed out after 45000 milliseconds with -1 out of 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html
```  
The issue is that Collabora_Online.AppImage is linked with libstdc++ that contains GLIBCXX_3.4.20 symbol but CentOS 7 only has GLIBCXX_3.4.19 symbols.   
If richdocumentscode is not going to be compatible with CentOS 7 and/or other operating systems, a warning should be printed.

**Comment by joshtrichards** [comment]
This repository is for the integration app, which is required for both the built-in as well as independent deployment models.

The Built-in CODE Server app repository is here:

https://github.com/CollaboraOnline/richdocumentscode

Alternatively you can use this integration app with a dedicated CODE instance (which will perform better anyway generally):

https://docs.nextcloud.com/server/latest/admin_manual/office/installation.html
