### ISSUE TITLE
Two nextclouds, two collaboras, one shared odt

### ISSUE THREAD

**Issue by buttle** [nextcloud/richdocuments#267]
Hi,

Two nextcloud servers, each one with a collabora server working correctly.

But…
jane@nextcloud1 creates an odt and can edit it online.
jane@nextcloud1 share the odt with carl@nextcloud2
carl@nextcloud2 accepts the share and it is added to his server.
carl@nextcloud2 cannot edit the odt from his nextcloud2 web interface.

nextcloud2 logs say:

```
Internal Server Error

Error: Call to a member function getUID() on null

0. /var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php - line 179: OCA\Richdocuments\TokenManager-&gt;getToken(*** sensitive parameters replaced ***)
1. [internal function] OCA\Richdocuments\Controller\DocumentController-&gt;index('487957')
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
3. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher-&gt;executeController(Object(OCA\Richdocuments\Controller\DocumentController), 'index')
4. /var/www/nextcloud/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher-&gt;dispatch(Object(OCA\Richdocuments\Controller\DocumentController), 'index')
5. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Richdocumen...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
6. [internal function] OC\AppFramework\Routing\RouteActionHandler-&gt;__invoke(Array)
7. /var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
8. /var/www/nextcloud/lib/base.php - line 999: OC\Route\Router-&gt;match('/apps/richdocum...')
9. /var/www/nextcloud/index.php - line 42: OC handleRequest()
10. {main}
```
I sort of imagined collaborative editing would not work. But I didn’t expect non-collaborative editing to fail.

Config on nextcloud1

```
<?php
$CONFIG = array (
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => nextcloud1',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'xxxxxxxxxxxxxxxxxxx',
  'dbtype' => 'mysql',
  'version' => '13.0.6.1',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'xxxxxxxxxxxxxxx',
  'installed' => true,
  'instanceid' => 'xxxxxxxxxxxxxxxxxxxx',
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\Memcached',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'no-reply',
  'mail_domain' => 'xxxxxxxxxxxxxxxxxxxx',
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'mail_smtpauthtype' => 'Plain',
  'mail_smtphost' => 'localhost',
  'mail_smtpport' => '25',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
);
```

Config on nextcloud2

```
<?php
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' =>
  array (
    0 => 'nextcloud2',
  ),
  'datadirectory' => '/opt/nextcloud-data',
  'overwriteprotocol' => 'https',
  'overwrite.cli.url' => 'xxxxxxxxxxxxxx',
  'htaccess.RewriteBase' => '/',
  'dbtype' => 'mysql',
  'version' => '13.0.6.1',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'xxxxxxxxxxxxxxx',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'default_language' => 'ca',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'maintenance' => false,
  'theme' => '',
  'logfile' => '/var/log/nextcloud/nextcloud.log',
  'loglevel' => 2,
  'mail_smtpmode' => 'sendmail',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'no-reply',
  'mail_domain' => 'xxxxxxxxxxxxx',
  'auth.bruteforce.protection.enabled' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'updater.release.channel' => 'stable',
);
```

Cheers.

**Comment by Pesticles** [comment]
I have this exact problem. Both nextclouds are upgraded to 14.0.3, although the problem started some time ago with version 13.?
This _used_ to work.
Sharing documents by Link seems to work, it's just the federated sharing that doesn't.

**Comment by madmath03** [comment]
I confirm the issue is still here with NextCloud 14 and Collabora Online 3.2.4 (linked to a Collabora CODE 4.0.4).

I do believe this used to work in NC 12. Any news on this ?

**Comment by madmath03** [comment]
So I did a few tests on new instances and here are my results:
* the issue does not appear if the receiving NC does not have the encryption enabled (which makes sense given the source of the error), even if encryption is enabled on the source NC
* after enabling encryption on the receiving NC, thus triggering the issue, I manually edited the `DocumentController.php` mentioned before:
```
if ($encryptionManager->isEnabled() && !empty($item->getOwner()))
```
* after the above fix, opening shared file works again
* keeping the fix in place, I can still create new documents, edit them and share with other local without issues

So, **the previous fix seems to work and not have regressions**, and I can provide a quick PR for it... but I have big questions about the **security implications** of not executing this code and I feel like **_fixing_ the owner** to a correct value would actually be better.

@schiessle, @timar, @pranavk: I picked up your names in [NextCloud Maintainers](https://github.com/nextcloud/server/wiki/Maintainers) for respectively encryption/federation and richdocuments. Could any of you help on the following questions: 
* If we do not update the access list on an encrypted instance, would it create a (security) issue ?
* When receiving a federated file, who is the owner ? What if the file was shared with a group instead of a user ? Would it be valid to use the current user for encryption update ? Something like this: `$owner = !empty($item->getOwner()) ? $item->getOwner()->getUID() : $this->uid;`

**Comment by motey** [comment]
Another behavior here:
Two instances of nextcloud(Docker:16.0.4:apache)+collabora(collabora/code:4.0.6.1) setups
Lets call them:

* cloud.work.org / office.work.org
* cloud.private.org / office.private.org

**What did i do**

* Sharing an ods-File from user01@cloud.private.org to user02@cloud.work.org
* Accept the file as user02@cloud.work.org
* Try to open the file as user02@cloud.work.org
* an "access denied" message appears.

Nextcloud log(cloud.work.org):
 ```json
{
    "reqId": "ubHyq1OkXyKDfsTVPGD0",
    "level": 1,
    "time": "2019-09-09T14:36:21+00:00",
    "remoteAddr": "146.107.176.97",
    "user": "user02",
    "app": "richdocuments",
    "method": "GET",
    "url": "\/apps\/richdocuments\/open?fileId=46380",
    "message": "Unable to determine collabora URL of remote server https:\/\/cloud.private.org\/ - Remote is not a trusted server",
    "userAgent": "Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko\/20100101 Firefox\/68.0",
    "version": "16.0.4.1"
} {
    "reqId": "ubHyq1OkXyKDfsTVPGD0",
    "level": 2,
    "time": "2019-09-09T14:36:21+00:00",
    "remoteAddr": "146.107.176.97",
    "user": "user02",
    "app": "richdocuments",
    "method": "GET",
    "url": "\/apps\/richdocuments\/open?fileId=46380",
    "message": "Failed to connect to remote collabora instance for 46380",
    "userAgent": "Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko\/20100101 Firefox\/68.0",
    "version": "16.0.4.1"
}
```
Collabora log is empty

**what happens**
It seems that the NC Collabora App is trying to connect to the remote collabora office to enable collaborative editing. Which is OK. But the domain is not trusted. So it denies access. Which is OK, too. 

**what do i expect**
But i expect to load the file in the local collabora instance instead, to enabled editing at least and not just throw me on a "access denied"-page without any other informatios.

**Comment by natrius** [comment]
Two instances of nextcloud, one with collabora (ServerB).

**Lets call them:**
- nextcloud.serverA.org
- nextcloud.serverB.org / office.private.org

**What did i do**
1. Sharing an ods-File from user01@nextcloud.serverA.org to user02@nextcloud.serverB.org
2. Accept the file as user02@nextcloud.serverB.org
3. Try to open the file as user02@nextcloud.serverB.org
4. an "access denied" message appears.

**Nextcloud log**
(Missing, can deliver later if needed)

**What happens**
It seems that the NC Collabora App from ServerB is trying to connect to the remote collabora office (ServerA) to enable collaborative editing. Which is OK. But the domain is not trusted (i could do that, but there is no collabora present right now). So it denies access. Which is OK, too.

**What do i expect**
But i expect to load the file in the local collabora instance instead, to enabled editing at least and not just throw me on a "access denied"-page without any other information.

If you need some logs, please just tell me. If Collabora is needed on both server, tell me as well :)

**Comment by juliushaertl** [comment]
Should work fine these days with the setup described in https://github.com/nextcloud/richdocuments#federated-editing--global-scale

If you still encounter issues please open a separate bug report.
