### ISSUE TITLE
This is an unsupported version.....

### ISSUE THREAD

**Issue by snetat** [nextcloud/richdocuments#2675]
Window popup see screenshot

![Screenshot from 2022-12-08 22-46-53](https://user-images.githubusercontent.com/5556794/206580335-5d4255d6-5d8e-4031-a4c0-169bba47374b.png)

**To Reproduce**
I open and **close** approx. 20 x documents. 
Then this message appears at the bottom right.
No open documents are displayed in the coolwsd admin console, but this window appears.

After restarting coolwsd it works again.

**Expected behavior**
This window should only be displayed if this limit has actually been reached.

## Server details

**Operating system**: 
Linux Debian 11.5

**Web server:**
Apache2

**Database:**
MariaDB

**PHP version:**
8.1

**Nextcloud version:**
25.0.2

**Version of the richdocuments app**
7.0.2

**Version of Collabora Online**
22.05.8.4

**Comment by srkunze** [comment]
This issue is described here: https://www.libreoffice.org/download/libreoffice-online/

**Comment by snetat** [comment]
> This issue is described here: https://www.libreoffice.org/download/libreoffice-online/

No, my problem was not the limit, but that the message was displayed although the limit was not reached.

I have changed my configuration and now this problem no longer occurs.

**Comment by juliushaertl** [comment]
This is nothing related to the richdocuments app, please report this upstream at https://github.com/CollaboraOnline/online and also provide details how you deployed CODE there.

**Comment by NikoKS** [comment]
@snetAT, what config did you change to fix the problem?
