### ISSUE TITLE
Copyable text in read only documents

### ISSUE THREAD

**Issue by grutzifix** [nextcloud/richdocuments#2682]
Hey guys

**Is your feature request related to a problem? Please describe.**
People cant copy text in read only mode in excel-like documents.
People cant use STRG+F to find something in the document.

**Describe the solution you'd like**
Not displaying text as a "picture".

I do not see the usecase where such a readonly is very usefull, I only like to prevent people to change the document.

I hope you understand,
thx Grutzifix

**Comment by digitalrevisor** [comment]
We are also having issues with this, hyperlinks don't work unless the file is editable and one can't mark and copy the links either.
This makes the read-only mode too restrictive for many use cases. 

The Office Online app handles this quite well, but there are some issues to have both apps enabled at the same time.

**Comment by juliushaertl** [comment]
This issue tracker is only for the Nextcloud connector app for Collabora Online. For issues within the Collabora Online software itself, please open a bug report at: https://github.com/collaboraonline/online
