### ISSUE TITLE
The file downloaded outside Nextcloud Office is always corrupted and cannot be opened. 

### ISSUE THREAD

**Issue by kevinkuan1969** [nextcloud/richdocuments#2706]
The file downloaded not within the Nextcloud Office is always corrupted and cannot be opened. 

When click download from the Files and Versions tab, 
![image](https://user-images.githubusercontent.com/80019930/209569402-2bb0a13f-2e81-4442-992d-0c071d22b7c2.png)

![image](https://user-images.githubusercontent.com/80019930/209569442-a057f49d-b3a8-423d-8ef5-39dd98de9786.png)

it is always displaying the following message:

![image](https://user-images.githubusercontent.com/80019930/209569313-57495cbc-23a3-4a80-881b-ada29018a2f0.png)

Expected behavior
All the office files can be opened after download locally 

Client details:

OS - MS Windows 11
Browser - MS Edge
Version 108.0.1462.54 (Official build) (64-bit)
Device: Desktop
Server details

Operating system: Ubuntu 20.14

Web server:

Database: MySQL 8.0.31

PHP version: 8.1.13

Nextcloud version: 24.0.7

Version of the Collabora Online - Build-in CODE server: 22.5.802

Version of Nextcloud Office: 6.3.2

**Comment by thebearon** [comment]
Can you add a sample both in its good and bad state? Ie. before you upload to Nextcloud, or if you download from within CODE/Collabora Online/Nextcloud Office, and the one you download separately?

**Comment by juliushaertl** [comment]
Closing as there is no feedback. Feel free to reopen when providing the additionally requested information.
