### ISSUE TITLE
Force the same protocol as the server for nextcloud 25.0.2

### ISSUE THREAD

**Issue by TwoDogs2** [nextcloud/richdocuments#2717]
Hi Is it possible to set not to use the same protocol as the server，I installed nextcloud and nextcloud office on the same server，Next Cloud has used the https protocol，So nextcloud office uses the http protocol, which is displayed normally when adding, but it will prompt later that it needs to use the same protocol as the server, and the online editing function is unavailable。
![image](https://user-images.githubusercontent.com/121689365/210334721-d0dbede1-51b4-42db-ae47-d973e206cfd9.png)
![image](https://user-images.githubusercontent.com/121689365/210334798-dc7fdca0-3631-470c-9cab-7c1820d28088.png)
![image](https://user-images.githubusercontent.com/121689365/210334880-a75553d3-4e12-4704-badf-adce49f6feef.png)

**Comment by juliushaertl** [comment]
You will need to configure your Collabora server to properly expose itself as HTTPS either through coolwsd.xml itself or through a reverse proxy that handles ssl and setting ssl.termination to true in coolwsd.xml.

More details can be found here:
https://sdk.collaboraonline.com/docs/installation/Configuration.html#ssl-configuration

Nextcloud will just use the URL that the Collabora server announces and it seems you have a mismatch there between what Nextcloud uses and what Collabora announces.

**Comment by TwoDogs2** [comment]
> You will need to configure your Collabora server to properly expose itself as HTTPS either through coolwsd.xml itself or through a reverse proxy that handles ssl and setting ssl.termination to true in coolwsd.xml.
> 
> More details can be found here: https://sdk.collaboraonline.com/docs/installation/Configuration.html#ssl-configuration
> 
> Nextcloud will just use the URL that the Collabora server announces and it seems you have a mismatch there between what Nextcloud uses and what Collabora announces.

Hi My Collaboration server is installed on the next cloud server. Can the two servers coexist I used the Collaboration Online - Built in CODE Server in Apps, but it doesn't work
