### ISSUE TITLE
New document from default templates doesn't go via TemplateSource

### ISSUE THREAD

**Issue by thebearon** [nextcloud/richdocuments#2729]
Collabora Online supports creating new files based on templates, for this the `CheckFileInfo` response needs a `TemplateSource` property with the URL to the template (as it says [here](https://sdk.collaboraonline.com/docs/advanced_integration.html#templatesource)).

However, when files created from default templates, `TemplateSource` isn't used.
See the following log snippets from coolwsd with CheckFileInfo JSON, and note how one doesn't include a `TemplateSource` entry.

- default template
```
DBG  WOPI::CheckFileInfo (95ms): {"BaseFileName":"doc1.odt","Size":642,"Version":"0","UserId":"admin","OwnerId":"admin","UserFriendlyName":"admin","UserExtraInfo":{"avatar":"https:\/\/<...>\/nextcloud\/index.php\/avatar\/admin\/64","is_admin":true},"UserCanWrite":true,"UserCanNotWriteRelative":false,"PostMessageOrigin":"https:\/\/<...>\/nextcloud\/","LastModifiedTime":"2023-01-06T02:53:09.000000Z","SupportsRename":true,"UserCanRename":true,"EnableInsertRemoteImage":true,"EnableShare":true,"HideUserList":"","DisablePrint":false,"DisableExport":false,"DisableCopy":false,"HideExportOption":false,"HidePrintOption":false,"DownloadAsPostMessage":false,"SupportsLocks":false,"IsUserLocked":false}| wsd/Storage.cpp:716
```
- custom template
```
DBG  WOPI::CheckFileInfo (90ms): {"BaseFileName":"doc2.odt","Size":11025,"Version":"0","UserId":"admin","OwnerId":"admin","UserFriendlyName":"admin","UserExtraInfo":{"avatar":"https:\/\/<...>\/nextcloud\/index.php\/avatar\/admin\/64","is_admin":true},"UserCanWrite":true,"UserCanNotWriteRelative":false,"PostMessageOrigin":"https:\/\/<...>\/nextcloud\/","LastModifiedTime":"2023-01-06T02:53:25.000000Z","SupportsRename":true,"UserCanRename":true,"EnableInsertRemoteImage":true,"EnableShare":true,"HideUserList":"","DisablePrint":false,"DisableExport":false,"DisableCopy":false,"HideExportOption":false,"HidePrintOption":false,"DownloadAsPostMessage":false,"SupportsLocks":false,"IsUserLocked":false,"TemplateSource":"https:\/\/<...>\/nextcloud\/index.php\/apps\/richdocuments\/wopi\/template\/4480?access_token=<...>"}| wsd/Storage.cpp:716
```

**To Reproduce**
1. Create eg. a personal template folder, specify it in the NC config, and add an OTT template to it,
2. Create a new file based on this template,
3. Create a new document based on the default empty template,
4. Check the `CheckFileInfo` response in coolwsd logs for both cases.

Note that step 2 fails in richdocuments 7.0.2 due to #2697.

## Server details
**Nextcloud version:**
25.0.2
**Version of the richdocuments app**
7.0.1 or so
**Version of Collabora Online**
22.05.x

**Comment by juliushaertl** [comment]
We currently create new empty files by copying the empty file assets from https://github.com/nextcloud/richdocuments/tree/master/emptyTemplates since the file creating needs to be performed before calling Collabora. Would there be any benefit in still passing a TemplateSource in case of empty files?

One issue I noticed during reproducing #2697 was that Collabora seems to fail creating a odt file from a dotx template, so I assume we would need either separate template files or a fix in Collabora to make creating files from templates of different types possible. Is that a known limitation?

**Comment by thebearon** [comment]
> We currently create new empty files by copying the empty file assets from https://github.com/nextcloud/richdocuments/tree/master/emptyTemplates since the file creating needs to be performed before calling Collabora. Would there be any benefit in still passing a TemplateSource in case of empty files?

@kendy, what is your take on this?

> One issue I noticed during reproducing #2697 was that Collabora seems to fail creating a odt file from a dotx template, so I assume we would need either separate template files or a fix in Collabora to make creating files from templates of different types possible. Is that a known limitation?

I checked this with a DOTX template in a local build, and had no problem with creating an ODT file based on it. Is there a sample DOTX you could share?

**Comment by juliushaertl** [comment]
I've seen this with the following two template files added to the user template directory when testing with #2740 

[Test.dotx.zip](https://github.com/nextcloud/richdocuments/files/10389931/Test.dotx.zip)
[presentation.potx.zip](https://github.com/nextcloud/richdocuments/files/10389925/presentation.potx.zip)

TemplateSource is set, attached the coolwsd.log for that attempt where it seems the template file is properly downloaded

[coolwsd.log](https://github.com/nextcloud/richdocuments/files/10389992/coolwsd.log)

**Comment by kendy** [comment]
> > We currently create new empty files by copying the empty file assets from https://github.com/nextcloud/richdocuments/tree/master/emptyTemplates since the file creating needs to be performed before calling Collabora. Would there be any benefit in still passing a TemplateSource in case of empty files?
> 
> @kendy, what is your take on this?

The befit as I see it is that there would be just 1 code path that is used for creating files; so it would be much easier to spot problems with file creation - as it would appear already here.

Having said that, I suppose you cannot remove the "copy & then open" functionality from Nextcloud, as you are using that also for other file templates, like the .md and others - so I don't think it is necessary to change to the TemplateSource way of creating files here.
