### ISSUE TITLE
Libre Office Online - threaded comments 

### ISSUE THREAD

**Issue by danielbotting-mcr** [nextcloud/richdocuments#274]
Hi,

In Libre Office Online currently you can put a comment on an item, we use Google Docs where you have threaded view that can be pulled up any time from within the document and the ability for 'resolved' comments to stay in place. That way you have a clear history of what has been discussed and can be referred back to.

Can this be marked as a feature request and tagged as an enhancement please.

Many thanks

Daniel

**Comment by thebearon** [comment]
Please open a bug report on this in [LibreOffice Bugzilla](https://bugs.documentfoundation.org/), for component LibreOffice Online. I'm thinking about whether this could be interesting for the desktop product... probably less relevant there.

**Comment by thebearon** [comment]
A similar bug report: [Bug 89232 - Improvements to comments look and function](https://bugs.documentfoundation.org/show_bug.cgi?id=89232)

**Comment by danielbotting-mcr** [comment]
Hi,

Please accept my apologies for the delay in responding, thanks for taking a look at this.

Many thanks

Daniel

**Comment by davepage-mcr** [comment]
I've clarified what our requirements are with our stakeholders. Basically, we need to replicate three elements of Google Docs in LOO:

1. Users can to reply to other users' comments (this already exists in Writer, but  not Calc / Impress)
2. Comment threads can be "Resolved", meaning they are hidden but not deleted, and reopened
3. An option to view all comment threads including Resolved ones, so previous discussion can be revisited
