### ISSUE TITLE
External link with edit right does not work if you are logged in

### ISSUE THREAD

**Issue by stefanroesler** [nextcloud/richdocuments#2755]
An external link with edit right doesn't work when you are already logged in.

Tested in Firefox and Chrome

Problems occur only since 6.3.3 or 7.1.0.

Message in console:
"Uncaught TypeError: OC.getCapabilities().richdocuments is undefined".

If you are not logged in to Nextcloud, it works without problems.

**Comment by juliushaertl** [comment]
Thanks for reporting. I can reproduce this and it seems related to the incognito mode that the files_sharing app sets. I'll have a look into that.

**Comment by krumelmonster** [comment]
We have the same issue, probably since the upgrade to nextcloud 25.0.3 and also cannot view documents in collabora via read only links (only preview image is shown).
Does indeed work when not logged in.

**Comment by lvarnava** [comment]
Nextcloud 24.0.9
Nextcloud Office 6.3.3
The application does not open the file in shared folders if you are logged in. Instead, the file is downloaded.

**Comment by rbircher** [comment]
Has somone tryed to reproduce this bug with NC 23?

**Comment by rbircher** [comment]
Unfortunally I deden't find a changelog from NC 23 But I found a Blog about it

[https://nextcloud.com/blog/nextcloud-hub-24-is-here/](https://nextcloud.com/blog/nextcloud-hub-24-is-here/)

There in Nextcloud Files is an entry "Improved file Permission"

I expect that the regression sits in this improovment.
