### ISSUE TITLE
Zotero improvements

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#2764]
- Send empty api key if none is configured so collabora knows that we support it https://github.com/nextcloud-releases/richdocuments/blob/db1582f937e2cde968e17eecfa1f435c3811f371/lib/Controller/WopiController.php#L228
- Listen to the post message for showing a dialog
  - Collabora will send a post message `UI_ZoteroKeyMissing` as per https://github.com/CollaboraOnline/online/pull/5703 if there was no key provided and the user clicked the button
    - We should catch this post message and show a modal as shown below

**Comment by pedropintosilva** [comment]
Pasting something quickly (there are typos and poor spacing) here  so I don't forget what is this about (that it is not just a warning but a dialog with a direct link to that `Personal settings` > `Zotero` section)
![image](https://user-images.githubusercontent.com/65948705/219068363-136d4f07-f97e-471c-897a-08ba8eec6d59.png)

**Comment by pedropintosilva** [comment]
@jancborchardt @nimishavijay ^
