### ISSUE TITLE
Regression - Open a file with Collabora update file on server even if no modifications.

### ISSUE THREAD

**Issue by RTrave** [nextcloud/richdocuments#2771]
For a few month, collabora always update file on nextcloud server, even if no modification is done.

1. Go to Files
2. Click on a doc/odt/xls/odp/.., opening it with Collabora
3. Close collabora without any change in file
4. See error: the file is updated in Nextcloud.

**Expected behavior**
As for Collabora a few month ago, or onlyoffice, or the nextcloud Text app, the doc without changes don't have to be updated on Nextcloud server ( changing modif time and creating a new version of the file ).

**Client details:**
 - OS: debian 11
 - Browser: firefox/chrome
 - Version 24 and 25

## Server details

**Operating system**: Debian 11

**Web server:** APACHE2.4

**Database:** MARIADB

**PHP version:** 8.1

**Nextcloud version:** 25.0.3

**Version of the richdocuments app** 7.1.0

**Version of Collabora Online** 
Version COOLWSD (Docker):
22.05.9.3 git hash: [6fe6d24]
Servi par : Debian GNU/Linux 11 (bullseye)

**Comment by juliushaertl** [comment]
Could you share the coolwsd xml file from your docker container?

You can get the content by running `docker exec container_id cat /etc/coolwsd/coolwsd.xml`

**Comment by RTrave** [comment]
Hi,

here's my coolwsd.xml

[coolwsd.zip](https://github.com/nextcloud/richdocuments/files/10535336/coolwsd.zip)

The unique errors i notice are:
- [ forkit ] ERR  Error while copying from /etc/passwd to /usr/bin/systemplate//etc/passwdcSNNRtgOCNdk: Failed to open dest /usr/bin/systemplate//etc/passwdcSNNRtgOCNdk| common/FileUtil.cpp:162
- [ docbroker_001 ] ERR  No socket associated with WebSocketHandler 0x7f6e4c00efd0 to send Close Frame to.| net/WebSocketHandler.hpp:189

but all is working perfectly.

**Comment by thebearon** [comment]
@RTrave can you please check information or trace level logs (run image with parameter `-e "extra_params=--o:logging.level=information"` or `trace`), and if you see entries containing `WOPI::PutFile uploaded` ... for files that you simply open and close? You shouldn't, but if the update of files is triggered by CODE/Collabora Online, it will show there. This requires at least information level logging.

There's also a setting in `coolwsd.xml` affecting this, if `always_save_on_exit` were `true`, documents would be saved regardless of being changed or not, but as I can see in your config it is `false` (which is also the default).

In addition, in a few specific cases files could open in CODE already modified, this can be noted by the state of the save icon, but this wouldn't happen to all files as noted in the description (`doc/odt/xls/odp/..`).

**Comment by RTrave** [comment]
Well, i've a confused double installation, of docker and deb Collabora. After cleaning all, seems the docker install perfectly works, so RichDocuments is not the one to blame.
Thx for support.
