### ISSUE TITLE
watermark settings in the Office admin menu are making weird stuff on the display

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/richdocuments#2794]
**Describe the bug**
all the tick boxes for the watermark settings in the Office admin menu are making weird weird stuff on the display (layout is being cut in half, and the more boxes you tick, the more it seems to cut, only ctrl+F5 seems to be a workaround at the moment) (I am on the latest enterprise version)

**To Reproduce**
1. Go to Administration settings > Nextcloud Office
3. Scroll down to Watermarks
4. Tick one of the boxes.
5. The more boxes you tick, the less content you see until the content completely disappear.

**Expected behavior**
The content should not diminish.

**Screenshots**
before unticking enable watermark for all shares
![image](https://user-images.githubusercontent.com/87175513/217255410-dcae07ce-4a0b-44eb-b1a3-8171cc34328f.png)

after unticking (or ticking)
![image](https://user-images.githubusercontent.com/87175513/217255527-669aff34-b968-4eda-bc41-4279996a3c06.png)

after refresh
![image](https://user-images.githubusercontent.com/87175513/217255527-669aff34-b968-4eda-bc41-4279996a3c06.png)

after ctrl+F5
![image](https://user-images.githubusercontent.com/87175513/217255850-134a1ddf-eafa-49f5-b5e9-da6845dc456b.png)

**Client details:**
firefox latest windows 11

## Server details
try.nextcloud.com

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:**
latest community and enterprise

**Version of the richdocuments app**
7.1.0

**Version of Collabora Online**
22.0.5

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by joshtrichards** [comment]
I can't reproduce this today. Are you still seeing this behavior?

**Comment by juliushaertl** [comment]
There was a fix for that but I cannot find the reference anymore 🙈

**Comment by joshtrichards** [comment]
Me neither, but that further suggests this really is fixed. I'll close as completed.
