### ISSUE TITLE
Typing on first line/new line is not working on firefox 

### ISSUE THREAD

**Issue by elhananjair** [nextcloud/richdocuments#2804]
**Describe the bug**
This is a problem am facing with Firefox, I create a new document and started writing something right away, unfortunately, it doesn't put the letter I type on the first line instead after I pressed space the words I type start to appear on the screen, check out the attached short video. 

**To Reproduce**
1. Go to firefox 
2. Create a new document and start to type something as nextcloud office opens the document 
3. The first letter you type won't appear 

**Expected behavior**
As in other browsers, it should appear as you type any letter. 

**Screenshots**

https://user-images.githubusercontent.com/69236638/219341085-a3d9ca15-6a6b-48b9-8f12-f14586c846bd.mp4

**Client details:**
 - OS: Fedora server
 - Browser Firefox
 - Version 109.0.1
 - Device: desktop

## Server details

**Operating system**: Fedora Server

**Web server:** Apache

**Database:** Postgresql

**PHP version:** 8.0.26

**Nextcloud version:** 25.0.3

**Version of the richdocuments app** 7.1.1

**Version of Collabora Online** 22.05.10

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Nothing related to this issue
```

#### Browser log
```
Nothing related to this issue
```

</details>

**Comment by juliushaertl** [comment]
This looks like a bug in Collabora Online itself, please open a bug report at: https://github.com/collaboraonline/online

**Comment by elhananjair** [comment]
hello, @juliushaertl is it possible to transfer it from here or I should create a new one at https://github.com/collaboraonline/online?

**Comment by juliushaertl** [comment]
Github doesn't support transferring across organisations so opening a new one would be appreciated :)
