### ISSUE TITLE
Words are not breaking at the end of the paragraph and go to next line 

### ISSUE THREAD

**Issue by elhananjair** [nextcloud/richdocuments#2805]
**Describe the bug**
I am trying to type in Amharic Language and when I type and reach the end of the paragraph some words won't continue to the next line instead the letters break apart and half of it goes to the next line. 

**To Reproduce**
1. Go to Firefox and create a new document 
2. Change your keyboard to the Amharic language
3. Type some words till you reach the end of the paragraph 
4. Try to type some words like በጣም half of the word won't step to the next line which is not right. 

**Expected behavior**
Words should go to the next line if the space is not fit them at the end of a paragraph. 

**Screenshots**

https://user-images.githubusercontent.com/69236638/219345199-0f72a328-451f-4ad0-947d-ff3b2f166f9a.mp4

**Client details:**
 - OS: Fedora 37
 - Browser: Firefox 109
 - Version: 109
 - Device: desktop

## Server details

**Operating system**: Fedora Server

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:** 8.0.26

**Nextcloud version:** 25.0.3

**Version of the richdocuments app** 7.1.1

**Version of Collabora Online**: 22.05.10

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
None related to this issue
```

#### Browser log
```
None related to this issue
```

</details>

**Comment by juliushaertl** [comment]
This looks like a bug in Collabora Online itself, please open a bug report at: https://github.com/collaboraonline/online
