### ISSUE TITLE
PDFs do not open, infinite loading

### ISSUE THREAD

**Issue by teclab-at** [nextcloud/richdocuments#2812]
**Describe the bug**
When enabling richdocuments xlsx files open, but PDFs are loading infinite. See screenshot attached.
Disabling richdocuments the PDFs download.

**To Reproduce**
Enable richdocuments with collabora demo server (Ireland for example).
Open the web-interface https://mynextcloud/.... and then click on a PDF document.

**Expected behavior**
The PDF content should be viewed.

**Screenshots**

**Client details:**
Chrome Version 110.0.5481.77

## Server details

**Operating system**:
Ubuntu 22

**Web server:**
Server version: Apache/2.4.52 (Ubuntu)

**PHP version:**
PHP 8.1.2-1ubuntu2.10 (cli) (built: Jan 16 2023 15:19:49) (NTS)

**Nextcloud version:**
[Nextcloud Hub 3](https://nextcloud.com/) (26.0.0 beta 4)

**Version of the richdocuments app**
18d64ebdd64704914daf8b3f66495e07e67135b7
Fri Feb 3 13:52:11 2023 +0100

**Version of Collabora Online**
Happens with own instance:
COOLWSD 22.05.10.1 (git hash: [719ae9b](https://github.com/CollaboraOnline/online/commits/719ae9b))
and **also with Ireland demo server**.

![collabora](https://user-images.githubusercontent.com/1011714/219938118-89a16be5-6230-4c1e-9472-f00b00bd4dfc.png)

**Comment by joshtrichards** [comment]
Hi @teclab-at - I'm unable to reproduce this in NC26 today. Are you still able to reproduce this behavior?

**Comment by teclab-at** [comment]
It looks like the issue has resolved itself. I am currently on v27.
Thank You!
