### ISSUE TITLE
Document loading failed In Docker based deployment

### ISSUE THREAD

**Issue by psarvaiya** [nextcloud/richdocuments#2824]
**Describe the bug**
Document loading failed In Docker based deployment

**To Reproduce**

We created a docker image of collabora office with the latest build. Then we use next cloud docker image, i.e. already present in docker hub.

We configured next cloud, and added postgres to integrate with the database.
In administration configuration, we have added collabora office that we created and updated the new entry point from UI.

We deploy both collabora office, next cloud and postgres on our k8s cluster.

Now, when I can create a document or any files, it shows me document loading fail. Then it automatically loads after few seconds. Overall, I have observed it is taking 27 secs to automatically load completely, and one time it fails with ‘document loading failed’.

Can someone please assist me, share some guidance/documentation on how to fix this. Also, if there is way to update the load timeout to 30 secs, so we stop getting the error.

**Expected behavior**
1. Document should be loaded without any timeout
2. Timeout can be configurable

**Screenshots**
![image](https://user-images.githubusercontent.com/112694225/221828328-a95c9a2d-0314-4a6c-aafe-44347cc006b3.png)

**Client details:**
Docker based deployment
https://hub.docker.com/_/nextcloud

## Server details

**Operating system**: Docker based deployment

**Web server:**

**Database:** mysql

**PHP version:**

**Nextcloud version:**
25.0.3

**Version of the richdocuments app**

**Version of Collabora Online** 
core-co-22.05

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
tn @ globals.js:60
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
branding.js:1          Failed to load resource: the server responded with a status of 404 ()
branding.css:1          Failed to load resource: the server responded with a status of 404 ()
cool.html?WOPISrc=http%3A%2F%2F10.1.100.212%3A8085%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F197_ocrccab3b5dy&title=hjvagcv.odt&lang=en&closebutton=1&revisionhistory=1:1316          GET http://10.1.100.212:9980/browser/e6b26f3da/branding-desktop.css net::ERR_ABORTED 404
(anonymous) @ cool.html?WOPISrc=http%3A%2F%2F10.1.100.212%3A8085%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F197_ocrccab3b5dy&title=hjvagcv.odt&lang=en&closebutton=1&revisionhistory=1:1316
Office.vue:202 FAILED
(anonymous) @ Office.vue:202
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
cool.html?WOPISrc=http%3A%2F%2F10.1.100.212%3A8085%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F197_ocrccab3b5dy&title=hjvagcv.odt&lang=en&closebutton=1&revisionhistory=1:363 L.Map.SlideShow: Cypress in window: false
TextInput.js:sourcemap:86 Blocked autofocusing on a <textarea> element in a cross-origin subframe.
onAdd @ TextInput.js:sourcemap:86
```

#### Browser log
It is failing at timeout for every document that i open, and then automatically loads after sometime.
Is there a way that I can update timeout to 1 min to stop getting error.

![image](https://user-images.githubusercontent.com/112694225/221829970-0a1698d1-fe53-4e4a-a6a8-4530d4cd5f98.png)

```
```

</details>

**Comment by kmamtora** [comment]
Hi @psarvaiya, let me know if the issue is resolved. for me also same issue, not sure what config I am missing 

@adsworth @rullzer @Gomez @SunboX can you help us on this

**Comment by HolgerHees** [comment]
I would check the following places.

1. Nextcloud logfile
2. Collabora Docker logfile
3. JavaScript Console for errors/exceptions
4. Networktab in your browser to check if there are any blocked or failed network requests

**Comment by psarvaiya** [comment]
Hi @HolgerHees , @kmamtora ,

[chrome.log](https://github.com/nextcloud/richdocuments/files/10883760/chrome.log)
[collabora.log](https://github.com/nextcloud/richdocuments/files/10883819/collabora.log)
[nextcloud.log](https://github.com/nextcloud/richdocuments/files/10883820/nextcloud.log)

Kindly assist me

**Comment by HolgerHees** [comment]
some of your request from collabora are answered with a 404
```
branding.css:1          Failed to load resource: the server responded with a status of 404 ()
branding.js:1          Failed to load resource: the server responded with a status of 404 ()
branding-desktop.css:1          Failed to load resource: the server responded with a status of 404 ()
Office.vue:202 FAILED
```

can you check the network tab too.

**Comment by psarvaiya** [comment]
Please find the complete network,  https://drive.google.com/file/d/1WOtpqrGcxNRW-aJ-1Vy2dfJw0KdIwFvw/view?usp=sharing

<img width="1440" alt="Screen Shot 2023-03-06 at 5 16 10 PM" src="https://user-images.githubusercontent.com/112694225/223101848-c98ae220-71ad-4cfb-9bca-eeec7f7febd8.png">
<img width="1440" alt="Screen Shot 2023-03-06 at 5 16 20 PM" src="https://user-images.githubusercontent.com/112694225/223101861-391b7c51-de3f-4324-9545-9dafa13af3f6.png">

Please note, i create/view a write/any file first time it always fails, then it automatically loads in 30 secs. Kindly assist me, let me know if you need more information

**Comment by HolgerHees** [comment]
you have to find out why you get these 404. In your log files I have not find anything related to it.

**Comment by psarvaiya** [comment]
okay, is there a way that I can increase the timeout, lets say 1 min in Office.vue so this will reduce the probability of this error ?

**Comment by HolgerHees** [comment]
I think this is the wrong way. If this ressource takes longer then 2 seconds to load, something is wrong. 

So, if you increase the timeout you will just delay the error message.

If I open my branding.js url, it will load on 0.016 seconds. And my server has a intel atom cpu which is extremely slow.

**Comment by psarvaiya** [comment]
Hi @HolgerHees ,

I have added the files manually. So, I copied 3 files from collabora image present in dockerhub inside my container, now I am not getting 404. But, still document failing with timeout in office.vue. 

![image](https://user-images.githubusercontent.com/112694225/223115239-9c22ba9b-c243-4109-9c31-fe99453f593f.png)

**Comment by HolgerHees** [comment]
then there must be still an error.

The timeout is just a sympthom of somthing went wrong. The procedure is the following.

1. The Framework is initializing a timer which shows after a while this error
2. The Framework is initialized and starts loading resources etc.
3. If everything is loaded and initialized, the timer is canceled

in your case, point 2 is failing somewhere. This is why the timer is triggered and showing the error message. Please check everything again very carefully. There must be a problem somewhere.

May you can use the collabora docker container, which works for me fine. This will reduce the amount potential error cases.

**Comment by Wikinaut** [comment]
My (bad) experiences with Collabora are based on virtual machines with a low RAM memory assignment. On these VMs, Nextclouds works fine, but not with the `richdocuments` office suite. 

Unfortunately -  and I complain about this - there is no indication oder notification (during deployment, starting-up or so), that the memory is too low to run it.
