### ISSUE TITLE
Compatibility...

### ISSUE THREAD

**Issue by jenspeternielsen** [nextcloud/richdocuments#2825]
If you create / save a spreadsheet in Nextcloud office and then open it in excel or Libre Office - 
the sheet opens at 200% zoom factor - maybe not a bug but just annoying. 
<img width="224" alt="Skærmbillede 2023-02-28 kl  12 04 01" src="https://user-images.githubusercontent.com/4323147/221837708-30e6bb64-b641-4b22-a9f8-b9b295ebf711.png">
<img width="542" alt="Skærmbillede 2023-02-28 kl  12 06 28" src="https://user-images.githubusercontent.com/4323147/221837890-8d1391d2-2f9f-4137-9f49-61401427d021.png">

**Comment by thebearon** [comment]
This is tracked in the following issue, let me close it here:
https://github.com/CollaboraOnline/online/issues/4250
