### ISSUE TITLE
Logo not showing on white background

### ISSUE THREAD

**Issue by oculos** [nextcloud/richdocuments#2832]
**Describe the bug**

A white Nextcloud logo does not show when viewing a document.

**To Reproduce**
1. Choose a white logo
2. Open a document
3. The logo is not visible

**Expected behavior**

There should be an option to get a darker background for the top bar.

**Screenshots**

<img width="367" alt="Screenshot 2023-03-03 at 13 34 56" src="https://user-images.githubusercontent.com/6791923/222721602-bfdf6ead-1341-4b53-9fbe-d77dfe6360ab.png">

**Client details:**
 - OS: macOS
 - Safari

**Nextcloud version:**
25.0.1

**Version of the richdocuments app**
7.1.1

**Version of Collabora Online**
The newest.

**Comment by pedropintosilva** [comment]
I have been thinking about this and testing things out. Probably the best would to allow users to upload an inverted version of their logo via `nextcloud-instance/index.php/settings/admin/theming` 

* Allows for better user control over personal branding
* Avoids problems from alternative solutions (as using the primary colour as the background)
  * Contrast and colour problems will appear
  * Extra hacky code to account for special cases (just apply this for when the logo is white, or lacks etc)
* Benefits the upcoming dark-mode

This is just an idea but if we agree on this we then need to think about clear labelling within `nextcloud-instance/index.php/settings/admin/theming` , probably avoid the word "inverted" and be clear about it. Something that expresses :
| Section | Description | button |
| --- | --- | --- |
| Logotype | For dark backgrounds | Upload |
| Logotype | For light backgrounds | Upload |

**Comment by juliushaertl** [comment]
@elzody Could you share the workaround implemented here and file a follow up in server about the additional logo option for the theming settings?

**Comment by elzody** [comment]
Sure, as an update to this issue we implemented a workaround which lets you set CSS variables to control the background color or visibility of the logo in Collabora.

```css
:root {
  /* change the background color of the logo */
  --nc-logo-background: cyan;

  /* or hide the logo completely */
  --nc-logo-display: none;
}
```

In order to set these properties you need to use the [custom css](https://apps.nextcloud.com/apps/theming_customcss) app, which exposes an extra area in the theming settings to enter custom CSS

**Comment by juliushaertl** [comment]
Let's close this here since we have a server issue tracking a custom logo and we have a workaround with the custom css app, so there is nothing else we can do for now on the richdocuments side.
