### ISSUE TITLE
Failed to lock docKey [...] with session [...] after downloading

### ISSUE THREAD

**Issue by HolgerHees** [nextcloud/richdocuments#2833]
**Describe the bug**
I'm running latest nextcloud (25.0.4) and collabora (22.05.10.8.1) docker images. Both, nextcloud and collabora are behind an apache reverse proxy.  Everything works fine, including editing documents in collabora.

Only one strange thing is, that every time, I'm opening a document, I get the following error log in collabora. Without any noticeable effect.

```
wsd-00001-00051 2023-03-03 13:20:22.575099 +0100 [ docbroker_001 ] ERR  Failed to lock docKey [https://nextcloud.myserver.de:443/index.php/apps/richdocuments/wopi/files/105404_ocbbe1e1d5a2] with session [001] after downloading: | wsd/DocumentBroker.cpp:1009
```

the related http logs are reporting http code 200. 

has anyone an idea whats happen here?

**Comment by juliushaertl** [comment]
Debug log should give more details about this, but might be that this is reported becaues locks are only supported in combination with the files_lock app currently.

https://github.com/CollaboraOnline/online/blob/b8fe7cd24bea500896b87fd8e5f1f1be74cd359e/wsd/DocumentBroker.cpp#L1229 returns false and could still trigger this error then.

**Comment by HolgerHees** [comment]
Thanks for the explanation. So, I will ignore it for now.

Should I close this ticket?

**Comment by juliushaertl** [comment]
Yes, I've just filed https://github.com/nextcloud/richdocuments/issues/2835 as this would make sense to have lock support even without an additional app.
