### ISSUE TITLE
security: wrong protocol is used which triggers an mixed content error

### ISSUE THREAD

**Issue by magiruuvelvet** [nextcloud/richdocuments#284]
I'm experiencing an issue I can't figure out why this even happens. For no apparent reason richdocuments falls back to http in the URL, even though https is configured.

### Steps to reproduce
1. Go to `richdocuments` settings.
2. Enter the Collabora Office URL with explicit https `https://your.office.com`.
3. Open dev console and see `http` being used instead of `https` for the Collabora Office URL and get a mixed content error because of this :(

![screenshot_20181019_182732](https://user-images.githubusercontent.com/13280758/47231270-bb105900-d3cc-11e8-87a9-7105292e63dd.png)

### Expected behaviour
richdocuments should use https as declared in the settings and don't fall back to http for whatever reason.

### Actual behaviour
![screenshot_20181019_182719](https://user-images.githubusercontent.com/13280758/47231262-b6e43b80-d3cc-11e8-8e04-7923cdf72bcf.png)

### Server configuration (Nextcloud server)

**Operating system**: FreeBSD 11.2

**Web server:** Caddy Server 0.11

**Database:** MariaDB 10.2.17

**PHP version:** PHP 7.2.10

**Nextcloud version:** 14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** rolling since version 10

**Where did you install Nextcloud from:** official release package extracted to a directory

**Signing status:** disabled
```
Integrity checker has been disabled. Integrity cannot be verified.
```

**List of activated apps:**
```
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_notifications: 1.0.2
  - announcementcenter: 3.3.1
  - apporder: 0.5.0
  - audioplayer: 2.4.1
  - bookmarks: 0.13.1
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.3
  - camerarawpreviews: 0.6.1
  - caniupdate: 0.2.0
  - checksum: 0.4.1
  - cloud_federation_api: 0.0.1
  - contacts: 2.1.6
  - dav: 1.6.0
  - deck: 0.4.1
  - external: 3.1.0
  - federatedfilesharing: 1.4.0
  - files: 1.9.0
  - files_accesscontrol: 1.4.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - flowupload: 0.0.8
  - gallery: 18.1.0
  - groupfolders: 1.3.3
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.11.0
  - metadata: 0.7.0
  - music: 0.9.2
  - nextcloud_announcements: 1.3.0
  - notes: 2.4.2
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - previewgenerator: 1.1.0
  - provisioning_api: 1.4.0
  - quota_warning: 1.3.0
  - richdocuments: 3.0.1
  - serverinfo: 1.4.0
  - spreed: 4.0.0
  - support: 1.0.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - theming_customcss: 1.1.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_totp: 1.5.0
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
```

**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
                *** REMOVED ***
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.magiruuvelvet.gdn",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 1.5
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "integrity.check.disabled": true,
        "theme": "",
        "loglevel": 0,
        "enable_previews": true,
        "preview_max_filesize_image": 50,
        "preview_libreoffice_path": "\/usr\/local\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore --convert-to pdf --outdir ",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\SVG",
            "OC\\Preview\\Image",
            "OC\\Preview\\PDF",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Photoshop"
        ],
        "updater.release.channel": "stable",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25"
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

Nextcloud is managed by Caddy.

### Server configuration (Collabora Office server)

**Operating system:** CentOS 7

**Web server:** Caddy Server 0.11

**Collabora Office Version:** 5.3

`loolwsd` is strictly running on localhost, Caddy acts as a HTTPS proxy. SSL in loolwsd.xml is disabled!

Collabora itself is working fine and when hacking together some basic s\*\*\* using electron and ignoring any kind of security it basically works. I also tried playing around with CSP headers, but no chance. Firefox just hates on everything.

### Client configuration
**Browser:** Mozilla Firefox 56.0.2 with *custom* patches and backports

**Operating system:** Arch Linux

#### Web server error log
none

#### Nextcloud log (data/nextcloud.log)
no entry related to richdocuments, only lots of debug spam

#### Browser log
see screenshot above

---

## Bonus section

This is my Caddyfile for Collabora Office
```
    # Collabora Office root url and static files
    proxy / http://127.0.0.1:9980/ {
        transparent
        websocket
    }

    # client-side JavaScript components
    proxy /loleaflet http://127.0.0.1:9980/ {
        transparent
        websocket
    }

    # WOPI discovery URL
    proxy /hosting/discovery http://127.0.0.1:9980/ {
        transparent
        websocket
    }

    # WebSockets, download, presentation and image upload
    proxy /lool http://127.0.0.1:9980/ {
        transparent
        websocket
    }
```

---

Some important side note: Previews are WORKING!! Previews are definitely generated using loolwsd.

**Comment by magiruuvelvet** [comment]
I found a fix for this problem and now everything is working. The issue was not related to richdocuments, but the configuration in loolwsd. Under the SSL section I had SSL disabled because of the Caddy proxy, but loolwsd returned a http URL. I found an option under the SSL settings called termination and it was set to false. I changed it to true and now https is used.

Posting this in case others are **not** using the docker image, but installed the package from the repositories and experiencing the same issue with proxies.

Feels free to mark this issue as invalid.

**Comment by thebearon** [comment]
Yes, that makes sense if you use a termination proxy. I'm glad to hear the issue is resolved.

**Comment by pierre-alain-b** [comment]
Hi there,

I have exactly the same issue as the one described above. Yet
- SSL is disabled in loolwsd.conf
- SSL termination is set to true, https://collabora.mydomain.tld works well, https://collabora.mydomain.told/hosting/discovery returns only https URLs
- the URL of the CODE server is https (and the apps says it is reachable)

But, in Nextcloud, I get an error "mixed content" and the request is blocked because indeed I see that the app calls http://collabora.mydomain.tld and not https !

I have two proxy: first a Haproxy just pushing everything to Nginx and then Nginx (set as described here: https://www.collaboraoffice.com/code/nginx-reverse-proxy/) that relays to the code server (deployed as described here: https://www.collaboraoffice.com/code/linux-packages/).

Any idea?

**Comment by pierre-alain-b** [comment]
Well I fixed the issue for me by dropping my 2 layers of reverse proxy even if it was annoying. I guess the collabora code server does not fully respect the x-forwarded-proto that can be passed by a chain of reverse proxies?
