### ISSUE TITLE
Move revision history to regular files sidebar

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#286]
The revision history is already using the Nextcloud versions api, so we should make sure we don't have another sidebar there. When clicking a version in the files sidebar, it should be previewed in collabora. Also when restoring a version while editing a document, the user should see the updated document.

**Comment by rullzer** [comment]
I noticed the revision history is broken in NC15 because we removed the weird API.
Could we somehow move over the functionality to the main NC version sidebar?

**Comment by juliushaertl** [comment]
@rullzer I have a partly working solution locally, however it still has some issues when the sidebar is opened before the document is open in collabora. I'll try to look into that so we have a properly working version for 15.

**Comment by juliushaertl** [comment]
Done with #316
