### ISSUE TITLE
Cannot specify CA certificates to connect nextcloud to collabora server

### ISSUE THREAD

**Issue by keestux** [nextcloud/richdocuments#2865]
In my setup I have SSL certificates generated by FreeIPA. There is a CA cert installed on all systems and in all tools (browsers, etc). We also have a collabora server setup with a proper FreeIPA cert. All systems works fine except that my nextcloud instance does not accept the SSL connection to the collabora server. The work-around is to set the "Disable certificate verification".

What I would like to have is a way to configure nextcloud (probably `richdocuments` is more precise) to use the correct list of CA certs. On my CentOS system that list is in `/etc/pki/tls/cert.pem`. On Ubuntu/Debian it would be `/etc/ssl/certs/ca-certificates.crt`.

Or else, it would be nice to know which part of the software actually contains the (builtin?) list of trusted CA certs. `richdocuments` is partly PHP, partly typescript, right?

**Comment by juliushaertl** [comment]
It uses the Nextcloud servers certificate store so https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#security should give you the hints for adding the certificate there.

**Comment by keestux** [comment]
Thanks. That worked.
