### ISSUE TITLE
Richdocuments tables not installing in database

### ISSUE THREAD

**Issue by davidwuest** [nextcloud/richdocuments#2878]
**Describe the bug**
Hello, hope someone can help.
the richdocuments app is installing without problems, but I get the error that the following tables are missing:
oc_richdocuments_wopi
oc_richdocuments_template

I actually can’t find any oc_richdocuments tables in the database.

Are the oc_richdocuments tables are generated on install or part of nc db?

Can someone please post me the oc_richdocuments tables structure.

Thanks in advance for any help.

**To Reproduce**
no info

## Server details

**Operating system**:
18.04.6 LTS

**Web server:**
apache 
**Database:**
MariaDB

**PHP version:**
8.2.4

**Nextcloud version:**
26.0.0.

**Version of the richdocuments app**
8.0.0

**Version of Collabora Online**
22.05.12.4

**Comment by davidwuest** [comment]
@juliushaertl Thanks for the feedback. I tried that, but it did not work. Solution was to setup a fresh NC instance, install  the app and copy the oc_richdocuments_% tables to the data base missing the tables.

**Comment by Mannshoch** [comment]
@juliushaertl I have the same Error message

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'meinenextcloud_.oc_richdocuments_template' doesn't exist","Code":1146,"Trace"`

Is the proposed solution still the same?

I tryed to deactivate, uninstall and reinstall. that not worked.

**Comment by Mannshoch** [comment]
For the record, solved: https://github.com/nextcloud/richdocuments/issues/3186#issuecomment-1776619670
