### ISSUE TITLE
Weird Error

### ISSUE THREAD

**Issue by jet438** [nextcloud/richdocuments#2888]
I'm now getting a weird error in my Nextcloud log file. The error says it's from richdocuments.
GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: cloud.example.com 

Now I'm pretty sure that the host name (cloud.example.com) is in the config file somewhere. Not sure where that config file is or what to change it to once I find it.

I'm using the Collabora built in code server 22.05.802 and Nextcloud Office 7.1.2 on Nextcloud 25.0.5. I installed everything through Nextcloud and it didn't ask me to change anything and there's nothing in the Nextcloud's administration sections to change.

Any help would be greatly appreciated

**Comment by jet438** [comment]
I actually figured it out (I think). I disabled CODE arm64 on my server and
now it works fine with just Next cloud Office enabled. No errors.

**Comment by joshtrichards** [comment]
Hi @jet438 Glad you figured it out, but I'm a bit confused: I thought you were using the Built-in CODE Server? With it disabled don't you no longer have Office access?

**Comment by joshtrichards** [comment]
Okay. Settings are all under *Administration settings -> Office*

That'll also tell you what CODE Server you're using if it's not the built-in one.

I'll close this out.
