### ISSUE TITLE
Move file integration to events

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#2894]
> Just for some awareness for the files2vue project, we have this use case where the viewer interaction would want to update the underlying file list on save/save as/rename. Is that something considered already? I guess we could use events for that in the future.

Yes, I started doing that here: https://github.com/nextcloud/server/blob/5024f295dcfdf850d2d95f419bcf122bf08be5c8/apps/files/src/components/NavigationQuota.vue#L81-L91
You can use the following:

```js
subscribe('files:file:created', (node: Node) => {})
subscribe('files:file:deleted', (node: Node) => {})
subscribe('files:file:moved', (node: Node) => {})
subscribe('files:file:updated', (node: Node) => {})

subscribe('files:folder:created', (node: Node) => {})
subscribe('files:folder:deleted', (node: Node) => {})
subscribe('files:folder:moved', (node: Node) => {})
subscribe('files:folder:updated', (node: Node) => {})
```

```js
subscribe('files:folder:updated', ({ fileid }: { fileid: string }) => {})
```

_Originally posted by @skjnldsv in https://github.com/nextcloud/richdocuments/issues/2881#issuecomment-1495669157_

**Comment by juliushaertl** [comment]
Btw, the data passed will be a [`Node`](https://nextcloud.github.io/nextcloud-files/classes/Node.html) (`File` or `Folder`) object. Which you can check against `fileid` :)

**Comment by skjnldsv** [comment]
I do wonder if we shouldn't merge those two and use `node` instead and let the dev check for `node.type === FileType.Folder`

```js
subscribe('files:node:created', (node: Node) => {})
subscribe('files:node:deleted', (node: Node) => {})
subscribe('files:node:moved', (node: Node) => {})
subscribe('files:node:updated', (node: Node) => {})
```

Any preferences @juliushaertl ?

**Comment by juliushaertl** [comment]
Adapted where needed.
