### ISSUE TITLE
Loading files never finishes

### ISSUE THREAD

**Issue by srkunze** [nextcloud/richdocuments#2909]
**Describe the bug**
Loading a file (click on the file) should open the file editor in the browser. The loading overlay appears and stays forever.

**To Reproduce**
1. install nextcloud with snap
2. install CODE via the web interface
3. install Nextcloud Office via the web interface
4. open pre-uploaded file "Simple.odp"

**Expected behavior**
Opens Nextcloud Office editor.

**Screenshots**
![image](https://user-images.githubusercontent.com/1389648/230798787-993dfbf0-c68d-4a38-9de4-715fd4e739d8.png)

**Client details:**
 - OS: Ubuntu 22.04.2
 - Browser chrome
 - Version 111
 - Device: Lenovo Laptop

## Server details

**Operating system**: Ubuntu 22.04.2

**Web server:** haproxy

**Database:** MySQL

**PHP version:**

**Nextcloud version:** 25

**Version of the richdocuments app** 7.1.2

**Version of Collabora Online** 22.5.802

<details>
nothing found so far. any hints are appreciated
</details>

**Comment by LokeYourLord** [comment]
You might be facing this one: https://github.com/nextcloud/richdocuments/issues/2873

I face this on mobile (app) only. Web Browser on PC and Mobile loads just fine for me.

**Comment by LokeYourLord** [comment]
Having set "Log Level" to "0" (debug), even that gives me no particularly related message that tells me why a file doesn't open on the mobile app, but opens on the Web interface. Truly weird.

**Comment by srkunze** [comment]
I just deactivated CODE and used a dedicated setup Collabora server on my machine. That seem to work fine. But CODE behind a reverse-proxy doesn't seem to work.
