### ISSUE TITLE
"no_glibc" infinite loading issue

### ISSUE THREAD

**Issue by LukeVader-IV** [nextcloud/richdocuments#2912]
**Describe the bug**
Hi, i have an issue with nextcloud office, it will indefinetly show the loading icon when a file is opened.
I noticed a PHP error in /var/log/php-fpm/www-error.log
`richdocumentscode (proxy.php) error exit, PID: 1391, Message: no_glibc`
however glib_c is most definitely installed on the system

further i have no SELinux errors

**To Reproduce**
1. install Nextcloud office and Collabora built-in code server
2. open a document (like a spreadsheet)
3. wait indefinetly

**Expected behavior**
opens the office suite and allows you to edit the selected file

**Client details:**
 - OS: Fedora Workstation 37 / Workstation 38 / Silverblue 37
 - Browser: chrome / firefox
 - Device: desktop

## Server details

**Operating system**: Rocky Linux 8

**Web server:** Apache

**Database:** MariaDB

**PHP version:** php-8.0.28-1.el8.remi.x86_64

**Nextcloud version:** 25.0.5

**Version of the richdocuments app** 7.1.3

**Version of Collabora Online** 22.5.802

**Comment by juliushaertl** [comment]
The error is part of the richdocumentscode app so it would be appreciated if you file the issue at https://github.com/CollaboraOnline/richdocumentscode

For reference this is the code that checks for glibc:
https://github.com/CollaboraOnline/richdocumentscode/blob/master/proxy.php#L147-L149
