### ISSUE TITLE
Zotero integration with Collabora not working

### ISSUE THREAD

**Issue by Andriel00** [nextcloud/richdocuments#2913]
**Describe the bug**
Zotero citations integration with Nextcloud Office (Collabora) not working. Not showing citations or adding anything to the document for that matter, when choosing publication. Same behavior in Webinterface and on mobile (IOS).

**To Reproduce**
   Open nextcloud in Web
   Enter Zotero API Key into Settings
   Open document and click "add reference"
   Work through dialogues (choose style, choose publication) and click ok.
   Click on generate bibliography

**Expected behavior**
Adding citations into text after choosing the publications in the dialogues. Being able do generate bibliography for document.

**Actual behavior**
Nothing happens after clicking OK after choosing publication.
Clicking generate bibliography does not do anything if clicked after add reference dialogue.
If clicked before, style can be chosen but nothing happens afterwards.

**Environment**
Nextcloudhub 26, Nextcloudoffice v8.0.1, Dedicated Collaboraonline CODE Server in Docker with latest version

**Comment by juliushaertl** [comment]
So as it seems to load the bibliography items I don't suspect an issue with the integration of the API key. Could you file this issue upstream at https://github.com/CollaboraOnline/online as this is most likely related to CODE itself.

FYI @pedropintosilva
