### ISSUE TITLE
Same Long List Error Message - Could not find token 

### ISSUE THREAD

**Issue by kevinkuan1969** [nextcloud/richdocuments#2916]
**Describe the bug**

The Nextcloud Office works fine but the same error message keep on generating non-stop in the Logfile saying could not find token. 
![image](https://user-images.githubusercontent.com/80019930/232178044-62c5454d-83df-4e92-b716-076c8416c47a.png)
 

 Server details

Operating system - Ubuntu 22.04

Web server - Apache2 

Database:  MariaDB 10.6.12

PHP version: 8.1

Nextcloud version: 26

Version of the richdocuments app   8.0.1

Version of Collabora Online  22.5.1301

**Comment by juliushaertl** [comment]
This should be covered by the upstream fix at https://github.com/CollaboraOnline/online/issues/5870
