### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/richdocuments#292]
### Steps to reproduce
1. Deploy the app
2. Configure to be available to a small group of users for testing

### Expected behaviour
App should only be available to the users in the selected group

### Actual behaviour
Some users not in the group also have access (few, not many, no pattern discerned as to which users also gain access)

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** Postgres

**PHP version:** 7.0.8

**Nextcloud version:** 14.03

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated through many versions

**Comment by putt1ck** [comment]
We thought this was resolved by an update to 3.02, but it turns out the issue is intermittent. The original user to experience the issue has now tested this and reports he "clicked on a word doc and it opened in collabora, clicking on another word doc 2 minutes later behaved as expected (ie download option only). Then clicking on the original document gave the expected behaviour (download) rather than opening in Collabora".

**Comment by Binford3000** [comment]
Here are my problems with this "bug".
I installed the latest Collabora Nextcloud app and use the latest Collabora docker image. I have the app enabled and restricted to a group of users. Everything works fine as expected until someone shares a doc as a link. The doc is opened with collabora but it should not. If you open the link as a logged in user with no permission to use collabora, the "file download" appears. If the same user logout and open the link, collabora pops up!?

Cheers!

**Comment by juliushaertl** [comment]
> Configure to be available to a small group of users for testing

The richdocuments app does not support being limited to groups, since with that public sharing would not work anymore.

**Comment by putt1ck** [comment]
Apologies there must be a misunderstanding. On the install we go to settings -> Collabora Online. There is an option there "Restrict usage to specific groups". The information link at the top of that settings group takes us to a page about irchdocuments and the github link on that leads here. Is it not the same app?

**Comment by juliushaertl** [comment]
@putt1ck Ok, sorry, I was just checking the app settings and missed the additional settings in the richdocument app. 

Can you give some more details how the users can open the file? Can you check if there is any error in the browser console?
