### ISSUE TITLE
Adjust smart picker labels in Collabora

### ISSUE THREAD

**Issue by julien-nc** [nextcloud/richdocuments#2920]
This is something to adjust in Collabora Online. This issue is for keeping track on our side.

It would be nice to change the label of the menu item that opens the smart picker from `Pick link` to `Open the Smart Picker`.

Another suggestion: `Hyperlink...` could be renamed to `Insert link`.

**Comment by juliushaertl** [comment]
Saying was adjusted in https://github.com/CollaboraOnline/online/pull/6170

As per discussion with @jancborchardt we should generally adjust the smart picker icon to https://fonts.google.com/icons?selected=Material+Icons:dashboard_customize: as the current one may cause confusion with inserting shapes
