### ISSUE TITLE
Nextcloud no longer responds after activating Nextcloud Office

### ISSUE THREAD

**Issue by neckflo90** [nextcloud/richdocuments#2923]
Sobald die Anwendung in der Version 8.0.1 installiert wird, erscheint sofort ein Serverfehler 500 oder Nextcloud reagiert nicht mehr und nach ein paar Minuten folgt und es besteht kein Zugriff mehr auf die Nextcloud. Die Anwendung muss dann via ssh mit 'occ app:disable richdocuments' deaktiviert werden.

Debian 11
Server version: Apache/2.4.56 (Debian)
PHP 8.0.28 (cli)
Nextcloud:  26.0.1

**Comment by joshtrichards** [comment]
A 500 error means there was an exception or other fatal error generated in Nextcloud Server. What does your `nextcloud.log` show for these web transactions when this happens?

**Comment by joshtrichards** [comment]
Closing due to insufficient information to follow-up on further.
