### ISSUE TITLE
Collabora randomly fails to save since NC26+

### ISSUE THREAD

**Issue by tareko** [nextcloud/richdocuments#2927]
**Describe the bug**
Since upgrading to NC26, I have had multiple messages saying that a file could not save. The error message is: "Document cannot be saved to storage. Check your permissions or contact the storage server administrator.". This seems to be random. Most times it saves, but it can lose a significant amount of information without notice, costing several hours of work sometimes. All permissions seem correct and certainly haven't changed since the upgrade.

**To Reproduce**
1. Go to pre-existing document
2. Type some stuff
4. Error appears

**Expected behavior**
Files should save and not have write problems.

**Screenshots**

**Client details:**
 - Device: [e.g. iPhone6, desktop]

## Server details

**Operating system**:
Ubuntu 22.04

**Web server:**
nginx/1.18.0 (Ubuntu)

**Database:**
mysql  Ver 8.0.32-0ubuntu0.22.04.2 for Linux on x86_64 ((Ubuntu))

**PHP version:**
PHP 8.1.2-1ubuntu2.11 (cli) (built: Feb 22 2023 22:56:18) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.11, Copyright (c), by Zend Technologies

**Nextcloud version:**
26.0.1

**Version of the richdocuments app**
8.0.1
```
        "richdocuments": {
            "enabled": "yes",
            "installed_version": "8.0.1",
            "public_wopi_url": "https:\/\/office.x.x",
            "types": "prevent_group_restriction",
            "wopi_url": "https:\/\/office.x.x"
    }
```

**Version of Collabora Online**
22.05.13.1

<details>

<summary>Logs</summary>

#### Logs from Collabora pod
```
wsd-00001-00410 2023-04-25 16:03:22.373750 +0000 [ docbroker_010 ] WRN  #31: Timed out while requesting [POST cloud.x.x/index.php/apps/richdocuments/wopi/files/<numericid_replaced>/contents?access_token=<token_replaced>&access_token_ttl=1682474320000] after 33759ms| net/HttpRequest.hpp:1463
wsd-00001-00410 2023-04-25 16:03:22.373919 +0000 [ docbroker_010 ] ERR  Unexpected response to WOPI::PutFile. Cannot upload file to WOPI storage uri [https://cloud.x.x/index.php/apps/richdocuments/wopi/files/<numericid_replaced>/contents?access_token=<token_replaced>&access_token_ttl=1682474320000]: 0 : No response received. Connection terminated or timed-out.| wsd/Storage.cpp:1544
wsd-00001-00410 2023-04-25 16:03:22.373963 +0000 [ docbroker_010 ] ERR  Failed to upload docKey [https://cloud.x.x:443/index.php/apps/richdocuments/wopi/files/<numericid_replaced>] to URI [https://cloud.x.x/index.php/apps/richdocuments/wopi/files/<numericid_replaced>?access_token=<token_replaced>&access_token_ttl=1682474320000]. Notifying client.| wsd/DocumentBroker.cpp:1947
wsd-00001-00410 2023-04-25 16:05:46.722018 +0000 [ docbroker_010 ] ERR  getJSONValue for [COOLStatusCode]: Invalid access: Can not convert empty value.| common/JsonUtil.hpp:86
wsd-00001-00410 2023-04-25 16:05:46.722170 +0000 [ docbroker_010 ] ERR  PutFile says that Document [https://cloud.x.x:443/index.php/apps/richdocuments/wopi/files/1720541_5069b7bf5a66e] changed in storage| wsd/DocumentBroker.cpp:1963
```

#### Nextcloud log (data/nextcloud.log)
No useful logging information

#### Browser log
Nothing particularly useful here.

</details>

**Comment by joshtrichards** [comment]
The first two lines of your logs suggest your Collabora Online container(s) are having trouble reaching `https://cloud.x.x/`.

If there are no entries in your Nextcloud server logs than it's connections or connectivity are being interrupted somewhere else along the way.

What ds your lb/proxy/web server logs show for these transactions?

Unl

**Comment by joshtrichards** [comment]
Closing due to no further response after >6 months.
