### ISSUE TITLE
Problem with 2-byte character input

### ISSUE THREAD

**Issue by Bables55** [nextcloud/richdocuments#294]
### Steps to reproduce
1.Open the Collabora documents at Nextcloud(Collabora Office 5.3-57) with the Vivaldi browser.
2.Enable Japanese input mode
3.Enter Japanese

### Expected behaviour
Characters are correctly entered

### Actual behaviour
2-byte characters are regularly repeated twice.
I will explain with the alphabet)
I enter "NIHONGO". Then "NIHONGONIHONGO" is displayed on the screen.
When I enter sentences without leaving:
I enter "NihongoSCHOOLheikou". Then "NihongoSCHOOLheikouNihongoSCHOOLheikou".
When inputting by word:
I enter "Nihongo" -> "SCHOOL" -> "heikou". Then "NihongoNihongo" "SCHOOL" "heikouheikou".
As mentioned above, only 2-byte characters are consecutive twice.
This is not a problem with Firefox. Vivaldi(ver.2.0 or 2.1) (probably also Chrome) is occurring.
The type of Japanese input system(IME) seems to be related. The standard in Japanese is MS-IME.

### Server configuration

**Operating system**:
CentOS 7.5
**Web server:**
eginx 1.13.8
**Database:**
MariaDB 10.2.18
**PHP version:**
PHP 7.1.23
**Nextcloud version:** (see Nextcloud admin page)
14.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
from Nextcloud 13
**Where did you install Nextcloud from:**
Get official source
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
"system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "NC DOMAIN",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/NC DOMAIN",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_type": "file",
        "logtimezone": "Asia\/Tokyo",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "auth.bruteforce.protection.enabled": false,
        "versions_retention_obligation": "7,auto",
        "trashbin_retention_obligation": "auto",
        "defaultapp": "calendar",
        "theme": "",
        "updater.release.channel": "stable"
}
```
</details>

### Client configuration
**Browser:**
Vivaildi 2.0, 2.1
**Operating system:**
Windows10 1803

**Comment by Bables55** [comment]
On smartphones, the problem is that characters are not fixed even if characters are entered. For example, although I input 5 characters, only the first one character is definitely entered actually.
Apparently the current version does not seem to use 2-byte characters on Windows(Chromium type) or iPhone/iPad.

**Comment by Bables55** [comment]
I tried other Chromium type browsers. Vivaldi, Canary, Sleipnir. All of them caused problems with 2-byte characters. Firefox has no problem. 2-byte character input on a smartphone is catastrophic.

LOOLWSD 4.0.0 / Collabora Office 6.0-18

**Comment by ixinshang** [comment]
i have the same problems.
Collabora Server 1:Docker version 18.06.1-ce, build e68fc7a   collabora/code:latest
Nextcloud Server 1:Docker version 18.06.0-ce, build 0ffa825  NC15
CentOS Linux release 7.4.1708 (Core)  .10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Bables55** [comment]
Vivaldi has the ability to display web pages in the side panel. There seems NC recognized as a connection with Android, it looks like a mobile version. I can enter 2 byte characters without problems with Collabora's operation with NC in its side panel. Of course, 2 byte characters can not be entered correctly with iPhone.

And this is the same on the demo site of the [Collabora website](https://www.collaboraoffice.com/popup-collabora-online-demo/).

**Comment by ixinshang** [comment]
@Bables55   hi,i create a account from Collabora website.  For chinese, in chrome, it's wrong. i record a gif.https://i.bmp.ovh/imgs/2019/01/a807d4a79346aaa1.gif

**Comment by cedarice** [comment]
The same issuse in Chrome.

**Comment by Bables55** [comment]
I have confirmed that this problem is occurring on "Chromium" based browsers such as Canary and Brave. The only interesting thing is when I displayed NC in Vivaldi's sidebar. Vivaldi is a Chromium based browser. When it is displayed in the sidebar of it, the smartphone mode is set by CSS. Depending on the site, it may be recognized as Android. In this case, the user can normally input 2byte characters. Is there a clue to problem solving here?

The worst is the smartphone. On any browser on the iPhone, the user can only enter 2byte characters for the first single character.

**Comment by juliushaertl** [comment]
Thanks for your bug report. This issue tracker is only targeting the collabora integration inside Nextcloud. Your issue is actually related to Collabora/LibreOffice Online, so please head over to https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online for reporting.
