### ISSUE TITLE
FileServerRequestHandler: File not found: Invalid URI request

### ISSUE THREAD

**Issue by JB1985** [nextcloud/richdocuments#296]
Hi, 

I have try to compile Collabora Online.

Core:  cp-5.3-57
Online: cd-3.4.0-5

loolwsd is starting without error. But If I try to open a document in Nextcloud I see this error in the logs:

wsd-03875-03875 2018-11-04 17:06:15.383923 [ loolwsd ] TRC  Have 1 new children.| wsd/LOOLWSD.cpp:2879
wsd-03875-03875 2018-11-04 17:06:15.383946 [ loolwsd ] INF  WSD initialization complete: setting log-level to [warning] as configured.| wsd/LOOLWSD.cpp:2886
wsd-03875-03888 2018-11-04 17:06:41.846838 [ websrv_poll ] WRN  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/3.4.0/loleaflet.html?WOPISrc=https%3A%2F%2Fmy.nextcloud.xyz%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F156548_oct4xxapqijw&title=sdsd.odt&lang=de-DE&closebutton=1&revisionhistory=1].| wsd/FileServer.cpp:442
wsd-03875-03888 2018-11-04 17:07:04.892675 [ websrv_poll ] WRN  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/3.4.0/loleaflet.html?WOPISrc=https%3A%2F%2Fmy.nextcloud.xyz%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F156546_oct4xxapqijw&title=Neues%20Dokument.odt&lang=de-DE&closebutton=1&revisionhistory=1].| wsd/FileServer.cpp:442

I have try with Nextcloud 13 and Nextcloud 14.

**Comment by JB1985** [comment]
Nobody has an idea?

I have try with cp-5.3.59, too. Same error.

**Comment by danger89** [comment]
Fixed or not? I have also diffuclies to get it working with Nextcloud.

My LibreOffice Online will report similar issues:
```
FileServerRequestHandler: File not found: Invalid URI request
```

Tried all configs:
https://www.collaboraoffice.com/code/nginx-reverse-proxy/

**Comment by danger89** [comment]
Reopen?
