### ISSUE TITLE
Request: Page Numbers

### ISSUE THREAD

**Issue by Starcr0ss** [nextcloud/richdocuments#2973]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I think that having page numbers is an important component of a word processor/office suite and is missing from Nextcloud office

**Describe the solution you'd like**
Allow adding page numbers to documents, and having the "Different first page" subfeature

**Describe alternatives you've considered**
Typing in page numbers manually (though these do not automatically add per new page), or using other office suites

**Additional context**

**Comment by juliushaertl** [comment]
Nextcloud Office is based on Collabora Online so any features regarding office editing itself would need to be done there. Could you please open a feature request in https://github.com/collaboraonline/online for taht?
