### ISSUE TITLE
Stop usage of ``\OCP\AppFramework\Http\EmptyContentSecurityPolicy::allowInlineScript`` 

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/richdocuments#2979]
**Describe the bug**

``\OCP\AppFramework\Http\EmptyContentSecurityPolicy::allowInlineScript`` was deprecated in Nextcloud 10. It will be removed soon.

**To Reproduce**

See code

**Expected behavior**

Good code

**Screenshots**

![image](https://github.com/nextcloud/richdocuments/assets/1374172/8170a1e0-4a63-42a2-8649-fa95ac6116fb)

**Client details:**
 - Device: [e.g. iPhone6, desktop]

## Server details

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:**

**Version of the richdocuments app**

**Version of Collabora Online**

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
Preliminary work should have been done with #2258
