### ISSUE TITLE
Create specific authentication page for admins on a different port for added security on a wan situation.

### ISSUE THREAD

**Issue by astrometrics** [nextcloud/richdocuments#2980]
**Is your feature request related to a problem? Please describe.**

Admins can log on on wan... that's a bit problematic.

**Describe the solution you'd like**

Separation of login pages from normal users and admins. Admins can log on to a different port, which could be better managed by firewalls, increasing security greatly I think. This solution may have an appeal to organizations or anyone really focused on security.
That should be easy as an admin config or config.php admin port setting. If admin_port is omitted then same port as normal user is used.

**Describe alternatives you've considered**

**Additional context**

**Comment by juliushaertl** [comment]
This feature request doesn't seem related to the richdocuments app itself so please file it at https://github.com/nextcloud/server/ instead :)
