### ISSUE TITLE
js ignore window.location.port

### ISSUE THREAD

**Issue by CoachRun** [nextcloud/richdocuments#2981]
**Describe the bug**
If I try to use a port other than the default web port, it won't work

**To Reproduce**
1. Click on 'some.docs'
2. See white screen error
```
server port: 8899
but js request
https://netdisk.xxxxx.com/custom_apps/richdocumentscode/proxy.php?status
```

**Expected behavior**
```
js request
https://netdisk.xxxxx.com:8899/custom_apps/richdocumentscode/proxy.php?status
```

**Client details:**
 - OS: Windows 10
 - Browser: Edge
 - Version: 113.0.1774.57
 - Device: desktop

## Server details

**Operating system**:
Linux

**Web server:**
Docker

**Database:**
Postgres 14.8

**PHP version:** 
8.1.19

**Nextcloud version:** 
26.0.1

**Version of the richdocuments app**
8.0.2

**Version of Collabora Online**built-in server
 22.5.1301

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
None yet.
```

#### Browser log
```
Refused to connect to 'https://netdisk.xxxxx.com/custom_apps/richdocumentscode/proxy.php?status' because it violates the following Content Security Policy directive: "connect-src 'self' blob: stun.nextcloud.com:443".
```

</details>

**Comment by juliushaertl** [comment]
Can you try the following:

- Go to the office admin setttings and select "Use your own server"
- Check if the url (which should point to proxy.php) contains the custom port
- if not, add the port there and save

**Comment by CoachRun** [comment]
Collabora Online - Built-in CODE Server installed

follow the step
- select "Use your own server"
- add the port
- save

but, always sets up the "built server" option for me automatically

**Comment by juliushaertl** [comment]
Yes, but the url should get updated. Is there an difference then when opening a document?

**Comment by CoachRun** [comment]
there is no difference, there are the same problems

**Comment by juliushaertl** [comment]
This should be fixed these days with the server_name from collabora properly being picked up.
