### ISSUE TITLE
Default blank document file is in US letter, all other ones in DIN A4

### ISSUE THREAD

**Issue by JMoVS** [nextcloud/richdocuments#2983]
**Describe the bug**
The default blank template .docx is in US letter format, but the default .ott and .odt files are all in DIN A4 - I think the format should be DIN A4 as default or at least allow an easy switch

**To Reproduce**
Create a new document, observe layout to be US letter.

**Expected behavior**
One has to manually adjust the template in the app directory to change that to DIN A4 - I hope it survives an update but I'm not even sure about that.

**Screenshots**

**Client details:**
 - Browser Firefox
 - Device: [e.g. iPhone6, desktop]

## Server details

**Operating system**:
Ubuntu
**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:**
26.0.2
**Version of the richdocuments app**
8.0.2
**Version of Collabora Online**
latest CODE

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by JMoVS** [comment]
@juliushaertl Do you want me to create a pull request to fix this?

**Comment by juliushaertl** [comment]
@pedropintosilva Can you tell if there is a way to make the template dynamically adjust the page size maybe depending on what is most common in the users region?

**Comment by JMoVS** [comment]
happy to provide a pull request to make all consistent - I don't know how to solve the dynamic case though

**Comment by juliushaertl** [comment]
This should also be addressed by https://github.com/nextcloud/richdocuments/pull/3059 @JMoVS If you are up for testing the patch, feedback is much appreciated :)

**Comment by JMoVS** [comment]
earliest on the weekend - how could I test this? And can I test this on nextcloud 26?

**Comment by bbx-github** [comment]
> The default blank template .docx is in US letter format

True - and if it is in DIN A4 it would solve my problem as well.

But `.docx` is not a template format. A template has `.dotx`. Such a file is missing in `richdocuments/emptyTemplates`. The naming scheme suggests a name `document.dotx` Using this template format may set the page format according to the locale? And is needed to make https://github.com/nextcloud/richdocuments/pull/3059 work for ooxml?

**Comment by JMoVS** [comment]
@juliushaertl Not sure but right now, new documents are created in US letter again now that I upgraded to the latest version. I think this should be reopened
