### ISSUE TITLE
No App icon after install

### ISSUE THREAD

**Issue by Yetangitu** [nextcloud/richdocuments#3]
After installing (tried both current github as well as latest release, on both NC 11.0 as well as current github), no new icon appears in the menu. The (admin) settings page does work, the app is shown as being 'enabled' but it does not work.
Manually navigating to NC_BASE_ADDRESS/index.php/apps/richdocuments/index does not work either ('no app in context' in log, CSRF check failed in UI).

**Comment by Bubbelb** [comment]
I can confirm this bug. My setup is as follows:
- NginX Installment (plain http) on one server
- Server also runs the docker container for Collabora
- Nextcloud 11 installed in the webroot
- Separate read/write app folder outside of the nextcloud folder structure.
- Reverse NginX proxy set for Collabora docker instance
- Database is MariaDB

All this is behind a reverse NginX proxy, that is serving the site using https and Nextcloud is published under a subfolder.
Nextcloud is functioning well, as it did for a while. Only the icon refuses to appear, although the Collabora app is installed.

Tried the following, all failed:
- Disable, Uninstall and then Reinstall app
- Disable and Uninstall the app. Then remove any 'richdocuments' fields from the database and then reinstall.

**Comment by victorbw** [comment]
dito here, no app-icon available nor am i able to open any documents directly through file-app (which worked nicely before).

by opening the file through the file-app, ill get a "zugriff verboten"/"access denied".

system:

- ubuntu 16.04x64 lts
- php7.0
- apache2 2.4.18
- mysql 5.7.16
- redis-cache 3.0

**Comment by sotor-rus** [comment]
I have the same bug.

**Comment by LukasReschke** [comment]
The app icon and menu in the top left has been removed as it doesn't provide any benefit except massively slowing down the application when opening files etc.

If you want to open Office documents just click on them in the files list.

cc @jancborchardt

**Comment by victorbw** [comment]
well, im not sure if it really works properly, but im having still an issue there.

when i try to open them as youve told @LukasReschke , ill simply get an error "access denied". Now I'm either unaware what has changed or it's missing in the documentation.

a hint anyone?

**Comment by LukasReschke** [comment]
@victorbw Can you please file a new issue for that? THX.

**Comment by Bubbelb** [comment]
Ahh. Thanks. Mised that one...

**Comment by victorbw** [comment]
someone was faster than i: https://github.com/nextcloud/richdocuments/issues/4
