### ISSUE TITLE
Editors in top bar should show readonly status

### ISSUE THREAD

**Issue by rullzer** [nextcloud/richdocuments#300]
It would be nice if we somehow indicate which users can edit and which can only read a document.

Currently all users are created equally in the editor list (in the header).

CC: @juliushaertl

**Comment by juliushaertl** [comment]
Probably the easiest way of displaying would be to give read only users avatars a bit of opacity and add a (read access) to the tooltip. @nextcloud/designers

**Comment by rullzer** [comment]
Would be fine by me for a first iteration :+1:
