### ISSUE TITLE
Snap Couldn't find coolwsd.xml file, unable to add font

### ISSUE THREAD

**Issue by PuZhiweizuishuai** [nextcloud/richdocuments#3006]
**Describe the bug**
I deployed Nextcloud using snap and when trying to add fonts, I couldn't locate the coolwsd.xml file in the system to modify remote_font_config. How can I solve this problem?

**To Reproduce**
1. There is a temporal coolwsd.xml file but no obvious solution how to make a permanent change to it.

2.run

```
find / -name "coolwsd.xml"
```
3.result

```
/tmp/appimage_extracted_<hex-id>/etc/coolwsd/coolwsd.xml
```

**Client details:**
 - OS:   Windows10
 - Browser Edge 1114.0.1823.41 

## Server details

**Operating system:**  Ubuntu 20.04.6 LTS

**Nextcloud version:** 25.0.6 

**Version of the richdocuments app:** 7.1.4

**Version of Collabora Online:** 22.5.1301

**Comment by joshtrichards** [comment]
Hi @PuZhiweizuishuai: This repository covers only the Nextcloud integration app which requires a Collabora Online server to connect to. It sounds like you're trying to customize the Collabore Online server from the Built-in CODE Server app. The correct repository is:

  https://github.com/CollaboraOnline/richdocumentscode

Also you're using it in a Snap which adds an additional layer of complexity to things.

These may be relevant to your situation:

https://github.com/CollaboraOnline/richdocumentscode/issues/121
https://github.com/nextcloud-snap/nextcloud-snap/issues/1628

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/richdocuments/issues/2763

**Comment by joshtrichards** [comment]
Let's consolidate tracking this into #2763.

The *Built-in Collabora Online Server* (richdocumentscode) supports loading the fonts list remotely from the Nextcloud Office app when they are set and uploaded via the *Admin Settings* ->  _Office_ page. So there is no need to edit this file.
