### ISSUE TITLE
DOS Attack causes 100% CPU usage

### ISSUE THREAD

**Issue by theAkito** [nextcloud/richdocuments#3009]
**Describe the bug**
100% CPU usage out of nothing, due to this app. After disabling it inside Nextcloud & force killing it on the OS, the CPU usage went down.

The high CPU usage was caused by an infinite spam of `POST` request onto the reverse proxy, which couldn't handle this DOS attack.

**To Reproduce**
Unknown. I've just noticed the high CPU usage & have proven, without any doubt, that this app is responsible for it.

**Expected behavior**
CPU usage should stay normal, i.e. no `POST` requests should be infinitely spammed onto the reverse proxy.

**Comment by joshtrichards** [comment]
Hi @theAkito - Thank you for your report. Unfortunately it lacks sufficient detail. Can you provide logs of these POST requests towards your reverse proxy?

Also can you provide a few more details about your setup/environment: NC version, NC installation method, richdocuments version, what Collabora service/install method you're using, etc.

Are you Nextcloud Office or did it just happen to be installed?

**Comment by theAkito** [comment]
Greetings @joshtrichards,


thank you for your interest in this issue. 🙂

This happened a while ago & I need to research the logs, that I have noted somewhere. I can also provide you with those version information, since nothing changed since then.

> Are you Nextcloud Office or did it just happen to be installed?

The `richdocuments` app was probably manually installed by someone, if that's what you mean.



I'll get back with the requested information. 😃
