### ISSUE TITLE
In "compact view" selected toolbar icons stay black in front of dark blue

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/richdocuments#3021]
**Describe the bug**
As of version 23.05.0.5 of COOLWSD when selecting a menu item, the selected menu item uses dark a blue background with black text colour. Before the text color was white and not black.

The same applies to the headers of the selected column and row in spreadsheets.

**To Reproduce**
Open the application, hover menu items.

Open a spreadsheet for editing and navigate within it.

**Expected behavior**
Text of selected menu items or spreadsheet headers is white as it was before in version 22.

**Screenshots**
![image](https://github.com/nextcloud/richdocuments/assets/6613614/ad804678-fd86-4df0-aefe-d09c2d38b9d1)

**Client details:**
 - OS: Windows 10 Pro x64
 - Browser: Vivaldi, Firefox, Edge, Safari - tested in several browsers, happens in all of them
 - Version: several version (Vivaldi 6.1.3035.84 (Stable channel) (64-Bit), Firefox 113.0 etc.) - happens in all of them
 - Device: Desktop

## Server details

**Operating system**

Ubuntu 22.04

**Web server**

Apache

**Database**

MariaDB

**PHP version**

 8.1.20

**Nextcloud version**

 26.0.2

**Version of the richdocuments app**

 8.0.2

**Version of Collabora Online**

23.05.0.5

#### Nextcloud log (data/nextcloud.log)

(not relevant)

#### Browser log

(not relevant)

</details>

**Comment by arnowelzel** [comment]
After upgrading Nextcloud to version 27.0.0 the app is now completely different. Now it uses a "ribbon" style menu and no longer drop down menus. It seems the upgrade also installed a new version of the Nextcloud Office app which is now version 8.1.0 instead of 8.0.2.

Ok, problem somewhat solved. However this is quite confusing since using Nextcloud 27.0.0 is not mandatory to use Nextcloud Office.

**Comment by arnowelzel** [comment]
Hmm... when I now open a document, I suddenly get the older UI again. Very confusing, really...

![image](https://github.com/nextcloud/richdocuments/assets/6613614/d6846117-3ac6-4f30-9420-74ca9555c2c4)

**Comment by arnowelzel** [comment]
Ok, got it. You can switch between the new and old UI.

**Comment by joshtrichards** [comment]
All good now? Okay to close this?

**Comment by arnowelzel** [comment]
There is still an issue with the toolbar icons.

In the "compact view" the selected icons stay black in front of dark blue:

![image](https://github.com/nextcloud/richdocuments/assets/6613614/65680052-a235-45b7-a393-bc7d161f8819)

However in the new "tab view" the selected icons are brighter which makes it much easier to recognize them:

![image](https://github.com/nextcloud/richdocuments/assets/6613614/447ed83c-4fe6-4ff7-b1c1-0f51be87743f)

**Comment by juliushaertl** [comment]
Thanks for the update, can reproduce an will prepare a fix for that

Note for myself:

```css
/* branding.css | /browser/5093121/nextcloud/branding.css */

.w2ui-toolbar table.w2ui-button.checked .w2ui-tb-image {
  filter: var(--nc-primary-invert-if-dark);
}
```

**Comment by juliushaertl** [comment]
This has now been fixed with the latest Collabora release

**Comment by sebastiaanveld** [comment]
Tested and looks fixed. Issue can be closed, agree @arnowelzel?

![image](https://github.com/nextcloud/richdocuments/assets/37268999/68824d27-8cbc-4d4d-8968-1f87f5b72314)

![image](https://github.com/nextcloud/richdocuments/assets/37268999/7bad54cc-c663-4876-86f1-b805c5905ef9)


COOLWSD version: 23.05.7.2 (git hash: f76e08a (E))
LOKit version: Collabora Office 23.05.7.2 (git hash: 6d9d5d1)
Served by: Debian GNU/Linux 12 (bookworm)
Server ID: c31b1370

**Comment by arnowelzel** [comment]
Agree 👍
