### ISSUE TITLE
"read-only" banner on editable documents

### ISSUE THREAD

**Issue by Stooovie** [nextcloud/richdocuments#3025]
**Describe the bug**
On mobile, Nextcloud Office displays a "read-only" banner up top the editor UI even when the file is editable. It leads to confusion and frustration trying to fix an issue that doesn't really exist.

**To Reproduce**
1. open an .odt file in Nextcloud for iPhone
2. there's a "read-only" banner visible, but the document can be edited and saved without any issues

**Expected behavior**
Read-only should be visible only on actual read-only documents

**Screenshots**
![IMG_51ED4D8C9CAD-1](https://github.com/nextcloud/richdocuments/assets/10572373/adb4f1bd-2a64-4cd3-a47a-9af93c7ff2a9)

and here's a video
https://nc.jirifiala.cz/s/492EC4FW3boaBGn

**Client details:**
 - OS: iOS 16.6
 - Nextcloud app 4.8.3
 - Nextcloud v 27 (Nextcloud AIO v6.1.1)
 - Device: iPhone 11 Pro

**Comment by juliushaertl** [comment]
Can you file this issue at Collabora Online itself as this part is handled in the repo at https://github.com/collaboraonline/online

Thanks a lot :)
