### ISSUE TITLE
App doesn't work on a fresh Installation

### ISSUE THREAD

**Issue by KaeTuuN** [nextcloud/richdocuments#3026]
**Describe the bug**
I can't edit any document.
New Documents are created, editing is not possible.

Installed NC 27 from scratch, installed apps with:
sudo -u www-data /-path-to-php- /-path-to-nc-/occ app:install richdocuments
sudo -u www-data /-path-to-php- /-path-to-nc-/occ app:install richdocumentscode

**To Reproduce**
1. Login
2. Try to open any document
3. Wait for timeout
4. See error (screenshot)
5. Completly loose connection to the webinterface until timeout (45 Seconds)

**Expected behavior**
I can open and edit documents.

**Screenshots**
![Bildschirmfoto vom 2023-06-19 18-30-03](https://github.com/nextcloud/richdocuments/assets/10331843/a92eea01-8c71-4f43-a505-32aec94866c9)

**Client details:**
 - OS: Newest Nobara Linux
 - Browser: Firefox
 - Version: 113
 - Device: desktop

## Server details

**Operating system**: Ubuntu Server 22.04 LTS
**Web server:**  Nginx 
**Database:** MariaDB 10.11
**PHP version:** 8.1.4
**Nextcloud version:** 27.0.0.8
**Version of the richdocuments app:** 8.1.0
**Version of Collabora Online:** 23.5.5

<details>
<summary>Logs
</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"RaaQ2gyDsK6IdAUf9lv6","level":3,"time":"2023-06-19T18:09:30+02:00","remoteAddr":"-IP-filtered-","user":"Testadmin","app":"PHP","method":"GET","url":"/apps/richdocuments/index?fileId=228&requesttoken=x%2Bj2C%2B2GA1GS4lUTJSGU7ma7Dl2GC%2FkM9tCVOFyYSN4%3D%3AtamMeLfKewmjoxlKblTNv1PLOxLLaohAxqjyUy3iEaw%3D&path=%2Ftest.odt","message":"Trying to access array offset on value of type null at /-path-to-nc-/apps/richdocuments/lib/WOPI/DiscoveryManager.php#130","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0","version":"27.0.0.8","data":{"app":"PHP"}}
{"reqId":"RaaQ2gyDsK6IdAUf9lv6","level":3,"time":"2023-06-19T18:09:30+02:00","remoteAddr":"-IP-filtered-","user":"Testadmin","app":"PHP","method":"GET","url":"/apps/richdocuments/index?fileId=228&requesttoken=x%2Bj2C%2B2GA1GS4lUTJSGU7ma7Dl2GC%2FkM9tCVOFyYSN4%3D%-path-to-nc-/www/nc_test/apps/richdocuments/lib/WOPI/DiscoveryManager.php#131","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0","version":"27.0.0.8","data":{"app":"PHP"}}
{"reqId":"RaaQ2gyDsK6IdAUf9lv6","level":3,"time":"2023-06-19T18:09:30+02:00","remoteAddr":"-IP-filtered-","user":"Testadmin","app":"PHP","method":"GET","url":"/apps/richdocuments/index?fileId=228&requesttoken=x%2Bj2C%2B2GA1GS4lUTJSGU7ma7Dl2GC%2FkM9tCVOFyYSN4%3D%3AtamMeLfKewmjoxlKblTNv1PLOxLLaohAxqjyUy3iEaw%3D&path=%2Ftest.odt","message":"Trying to access array offset on value of type null at /-path-to-nc-/apps/richdocuments/lib/WOPI/DiscoveryManager.php#132","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0","version":"27.0.0.8","data":{"app":"PHP"}}
{"reqId":"RaaQ2gyDsK6IdAUf9lv6","level":3,"time":"2023-06-19T18:10:15+02:00","remoteAddr":"-IP-filtered-","user":"Testadmin","app":"richdocuments","method":"GET","url":"/apps/richdocuments/index?fileId=228&requesttoken=x%2Bj2C%2B2GA1GS4lUTJSGU7ma7Dl2GC%2FkM9tCVOFyYSN4%3D%3AtamMeLfKewmjoxlKblTNv1PLOxLLaohAxqjyUy3iEaw%3D&path=%2Ftest.odt","message":"cURL error 28: Operation timed out after 45000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://-domain-removed-/apps/richdocumentscode/proxy.php?req=/hosting/discovery","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0","version":"27.0.0.8","exception":{"Exception":"GuzzleHttp\\Exception\\ConnectException","Message":"cURL error 28: Operation timed out after 45000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://-domain-removed-/apps/richdocumentscode/proxy.php?req=/hosting/discovery","Code":0,"Trace":[{"file":"/-path-to-nc-/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":158,"function":"createRejection","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/-path-to-nc-/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":110,"function":"finishError","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::"},{"file":"/-path-to-nc-/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php","line":47,"function":"finish","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::"},{"file":"/-path-to-nc-/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":137,"function":"__invoke","class":"GuzzleHttp\\Handler\\CurlHandler","type":"->"},{"file":"/-path-to-nc-/lib/private/Http/Client/DnsPinMiddleware.php","line":114,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/-path-to-nc-/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php","line":35,"function":"OC\\Http\\Client\\{closure}","class":"OC\\Http\\Client\\DnsPinMiddleware","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/-path-to-nc-/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":31,"function":"__invoke","class":"GuzzleHttp\\PrepareBodyMiddleware","type":"->"},{"file":"/-path-to-nc-/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php","line":71,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/-path-to-nc-/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":63,"function":"__invoke","class":"GuzzleHttp\\RedirectMiddleware","type":"->"},{"file":"/-path-to-nc-/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php","line":75,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/-path-to-nc-/3rdparty/guzzlehttp/guzzle/src/Client.php","line":331,"function":"__invoke","class":"GuzzleHttp\\HandlerStack","type":"->"},{"file":"/-path-to-nc-/3rdparty/guzzlehttp/guzzle/src/Client.php","line":168,"function":"transfer","class":"GuzzleHttp\\Client","type":"->"},{"file":"/-path-to-nc-/3rdparty/guzzlehttp/guzzle/src/Client.php","line":187,"function":"requestAsync","class":"GuzzleHttp\\Client","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/-path-to-nc-/lib/private/Http/Client/Client.php","line":226,"function":"request","class":"GuzzleHttp\\Client","type":"->"},{"file":"/-path-to-nc-/apps/richdocuments/lib/WOPI/DiscoveryManager.php","line":89,"function":"get","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/-path-to-nc-/apps/richdocuments/lib/WOPI/DiscoveryManager.php","line":61,"function":"fetchFromRemote","class":"OCA\\Richdocuments\\WOPI\\DiscoveryManager","type":"->"},{"file":"/-path-to-nc-/apps/richdocuments/lib/WOPI/Parser.php","line":41,"function":"get","class":"OCA\\Richdocuments\\WOPI\\DiscoveryManager","type":"->"},{"file":"/-path-to-nc-/apps/richdocuments/lib/TokenManager.php","line":207,"function":"getUrlSrc","class":"OCA\\Richdocuments\\WOPI\\Parser","type":"->"},{"file":"/-path-to-nc-/apps/richdocuments/lib/Controller/DocumentController.php","line":181,"function":"getToken","class":"OCA\\Richdocuments\\TokenManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/-path-to-nc-/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"index","class":"OCA\\Richdocuments\\Controller\\DocumentController","type":"->"},{"file":"/-path-to-nc-/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/-path-to-nc-/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/-path-to-nc-/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/-path-to-nc-/lib/base.php","line":1064,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/-path-to-nc-/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/-path-to-nc-/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","Line":210,"CustomMessage":"--"}}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
> cURL error 28: Operation timed out after 45000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://-domain-removed-/apps/richdocumentscode/proxy.php?req=/hosting/discovery

Can you please check if this URL is reachable from your Nextcloud server e.g. using curl?

In addition you could check https://-domain-removed-/apps/richdocumentscode/proxy.php?status

**Comment by KaeTuuN** [comment]
| Link | From Server | From Client | Answer |
| --- | --- | --- | --- |
| https://test.wellmann.wtf/apps/richdocumentscode/proxy.php?req=/hosting/discovery | not reachable | not reachable | Timeout |
| https://test.wellmann.wtf/apps/richdocumentscode/proxy.php?status | reachable | reachable | {"status":"starting"} |

**Comment by juliushaertl** [comment]
You could check the PHP/Webserver error log, maybe you can even comment out the line in https://github.com/CollaboraOnline/richdocumentscode/blob/f38391684ef732fee7141697fbaad32b1c4f321e/proxy.php#L24 to get more verbose information about the launch of the richdocumentscode app.

**Comment by juliushaertl** [comment]
Other than that maybe @timar can give a hint if there is a way to get the coolwsd log on richdocumentscode

**Comment by KaeTuuN** [comment]
php log doesn't give any useful information.
nginx error log however has lots entries like this one:
```
2023/06/20 12:43:49 [error] 3673#3673: *10605 FastCGI sent in stderr: "PHP message: richdocumentscode (proxy.php) error exit, PID: 4142, Message: The param should be 'status' or 'req=...', but is: ''" while reading upstream, client: -IP-removed-, server: -Server-removed-, request: "GET /apps/richdocumentscode/proxy.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "-Domain-removed-"
```

**Comment by Hoerli1337** [comment]
Got the same error.
- nginx
- php8.1
- MariaDB

With NextCloud 27 the Office app does not work at all anymore.
Have now 3 instances where now Office does not work anymore.
Have already checked the php config and nginx config but found no errors.
Until version 26 everything worked with php8.0.

**Comment by Hoerli1337** [comment]
@KaeTuuN Unfortunately not so fast, because I have to install a new instance for this.

**Comment by Artens** [comment]
Any updates so far? I've been looking at blank screens for several months.

**Comment by Arbel-arad** [comment]
i am getting this error after updating to version 27.0.1.
this is with nextcloud AIO 6.3.0 and the collabora container is enabled. i also tried using the demo servers but they give the same error.
![image](https://github.com/nextcloud/richdocuments/assets/65590498/2bde9ddc-f078-4ebe-a71c-3279162bfc5a)

the collabora container keeps repeating these errors:
```
wsd-00001-00022 2023-07-14 13:23:53.527758 +0300 [ remotefontconfig_poll ] ERR  Remote config server has response status code: Bad Gateway| wsd/COOLWSD.cpp:1174
wsd-00001-00022 2023-07-14 13:24:53.591684 +0300 [ remotefontconfig_poll ] ERR  Remote config server has response status code: Bad Gateway| wsd/COOLWSD.cpp:1174
wsd-00001-00022 2023-07-14 13:25:53.656222 +0300 [ remotefontconfig_poll ] ERR  Remote config server has response status code: Bad Gateway| wsd/COOLWSD.cpp:1174
wsd-00001-00022 2023-07-14 13:26:53.709208 +0300 [ remotefontconfig_poll ] ERR  Remote config server has response status code: Bad Gateway| wsd/COOLWSD.cpp:1174
wsd-00001-00022 2023-07-14 13:27:53.771380 +0300 [ remotefontconfig_poll ] ERR  Remote config server has response status code: Bad Gateway| wsd/COOLWSD.cpp:1174
wsd-00001-00024 2023-07-14 13:29:17.103135 +0300 [ websrv_poll ] ERR  unknown UI default's component UITheme| wsd/FileServerUtil.cpp:99
frk-00019-00019 2023-07-14 13:29:17.472786 +0300 [ forkit ] WRN  The systemplate directory [/opt/cool/systemplate] is read-only, and at least [/opt/cool/systemplate//etc/hosts] is out-of-date. Will have to copy sysTemplate to jails. To restore optimal performance, make sure the files in [/opt/cool/systemplate/etc] are up-to-date.| common/JailUtil.cpp:519
sh: 1: /usr/bin/coolmount: Operation not permitted
sh: 1: /usr/bin/coolmount: Operation not permitted
sh: 1: /usr/bin/coolmount: Operation not permitted
```

**Comment by KaeTuuN** [comment]
@joshtrichards
`cat: '/tmp/coolwsd.*/coolwsd.log': No such file or directory`
Under /tmp I just have coolwsd.pid

**Comment by n-greene** [comment]
I am having a similar problem since V27 and updating Nextcloud Office and CODE Server to latest versions
[Nextcloud Office.pdf](https://github.com/nextcloud/richdocuments/files/12111892/Nextcloud.Office.pdf)

**Comment by EmJotGeh** [comment]
Same here, new install NC 27.02 - it's not possible to open/create/modify a document.

**Comment by JohnFarl** [comment]
I have problems with latest version too. In my case the editing and creation works but are logged nonstop errors related to ```
[GuzzleHttp\Exception error](https://help.nextcloud.com/t/nextcloud-collabora-guzzlehttp-exception-error/151995)
`[proxy.php?req=/hosting/capabilities`](http://localhost/nextcloud/apps/richdocumentscode/proxy.php?req=/hosting/capabilities%60)`
```

**Comment by solarisfire** [comment]
Brand new install having issues here too...

Can create documents. But it just hangs when going to edit them...

WOPI is set to 0.0.0.0/0

https://***/apps/richdocumentscode/proxy.php?status returns:

status | "starting"
-- | --

Logs are unhelpful...

<pre>
Error   richdocuments   GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 45000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for   2023-10-28T12:47:16+00:00  
                          https://***/apps/richdocumentscode/proxy.php?req=/hosting/discovery at .../guzzlehttp/guzzle/src/Handler/CurlFactory.php line 210                                                            
                                                                                                                                                                                                                                             
                           0. 3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 158                                                                                                                                                
                              GuzzleHttp\Handler\CurlFactory::createRejection("*** sensitive parameters replaced ***")                                                                                                                       
                           1. 3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 110                                                                                                                                                
                              GuzzleHttp\Handler\CurlFactory::finishError(                                                                                                                                                                   
                                                                                                                                                                                                                                             
                              )                                                                                                                                                                                                              
                           2. 3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php line 47                                                                                                                                                 
                              GuzzleHttp\Handler\CurlFactory::finish(                                                                                                                                                                        
                                                                                                                                                                                                                                             
                              )                                                                                                                                                                                                              
                           3. 3rdparty/guzzlehttp/guzzle/src/Middleware.php line 137                                                                                                                                                         
                              GuzzleHttp\Handler\CurlHandler->__invoke(                                                                                                                                                                      
                                                                                                                                                                                                                                             
                              )                                                                                                                                                                                                              
                           4. lib/private/Http/Client/DnsPinMiddleware.php line 114                                                                                                                                                          
                              GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")                                                                                                                           
                           5. 3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php line 35                                                                                                                                               
                              OC\Http\Client\DnsPinMiddleware->OC\Http\Client\{closure}("*** sensitive parameters replaced ***")                                                                                                             
                           6. 3rdparty/guzzlehttp/guzzle/src/Middleware.php line 31                                                                                                                                                          
                              GuzzleHttp\PrepareBodyMiddleware->__invoke(                                                                                                                                                                    
                                                                                                                                                                                                                                             
                              )                                                                                                                                                                                                              
                           7. 3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php line 71                                                                                                                                                  
                              GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")                                                                                                                           
                           8. 3rdparty/guzzlehttp/guzzle/src/Middleware.php line 63                                                                                                                                                          
                              GuzzleHttp\RedirectMiddleware->__invoke(                                                                                                                                                                       
                                                                                                                                                                                                                                             
                              )                                                                                                                                                                                                              
                           9. 3rdparty/guzzlehttp/guzzle/src/HandlerStack.php line 75                                                                                                                                                        
                              GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")                                                                                                                           
                          10. 3rdparty/guzzlehttp/guzzle/src/Client.php line 331                                                                                                                                                             
                              GuzzleHttp\HandlerStack->__invoke(                                                                                                                                                                             
                                                                                                                                                                                                                                             
                              )                                                                                                                                                                                                              
                          11. 3rdparty/guzzlehttp/guzzle/src/Client.php line 168                                                                                                                                                             
                              GuzzleHttp\Client->transfer(                                                                                                                                                                                   
                                                                                                                                                                                                                                             
                              )                                                                                                                                                                                                              
                          12. 3rdparty/guzzlehttp/guzzle/src/Client.php line 187                                                                                                                                                             
                              GuzzleHttp\Client->requestAsync("*** sensitive parameters replaced ***")                                                                                                                                       
                          13. lib/private/Http/Client/Client.php line 230                                                                                                                                                                    
                              GuzzleHttp\Client->request(                                                                                                                                                                                    
                                                                                                                                                                                                                                             
                              )                                                                                                                                                                                                              
                          14. apps/richdocuments/lib/WOPI/DiscoveryManager.php line 89                                                                                                                                                       
                              OC\Http\Client\Client->get(                                                                                                                                                                                    
                                                                                                                                                                                                                                             
                              )                                                                                                                                                                                                              
                          15. apps/richdocuments/lib/WOPI/DiscoveryManager.php line 61                                                                                                                                                       
                              OCA\Richdocuments\WOPI\DiscoveryManager->fetchFromRemote(                                                                                                                                                      
                                                                                                                                                                                                                                             
                              )                                                                                                                                                                                                              
                          16. apps/richdocuments/lib/WOPI/Parser.php line 41                                                                                                                                                                 
                              OCA\Richdocuments\WOPI\DiscoveryManager->get(                                                                                                                                                                  
                                                                                                                                                                                                                                             
                              )                                                                                                                                                                                                              
                          17. apps/richdocuments/lib/TokenManager.php line 316                                                                                                                                                               
                              OCA\Richdocuments\WOPI\Parser->getUrlSrc(                                                                                                                                                                      
                                                                                                                                                                                                                                             
                              )                                                                                                                                                                                                              
                          18. apps/richdocuments/lib/Controller/DocumentController.php line 387                                                                                                                                              
                              OCA\Richdocuments\TokenManager->getUrlSrc(                                                                                                                                                                     
                                                                                                                                                                                                                                             
                              )                                                                                                                                                                                                              
                          19. lib/private/AppFramework/Http/Dispatcher.php line 230                                                                                                                                                          
                              OCA\Richdocuments\Controller\DocumentController->token(                                                                                                                                                        
                                                                                                                                                                                                                                             
                              )                                                                                                                                                                                                              
                          20. lib/private/AppFramework/Http/Dispatcher.php line 137                                                                                                                                                          
                              OC\AppFramework\Http\Dispatcher->executeController(                                                                                                                                                            
                                                                                                                                                                                                                                             
                              )                                                                                                                                                                                                              
                          21. lib/private/AppFramework/App.php line 183                                                                                                                                                                      
                              OC\AppFramework\Http\Dispatcher->dispatch(                                                                                                                                                                     
                                                                                                                                                                                                                                             
                              )                                                                                                                                                                                                              
                          22. lib/private/Route/Router.php line 315                                                                                                                                                                          
                              OC\AppFramework\App::main(                                                                                                                                                                                     
                                                                                                                                                                                                                                             
                              )                                                                                                                                                                                                              
                          23. lib/base.php line 1068                                                                                                                                                                                         
                              OC\Route\Router->match(                                                                                                                                                                                        
                                                                                                                                                                                                                                             
                              )                                                                                                                                                                                                              
                          24. index.php line 36                                                                                                                                                                                              
                              OC::handleRequest(                                                                                                                                                                                             
                                                                                                                                                                                                                                             
                              ) 
</pre>

**Comment by navennn** [comment]
Hi
I have a similar issue, except it's trying to load wrong endpoint

```
GuzzleHttp\Exception\ClientException: Client error: `GET https://nxt.example.org/nextcloud/apps/richdocumentscode/proxy.php?req=/hosting/capabilities` resulted in a `404 Not Found` response: <!DOCTYPE html> <html class="ng-csp" data-placeholder-focus="false" lang="en" data-locale="en" translate="no" > <head (truncated...)
```

if I curl this, it results

```
	(...)	<h2>Page not found</h2>
		<p class="infogroup">The page could not be found on the server or you may not be allowed to view it.</p>
(...)
```

The correct one is 
https://nxt.example.org/apps/richdocumentscode/proxy.php?req=/hosting/capabilities

```
 curl -k https://nxt.example.org/apps/richdocumentscode/proxy.php?req=/hosting/capabilities
{"convert-to":{"available":true,"endpoint":"/cool/convert-to"},"hasMobileSupport":true,"hasProxyPrefix":true,"hasTemplateSaveAs":false,"hasTemplateSource":true,"hasZoteroSupport":true,"productName":"Collabora Online Development Edition","productVersion":"23.05.5.3","productVersionHash":"5093121","serverId":"e1eb026b"}
```

How can I change this endpoint?

**Comment by juliushaertl** [comment]
You should be able to switch to the use your own server setting and adjust the URL.

**Comment by navennn** [comment]
But to do that, I need to choose the first option ( from the screenshot), which I don't have?

**Comment by FlowSem** [comment]
I have the same problem.
After installing the "richdocuments" app, either via web or cli renders the nextcloud instance unusable.
Removing the app via cli again instantly fixes the problem....

**Comment by halmich** [comment]
I've got the same problem over here.
In addition, I've got the following error in apache2 error.log
` richdocumentscode (proxy.php) error exit, PID: 99418, Message: The param should be 'status' or 'req=...', but is: 'ui_theme=light'`
`richdocumentscode (proxy.php) error exit, PID: 99394, Message: No content in reply from coolwsd. Is SSL enabled in error ?`

**Comment by joshtrichards** [comment]
There are at least ~4 completely different scenarios in this Issue, several of which are configuration/environment matters. The rest (including OP's matter) appear to be issues with `richdocumentscode` (which is not this app). I suggest troubleshooting via the help forums (we're not equipped to do one-on-one troubleshooting here).

So please take follow-up here: https://help.nextcloud.com/

If after troubleshooting there appears to be a probable bug, the reporting channel for the *Built-in CODE Server* is here: https://github.com/CollaboraOnline/richdocumentscode

For those reasons, plus this issue hasn't seen traffic in ~1 year, I'm going to close this one out.
