### ISSUE TITLE
Documents do not open in Safari/OSX

### ISSUE THREAD

**Issue by alebeta90** [nextcloud/richdocuments#303]
### Steps to reproduce
1.Try to open document with Safari

### Expected behaviour
We should open the document and be able to work on it

### Actual behaviour
It shows the loading image

### Server configuration

**Operating system**:
CentOS Linux release 7.5.1804 (Core) 3.10.0-862.14.4.el7.x86_64 

**Web server:**
Server version: Apache/2.4.6 (CentOS)

**Database:**
MariaDB

**PHP version:**
PHP 7.1.22 (cli) (built: Sep 15 2018 07:33:01) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
14.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from old Nextcloud installation

**Where did you install Nextcloud from:**
few months ago it was an owncloud installation and I used the web tool to migrate from owncloud to nextcloud

**Are you using external storage, if yes which one:** local/smb/sftp/...
NFS

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
(Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.1 Safari/605.1.15"

**Operating system:**
OSX

#### Collabora Logs
<details>
<summary>Collabora error log</summary>
```
loolwsd: wsd-09111-09124 2018-11-08 14:51:41.813718 [ websrv_poll ] WRN  WOPI host did not pass optional access_token_ttl| wsd/FileServer.cpp:611

```
</details>

Collabora server version 3.4.0

**Comment by thebearon** [comment]
There's no problem with opening files in Safari. Probably a setup issue, I'd suggest checking configuration of Collabora Online app in Nextcloud, browser console in Safari and logs from service `loolwsd` on the server.

**Comment by thebearon** [comment]
No reply for a month, closing this for now. If you have details feel free to add those.
