### ISSUE TITLE
Follow up for document linking

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#3043]
Remaining item would be:
- [ ] test the recent changes from Collabora to also allow sheets/slides to be targets.
- [ ] Double check if previews now work properly so we can make use of that where suitable

_Originally posted by @juliushaertl in https://github.com/nextcloud/richdocuments/issues/2834#issuecomment-1594221700_

**Comment by pedropintosilva** [comment]
@eszkadev could you please test this?

**Comment by eszkadev** [comment]
both sheets and slides are exported in link targets JSON
