### ISSUE TITLE
Laser Pointer for Nextcloud office

### ISSUE THREAD

**Issue by elhananjair** [nextcloud/richdocuments#3061]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
This is a feature request, I just wanted to suggest if it's possible to have a laser pointer implemented on Nextcloud office just like google docs.

**Comment by juliushaertl** [comment]
This sounds like a nice idea however would be something to implement within Collabora Online directly. Can you please file a feature request at https://github.com/collaboraonline/online
