### ISSUE TITLE
Regression: Cannot open pasword protected ODS files

### ISSUE THREAD

**Issue by gohrner** [nextcloud/richdocuments#307]
### Steps to reproduce
1. Store a password protected ODS document in Nextcloud
2. Try to edit the document in CODE

### Expected behaviour
The Richdocuments app asks for a password and allows to edit the file if you provide the correct password.

That's how it worked until some time ago - unfortunately I'm not sure which update broke it.

### Actual behaviour
The loading spinner never stops spinning, CODE never shows up.

LOOL logs the following messages:

kit-04297-04303 2018-11-09 14:21:34.398846 [ lokit_1b6 ] ERR  Failed to load: file:///user/docs/iTkJRnd7afzy2MGD/test.ods, error: loadComponentFromURL returned an empty reference| kit/Kit.cpp:1554
wsd-00027-04301 2018-11-09 14:21:34.400425 [ docbroker_1b6 ] WRN  Document load failed: passwordrequired:to-view| wsd/ClientSession.cpp:726
kit-04297-04303 2018-11-09 14:21:34.402984 [ lokit_1b6 ] ERR  Failed to get LoKitDocument instance for [file:///user/docs/iTkJRnd7afzy2MGD/test.ods].| kit/ChildSession.cpp:370
kit-04297-04303 2018-11-09 14:21:34.450429 [ lokit_1b6 ] WRN  Skipping unload on incomplete view.| kit/ChildSession.cpp:72

## Server configuration detail

**Operating system:** Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u5 (2018-09-30) x86_64

**Webserver:** Apache/2.4.25 (Debian) (apache2handler)

**Database:** mysql 10.1.26

**PHP version:** 

7.0.30-0+deb9u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, recode, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.7 - 13.0.7.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from a freash 13.0.3-or-something install.

**Where did you install Nextcloud from:** tarball

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - apporder: 0.5.0
 - bookmarks: 0.12.2
 - calendar: 1.6.1
 - circles: 0.14.2
 - comments: 1.3.0
 - contacts: 2.1.5
 - dav: 1.4.7
 - external: 3.0.4
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.4.0
 - ldapcontacts: 1.1.4
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.8.3
 - nextcloud_announcements: 1.2.0
 - notes: 2.4.2
 - notifications: 2.1.2
 - oauth2: 1.1.1
 - password_policy: 1.3.0
 - polls: 0.8.3
 - provisioning_api: 1.3.0
 - richdocuments: 3.0.3
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - socialsharing_email: 1.0.4
 - spreed: 3.2.6
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.7
 - theming: 1.4.5
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - user_ldap: 1.3.1
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_external

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.ohrner-it.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/nextcloud.ohrner-it.com",
    "htaccess.RewriteBase": "\/",
    "dbtype": "mysql",
    "version": "13.0.7.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "php",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "app.mail.accounts.default": {
        "email": "%USERID%@ohrner-it.com",
        "imapHost": "luggage.ohrner.net",
        "imapPort": 993,
        "imapUser": "%USERID%",
        "imapSslMode": "ssl",
        "smtpHost": "luggage.ohrner.net",
        "smtpPort": 465,
        "smtpUser": "%USERID%",
        "smtpSslMode": "ssl"
    },
    "auth.bruteforce.protection.enabled": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "updater.release.channel": "production"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** LDAP

<details><summary>LDAP configuration (delete this par if not used)</summary>

```
_lastChange: 1541772905background_sync_interval: 1800background_sync_offset: 0background_sync_prefix: cleanUpJobOffset: 0enabled: yeshas_memberof_filter_support: 1installed_version: 1.3.1ldap_agent_password: MGh5SldsV0cgRzVTc2NsQmEgUXEzd1VCVmQ=ldap_base: dc=ohrner-it,dc=comldap_base_groups: dc=ohrner-it,dc=comldap_base_users: dc=ohrner-it,dc=comldap_cache_ttl: 600ldap_configuration_active: 1ldap_display_name: cnldap_dn: cn=nextcloud,ou=system,dc=ohrner-it,dc=comldap_email_attr: mailldap_expert_username_attr: uidldap_group_filter: (&(|(objectclass=groupOfNames)))ldap_group_filter_mode: 0ldap_group_member_assoc_attribute: memberldap_groupfilter_groups: ldap_groupfilter_objectclass: groupOfNamesldap_host: ldaps://localhost/ldap_login_filter: (&(&(|(objectclass=inetOrgPerson))(|(memberof=cn=ohrner-it-mitarbeiter,ou=gruppen,ou=Ohrner-IT,dc=ohrner-it,dc=com)(memberof=cn=xdis-entwickler,ou=gruppen,ou=Ohrner-IT,dc=ohrner-it,dc=com)))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))ldap_loginfilter_email: 1ldap_loginfilter_username: 1ldap_nested_groups: 1ldap_port: 636ldap_user_filter_mode: 0ldap_userfilter_groups: ohrner-it-mitarbeiter
xdis-entwicklerldap_userfilter_objectclass: inetOrgPersonldap_userlist_filter: (&(|(objectclass=inetOrgPerson))(|(memberof=cn=ohrner-it-mitarbeiter,ou=gruppen,ou=Ohrner-IT,dc=ohrner-it,dc=com)(memberof=cn=xdis-entwickler,ou=gruppen,ou=Ohrner-IT,dc=ohrner-it,dc=com)))types: authentication
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/70.0.3538.77 Chrome/70.0.3538.77 Safari/537.36

**Operating system:** KDE Neon 5.14.3 (Ubuntu 18.10)

**Comment by rullzer** [comment]
Could you share an example file so we can test this?

**Comment by gohrner** [comment]
Ok, attached - I had to ZIP the file because this issue tracker does not accept ODS attachments. It's actually a ZIP (without password) wrapping the ODS, not just the ODS renamed.

The ODS' password is "test" (without quotation marks).

[test.zip](https://github.com/nextcloud/richdocuments/files/2566317/test.zip)
