### ISSUE TITLE
On firefox, collabora seems smoother with `use_integration_theme` set to `False`

### ISSUE THREAD

**Issue by Ornanovitch** [nextcloud/richdocuments#3084]
**Describe the bug**
This is not "a bug" but rather a global impression. I have been working for some weeks in order to get our Nextcloud office smoother/quicker, especially on firefox and especially on spreadsheets, where our users have difficulties (for example when scrolling).

While testing different options, I noticed that disabling the Nextcloud theme in Collabora (with `use_integration_theme` set to `false`) improved a lot the whole usability and reactivity of Nextcloud office. I don't know how to prove it or test it further, but I guess it would be good to benchmark and analyze the effects of the Nextcloud theme on the Collabora user experience.

**To Reproduce**
1. Open a document on Nextcloud and work on it
2. In your CODE server, set this option to `false`:

```
<use_integration_theme desc="Use theme from the integrator" type="bool" default="true">false</use_integration_theme>
```

3. Reopen the document and work on it
5. Feel that its better?

**Expected behavior**
The usability and reactivity should be the same with or without the Nextcloud integration, on Firefox as on Chromium

**Client details:**
 - OS: Arch Linux and Windows 10
 - Browser Firefox
 - Version 115
 - Device: desktop

## Server details

**Operating system**: Debian 10

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 8.0

**Nextcloud version:** NC 26.0.4

**Version of the richdocuments app** latest for NC 26

**Version of Collabora Online** latest (23.05)

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
Nothing relevant

#### Browser log
Nothing relevant

</details>

**Comment by juliushaertl** [comment]
Thanks for reporting. I'll have a look to see if there is something in the theme causing performance issues.

**Comment by Ornanovitch** [comment]
I didn't try to enable the `integration_theme` since 23.05.2.2, I just did and indeed, the usability issue seems to be fixed :)

**Comment by juliushaertl** [comment]
Thanks for confirming that. I'll close this issue then

**Comment by flightmansam** [comment]
Disabling doesn't seem to speed up in my testing.

**Comment by JeroenvanderSluijs** [comment]
I also experience very slow performance of Nextcloud (31.0.5) with collabora Built-in CODE server in Firefox (138.0.3 (64-bit).) 

Strange enough the load time is 5x faster in a private Firefox window (ctrl+shift+p)  compared to a normal Firefox window for exactly the same page.
