### ISSUE TITLE
column width isn't saved correctly

### ISSUE THREAD

**Issue by jpb1s** [nextcloud/richdocuments#3085]
**Describe the bug**
When changing column size and closing the document it is changed by Nextcloud to a different size. Related to that it is changed to a size with two decimal points, despite Nextcloud claiming that column size is only allowed to have one decimal point.

**To Reproduce**
1. Open a new table in Nextcloud
2. Change the column width to e.g. 1.7cm
3. Close the table 
4. Reopen the table and see that column size is changed (in my case 1.62)
5. When confirming 1.62 Nextcloud complains that I need to "select a valid value"

**Expected behavior**
I'd expect Nextcloud to remember the column width upon saving the document. If Nextcloud suggests a column width with two decimal points I'd expect it to be valid.

**Screenshots**
![image001](https://github.com/nextcloud/richdocuments/assets/140501679/c6826460-6033-48d7-85c2-1b9e5572448a)
![image002](https://github.com/nextcloud/richdocuments/assets/140501679/07a7ebec-7750-4bb9-b0d2-e110914c4de2)
![image003](https://github.com/nextcloud/richdocuments/assets/140501679/9b5100a8-ab27-4db1-809b-a89166c2f322)
![image004](https://github.com/nextcloud/richdocuments/assets/140501679/4a7ddd48-7005-415b-a9a7-b0c2ff842bf1)

**Client details:**
 - OS: Ubuntu 22.04
 - Browser Firefox
 - Version 115.0.2
 - Device: Desktop

## Server details

**Operating system**: Debian 12

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 8.2

**Nextcloud version:** 25.0.9

**Version of the richdocuments app** 7.1.4

**Version of Collabora Online** 23.05.1.2

**Comment by juliushaertl** [comment]
Thanks a lot for reporting this. The mentioned components that are handled by Collabora online directly so maybe you can file an issue in https://github.com/CollaboraOnline/online instead.
