### ISSUE TITLE
Dark mode NOK in Ubuntu 22.04

### ISSUE THREAD

**Issue by timur-g** [nextcloud/richdocuments#3087]
I build Collabora Online and use  in NC 27.0.1 and Dark mode is OK. It is Mint 21.2 based on Ubuntu 22.04.

I tested Online with Release 23.05.2 native install packages in a separate machine with Ubuntu 22.04 but had trouble with dark mode. In Writer, menus are OK but document is not dark, in Calc menus and document are dark but Automatic font remains black. 
I thought it was becuse of NC 25 but the same when I upgraded to 26 to 27.0.1,  All apps in NC are up to date, NC Office / richdocuments is 8.1.0.

If using built-in CODE, then Dark is OK. 

This may be about the specific machine but I report here to see.
![image](https://github.com/nextcloud/richdocuments/assets/7240617/2ed0733a-0476-42ef-971c-ae91efa59101)

**Comment by timur-g** [comment]
@pedropintosilva @thebearon please see.

**Comment by juliushaertl** [comment]
Can you paste the exact version and git hash from your about dialog of Collabora Online?

**Comment by timur-g** [comment]
COOLWSD version: 23.05.2.1 git hash: [7256b59](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/7256b59'));) (E)
COOLWSD version: 23.05.2.2 git hash: 
[91c166d](javascript:void(window.open('https://github.com/CollaboraOnline/online/commits/91c166d'));) (E)

This is in Ubuntu 22.04 both with Dark or Light Appearance.

**Comment by thebearon** [comment]
@timur-g Does this still occur for you?

**Comment by timur-g** [comment]
I had 23.05.6 and it was still wrong. Updated and now with 23.05.8 it is OK.
