### ISSUE TITLE
Error "Failed to generate token for existing file on direct editing"

### ISSUE THREAD

**Issue by Menzaah** [nextcloud/richdocuments#3088]
**Describe the bug**
We encounter a problem when we want to put access rules on certain files of a folder or the folder directly with the notion of inheritance for the documents in the folders. The result is the same.

Access rules are not taken into account and even worse, they malfunction.
For example :

I have the "grp-home" group which is supposed to be able to read files only. Unfortunately it is impossible for me to open this document with a user of this group. I took the opportunity to retrieve the logs that appear at this time from the administration panel.

**To Reproduce**
1 - Have user groups and a group folder
2 - Create authorization rules on this folder or a document inside "Excel/Table" type
3 - Test if with a read-only user/group we manage to open the file to read it and not be able to modify or delete it as indicated in the access rule

**Expected behavior**
Be able to use read/write access rules according to user group membership.

**Screenshots**
![AccesRule](https://github.com/nextcloud/richdocuments/assets/78805485/741e09ac-9b46-4bd8-b53f-b2941dcfc929)
![OpenFileError](https://github.com/nextcloud/richdocuments/assets/78805485/c3391d68-3138-44a8-be3c-f9f51d1fb2a2)
![Error logs](https://github.com/nextcloud/richdocuments/assets/78805485/e897a388-a3a8-4a01-90c4-c0a1dfad6db8)

**Client details:**
All platform

## Server details

**Operating system**:
Ubuntu 22.04.2 LTS

**Nextcloud version:**

Nextcloud AIO v6.3.0 

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
[apache.log](https://github.com/nextcloud/richdocuments/files/12176227/apache.log)
[collabora.log](https://github.com/nextcloud/richdocuments/files/12176228/collabora.log)
[database.log](https://github.com/nextcloud/richdocuments/files/12176229/database.log)
[nextcloud.log](https://github.com/nextcloud/richdocuments/files/12176230/nextcloud.log)

</details>

Thank you in advance for your help or any contribution. This is a very interesting feature that we would like to be able to use without problems.

Regards,

**Comment by Menzaah** [comment]
After several tests and different approaches, it seems that we only encounter this problem on the mobile application.

I oriented my research in this direction and the only link related to my problem is this one #2874 but which is a bit dated.

I take this opportunity to put the raw logs if it can help.

`{"reqId":"UyjoUwu9G821VtIobTL3","level":4,"time":"2023-07-31T21:26:50+00:00","remoteAddr":"81.185.163.90","user":"--","app":"richdocuments","method":"GET","url":"/apps/richdocuments/direct/NGR3xlZjiMw5sTHun9BoHikXZV4Kydy8HUS9cjknEhQonJHqkPlPTBoDsD3Mx4jf","message":"Failed to generate token for existing file on direct editing","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.25.0","version":"26.0.4.2","data":{"exception":"{\"class\":\"Exception\",\"message\":\"\",\"code\":0,\"file\":\"/var/www/html/custom_apps/richdocuments/lib/Controller/DirectViewController.php:149\",\"trace\":\"#0 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(230): OCA\\Richdocuments\\Controller\\DirectViewController->show('NGR3xlZjiMw5sTH...')\\n#1 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(137): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Richdocuments\\Controller\\DirectViewController), 'show')\\n#2 /var/www/html/lib/private/AppFramework/App.php(183): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Richdocuments\\Controller\\DirectViewController), 'show')\\n#3 /var/www/html/lib/private/Route/Router.php(315): OC\\AppFramework\\App::main('OCA\\\\Richdocumen...', 'show', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\\n#4 /var/www/html/lib/base.php(1065): OC\\Route\\Router->match('/apps/richdocum...')\\n#5 /var/www/html/index.php(36): OC::handleRequest()\\n#6 {main}\"}","app":"richdocuments"},"id":"64c90f928960b"}`

`{"reqId":"UyjoUwu9G821VtIobTL3","level":3,"time":"2023-07-31T21:26:50+00:00","remoteAddr":"81.185.163.90","user":"--","app":"PHP","method":"GET","url":"/apps/richdocuments/direct/NGR3xlZjiMw5sTHun9BoHikXZV4Kydy8HUS9cjknEhQonJHqkPlPTBoDsD3Mx4jf","message":"Undefined array key 0 at /var/www/html/custom_apps/richdocuments/lib/Controller/DirectViewController.php#147","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.25.0","version":"26.0.4.2","data":{"app":"PHP"},"id":"64c90f9289643"}`

**Comment by JonesGreen** [comment]
I have the same problem on my instance. Files don't open via ios or android app. It works fine using the browser. 

Using Nextcloud AIO v7.2.1 - Nextcloud 27.1.0 with advanced permissions.

Undefined array key 0 at /var/www/html/custom_apps/richdocuments/lib/Controller/DirectViewController.php#112

`{"reqId":"qPL4kiKzI2lSPqnA2Ypp","level":3,"time":"2023-10-05T14:01:28+00:00","remoteAddr":"yy","user":"--","app":"PHP","method":"GET","url":"/apps/richdocuments/direct/WJsVKr6UEot0fsAkFDuhNNV8RiGp16D9wFqEp3GByDLU6UzMboQ51ujxEJxauIDQ","message":"Undefined array key 0 at /var/www/html/custom_apps/richdocuments/lib/Controller/DirectViewController.php#112","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.25.0","version":"27.1.0.7","data":{"app":"PHP"},"id":"651ec1eaecae6"}`

Failed to generate token for existing file on direct editing

`{"reqId":"qPL4kiKzI2lSPqnA2Ypp","level":4,"time":"2023-10-05T14:01:28+00:00","remoteAddr":"yy","user":"--","app":"richdocuments","method":"GET","url":"/apps/richdocuments/direct/WJsVKr6UEot0fsAkFDuhNNV8RiGp16D9wFqEp3GByDLU6UzMboQ51ujxEJxauIDQ","message":"Failed to generate token for existing file on direct editing","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.25.0","version":"27.1.0.7","data":{"exception":"{\"class\":\"Exception\",\"message\":\"\",\"code\":0,\"file\":\"/var/www/html/custom_apps/richdocuments/lib/Controller/DirectViewController.php:114\",\"trace\":\"#0 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(230): OCA\\Richdocuments\\Controller\\DirectViewController->show('WJsVKr6UEot0fsA...')\\n#1 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(137): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Richdocuments\\Controller\\DirectViewController), 'show')\\n#2 /var/www/html/lib/private/AppFramework/App.php(183): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Richdocuments\\Controller\\DirectViewController), 'show')\\n#3 /var/www/html/lib/private/Route/Router.php(315): OC\\AppFramework\\App::main('OCA\\\\Richdocumen...', 'show', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\\n#4 /var/www/html/lib/base.php(1068): OC\\Route\\Router->match('/apps/richdocum...')\\n#5 /var/www/html/index.php(36): OC::handleRequest()\\n#6 {main}\"}","app":"richdocuments"},"id":"651ec1eaecadd"}`

**Comment by Janoo1606** [comment]
Hello,
i have the same problem via android app and browser. The documents get stuck while loading. But it affects all documents whether in the group folder or in your own directory.  And also newly created ones.

Use the extensions: Nextcloud Office with Collabora Online - Built-in CODE Server.  It works with the demo server setting, but not with the built-in Collabora Online Development Edition setting.

The protocol says: Failed to generate token for existing file on direct editing

Does somebody has any idea?

**Comment by Nils160988** [comment]
I can confirm this issue, editing only fails if all those criteria are met:
- groupfolder
- access rules
- access via mobile
If one of those criteria does not apply, the file can be accessed by collabora.

No idea, what is the root cause behind it.

This is the entry in my log when access fails:
`{"reqId":"replaced","level":4,"time":"2023-11-11T22:59:29+01:00","remoteAddr":"replaced","user":"--","app":"richdocuments","method":"GET","url":"/apps/richdocuments/direct/a17XldeTQcyYQkIgXoK1tnEZ0V2qNsB4KAKsmcCFg8NlJUZ9tmuod9EiInDltIJj","message":"Failed to generate token for existing file on direct editing","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.26.0","version":"27.1.3.2","d     ata":{"exception":"{\"class\":\"OCP\\Files\\NotPermittedException\",\"message\":\"\",\"code\":0,\"file\":\"/var/www/replaced/apps/richdocuments/lib/TokenManager.php:185\",\"trace\":\"#0 /var/www/replaced/apps/richdocuments/lib/Controller/DirectViewController.php(126): OCA\\Richdocuments\\TokenManager->generateWopiToken()\\n#1 /var/www/replaced/lib/private/AppFramework/Http/Dispatcher.php(230): OCA\\Richdocuments\\Controller\\DirectViewController->show()\\n#2 /var/www/replaced/lib/private/AppFramework/Http/Dispatcher.php(137): OC\\AppFramework\\Http\\Dispatcher->executeController()\\n#3 /var/www/replaced/lib/private/AppFramework/App.php(183): OC\\AppFramework\\Http\\Dispatcher->dispatch()\\n#4 /var/www/replaced/lib/private/Route/Router.php(315): OC\\AppFramework\\App::main()\\n#5 /var/www/replaced/lib/base.php(1068): OC\\Route\\Router->match()\\n#6 /var/www/replaced/index.php(36): OC::handleRequest()\\n#7 {main}\"}","app":"richdocuments"}}`

**Comment by juliushaertl** [comment]
Just a quick thought without diving into it in depth. It might be that we miss setting the correct user scope for certain code paths in groupfolders/files_accesscontrol then.

This could be patch candidate to solve that, but currently untested:

```diff
diff --git a/lib/Controller/DirectViewController.php b/lib/Controller/DirectViewController.php
index 89725c57..5ca21b64 100644
--- a/lib/Controller/DirectViewController.php
+++ b/lib/Controller/DirectViewController.php
@@ -27,6 +27,7 @@ use OCA\Richdocuments\Db\Direct;
 use OCA\Richdocuments\Db\DirectMapper;
 use OCA\Richdocuments\Service\FederationService;
 use OCA\Richdocuments\Service\InitialStateService;
+use OCA\Richdocuments\Service\UserScopeService;
 use OCA\Richdocuments\TemplateManager;
 use OCA\Richdocuments\TokenManager;
 use OCP\AppFramework\Controller;
@@ -52,6 +53,7 @@ class DirectViewController extends Controller {
                private IRootFolder $rootFolder,
                private TokenManager $tokenManager,
                private DirectMapper $directMapper,
+               private UserScopeService $userScopeService,
                private InitialStateService $initialState,
                private IConfig $config,
                private AppConfig $appConfig,
@@ -88,6 +90,8 @@ class DirectViewController extends Controller {
                        return $this->showPublicShare($direct);
                }

+               $this->userScopeService->setUserScope($direct->getUid());
+               $this->userScopeService->setFilesystemScope($direct->getUid());

                $folder = $this->rootFolder->getUserFolder($direct->getUid());
                if ($this->templateManager->isTemplate($direct->getFileid())) {
```

**Comment by Nils160988** [comment]
Your patch looks promising, seems to fix the issue for me :)

**Comment by Janoo1606** [comment]
How can I install or insert the patch?

**Comment by Nils160988** [comment]
For now, you have to manually patch the file at your system until this fix becomes part of another release @Janoo1606 
Can I help and speed up the process (maybe create a PR for this fix)? @juliushaertl

**Comment by juliushaertl** [comment]
Just did that with #3293
