### ISSUE TITLE
No content area with IE11

### ISSUE THREAD

**Issue by thebearon** [nextcloud/richdocuments#309]
With Nextcloud 14.0.3, richdocuments 3.0.4 and Collabora Online 3.4.0, when using Internet Explorer 11, the menu, toolbar and document area are missing. This was working before version 3 of richdocuments.

![missing_content](https://user-images.githubusercontent.com/19438782/48320264-e119c980-e617-11e8-8844-076859d5749e.png)

**Comment by thebearon** [comment]
CC @rullzer

**Comment by juliushaertl** [comment]
Should be fixed with https://github.com/nextcloud/server/pull/12342 in the server repo. (Backport will be in the next release of Nextcloud 14)
