### ISSUE TITLE
Feature request: open files in new tab/window

### ISSUE THREAD

**Issue by jschreuder** [nextcloud/richdocuments#31]
Currently files open within the Nextcloud tab. This is usefull when editing a single file, but much less so when editing or working with multiple files simultaniously. The Google Docs behavior which opens each file in a new tab works far better for that usecase.
Currently opening a document in a new tab will just download the file, instead of opening a new Nextcloud tab with the file opened.

Would it be possible to allow for this? And in addition to possibly to either change the default behavior (add a setting to open in tab by default) and/or allow opening in same-tab and new-tab from the ... icon after the file. And supporting opening the file in a new tab within Nextcloud/Collabora.

**Comment by TheMrApostel** [comment]
+1

**Comment by davepage-mcr** [comment]
+1 This would make migrating people from Google Docs to NextCloud much easier for us.

**Comment by dvaerum** [comment]
I also really want this feature, just as a option in the setting just like one has with OnlyOffice. Is there any plans for this?

**Comment by tk7936** [comment]
I could live with just one window for a document allthough i agree it would be nice to have multiple tabs for documents. What i think is absolutely necessary though is to open different modules in different tabs.
For example if im editing a document and get a mail i cant switch to the mail client in a different tab, i have to interrupt document editing, click on email menu and thereby closing the document, then after doing email reopen the document. Also meaning i cant even read a document while writing a email and that's just a joke.

**Comment by jaschrock** [comment]
Any chance this can be added?  Similarly to others, coming from Google Docs, this is one of the complaints I am getting.

**Comment by jakobroehrl** [comment]
Maybe it will be fixed with this issue: https://github.com/nextcloud/server/issues/14593

**Comment by dvaerum** [comment]
What is that status on this?

**Comment by cornouws** [comment]
For time being, I simply do a Ctrl+click on the folder icon, while I'm in a document in CollaboraOnline.
Yes, that does open the default folder - I know ;)

**Comment by juliushaertl** [comment]
Ctrl+click on the file itself will actually now open collabora in a new window with Nextcloud 19+ as of https://github.com/nextcloud/server/pull/20185

**Comment by avatar1024** [comment]
Great that the possibility exists...but it is hard to find (I found it on here) and it is counter-intuitive. For reason there is no plan to create a setting for this ([see comment here](https://github.com/nextcloud/richdocuments/issues/1598#issuecomment-858350403) ...even though a simple option in right click context menu would be enough for most use case. It would be interesting to understand where the design decision comes from.

**Comment by juliushaertl** [comment]
Maybe @jancborchardt remembers the details on that, I cannot find the exact issue where this was discussed anymore.

**Comment by audunmb** [comment]
Why is this closed? There are very good UX reasons for why this behaviour (open document in new tab) is default in Dropbox, Google Docs and OneDrive/Sharepoint, so Nextcloud should adopt it as well.

**Comment by dvaerum** [comment]
Hey @audunmb I don't know how much this helps, but back in 2020, I got this response from a guy (who works/worked at LibreOffice), he tried to give the feature a push inside Collabora Online, but he was unsuccessfully, here is the reply I got, hope it helps.

```
Subject: LibreOffice Online and new browser tab/window issue

Hi Dennis,

I got in touch with the product manager for the Collabora Online
instance and I made your request being directly inspected.

Unfortunately it seems that we (you and me) probably deeply
misunderstood how much work is to be done to fix this issue: if we try
to provide a configurable flag inside the settings to open up all the
documents in a new tab/window from the browser (which is a pretty much
sensible and smart way of fixing your issue), a rough estimation of the
work needed is one full day of work for a PHP/Javascript/SQL developer.

Additional insights you may want to know on your use case are the following:
* Owncloud permits, for example, to use the back button to get again to
the list of documents open, which is not possible because Nextcloud
instead will obfuscate in some ways the URL and going back wouldn't take
you again on the list of the documents;
* What OnlyOffice is doing there (one window more when clicking on the
document from a document list) is helping them on the business version,
since this opens up an additional connection to their engine and they
invoice per number of connections. I think this doesn't apply to the
community version though.

My own opinion on that (still, I am not a developer and I don't know the
core bits of LibreOffice, even the Desktop one), is that a skilled and
up-to-date LOOL developer would take much less time to do this modification.

Again, Collabora is a company and unless other of their own customers
will ask for the same feature multiple times, they are not going to
implement it, at least in the few years.

Still, I might have the option to point them out to the feature request
you mentioned during our brief talk. Do you happen to know where it is
in Bugzilla?
```
**Note:** I reply to the email with a link to this issue - https://github.com/nextcloud/richdocuments/issues/31 
```
I will also push, as I might be able to do that, to have a copy of the
Collabora Online integration app for Nextcloud and make a community one
to cope with it in the community version of LOOL, but things are not so
simple anyways.

So in the end, no good news on this side but still hoping that will
happen in the future.
```

**Comment by glorenzutti** [comment]
No news ?

I imagined this was going to have more impact.
The onlyoffice version does this a long time ago.
Collabora was chosen as the default office suite for the platform, but it does not allow you to open documents in a new browser tab by default.
It is very complex to explain this to all users, and it greatly limits the adoption of the platform.
Added to what we've all been saying, all popular products do this by default.

**Comment by urfin73** [comment]
Hello. Please tell me, has anyone noticed that in version Nextcloud 28.0 the ctrl+ key combination stopped working when opening a document? The document opens in the same window.

**Comment by juliushaertl** [comment]
Pushed a fix for the files app in https://github.com/nextcloud/server/pull/42457

**Comment by urfin73** [comment]
Hello, version Nextcloud Hub 10 (31.0.2) Same problem...

**Comment by D592VN5** [comment]
Very annoying that there is no way to use standard browser keyboard shortcut to open file in new tab.

**Comment by ferdiga** [comment]
yes would enhance the workflow a lot if multiple documents needed to be opene

**Comment by jancborchardt** [comment]
@urfin73 @D592VN5 @ferdiga just tested with latest master as well as with Nextcloud 31.0.8, and both `Ctrl+Click` and `Middle click` work to open documents in new tabs.
