### ISSUE TITLE
Insert "Remote Image" is not working

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/richdocuments#310]
### Steps to reproduce
1. Open a document in Collabora (3.4.0)
2. Try to insert an image from NC by choosing "Remote Image"
3. The file picker appears, select a file und confirm

### Expected behaviour
The image should be inserted in the document

### Actual behaviour
Nothing happens in the editor.

I tried to trace the javascript functions as best as I can. The last call is to ```sendMessage``` with the following message:
```"insertfile name=<encodedURL> type=graphicurl"``` which looks fine to me. After this, nothing happens.
No error in console or logs. The URL which is generated is working fine when tested from a browser. Even from the Collabora container it is perfectly accessable (tried to download it there with wget).

### Server configuration
**Operating system**: Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64

**Web server:** Apache/2.4.25 (Debian) (apache2handler) (NGINX Reverse Proxy)

**Database:** mysql 5.7.22

**PHP version:** 7.0.27-0+deb9u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** (see Nextcloud admin page) 14.0.3 - 14.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** From 13

**Where did you install Nextcloud from:** Online Update

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - dav: 1.6.0
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - groupfolders: 1.3.3
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - nextcloud_announcements: 1.3.0
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - previewgenerator: 2.0.0
 - provisioning_api: 1.4.0
 - richdocuments: 3.0.5
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - admin_audit
 - encryption
 - files_accesscontrol
 - files_external
 - user_external
 - user_ldap
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "14.0.3.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "sendmail",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "log_type": "syslog",
    "logtimezone": "Europe\/Berlin",
    "logfile": "\/var\/nextcloud\/log\/nextcloud.log",
    "loglevel": 0,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\TIFF",
        "OC\\Preview\\PDF"
    ],
    "maintenance": false,
    "theme": "",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "preview_max_x": 512,
    "preview_max_y": 512,
    "preview_max_scale_factor": 1,
    "skeletondirectory": "",
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome 70

**Operating system:** Windows 10 x64 1803

**Comment by rullzer** [comment]
This should be fixed with collabroa 3.4.1 that has just been released

**Comment by SystemKeeper** [comment]
Thanks for the quick reply. I've upgraded to 3.4.1.1 and it's working perfectly now!

**Comment by thebearon** [comment]
Note for people using self-signed certificates: this feature currently isn't working with those, as it'd require user action to confirm the security exception inside the jailed LO instance, and the dialog for that doesn't appear.
