### ISSUE TITLE
Office: Fonts improvements: Previews, popular from Google Fonts, checking with LO desktop fonts, deduplicating Noto Sans & Serif variants

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#3139]
- [x] Font preview ongoing in COOL
  - [x] https://github.com/CollaboraOnline/online/pull/7131
- [ ] Ship popular fonts
	- [ ] Clarify licenses if we can ship it, need to attribute (and how)
	- [ ] Test if variable fonts work as expected (e.g. `RobotoMono-VariableFont_wght.ttf`)
	- [ ] Pick font files to ship depending on if variable sizing is working to not increase the richdocuments bundle size too much
	- [ ] Implementation https://github.com/nextcloud/richdocuments/pull/3304 @luka-nextcloud 
  	  - [ ] Font files get shipped as part of richdocuments in an extra assets/fonts/ directory
	  - [ ] New fonts shall be copied from the assets/fonts folder and added through the existing [FontService method](https://github.com/nextcloud/richdocuments/blob/05657472698a27f8afc57072e777e83240280bab/lib/Service/FontService.php#L155)
	  - [ ] Add a [repair job](https://docs.nextcloud.com/server/19/developer_manual/app/repair.html) to add new fonts once to the installation ([repair step version check example](https://github.com/nextcloud/text/blob/886012022aac3e4a525f9a7e6af9ecbf3464211f/lib/Migration/ResetSessionsBeforeYjs.php#L39))
	  - [ ] Add an occ command to install shipped fonts again if manually removed as the admin
	  - [ ] Cypress test that ensures the fonts are listed in the admin settings
- [ ] Possible follow up: Deduplicate/group fonts in the UI -> Collabora

**Comment by juliushaertl** [comment]
@jancborchardt ping for a possible list of fonts. We could start shipping those with richdocuments and then try to improve the auto setup to pick up fonts automatically from there.

**Comment by jancborchardt** [comment]
Here are the ones Google Docs provides and I would say we make sure to add those. Fonts in (parentheses) are proprietary though:


- Amatic https://fonts.google.com/specimen/Amatic+SC
- (Arial)
- Caveat https://fonts.google.com/specimen/Caveat
- Comfortaa https://fonts.google.com/specimen/Comfortaa
- (Courier New)
- EB Garamond https://fonts.google.com/specimen/EB+Garamond
- Lexend https://fonts.google.com/specimen/Lexend
- Lobster https://fonts.google.com/specimen/Lobster
- Lora https://fonts.google.com/specimen/Lora
- Merriweather (could include Merriweather Sans too) https://fonts.google.com/specimen/Merriweather
- Montserrat https://fonts.google.com/specimen/Montserrat
- Nunito https://fonts.google.com/specimen/Nunito
- Oswald https://fonts.google.com/specimen/Oswald
- Pacifico https://fonts.google.com/specimen/Pacifico
- Playfair Display https://fonts.google.com/specimen/Playfair+Display
- Roboto https://fonts.google.com/specimen/Roboto
- Roboto Mono https://fonts.google.com/specimen/Roboto+Mono
- Roboto Serif https://fonts.google.com/specimen/Roboto+Serif
- Spectral https://fonts.google.com/specimen/Spectral
- (Times New Roman)

As a bonus we could also include these 2 popular ones:
- Poppins: https://fonts.google.com/specimen/Poppins
- Inter: https://fonts.google.com/specimen/Inter

Does that make sense @juliushaertl, or too many?

**Comment by juliushaertl** [comment]
- [ ] Clarify licenses if we can ship it, need to attribute (and how)
- [ ] Test if variable fonts work as expected (e.g. `RobotoMono-VariableFont_wght.ttf`)
- [ ] Pick font files to ship depending on if variable sizing is working to not increase the richdocuments bundle size too much
- [ ] Implementation
  - [ ] Add an occ command to install shipped fonts
  - [ ] Add a repair job to add new fonts once to the installation

**Comment by jospoortvliet** [comment]
We should make sure we have the default MS Office ones - that will make sure documents from MS Office look good. Really key, I think, to ensure a good experience, as MS Office fonts and docs are used the most.

I think to ship proprietary fonts you might have to do what Linux distributions do - download them on demand. You are likely not allowed to ship them, but they can be downloaded for free.

**Comment by juliushaertl** [comment]
I'm not sure, Microsoft has a dedicated option to buy a server license 

https://www.fonts.com/content/microsoft-typography

> Apart from the document embedding rights described previously, you may not redistribute the Windows fonts. You may not copy them to other computers or servers, and you may not convert them to other formats, including bitmap formats, or modify them.

https://learn.microsoft.com/en-us/typography/fonts/font-faq

**Comment by juliushaertl** [comment]
Interestingly onlyoffice does this in https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/6e424a5541664247a1296f87d113cb49c4de0408/Dockerfile#L16 but autoconfirm the EULA, but I would not do that without having a clear statement that this is legally fine.

**Comment by juliushaertl** [comment]
https://git.launchpad.net/ubuntu/+source/msttcorefonts/tree/update-ms-fonts#n34

https://github.com/pop-os/msttcorefonts/blob/master_jammy/debian/postinst#L70-L80

**Comment by juliushaertl** [comment]
You can download them from the list in https://github.com/nextcloud/richdocuments/issues/3139#issuecomment-1723176076, but feel free to just use one for testing for now. I already have a full directory with all of them that I can just push to the pull request then.

The assets I'd just put in the root, yes.

**Comment by jospoortvliet** [comment]
> I'm not sure, Microsoft has a dedicated option to buy a server license
> 
> https://www.fonts.com/content/microsoft-typography
> 
> > Apart from the document embedding rights described previously, you may not redistribute the Windows fonts. You may not copy them to other computers or servers, and you may not convert them to other formats, including bitmap formats, or modify them.
> 
> https://learn.microsoft.com/en-us/typography/fonts/font-faq

Yes, you and me can not do that. But a user (AKA the server admin) can dowload them for themselves. The fonts do not leave the one server and they are not distributing them.

This is how Linux distributions do it - they don't ship them. They have a script or a package that contains a script that asks the user to agree to the EULA and then downloads and installs them.

So we will need the same - a button in the UI that says "install Microsoft fonts" which then shows the EULA and then grabs them. I am sure we can't ship them and I don't think we can auto-accept the EULA like OO does.
