### ISSUE TITLE
Revision History panel is partially localized

### ISSUE THREAD

**Issue by timar** [nextcloud/richdocuments#314]
The sample image was taken from pt-BR language, where only a few strings are in Portuguese.
![image](https://user-images.githubusercontent.com/290614/48901084-95a3be80-ee54-11e8-9f2a-3e09ff61ba54.png)

The string "Revision History" is not marked up for localization in the source code. I don't know where the translated time ago strings should come from.

**Comment by rullzer** [comment]
Is this the Nextcloud sidebar?

**Comment by timar** [comment]
It is the Nextcloud sidebar.

**Comment by rullzer** [comment]
On which version of Nextcloud?

**Comment by timar** [comment]
Sorry, maybe I was unclear. I see it on Nextcloud 13.0.6, but the Revision History string is in richdocuments. 
``    timar@linux-dell:~/GitHub/nextcloud/richdocuments$ git grep "Revision History" ``
``    js/templates.js:  return "<div id=\"revPanelContainer\" class=\"loleaflet-font\">\n     <div id=\"revPanelHeader\">\n           <h2>Revision History</h2>\n           <span>"``
``    js/templates/revHistoryContainer.handlebars:            <h2>Revision History</h2>``

**Comment by rullzer** [comment]
Ah right I see it now.
I'll take care of it.

**Comment by rullzer** [comment]
So it looks like the actual timestamps are also not localized for the versions.

**Comment by rullzer** [comment]
I'll see if i can look into the other translations as well. I guess they need to be handled by moment.js ;)

**Comment by juliushaertl** [comment]
Fixed with the files sidebar integration.
