### ISSUE TITLE
希望使用docker搭建的内建版本可以支持中文字体，谢谢。

### ISSUE THREAD

**Issue by snakwu** [nextcloud/richdocuments#3145]
![Screenshot_20230828_041904_Edge](https://github.com/nextcloud/richdocuments/assets/5343595/97d6405d-6355-4aa7-99ab-118c9993fc0b)
![Screenshot_20230828_041845_Edge](https://github.com/nextcloud/richdocuments/assets/5343595/f54b00ad-8df9-4681-b202-fc164ad3c50e)
使用的是docker搭建，安装内置的Collabora中文不能显示

**Comment by juliushaertl** [comment]
Please file your issue reports in English and stick to filling out the complete issue template.

**Comment by zghmidi** [comment]
Why can't nextcloud built with docker use the built-in Collabora CODE to display Chinese fonts?
