### ISSUE TITLE
Continuous View / Web Layout

### ISSUE THREAD

**Issue by panomitrius** [nextcloud/richdocuments#3159]
I'm looking for a way to edit documents without the text being visually divided as pages (what's usually called Continuous View / Web Layout). Is there such a setting, or is it not implemented yet?

**Comment by juliushaertl** [comment]
This sounds like a great suggestion. This issue tracker is only for the Nextcloud connector app named Collabora Online. For feature requests with Collabora Online itself, please open a report at: https://github.com/collaboraonline/online
