### ISSUE TITLE
One person editing, but several avtatars

### ISSUE THREAD

**Issue by enoch85** [nextcloud/richdocuments#3166]
**Describe the bug**
When editing a document, and the file is open 1 (one) tab, still several avatars of the same person is being showed.

**To Reproduce**
1. Open document
2. Close document
3. Open document in a new tab

**Expected behavior**
Only one avatar should be show as there's actually only one person editing. Or is this some kind of caching issue?

**Screenshots**
![image](https://github.com/nextcloud/richdocuments/assets/4511254/d47997a6-e7b9-43b6-8d9c-80301ae773bc)

**Client details:**
 - OS: Windows 10
 - Browser Edge
 - Version 116
 - Device: Desktop

## Server details

**Operating system**:
Ubuntu Server 22.04

**Web server:**
Apache2

**Database:**
MariaDB

**PHP version:**
8.2

**Nextcloud version:**
27.0.2

**Version of the richdocuments app**
 8.1.1

**Version of Collabora Online**
22.05.18-1

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
Looks like a dupilcate of https://github.com/nextcloud/richdocuments/issues/2593 / https://github.com/CollaboraOnline/online/issues/5452. Maybe you can comment in those if this is also happening with 23.05 and if you are using a full Collabora server or the richdocumentscode app.
