### ISSUE TITLE
Expose endpoint for clients

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/richdocuments#318]
Only the upcoming COOL version 4.0 should be used with clients, as the current one does not support hdpi, no decent mobile/response design.

So RichDocuments should expose "direct_editing" via Capabilities, which checks against COOL version via their capability endpoint:
- no capability / version <4.0 => "direct_editing": false
- version >= 4.0 => "direct_editing": true

With this clients can right now add and check this.

@rullzer as discussed on irc
@juliushaertl maybe you can help with the implementation as Roeland is not available tomorrow
@marinofaggiana please implement the check also on iOS

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/commit/f6f22a245220fe4cda15048d7a096115b005681a
