### ISSUE TITLE
Nextcloud 25.0.9 with Nextcloud Office 7.1.6 does not work on Android (download instead of opening documents)

### ISSUE THREAD

**Issue by Mornsgrans** [nextcloud/richdocuments#3182]
**Describe the bug**
After installation of Nextcloud Office 7.1.6 and Collabora Online Builtin CODE Server 23.5.301 apps an office document .doc becomes downloaded and a dialog to select an app to open the file appears.
(In Firefox on laptop it works as expected)

**To Reproduce**
1. Go to Nextcloud-app on Android device, select a folder containing office documents  
2. Tap on an office document file, which is not synchronized 
3. The file becomes synchronized (green circle with white hook appeas) and the dialog to select an app to open with (see screenshot below).

**Expected behavior**
Expected, that the document becomes opened as in the Nextcloud Office 7.1.4
Collabora CODE 23.05.1.3-ucs1 and 23.05.2.2 Instances both work with Nextcloud Office 7.1.4 and Collabora Online Builtin CODE Server 23.5.104 apps

**Screenshots**
![grafik](https://github.com/nextcloud/richdocuments/assets/85793094/1ecba05a-5932-418d-80f2-7a3d159fe51d)

**Client details:**
 - OS: Android 9
 - Nextcloud App 
 - Version 3.26.0
 - Device: Huawei P10 Plus

## Server details

**Operating system**: Univention Corporate Server 5.0.4 and 5.0.5 (Debian GNU/Linux 10 (buster))

**Web server:** Apache 2.4.38-3+deb10u10A~5.0.3.202304251027

**Database:** PostgreSQL 9.6.24-0+deb9u3

**PHP version:** 7.3+69

**Nextcloud version:** 25.0.9

**Version of the richdocuments app** 7.1.6 and Collabora Online Builtin CODE Server 23.5.301

**Version of Collabora Online** Tested with Collabora CODE 23.05.1.3-ucs1 and 23.05.2.2 docker instances 

<details>
<summary>xx.xx.xx.xx - - [16/Sep/2023:18:39:37 +0200] "PROPFIND /nextcloud/remote.php/dav/files/user/Des%20Admins%20Gebote.doc HTTP/1.1" 207 2240 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.26.0"
</summary>

#### Nextcloud log (data/nextcloud.log)
```
no coresponding log entry generated (last entry was 5 days ago)
```

#### Browser log
```
Insert your browser log here, this could for example include:

No log in Android-App "Nextcloud" available
```

</details>

**Comment by RuHitt** [comment]
Hey, I noticed that too after the last app update.
This is the relevant change that leads to the problem: https://github.com/nextcloud/richdocuments/pull/3154
I was able to solve it by manually changing the php line back.

Maybe someone with background knowledge can explain this and/or start a new backport.

Best regards

**Comment by juliushaertl** [comment]
Thanks for reporting, just pushed a fix for this in https://github.com/nextcloud/richdocuments/pull/3184

**Comment by Mornsgrans** [comment]
I tried setting the "mobile_setting" config in my confuguration using the occ-command as mentioned in https://github.com/nextcloud/richdocuments/pull/3184 and it made the bahavior worse.

Independent of the value "yes" or "no" even in the Firefox browser always my local Libreoffice will be executed after click on the office document instead of opening in Nextcloud office.

**Comment by Mornsgrans** [comment]
The issue still persists now with 
Collabora Online - Built-in CODE Server 23.5.402
and 
Nextcloud Office 7.1.6
There still the document becomes downloaded and I am asked to select an Android app to open it.
In my Browser under Windows it works.
