### ISSUE TITLE
Improve listing of current editors

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#320]
As discussed:

![image](https://user-images.githubusercontent.com/3404133/49292506-ba7bdf80-f4ad-11e8-885e-edad80fb08e5.png)

- [ ] Add option to remove view
- [ ] Allow to follow editing users

**Comment by juliushaertl** [comment]
@jancborchardt I spent a lot of time trying to find a way we can hook the current editing view into the share list, but I could not come up with a solution that works reliable. I would actually go for a popovermenu for now, if more than 5 users are currently editing. We can think about providing a proper javascript integration in the files app, if we do some bigger rework on the sidebar.

**Comment by jancborchardt** [comment]
Ok, in that case cc @nextcloud/designers / @nextcloud/javascript FYI regarding standardization and sidebar rework. https://github.com/nextcloud/server/issues/10289
