### ISSUE TITLE
Dropdowns have wrong mark color in browsers

### ISSUE THREAD

**Issue by Darshan-upadhyay1110** [nextcloud/richdocuments#3235]
**Describe the bug**

List view in format cell has weird dark background color.

![image](https://github.com/nextcloud/richdocuments/assets/61383886/04148c76-dae7-47ef-b395-20c88ed14996)

 - It is  reproducible in Chrome V- 118.
 - after updating to 8.2.1 `--nc-color-primary-element-light` value is sometimes has the correct "light" value #e5f0f5 and sometimes it comes with a "dark" color: #141f25 
 - i suspect regression bug.  this was OK in 8.0.5

**To Reproduce**
1. Open to any .ods file
2. Right Click on any cell
3. Select `Format Cell`
4. You can see dark color for selcted item in list.

**Expected behavior**
In every browser it should be same color value to set in variable `--nc-color-primary-element-light`

**Current behavior**
In chrome i am getting dark color (color: #141f25 ) for  `--nc-color-primary-element-light`

Richdocument version : 8.2.1
NC version: 27

Issue has already filed for Collabora online : https://github.com/CollaboraOnline/online/issues/7451

Maybe the problem is on Nextcloud side because no sense to set dark color for light mode.

CC: @juliushaertl

**Comment by Darshan-upadhyay1110** [comment]
- As i have dig some code bit in richdocument i have found this line where we are setting the colors: https://github.com/nextcloud/richdocuments/blob/331f8f7b2849047c0f5d219074d4991070d267c0/src/helpers/coolParameters.js#L55
 
@juliushaertl can you please guide me where this color codea are defined which is set inside ` --nc-color-primary-element-light` ?

**Comment by juliushaertl** [comment]
The value of  --nc-color-primary-element-light is extracted from nextcloud for both variants, dark and light mode here:
https://github.com/nextcloud/richdocuments/blob/331f8f7b2849047c0f5d219074d4991070d267c0/src/helpers/coolParameters.js#L121-L136

Nextcloud itself generates this value based on the primary color and mixes it with the background (white or black) depending on light or dark mode. Maybe you can check the values of --nc-light-color-primary-element-light and --nc-dark-color-primary-element-light

**Comment by Darshan-upadhyay1110** [comment]
About mixup color so you mean it generates the color dynamically?  and if yes then can you give any pointer where i can look ?

**Comment by juliushaertl** [comment]
> About mixup color so you mean it generates the color dynamically? and if yes then can you give any pointer where i can look ?

Yes, those values are also used within Nextcloud and generated by the server:
https://github.com/nextcloud/server/blob/ddb808e13629e9fb7216787ed9d76544236377b0/apps/theming/lib/Themes/CommonThemeTrait.php#L44

I cannot reproduce this. Can you maybe share the following:
- Nextcloud primary color (run this in the js console of nextcloud `OCA.Theming.defaultColor`)
- User primary color (run this in the js console of nextcloud `OCA.Theming.color`)
- Which apprearance setting in nextcloud is selected (https://nextcloud.local/index.php/settings/user/theming)
- Is the os/browser in dark/light mode?

**Comment by Darshan-upadhyay1110** [comment]
- Nextcloud primary color: `#0082c9`
- User primary color : `#0082c9` 
![image](https://github.com/nextcloud/richdocuments/assets/61383886/ef6749c4-96b6-482e-835e-9f0e0c87112c)

- System default theme. 
![image](https://github.com/nextcloud/richdocuments/assets/61383886/b275fd94-0674-4a0c-8d83-d22364a5bdd1)

- yes i am using dark mode for both os and browser as well.

**Comment by Darshan-upadhyay1110** [comment]
ahaa okay but @juliushaertl i am not sure about where you are refering to add this two  div. is it inside  `<template> ` directly or need to add new component.

i have added this into dom but no effect.
![image](https://github.com/nextcloud/richdocuments/assets/61383886/8c79cad3-cc04-4fcf-86d3-8fe9e8839d66)

maybe i am adding wrong way i don't know :(

**Comment by juliushaertl** [comment]
Hm, all right, i think the viewer component is then not rendered early enough to put those divs into the DOM.

We probably could do something like this programatically then in coolParameters.js

```
const lightElement = document.createElement('div')
lightElement.setAttribute('data-theme-light')
document.body.appendChild(lightElement)
```

This should work to properly get the values for the light theme as well.
