### ISSUE TITLE
NC 27 regression: Fullscreen fails in Chrome due to missing "Feature-Policy: fullscreen" header

### ISSUE THREAD

**Issue by jonas2515** [nextcloud/richdocuments#3236]
With the update to Nextcloud 27, fullscreening documents or presentation is broken in the Chrome browser because the `Feature-Policy: fullscreen` header is no longer set to allow the iframe to request fullscreen. In NC 26 this header was set to `fullscreen 'self' https://CODEserverDomain.tld;`, in NC 27 that entry is missing.

Steps to reproduce: Open a presentation in Nextcloud office with Chrome and try to present it using the "Presentation" button. The browser will try to fullscreen the iframe, but that will fail due to missing permissions (there's an error on the JS console). It still works in Firefox.

A temporary workaround for this is to serve to CODE/Collabora Office installation from the same domain as the Nextcloud installation. This can easily be done by using the "Built-in CODE server" app instead of an own installation.

**Comment by juliushaertl** [comment]
Notes for the fix:

https://github.com/nextcloud/richdocuments/blob/ba45233bff0c5356e8e926d4bffd8d34053b16cf/lib/Controller/DocumentTrait.php#L27-L35 is no longer loaded in a nested iframe

We need a AddFeaturePolicyEvent listener similar to https://github.com/nextcloud/richdocuments/blob/ba45233bff0c5356e8e926d4bffd8d34053b16cf/lib/Listener/CSPListener.php#L53
