### ISSUE TITLE
Restoring an old revision causes CSRF error

### ISSUE THREAD

**Issue by thebearon** [nextcloud/richdocuments#325]
- Make some changes to a file, and save after the changes, so it has multiple revisions.
- Open File -> See Revision History.
- Select an older revision, and click the 'Restore this revision' icon.

=> The following error message is shown:

> Access forbidden
> CSRF check failed

This is a regression, and based on bisect results it seems to have originated from 1b57dd435fcd7f0904efc97d79f85d895471d33c.

**Comment by rullzer** [comment]
Actually @juliushaertl has a PR to fix the versioning in the sidebar. However it is not 13 compliant yet.
