### ISSUE TITLE
Comments overlapping so i can't edit them

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/richdocuments#3254]
**Describe the bug**
See this:
![Screenshot 2023-10-24 at 15 57 21](https://github.com/nextcloud/richdocuments/assets/551757/f2c3be2c-4ae1-4bf8-8b71-ae13ca600607)

Says it all, I guess. Firefox, on Mac OS, both latest version, on cloud.nextcloud.com

Happy to share the document.

**Comment by jospoortvliet** [comment]
Turns out, resizing the window moved stuff around - now it doesn't overlap anymore:
![Screenshot 2023-10-24 at 16 35 53](https://github.com/nextcloud/richdocuments/assets/551757/c5747c73-6746-42cd-b38d-074c27abcd66)


#magic

**Comment by thebearon** [comment]
Since this is an issue in Collabora Online, please file it over at: https://github.com/CollaboraOnline/online/issues/
Also, include more details about the window size.

**Comment by pedropintosilva** [comment]
Thanks @jospoortvliet for taking the time to report this and also for adding screenshots (it really helps).

@thebearon I don't think we need to close this. I would rather transfer it and keep the original history of it

**Comment by pedropintosilva** [comment]
It seems GitHub doesn't let me transfer issues to another org. I have manually created the new ticket (see above) . Thanks!

**Comment by timur-g** [comment]
There is a fix over there, in Review status.
