### ISSUE TITLE
Spanish translation of "New filename"

### ISSUE THREAD

**Issue by timar** [nextcloud/richdocuments#327]
l10n/es_419.js:    "New filename" : "Nuevo nombredearchivo",
l10n/es_419.json:    "New filename" : "Nuevo nombredearchivo",
l10n/es_CL.js:    "New filename" : "Nuevo nombredearchivo",
l10n/es_CL.json:    "New filename" : "Nuevo nombredearchivo",
l10n/es_CO.js:    "New filename" : "Nuevo nombredearchivo",
l10n/es_CO.json:    "New filename" : "Nuevo nombredearchivo",
l10n/es_CR.js:    "New filename" : "Nuevo nombredearchivo",
l10n/es_CR.json:    "New filename" : "Nuevo nombredearchivo",
l10n/es_DO.js:    "New filename" : "Nuevo nombredearchivo",
l10n/es_DO.json:    "New filename" : "Nuevo nombredearchivo",
l10n/es_EC.js:    "New filename" : "Nuevo nombredearchivo",
l10n/es_EC.json:    "New filename" : "Nuevo nombredearchivo",
l10n/es_GT.js:    "New filename" : "Nuevo nombredearchivo",
l10n/es_GT.json:    "New filename" : "Nuevo nombredearchivo",
l10n/es_HN.js:    "New filename" : "Nuevo nombredearchivo",
l10n/es_HN.json:    "New filename" : "Nuevo nombredearchivo",
l10n/es_MX.js:    "New filename" : "Nuevo nombredearchivo",
l10n/es_MX.json:    "New filename" : "Nuevo nombredearchivo",
l10n/es_NI.js:    "New filename" : "Nuevo nombredearchivo",
l10n/es_NI.json:    "New filename" : "Nuevo nombredearchivo",
l10n/es_PA.js:    "New filename" : "Nuevo nombredearchivo",
l10n/es_PA.json:    "New filename" : "Nuevo nombredearchivo",
l10n/es_PE.js:    "New filename" : "Nuevo nombredearchivo",
l10n/es_PE.json:    "New filename" : "Nuevo nombredearchivo",
l10n/es_PR.js:    "New filename" : "Nuevo nombredearchivo",
l10n/es_PR.json:    "New filename" : "Nuevo nombredearchivo",
l10n/es_PY.js:    "New filename" : "Nuevo nombredearchivo",
l10n/es_PY.json:    "New filename" : "Nuevo nombredearchivo",
l10n/es_SV.js:    "New filename" : "Nuevo nombredearchivo",
l10n/es_SV.json:    "New filename" : "Nuevo nombredearchivo",
l10n/es_UY.js:    "New filename" : "Nuevo nombredearchivo",
l10n/es_UY.json:    "New filename" : "Nuevo nombredearchivo",

These are wrong. Suggestion: "Nuevo nombre de archivo".  

This has to fixed in Transifex. E.g. @jospoortvliet has admin rights there.

**Comment by juliushaertl** [comment]
New translations have been pushed.
