### ISSUE TITLE
Nextcloud Collabora Document loading failed.

### ISSUE THREAD

**Issue by javito1081** [nextcloud/richdocuments#3270]
**Describe the bug**
When i try to open a document i get this error:
![Failed](https://github.com/nextcloud/richdocuments/assets/44751549/e1732638-a5d6-4fdc-9d17-89c01c182c20)

**To Reproduce**
1. Open any document
2. Get error Failed to load document

**Expected behavior**
Document should open without issues

**Screenshots**
Here
![Failed](https://github.com/nextcloud/richdocuments/assets/44751549/77fe8830-caea-46d2-8de7-b61fb228e6a5)

**Client details:**
 - OS: Ubuntu Server 22.04
 - Browser Chrome
 - Version 118.0.5993.118 (Official Build) (64-bit)
 - Device: Desktop

## Server details

**Operating system**: Ubuntu Server 22.04

**Web server: Apache2

**Database: MariaDB

**PHP version: 8.1.2

**Nextcloud version: 27.1.3

**Comment by joshtrichards** [comment]
Hi @javito1081 It's hard to be helpful without knowing what version/type/install method of Collabora Online you using with Nextcloud Office. This error is coming from CollaboraOnline and indicates a configuration problem with your reverse proxy setup:

- https://sdk.collaboraonline.com/docs/installation/Proxy_settings.html
- https://docs.nextcloud.com/server/latest/admin_manual/office/proxy.html

As this seems like a configuration issue not a bug, please use the Nextcloud Help Forum or other appropriate channels for troubleshooting assistance:

- https://github.com/nextcloud/richdocuments#support
- https://help.nextcloud.com/c/support/collabora/34
