### ISSUE TITLE
Nextcloud Office doesn't close when closing a document

### ISSUE THREAD

**Issue by timparker14** [nextcloud/richdocuments#3271]
Nextcloud Office editor doesn't close when closing a document (the document disappears but the editor remains open and can't be closed).

**To Reproduce**
1. Go to Files
2. Click on any document and wait for it to open
3. Click the "X"(Close document) symbol top right of editor screen

**Expected behavior**
Document closes and users returned to the files screen.

**Screenshots**

**Client details:**
 - OS: [e.g. Ubuntu]
 - Browser [Firefoxi]
 - Version [119.0]
 - Device: [Desktop]

## Server details

**Operating system**: Ubuntu 22.04.3 LTS

**Web server:** NGINX

**Database:** PostgreSQL 14.9

**PHP version:** 8.1.2

**Nextcloud version:** 27.1.1

**Version of the richdocuments app** Nextcloud Office 8.2.1

**Version of Collabora Online** 23.05.5.3

No errors in the logs

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
Could you check the browser console for errors reported during close?

**Comment by timparker14** [comment]
There are no errors reported in the console

**Comment by timparker14** [comment]
Very odd...Nothing has changed and nothing was rebooted. But this issue appears to have resolved itself. I have just opened and closed a document without issue.
