### ISSUE TITLE
Edit locally does not work with WOPI allow list

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#3299]
Edit locally tries to unlock the file using the WOPI endpoints which does not work if you have a wopi allow list configured.

**Comment by juliushaertl** [comment]
Having a separate endpoint for frontend unlock sounds the most sane to me.

One unresolved question, how does the unlock behave when other users are also joined the editing session

**Comment by pedropintosilva** [comment]
Something else I have discovered just outside of collaborative editing:

1. In the files view `…` -> `Edit locally`
2. Browser's native dialog appears 
3. Either choose cancel Or open (but make sure you nextcloud client doesn't have that instance configured)
4. Open file locally dialog appears and it's impossible to close the dialog
5. Press close button or `Continue editing online` -> see the web console errors
![image](https://github.com/nextcloud/richdocuments/assets/65948705/0a66d1ae-3aa1-44c8-92ad-95c505308465)


```javascript
15:21:27.767 Uncaught Error: Opening the viewer with a single string parameter is deprecated. Please use a destructuring object instead
    NextJS 79
[...]
15:21:37.913 Uncaught Error: Opening the viewer with a single string parameter is deprecated. Please use a destructuring object instead
    NextJS 77
```

<details>
15:21:08.909 [DEBUG] text: sending steps  
Object { app: "text", uid: "pedro", level: 0, steps: [], awareness: "AWABwqLizQEGWHsidXNlciI6eyJuYW1lIjoicGVkcm8iLCJjbGllbnRJZCI6NDMxNTI2MjEwLCJjb2xvciI6IiNiOGJlNjgiLCJsYXN0VXBkYXRlIjoxNzA0MjA1MTg1fX0=", version: 17845 }
text-init.js:2:13255
15:21:08.919 XHRPOST
https://tech-preview.nextcloud.com/apps/text/session/538194/push
[HTTP/1.1 200 OK 67ms]

15:21:09.009 [DEBUG] text: synced  
Object { app: "text", uid: "pedro", level: 0, version: 17845, steps: [] }
text-init.js:2:13255
15:21:09.825 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "pedro", level: 0 }
text-init.js:2:13255
15:21:09.832 XHRPOST
https://tech-preview.nextcloud.com/apps/text/session/538194/sync
[HTTP/1.1 200 OK 85ms]

15:21:09.923 [DEBUG] text: synced  
Object { app: "text", uid: "pedro", level: 0, version: 17845, steps: (1) […] }
text-init.js:2:13255
15:21:10.203 Error in parsing value for 'top'.  Declaration dropped. cool.html
15:21:10.322 [viewer] Received post message Clicked_Button 
Object { Id: "Open_Local_Editor" }
 false richdocuments-viewer.js:2:4142271
15:21:10.332 XHRGET
https://tech-preview.nextcloud.com/core/templates/message.html
[HTTP/1.1 200 OK 23ms]

15:21:14.956 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "pedro", level: 0 }
text-init.js:2:13255
15:21:14.966 XHRPOST
https://tech-preview.nextcloud.com/apps/text/session/538194/sync
[HTTP/1.1 200 OK 53ms]

15:21:15.031 [DEBUG] text: synced  
Object { app: "text", uid: "pedro", level: 0, version: 17845, steps: (1) […] }
text-init.js:2:13255
15:21:15.363 XHRGET
https://tech-preview.nextcloud.com/ocs/v2.php/apps/notifications/api/v2/notifications
[HTTP/1.1 304 Not Modified 68ms]

15:21:16.220 PostMessageService.sendPostMessage FRAME_DOCUMENT {"MessageId":"Get_Views","SendTime":1704205276221,"Values":{}} richdocuments-viewer.js:2:4115204
15:21:16.232 Error in parsing value for 'top'.  Declaration dropped. cool.html
15:21:16.235 [viewer] Received post message Get_Views_Resp 
Array [ {…} ]
 false richdocuments-viewer.js:2:4142271
15:21:16.242 XHRPOST
https://tech-preview.nextcloud.com/index.php/apps/richdocuments/wopi/files/466171
[HTTP/1.1 200 OK 68ms]

15:21:16.321 XHRPOST
https://tech-preview.nextcloud.com/ocs/v2.php/apps/files/api/v1/openlocaleditor
[HTTP/1.1 200 OK 76ms]

15:21:16.389 Navigated to nc://open/pedro@tech-preview.nextcloud.com/Meeting%20notes%20ongoing.odt?token=Co1UujYXRj7QRrRK5kwmNK7XeaaTSJ2tnHxz3ZYOnxb2XZhu8412RwlYNJIb6i472cTzzTagNMYumQmSnxLGvMzjH1kUcYNcwxrkxtxj88eylSttuKspb8HAfkADm2As
15:21:20.053 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "pedro", level: 0 }
text-init.js:2:13255
15:21:20.060 XHRPOST
https://tech-preview.nextcloud.com/apps/text/session/538194/sync
[HTTP/1.1 200 OK 71ms]

15:21:20.137 [DEBUG] text: synced  
Object { app: "text", uid: "pedro", level: 0, version: 17845, steps: (1) […] }
text-init.js:2:13255
15:21:23.909 [DEBUG] text: sending steps  
Object { app: "text", uid: "pedro", level: 0, steps: [], awareness: "AWABwqLizQEHWHsidXNlciI6eyJuYW1lIjoicGVkcm8iLCJjbGllbnRJZCI6NDMxNTI2MjEwLCJjb2xvciI6IiNiOGJlNjgiLCJsYXN0VXBkYXRlIjoxNzA0MjA1MTg1fX0=", version: 17845 }
text-init.js:2:13255
15:21:23.917 XHRPOST
https://tech-preview.nextcloud.com/apps/text/session/538194/push
[HTTP/1.1 200 OK 58ms]

15:21:23.984 [DEBUG] text: synced  
Object { app: "text", uid: "pedro", level: 0, version: 17845, steps: [] }
text-init.js:2:13255
15:21:25.165 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "pedro", level: 0 }
text-init.js:2:13255
15:21:25.181 XHRPOST
https://tech-preview.nextcloud.com/apps/text/session/538194/sync
[HTTP/1.1 200 OK 90ms]

15:21:25.280 [DEBUG] text: synced  
Object { app: "text", uid: "pedro", level: 0, version: 17845, steps: (1) […] }
text-init.js:2:13255
15:21:27.767 Uncaught Error: Opening the viewer with a single string parameter is deprecated. Please use a destructuring object instead
    NextJS 79
OCA.Viewer.open({ path: 'undefined' }):2:910424
15:21:30.332 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "pedro", level: 0 }
text-init.js:2:13255
15:21:30.349 XHRPOST
https://tech-preview.nextcloud.com/apps/text/session/538194/sync
[HTTP/1.1 200 OK 123ms]

15:21:30.486 [DEBUG] text: synced  
Object { app: "text", uid: "pedro", level: 0, version: 17845, steps: (1) […] }
text-init.js:2:13255
15:21:35.518 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "pedro", level: 0 }
text-init.js:2:13255
15:21:35.533 XHRPOST
https://tech-preview.nextcloud.com/apps/text/session/538194/sync
[HTTP/1.1 200 OK 110ms]

15:21:35.651 [DEBUG] text: synced  
Object { app: "text", uid: "pedro", level: 0, version: 17845, steps: (1) […] }
text-init.js:2:13255
15:21:37.913 Uncaught Error: Opening the viewer with a single string parameter is deprecated. Please use a destructuring object instead
    NextJS 77
OCA.Viewer.open({ path: 'undefined' }):2:910424
15:21:38.926 [DEBUG] text: sending steps  
Object { app: "text", uid: "pedro", level: 0, steps: [], awareness: "AWABwqLizQEIWHsidXNlciI6eyJuYW1lIjoicGVkcm8iLCJjbGllbnRJZCI6NDMxNTI2MjEwLCJjb2xvciI6IiNiOGJlNjgiLCJsYXN0VXBkYXRlIjoxNzA0MjA1MTg1fX0=", version: 17845 }
text-init.js:2:13255
15:21:38.934 XHRPOST
https://tech-preview.nextcloud.com/apps/text/session/538194/push
[HTTP/1.1 200 OK 82ms]

15:21:39.019 [DEBUG] text: synced  
Object { app: "text", uid: "pedro", level: 0, version: 17845, steps: [] }
text-init.js:2:13255
15:21:40.688 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "pedro", level: 0 }
text-init.js:2:13255
15:21:40.696 XHRPOST
https://tech-preview.nextcloud.com/apps/text/session/538194/sync
[HTTP/1.1 200 OK 66ms]

15:21:40.770 [DEBUG] text: synced  
Object { app: "text", uid: "pedro", level: 0, version: 17845, steps: (1) […] }
text-init.js:2:13255
15:21:41.082 XHRGET
https://tech-preview.nextcloud.com/apps/files/api/v1/stats
[HTTP/1.1 200 OK 73ms]

15:21:45.362 XHRGET
https://tech-preview.nextcloud.com/ocs/v2.php/apps/notifications/api/v2/notifications
[HTTP/1.1 304 Not Modified 82ms]

15:21:45.805 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "pedro", level: 0 }
text-init.js:2:13255
15:21:45.812 XHRPOST
https://tech-preview.nextcloud.com/apps/text/session/538194/sync
[HTTP/1.1 200 OK 63ms]

15:21:45.880 [DEBUG] text: synced  
Object { app: "text", uid: "pedro", level: 0, version: 17845, steps: (1) […] }
text-init.js:2:13255
15:21:49.419 XHRPUT
https://tech-preview.nextcloud.com/ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json
[HTTP/1.1 200 OK 65ms]

15:21:50.917 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "pedro", level: 0 }
text-init.js:2:13255
15:21:50.924 XHRPOST
https://tech-preview.nextcloud.com/apps/text/session/538194/sync
[HTTP/1.1 200 OK 69ms]

15:21:51.003 [DEBUG] text: synced  
Object { app: "text", uid: "pedro", level: 0, version: 17845, steps: (1) […] }
text-init.js:2:13255
15:21:53.926 [DEBUG] text: sending steps  
Object { app: "text", uid: "pedro", level: 0, steps: [], awareness: "AWABwqLizQEJWHsidXNlciI6eyJuYW1lIjoicGVkcm8iLCJjbGllbnRJZCI6NDMxNTI2MjEwLCJjb2xvciI6IiNiOGJlNjgiLCJsYXN0VXBkYXRlIjoxNzA0MjA1MTg1fX0=", version: 17845 }
text-init.js:2:13255
15:21:53.935 XHRPOST
https://tech-preview.nextcloud.com/apps/text/session/538194/push
[HTTP/1.1 200 OK 69ms]

15:21:54.008 [DEBUG] text: synced  
Object { app: "text", uid: "pedro", level: 0, version: 17845, steps: [] }
text-init.js:2:13255
15:21:56.034 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "pedro", level: 0 }
text-init.js:2:13255
15:21:56.045 XHRPOST
https://tech-preview.nextcloud.com/apps/text/session/538194/sync
[HTTP/1.1 200 OK 77ms]

15:21:56.129 [DEBUG] text: synced  
Object { app: "text", uid: "pedro", level: 0, version: 17845, steps: (1) […] }
text-init.js:2:13255
15:22:01.166 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "pedro", level: 0 }
text-init.js:2:13255
15:22:01.174 XHRPOST
https://tech-preview.nextcloud.com/apps/text/session/538194/sync
[HTTP/1.1 200 OK 139ms]

15:22:01.321 [DEBUG] text: synced  
Object { app: "text", uid: "pedro", level: 0, version: 17845, steps: (1) […] }
text-init.js:2:13255
15:22:06.349 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "pedro", level: 0 }
text-init.js:2:13255
15:22:06.362 XHRPOST
https://tech-preview.nextcloud.com/apps/text/session/538194/sync
[HTTP/1.1 200 OK 114ms]

15:22:06.488 [DEBUG] text: synced  
Object { app: "text", uid: "pedro", level: 0, version: 17845, steps: (1) […] }
text-init.js:2:13255
15:22:08.927 [DEBUG] text: sending steps  
Object { app: "text", uid: "pedro", level: 0, steps: [], awareness: "AWABwqLizQEKWHsidXNlciI6eyJuYW1lIjoicGVkcm8iLCJjbGllbnRJZCI6NDMxNTI2MjEwLCJjb2xvciI6IiNiOGJlNjgiLCJsYXN0VXBkYXRlIjoxNzA0MjA1MTg1fX0=", version: 17845 }
text-init.js:2:13255
15:22:08.934 XHRPOST
https://tech-preview.nextcloud.com/apps/text/session/538194/push
[HTTP/1.1 200 OK 61ms]

15:22:09.000 [DEBUG] text: synced  
Object { app: "text", uid: "pedro", level: 0, version: 17845, steps: [] }
text-init.js:2:13255
15:22:11.526 [DEBUG] text: [PollingBackend] Fetching steps 
Object { app: "text", uid: "pedro", level: 0 }
text-init.js:2:13255
15:22:11.533 XHRPOST
https://tech-preview.nextcloud.com/apps/text/session/538194/sync
[HTTP/1.1 200 OK 50ms]

15:22:11.595 [DEBUG] text: synced  
Object { app: "text", uid: "pedro", level: 0, version: 17845, steps: (1) […] }
text-init.js:2:13255

</details>
