### ISSUE TITLE
Insert images from Nextcloud file picker is broken

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#3312]
Insert images from Nextcloud doesn't seem to work currently.

https://sdk.collaboraonline.com/docs/advanced_integration.html#enableinsertremoteimage
https://sdk.collaboraonline.com/docs/postmessage_api.html#ui-insertgraphic

- File picker is showing up
- Post message is sent to Collabora
  - `{"MessageId":"Action_InsertGraphic","SendTime":1700635265941,"Values":{"filename":"photo-1498855592392-af2bf1e0a4c7.jpeg","url":"https://nextcloud.local/index.php/apps/richdocuments/assets/OHp61nN4gQMDLWNIp0rwueDGLOFyhoUlMfJU0Ll9KJO8uYJx6xfGZsaZzNGUL5zw"}}`
- No request happening from Collabora to load the image

```
Nextcloud master / richdocuments main 
COOLWSD version: 23.05.5.4 (git hash: fc0de5b (E))
LOKit version: Collabora Office 23.05.5.4 (git hash: 1681200)
Served by: Debian GNU/Linux 12 (bookworm)
Server ID: deae1ec0
```

**Comment by dsisysteme** [comment]
Same problem for us. Impossible to insert an image from Nextcloud (v27.1.4 and Richdocument 8.2.3) but it works from a local location.
After the rollback of our Collabora instance to 22.05, it works again, with the same Nextcloud and Richdocument versions.

**Comment by juliushaertl** [comment]
@pedropintosilva This would be good to check on the online side. As far as I see the URL is properly handed over to Collabora.

**Comment by pedropintosilva** [comment]
I can reproduce this
```javascript
13:34:12.781 [viewer] Received post message UI_InsertGraphic 
Object {  }
 false Office.vue:300
13:34:22.134 PostMessageService.sendPostMessage FRAME_DOCUMENT {"MessageId":"Action_InsertGraphic","SendTime":1702989262134,"Values":{"filename":"nb-mode-inverted.png","url":"https://share.collabora.com/index.php/apps/richdocuments/assets/QqeuBHjdtJzCW4lLnBNfYoJsFxsvDpsqdsOYA7jvJ0DSRIQmODtNPh6erBZsHSrN"}} postMessage.tsx:42:8

```

Could you take a look @eszkadev ?

**Comment by eszkadev** [comment]
I think it might be related to new coolwsd.xml setting: `net.lok_allow` where you need to specify allowed hosts for external communication.
List automatically includes directly allowed wopi hosts, but I guess you don't configured that but use default setting: "first wopi host is allowed".

Could you check if adding `nextcloud.local` to `net.lok_allow` fixes the problem?

**Comment by juliushaertl** [comment]
I've also seen this on our tech-preview instance where a wopi allow list is configured but will do some tests around that.

**Comment by eszkadev** [comment]
@juliushaertl you reported version: `23.05.5.4` , but feature I mentioned is since: `23.05.6.2`, so it is not a source of a problem, sorry for noise

**Comment by eszkadev** [comment]
I'm working on better warning presentation for `net.lok_allow`: https://github.com/CollaboraOnline/online/pull/7863
Also I can confirm the bug in `23.05.5.4` (it fails in core to fetch the image), but when testing with newer versions it works as expected for me.

**Comment by juliushaertl** [comment]
I can confirm this works as expected on the latest release 25.05.6.4
