### ISSUE TITLE
Change selection keyboard shortcuts on macOS

### ISSUE THREAD

**Issue by NoahPeeters** [nextcloud/richdocuments#3323]
**Describe the bug**
When I edit the text in Nextcloud Write (e.g. an odt document), the default keyboard shortcuts to change the current selection does not work correctly.
The Shortcuts I'm referring to:
- shift + arrow (left-right) to change the selection by one character
- shift + option + arrow (left-right) to change the selection by one word
- shift + cmd + arrow (left-right) to change the selection to the beginning/end of line

**To Reproduce**
1. Open a document
2. Write some text in the document body
3. Make a selection (either with the mouse of the keyboard)
4. Press shift + option + arrow (left)

**Expected behavior**
The selection should be extended by one word to the left, Instead, nothing happens.

shift + cmd + arrow (left) should extend the selection to the beginning of the line, instead, it extends the selection by one word (the expected behavior for option, not cmd)

The shortcuts work everywhere else (at least everywhere I tested). This includes both the main Nextcloud UI (e.g. renaming files) as well as nextcloud office (e.g. in the font selection)

**Client details:**
 - OS:macOS
 - Browser safari
 - Device: M1 MacBook Pro

## Server details

I am running the latest version of Nextcloud AIO with the following containers:
- Apache
- Database
- Nextcloud
- Notify Push
- Redis
- Collabora
- Imaginary
- Fulltextsearch
- Docker Socket Proxy

**Operating system**:
`Linux v2202102141689143652 4.19.0-25-amd64 #1 SMP Debian 4.19.289-2 (2023-08-08) x86_64 GNU/Linux`

**Web server:**
`Apache/2.4.58`

**Database:**
`PostgreSQL 15.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit`

**Nextcloud version:**
`27.1.3`

**Comment by juliushaertl** [comment]
This is an upstream issue in Collabora Online, already reported at https://github.com/CollaboraOnline/online/issues/7689
