### ISSUE TITLE
unable to click share button (NC15 & richdocuments 3.0.6)

### ISSUE THREAD

**Issue by himpierre** [nextcloud/richdocuments#333]
### Steps to reproduce
1. Open Document (odt in my case)
2. Try to click the share icon on the upper right side next to the bell button
3. Nothing happens

### Expected behaviour

Nothing.

### Actual behaviour

Sidebar should open.

### Server configuration

**Operating system**:

Ubuntu 18.04

**Web server:**

Apache.

**Database:**

MariaDB.

**PHP version:**

PHP-7.2

**Nextcloud version:** (see Nextcloud admin page)

15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**

Fresh installation.

**Comment by juliushaertl** [comment]
Already fixed on master by #321
