### ISSUE TITLE
is issue?

### ISSUE THREAD

**Issue by tbs575** [nextcloud/richdocuments#3355]
**Describe the bug**
upgrade nextcloud 25.0.13-fpm to 26.0.9-fpm, version icon missing

**To Reproduce**
1. just replace nextcloud container version from 25.0.13-fpm to  26.0.9-fpm
2. Using richdocuments-v8.0.6
3. editing docx file
4. see document version, found icon missing

**Expected behavior**

**Screenshots**
![image](https://github.com/nextcloud/richdocuments/assets/30616402/ac8073b2-e55d-49d8-992a-610e0159b56a)

**Client details:**
 - OS: Windows 
 - Browser: Chrome
 - Version 120.0.6099.71
 - Device: destop

## Server details

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:**

**Version of the richdocuments app**

**Version of Collabora Online**

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
This is currently expected behaviour if no preview generator is available for office documents.
