### ISSUE TITLE
Anonymous users can use Collabora and can edit the document in publicly share link

### ISSUE THREAD

**Issue by hammeractual** [nextcloud/richdocuments#3358]
**Describe the bug**

Anonymous users in publicly share link by users associated to a group that is allowed in the Nextcloud Richdocuments App's Permission config ("Restrict usage to specific groups" and  "Restrict edit to specific groups") can use Collabora and can edit the document when folder/file share permission is set to Can Edit.

**To Reproduce**

**Expected behavior**

Anonymous users in publicly share link by users associated to a group that is allowed in the Nextcloud Richdocuments App's Permission config ("Restrict usage to specific groups" and  "Restrict edit to specific groups") can't use Collabora and can't edit the document even when folder/file share permission is set to Can Edit.

**Screenshots**
![jknjnlk;ml](https://github.com/nextcloud/richdocuments/assets/10388725/5f72be71-77ba-4c4b-8692-af071b60ab6b)

**Client details:**
 - OS: Windows 11
 - Browser: Chrome, Edge
 - Version: Latest version
 - Device: Desktop

## Server details

**Operating system**: Ubuntu 22.04

**Web server:** Apache 2.4.52

**Database:** MariaDB 10.11.6

**PHP version:** 8.2.13

**Nextcloud version:** 28.0.0

**Version of the richdocuments app:** 8.3.0

**Version of Collabora Online:** 23.05.5.2

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
Thanks for reporting, I pushed a fix in https://github.com/nextcloud/richdocuments/pull/3372
