### ISSUE TITLE
Error being thrown to log Error Call to undefined method OCA\Richdocuments\Service\DiscoveryService::refetch() Could not boot richdocuments: Call to undefined method OCA\Richdocuments\Service\DiscoveryService::refetch()

### ISSUE THREAD

**Issue by Jeefongithub** [nextcloud/richdocuments#3363]
**Describe the bug**

Getting the following error thrown to the log every few seconds. It doesn't seem to be affecting any of my workloads but I'd like to try and identify how to solve it

 Error Call to undefined method OCA\Richdocuments\Service\DiscoveryService::refetch()
Could not boot richdocuments: Call to undefined method OCA\Richdocuments\Service\DiscoveryService::refetch()

**To Reproduce**
1. Go to admin settings
2. scroll down to logging
3. error is presented

**Expected behavior**

unsure

**Screenshots**

![image](https://github.com/nextcloud/richdocuments/assets/53583661/65625d00-1dae-4d38-b5a7-5a0501df5ae2)

**Client details:**
 - OS: Debian 12
 - Browser Floorp (firefox fork)
 - Version 11.6.1
 - Device: Laptop

## Server details

**Operating system**: Debian 12

**Web server:** Apache 2.4.56

**Database:** MariaDB 10.5.21

**PHP version:** 8.2.13

**Nextcloud version:** 28.0.0

**Version of the richdocuments app** 8.3.0

**Version of Collabora Online** 25.5.602

#### Nextcloud log (data/nextcloud.log)

```
{
  "reqId": "aotXjCZpSlFyOnqxkmgS",
  "level": 4,
  "time": "2023-12-16T13:13:08+00:00",
  "remoteAddr": "192.168.55.4",
  "user": "Jeef",
  "app": "no app in context",
  "method": "GET",
  "url": "/index.php/apps/logreader/api/poll?lastReqId=",
  "message": "Could not boot richdocuments: Call to undefined method OCA\\Richdocuments\\Service\\DiscoveryService::refetch()",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0",
  "version": "28.0.1.0",
  "exception": {
    "Exception": "Error",
    "Message": "Call to undefined method OCA\\Richdocuments\\Service\\DiscoveryService::refetch()",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/nextcloud/apps/richdocuments/lib/AppInfo/Application.php",
        "line": 154,
        "function": "checkAndEnableCODEServer",
        "class": "OCA\\Richdocuments\\AppInfo\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php",
        "line": 200,
        "function": "boot",
        "class": "OCA\\Richdocuments\\AppInfo\\Application",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/App/AppManager.php",
        "line": 434,
        "function": "bootApp",
        "class": "OC\\AppFramework\\Bootstrap\\Coordinator",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/App/AppManager.php",
        "line": 213,
        "function": "loadApp",
        "class": "OC\\App\\AppManager",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/legacy/OC_App.php",
        "line": 125,
        "function": "loadApps",
        "class": "OC\\App\\AppManager",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/base.php",
        "line": 1049,
        "function": "loadApps",
        "class": "OC_App",
        "type": "::"
      },
      {
        "file": "/var/www/html/nextcloud/index.php",
        "line": 39,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/var/www/html/nextcloud/apps/richdocuments/lib/AppInfo/Application.php",
    "Line": 226,
    "message": "Could not boot richdocuments: Call to undefined method OCA\\Richdocuments\\Service\\DiscoveryService::refetch()",
    "exception": {},
    "CustomMessage": "Could not boot richdocuments: Call to undefined method OCA\\Richdocuments\\Service\\DiscoveryService::refetch()"
  }
}
```

**Comment by aml125** [comment]
Having the same problem here after last update. I'm using the truenas scale offical app version.

**Comment by juliushaertl** [comment]
Can you post the full log trace?

**Comment by Jeefongithub** [comment]
[nextcloud.log](https://github.com/nextcloud/richdocuments/files/13696559/nextcloud.log)

**Comment by thejudderman** [comment]
Same problem

 `occ app:disable richdocumentscode`  no more errors, but would like to have CODE Office solution back up and running at some point !

**Comment by MatthiasGer0821** [comment]
Same problem. Any idea what could help? I really need my CODE office solution :-(

**Comment by manuelkamp** [comment]
Also having this issue, it is flooding my logs since update to 28 (still in 28.01 present). There needs to be a fix soon!

**Comment by SMH17** [comment]
This issue has been introduced after a recent update. Seems it is needed to release an update of `richdocumentscode` to address this problem.

**Comment by witzker** [comment]
Someone working on this?
How can we help?
Additional Info needed?

**Comment by damarges** [comment]
Has anyone tried out to run the CODE Environment in a separate docker container? Do the error messages disappear then?

**Comment by joshtrichards** [comment]
Feel free to try out the proposed fix in #3380.

**Comment by manuelkamp** [comment]
thx, that works for me

**Comment by damarges** [comment]
I Got the Errors fixed by running CODE on own Server.
