### ISSUE TITLE
Redesign guest name input

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#3368]
As brought up by @jancborchardt 

- reference for asking guest name from Talk: https://github.com/nextcloud/spreed/pull/10467
- We need to show the input before loading the document as we need to pass the name along to Collabora
- We can take the opportunity to get rid of quite some legacy code there then and do it properly with new vue components

**Comment by jancborchardt** [comment]
FYI @szaimen assigned you for the design part since you did the same for Talk, but since it’s already done for Talk I don’t think much more is needed, right @juliushaertl? Just so it is known who can answer follow-up questions.

**Comment by juliushaertl** [comment]
Just to confirm, clarify on how I would imagine the adapted talk mockup to public file shares, however if a quick mockup can be provided that is probably the best:

- Opening a single public share link shows the public share link page in the background and opens the modal directly to enter the name, once confirmed the name the document will open
- On a shared folder we will show the modal once the user opens a file, once confirmed the name the document will open
- The modal would show:
  - "Enter your name to join the "My document.odt" as a guest."
  - Input to enter the name, prefilled with a placeholder "Anonymous guest"
  - Button to "Submit name and join"
  - Talk shows the call icon and name, should we show something similar as the header of the modal?

**Comment by juliushaertl** [comment]
@elzody Since you are checking the other ticket about the guest name picker, this might be valuable input to consider when recreating the picker in vue
