### ISSUE TITLE
Cannot declare class OCA\\Richdocuments\\Controller\\DocumentController, because the name is already in use

### ISSUE THREAD

**Issue by sgofferj** [nextcloud/richdocuments#337]
Setup:
NC 14.3, discrete installation, updated from Owncloud ages ago
CODE discrete installation
Ubuntu 18.04
Apache/PHP7
Nextcloud running with SSL
loolwsd running behind Apache reverse proxy on same VM
loolwsd reachable via http://<ip>:9980 and https://proxyaddress
https://proxyaddress/hosting/discovery shows valid XML output
Double checked NC Collabora config.

Symptom:
Trying to create an office file leads to a white screen with NC header.
Nothing appears in NC log
No connect appears in loowsd log
Apache error log shows:
[Sun Dec 30 22:52:44.914357 2018] [php7:error] [pid 9295] [client RFC1918IP:33996] PHP Fatal error:  Cannot declare class OCA\\Richdocuments\\Controller\\DocumentController, because the name is already in use in /var/www/ssl/cloud/apps/richdocuments/lib/Controller/DocumentController.php on line 0

I can provide a testaccount if required.

**Comment by Rbillon59** [comment]
Hi,

Same error.

**Comment by Rbillon59** [comment]
Hi,

I encountered the same issue while creating a document without selecting a template. 
It works fine if i select the template.

Hope this help

**Comment by juliushaertl** [comment]
The error actually looks a bit weired, since we definitely only specificy DocumentController once. Please check the Nextcloud logs for more details on that error. Can you try to remove the richdocuments app folder and install it again?

**Comment by sgofferj** [comment]
Sorry for the delay in replying. I don't see the issue any more after updating to 14.0.5

**Comment by juliushaertl** [comment]
Thanks for reporting back, let's close this.
