### ISSUE TITLE
W

### ISSUE THREAD

**Issue by SMH17** [nextcloud/richdocuments#3417]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client details:**
 - Device: [e.g. iPhone6, desktop]

## Server details

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:**

**Version of the richdocuments app**

**Version of Collabora Online**

**Configuration of the richdocuments app**
```
Insert the output of `./occ config:list richdocuments` (or equivalent adapted for your runtime environment)
```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by Alessandrali** [comment]
Insert the output of `./occ config:list richdocuments` (or equivalent adapted for your runtime environment)
