### ISSUE TITLE
Revision history has an extra closing "X" that doesn't hide sidebar

### ISSUE THREAD

**Issue by thebearon** [nextcloud/richdocuments#342]
Note the two closing "X" symbols when revision history is open:
- one on the revision history sidebar (this has always been there),
- one in the document viewer (this is new in 3.1.0).

Using the one in the document viewer returns to edit mode, but doesn't close the sidebar.

Btw, nice to see that switching revisions is working fine again, thanks @juliushaertl! Could this be related to that fix?

**Comment by juliushaertl** [comment]
> Btw, nice to see that switching revisions is working fine again, thanks @juliushaertl! Could this be related to that fix?

Yes, indeed it makes sense to just close the sidebar, if the viewer is hidden.

**Comment by thebearon** [comment]
> Yes, indeed it makes sense to just close the sidebar, if the viewer is hidden.

I am not sure what "viewer is hidden" means here. In the meantime it seems the behavior is different once again, now the two "X"-es are independent, one only closes the revision history sidebar, and the other returns from the read-only document to the edited one.

The expectation would be to have one single "X" (preferably in the sidebar), which return from the revision history to the editing session.
