### ISSUE TITLE
Fonts still didn't show the preview in the Richdocuments App's Config

### ISSUE THREAD

**Issue by hammeractual** [nextcloud/richdocuments#3425]
**Describe the bug**
Fonts still didn't show the preview in the Richdocuments App's Config while the physical file exist in the server directory.

**To Reproduce**

**Expected behavior**
All fonts show the preview

**Screenshots**
![Error](https://github.com/nextcloud/richdocuments/assets/10388725/30913d5c-8605-4d57-87bd-be6eb5125121)

**Client details:**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 120.0.6099.224
 - Device: Desktop

## Server details

**Operating system**: Ubuntu 22.04

**Web server:** Apache 2.4

**Database:** MariaDB 10.11

**PHP version:** 8.2

**Nextcloud version:** 28.0.1

**Version of the richdocuments app:** 8.3.1

**Version of Collabora Online:** 23.05.6.3

**Configuration of the richdocuments app**
```
Insert the output of `./occ config:list richdocuments` (or equivalent adapted for your runtime environment)
```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
Could you try running the `occ richdocuments:install-fonts` command to update the font files from the shipped ones again and see if that makes any difference?

**Comment by hammeractual** [comment]
> Could you try running the `occ richdocuments:install-fonts` command to update the font files from the shipped ones again and see if that makes any difference?

WoW thanks, it works! 

![zzzzz](https://github.com/nextcloud/richdocuments/assets/10388725/40b7ba76-f40b-4672-905b-e0a33e3d5e64)
![sdsadsad](https://github.com/nextcloud/richdocuments/assets/10388725/8ad07fa4-a78e-4680-94b4-16d45a23cd1a)

However, I think this app should improve the mechanism to install the fonts so that the fonts preview could function properly without any manual overriding with occ richdocuments:install-fonts first. :)

**Comment by juliushaertl** [comment]
I think such a repair step makes sense but is tricky. We could add a button to the UI to restore the default fonts, but currently that is not a priority. I'll close this but we would welcome any contribution of course in case someone wants to work on this.
