### ISSUE TITLE
Cannot open LibreOffice files via the android app since 3-4 weeks

### ISSUE THREAD

**Issue by Stamp81** [nextcloud/richdocuments#3437]
Hello, I have a problem by opening LibreOffice documents via the android app since 3-4 weeks.
When I click on a document, I am taken to an infinite loading screen. This only happens with my Android devices, with Apple devices everything works as usual. Everything also works on the browser.

I use:
Nextcloud 27.1.5 
Nextcloud Office 8.2.4
Collabora 23.5.705

I have seen that there was a similar problem in the past, which has probably been fixed by a patch.
Could it be that the same problem has reappeared?
https://github.com/nextcloud/richdocuments/issues/2873

**Comment by joshtrichards** [comment]
What version of the Android client? If v3.27.0 then it's a bug in that version (nextcloud/android#12338) and already fixed (in nextcloud/android#12350). It'll be in v3.27.1.

**Comment by Stamp81** [comment]
Thank you for your help.

I have the v3.27.0 on all devices (Germany).
Do you know when the next version will be released?

**Comment by joshtrichards** [comment]
Real Soon(tm). (I'm not certain, but would not be surprised if it was in the next few days).
