### ISSUE TITLE
Wrong default date time format.

### ISSUE THREAD

**Issue by kamilko** [nextcloud/richdocuments#3447]
In spreadsheet comments or tooltip long date is always formatted as M/D/Y type.

How to reproduce:
- have your zone date format as D/M/Y
- add comment (while doing this, comment date will be displayed properly)
- save comment and then display comment tooltip
- date format will be always as M/D/Y

This was tested on many different version of Nextcloud as well as many different version of OS (mostly Debian and Ubuntu, also snap version of Nextcloud).
Also it doesn't matter what locale is on server or user system, as long it isn't M/D/Y.

![image](https://github.com/nextcloud/richdocuments/assets/5320088/5b38c018-1f4c-40a7-804f-b296fc87303d)
![image](https://github.com/nextcloud/richdocuments/assets/5320088/a0f30950-a842-4ed5-8f3b-14ead45fd745)
![image](https://github.com/nextcloud/richdocuments/assets/5320088/e55de28a-7659-4a4d-ad6a-b3b3c3b7cb77)

**Comment by timur-g** [comment]
@kamilko this seem to depend on the sheet, and NC locale settings. Please attach test sheet. Today is 01 Feb so you may write there to be clear, when show wrongly it is 02 Jan, please take screenshots and put in the file aside to the comments. 
In my test, seems that comment is always written to ODS as 02/01 regardless if I see it as 01 Feb for a user that has such a locale. That would mean that 31/12 is used to write and locale to read. 
But I cannot say why I see this in some sheets and not others, which does not seem related to cell format setting.

**Comment by kamilko** [comment]
This are another examples:
![image](https://github.com/nextcloud/richdocuments/assets/5320088/df38daab-4504-4a4a-97c6-407cfbaa1490)
![image](https://github.com/nextcloud/richdocuments/assets/5320088/8c59e957-1e9b-4a80-ae60-3db161d822fa)
So writing comment dialog has proper date, but as soon as you save and hover over, you get US formatted date.

And also attached file from screenshots.
[test.ods](https://github.com/nextcloud/richdocuments/files/14123833/test.ods)

As you can see, locale for server are set as PL however tooltip has US date. BTW there are some part which are always not translated when richdocummentscode is used. To get everything in PL standalone CODE server must be installed and all the localized libraries must be with -pl version - but I digress.

ServerOS: Ubuntu LTS 22.04 with Nextcloud installed as snap package.

**Comment by juliushaertl** [comment]
Thanks for reporting. We hand over the user locale to Collabora so it seems that this is an upstream issue. This issue tracker is only for the Nextcloud connector app named Collabora Online. For issues with Collabora Online itself, please open a bug report at: https://github.com/collaboraonline/online

**Comment by jazevedo-coll** [comment]
just for completion, this has been fixed with: https://github.com/CollaboraOnline/online/pull/11212 and will be available in version: 24.04.13-3
