### ISSUE TITLE
Insert hyperlink can not paste

### ISSUE THREAD

**Issue by Bables55** [nextcloud/richdocuments#345]
### Steps to reproduce
1. Open Calc, Documents data.
2. Selet characters.
3. Choose a hyperlink from the Insert menu or Toolbar.
4. Paste from the clipboard into every text field.

### Expected behaviour
Characters are pasted on Collabora Office 6.0-18/loolwsd 4.0.0.

### Actual behaviour
Nothing is pasted by any methods.
The same is true for characters copied in Collabora.
In Mac, trying to paste into the text field of the dialog will replace the original text. Then I can not close the dialog.
In iPhone, even if the hyperlink dialog is displayed, it can not operate anything.
 
The problem is not only Hyperlink, it seems that paste input can not be done in the whole dialog displayed in Collabora.

### Server configuration

**Operating system**:
CentOS 7.6
**Web server:**
nginx 1.14.1
**Database:**
MariaDB 10.2.21
**PHP version:**
PHP 7.2.13
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 15.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
14.0.4
**Where did you install Nextcloud from:**
Nextcloud
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
[PC]Firefox 60 ESR , Vivaldi 2.2.37
{Smartphone] Safari
**Operating system:**
Windows10, macOS 10.14
iOS12.1
#### Web server error log
<details>
<summary>Web server error log</summary>
```
none
```
</details>

**Comment by juliushaertl** [comment]
Thanks for your bug report. This issue tracker is only targeting the collabora integration inside Nextcloud. Your issue is actually related to Collabora/LibreOffice Online, so please head over to https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online for reporting.
