### ISSUE TITLE
[richdocuments] Error: Failed to fetch the Collabora capabilities endpoint (1000s of occurances)

### ISSUE THREAD

**Issue by unknownuserisknown** [nextcloud/richdocuments#3459]
**Describe the bug**
Error log contains thousands of these errors:

`[richdocuments] Error: Failed to fetch the Collabora capabilities endpoint: cURL error 7: Failed to connect to localhost port 80: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost/apps/richdocumentscode/proxy.php?req=/hosting/capabilities
	GET /ocs/v2.php/apps/user_status/api/v1/user_status?format=json
	from [IP ADDRESS] by [NEXTCLOUD USER] at Feb 3, 2024, 11:00:25 AM`

The error is thrown in pairs (two identical in content) approximately every 5 minutes.

**To Reproduce**
1. Updated to Nextcloud 28.0.2, latest versions of CODE server and Nextcloud Office are installed.
2. Monitor Log

**Expected behavior**
No errors.

**Screenshots**

## Server details

**Operating system**: Ubuntu 20.04.6 LTS

**Web server:** 

**Database:** mysql 10.3.39

**PHP version:** 8.3.2

**Nextcloud version:** 28.0.2

**Version of the richdocuments app** 8.3.1

**Version of Collabora Online** 23.5.705

**Configuration of the richdocuments app**
```
{
    "apps": {
        "richdocuments": {
            "disable_certificate_verification": "yes",
            "edit_groups": "",
            "enabled": "no",
            "installed_version": "8.3.1",
            "public_wopi_url": "https:\/\/cloud.orangekarat.com\/apps\/richdocumentscode\/proxy.php?req=",
            "types": "prevent_group_restriction",
            "use_groups": "",
            "wopi_allowlist": "",
            "wopi_url": "https:\/\/cloud.orangekarat.com\/apps\/richdocumentscode\/proxy.php?req="
        }
    }
}
```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by joshtrichards** [comment]
I assume Collabora does not work at all? It's not just these errors you're seeing, correct?

Did you initially activate from the web UI or was it via `occ`?

Your config indicates:

```
            "wopi_url": "https:\/\/cloud.orangekarat.com\/apps\/richdocumentscode\/proxy.php?req="
```

But the log says it's using `localhost` as well as `http` so something is wrong here.

Does the problem go away when you either toggle in the Web UI between *Use own Server* and back to *Use built-in* (or run `occ richdocuments:activate-config` from the command-line)?

**Comment by unknownuserisknown** [comment]
Colabora was activated via the webui and it's working well. I'm able to successfully load and edit documents with Nextcloud office. I only noticed this problem because I received a warning in the admin panel that several thousands of errors were in the log.

I have not made any changes to the default configuration of Nextcloud Office since I installed it. When navigate to the Office admin settings, this is what is reported:

![image](https://github.com/nextcloud/richdocuments/assets/109682984/ea40f140-5c3d-4b23-9b36-280ae1cab89c)

I upgraded Nextcloud server 28.0.2 from that last incremental release of 27. I try to keep my instance as up to date as possible.

I'm using `redis` for `memcache`

And here is the output of `occ config:list system`

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.orangekarat.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.2.5",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "US",
        "skeletondirectory": "",
        "mail_smtpport": "465",
        "app_install_overwrite": [
            "documentserver_community",
            "impersonate",
            "richdocumentscode",
            "groupfolders",
            "files_rightclick"
        ],
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Movie",
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\MP4",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF"
        ],
        "mail_smtpauth": 1,
        "mail_smtpsecure": "ssl",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance_window_start": 6
    }
}
```

**Comment by joshtrichards** [comment]
>         `"overwrite.cli.url": "http:\/\/localhost",`

Is there a reason you're using `http://localhost` in your `overwrite` here?

**Comment by unknownuserisknown** [comment]
> > ```
> >     `"overwrite.cli.url": "http:\/\/localhost",`
> > ```
> 
> Is there a reason you're using `http://localhost` in your `overwrite` here?

As far as I know that was set up automatically, and I must confess I don't even know what that setting does. I have only made a few modifications to the configuration apart from using the webui (like for setting up the readis cache).

**Comment by joshtrichards** [comment]
It's possible it was set if you initially installed via `http://localhost`.

It should be the full URL used to access your Nextcloud Server instance. So it sounds like you should change it to `https://cloud.orangekarat.com` in your case. Then restart your web (if using mod_php) or fpm (if using) service.

**Comment by unknownuserisknown** [comment]
> It's possible it was set if you initially installed via `http://localhost`.
> 
> It should be the full URL used to access your Nextcloud Server instance. So it sounds like you should change it to `https://cloud.orangekarat.com` in your case. Then restart your web (if using mod_php) or fpm (if using) service. Then see if your problem goes away.

I will make that change and will see if that clears the issue!

**Comment by unknownuserisknown** [comment]
I made the change and re-enabled `richdocuments` and `Colabra`. After about 30 minutes or so no of monitoring, I see no new errors in the log. Thank you for your help!

**Comment by joshtrichards** [comment]
:+1:

**Comment by mauriceKA** [comment]
The solution of changing the overwrite to the full server address also worked for me! Thanks a bunch!
