### ISSUE TITLE
[Bug]: Unable to uncheck 'restrict usage/edit to specific groups' in Nextcloud Admin Settings

### ISSUE THREAD

**Issue by isdnfan** [nextcloud/richdocuments#3506]
**Describe the bug**
- once checked both values can not be unchecked.
error is logged in browser console

**To Reproduce**
1. Go to 'https://cloud.mydomain/settings/admin/richdocuments)'
2. Check the checkbox 'restrict usage to specific groups'
3. try to unCheck the checkbox 'restrict usage to specific groups'
4. in browser console see error 'TypeError: this.value.filter is not a function'

**Expected behavior**
settings could be checked/unchecked

**Screenshots**
![image](https://github.com/nextcloud/richdocuments/assets/18125597/7f9d5219-b7e1-4dcf-8b5c-ce31ec351d4c)

**Client details:**
 - OS: Windows
 - Browser Firefox

## Server details

**Operating system**: docker community edition
**Web server:** Apache
**Database:** MariaDB
**PHP version:** 8.2
**Nextcloud version:** 28.0.2
**Version of the richdocuments app** 8.3.1
**Version of Collabora Online** 23.05.6.4
**Configuration of the richdocuments app**
```
    "richdocuments": {
      "canonical_webroot": "",
      "doc_format": "",
      "edit_groups": "",
      "enabled": "yes",
      "external_apps": "",
      "installed_version": "8.3.1",
      "public_wopi_url": "https://collabora.mydomain.tld",
      "types": "prevent_group_restriction",
      "use_groups": "",
      "wopi_allowlist": "172.16.0.0/12,fd00:feed:beef::/48",
      "wopi_url": "https://collabora.mydomain.tld"
    }
```

initially reported at https://help.nextcloud.com/t/nextcloud-collabora-code-docker-compose-almost-everything-is-working-except-it-isnt/183450

**Comment by isdnfan** [comment]
similar to #3377

**Comment by lftsy** [comment]
FYI, here is the woraround I used

```
root@ifrit:[~]# sudo -u www-data php --define apc.enable_cli=1 /var/www/nextcloud/occ config:app:delete richdocuments use_groups
Config value use_groups of app richdocuments deleted

root@ifrit:[~]# sudo -u www-data php --define apc.enable_cli=1 /var/www/nextcloud/occ config:app:delete richdocuments edit_groups
Config value edit_groups of app richdocuments deleted
```

**Comment by RealKoenisch** [comment]
This bug goes even deeper. In case you set in case you restrict the usage the groups (1st option) for all non listed groups the folder management is broken - click on o folder for users in groups without office access will lead to a download, instead of openingg the folder; right click on the folder will not shown the nextcloud menu, the display of the the shared sources is not shwon and finally the 3-horizontal dots are missing as well.

KR

**Comment by steadfasterX** [comment]
I can confirm what @RealKoenisch wrote, see: https://help.nextcloud.com/t/upgrade-28-29-right-click-menu-stopped-working/190537

**Comment by RealKoenisch** [comment]
> This bug goes even deeper. In case you limit the usage of office by restricing the groups (1st option), for all non listed groups the folder management is broken - click on o folder for users in groups without office access will lead to a download, instead of opening the folder; right click on the folder will not shown the nextcloud menu, the display of the the shared sources is not shown (icon is missing) and finally the 3-horizontal dots are missing as well.
> 
> User of a group without access to office ![image](https://private-user-images.githubusercontent.com/93999424/328043442-d1fcfcc1-0af0-48b6-8aef-e4d4a01f07bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNzYxMjEsIm5iZiI6MTcxNTM3NTgyMSwicGF0aCI6Ii85Mzk5OTQyNC8zMjgwNDM0NDItZDFmY2ZjYzEtMGFmMC00OGI2LThhZWYtZTRkNGEwMWYwN2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDIxMTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNjg0ODJhMjUzZTYxNWI2ODdlMjhkZDUyMjQ0MjIxMjAyZTlmMmE2NmNiOTJhMzBlMzQ2NzhlMmZhZDEyMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zHlK332Ifcd_wSe_igFHN1Sf_5WwabS4I522IaZtMYU)
> 
> User with access to office ![image](https://private-user-images.githubusercontent.com/93999424/328043478-2d7aa62c-56c1-4379-b16c-7f40bd847766.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNzYxMjEsIm5iZiI6MTcxNTM3NTgyMSwicGF0aCI6Ii85Mzk5OTQyNC8zMjgwNDM0NzgtMmQ3YWE2MmMtNTZjMS00Mzc5LWIxNmMtN2Y0MGJkODQ3NzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDIxMTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3Nzk4ZTRkYTAzNGE5ZjMzNjM0NmQwMTNmNWI3ZjhjNjA1ODUzYTA1ZThmNDg4YjhlOWE3NzM5NmY1YmM2MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OoDAg3UjSXNkXlT_AFEKFRY4rsvSnmSWa61uG-oFDQY)
> 
> ![image](https://private-user-images.githubusercontent.com/93999424/328042763-f3d1104f-b4b2-4b9c-97d2-44f8fe3d96e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNzYxMjEsIm5iZiI6MTcxNTM3NTgyMSwicGF0aCI6Ii85Mzk5OTQyNC8zMjgwNDI3NjMtZjNkMTEwNGYtYjRiMi00YjljLTk3ZDItNDRmOGZlM2Q5NmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDIxMTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNzI5NDhkNmJhNDIxZTRkNjU2ZWNhMDQ0ODdhNzNkYjA5NTJkZGMxMzNlYTNkNWFlODlkYTJjYjc1ZGU2M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._4tdvFAP64H-DVAmcnav0vzU_7UdnT1p-GWwywPSjE8)
> 
> KR

In the actual release Version I can limit again the access to office without breaking the folder management. Unchecking is still buggy.

KR Koenisch
