### ISSUE TITLE
Nextcloud Office breaks cron with call to OC\BackgroundJob\TimedJob

### ISSUE THREAD

**Issue by cfuller** [nextcloud/richdocuments#3523]
**Describe the bug**
On every cron run, the following error is thrown by this app, causing cron to fail:
Error: Class "OC\BackgroundJob\TimedJob" not found in /var/www/nextcloud/apps/richdocuments/lib/Backgroundjobs/ObtainCapabilities.php:29

**To Reproduce**
1. Enable system cron to run background jobs
2. Install and Enable Nextcloud Office
3. See error

**Expected behavior**
Background jobs run via system cron with no errors

**Client details:**
- Any

## Server details

**Operating system**: Ubuntu 20.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 8.2

**Nextcloud version:** Nextcloud Hub 8 (29.0.0 beta 2)

**Version of the richdocuments app** 8.4.0-beta.1

**Version of Collabora Online**

**Configuration of the richdocuments app**
```
Insert the output of `./occ config:list richdocuments` (or equivalent adapted for your runtime environment)
```
{
    "apps": {
        "richdocuments": {
            "disable_certificate_verification": "yes",
            "enabled": "yes",
            "installed_version": "8.4.0-beta.1",
            "public_wopi_url": "https:\/\/nc.<domain>.com",
            "types": "prevent_group_restriction",
            "use_groups": "Users",
            "wopi_url": "https:\/\/nc.<domain>.com\/apps\/richdocumentscode\/proxy.php?req="
        }
    }
}

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by kmorber** [comment]
I applied the fixes, but i still have the same problem.

**Comment by joshtrichards** [comment]
@kmorber Are you sure it's still coming from RD? Not something else like the FTS app? Can you post the exact error you're still seeing?

**Comment by theyoungstone** [comment]
Hi,

same issue here with Nextcloud 29.0.0.19

{"reqId":"5Emhbvg90vptBDbuVq2Q","level":3,"time":"2024-04-27T17:35:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Class \"OC\\BackgroundJob\\TimedJob\" not found","userAgent":"--","version":"29.0.0.19","exception":{"Exception":"Error","Message":"Class \"OC\\BackgroundJob\\TimedJob\" not found","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/lib/composer/composer/ClassLoader.php","line":576,"function":"include"},{"file":"/var/www/html/nextcloud/lib/composer/composer/ClassLoader.php","line":427,"function":"Composer\\Autoload\\{closure}","args":["*** sensitive parameters replaced ***"]},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":126,"function":"__construct","class":"ReflectionClass","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":146,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":470,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/ServerContainer.php","line":155,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":64,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/Server.php","line":55,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/BackgroundJob/JobList.php","line":326,"function":"get","class":"OCP\\Server","type":"::"},{"file":"/var/www/html/nextcloud/lib/private/BackgroundJob/JobList.php","line":235,"function":"buildJob","class":"OC\\BackgroundJob\\JobList","type":"->"},{"file":"/var/www/html/nextcloud/cron.php","line":163,"function":"getNext","class":"OC\\BackgroundJob\\JobList","type":"->"}],"File":"/var/www/html/nextcloud/apps/phonetrack/lib/Cron/AutoExport.php","Line":15,"message":"Class \"OC\\BackgroundJob\\TimedJob\" not found","exception":[],"CustomMessage":"Class \"OC\\BackgroundJob\\TimedJob\" not found"},"id":"662d379f97988"}

**Comment by criegerde** [comment]
Same for me on Nextcloud 30.0.2, richdocuments: 8.3.8 (installed 8.3.8), PHP8.3-fpm/cli, MariaDB, nginx.

When disabling (occ app:disable richdocuments) the cron.php errors are gone.

![Image](https://github.com/user-attachments/assets/aa1bb7a7-bf6c-48df-8d5e-2226732b669e)

Having the richdocuments-app enabled the following errors are thrown:

![Image](https://github.com/user-attachments/assets/1defcc22-426c-432b-9e90-f8e34876bf6b)

<pre>Error: Class &quot;OC\BackgroundJob\TimedJob&quot; not found in /var/www/nextcloud/apps/richdocuments/lib/Backgroundjobs/ObtainCapabilities.php:29
Stack trace:
#0 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(576): include()
#1 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(427): Composer\Autoload\{closure}()
#2 [internal function]: Composer\Autoload\ClassLoader-&gt;loadClass()
#3 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(104): ReflectionClass-&gt;__construct()
#4 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer-&gt;resolve()
#5 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(448): OC\AppFramework\Utility\SimpleContainer-&gt;query()
#6 /var/www/nextcloud/lib/private/ServerContainer.php(137): OC\AppFramework\DependencyInjection\DIContainer-&gt;queryNoFallback()
#7 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer-&gt;query()
#8 /var/www/nextcloud/lib/public/Server.php(39): OC\AppFramework\Utility\SimpleContainer-&gt;get()
#9 /var/www/nextcloud/lib/private/BackgroundJob/JobList.php(288): OCP\Server::get()
#10 /var/www/nextcloud/lib/private/BackgroundJob/JobList.php(197): OC\BackgroundJob\JobList-&gt;buildJob()
#11 /var/www/nextcloud/cron.php(148): OC\BackgroundJob\JobList-&gt;getNext()
#12 {main}
</pre>

**Comment by criegerde** [comment]
Fxed when manually applied [the fix](https://github.com/nextcloud/richdocuments/pull/3527)

**Comment by juliusknorr** [comment]
@criegerde It seems you are running a richdocuments release (8.3.x) that is not compatible with Nextcloud 30. For 30 it should be the 8.5.x releases (currently 8.5.2) which would already include the fix.

https://apps.nextcloud.com/apps/richdocuments
