### ISSUE TITLE
Wrong resonse 

### ISSUE THREAD

**Issue by daif** [nextcloud/richdocuments#353]
Hi @juliushaertl 
I think $.when return an array instead of response and passed to registerFilesMenu.
https://github.com/nextcloud/richdocuments/blob/32c36fe3c8dcee783d5651ce46325a916e8b1ba1/js/viewer/viewer.js#L160
Quick work around for this  issue
`var ooxml = response[0].doc_format === 'ooxml';`

**Comment by juliushaertl** [comment]
Thanks for the report. I've pushed a fix in #357
