### ISSUE TITLE
Create new document with template -> fails to connect to "document"

### ISSUE THREAD

**Issue by beccon4** [nextcloud/richdocuments#355]
### Steps to reproduce
1. Install the latest Nextcloud (15.0.2) and Collabora 4.0
2. Create new document
3. Try to open a newly created document (app asks to select a template
4. Error message - "cant connect to the file" (something like that my message is in German)
5. open the document again and it works

### Expected behaviour
Create a new document open it and start to work.

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:
Ubuntu 18.04

**Web server:**
Apache 2.0

**Database:**
MySQL

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
15.0.2
Installed the latest Collabora using Ubuntu deb packets - no Docker

**Updated from an older Nextcloud/ownCloud or fresh install:**
virgin install

**Where did you install Nextcloud from:**
nextcloud.com

It looks like a SSL problem though I don't use SSL on the way between Nextcloud and Collabora - actually they reside on the same machine. I terminate crypto in an reverse proxy upstream in the DMZ.

```
`wsd-12493-12545 2019-01-14 20:37:23.208176 [ docbroker_004 ] ERR  Cannot get file info from WOPI storage uri [http://eth.kryptonerd.de/nextcloud/index.php/apps/richdocuments/wopi/files/492_ocwp0qht58o5?access_token=xkLFJlonAHkEK1WaWNTxI7TkZU76UzXu&access_token_ttl=&permission=edit]. Error: SSL Exception: error:1408F10B:SSL routines:ssl3_get_record:wrong version number| wsd/Storage.cpp:474

wsd-12493-12545 2019-01-14 20:37:23.208273 [ docbroker_004 ] ERR Failed to add session to [/nextcloud/index.php/apps/richdocuments/wopi/files/492_ocwp0qht58o5] with URI [http://eth.kryptonerd.de/nextcloud/index.php/apps/richdocuments/wopi/files/492_ocwp0qht58o5?access_token=xkLFJlonAHkEK1WaWNTxI7TkZU76UzXu&access_token_ttl=&permission=edit]: SSL Exception| wsd/DocumentBroker.cpp:1093
wsd-12493-12545 2019-01-14 20:37:23.208308 [ docbroker_004 ] ERR Error while loading : SSL Exception| wsd/LOOLWSD.cpp:2674
wsd-12493-12545 2019-01-14 20:37:23.208470 [ docbroker_004 ] WRN Child session [000a] not found to forward message: load url=http://eth.kryptonerd.de/nextcloud/index.php/apps/richdocuments/wopi/files/492_ocwp0qht58o5?access_token=xkLFJlonAHkEK1WaWNTxI7TkZU76UzXu&access_token_ttl=&permission=edit readonly=0 lang=de| wsd/DocumentBroker.cpp:1738
wsd-12493-12545 2019-01-14 20:37:24.209435 [ docbroker_004 ] ERR Invalid or unknown session [000a] to remove.| wsd/DocumentBroker.cpp:1162
wsd-12493-12545 2019-01-14 20:37:24.209477 [ docbroker_004 ] ERR No socket associated with WebSocketHandler 0x7f29500092f0| ./net/WebSocketHandler.hpp:108
…
wsd-12493-12549 2019-01-14 20:37:51.239735 [ docbroker_005 ] ERR Cannot get file info from WOPI storage uri [http://eth.kryptonerd.de/nextcloud/index.php/apps/richdocuments/wopi/files/492_ocwp0qht58o5?access_token=xkLFJlonAHkEK1WaWNTxI7TkZU76UzXu&access_token_ttl=&permission=edit]. Error: SSL Exception: error:1408F10B:SSL routines:ssl3_get_record:wrong version number| wsd/Storage.cpp:474
wsd-12493-12549 2019-01-14 20:37:51.239801 [ docbroker_005 ] ERR Failed to add session to [/nextcloud/index.php/apps/richdocuments/wopi/files/492_ocwp0qht58o5] with URI [http://eth.kryptonerd.de/nextcloud/index.php/apps/richdocuments/wopi/files/492_ocwp0qht58o5?access_token=xkLFJlonAHkEK1WaWNTxI7TkZU76UzXu&access_token_ttl=&permission=edit]: SSL Exception| wsd/DocumentBroker.cpp:1093
wsd-12493-12549 2019-01-14 20:37:51.239822 [ docbroker_005 ] ERR Error while loading : SSL Exception| wsd/LOOLWSD.cpp:2674`
```

Only noticable here:
Error: SSL Exception: error:1408F10B:SSL routines:ssl3_get_record:wrong version number| wsd/Storage.cpp:474 <- SSL? I don’t do SSL on the Collabora Server - I configured it without

Has anyone an idea what can be wrong here?`

![grafik](https://user-images.githubusercontent.com/12436716/51272068-624f5d00-19c9-11e9-9c88-fcc69387e7ce.png)

**Comment by beccon4** [comment]
PS: there is a typo in the German message -it should read "Es konnte keine Verbindung zu ihrem Dokument hergestellt werden."

**Comment by juliushaertl** [comment]
You probably need to configure collabora to work without ssl, as by default using https is enforced. As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

For the translation error: This string is not part of richdocuments, so you probably want to report that to Collabora: https://www.collaboraoffice.com/code/#participate

**Comment by rmeissn** [comment]
Actually this seems to be an issue with v3.2.1. I'm using a nginx reverse-proxy (with certs from letsencrypt) and connect to the collabora backend docker container via https (as it creates certs and this seems to be the default).
When I try to create a new document by a template, the same message as mentioned by @beccon4 is displayed. When I open the same document again (after refreshing the browser) it works as expected.

**Comment by brtptrs** [comment]
We are having the same Problem with this setup:

CentOS
Apache
php.7.1
NC 15.0.7
LOOL 4.0.3
richdocuments 3.2.4

Collabora is installed from the repositories following the provided guidelines.

We have copied the templates to
appdata_xyz/richdocuments/templates/

and then ran
occ files:scan-app-data

The templates are now displayed but the error as explained above still shows up.

**Comment by dieg0nob** [comment]
same problem here
NC 17.0.6
Lool 4.2.2 and 4.0.1

I can edit every document, but creating a new, have an error, later, exit collabora and them open the new document created before and can edit it.

![IMG_4021](https://user-images.githubusercontent.com/29979144/81326980-fcc92900-9070-11ea-83b8-6714f57b5036.jpg)

testing with templates and without templates.
