### ISSUE TITLE
Ability to copy and paste to text

### ISSUE THREAD

**Issue by hyoretsu** [nextcloud/richdocuments#3568]
**Is your feature request related to a problem? Please describe.**
Currently we can copy and paste entire columns, but not to other software like Notepad. This is a feature that was prety useful in Google Sheets and Microsoft Excel. (E.g. for using it to score exams and handily copying the entire "student" and "score" columns)

**Describe the solution you'd like**
Ctrl + c, ctrl + v in Sheets software copies everything, from text to formatting, but ctrl + v in text software only pastes the text.

**Comment by juliushaertl** [comment]
This issue tracker is only for the Nextcloud connector app. For issues in office editing itself with Collabora Online itself, please open a bug report at: https://github.com/collaboraonline/online Best would be to also provide more insights on the version you use :)
