### ISSUE TITLE
Missing changelog for 8.3.4

### ISSUE THREAD

**Issue by siccovansas** [nextcloud/richdocuments#3594]
**Describe the bug**
The changelog for 8.3.4 was listed as 8.3.3 (so there are now two entries for 8.3.3.). See [this PR](https://github.com/nextcloud/richdocuments/pull/3587/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed).

**Comment by juliushaertl** [comment]
Thanks for reporting, fixed
