### ISSUE TITLE
error when opening a document without error message in collabora.

### ISSUE THREAD

**Issue by nonofr91** [nextcloud/richdocuments#3598]
**Describe the bug**
I can't open documents in collabora. I didn't have a problem until now, but without identifying the changes it no longer works. I carried out the updates via portainer and docker compose and I realized that the coolwsd.xml file had changed. I reset the important settings then restarted the container. I can connect to the collabora server but I cannot open the files. and I have no errors in the collabora logs or in nextcloud.
In the collaboration logs we see the start of the file opening and then a shutdown of the connection.
I can't find why, thanks for any help you can give me.

**To Reproduce**
4. See error: Failed to load document

Nextcloud Office failed to load - please try again later

**Expected behavior**

**Screenshots**

**Client details:**
 - OS: [e.g. iOS] : Windows 11
 - Browser [e.g. chrome, safari]: Chrome et Firefox
 - Device: [e.g. iPhone6, desktop]

## Server details

**Operating system**: Debian 11 + Docker

**Web server:** 

**Database:**

**PHP version:**

**Nextcloud version:**  28.0.4

**Version of the richdocuments app**  v8.4.0-beta.3

**Version of Collabora Online** :  Collabora Online Development Edition 23.05.10.1 baa6eef

**Configuration of the richdocuments app**
```
Insert the output of `./occ config:list richdocuments` (or equivalent adapted for your runtime environment)
{
    "apps": {
        "richdocuments": {
            "disable_certificate_verification": "",
            "doc_format": "",
            "enabled": "yes",
            "installed_version": "8.3.4",
            "public_wopi_url": "https:\/\/collabora.??????duckdns.org",
            "types": "prevent_group_restriction",
            "wopi_allowlist": "82.123.yyy.xxx,127.0.0.1\/8,192.168.0.0\/16,172.16.0.0\/12,10.0.0.0\/8,fd00::\/8,::1",
            "wopi_url": "https:\/\/collabora.??????.duckdns.org"
        }
    }
}
```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:


a) The javascript console log
b) The network log
c) ...
```

</details>

[log collabora.txt](https://github.com/nextcloud/richdocuments/files/14979246/log.collabora.txt)

**Comment by joshtrichards** [comment]
Given your description and what lead up to this situation, this sounds like a configuration or general troubleshooting matter. This channel is only for bug reporting. For assistance I suggest you post your situation on the Community Help Forum (https://help.nextcloud.com).
