### ISSUE TITLE
Shared external links of docx-files does not open in Onlyoffice

### ISSUE THREAD

**Issue by rollanders** [nextcloud/richdocuments#361]
I have both OpenOffice and Collabora installed. In the browser user interface doc and docx files are opened in OnlyOffice and odt-files in Collabora. I use different file-extensions as I want to choose the editor. This can be usefulk as they have different characteristics. 

However if I share the files to an external guest all file-formats are opened in Collabora. I want to be able to choose Onlyoffice as editor of docx files also for external guestusers. 

### Steps to reproduce
1. Create docx and odt files. 
2. Share them with an external link
3. Open them from the external link. Both types will open in Collabora. 

### Expected behaviour
docx files should open in OnlyOffice

### Actual behaviour
Tdocx file is opened in Collabora. 

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
NC15.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
Followed c.riegers instructions
**List of activated apps:**
All apps updated to latest. 
Latest Collabora and Onlyoffice in docker

**Comment by juliushaertl** [comment]
Running Collabora besides OnlyOffice is not supported. See https://github.com/nextcloud/server/issues/9192 for the related server issue.

**Comment by LinneyS** [comment]
Hi Nextcloud
Hi @juliushaertl
I want to re-open this issue for discussion.
This does not apply to the default action when clicking on a file (`fileActions.setDefault`).
The question is about the unconditional opening of the Collabora editor when clicking on a link for external access.
https://github.com/nextcloud/richdocuments/blob/v3.3.9/js/viewer/viewer.js#L391

I would like to allow the user to decide which editor to use for this file.
At the moment, no other conflict points are known for using two applications: Collabora and ONLYOFFICE.

**Comment by juliushaertl** [comment]
@LinneyS As mentioned above, this is more a server issue, since we have no way of handling which app should handle the file display. I don't think that adding another option for that to richdocuments/onlyoffice is the right way to implement this, so I would like to have this discussed in a more general approach.

Feel free to head over to the server repo and open a new issue.

**Comment by vasyugan** [comment]
> Running Collabora besides OnlyOffice is not supported. See [nextcloud/server#9192](https://github.com/nextcloud/server/issues/9192) for the related server issue.

The result is, in my experience, that most people disable Collabora because of this, as MS Formats are used more widely and the OnlyOffice interface is more familiar to users of MS Office. Therefore, as long as this isn't resolved, this is only to the disadvantage of Collabora.
