### ISSUE TITLE
No Edit in Nextcloud Office option for PDF files

### ISSUE THREAD

**Issue by thebearon** [nextcloud/richdocuments#3621]
Similar issue to #1894. In Nextcloud 28.0.5 and richdocuments 8.3.5, there is no Edit in Nextcloud Office option for PDF files in the ... menu.

This used to work in Nextcloud 27 (upgraded from 27.1.9).

**Comment by juliushaertl** [comment]
I can reproduce. It looks like we missed to migrate the optional file action to the new API with 28:

https://github.com/nextcloud/richdocuments/blob/main/src/viewer.js#L45-L67

Needs to be moved to https://nextcloud-libraries.github.io/nextcloud-files/functions/registerFileAction.html
