### ISSUE TITLE
PDF export includes reviewed state

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/richdocuments#3680]
This is in between a bug report and a bug report - from a technical pov I'm sure it's a feature request, but from an user pov it's more like a bug. The issue:

When using the export to PDF, the resulting PDF includes the changes - not exactly what you'd expect, as PDF is typically an end product... here's how it works RN:

![Screenshot 2024-05-08 at 14 07 32](https://github.com/nextcloud/richdocuments/assets/551757/6ba13eaa-7662-4531-a161-3f36a4497a90)
![Screenshot 2024-05-08 at 14 07 50](https://github.com/nextcloud/richdocuments/assets/551757/f379cec3-a4d9-4844-b59c-b199ab18e751)
![Screenshot 2024-05-08 at 14 09 22](https://github.com/nextcloud/richdocuments/assets/551757/94a49a3f-c6e5-420f-b5a6-c1e0613be1a2)
![Screenshot 2024-05-08 at 14 09 35](https://github.com/nextcloud/richdocuments/assets/551757/a860a529-fafd-48cf-8bca-8ceb5ea9ac42)
![Screenshot 2024-05-08 at 14 10 26](https://github.com/nextcloud/richdocuments/assets/551757/d1fdf7c3-fbf2-4a97-9de0-83e28b6bbb71)

What I'd hope for is an option perhaps "show changes" that is off by default ;-)

**Comment by juliushaertl** [comment]
Maybe @pedropintosilva has any insights if such an option is available or could be exposed from core ?

**Comment by jospoortvliet** [comment]
Hi @pedropintosilva do you have any input?

**Comment by pedropintosilva** [comment]
@jospoortvliet yes and sorry for not updating this. I think I mentioned this in some call but I forgot to update this.

----

In Short: Thanks! I think this would be quite valuable. To allow users to export files be that PDF or other file type with or without tracking changes displayed (similar as it's already possible when editing the document via Review > Show toggle button)

----

We are still not working on this. It might be useful to implement a solution that is not PDF dependent (changing the PDF dialog etc) because well, it would only work for that and because adding one more option within that dialog would just increase the number of options and the probability of user never see it. Thus, maybe adding a subtle intermediary via snackbar (a bottom component, see screenshot) that allows the user to understand what is going on and with a button to switch off

**Comment by pedropintosilva** [comment]
right now I think we have the same behaviour as other office suites which is export what is visible to the user. So, if the user toggles that off in the tabbed the PDF export should come out without changes

**Comment by pedropintosilva** [comment]
> [...] So, if the user toggles that off in the tabbed the PDF export should come out without changes

@jospoortvliet if this doesn't suffice then I wonder if having another button something along the lines of "Publish" something that would signify "Export without tracking changes" that would hide the tracking changes + trigger the PDF export dialog

**Comment by jospoortvliet** [comment]
Hmmm, I see. Looking at the dialog, a generic solution would indeed be to have an option in the list of "export X" things that says "export tracking changes", which probably should be off by default for PDF's. So at least you're not losing anything but do the sane thing by default.

**Comment by pedropintosilva** [comment]
@jospoortvlietI think I understand what you mean. We would have some troubles with lengthy labels etc but probably it could be worked out. But just to be sure this is what you mean, right?

![image](https://github.com/nextcloud/richdocuments/assets/65948705/35089c65-8c2f-4b64-bc26-f89b52d1bddf)

(in there ^ I removed the `as` in the `Export as` button as it then allow us to have the shortened label inside `With`)

Nevertheless, I'm still not sure if changing the default behaviour is the right move. But if the above is what you mean then we can maybe test the waters and get feedback via the community/development edition. What do you think?

**Comment by jancborchardt** [comment]
The "Show" button in the "Review" tab toggles the state already – when you export as PDF, it will show whatever you see.

So when you want to export without the change details visible, you just toggle that option and then export. Seems fine to me @jospoortvliet?

**Comment by jospoortvliet** [comment]
You're right of course, you can just turn it off in the view. Maybe I'm overcomplicating it and that is the easiest solution.

Ok, let's focus on bigger things ;-)
