### ISSUE TITLE
http_response_code(): Cannot set response code - headers already sent

### ISSUE THREAD

**Issue by modir** [nextcloud/richdocuments#3699]
I did now an update to the latest version(8.4.2) of richdocuments and now it is not possible anymore to open files. The log is filled with this warning:

`PHP Warning:  http_response_code(): Cannot set response code - headers already sent (output started at /srv/httpd/nextcloud/apps/richdocumentscode/proxy.php:285) in /srv/httpd/nextcloud/apps/richdocumentscode/proxy.php on line 292`

It is very likely this is the problem.

**Comment by juliushaertl** [comment]
Please file this issue to the richdocumentscode app at https://github.com/CollaboraOnline/richdocumentscode

**Comment by bright-webb** [comment]
if you are using nginx, be sure to remove any space before <?php
