### ISSUE TITLE
Print Dialog in Spreadsheet View does Nothing

### ISSUE THREAD

**Issue by LinuxSpielKind** [nextcloud/richdocuments#3701]
**Describe the bug**
While having a spread file opened with Nextcloud Office a click on the button "Print" under the menu "Files" does nothing. The beavior with all other Office documents (presentation and text document have been tested) a PDF is rendered an the print dialog of the browser is opened. The difference to the later documents is, that a sub menu with "active page" and "all pages" is displayed. 
Unfortunately I don't see anything of interest in the browser logs.
A workaround is hitting CTRL+P what seems to open the "All Pages" option.

**To Reproduce**
1. Go to 'Files'
2. Click on 'Print'
3. Select either "active page" or "all pages"
4. Nothing is displayed

**Expected behavior**
I would expect, that a PDF is rendered, according to the selected view option, and the print dialog of the browser is opened
**Screenshots**
![grafik](https://github.com/nextcloud/richdocuments/assets/142408439/7ac1995a-99c1-4ef8-9cf3-988f95ec2cac)

**Client details:**
 - OS: Windows 10
 - Browser: Firefox  
 - Version: 125.0.3 (64-Bit)
 - Device: desktop
## Server details

**Operating system**: 
- Ubuntu 22.04

**Web server:**
- Apache2

**Database:**
- PostgreSQL 15.6 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit

**PHP version:**
- 8.2.18

**Nextcloud version:**
- 28.0.5 (Nextcloud AIO v8.2.1)

**Version of the richdocuments app** 
8.3.7
**Version of Collabora Online**
Collabora Online Development Edition 24.04.1.4 f12ee1f
**Configuration of the richdocuments app**
```
{
    "apps": {
        "richdocuments": {
            "types": "prevent_group_restriction",
            "installed_version": "8.3.7",
            "enabled": "yes",
            "public_wopi_url": "https:\/\/nextcloud.intern.example.com",
            "wopi_allowlist": "192.168.20.8,127.0.0.1\/8,192.168.0.0\/16,172.16.0.0\/12,10.0.0.0\/8,fd00::\/8,::1,nextcloud.intern.example.com,$EXTERNAL_IP",
            "disable_certificate_verification": "yes",
            "wopi_url": "https:\/\/nextcloud.intern.example.com\/",
            "wopi_callback_url": ""
        }
    }
}
```
.
<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Way too many corporate infos ;-)
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by joshtrichards** [comment]
Reproduced, but this may be an issue in Collabora Online itself:

https://github.com/CollaboraOnline/online/issues/8969

**Comment by thebearon** [comment]
Correct, please follow https://github.com/CollaboraOnline/online/issues/8969 for updates.
