### ISSUE TITLE
"Connection Loss" – file download is offered instead opening office editor until reapplying app configuration

### ISSUE THREAD

**Issue by 4001982248998** [nextcloud/richdocuments#3709]
**Description**
Connection to a Collabora (Nextcloud Office) service running as docker container is setup and working. But after a few hours, when clicking on an odt file, a download dialogue opens instead of Collabora.

It is, however, able to start the office editor by using the three-point-menu and then choosing "edit in Nextcloud Office"!

Access to the Nextcloud Office app is limited to a certain user group. That is configured in Nextcloud's app administration page.

**To Reproduce**
1. Setup Collabora connector in Nextcloud, confirm it's working
2. Wait a few hours, maybe logoff from Nextcloud
3. Click on an office document
4. A file download dialogue will open. Bad!
5. Go to Nextcloud's App configuration and reapply the Collabora connection
6. Click on an office document
7. Now Collabora opens again

**Expected behavior**
After clicking on an office document, Collabora office should start always, not only after reapplying the connection.

## Server details

- **Operating system**: Ubuntu
- **Web server:** Apache2
- **Database:** MariaDB
- **PHP version:** 8.1
- **Nextcloud version:** 28.0.5
- **Version of the richdocuments app**: 8.3.7
- **Version of Collabora Online**: Collabora Online Development Edition 24.04.1.3 89a7742 or Collabora Online Development Edition 24.04.3.1 594b605
- **Configuration of the richdocuments app**
```
{
    "apps": {
        "richdocuments": {
            "disable_certificate_verification": "",
            "edit_groups": "collabora-test",
            "enabled": "yes",
            "external_apps": "",
            "installed_version": "8.3.7",
            "public_wopi_url": "https:\/\/my.host.com",
            "types": "prevent_group_restriction",
            "use_groups": "collabora-test",
            "wopi_allowlist": "my-host-ip\/32",
            "wopi_url": "https:\/\/my.host.com"
        }
    }
}

```

**Comment by Niemand112233** [comment]
Have the same problem on NC 29.0.1 and a dedicated collabora instance (which is working on another NC), but I can't get it back to work.

**Comment by joshtrichards** [comment]
Can you check your Nextcloud log during the time window between it working and stopping working? I suspect you'll have some errors there. Possible saying "Failed to fetch [...]" or similar.

**Comment by juliushaertl** [comment]
This might be addressed by https://github.com/nextcloud/richdocuments/pull/3749 which makes the cached response if the Collabora server is setup permanent and no longer expiring if the background fetch fails
