### ISSUE TITLE
Enabling Nextcloud Office instance-wide breaks hide download functionality on PDFs

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/richdocuments#3710]
**Describe the bug**
When Nextcloud Office is enabled instance-wide (no limits applied on user groups), when a public share link of a PDF file is exposed with the Hide Download button, the PDF is not shown 

**To Reproduce**
1. Create a public share of a PDF file with the Hide Download option
2. Open the file via the public share

**Expected behavior**
The PDF file is displayed in the browser

**Screenshots**
The PDF file is not displayed in the browser

**Client details:**
Firefox 125.0.3
Chromium 125.0.6422.60

## Server details

**Nextcloud version:** 28.0.5

**Version of the richdocuments app** 8.3.7

**Version of Collabora Online** 24.04.3.1-1

**Configuration of the richdocuments app**
```
{
    "apps": {
        "richdocuments": {
            "enabled": "yes",
            "installed_version": "8.3.7",
            "mobile_editing": "yes",
            "public_wopi_url": "****",
            "types": "prevent_group_restriction",
            "use_groups": "",
            "wopi_url": "****"
        }
    }
}

```

**Comment by elzody** [comment]
I am not able to reproduce the issue on my end. Can you provide more details logs, like nextcloud.log, browser console logs, or list of enabled apps?
