### ISSUE TITLE
cURL error 28: Connection timed out after 120001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://github.com/nextcloud-releases/richdocuments/releases/download/v8.4.2/richdocument-v8.4.2.tar.gz

### ISSUE THREAD

**Issue by sneal0** [nextcloud/richdocuments#3743]
**Describe the bug**
cURL error 28: Connection timed out after 120001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://github.com/nextcloud-releases/richdocuments/releases/download/v8.4.2/richdocument-v8.4.2.tar.gz

New to all of this. Trying to put nextcloud office on next cloud for cloud storage on home nas. 

**To Reproduce**
1. Go to https://192.168.1.222:9001/settings/apps/office/richdocuments
2. Click on download and enable
3. Scroll down to 
4. See error = cURL error 28: Connection timed out after 120001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://github.com/nextcloud-releases/richdocuments/releases/download/v8.4.2/richdocument-v8.4.2.tar.gz

**Expected behavior**
I expect to be bale to download and enable next cloud office.

**Screenshots**
![image](https://github.com/nextcloud/richdocuments/assets/172154595/fd71f717-7726-4f72-aa53-366af4cd06c0)

**Client details:**
 - OS: windows and truenas collabora opnsense for router/firewall
 - Browser chrome

 - Device: desktop

## Server details

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** 29.0.1

**Version of the richdocuments app**???

**Version of Collabora Online**

**Configuration of the richdocuments app**
```
Insert the output of `./occ config:list richdocuments` (or equivalent adapted for your runtime environment)
```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

I'm trying to download and enable next cloud office but keep getting this error code cURL error 28: Connection timed out after 120001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://github.com/nextcloud-releases/richdocuments/releases/download/v8.4.2/richdocument-v8.4.2.tar.gz.

I new to all of this. First off i want to understand what the issue is and secondly I want to be  able to fix it.

**Comment by helmo** [comment]
It looks like your nextcloud server was unable to connect to the internet, especially https://github.com/.

**Comment by joshtrichards** [comment]
This is a configurations / local environment troubleshooting matter. GitHub is a bug reporting channel, but not for general tech support. :-) You need to ask for help at the community help forum: https://help.nextcloud.com
