### ISSUE TITLE
Browser title contains wrong filename with templates

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#375]
When creating a new file from a template, the browser page title doesn't update to the correct document title. Instead it keeps the name of the template.

**Comment by thebearon** [comment]
Similarly, when opening an existing file, it briefly shows the file name there, but once it's finished loading, the file name part disappears again.

**Comment by juliushaertl** [comment]
The title might be restored by the files app when we call reload on the fileList on Document_Loaded https://github.com/nextcloud/richdocuments/blob/24bc4dfdc8c1f2427ec4aa8b4b43035e7cb62f80/js/documents.js#L615-L617
