### ISSUE TITLE
Popup "Check security warnings of your server" cannot be discarded

### ISSUE THREAD

**Issue by jmechnich** [nextcloud/richdocuments#3755]
**Describe the bug**
After upgrade to Collabora CODE 24.04.4.1.1, a popup appears repeatedly while editing a document with the message "Check security warnings of your server" (screenshot 1). Opening the details, there are two possible outcomes: either there are no issues found but a notice "The is_admin user property is set" (screenshot 2) or an actual error "The is_admin user property is not set" (screenshot 3). See also [this post](https://help.nextcloud.com/t/security-warning-the-is-admin-user-property-is-set/194935) in the Nextcloud help forum.

**To Reproduce**
1. Check that Collabora CODE 24.0.4.4.1.1 is installed.
2. Open a text document using Collabora.
3. Start editing and wait for the popup to appear.

**Expected behavior**
No popups or at least no recurrence after checking their contents.

**Screenshots**
Screenshot 1:
![image](https://github.com/nextcloud/richdocuments/assets/6206799/c98e42a8-9599-449e-8772-62ebbdad2ed1)

Screenshot 2:
![image](https://github.com/nextcloud/richdocuments/assets/6206799/ab7ef7a2-3d90-4344-afbb-5e5905697a7b)

Screenshot 3:
![image](https://github.com/nextcloud/richdocuments/assets/6206799/17d5aa99-7ad8-4cec-966d-cb5056e9c446)

**Client details:**
 - OS: Debian bookworm
 - Browser: Firefox
 - Version: 115.11.0esr
 - Device: Desktop

## Server details

**Operating system**:
Debian bookworm

**Web server:**
Apache/2.4.59 (Debian)

**Database:**
mariadb  Ver 15.1 Distrib 10.11.6-MariaDB

**PHP version:**
PHP 8.2.18

**Nextcloud version:**
28.0.6

**Version of the richdocuments app**
8.3.7

**Version of Collabora Online**
collabora/code:24.04.4.1.1 Docker image

**Configuration of the richdocuments app**
```
{
    "apps": {
        "richdocuments": {
            "disable_certificate_verification": "",
            "enabled": "yes",
            "installed_version": "8.3.7",
            "public_wopi_url": "https:\/\/redacted.host.name",
            "types": "prevent_group_restriction",
            "wopi_allowlist": "172.0.0.0\/8",
            "wopi_url": "https:\/\/redacted.host.name\/"
        }
    }
}
```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
(empty)
```

#### Browser log
```
...
Unknown server audit entry: certwarning bundle.js:24657:46
...
```

</details>

**Comment by joshtrichards** [comment]
This is a Collabora Online/CODE matter. It also looks like it's been addressed just recently:

https://github.com/CollaboraOnline/online/pull/9229
https://github.com/CollaboraOnline/online/pull/9242
