### ISSUE TITLE
Moving in excel sheet on android cause resseting view, also sheet is choppy

### ISSUE THREAD

**Issue by Oriann** [nextcloud/richdocuments#3756]
**Describe the bug**
Opening excel sheet in nextcloud android app is resseting view to upper left most corner, also moving through sheet is choppy.

**To Reproduce**
1. Open excel sheet in nextcloud on android phone
2. Move through the sheet
3. View consistently resseting to upper left most corner and moving through sheet is also choppy.

**Expected behavior**
Moving through sheet is not resseting view and is not choppy.

**Screenshots**
Video here:

https://github.com/nextcloud/richdocuments/assets/11374526/c1c95564-9c86-4841-9488-5566a413f4ae

**Client details:**
 - OS: Android 14
 - Nextcloud app version: 3.29.0
 - Collabora online version: 24.04.3.2 (standalone install)
 - Device: Samsung Galaxy S24 Ultra

## Server details

**Operating system**:
Debian 12 Bookworm
**Web server:** 
Nginx 26.1
**Database:**
MariaDB 10.11.8
**PHP version:**
PHP 8.2
**Nextcloud version:**
28.0.6
**Version of the richdocuments app**
8.3.7
**Version of Collabora Online**
24.04.3.2
**Configuration of the richdocuments app**
```
{
    "apps": {
        "richdocuments": {
            "canonical_webroot": "",
            "disable_certificate_verification": "",
            "doc_format": "ooxml",
            "enabled": "yes",
            "external_apps": "",
            "installed_version": "8.3.7",
            "public_wopi_url": "https:\/\/collabora.*****.cz",
            "types": "prevent_group_restriction",
            "wopi_allowlist": "192.168.2.0\/24",
            "wopi_url": "https:\/\/collabora.*****.cz"
        }
    }
}

```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Empty log
```

#### Browser log
```
Not applicable, problem is in android app
```

</details>

**Comment by juliushaertl** [comment]
This issue tracker is only for the Nextcloud connector app named Collabora Online. For issues with Collabora Online itself, please open a bug report at: https://github.com/collaboraonline/online
