### ISSUE TITLE
Collabora Online "Use OOXML as the default" does not work (xlmx or docx)

### ISSUE THREAD

**Issue by PpaiSanchez** [nextcloud/richdocuments#378]
The option in the App Collabora Online “Use OOXML as the default for new files” should actually cause the new Office files to be created as xlmx or docx. Although we use the latest server and it does not work anymore. All files are always created only as odt or ods. What could that be?

**Comment by PpaiSanchez** [comment]
I just ended up going into the apps directory and changing the viewer.js file (/var/www/nextcloud/apps/richdocuments/js/viewer/viewer.js) and copied and pasted the same variables in the if statement for ooxml checking to look like this (so that it was using ooxml if it was checked or not:

                        docExt = 'docx';
                        spreadsheetExt = 'xlsx';
                        presentationExt = 'pptx';
                        docMime = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
                        spreadsheetMime = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
                        presentationMime = 'application/vnd.openxmlformats-officedocument.presentationml.presentation';
                } else {
                        docExt = 'docx';
                        spreadsheetExt = 'xlsx';
                        presentationExt = 'pptx';
                        docMime = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
                        spreadsheetMime = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
                        presentationMime = 'application/vnd.openxmlformats-officedocument.presentationml.presentation';

**Comment by PpaiSanchez** [comment]
It works. So it seems to be a bug.

**Comment by juliushaertl** [comment]
@PpaiSanchez Can you please report the versions of richdocuments and collabora you are using? Can you check if it works when updating to richdocuments 3.2.0 as this should be fixed with https://github.com/nextcloud/richdocuments/issues/357

**Comment by juliushaertl** [comment]
Closing as fiexed with #357, feel free to reopen if the problem still occurs for you on 3.2.0
