### ISSUE TITLE
Unit defaults to inch (does not respect language settings)

### ISSUE THREAD

**Issue by XueSheng-GIT** [nextcloud/richdocuments#3786]
**Describe the bug**
Units default to inch even if a European country is chosen in language settings (e.g. Germany).

**To Reproduce**
1. Go to Personal settings and change language and region to German/Germany
2. Open Nextcloud office (e.g. create new document)
3. Look at the units shown in the side bar (screenshots below)

**Expected behavior**
All units within Nextcloud Office should be aligned to the chosen language in personal nextcloud settings. If German is chosen, unit should default to "cm" instead of inch.
I wasn't able to find a way to change the unit manually.

**Screenshots**
Nextcloud language setting:
![image](https://github.com/nextcloud/richdocuments/assets/4077683/1141b32b-7099-40d8-b557-1badde727395)

Nextcloud office units in inch (should be cm):
![image](https://github.com/nextcloud/richdocuments/assets/4077683/0162443a-94d1-4595-92a5-4dcd8eba3fc6)

**Client details:**
 - OS: Ubuntu 24.04
 - Browser Firefox
 - Version 127
 - Device: Desktop

## Server details

**Operating system**: Ubuntu 22.04

**Web server:** apache2

**Database:** postgresql

**PHP version:** 8.1

**Nextcloud version:** 29.0.2

**Version of the richdocuments app** 8.4.3

**Version of Collabora Online** 24.04.4.2

**Configuration of the richdocuments app**
```
{
    "apps": {
        "richdocuments": {
            "installed_version": "8.4.3",
            "disable_certificate_verification": "",
            "canonical_webroot": "",
            "external_apps": "",
            "types": "prevent_group_restriction",
            "wopi_allowlist": "192.168.5.0\/24",
            "wopi_url": "https:\/\/office.my-domain.de",
            "public_wopi_url": "https:\/\/office.my-domain.de",
            "enabled": "yes"
        }
    }
}

```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
n/a
```

#### Browser log
```
n/a
```

</details>

**Comment by juliushaertl** [comment]
I could reproduce this but the language setting is properly handed over so I expect this issue on the Collabora side.

This issue tracker is only for the Nextcloud connector app named Collabora Online. For issues with Collabora Online itself, please open a bug report at: https://github.com/collaboraonline/online.
