### ISSUE TITLE
Unable to Rename Version While Editing File

### ISSUE THREAD

**Issue by Does-This-Work** [nextcloud/richdocuments#3795]
**Describe the bug**
When trying to rename a version while editing a file, it is not possible to type in the version name field. However, renaming a version is possible through the Files app.

**To Reproduce**
1. Create or open a document.
2. Go to the Files tab.
3. Open "See History"
4. Try renaming any version.

**Expected behavior**
You should be able to type into the version field when attempting to rename a version.

**Screenshots**
![image](https://github.com/nextcloud/richdocuments/assets/102190830/e60c459c-d1b9-4016-af7c-05979bdc9ebb)

**Client details:**
 - Browser: Firefox and Chrome (both with the latest version)

## Server details

**Operating system**: Nextcloud AIO (Docker)

**Web server:** Apache

**Database:** PostgreSQL 16.3

**PHP version:** 8.2.20

**Nextcloud version:** Nextcloud Hub 8 (29.0.2)

**Version of the richdocuments app** 8.4.3

**Version of Collabora Online** 24.04.4.1

**Configuration of the richdocuments app** 
```
{
    "apps": {
        "richdocument": []
    }
}
```

**Comment by mejo-** [comment]
This issue is reproducible on stable28 and stable29. It's related to an outdated `@nextcloud/vue` version in the server.
