### ISSUE TITLE
List of documents won't load on app homepage

### ISSUE THREAD

**Issue by idmacdonald** [nextcloud/richdocuments#38]
Hi,

I'm running version 1.1.17 of the app in NextCloud 10.0.3. When I click on 'Office' in the apps menu, the app's 'homepage' is loaded. There are the buttons for 'New document', plus a list of all compatible documents the user has access to. On a NextCloud installation with many files, this flat list of documents could include thousands of files.

I find that if I click on 'New document' before the list of existing documents has rendered and appeared, I get the rotating circle that doesn't stop and Collabora never fully loads. The new document is created, it just doesn't get loaded.

I am wondering about the UI that presents a flat list of all documents that the user has access to. That list can, in some cases, be very, very long, and the behaviour I'm seeing suggests that some web browsers just don't have the resources to render it quickly. Should there be pagination by default on that screen? Or can we do something else to prevent browsers' getting stuck while trying to render the page?

If I am looking for a document to edit, I will generally do so via the main files web interface, which will allow me to open the file in Collabora. So, I am not sure of the utility of a single flat list of all compatible documents, I don't find it so useful and at the moment it is just giving me lots of 'unresponsive script' errors in Firefox. I've also tested in Chrome and it seems to hang on loading there as well.

How to fix this? Make that list less resource-intensive to render? Or change the interface completely? Other ideas?

Cheers,
-Ian

**Comment by pranavk** [comment]
The app view completely removed now in the latest version.
