### ISSUE TITLE
Collabora doesnt respect NextCloud language setting

### ISSUE THREAD

**Issue by MagnusWestin** [nextcloud/richdocuments#381]
**Describe the bug**
I have Language set to "English (US)". But Locale is set to "Swedish (Sweden)". I do this, because I want my UI in english, but dates and sorting to work like swedish. It works fine for everything in NextCloud, the UI is in english and the sorting and dates are according to swedish rules. But for Collabora, the UI becomes Swedish. Which I find very annoying :)

**To Reproduce**
1. Change Locale
2. Open a collabora document, language is set after locale not, Language setting.

**Expected behavior**
Collabora to use Language setting to control language

**Screenshots**

**Client details:**
 - OS: Linux
 - Browser Firefox
 - Version 64.0.2
 - Device: Laptop

## Server details

**Operating system**: Fedora 29 Server

**Web server:** Apache

**Database:** Maria DB

**PHP version:** 7.2.14

**Nextcloud version:** 15.0.2

**Version of the richdocuments app** 3.1.1

**Version of Collabora online** 6.0-21

**Comment by juliushaertl** [comment]
Currently just the value of `OC.getLocale()` is handed over to collabora. 

https://github.com/nextcloud/richdocuments/blob/14587738b8b9e8db7d6e234fafd4b5d602ea9da6/js/documents.js#L381

@kendy Is it possible to have a separate locale and language here as well?
