### ISSUE TITLE
disable_certificate_verification no longer works

### ISSUE THREAD

**Issue by LMRW** [nextcloud/richdocuments#3824]
**Describe the bug**
Setting disable_certificate_verification in the Admin UI so self signed certificates should be allowed used to work. It no longer does.

**To Reproduce**
1. Go to admin setting for office in nextcloud
2. Enable 'Disable certificate verification' option
3. Use a self signed certificate for collabora
4. Access a document in nextcloud
5. You see the error 'Unauthorised WOPI host. Please try again later and report to your administrator if the issue persists. Authorization error was: 'self-signed certificate in certificate chain'.'

**Expected behavior**
The document used to open just fine. Since recent updates, it no longer does.

**Screenshots**
<img width="593" alt="Screenshot 2024-07-16 at 16 36 33" src="https://github.com/user-attachments/assets/03a1c397-d9c9-4b6c-9f72-8bc1795468c5">
<img width="1387" alt="Screenshot 2024-07-16 at 16 36 27" src="https://github.com/user-attachments/assets/69af7fc6-111b-4d98-8134-700f3f83a465">

## Server details

**Operating system**: Ubuntu 22.04

**Nextcloud version:**29.0.2 via nextcloud-snap

**Version of the richdocuments app** 8.4.3

**Version of Collabora Online**: 24.04.5.1

**Configuration of the richdocuments app**
```
{
    "apps": {
        "richdocuments": {
            "canonical_webroot": "",
            "disable_certificate_verification": "yes",
            "doc_format": "ooxml",
            "enabled": "yes",
            "external_apps": "",
            "installed_version": "8.4.3",
            "public_wopi_url": "https:\/\/myurl.com:9999",
            "types": "prevent_group_restriction",
            "wopi_allowlist": "my.host.ip",
            "wopi_url": "https:\/\/myurl.com:9999"
        }
    }
}
```

Note: Config used to work perfectly for months before. 
Only recently broke.

**Comment by LMRW** [comment]
New information: rolling back my docker container of collabora to image 'collabora/code:24.04.4.2.1' resolved the issue.

So it is possible the issue is with collabora/code

Or perhaps it is possible with version  collabora/code:24.04.5.1.1 and onwards, nextcloud/richdocuments needs an update to remain compatible.

As such I will leave this issue here and open until advised otherwise, and incase others experience same issue and also end up here

Thanks everyone

**Comment by LMRW** [comment]
See related issue here: https://github.com/CollaboraOnline/online/issues/9519

**Comment by juliushaertl** [comment]
Thanks, I left a comment in the collabora ticket, will close here then.
