### ISSUE TITLE
"Save As" from CODE in link-shared folder can save in the folder of the user who created the share.

### ISSUE THREAD

**Issue by A-Aurel** [nextcloud/richdocuments#3830]
**Describe the bug**
When a guest "Saves as", guest can save in the folder of the user who created the share.

**To Reproduce**

USER creates a folder and shares a link with write access.
GUEST enters the folder, creates an Opendocument sheet, and opens it via Nextcloud Richdocuments app, with CODE.
GUEST "Saves as" or ("Export") to /File.ods

**Expected behavior**
The "/" is related to the files of USER, not to the share.
GUEST should be restricted to writing in the shared folder only.

**Screenshots**
N/A

**Client details:**
 - OS: Linux
 - Browser Chromium
 - Version 126.0.6478.126
 - Device: desktop

## Server details

**Operating system**:
Fedora

**Web server:**
Apache

**Database:**
Mariadb

**PHP version:**
8.3.8

**Nextcloud version:**
29.0.3

**Version of the richdocuments app**
8.4.3

**Version of Collabora Online**
COOLWSD version:
24.04.4.2 git hash: fbf97e9 (E)

**Configuration of the richdocuments app**
```
    "apps": {
        "richdocuments": {
            "canonical_webroot": "",
            "disable_certificate_verification": "",
            "enabled": "yes",
            "external_apps": "",
            "installed_version": "8.4.3",
            "public_wopi_url": "https:\/\/office.xxx.xxx:443",
            "types": "prevent_group_restriction",
            "wopi_allowlist": "10.88.0.0\/16",
            "wopi_url": "https:\/\/office.xxx.xxx:443"
        }
    }
}

```

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/richdocuments?tab=security-ov-file#readme

**Comment by joshtrichards** [comment]
For what it's worth, I cannot reproduce this behavior so far. As the share receiver, I use *Save as* (or *Export*) and save to `/blah.odt`. This file ends up in the root of the share receiver (guest in your example). The file does not appear in the share sender (user in your example) account.

**Comment by A-Aurel** [comment]
Hello,

Thanks for reading and trying to reproduce.

I did retry, with same behavior.
Perhaps I was not clear enough: I share the folder as a link to a person
who does not have an account. So per se, there is no GUEST root folder,
just access through web interface to the USER's /shared folder.
Is it what you did, or did GUEST have an account ?

Since one could not override existing files, I did not report it as
security, but I guess one GUEST can mess up the folders of the sharing user
and that can be some deal.

Do you recommend I report it as a security thing ?

Thanks
Regards

**Comment by joshtrichards** [comment]
Yes, please report it there. Thanks! :+1:

**Comment by A-Aurel** [comment]
Hi,

Done: https://hackerone.com/reports/2618417
Not sure of what all the classifications are but I put all info I could...

Thanks !
Aureliano
