### ISSUE TITLE
Can't open documents after last update Nextcloud AIO

### ISSUE THREAD

**Issue by KOCTET-SPB** [nextcloud/richdocuments#3839]
**Describe the bug**
Can't open documents after last update nextcloud:
"Failed to establish socket connection or socket connection closed unexpectedly. The reverse proxy might be misconfigured, please contact the administrator. For more info on proxy configuration please checkout https://sdk.collaboraonline.com/docs/installation/Proxy_settings.html"
**To Reproduce**

**Expected behavior**

**Screenshots**

**Client details:**
 - OS: Android 12, Windows 11
 - Browser Chrome
 - Device: Xiaomi 9, desktop 

## Server details

**Operating system**:
Ubuntu 22.04
**Web server:**
Apache/2.4.52
**Database:**

**PHP version:**

**Nextcloud version:**
Nextcloud AIO Nextcloud Hub 8 (29.0.4)
**Version of the richdocuments app**
Nextcloud Office 8.4.3
**Version of Collabora Online**
Collabora Online Development Edition 24.04.5.2 ca2ed20
**Configuration of the richdocuments app**

Insert the output of `./occ config:list richdocuments` (or equivalent adapted for your runtime environment)
```json
{   
    "apps": {        
        "richdocuments": {
            "types": "prevent_group_restriction",
            "public_wopi_url": "https:\/\/cloud.mydomen.com",
            "doc_format": "ooxml",
            "wopi_url": "https:\/\/cloud.mydomen.com\/",
            "wopi_callback_url": "",
            "enabled": "yes",
            "installed_version": "8.4.3",
            "disable_certificate_verification": "",
            "wopi_allowlist": "bbb.aaa.yyy.xxx,127.0.0.1\/8,192.168.0.0\/16,172.16.0.0\/12,10.0.0.0\/8,fd00::\/8,::1,cloud.mydomen.com,192.168.1.201,0.0.0.0\/0"
        }
    }
}
```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Ошибка | index | ExceptionCall to a member function xpath() on bool in file '/var/www/html/custom_apps/richdocuments/lib/WOPI/Parser.php' line 56
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by KOCTET-SPB** [comment]
> Are you using the AIO CODE or Built-in CODE (aka: `richdocumentscode`)?
I use what comes with the AIO

**Comment by joshtrichards** [comment]
Additional context: https://github.com/nextcloud/all-in-one/discussions/5042

**Comment by fcharlaix-opendsi** [comment]
I have the issue on a non Docker/AIO installation with Nextcloud 29.0.4 and Nextcloud Office 8.4.3.

This is an error cause by the commit ["Cleanup source code"](https://github.com/nextcloud/richdocuments/commit/75af90b4f196014ecbf333229431147009bf8950), [`simplexml_load_string`](https://github.com/nextcloud/richdocuments/blob/502046777de6cf85445c85e562cc8de2c0b5fcc1/lib/WOPI/Parser.php#L54C1-L54C56) can return `false`, [this was checked before the cleanup](https://github.com/nextcloud/richdocuments/blob/f304fd46299cffa52b0fb4c1373bd8f0789bf1ad/controller/documentcontroller.php#L72).

**Comment by KOCTET-SPB** [comment]
> I have the issue on a non Docker/AIO installation with Nextcloud 29.0.4 and Nextcloud Office 8.4.3.
> 
> [`simplexml_load_string`](https://github.com/nextcloud/richdocuments/blob/502046777de6cf85445c85e562cc8de2c0b5fcc1/lib/WOPI/Parser.php#L54C1-L54C56) can return `false`, [this was checked before the cleanup](https://github.com/nextcloud/richdocuments/blob/f304fd46299cffa52b0fb4c1373bd8f0789bf1ad/controller/documentcontroller.php#L72). This seems to return `false` because `$discovery` is null for some reason in my case. If I go into the settings and save the address (whiteout modifying anything) this solves the issue.

I saved different addresses several times.  The error in the log has disappeared, but the documents do not open, the same error:
"Failed to establish socket connection or socket connection closed unexpectedly. The reverse proxy might be misconfigured, please contact the administrator. For more info on proxy configuration please checkout"

**Comment by KOCTET-SPB** [comment]
Update to Nextcloud Office 8.4.4:
I saved the addresses several times, after which the documents open.
Works fine now. Thank you

**Comment by juliusknorr** [comment]
Closing as resolved.
