### ISSUE TITLE
WOPI address needs to be empty

### ISSUE THREAD

**Issue by bes1002t** [nextcloud/richdocuments#3856]
**Describe the bug**
Documents won't open, if the WOPI address is not empty.
A clear documentation of the issue is posted here: https://help.nextcloud.com/t/security-setting-for-nextcloud-office/151613/11
Please also clarify the security implications of the empty list.

**To Reproduce**
1. Go to 'Administration Settings'
2. In the Navigation Bar, go to 'Office'
3. Check 'Allow list for WOPI requests'

**Expected behavior**
Enter localhost and documents could be edited in browser

**Current behavior**
Document editing only works in browser, if the WOPI requests list is empty

**Client details:**
 - OS: Fedora 40
 - Browser: Firefox
 - Version: 127.0.2
 - Device: Desktop

## Server details
**Operating system**: Debian Bookworm
**Web server:** Nginx
**Database:** Mysql
**PHP version:** 8.3.9
**Nextcloud version:** Nextcloud Hub 8 (29.0.3)
**Version of Collabora Online** 24.4.402 BUILT-IN CODE Server

**Comment by XueSheng-GIT** [comment]
I don't see why WOPI needs to be empty. I assume there's a configuration issue with the CODE server.
Maybe double check the documentation.

https://sdk.collaboraonline.com/docs/installation/Configuration.html
https://sdk.collaboraonline.com/docs/How_to_integrate.html

**Comment by bes1002t** [comment]
I'm using the built in CODE server. Either there needs to be a nextcloud config update on my server, or something else is broken. But I'm not the only one with this problem, as explained in the thread I linked in the initial post.

**Comment by juliushaertl** [comment]
It is not the wopi address. It is an allow list to limit which servers can send requests to the wopi endpoints of Nextcloud, which would be recommended to set to the incoming IP that your Collabora server has. How to configure might depend on your network and reverse proxy constellation.

If the IP/subnet you try to enter does not work you can check the logs at warning level (2) to see which IP Nextcloud is actually seeing as the source.

You will see a message like this showing up that will help you configure it properly:

`WOPI request denied from 192.168.178.10 as it does not match the configured ranges: 192.168.1.0/24`

**Comment by bes1002t** [comment]
> It is not the wopi address. It is an allow list to limit which servers can send requests to the wopi endpoints of Nextcloud, which would be recommended to set to the incoming IP that your Collabora server has. How to configure might depend on your network and reverse proxy constellation.

Sorry you are right, I update the description.
 
> If the IP/subnet you try to enter does not work you can check the logs at warning level (2) to see which IP Nextcloud is actually seeing as the source.
> 
> You will see a message like this showing up that will help you configure it properly:
> 
> `WOPI request denied from 192.168.178.10 as it does not match the configured ranges: 192.168.1.0/24`
It shows the users public IP that tries to access the file, not the IP of the nextcloud or built in code server. I can not configure all IP addresses that want to access files in my cloud. So the only valid way is to keep the allow list empty.
