### ISSUE TITLE
Document shared with a team ignores download permission

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/richdocuments#3859]
**Describe the bug**
If you share a folder/file with a team (formerly circles) and disallow download, all files are just displayed, and download buttons are visible for office documents. 

**To Reproduce**
1. create team "Testteam" (formerly circles) with user A and user B
2. user A shares folder (containing .odt .md .jpg .pdf) with Testteam, removing the checkmark for the "allow download" setting
3. user B goes to shared folder
5. user B can open office files, in menu "File" there is a download button

**Expected behavior**
no download button available

Related: https://github.com/nextcloud/server/issues/46920

### Nextcloud Server version

29.0.3

**Comment by juliushaertl** [comment]
On the richdocuments side we do not make any differentiation between user and circle shares there. After checking this it seems to be a server/files issue where the attribute is not added to the database.
