### ISSUE TITLE
Revision cannot access documents in memory with Groupfolders

### ISSUE THREAD

**Issue by hriekehof** [nextcloud/richdocuments#387]
**Describe the bug**
When i access the revision history from collabora from a file within a groupfolder in NC 15 i get the following error:
- Failed, reading the document from memory. Please contact administrator

**To Reproduce**
1. Put a document into a group folder
2. Make some changes and then try to recall this changes in the revision history window from collabora
3. See error

**Expected behavior**
See the document revision you select in the revision monitor

**Screenshots**
![image](https://user-images.githubusercontent.com/9348635/52401950-4409e800-2ac3-11e9-9863-7a327fd34d8e.png)

The error in englisch is: reading from memory failed

**Client details:**
 - OS: Win10
 - Browser: chrome
 - Version: 71
 - Device: desktop

## Server details

**Operating system**: official nextcloud docker image 15.0.2

**Web server:** apache

**Database:** mariadb

**PHP version:** 7

**Nextcloud version:** 15.0.2

**Version of the richdocuments app** 3.2.0

**Version of Collabora online** 4.0.0.2

<details>

<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
[no app in context] Error: OCP\Lock\LockedException: "files/9d3d8fb84dfca6cb0074460c449bace8" is locked, existing lock on file: none at <<closure>>

 0. /var/www/html/lib/private/Files/Storage/Common.php line 778
    changeLock("files/9d3d8fb84dfca6cb0074460c449bace8", 2)
 1. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 615
    changeLock("/__groupfolders ... x", 2, OC\Lock\MemcacheLockingProvider {})
 2. /var/www/html/lib/private/Files/Storage/Wrapper/Jail.php line 469
    changeLock("/__groupfolders ... x", 2, OC\Lock\MemcacheLockingProvider {})
 3. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 615
    changeLock("Bestelliste Deu ... x", 2, OC\Lock\MemcacheLockingProvider {})
 4. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 615
    changeLock("Bestelliste Deu ... x", 2, OC\Lock\MemcacheLockingProvider {})
 5. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 615
    changeLock("Bestelliste Deu ... x", 2, OC\Lock\MemcacheLockingProvider {})
 6. /var/www/html/lib/private/Files/View.php line 1964
    changeLock("Bestelliste Deu ... x", 2, OC\Lock\MemcacheLockingProvider {})
 7. /var/www/html/lib/private/Files/View.php line 659
    changeLock("/admin/files/Ve ... x", 2)
 8. /var/www/html/lib/private/Files/Node/File.php line 66
    file_put_contents("/admin/files/Ve ... x", null)
 9. /var/www/html/custom_apps/richdocuments/lib/Controller/WopiController.php line 322
    putContent(null)
10. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 166
    putFile("2473", "x38CWIIsUucW7OZeSViAVkJ9XSygESSK")
11. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 99
    executeController(OCA\Richdocument ... {}, "putFile")
12. /var/www/html/lib/private/AppFramework/App.php line 118
    dispatch(OCA\Richdocument ... {}, "putFile")
13. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("OCA\\Richdocume ... r", "putFile", OC\AppFramework\ ... {}, {fileId: "2473_o ... "})
14. <<closure>>
    __invoke({fileId: "2473_o ... "})
15. /var/www/html/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {fileId: "2473_o ... "})
16. /var/www/html/lib/base.php line 987
    match("/apps/richdocum ... s")
17. /var/www/html/index.php line 42
    handleRequest()

POST /apps/richdocuments/wopi/files/2473_ocd792058piq/contents?access_token=x38CWIIsUucW7OZeSViAVkJ9XSygESSK&access_token_ttl=0&permission=edit
from 172.18.0.2 by admin at 2019-02-07T09:09:27+00:00
```
</details>

**Comment by juliushaertl** [comment]
I can reproduce this. Unfortunately groupfolder versions are stored in a different location then the default user files ones we try to fetch at https://github.com/nextcloud/richdocuments/blob/56bd27d5c51e7b1b614b87af6a4bb77b1eb8613d/lib/Controller/WopiController.php#L212

**Comment by bbolokofsky** [comment]
This seems to still be a problem.  Is this not fixable?

**Comment by juliushaertl** [comment]
Dived a bit further into this, it should be fairly simple to implement with using https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/apps/files_versions/lib/Versions/VersionManager.php#L85 to get the file version instead of the manual fetching through the View.
