### ISSUE TITLE
Richdocuments doesn't work with IE 11 since 3.2.0

### ISSUE THREAD

**Issue by thebearon** [nextcloud/richdocuments#388]
If I open Nextcloud with Collabora Online integration app in Internet Explorer 11, file opening doesn't work (wants to download instead), and the '+' for new doesn't list document/spreadsheet/presentation types.

Bisected to the following commit: ec388693be862795a37820a1380be02c898d09f6

In developer console it has problems with the following line:
https://github.com/nextcloud/richdocuments/blob/ec388693be862795a37820a1380be02c898d09f6/js/viewer/viewer.js#L3
Error message: Object doesn't support this action.

@juliushaertl, please take a look at it.

**Comment by eszkadev** [comment]
f0f151268156fcfafc1dfebe97fc1c5e8211607d caused this bug
edd9c6bb3ef9e9d71d28b39db5e814f8b4166b4d is a last working commit

**Comment by juliushaertl** [comment]
Thanks for bisecting, I'll have a look.
