### ISSUE TITLE
Shared documents with different results for Dark/Light Modes

### ISSUE THREAD

**Issue by BiglifeMatt** [nextcloud/richdocuments#3896]
**Describe the bug**
If a user shares a Nextcloud Doc made while in Light Mode with someone, and that other person opens the doc on a device set to Dark Mode, the font colors are not reversed so the result is black font on black background.

**Expected behavior**
Documents to adjust both in web browsers as well as mobile apps to transform the document based on the devices mode setting.

## Server details

**Operating system**: Ubuntu 22.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 8.1.2

**Nextcloud version:** 28.0.8

**Version of the richdocuments app** 8.3.9

**Version of Collabora Online** 23.05.7.5

**Configuration of the richdocuments app** 
```
Insert the output of `./occ config:list richdocuments` (or equivalent adapted for your runtime environment)
```

**Comment by juliushaertl** [comment]
The reason for this is likely that the document you are using does have a static text color set (e.g. black) instead of using an automatic color. Collabora does not automatically invert colors unless the automatic color is set.

**Comment by BiglifeMatt** [comment]
Still need help here.  I can create a new document in either Nextcloud Hub, or the Nextcloud phone app.  If I choose to save as .docx, then the mode will not change the font color, but if I save as .odt then it will flip the color properly.  I have set my server defaults to open format files but this seems to be an issue with trying to use MS format which could still be an issue.
