### ISSUE TITLE
Can't reopen file where i leave it

### ISSUE THREAD

**Issue by warnerbryce** [nextcloud/richdocuments#39]
### Steps to reproduce
1. Create a spreadsheet with a lot of lines
2. Put some things inside and close the document at line 122 for exemple, collum G for exemple
3. Save and close the spreadsheet
4. Reopen the file

### Expected behaviour
On older versions of richdocument, i should restart directly where i leave the doc. In this exemple on line 122 - G 

### Actual behaviour
Now the app start on the uper left, and i have to scroll down to find where i have to continue to edit my file. Therefore, the line 122 and collum G are in Blue. 

### Server configuration
**Operating system**: ubuntu server 16.04

**Web server:** apache 2.4

**Database:** MariaDB 10.1

**PHP version:** php 7.0

**Nextcloud version:** (see Nextcloud admin page) 11.0.2 happen on older version too

**Updated from an older Nextcloud/ownCloud or fresh install:** both

**Where did you install Nextcloud from:** tested for nextcloud.com and updated with the updaterapp. 

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.4.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - richdocuments: 1.1.25
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "oc9wfqf2th66",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.10.19",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Paris",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "maintenance": false,
        "loglevel": 3,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "updater.release.channel": "stable"
    }
}
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** All of them, Safari on OS X, Firefox on OS X / Windows, Chrome OS X / Windows

**Operating system:** OS X 10.10.5 -> 10.12.4 / Windows 7 -> 10 

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by timar** [comment]
The cell cursor is there where you left it. It is only the view that is out of sight. If you move the cell cursor with arrow keys, the view will jump there. 

What was that older version of richdocuments, which was working for you? Also, what are the version numbers shown in Help - About of Collabora Online?

**Comment by warnerbryce** [comment]
I don't know the version number, but it was working on Nextcloud 10. Thanks for the tip with the arrow keys, it will help my teamates for waiting a fix.

**Comment by warnerbryce** [comment]
Same issue with Nextcloud 12 Beta 2 and Collabora Apps 1.1.26

**Comment by pranavk** [comment]
This isn't a richdocuments issue at all. It should ideally filed as a bug in bugs.documentfoundation.org against LibreOffice Online.
