### ISSUE TITLE
richdocuments 3.2.0 breaks android collabora editing

### ISSUE THREAD

**Issue by himpierre** [nextcloud/richdocuments#390]
Hello Devs.

After the richdocuments 3.2.0 update editing of documents is not possible anymore via android client. When opening a document the blue circle keeps spinning and does not recover from that.

**To Reproduce**
1. Open a Document (.odt for example) with the android client
2. Blue circle keeps spinning forever

**Expected behavior**
Document opens.

**Client details:**
 - OS: Android Pie
 - Browser Nextcloud Android Client
 - Version 3.4.2 and 3.5.0-rc2
 - Device: LG G6

## Server details

**Operating system**: Linux 

**Web server:** Apache

**Database:** Mysql

**PHP version:** 7.2

**Nextcloud version:** 15.0.4

**Version of the richdocuments app** 3.2.0

**Version of Collabora online** Latest (4.0.0)

**Comment by gradinaruvasile** [comment]
Same here. Endlessly spinning circle.
Collabora 4.0, richdocuments 3.2.0, NC 15.04, Nextcloud Android 3.5.0 RC2, dev last 3 versions from FDROID. Android Pie on Nokia 5.

Collabora works otherwise on desktop and in mobile browser.

**Comment by laopisai** [comment]
Same happened.
My android client is installed from F-Droid, version 3.4.2, on Google Pixel

NC 15.04, richdocuments 3.2.0, Collabora/code 4.0.0.2 on docker

**Comment by juliushaertl** [comment]
@tobiasKaminsky Anything changed recently on the android side? Because from 3.1.1 to 3.2.0 we only changed the way we fetch capabilities but those shouldn't have any influence on the loading process on android.

**Comment by ebogaard** [comment]
Maybe this gives some extra info: next to issues with Android, we experience a similar problem when editing documents shared by URL with 3.2.0. We just keep seeing the loading screen, nothing else happens.
In the networking- and browserconsole we see some 404 errors when this happens.

When editing your own documents, 3.2.0 works fine.

**Comment by tobiasKaminsky** [comment]
Endless spinner means that the url is either not loaded or the returning website has a problem, as the spinner is only removed once collabora is saying "document loaded".

I will try it on my own instance after upgrade.

**Comment by loxK** [comment]
I manage two instances. Since updating to 3.2.0 I have the exact same issue on both instances. Why has it been closed ? Is it a duplicate of #397 ?

**Operating system**: Ubuntu
**Web server:** nginx
**Database:** Mysql
**PHP version:** 7.2.0
**Nextcloud version:** 15.0.4
**Version of the richdocuments app** 3.2.0
**Version of Collabora online**  latest version (docker)

```
# docker pull collabora/code 
Using default tag: latest
latest: Pulling from collabora/code
Digest: sha256:3e71b254093247800f498e69f6e444d04c23c00ca38c7cf887a20bf8d5b3d40c
Status: Image is up to date for collabora/code:latest
```

<details>
<summary>Logs</summary>

#### Web server error log
```
Nothing revealent, no error
```

#### Nextcloud log (data/nextcloud.log)
```
Nothing revealent, no error
```
#### Device logs
```
02-14 10:57:06.299  3671  4483 I ActivityManager: Start proc 30597:com.android.chrome:sandboxed_process3/u0i120 for webview_service com.nextcloud.client/org.chromium.content.app.SandboxedProcessService3
02-14 10:57:06.697 30597 30624 I chromium: [INFO:library_loader_hooks.cc(42)] Chromium logging enabled: level = 0, default verbosity = 0
02-14 10:57:06.989 26316 26316 I chromium: [INFO:CONSOLE(7)] "JQMIGRATE: Migrate is installed, version 1.4.0", source: https://mydomain.com/nextcloud/core/vendor/core.js?v=aa1dfbab-18 (7)
02-14 10:57:07.161 26316 26316 I chromium: [INFO:CONSOLE(3711)] "Deprecation warning: tipsy is deprecated. Use tooltip instead.", source: https://mydomain.com/nextcloud/js/core/merged-template-prepend.js?v=aa1dfbab-18 (3711)
02-14 10:57:07.168 26316 26316 I chromium: [INFO:CONSOLE(548)] "Waiting for page to render…", source: https://mydomain.com/nextcloud/apps.installed/richdocuments/js/documents.js?v=aa1dfbab-18 (548)
02-14 10:57:07.172 26316 26316 I chromium: [INFO:CONSOLE(841)] "Uncaught TypeError: parent.OCA.Files.App.fileList.reload is not a function", source: https://mydomain.com/nextcloud/apps.installed/richdocuments/js/documents.js?v=aa1dfbab-18 (841)
02-14 10:57:07.238 26316 26316 I chromium: [INFO:CONSOLE(0)] "Failed to decode downloaded font: https://mydomain.com/nextcloud/core/fonts/Nunito-Regular.woff2", source: https://mydomain.com/nextcloud/apps/richdocuments/direct/MYGzKD3prIp0Ya5e9INbTSaHDDU3johbwVxg0dP1bxyCa6wh6BNaKrUvVOta9cnS (0)
02-14 10:57:07.238 26316 26316 I chromium: [INFO:CONSOLE(0)] "OTS parsing error: invalid version tag", source: https://mydomain.com/nextcloud/apps/richdocuments/direct/MYGzKD3prIp0Ya5e9INbTSaHDDU3johbwVxg0dP1bxyCa6wh6BNaKrUvVOta9cnS (0)
02-14 10:57:08.005 26316 26316 I chromium: [INFO:CONSOLE(22)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.", source: https://mydomain.com/loleaflet/bdf2f61/bundle.js (22)
```

</details>

**Comment by gradinaruvasile** [comment]
It was fixed in this commit:

https://github.com/nextcloud/richdocuments/commit/d8f8f5928685ff413e46be925b6fcfd266556efa

I tested it by manually applying it and mobile editing works.

**Comment by loxK** [comment]
Thanks I did it manually and I can confirm too that it fixes the bug.

**Comment by tobiasKaminsky** [comment]
@juliushaertl can you draft a new release?

**Comment by typorian** [comment]
The fix is not present in 3.2.1 right?

**Comment by tobiasKaminsky** [comment]
@typorian for me it is working with 3.2.1.

**Comment by juliushaertl** [comment]
@typorian The fix is included in 3.2.1, in case you still have problems please open a new issue with a complete issue template filled out for more information.

**Comment by laopisai** [comment]
Just upgrade to 3.2.2, seems like regression?

**Comment by pfoo** [comment]
Same here, since upgrade to 3.2.2, I cannot open documents in nextcloud android app anymore, it stay stuck on the blue circle spinning forever.
However, the document is show opened (but inactive) in CODE admin console.
Reverting to 3.2.1 makes it works again

**Comment by gradinaruvasile** [comment]
With 3.2.2 mobile editing doesn't work again...

Did you guy test this feature with new richdocuments releases?
