### ISSUE TITLE
Cannot insert image from the NC storage into document

### ISSUE THREAD

**Issue by eszkadev** [nextcloud/richdocuments#3902]
**Describe the bug**
User tries to insert remote image (from NC file picker) and it doesn't do anything.

**To Reproduce**
1. Open any document in Nextcloud Office
2. Insert -> Insert Image... (it shows NC file picker)
3. Double click on any entry (or even anywhere in the dialog?)
4. Click button 'Insert Image'

Result: no image inserted, in the browser console we can see error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'path')
    at callback (FilesAppIntegration.js:141:1)
    at handleButtonClick (FilePicker-DUbP4INd.mjs:1590:1)
    at Object.callback (FilePicker-DUbP4INd.mjs:1584:1)
    at handleClick (NcDialogButton-JvyN3X6S.mjs:57:1)
    at $a (vue.runtime.esm.js:3033:30)
    at l.a (vue.runtime.esm.js:1832:20)
    at $a (vue.runtime.esm.js:3033:30)
    at Uw.e.$emit (vue.runtime.esm.js:3732:17)
    at click (NcButton.mjs:225:1)
    at $a (vue.runtime.esm.js:3033:30)
    ```

Note: the same error appears if double clicked empty dialog (no available images).

**Expected behavior**
Image is inserted.

## Server details
NC 30 (master), richdocuments (main)

richdocuments:
commit 5afc01eac15cb61378489234bd3adad81257b831 (HEAD -> main, origin/main)
Merge pull request #3835 from nextcloud/dependabot/npm_and_yarn/requirejs-2.3.7

Nextcloud git hash:
commit 003e4b9939e693f16fa24ed4beb2e0d8b0d37168 (HEAD -> master, origin/master, origin/HEAD)
Fix(l10n): Update translations from Transifex

**Comment by juliushaertl** [comment]
We should also extend the test to not only assert for the modal to be visible 🙈 https://github.com/nextcloud/richdocuments/blob/main/cypress/e2e/integration.spec.js#L115-L122
