### ISSUE TITLE
#about-dialog too big

### ISSUE THREAD

**Issue by jooooaah** [nextcloud/richdocuments#3903]
**Describe the bug**
Not sure if that repo ist the right one - but sounds better than collabora.

When opening an office document in Nextcloud, the credits beyond the footer are way too big, even if the credits should not be reduced in any way.  div #about-dialog beyond footer has 355px height

**To Reproduce**
1. Open Nextcloud in browser
2. Open Office-Document (doesn't matter which type)

**Expected behavior**
Smaller credit line at the bottom page

**Screenshots**
![Firefox_Screenshot_2024-08-14T09-07-39 138Z](https://github.com/user-attachments/assets/0f318333-1209-4695-a0f9-bc60c0c4b2ef)

**Client details:**
 - OS: Win10, OpenSuse (Server on Ubuntu 22.04)
 - Browser: tested with Chromium and firefox
 - Device: [Android and desktop]

## Server details
Nextcloud 28.0.6, NC Office 8.3.9, Coolwsd 24.4.6.1
**Operating system**:
Ubuntu 22.04

**PHP version:**
8.1

**Nextcloud version:**
28.0.6

**Version of the richdocuments app**
8.3.9

**Version of Collabora Online**
24.4.6.1

#### Browser log
```
Message should be filterd during slurp [bundle.js:17059:49](https://xxx.xx/collabora/browser/8ec5fda/bundle.js)
    _onMessage https://xxx.xx/collabora/browser/8ec5fda/bundle.js:17059
    _onMessage https://xxx.xx/collabora/browser/8ec5fda/bundle.js:10276
    _emitSlurpedEvents https://xxx.xx/collabora/browser/8ec5fda/bundle.js:10022
    _slurpTimer https://xxx.xx/collabora/browser/8ec5fda/bundle.js:10009
    (Async: setTimeout handler)
    _queueSlurpEventEmission https://xxx.xx/collabora/browser/8ec5fda/bundle.js:10008
    _slurpMessage https://xxx.xx/collabora/browser/8ec5fda/bundle.js:10034
    _emptyQueue https://xxx.xx/collabora/browser/8ec5fda/bundle.js:9941
    connect https://xxx.xx/collabora/browser/8ec5fda/bundle.js:9939
    loadDocument https://xxx.xx/collabora/browser/8ec5fda/bundle.js:11030
    <anonym> https://xxx.xx/collabora/browser/8ec5fda/bundle.js:34711
    <anonym> https://xxx.xx/collabora/browser/8ec5fda/bundle.js:34715
    <anonym> https://xxx.xx/collabora/browser/8ec5fda/bundle.js:34715

```

</details>

**Comment by juliushaertl** [comment]
This issue tracker is only for the Nextcloud connector app named Collabora Online. For issues with Collabora Online itself, please open a bug report at: https://github.com/collaboraonline/online
