### ISSUE TITLE
Theme logo not appearing, top left navigation

### ISSUE THREAD

**Issue by nooblag** [nextcloud/richdocuments#3935]
**Describe the bug**
A theme logo no longer appears in Nextcloud Office/Collabora, top left navigation.

**To Reproduce**
1. Open a document

**Expected behavior**
Collabora pulls logo from Nextcloud theme as usual/before.

**Actual behavior**
Nextcloud logo appears. Theme logo is ignored.

**Screenshots**
![Screenshot from 2024-08-21 05-52-38](https://github.com/user-attachments/assets/bc6ac8dd-c51d-425a-889d-1b82dd24f00c)

**Client details:**
 - OS: All OSes
 - Browser All browsers

## Server details

**Operating system**:
Ubuntu 22.04.4 LTS

**Web server:**
nginx version: nginx/1.18.0 (Ubuntu) 

**Database:**
psql (PostgreSQL) 14.13 (Ubuntu 14.13-0ubuntu0.22.04.1)

**PHP version:**
PHP 8.2.22 (cli) (built: Aug  2 2024 15:36:02) (NTS)

**Nextcloud version:**
29.0.5

**Version of the richdocuments app**
8.4.4

**Version of Collabora Online**
COOLWSD version: 24.04.6.2 (git hash: 4fd2181 (E))
LOKit version: Collabora Office 24.04.6.2 (git hash: 47680e0)

**Configuration of the richdocuments app**
```
{
    "apps": {
        "richdocuments": {
            "wopi_allowlist": "127.0.0.1, ***redacted_IP***",
            "doc_format": "ooxml",
            "public_wopi_url": "https:\/\/***redacted_URL***",
            "external_apps": "Public Access:***redacted_key***,",
            "types": "prevent_group_restriction",
            "canonical_webroot": "",
            "wopi_url": "https:\/\/***redacted_URL***",
            "disable_certificate_verification": "",
            "installed_version": "8.4.4",
            "enabled": "yes"
        }
    }
}
```

**Comment by juliushaertl** [comment]
Was fixed with https://github.com/nextcloud/richdocuments/pull/3925

**Comment by nooblag** [comment]
Regression on this?

Theme logo again not appearing with:

```
COOLWSD version: 24.04.10.2(git hash: a4b67a7664 (E))
LOKit version: Collabora Office 24.04.10.2(git hash: 9d0c2a6)
Served by: Ubuntu 22.04.5 LTS
```

**Comment by elzody** [comment]
@nooblag Are you using the most recent version of Nextcloud Office for Nextcloud 29? It should be richdocuments v8.4.9.

**Comment by nooblag** [comment]
Thank you for getting back. Yes, running Nextcloud Office (richdocuments) version 8.4.9.

**Comment by wico** [comment]
Exact same issue here, the logo suddenly became the default one after upgrading to 24.04.10.2. The nextcloud-version does not matter, it happens with Nextcloud Hub 8 (29.0.10) and older versions. Richdocuments is on Version 8.4.9.

**Comment by elzody** [comment]
Unfortunately, I can confirm this now. Will be considered a regression I guess, and I will have a look how to fix it.

**Comment by juliusknorr** [comment]
Not sure how, but some kind of test case for this would be great to catch further regressions early next time.

**Comment by joshtrichards** [comment]
Maybe #4104 introduced this regression?

**Comment by juliusknorr** [comment]
I think this has been fixed again, I can no longer reproduce

**Comment by juliusknorr** [comment]
New design adjustment now removed the logo and replaced it with the file type icon

**Comment by muchachagrande** [comment]
I'm having this issue on latest update to Nextcloud 32.0.3, Office 9.0.2

Browser shows this error when I open a document:

```
Error 400:
https://wopi.example.com/browser/a0576a3364/%LOGO_URL%
```

May be this %LOGO_URL% should be solved to the proper logo name... I don't know.

**Comment by juliusknorr** [comment]
@pedropintosilva Is that error known?

However for the Nextcloud Office UI we decided no no longer show the logo as mentioned above

**Comment by wico** [comment]
<img width="1933" height="302" alt="Image" src="https://github.com/user-attachments/assets/d8960296-2d76-4b4f-992b-7153ba6ff907" />
