### ISSUE TITLE
Development Edition stops after a few hours?

### ISSUE THREAD

**Issue by sbe-arg** [nextcloud/richdocuments#3936]
**Describe the bug**
I have a weird behavior going on.

Every 2-3 days I have the need to edit documents. Each time I try to load any document I get the error for "Unable to load document" after 2-3 retries it starts working and works for a few hours trough the day without any issue and then the issue happens again.

Is there any sort of sleeping mechanism or warm-up required? But is the only think i can think of at the moment. Like if the Development server stops after X time and gets started only when a file is opened.

I don't mind If I it will waste a bit more resources but I'd prefer to have it running warm all the time.

**To Reproduce**
Open any file after 2 days of not using the editor.

**Expected behavior**
Always open documents without taking several retries to start?

**Screenshots**

**Client details:**
 - OS: Ubuntu 24.04
It happens on all clients.

## Server details

**Operating system**:
ubuntu 24.04

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:**
29 snap (but also occurs on 29 docker)

**Version of the richdocuments app**
8.4.4 - 24.04.5.2 ca2ed20

**Version of Collabora Online**
8.4.4 - 24.04.5.2 ca2ed20

**Configuration of the richdocuments app**
```
{
    "apps": {
        "richdocuments": {
            "disable_certificate_verification": "yes",
            "doc_format": "ooxml",
            "edit_groups": "",
            "enabled": "yes",
            "installed_version": "8.4.4",
            "types": "prevent_group_restriction",
            "use_groups": "",
            "wopi_allowlist": "172.16.0.0\/12,192.168.1.0\/24",
            "wopi_url": "https:\/\/cloud.somedomain.tld\/extra-apps\/richdocumentscode\/proxy.php?req="
        }
    }
}

```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
There are no logs capture by this behaviour.
```

</details>

**Comment by juliushaertl** [comment]
This sounds like an issue with https://github.com/CollaboraOnline/richdocumentscode so maybe you can file an issue over there. I generally would recommend a dedicated Collabora setup either using distribution packages or a docker container. While the "built-in CODE server" is an easy way to get it running, it is just spawning a process and there is not very much control over it if it gets killed for some reason.
