### ISSUE TITLE
Smart picker not working for document sections

### ISSUE THREAD

**Issue by pedropintosilva** [nextcloud/richdocuments#3957]
**Describe the bug**
I have noticed today that the https://sdk.collaboraonline.com/docs/linking_api.html is not working: https://paste.opensuse.org/pastes/3be00af7d685 . 

https://github.com/user-attachments/assets/a0de5e19-1f28-45c7-8c07-c246af608a73

I could reproduce this with current master and stable but also I have tried with a slightly older combination and I still get the same result:
* COOL 24.04.4.2 git hash: fbf97e9 (E)
* Richdocuments 8.4.3

**Comment by juliushaertl** [comment]
Fails at https://github.com/nextcloud-libraries/nextcloud-dialogs/blame/144923cd026110e33e824b445dffad827b91a8b1/lib/utils/dialogs.ts#L19 as we pass in an element not a selector

**Comment by juliushaertl** [comment]
We should actually use https://github.com/nextcloud-libraries/nextcloud-dialogs?tab=readme-ov-file#use-the-vue-component-directly instead
