### ISSUE TITLE
Nextcloud office | cant open any of my documents

### ISSUE THREAD

**Issue by cino-cafe** [nextcloud/richdocuments#3959]
i have just updated my Nextcloud server to [Nextcloud Hub 8] (29.0.5)

and now when i try to open any of my text documents or presentations it says this "Failed to load Nextcloud Office - please try again later"

but for some reason PDF documents do open 

Nextcloud is running on my Raspberry pi 5 - 8GB RAM

please let me know if you know how to resolve this

**Comment by juliushaertl** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

**Comment by cino-cafe** [comment]
> As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

Hi i have now fixed the issue it was due to the new updates form Nextcloud so i restored my Nextcloud version from my backups down to [Nextcloud Hub 8] (29.0.4) and now everything works perfectly. thanks for the help anyway
