### ISSUE TITLE
tab stops are difficult to see and click on in ruler

### ISSUE THREAD

**Issue by benniekiss** [nextcloud/richdocuments#3964]
**Describe the bug**

When adding tab stops by right-clicking the ruler, the rendered indicators are very small, difficult to see, and difficult move and remove. With darkmode, they are nearly impossible to see. 

**To Reproduce**
1. Enable the document ruler
2. Right click on the ruler
3. Add tab stop

**Expected behavior**

The indicators should be bigger, and they should show the shape associated with the type of tab stop

**Screenshots**
<img width="185" alt="Screenshot 2024-08-31 at 16 25 19" src="https://github.com/user-attachments/assets/856c7523-fb71-48f3-a6b4-606d8fd6fdd5">
<img width="187" alt="Screenshot 2024-08-31 at 16 24 13" src="https://github.com/user-attachments/assets/f8ac3612-630f-4081-be8b-9c7bc83710ed">

**Client details:**
 - OS: web
 - Browser: firefox
 - Version: 8.4.5
 - Device: browser

## Server details

**Operating system**:
linux
**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:**
Nextcloud Hub 8 (29.0.5)

**Version of the richdocuments app**
8.4.5

**Version of Collabora Online**
24.04.6.2

**Configuration of the richdocuments app**
```
{
    "apps": {
        "richdocuments": {
            "types": "prevent_group_restriction",
            "disable_certificate_verification": "",
            "canonical_webroot": "",
            "external_apps": "",
            "wopi_allowlist": "10.10.10.0\/24,10.10.20.0\/24,100.64.0.0\/24",
            "enabled": "yes",
            "public_wopi_url": "https:\/\/collabora.gts.bbalm.me",
            "wopi_url": "https:\/\/collabora.gts.bbalm.me",
            "doc_format": "ooxml",
            "installed_version": "8.4.5",
            "edit_groups": "56df26afced0daa87aa79b0e1b4cf31d90f3966fd2edd852e352ab7a176e844e|admin",
            "use_groups": "56df26afced0daa87aa79b0e1b4cf31d90f3966fd2edd852e352ab7a176e844e|admin"
        }
    }
}
```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
This issue tracker is only for the Nextcloud connector app named Collabora Online. For issues with Collabora Online itself, please open a bug report at: https://github.com/collaboraonline/online

**Comment by juliushaertl** [comment]
FYI @pedropintosilva @jancborchardt

**Comment by benniekiss** [comment]
I tested with Collabora on the ownCloud OCIS [demo instance](https://demo.owncloud.com), and it seems that the tab stops are actually rendered below the ruler. Not sure if this would still be an issue with richdocuments since it seems to be cutting off the rendering below the ruler entirely


<img width="875" alt="Screenshot 2024-09-16 at 05 44 53" src="https://github.com/user-attachments/assets/86553b44-5a68-4fb2-a792-bcf43db827dc">


The accessibility issues with dark mode are the same on the OCIS instance, so that seems to be an upstream issue.
