### ISSUE TITLE
richdocuments 3.2.0 editing document in share by URL link seems to have cross-site problem

### ISSUE THREAD

**Issue by ljo** [nextcloud/richdocuments#397]
**Describe the bug**
[As mentioned in comment of #390](https://github.com/nextcloud/richdocuments/issues/390#issuecomment-462289813) loading of editor page fails if using share by URL collection or document. For local users it works fine.

**To Reproduce**
1. Access a share by URL link collection or document.
2. In js console you get a Content Security Policy error: The page settings blocked the loading of a resource on inline (“script-src”).
3. When loading a editable document this blocking in 2) leads to a `Type error: Cannot read property 'fileList' of undefined` in js/documents.js. With #390 applied the error just moves to line 841 instead of line 615. 

## Server details

**Nextcloud version:**
v15.0.2-v15.0.4

**Version of the richdocuments app**
v3.2.0

**Version of Collabora online**
CODE4-rc3

Cheers!

**Comment by juliushaertl** [comment]
I can reproduce the error on public pages, however loading the document and editing works just fine. Do you see an error message or just the loading spinner? Are there errors in the network log of your browser?

**Comment by ljo** [comment]
@juliushaertl in UI it is only the loading spinner showing. In js console the error in step 3 shows.
In network log there is a 401 on ajax/settings.php and 404 as in attached image
![richdocument-share-by-link-20190211](https://user-images.githubusercontent.com/191478/52573625-da6b4000-2e1a-11e9-8b93-7ccbddb0c44c.png)

**Comment by danger89** [comment]
https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html?highlight=nginx

**Comment by danger89** [comment]
I want to add here that I'm currently facing a lot of issues with Libreoffice Online/Richdocuments & Nextcloud due to Content Security Policy.

I'm using the official [Nginx reverse proxy config of Nextcloud](https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html?highlight=nginx).

The default Nginx Nextcloud config is resulting in a lot of failures during execution.

Including but not limited by:

- Errors/warnings from the Libreoffice Online itself:
```
wsd-00015-00023 2019-02-26 18:05:24.485582 [ websrv_poll ] WRN  client - server version mismatch, disabling browser cache.| wsd/FileServer.cpp:279                                                         
wsd-00015-00023 2019-02-26 18:05:24.620217 [ websrv_poll ] WRN  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/8a61a5302/branding.js].| wsd/FileServer.cpp:425                 
wsd-00015-00023 2019-02-26 18:05:24.813640 [ websrv_poll ] WRN  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/8a61a5302/branding.js].| wsd/FileServer.cpp:425                 
wsd-00015-00023 2019-02-26 18:05:25.868642 [ websrv_poll ] WRN  client - server version mismatch, disabling browser cache.| wsd/FileServer.cpp:279                                                         
wsd-00015-00023 2019-02-26 18:05:26.018280 [ websrv_poll ] WRN  FileServerRequestHandler: File not found: Invalid URI request: [/loleaflet/8a61a5302/branding.js].| wsd/FileServer.cpp:425
```
And web console browser output:

![image](https://user-images.githubusercontent.com/628926/53437589-2c58bc00-39fe-11e9-81a9-bfc03a34032a.png)


I advise you to work more closely together with Nextcloud. Especially regarding the Nginx configuration files!

**Comment by juliushaertl** [comment]
Ok this seems to be a duplicate of #408 which will be fixed  with https://github.com/nextcloud/richdocuments/pull/412

@danger89 The CSP should actually be properly set by the richdocuments app to the wopi_url configured: https://github.com/nextcloud/richdocuments/blob/970ecadce4a39fd634c56aa583ff8ee5d8b8bdd3/appinfo/app.php#L66-L71 Note that both the Nextcloud server as well as the client browser needs to be able to contact the collabora server though that url.
