### ISSUE TITLE
Add draw functionality

### ISSUE THREAD

**Issue by tobias0409** [nextcloud/richdocuments#3972]
**Is your feature request related to a problem? Please describe.**
As a student, I frequently need to switch quickly between typing with the keyboard and taking handwritten notes. The current setup makes it challenging to seamlessly transition between these two methods, which slows down my workflow and impacts my productivity.

**Describe the solution you'd like**
I would like to suggest adding a "Draw" tab similar to the one in MS Word or OnlyOffice. This tab should include multiple pens, an eraser, and other drawing tools, allowing users to easily draw and take handwritten notes directly within the application. This would make it easier to switch between typing and handwriting without needing to switch applications or use external tools.

**Comment by joshtrichards** [comment]
I believe the repository you're looking for is this one: https://github.com/CollaboraOnline/online

This repository is just for the integration app between Collabora and Nextcloud.
