### ISSUE TITLE
Localization of "Enter Guest name" field don't work for German, Russian, French

### ISSUE THREAD

**Issue by clevermind-me** [nextcloud/richdocuments#4029]
Pop-up window "Enter Guest name" have to be translated to other languages except English, but in German,Russian and French text is not located - displays in English. This particular string seems to be already translated in ru_RU, de_DE and french one .json files, line 133, and most of other translations works - except this one.

The situation of its use is wide common. Files are shared with people who are not fluent in English. So it's problem.

1. Choose Russian (German/French) language for administrator.
2. Share an office (text) file with read-only access. You can use https://office.agrant.ru/index.php/s/dA9T5WG8dS4Cf4X
3. Open the link from another browser where you are not authorized in Nexcloud.
5. See error see pop-up window in English where Nextcloud asks for a Guest name: "Please enter the guest name you wish to use before proceeding to the document. If you don’t provide one, the default will be used."

Pop-up window where Nextcloud asks for a Guest name should display:
Пожалуйста, введите имя гостя, которое вы хотите использовать, прежде чем перейти к документу. Если вы не предоставите его, будет использовано имя по умолчанию.

Screenshot
<img width="1440" alt="Снимок экрана 2024-09-12 в 21 31 52" src="https://github.com/user-attachments/assets/e4c987e7-a1b2-4730-b425-982c9aecc175">

- macOS
 - Browser chrome, opera
 - Device: desktop

Server details
Operating system Linux 6.1.0-21-amd64 x86_64
Nextcloud version: Version 29.0.2

**Comment by juliushaertl** [comment]
This will be addressed as soon as the translations are done on https://explore.transifex.com/nextcloud/nextcloud/ they will sync to this repository and become available with the next patch release.
