### ISSUE TITLE
Welcome to Nextcloud Hub.docx should be prepared for Dark mode

### ISSUE THREAD

**Issue by timur-g** [nextcloud/richdocuments#4033]
NC has a sample document "Welcome to Nextcloud Hub.docx" that does not look nice in Dark mode, as it is done with white background and black text. Now that NC and RD long support Dark mode, that document should be prepared to look nice in Dark. 
Seen also with NC 30.

**Comment by juliushaertl** [comment]
Thanks for reporting. I've pushed an updated version in https://github.com/nextcloud/example-files/pull/32
