### ISSUE TITLE
Nextcloud timeouts when trying to open documents with collabora

### ISSUE THREAD

**Issue by podhorsky-ksj** [nextcloud/richdocuments#4040]
**Describe the bug**
Nextcloud timeouts when trying to open documents with collabora.
Connection in office is green.

I googled for everything, even tried to downgrade collabora.

**To Reproduce**
Go to files
Open xlsx document
It is opening, then it fails with timeout

There is nothing in collabora log and nothing in nextcloud log

When I tried before the collabora build-it it didn't work either
Only the demo is working

**Expected behavior**
Open document in collabora

**Screenshots**
![Screenshot from 2024-09-16 10-06-47](https://github.com/user-attachments/assets/d929c0c5-4ddc-4c24-abf8-5288d419f6d5)
![image](https://github.com/user-attachments/assets/b466c354-8a0e-4a82-84ba-3a6f28b6d8d1)

**Client details:**
 - OS: Fedora workstation 40
 - Browser firefox, chromium
 - Version latest
 
## Server details
All nextcloud and collabora run in podman rootless containers on podman network (with quadlet files)
I have no issue with nextcloud itself, if it's needed, I will provide all quadlet files.

Curl command with capabilities (not sure how it was, but I have tried it during googling for issues) from nextcloud to collabora 

**Operating system**:
Fedora server 40

**Web server:**

**Database:**
postgress docker.io/postgres:latest

**PHP version:**

**Nextcloud version:**
docker.io/library/nextcloud:latest

**Version of the richdocuments app**

**Version of Collabora Online**
I tried 24.04.7.2.1 and 24.04.5.1.1, because at least under podman 24.04.7.2.1 shows some errors in log

**Configuration of the richdocuments app**
```
{
    "apps": {
        "richdocuments": {
            "installed_version": "8.4.6",
            "types": "prevent_group_restriction",
            "enabled": "yes",
            "disable_certificate_verification": "yes",
            "public_wopi_url": "https:\/\/192.168.4.5:9980",
            "canonical_webroot": "",
            "external_apps": "",
            "wopi_allowlist": "0.0.0.0\/0",
            "wopi_url": "http:\/\/192.168.4.5:9980"
        }
    }
}
```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
there is nothing about the opening files. not even in debug logs
```

#### Browser log
```
in screenshot
```

</details>

**Comment by juliushaertl** [comment]
Can you check your browsers network console? There should be a request towards the collabora server URL to a browser.html file that is supposed to be loaded in an iframe. Maybe that fails for some reason? Can you check if the URL itself that is used is correct there and working generally in the browser?

**Comment by podhorsky-ksj** [comment]
You mean this POST?  
  POST
	https://192.168.4.5:9980/browser/48bf0bf/cool.html?WOPISrc=https://****:1180/index.php/apps/richdocuments/wopi/files/12500_ockwjlr0cmfa&title=/Documents/Dane/Dane2023/investice/Vypocet2022.xlsx&lang=en&closebutton=1&revisionhistory=1

I'm not sure how it should look like. If WOPIS should be 192.168.4.5 too or not.

When I looked to this, I have to mention something.
I have my own nginx and credentials for https, so I don't need to have any credentials on nextcloud. I just redirect request from nginx to podman published ports.
Also I have to done in config.php these changes:
```
 'overwrite.cli.url' => 'http://****.:1180',
  'overwriteprotocol' => 'https',
  'overwritehost' => '****:1180',
```
where **** is my domain
Otherwise i get:
```
Access through untrusted domain

Please contact your administrator. If you are an administrator, edit the "trusted_domains" setting in config/config.php like the example in config.sample.php. 
```
I just saying it, because I see https in https://192.168.4.5:9980 which is bad.
But I just tried it only with (others are maybe redundant)
```
'overwritehost' => '****:1180',
```
And it seems to be the same. With this change only post begins with http://

**Comment by podhorsky-ksj** [comment]
Hmm, I can't change it to http, even with:
```
 'overwrite.cli.url' => 'http://192.168.4.2:1180',
  'overwriteprotocol' => 'http',
```
they are really redundant.
POST is always https

Do you have any idea?

**Comment by juliushaertl** [comment]
> I just saying it, because I see https in [192.168.4.5:9980](https://192.168.4.5:9980/) which is bad.

This is likely a problem of your collabora server configuration then. Please check if that needs to disable ssl settings then in coolwsd. 

I'll close this here as it looks like a setup issue and your setup seems rather complex in terms of different ports/authentication in use so there is no quick help I can provide here. Therefore I would like to ask you to raise your question in the forums: https://help.nextcloud.com
