### ISSUE TITLE
Disable Guest-Name picker for View-Only shares

### ISSUE THREAD

**Issue by kub3let** [nextcloud/richdocuments#4073]
**Describe the bug**
I'm sharing `read/view` only PDF files via Nextcloud, these are automatically rendered via Collabora when `Hide downloads` is checked.

On opening these Links you are asked to enter your `Guest name`, this is generally used for shared editing of documents.

Component: [src/components/GuestNamePicker.vue](https://github.com/nextcloud/richdocuments/blob/c2bfd8b33dec64dcb38a3f16656ace27db71e4a9/src/components/GuestNamePicker.vue#L22)
 
![image](https://github.com/user-attachments/assets/5f61c8c8-eff8-4df4-8ebd-86e4b0aff52a)

**To Reproduce**
Share a PDF in Nextcloud with Office (Collabora) enabled and customize the Link

Check:
-> View Only
-> Hide Downloads

![image](https://github.com/user-attachments/assets/046e3306-62e1-4dfc-8a21-bf71b35a58ee)

Open the link in a private browser tab, not logged into Nextcloud.

**Expected behavior**
Since the File is View only it should not ask for a Guest name and just use the default.

## Server details

Nextcloud 29.0.7
Collabora Office 24.04.7.2

**Comment by elzody** [comment]
Closing since #4048 has just been merged as of yesterday, and I will build a release soon which will include it all the way back to NC 28.
