### ISSUE TITLE
Can't open files from shared link

### ISSUE THREAD

**Issue by typorian** [nextcloud/richdocuments#408]
**Describe the bug**
Documents in a folder shared by link can not be edited. The app does not open, after entering a nickname there is only a perpetual spinner.

**To Reproduce**
1. Go to a folder shared by link with a password
2. Click on a file such as a text document
3. Enter nickname
4. Observe endless spinner

**Expected behavior**
The richdocuments app should open and allow document editing as it would with a user that is logged in

## Server details

**Operating system**: debian stretch

**Web server:** apache

**Nextcloud version:** 15.0.4

**Version of the richdocuments app** 3.2.1

**Version of Collabora Online** 

LOOLWSD
4.0.0 (git hash: b956fd1)
LOKit
Collabora Office 6.0-23 (git hash: 6410049)

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
The relevant part I think is this:

{"reqId":"4NH2Lfjju797MjB54AQk","level":0,"time":"2019-02-17T16:24:10+00:00","remoteAddr":"CLIENT-IP","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OC\\Command\\CommandJob job with ID 2695","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.4.0"}
{"reqId":"4NH2Lfjju797MjB54AQk","level":0,"time":"2019-02-17T16:24:10+00:00","remoteAddr":"CLIENT-IP","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OC\\Command\\CommandJob job with ID 2695 in 0 seconds","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.4.0"}
{"reqId":"sVzcylze2atRUYBbNsN1","level":0,"time":"2019-02-17T16:24:16+00:00","remoteAddr":"CLIENT-IP","user":"--","app":"richdocuments","method":"GET","url":"\/index.php\/apps\/richdocuments\/public?shareToken=3KLwlO0AO7UyZMR&fileName=Filename.ods&requesttoken=Icbg5JwYnhl%2F8gYUmsIVQ02%2Bb6hk5s4bls71Dhue3f8%3D%3AU5yy1%2FczpmMvwnZx7aVAEQDGXJour7Rd36yBYlf6uK0%3D&fileId=326783","message":"Could not find resource file \"\/apps\/richdocuments\/js\/templates.js\"","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.4.0"}
{"reqId":"hYJ4GDNtHlIMz97Kj2kw","level":0,"time":"2019-02-17T16:24:16+00:00","remoteAddr":"CLIENT-IP","user":"--","app":"no app in context","method":"GET","url":"\/index.php\/css\/icons\/icons-vars.css?v=1550420441","message":"No cache entry found for \/appdata_ocho1y5xe0y3\/css\/icons\/icons-vars.css.gzip (storage: local::\/var\/nextclouddata\/data\/, internalPath: appdata_ocho1y5xe0y3\/css\/icons\/icons-vars.css.gzip)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.4.0"}
{"reqId":"BO5zCajZarAhnJRAykPB","level":0,"time":"2019-02-17T16:24:17+00:00","remoteAddr":"CLIENT-IP","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OC\\Command\\CommandJob job with ID 2696","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.4.0"}
{"reqId":"BO5zCajZarAhnJRAykPB","level":0,"time":"2019-02-17T16:24:17+00:00","remoteAddr":"CLIENT-IP","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OC\\Command\\CommandJob job with ID 2696 in 0 seconds","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.4.0"}
{"reqId":"KuSOj7fARcqnunUm63RS","level":0,"time":"2019-02-17T16:24:18+00:00","remoteAddr":"172.17.0.2","user":"--","app":"richdocuments","method":"GET","url":"\/index.php\/apps\/richdocuments\/wopi\/files\/326783_ocho1y5xe0y3?access_token=luH4w0rx3HzpaNv3KHpNkXPWpzmiGCdB&access_token_ttl=0&permission=edit","message":"Loaded WOPI Token record: {\"id\":\"1882\",\"owner_uid\":\"Owner\",\"editor_uid\":null,\"fileid\":\"326783\",\"version\":\"0\",\"canwrite\":\"1\",\"server_host\":\"https:\/\/nextcloud.NEXTCLOUD.DOMAIN\/\",\"token\":\"luH4w0rx3HzpaNv3KHpNkXPWpzmiGCdB\",\"expiry\":\"1550422456\",\"guest_displayname\":\"Guest: aa\",\"template_destination\":\"0\"}.","userAgent":"LOOLWSD WOPI Agent 4.0.0","version":"15.0.4.0"}
{"reqId":"B2dT0dIP7ky3QFc1kWEr","level":0,"time":"2019-02-17T16:24:18+00:00","remoteAddr":"172.17.0.2","user":"--","app":"richdocuments","method":"GET","url":"\/index.php\/apps\/richdocuments\/wopi\/files\/326783_ocho1y5xe0y3\/contents?access_token=luH4w0rx3HzpaNv3KHpNkXPWpzmiGCdB&access_token_ttl=0&permission=edit","message":"Loaded WOPI Token record: {\"id\":\"1882\",\"owner_uid\":\"Adrian\",\"editor_uid\":null,\"fileid\":\"326783\",\"version\":\"0\",\"canwrite\":\"1\",\"server_host\":\"https:\/\/nextcloud.NEXTCLOUD.DOMAIN\/\",\"token\":\"luH4w0rx3HzpaNv3KHpNkXPWpzmiGCdB\",\"expiry\":\"1550422456\",\"guest_displayname\":\"Guest: aa\",\"template_destination\":\"0\"}.","userAgent":"LOOLWSD WOPI Agent 4.0.0","version":"15.0.4.0"}

</details>

**Comment by typorian** [comment]
I'm not sure if this is related to https://github.com/nextcloud/richdocuments/issues/397 or not.

**Comment by juliushaertl** [comment]
`Could not find resource file "/apps/richdocuments/js/templates.js"`

Looks a bit odd to me, since the file should not be loaded anymore with 3.2.1 Are you sure you are actually running 3.2.1 and can you try with a cleared browser cache?

**Comment by juliushaertl** [comment]
Also please check your browser console for errors.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by taavit21** [comment]
Can confirm that is an active issue.

![github](https://user-images.githubusercontent.com/47745930/52952637-d648a080-338d-11e9-9684-4e26597b8d05.PNG)

**Comment by typorian** [comment]
I chekced again and I can confirm I'm using version 3.2.1. This is what I see in the console in the browser: 

![image](https://user-images.githubusercontent.com/18899038/52953686-77ccf380-3388-11e9-807c-025c57e0f9a5.png)

**Comment by taavit21** [comment]
Hello,

Sorry i didn´t post console output.
Attaching new image.

![cloud2](https://user-images.githubusercontent.com/47745930/53007651-5deee780-3440-11e9-9065-bf58f7bd58db.PNG)

**Comment by githubkoma** [comment]
I unfortunately have the same problem, and it really creates problems for my users :-(

Can see the same errors in the Chrome Console..
BUT: Starting it in Firefox shows quite similar behavior, but also different error messages:

![parent oca files app error firefox](https://user-images.githubusercontent.com/5107805/53022484-8e904a80-345b-11e9-8c73-969c01c710ec.PNG)

**Comment by typorian** [comment]
It's the same for me in all browsers, I also tried the Samsung browser on 
Android, IceWeasel, Chrome, Firefox...

**Comment by githubkoma** [comment]
@juliushaertl in documents.js, when replacing every occurence of `parent.OCA.Files.App.fileList` with `parent.OCA.Files.FileList` it works for me, but that is most likely just a quick workaround to show that i could be related to the issue. ! Please dont try this yourself in your production environment !

**Comment by taavit21** [comment]
> @juliushaertl in documents.js, when replacing every occurence of `parent.OCA.Files.App.fileList` with `parent.OCA.Files.FileList` it works for me, but that is most likely just a quick workaround to show that it could be related to the issue.
> !!! to Everyone else: Please dont try this yourself in your production environment !!!

I can confirm that your workaround works.
