### ISSUE TITLE
Document generation API

### ISSUE THREAD

**Issue by julien-nc** [nextcloud/richdocuments#4095]
Hey!

Would it be possible to extend the template filling API to "dynamically" generate documents?
The use case we have in the integrations team is more or less generating a presentation from a prompt.
We thought that an LLM could generate a text based, easy to parse, description of a set of slides. We would then need to generate a document from this description.

One way to approach this could be to have an endpoint to fill multiple templates and assemble them into one document.

The input for this endpoint could be like:
``` json
{
    "type": "presentation",
    "parts": [
        {
            "templatePath": "/templates/title.odp",
            "values": { "1": "big title", "2": "subtitle" },
        },
        {
            "templatePath": "/templates/bulletpoints.odp",
            "values": { "1": "slide title", "2": "* bullet one\n*bullet 2" },
        },

    ],
}
```

Wdyt @juliushaertl @elzody ?
cc @marcelklehr

**Comment by aszucs3** [comment]
Just a few things i found while i was checkd it a bit:
-it will need some extra work to make extract/transform work on impress documents as well... right now its source code is in writer.. but surely it is planned that we should extend it to impress/ calc anyway ..
-to open multiple document, and generate 1 more document based on it... seems to be a challenge now.. but i have some ideas..

The easiest idea i have: 
we could use extract on multiple documents, and then use the extracted data to to a transform to make a new document.. 
pro: we would not need to code multiple document opening into the system .. 
con1: im not sure if we can extract enought information to make the same slide as it was before..
con2: maybe it would need to run separate extract commands, then run a transfer with the extracted data... BUT maybe we could automate it... maybe it could be coded into the same code. ... it could generate the right extratc / transfrom .. and then run it on the server, so maybe the user would not see anything from it? :)

the other way: 
we could code into the server side to open all the documents separetelly ... and somehow copy/paste slides between them...
pro: it sure could copy all needed data.. 
con: it needs a different separete code into server side i never tried to... so im not sure what challenges i will meet there... but if i start to do it, i can see it .. :)

Later when i will have time, i will check it a bit more deep.. and maybe i will be able to give better ideas.. :)

**Comment by juliusknorr** [comment]
>  -to open multiple document, and generate 1 more document based on it... seems to be a challenge now.. extract/transform, open only 1 document .. and may generate 1 new from it .. but i have some idea to handle it.

We can simplify this to work differently of course, I imagine we could just have one file that is worked on that has different master slides that can be used to add extra slides. From my limited understanding of the transform API i think the minimum we'd need would be:

- extract endpoint to list all master slides with whatever identifier they have
- extract endpoint to list possible fields of a master slide
- transform method to add a slide based on a master slide
- transform method to fill in fields (e.g. title or bullet list) of a newly added slide (maybe that can also be passed to the previous transform method directly)

Would that make things more easy?
