### ISSUE TITLE
Icons still show after opening doc from Favorites page

### ISSUE THREAD

**Issue by io-node** [nextcloud/richdocuments#41]
### Steps to reproduce
1. Mark an OpenOffice doc as favorite
2. Go to Favorite page
3. Open a document

### Expected behaviour
Everything visible from the Favorite page should disappear and doc editor shows

### Actual behaviour
Filename and Favorite icon (star) disappear but file-type icon remains on top of doc editor

I have found a solution but not sure if it is a proper solution. I edit the file '/apps/richdocuments/js/viewer/viewer.js' on line 105 I added in the style section 'z-index:5'.

I went from this line:

var $iframe = $('<iframe id="richdocumentsframe" style="width:100%;height:100%;display:block;position:absolute;top:0;" src="'+viewer+'" />');

to 

var $iframe = $('<iframe id="richdocumentsframe" style="width:100%;height:100%;display:block;position:absolute;top:0;z-index:5;" src="'+viewer+'" />');

This since I noticed that the file-type icons have a z-index of 4.

### Server configuration

**Operating system**: Ubuntu 16.04
**Web server:** Apache
**Database:** MySQL
**PHP version:** 7.0
**Nextcloud version:** 11,0.3RC2

**Updated from an older Nextcloud/ownCloud or fresh install:** Clean install

**Where did you install Nextcloud from:** Original file from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - announcementcenter: 3.0.0
  - audioplayer: 1.5.1
  - comments: 1.1.0
  - dav: 1.1.1
  - deck: 0.1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - onlyoffice: 1.0.2
  - passman: 2.1.1
  - password_policy: 1.1.0
  - previewgenerator: 1.0.5
  - provisioning_api: 1.1.0
  - richdocuments: 1.1.25
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreedme: 0.3.8
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_automatedtagging
  - files_retention
  - user_external
  - user_ldap
  - user_saml
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "occ3bgzu13dp",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.wijman.net"
        ],
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "datadirectory": "\/media\/nextcloud",
        "overwrite.cli.url": "https:\/\/cloud.wijman.net",
        "dbtype": "mysql",
        "version": "11.0.3.1",
        "dbname": "nextcloud",
        "dbhost": "192.168.7.244",
        "dbtableprefix": "nc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "trusted_proxies": [
            "192.168.7.241",
            "127.0.0.1"
        ],
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "overwritecondaddr": "^192\\.168\\.7\\.241$",
        "mail_from_address": "cloud",
        "mail_smtpmode": "smtp",
        "mail_domain": "wijman.net",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "maintenance": false,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": "2",
        "log_rotate_size": "104857600",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.mailarena.net",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "updater.server.url": "https:\/\/updates.nextcloud.org\/updater_server\/",
        "filesystem_check_changes": 1,
        "enable_previews": true,
        "preview_max_x": 640,
        "preview_max_y": 640,
        "preview_max_scale_factor": 4,
        "skeletondirectory": "\/media\/nextcloud\/skeleton",
        "appstore.experimental.enabled": true,
        "session_keepalive": true,
        "activity_expire_days": 365,
        "theme": "wijman",
        "mail_smtpsecure": "tls",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF"
        ],
        "asset-pipeline.enabled": true,
        "share_folder": "\/Shares"
    }
}

</details>

**Are you using external storage, if yes which one:** local + smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** local

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 10

**Comment by timar** [comment]
Thanks for the suggestion @io-node.
