### ISSUE TITLE
CODE does not cleanup coolwsd and appimage_extracted directories

### ISSUE THREAD

**Issue by JOpsDev** [nextcloud/richdocuments#4130]
**Describe the bug**
When using CODE the coolwsd process seems to exit after some time and the coolwsd and appimage_extracted directories are not removed.

**To Reproduce**
1. Setup Nextcloud with richdocuments and CODE from Snap
2. Open/create a rich document, coolwsd process gets created and keeps running
3. let the coolwsd process "time out"

**Expected behavior**
/tmp/snap-private-tmp/snap.nextcloud/tmp should not be filling up with left over coolwsd and appimage_extracted directories.

## Server details

**Operating system**:

Name Version Rev Tracking Publisher Notes
nextcloud 29.0.7snap1+git2.a85bd4b 44403 latest/candidate nextcloud✓ -

snap 2.63+20.04ubuntu0.1
snapd 2.63+20.04ubuntu0.1
series 16
ubuntu 20.04
kernel 5.4.0-196-generic

**Nextcloud version:**
nextcloud 29.0.7snap1

**Version of the richdocuments app**
Nextcloud Office Version 8.4.7

**Version of Collabora Online**
Collabora Online - Built-in CODE Server Version 24.4.802

**Configuration of the richdocuments app**
```
{
    "apps": {
        "richdocuments": {
            "canonical_webroot": "",
            "disable_certificate_verification": "yes",
            "enabled": "yes",
            "external_apps": "",
            "installed_version": "8.4.7",
            "public_wopi_url": "https:\/\/cloud.xxx\/extra-apps\/richdocumentscode\/proxy.php?req=",
            "types": "prevent_group_restriction",
            "wopi_allowlist": "127.0.0.1\/8,2a01:real:ipv6::1",
            "wopi_url": "https:\/\/cloud.xxx\/extra-apps\/richdocumentscode\/proxy.php?req="
        }
    }
}
```

/tmp/snap-private-tmp/snap.nextcloud/tmp/coolwsd.vE1VGjlRM9/coolwsd.log ends with:

```
kit-211114-211114 2024-10-15 22:06:28.445555 +0200 [ kit_spare_004 ] ERR  #33: Kit for DocBroker [] connection lost without exit arriving from wsd. Setting TerminationFlag| kit/KitWebSocket.cpp:193
kit-211113-211113 2024-10-15 22:06:28.445969 +0200 [ kit_spare_003 ] ERR  #33: Kit for DocBroker [] connection lost without exit arriving from wsd. Setting TerminationFlag| kit/KitWebSocket.cpp:193
kit-211112-211112 2024-10-15 22:06:28.446227 +0200 [ kit_spare_002 ] ERR  #33: Kit for DocBroker [] connection lost without exit arriving from wsd. Setting TerminationFlag| kit/KitWebSocket.cpp:193
kit-210739-210739 2024-10-15 22:06:28.446511 +0200 [ kit_spare_001 ] ERR  #33: Kit for DocBroker [] connection lost without exit arriving from wsd. Setting TerminationFlag| kit/KitWebSocket.cpp:193
wsd-210700-210700 2024-10-15 22:06:28.479281 +0200 [ coolwsd ] WRN  Jails root directory [/tmp/coolwsd.vE1VGjlRM9/jails/] is not empty. Will not remove it.| common/JailUtil.cpp:413
```

I have been sent here from https://github.com/nextcloud-snap/nextcloud-snap/issues/2921 .

When I _kill_ the coolwsd process e.g. with "killall coolwsd" the coolwsd and appimage_extracted directories _are removed_. If I just let it time out with the above log messages the tmp directories stay around forever.

**Comment by elzody** [comment]
This could potentially be a bug/issue with Collabora, will look into it a bit and give an update here.

**Comment by elzody** [comment]
I took a deeper look, and I am pretty sure this would specifically be related to the built-in CODE server, which has a repository at https://github.com/CollaboraOnline/richdocumentscode

Especially after reading your analysis in the [other thread](https://github.com/nextcloud-snap/nextcloud-snap/issues/2921#issuecomment-2415979344), it makes me think this is the case. The repository for the built-in CODE server is actually managed by Collabora. I'd definitely ask there

Sorry for the redirects @JOpsDev

**Comment by juliusknorr** [comment]
This seems to be rather an issue within the richdocumentscode app, so mabye you can file the issue at https://github.com/CollaboraOnline/richdocumentscode as we only track issues with the integration app itself here.
