### ISSUE TITLE
ClientException Client error

### ISSUE THREAD

**Issue by HenkVirtual** [nextcloud/richdocuments#4183]
I am getting numerous logging entries like;
```
 ClientException Client error: `POST https://xxxxxxxxxxxxx/apps/richdocumentscode/proxy.php?req=/cool/convert-to/png` resulted in a `403 Forbidden` response
Failed to convert preview: Client error: `POST https://xxxxxxxxxxxxxxxxxxx/apps/richdocumentscode/proxy.php?req=/cool/convert-to/png` resulted in a `403 Forbidden` response
``` sinds the upgrade from NC 29 to NC 30.

running;
NC 30.0.1
php 8.2
nginx 1.24

**Comment by joshtrichards** [comment]
I suggest you post on the help forum to get some troubleshooting assistance - https://help.nextcloud.com

**Comment by sbe-arg** [comment]
I'm having similar on one of the instances.

**Comment by jon02ch** [comment]
same Problem here, I don't think thats a Troubleshooting issue.
https://help.nextcloud.com/t/numerous-logging-entries-from-richdocumentscode-nc30-0-1/208735/3
