### ISSUE TITLE
On tablet + Chrome, the view is taller than the screen if URL bar + tabs are visible

### ISSUE THREAD

**Issue by thebearon** [nextcloud/richdocuments#419]
@juliushaertl, it seems there's a leftover case even after #396. In Chrome when you scroll down on a page, ie. in the file list, the URL bar + tab list become hidden, and if you scroll up a bit, they reappear. When they are hidden, the UI appears correctly, but when they are visible, the UI extends further below the screen.

I wonder if it'd be possible to always hide the URL bar and tab list when loading a file to maximize available screen size, and if so, whether it needs to be done on Nextcloud or on Collabora side.

Correct view:
![screenshot1_small](https://user-images.githubusercontent.com/19438782/53539213-f821f000-3b10-11e9-9236-6958422cd6cc.png)

View with overflow:
![screenshot2_small](https://user-images.githubusercontent.com/19438782/53539207-f1937880-3b10-11e9-8e2a-a8699b8e27ee.png)

**Comment by juliushaertl** [comment]
@thebearon The only way to actually force hiding the address bar would be to switch the browser to full screen mode when editing on mobile. I'll have a look if we can do this easily.

**Comment by juliushaertl** [comment]
Needs a bit more investivation, moving to the next release.

**Comment by thebearon** [comment]
A note here, the window heigh probably still has to be dynamically adapted to what is available, ie. even if fits in full screen mode, the user might exit full-screen mode, but remain in Collabora Online, I presume.

**Comment by thebearon** [comment]
The more immediate problem is what can be seen on the 2nd screenshot: there's no way to get into edit mode, because the document view doesn't fit. Could that be addressed in the meantime?
