### ISSUE TITLE
Images are beeing cropped when exporting as PDF

### ISSUE THREAD

**Issue by maesitopi** [nextcloud/richdocuments#42]
### Steps to reproduce
1. Open an existing or new ODT Document with images
2. Press on File > download as > PDF
3. PDF is being generated but Cut-off on the left and top corners

### Expected behaviour
The PDF File should be generated as the Document which is beiing edited in Collabora

### Actual behaviour
The PDF File is generated but ALL Images are cropped on the top and left corners. Exporting as Document and Word Documents works as expected. Side Note: **Exporting from an Calculations Sheet works as expected!**

![01 05](https://cloud.githubusercontent.com/assets/17855960/25577978/ad8d6452-2e6a-11e7-9254-119e97e48308.png)

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4.18

**Database:** mysql 5.7.8

**PHP version:** 7.0.15

**Nextcloud version:** (see Nextcloud admin page) 10.0.3

**Collabora Version on Nextcloud :** 1.1.18

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Side Notes:** With Owncloud 11 & the newest Collabora but the same docker Installation it didn't work either.

**Comment by timar** [comment]
Whatever bug is this, it is not related to richdocuments. I think it is a bug in LibreOffice core. Isn't it reproducible in desktop LibreOffice? Please report at http://bugs.documentfoundation.org/.

**Comment by maesitopi** [comment]
In LibreOffice 5.2.7 it works while exporting as PDF. No cutting edges there.
