### ISSUE TITLE
Revision Sidebar Does Not Work If File Was Opened Through "Favourites" or "Recent Files"

### ISSUE THREAD

**Issue by gohrner** [nextcloud/richdocuments#420]
**Describe the bug**
I'm using Richdocuments 3.2.1 with CODE 4.0. If I open a (ODS) document through the Nextcloud Files view, the revision history works fine.

If I open the document through the "Favourites" or "Recent Files" lists, the screen turns grey if I try to open the revision history, and I have to leave Richdocuments and reopen the document to get it going again.

**To Reproduce**
1. Open an ODS document in CODE from the "Recent Files" list in Nextcloud.
2. Click on "File -> Show Version History..." or the "last modified..." entry in the menu bar.

**Expected behavior**
The opened file stays visible.
The revision sidebar opens, showing past revisions of the document and allowing to switch between revisions.

**Actual behavior**
An empty sidebar opens and the rest of the display area turns grey.

**Screenshots**
See Screenshot:

![image](https://user-images.githubusercontent.com/26199042/53559429-5cad7100-3b4a-11e9-9c01-431d96e78a8a.png)

**Client details:**
 - OS: KDE Neon 5.15.3 (Ubuntu 18.04)
 - Browser: Chromium
 - Version: 71.0.3578.98
 - Device: i64 Notebook

## Server details

**Operating system**: Debian 9.6 Stretch

**Web server:** Apache/2.4.25 (Debian) (apache2handler)

**Database:** mysql 10.1.37

**PHP version:** 7.0.33-0+deb9u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, recode, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 14.0.7

**Version of the richdocuments app**: 3.2.1

**Version of Collabora Online**: 4.0 (final)

**Comment by juliushaertl** [comment]
Can you check the browser console for error messages?

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by gohrner** [comment]
`documents.js?v=8dafdf83-10:445 Uncaught TypeError: Cannot read property 'get' of null
    at Object.addCurrentVersion (documents.js?v=8dafdf83-10:445)
    at Object.showViewer (documents.js?v=8dafdf83-10:367)
    at Object.showRevHistory (documents.js?v=8dafdf83-10:424)
    at documents.js?v=8dafdf83-10:678`

**Comment by juliushaertl** [comment]
Hm actually it seems that the way we currently fetch the file model doesn't work for other views than the main file list. I can reproduce now with a favorited files that are not in the root folder.

**Comment by juliushaertl** [comment]
Fixed with #553
