### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by ozgurkazancci** [nextcloud/richdocuments#4221]
Hi,

"richdocuments" application produces the following error log lines;

```
 
ClientException Client error: `POST https://collaserver.mysite.com/cool/convert-to/png` resulted in a `413 Request Entity Too Large` response: <html> <head><title>413 Request Entity Too Large</title></head> <body> <center><h1>413 Request Entity Too Large</h1>(truncated...)
Failed to convert preview: Client error: `POST https://collaserver.mysite.com/cool/convert-to/png` resulted in a `413 Request Entity Too Large` response: <html> <head><title>413 Request Entity Too Large</title></head> <body> <center><h1>413 Request Entity Too Large</h1>< (truncated...)

```

Nextcloud version: 30.0.2 with all apps up-to-date.

Any clue would be much appreciated!

P.S: On my nextcloud server, I already have **client_max_body_size** big enough (7G) defined in nginx.conf, however my CODE/Office server has all default nginx settings.

Best.

**Comment by joshtrichards** [comment]
> however my CODE/Office server has all default nginx settings.

The 413 is coming from your CODE server (well, or the reverse proxy in front of it). This error isn't coming from Nextcloud / Nextcloud Office (`richdocuments`). Check the logs there and, if needed, troubleshoot via https://forum.collaboraonline.com/ and/or https://help.nextcloud.com
