### ISSUE TITLE
"Undefined array key "type"

### ISSUE THREAD

**Issue by ozgurkazancci** [nextcloud/richdocuments#4228]
Hello,

I'm constantly having the following warning message in NC log files;

"Undefined array key "type" at /var/www/nextcloud/apps/richdocuments/lib/Service/TemplateFieldService.php#96"

PHP Version: 8.2.25
Nextcloud version: 30.0.2 - all apps up-to-date

FYI,
Regards.

Özgür Konstantin

**Comment by elzody** [comment]
Hi, could you please share with us any more information? Such as what you do to trigger the error, or what kinds of errors you get in the browser / network request.

**Comment by juliusknorr** [comment]
Please also share the raw json trace of the log line as that will give more hints on how this occurred. :)

**Comment by ozgurkazancci** [comment]
@juliusknorr 

Here it is; https://paste.mozilla.org/85mRLMsV

Best wishes.

**Comment by juliusknorr** [comment]
While stepping through the code for another issue i noticed that this seems caused by the document properties that are now also extracted:

![Image](https://github.com/user-attachments/assets/337688b5-bad4-40bf-bdfe-67b6064c34e3)
