### ISSUE TITLE
Collabora error on Nextcloud 15.0.5: TypeError -> Argument 2 passed to GuzzleHttp

### ISSUE THREAD

**Issue by PpaiSanchez** [nextcloud/richdocuments#427]
TypeError: Argument 2 passed to GuzzleHttp\Psr7\MultipartStream::addElement() must be of the type array, string given, called in /var/www/html/3rdparty/guzzlehttp/psr7/src/MultipartStream.php on line 70

See forum:
https://help.nextcloud.com/t/collabora-error-on-nextcloud-15-0-5/48668/

**Comment by monreal** [comment]
Seeing this aswell... I think it started with version 3.2.2 of the collabora online app (richdokuments), at least this is the first I have noticed it with.
