### ISSUE TITLE
Nextcloud Office app will be uninstalled upgrading nextcloud 25 to 26

### ISSUE THREAD

**Issue by claudiocuce** [nextcloud/richdocuments#4279]
Hi, newbie here, sorry.
Ttrying to upgrade nextcloud (web tool) a warning message tells me that some apps will be uninstalled because they are not compatible with 26.0.13. One of this app is Nextcloud Office.

We are using Nextcloud Office so we can't let the system uninstall it.
I see that this app is well mantained and updated until last month.

How can I upgrade nextcloud progressively to 26-27-28 keeping Nextcloud Office installed and active?

Thanks

### Steps to reproduce
1. upgrade from 25.0.13 to 26.0.13
2.
3.

### Expected behaviour
Group folder app is compatible

### Actual behaviour
Web updating process warns me that Nextcloud Office app will be uninstalled for being not compatible

### Server configuration

**Operating system:CentOS Linux 7.9.2009**

**Web server:apache**

**Database:maria**

**PHP version:8.1.**

**Nextcloud version:25.0.13** (see Nextcloud admin page)

**Nextcloud Office version:7.1.10**

**Updated from an older Nextcloud/ownCloud or fresh install:updated**

**Where did you install Nextcloud from:Plesk**

**Comment by juliusknorr** [comment]
Thanks for reporting. I'm unsure on what exact message you are seeing but there is a compatible release of the Office app for every Nextcloud release: https://apps.nextcloud.com/apps/richdocuments

It might be a bug in the old version. Usually when upgrading Nextcloud the updates for apps will be fetched after upgrading Nextcloud, so as long as there is a release for the next major version you will be fine.

Closing as we have a release and if updating leaves you with an app being uninstalled that is rather a server bug. However please try upgrading to a supported version before reporting as bugs that happen in EOL releases like 25 might be fixed on newer versions already.
