### ISSUE TITLE
Text files open in Collabora Online instead of text editor

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/richdocuments#43]
If you simply want to edit a txt or plain text file, the simple text editor is much quicker and more lightweight than loading the full Collabora Online editor. Especially because there’s no formatting anyway.

We should keep using the https://github.com/nextcloud/files_texteditor for .txt and other plain text documents because it’s much quicker and works a bit better on mobile. This as of now provides the superior user experience.

Can we do that @timar @pranavk? :)

As talked about cc @karlitschek @jospoortvliet.

Ref https://github.com/nextcloud/richdocuments/commit/829b2b77b977102c4df0c1657b1bd7bc68c876ba
(Original issue by @guddl at https://github.com/nextcloud/server/issues/4658)

**Comment by timar** [comment]
Did you see https://github.com/nextcloud/richdocuments/issues/10 ?
It was filed by a customer. Maybe we should make this configurable.

**Comment by hoerup** [comment]
Yes i have the same problem. It would be very nice if it was possible if it was configurable whether Collabora plugin registers as editor for 'text/plain'

**Comment by elpraga** [comment]
Was there any reason @deneb-alpha to disable the official Text editor app (as mentioned in https://github.com/nextcloud/richdocuments/issues/10) in your case? 

Was there any reason why you wanted to open `.txt` files in the Collabora Online app, or was it because you couldn't open the `.rtf` files? I wasn't sure what the case was, as you mentioned both.

I agree with @jancborchardt that opening `.txt` files in the Collabora Online app doesn't have any benefits, and it can potentially cause additional problems (unnecessarily exhausting system resources, very hard to use on mobile devices, ...), especially in cases like the today's update to version `1.12.30`, after which the app stopped working completely, and left us without being to edit even simple text files.. (https://github.com/nextcloud/richdocuments/issues/77)

It should at least be set as an option!!

**Comment by elpraga** [comment]
@timar is there a manual way to disable the association? I would assume that the original ticket regarded the use of `.rtf` files, and although technically they are plain text files, nobody opens them in a text editor. 

I guess, the ideal solution would be to open `.rtf` files in Collabora Online app and `.txt` files in Text editor app, but in the meantime, is there a way to disable this new behavior manually? I do not use `.rtf` files, so not being able to open them in Collabora Online wouldn't hurt me, but I would benefit from being able to open the `.txt` files in the native Text editor app.

**Comment by timar** [comment]
@elpraga you can remove the line text/plain from js/viewer/viewer.js.

**Comment by elpraga** [comment]
Thank you for your reply @timar ! I did just what you said, and now, when I create a new text file using the + button, it opens in the Text editor app. Nevertheless, when I reopen the very same file, it opens in Collabora Online app.

Do you have any why this happens?

**Comment by m4lvin** [comment]
Thanks @timar. This worked for me:
1. remove the `text/plain` line from `js/viewer/viewer.js`
2. disable and enable the collabora app again (maybe try this, @elpraga?)
3. restart apache

Now my .txt files open in the simple texteditor again 😄

**Comment by patschi** [comment]
That was exactly that what I was searching for. I also dislike opening simple .txt-files with Collabora Online. Removing the line and reloading with CTRL+F5, without deactivating the app, did it.

**Comment by elpraga** [comment]
Thank you all for your help. Now it is working as expected. I cannot say what caused it to work, but it does now.

Thank you!

**Comment by menaceone** [comment]
Hey guys,
opening `.txt` files with the simple text editor would be a great enhancement. 
Any chances to get this in future releases without modifying `viewer.js` by hand?

kind regards

**Comment by jancborchardt** [comment]
@timar when the files_texteditor is disabled, it's fine to open txt files with Collabora Online. If the texteditor app is enabled though, it should be used for plain text files.

Ok?

**Comment by timar** [comment]
@jancborchardt Yes, I think it's a good compromise. Do you know how the query whether files_texteditor is disabled from viewer.js?

**Comment by jancborchardt** [comment]
No, but maybe someone from @nextcloud/javascript knows? @MorrisJobke @ChristophWurst anyone? :)

**Comment by patschi** [comment]
I did some research: What about checking if the variable `OCA.Files_Texteditor` does actually exist? If it exist, it means that the texteditor is enabled and loaded. ([files_texteditor/blob/master/js/editor.js#L11](https://github.com/nextcloud/files_texteditor/blob/master/js/editor.js#L11))
```javascript
if (typeof OCA.Files_Texteditor === 'undefined') {
	console.log('Loading text/plain files using Collabora Online.');
}
```

**Comment by blizzz** [comment]
we use underscore.js so you can just write ``_.isUndefined(OCA.Files_Texteditor)`` as undefined check

**Comment by timar** [comment]
@patschi Can you please update your PR #101 with this? Thank you very much @patschi and @blizzz.

**Comment by patschi** [comment]
@timar Yep, will do!

**Comment by patschi** [comment]
PR #101 updated with commit 4db76d6f015bd3efd0ef35a4ebba2372828dd76e.

**Comment by jancborchardt** [comment]
Thanks a lot @patschi! :) Since #101 is merged, this is fixed and we can close it, right? :)
