### ISSUE TITLE
Failed to connect to the remote server: Could not find urlsrc for application/vnd.openxmlformats-officedocument.wordprocessingml.document in WOPI discovery response

### ISSUE THREAD

**Issue by supremesyntax** [nextcloud/richdocuments#4312]
**Describe the bug**
After update to richdocumentscode 24.4.110 richdocuments (Nextcloud Office) 8.3.12 seems to cannot connect to collabora anymore (worked before) with the following message:

Failed to connect to the remote server: Could not find urlsrc for application/vnd.openxmlformats-officedocument.wordprocessingml.document in WOPI discovery response

![Image](https://github.com/user-attachments/assets/73b5a8b7-83f1-4e2e-8de2-b6a8289691d1)

I am always getting 5 log messages with 3 of them seem to be php errors
![Image](https://github.com/user-attachments/assets/c607521a-f45a-4030-a61a-6470032fed33)

But when i open _/apps/richdocumentscode/proxy.php?req=/hosting/discovery_ i can see it

![Image](https://github.com/user-attachments/assets/6b5a152d-1944-4132-b24b-6ea780932fa3)

## Server details

**Operating system**:
Ubuntu 20.04.6 LTS
**Web server:**

**Database:**

**PHP version:**
8.2.26
**Nextcloud version:**
28.0.12
**Version of the richdocuments app**
8.3.12
**Version of Collabora Online**
24.4.110
**Configuration of the richdocuments app**
```
{
    "apps": {
        "richdocuments": {
            "disable_certificate_verification": "",
            "doc_format": "ooxml",
            "enabled": "yes",
            "external_apps": "",
            "installed_version": "8.3.12",
            "types": "prevent_group_restriction",
            "wopi_allowlist": "xxx",
            "wopi_url": "https:\/\/xxx\/apps\/richdocumentscode\/proxy.php?req="
        }
    }
}

```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"xxx","level":3,"time":"xxx","remoteAddr":"xxx","user":"xxx","app":"richdocuments","method":"GET","url":"/apps/richdocuments/settings/check","message":"Could not find urlsrc for application/vnd.openxmlformats-officedocument.wordprocessingml.document in WOPI discovery response","userAgent":"xxx","version":"28.0.12.2","exception":{"Exception":"Exception","Message":"Could not find urlsrc for application/vnd.openxmlformats-officedocument.wordprocessingml.document in WOPI discovery response","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php","line":39,"function":"getUrlSrc","class":"OCA\\Richdocuments\\WOPI\\Parser","type":"->"},{"file":"/var/www/nextcloud/apps/richdocuments/lib/Service/ConnectivityService.php","line":47,"function":"getUrlSrcValue","class":"OCA\\Richdocuments\\WOPI\\Parser","type":"->"},{"file":"/var/www/nextcloud/apps/richdocuments/lib/Controller/SettingsController.php","line":70,"function":"testDiscovery","class":"OCA\\Richdocuments\\Service\\ConnectivityService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"checkSettings","class":"OCA\\Richdocuments\\Controller\\SettingsController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php","Line":65,"message":"Could not find urlsrc for application/vnd.openxmlformats-officedocument.wordprocessingml.document in WOPI discovery response","exception":[],"CustomMessage":"Could not find urlsrc for application/vnd.openxmlformats-officedocument.wordprocessingml.document in WOPI discovery response"},"id":"xxx"}

{"reqId":"xxx","level":3,"time":"xxx","remoteAddr":"xxx","user":"xxx","app":"richdocuments","method":"GET","url":"/apps/richdocuments/settings/check","message":"Didn't find urlsrc for mimetype application/vnd.openxmlformats-officedocument.wordprocessingml.document in this WOPI discovery response: <html><body>\n<h1>Socket proxy error</h1>\n<p>Error: Timed out opening local socket: 99 - Cannot assign requested address</p>\n</body></html>\n","userAgent":"xxx","version":"28.0.12.2","data":{"app":"richdocuments"},"id":"xxx"}

{"reqId":"xxx","level":3,"time":"xxx","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"/apps/richdocuments/settings/check","message":"Trying to access array offset on value of type null at /var/www/nextcloud/apps/richdocuments/lib/Service/DiscoveryService.php#152","userAgent":"xxx","version":"28.0.12.2","data":{"app":"PHP"},"id":"xxx"}

{"reqId":"xxx","level":3,"time":"xxx","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"/apps/richdocuments/settings/check","message":"Trying to access array offset on value of type null at /var/www/nextcloud/apps/richdocuments/lib/Service/DiscoveryService.php#151","userAgent":"xxx","version":"28.0.12.2","data":{"app":"PHP"},"id":"xxx"}

{"reqId":"xxx","level":3,"time":"xxx","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"/apps/richdocuments/settings/check","message":"Trying to access array offset on value of type null at /var/www/nextcloud/apps/richdocuments/lib/Service/DiscoveryService.php#150","userAgent":"xxx","version":"28.0.12.2","data":{"app":"PHP"},"id":"xxx"}


```

</details>

**Comment by dwcline** [comment]
Any update on this issue?  I am experiencing the same problem, but at different versions - everything was working correctly until CODE upgrade to 24.4.1002

Server details
OS:  Debian 6.1.119-1
PHP: 8.2.26
Nextcloud version: 30.0.3
richdocuments: 8.5.3
richdocumentscode: 24.4.1002

**Comment by EasedVR** [comment]
I have the same problem after updating the CODE server to 24.4.1002. When downgrading it to 24.4.902, everything is working again.

OS: Debian 12
PHP: 8.3.14
Nextcloud: 30.0.2
richdocuments: 8.5.3
richdocumentscode: 24.4.1002

**Comment by elzody** [comment]
You all seem to be using the richdocumentscode app, which is maintained over at the Collabora repository: https://github.com/CollaboraOnline/richdocumentscode/issues. I would suggest filing the issue there instead

**Comment by Sem060923** [comment]
> Any update on this issue? I am experiencing the same problem, but at different versions - everything was working correctly until CODE upgrade to 24.4.1002
> 
> Server details OS: Debian 6.1.119-1 PHP: 8.2.26 Nextcloud version: 30.0.3 richdocuments: 8.5.3 richdocumentscode: 24.4.1002

I have the same problem. How did you downgrade the version? You can learn more..

**Comment by Sem060923** [comment]
I figured it out, everything worked out. Here is a step-by-step instruction that may help someone:

1.On the net cloud Active applications page, disable the Collabora Online - Built-in CODE Server application
2.On the Disable nexcloud applications page, delete the Collabora Online - Built-in CODE Server applications
3.Download the archive file with the previous version to the /var/www/html/nextcloud/apps directory
  https://github.com/CollaboraOnline/richdocumentscode/releases/download/24.4.902/richdocumentscode.tar.gz
4.Unpack the archive with the command: tar zxvf richdocumentscode.tar.gz
5.Set the user to the folder with the command: chown -R www-data:nogroup richdocuments
6.Go back to the cloud apps page and turn on the <Collabora Online> app
