### ISSUE TITLE
Posibility to add other Spell Checking languages

### ISSUE THREAD

**Issue by vovagorodok** [nextcloud/richdocuments#4330]
**Is your feature request related to a problem? Please describe.**
In my case adding Polish Spell Checking language is needed

**Describe the solution you'd like**
Add possibility in `Collabora Online - Built-in CODE Server` or `Nextcloud Office` app configuration

**Describe alternatives you've considered**
N/A

**Additional context**
![Image](https://github.com/user-attachments/assets/cbfe64db-8767-4748-8ed0-b0fdbeb2d611)

**Comment by juliusknorr** [comment]
For the build in code server please file issues at https://github.com/CollaboraOnline/richdocumentscode

You might want to consider other installation methods instead which would give you better performance and more flexibility regarding configuration and customization.
