### ISSUE TITLE
cannot open template files like .ott - the file will be downloaded instead

### ISSUE THREAD

**Issue by joergmschulz** [nextcloud/richdocuments#4337]
**Describe the bug**
Selecting an ott template document results in a download of this document.
**To Reproduce**
1. Click on 'the document file blah blah dot OTT'

**Expected behavior**
The OTT should be opened with office. A new document should be created from this template.

**Nextcloud version:**
30.0.[3|4]

**Version of the richdocuments app**
Nextcloud Office 8.5.3

**Version of Collabora Online**
24.0.4.8.2

**Configuration of the richdocuments app**
```
Insert the output of `./occ config:list richdocuments` (or equivalent adapted for your runtime environment)
{
    "apps": {
        "richdocuments": {
            "enabled": "yes",
            "types": "prevent_group_restriction",
            "doc_format": "odf",
            "external_apps": "",
            "test_server_groups": "",
            "test_wopi_url": "",
            "wopi_allowlist": "172.0.0.0\/8,10.0.0.0\/8,.....",
            "disable_certificate_verification": "",
            "public_wopi_url": "https:\/\/office5.xxx.de",
            "installed_version": "8.5.3",
            "wopi_url": "https:\/\/office5.xxx.de",
            "open_local_editor": "no"
        }
    }
}
nc:/www/
```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
(nothing relevant)
```

#### Browser log
```
(nothing relevant found)
```

</details>

**Comment by elzody** [comment]
I think it's mostly expected that these are properly used as templates, for example in the user templates folder. Then, when you create a new document from the "New file" button, you can select from these template files there. Directly opening them would only be useful for editing the template, no? Maybe @juliusknorr could provide more insight. Either way, I think opening them for editing the template should be allowed?

**Comment by juliusknorr** [comment]
Yes, this is actually already tracked as https://github.com/nextcloud/richdocuments/issues/2315 so let's close this as a duplicate.
