### ISSUE TITLE
after update to 3.2.2 editing in mobile app stopped working

### ISSUE THREAD

**Issue by small1** [nextcloud/richdocuments#434]
**Describe the bug**
Since update tp 3.2.2 from 3.2.1 mobile editing stopped working. Just get a spinner and nothing happens. In collabora it shows as if i have the document open. But it doesnt show on the cellphone.

**To Reproduce**
1. Open the mobile app. 
2. Choose a document and open in collabora
3. File never opens. But does when you open from the webui

**Expected behavior**
Open collabora and edit the document

**Client details:**
 - OS: Android 9 
 - Version 3.5.0 of the nextcloud app
 - Device: google pixel xl 

## Server details

**Operating system**:
Debian 9

**Web server:**
nginx 

**Database:**
mariadb

**PHP version:**
fpm 7.2

**Nextcloud version:**
15.0.5

**Version of the richdocuments app**
3.2.2

**Version of Collabora Online**
4.0.1

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
Cant find anything related to this in the nextcloud log

</details>

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/richdocuments/pull/426
