### ISSUE TITLE
iOS Copy&Paste needs keyboard ?

### ISSUE THREAD

**Issue by kdoteu** [nextcloud/richdocuments#4352]
Yesterday I updated my Nexclout Office Version, Coolwsd and my iOS App. Since then i can't copy and paste in the office documents. It always says something like "For pasting use your keyboard". But I've no keyboard attached or voice enabled.

**To Reproduce**
1. Open any document
2. Go to edit-mode
3. Copy Something
4. Popup shows up with the notice to use the keyboard

**Expected behavior**
As the behavior before I can copy and paste using the context menu on iOS

**Client details:**
 - OS: iOS
 - Browser Nextcloud App
 - Version 
 - Device: iPad

## Server details

**Operating system**: Ubuntu

**Web server:** Nginx

**Database:** PostgreSQL

**PHP version:** 7.X (i know :)

**Nextcloud version:** 25

**Version of the richdocuments app**: 7.1.10

<details>
**Version of Collabora Online** 

**Configuration of the richdocuments app**
```
Insert the output of `./occ config:list richdocuments` (or equivalent adapted for your runtime environment)
```

<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by elzody** [comment]
You're using pretty old versions of Nextcloud and the richdocuments app... is there any way you can upgrade? We do not support these anymore.

**Comment by kdoteu** [comment]
I can only upgrade durign the year change - but I thought eventually anybody else discovers this problem

**Comment by joshtrichards** [comment]
Fairly certain this would be a CO/CODE matter - https://github.com/CollaboraOnline/online

**Comment by juliusknorr** [comment]
Yes, there is nothing we can do about the copy paste behaviour on our side.

@kdoteu For issues with Collabora Online itself, please open a bug report at: https://github.com/collaboraonline/online

**Comment by kdoteu** [comment]
Opend a new issu on collabora online - https://github.com/CollaboraOnline/online/issues/10820
