### ISSUE TITLE
Document opens in the right side of the view, showing the left sidebar

### ISSUE THREAD

**Issue by oparoz** [nextcloud/richdocuments#44]
### Steps to reproduce

1. Install Nextcloud 12 beta 1
1. Open a Writer document

### Expected behaviour

Collabora should take the whole width and include scrollbars to be able to navigate through the document

### Actual behaviour

Collabora open on the right-hand side, leaving the left sidebar visible
Scrollbars have disappeared. Users are force to navigate through the document using the keypad.

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** 12b1

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** master

**Comment by michag86** [comment]
If you remove https://github.com/nextcloud/server/blob/v12.0.0beta2/core/css/apps.scss#L94 it's working, but display:flex is required (https://github.com/nextcloud/server/pull/3260).
I don't know why display:none from .hidden is not applied.

**Comment by michag86** [comment]
Adding this:
<pre>
        &.hidden {
                display: none;
        }
</pre>
After this line https://github.com/nextcloud/server/blob/v12.0.0beta2/core/css/apps.scss#L119 helps, but I don't know if this is the best solution.

**Comment by MorrisJobke** [comment]
Let me fix this.

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/nextcloud/server/pull/4975 - thanks @michag86 🚀
