### ISSUE TITLE
Activities in Sidebar Shown Twice / as Duplicates

### ISSUE THREAD

**Issue by gohrner** [nextcloud/richdocuments#442]
**Describe the bug**
I just upgraded to Richdocument 3.2.3 and wanted to check if the sidebar / version history problems with "Favourites" are fixed now - but apparently, there's still something very fishy...

**To Reproduce**
1. Add an office file in some sub-folder as a Nextcloud "Favourite"
2. Open the file from the Favourites list and see what happens
3. Show the file's history in the sidebar from within the files app

**Expected behavior**
Each file revision should be shown once, and only existing file revisions should be shown. Both revision lists should match more or less.

**Screenshots**
Two screenshots: The revision from within CODE and the revision from the files app.
As you can see, both show wrong information. The files history view shows all changes twice while the CODE history view shows an 11 days old "ghost" revision which does not actually exist:

![image](https://user-images.githubusercontent.com/26199042/54091965-d7665f80-4386-11e9-87e0-2ccd7a8644df.png)

![image](https://user-images.githubusercontent.com/26199042/54091938-7dfe3080-4386-11e9-8fc2-6c03c6f3cd35.png)

## Server details
**Nextcloud version:**  15.0.5
**Version of the richdocuments app**: 3.2.3
**Version of Collabora Online**: 4.0

**Comment by juliushaertl** [comment]
Not really related to the Colllabora app, i think there was some related fix in the server. Please check this again on the latest supported versions.

**Comment by gohrner** [comment]
Seems to be fixed, and yes, seems to have been more some kind of server sidebar issue.
