### ISSUE TITLE
Limit access to libre office files

### ISSUE THREAD

**Issue by hriekehof** [nextcloud/richdocuments#443]
**Is your feature request related to a problem? Please describe.**
We have the problem at the moment, that collabora code sometimes corrupt  MS excel files when you open und save them. We work with the newest Office 365 with some of our sheets. Some functions like table coloring is not supported by .ods 

**Describe the solution you'd like**
It would be nice for us if we could limit the access to collabora online to libre office file types like .ods .odt etc. I wasn't able to finde anything about this maybe its already possible. 
We would then use .ods and .odt files for every document which shall be edited and shared in collabora. files wich .xlsx extentions wouldn't open in collabora and therefore the corruption is avoided

**Comment by juliushaertl** [comment]
@thebearon Is the table coloring breaking documents a known isssue? Is that something that could be fixed easily?

**Comment by hriekehof** [comment]
I have no idea which other parts of those file formats are maybe incompatible. To be really safe i would really like to separate these two file types if necessary. It could be a simple option you can set in the app

**Comment by hriekehof** [comment]
I had another idea this morning. An alternative would be that .xlsx and .docx files are always read only in collabora if this is easier to achieve. Viewing is fine i think. Problems only occurs when you save a .xlsx file in collabora. During the conversion from .ods back to .xlsx there is a potential corruption.

**Comment by thebearon** [comment]
> @thebearon Is the table coloring breaking documents a known isssue? Is that something that could be fixed easily?

Hard to say blindly, it would be the best to see a sample.
