### ISSUE TITLE
Embed document through API

### ISSUE THREAD

**Issue by GlauberF** [nextcloud/richdocuments#444]
Hello, maybe this is not the place to ask the question, but I have doubts.

 1 - Can I create a new text document through the API?

2 - Can I embed via API, where can I call the file I want to display and from there, can they edit and preview the document?

**Comment by juliushaertl** [comment]
Hi,

we have some documentation about how we integrate collabora in our mobile apps in https://github.com/nextcloud/richdocuments/tree/master/docs Those should help you as well.
