### ISSUE TITLE
increase timeout for capabilities refresh

### ISSUE THREAD

**Issue by michag86** [nextcloud/richdocuments#445]
Change this:
https://github.com/nextcloud/richdocuments/blob/v3.2.3/lib/Service/CapabilitiesService.php#L70
from 5 to 10 for example.

5 seconds is the default timeout for dns. 
If dns response failes on first request, request takes more than 5 seconds. As result, capabilities are empty.

@MorrisJobke

**Comment by MorrisJobke** [comment]
cc @rullzer @juliushaertl

**Comment by MorrisJobke** [comment]
There you go: #446

**Comment by michag86** [comment]
@rullzer @MorrisJobke @juliushaertl 
maybe, raising the timeout is not the complete solution. if the refresh fails, it is updating the capabilities.json to "[]". At this time all capability depending functions are not working (mobile usage, templates). It would be useful, if there would be a retry, before a working configuration gets destroyed by capabilities discovery.

**Comment by MorrisJobke** [comment]
> maybe, raising the timeout is not the complete solution. if the refresh fails, it is updating the capabilities.json to "[]". At this time all capability depending functions are not working (mobile usage, templates). It would be useful, if there would be a retry, before a working configuration gets destroyed by capabilities discovery.

Could you open a new ticket for that.

**Comment by juliushaertl** [comment]
Ticket at https://github.com/nextcloud/richdocuments/issues/448
