### ISSUE TITLE
Restrict collabora if download is disabled for share links

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#447]
When download is disabled for share links we should set:
- DisableExport
- DisableCopy
- DisablePrint

**Comment by kendy** [comment]
In addition to the above, you want also:

* HideExportOption - that actually hides the Download As from menu (and also disables the Impres'es presentation mode - which is actually a download of a .svg version of the document).

* HidePrintOption - that hides the print option from the filemenu bar in the UI
