### ISSUE TITLE
1.1.26-nc11 is set as unstable in NC Appstore for over a week

### ISSUE THREAD

**Issue by devz3r0** [nextcloud/richdocuments#45]
### Steps to reproduce
look to: https://apps.nextcloud.com/apps/richdocuments

### Expected behaviour
set as stable, so versioning is working again and Clients/Server can recieve the update via the repo,
or asking in the forums, for testers who can test it on their installations to get it to the stable branch.

### Actual behaviour
Set as unstable, no one is getting the update and in the forums people asking why versioning isn't working.
Probably clients lost data, because they counted that versioning works, but don't.

**Comment by timar** [comment]
I released 1.11.27.
