### ISSUE TITLE
Collabora Template - Undefined index: preview at ... / Error PHP Undefined index: delete at ...

### ISSUE THREAD

**Issue by PpaiSanchez** [nextcloud/richdocuments#463]
Mehrere Nutzer berichten von folgenden Fehler. Bei mir ist dieser jetzt auch vorhganden:

"I just did a fresh install of nextcloud and collabora. When i try to create a doc I get a pop up that ask me to select a template. I get an error after that. I can open docs I upload but can’t create new ones. On the setting page for Collabora online I have 3 templates listed under global templates names empty. I can not delete them as I get an error. I can’t find a similar issue online."

See:
https://help.nextcloud.com/t/collabora-template/46027

Question: Can I completely disable this function of the templates? This totally annoys.
Thank you.

**Comment by juliushaertl** [comment]
We probably should not use the template picker if there would be the empty templates only anyway.

**Comment by juliushaertl** [comment]
Already implemented. If only one template is available we will directly use it.
