### ISSUE TITLE
mariadb slow query with NextCloud 15.0.5

### ISSUE THREAD

**Issue by vincent-lucy** [nextcloud/richdocuments#464]
**Describe the bug**
this logs appear very often since we upgraded the server from NC 14.0.8 to 15.0.5
We have the extension 3.2.4

## Server details

**Operating system**: 
Debian Stretch
**Web server:** 
Apache 2.4.25-3+deb9u6
**Database:**
mariadb-server
Version: 10.1.37-0+deb9u1
**PHP version:**
php-fpm
Version: 2:7.3+69+0~20190303094804.15+stretch~1.gbp0f7465
**Nextcloud version:**
version: 15.0.5.3
**Version of the richdocuments app**
richdocuments: 3.2.4
**Version of Collabora Online**
LOOLWSD
4.0.1 (git hash: e1b0096)
LOKit
Collabora Office 6.0-25 (git hash: 518234a)

<details>
<summary>Logs</summary>

#### MariaDB log (/var/log/mysql/mariadb-slow.log)
```
SET timestamp=1553523596;
SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'oc_richdocuments_member' */ WHERE k.table_name = 'oc_richdocuments_member' AND k.table_schema = 'oncloud' /*!50116 AND c.constraint_schema = 'oncloud' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL;
# Time: 190325 15:20:02
# User@Host: oc_admin[oc_admin] @ localhost []
# Thread_id: 630250  Schema: oncloud  QC_hit: No
# Query_time: 0.000120  Lock_time: 0.000041  Rows_sent: 3  Rows_examined: 3
# Rows_affected: 0
# Full_scan: Yes  Full_join: No  Tmp_table: Yes  Tmp_table_on_disk: No
# Filesort: No  Filesort_on_disk: No  Merge_passes: 0  Priority_queue: No
SET timestamp=1553523602;
SELECT TABLE_NAME AS `Table`, NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, SEQ_IN_INDEX AS Seq_in_index, COLUMN_NAME AS Column_Name, COLLATION AS Collation, CARDINALITY AS Cardinality, SUB_PART AS Sub_Part, PACKED AS Packed, NULLABLE AS `Null`, INDEX_TYPE AS Index_Type, COMMENT AS Comment FROM information_schema.STATISTICS WHERE TABLE_NAME = 'oc_file_locks' AND TABLE_SCHEMA = 'oncloud';
```

</details>

**Comment by juliushaertl** [comment]
As far as I can tell those queries are related to doctrine database migration, so they should actually only be run if the app is updated. From the richdocuments code there is no use of the oc_richdocuments_member table anymore. (This seems to be a leftover from old times) Can you check if the slow queries are actually happening during regular run time or just during updates?

**Comment by vincent-lucy** [comment]
Thanks for your response, I was out of the office last days.
You're right, those queries do not appear anymore.
false alert so (I track the slow query of our instance, huge latences were the result of the XMPP js chat app, I just removed it). It seems some (lots of) apps do not "clean" the database when they are uninstalled, it's a pity NextCloud has not a tool for cleaning it.
