### ISSUE TITLE
Don't request settings.php if user is not logged in

### ISSUE THREAD

**Issue by kesselb** [nextcloud/richdocuments#466]
**Describe the bug**

Don't request settings.php if user is not logged in

**To Reproduce**
1. richdocuments is enabled
2. Create a file drop share
3. Open share as anonymous user (e.g. other browser or incognito mode)
4. There is a xhr request to settings.php which fails with "Current user is not logged in"

**Expected behavior**

No request to settings.php if user is not logged in

**Screenshots**

![Peek 2019-03-27 17-43](https://user-images.githubusercontent.com/3902676/55095124-e9027380-50b7-11e9-8caf-63e3c2fb3862.gif)

## Server details

**Nextcloud version:** master

**Version of the richdocuments app** master

**Comment by juliushaertl** [comment]
No longer the case :wink:
