### ISSUE TITLE
Become a guest user via shared URL

### ISSUE THREAD

**Issue by Bables55** [nextcloud/richdocuments#467]
**Describe the bug**
Whenever Nextcloud users open a file via a shared URL, they will be accessed as "guest user".
And, the "Add to Your Nextcloud" menu does not work at all. This happens even if I disable the Collabora Online application, so it may be a problem with NC itself.

**To Reproduce**
1. Select a file from the file list and generate a shared URL(share link).
2. Existing Nextcloud users open share link.

**Expected behavior**
The document file is opened inheriting the login status of the Nextcloud user.

**Screenshots**
![nc-user-guest](https://user-images.githubusercontent.com/30524004/55370465-81c04580-5535-11e9-940c-24479e2990c2.png)
*The file has editable permissions.

**Client details:**
 - OS: [e.g. iOS] Windows10, macOS 10.14, iOS 12, Android7
 - Browser [e.g. chrome, safari] Firefox, Vivaldi, Safari, Chrome
 - Version [e.g. 22] Latest
 - Device: [e.g. iPhone6, desktop] Desktop and Mobile

## Server details

**Operating system**:
CentOS 7.6
**Web server:**
Nginx 1.14.2
**Database:**
MariaDB 10.2.23
**PHP version:**
7.3.3
**Nextcloud version:**
15.0.5
**Version of the richdocuments app**
LOOLWSD 4.0.3LOKit
Collabora Office 6.0-27
**Version of Collabora Online**
3.2.4

**Comment by juliushaertl** [comment]
This is more a server issue, since right now we don't use the information if a user is already logged in on public share links, so I'm closing this in favor of https://github.com/nextcloud/server/issues/721 and https://github.com/nextcloud/server/issues/6462

**Comment by Bables55** [comment]
Is this caused by the setting? Is it a bug by Nextcloud? Which? Or is this originally the normal behavior?
What is the meaning of "Add to Nextcloud" in the menu?
The topic has not been active in recent years. Is this a rare phenomenon?

**Comment by juliushaertl** [comment]
The add to nextcloud is just for federated sharing as of now. So you can add the file to your remote Nextcloud instance. The share link always being visited as a guest user is normal behavior, but we recently discussed, that this is something we need to look into.
