### ISSUE TITLE
Mobile Autocompletion does not work properly

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/richdocuments#468]
**Describe the bug**
I tested with google keyboard and swiftkey.

Type eg Schnee and try to complete to Schneemann and you get SchneeSchneemann
Or: Schnee->Schneewittchen but you will get sSchneewittchen

It concerns text and calc documents. In the calc function line it's working.

**Comment by juliushaertl** [comment]
I think this is a collabora issue, so please open a bug report for LibreOffice Online: bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online
