### ISSUE TITLE
iOS: document view can be scrolled down to reveal file list

### ISSUE THREAD

**Issue by thebearon** [nextcloud/richdocuments#476]
- Open a document (not sure if it has to be from the main directory, or many files have to exist in the directory).
- Press the "v" shaped, I assume scroll down key.

=> The view actually scrolls down to reveal the file list.
Happens with Chrome, Firefox and Safari.
In some browsers the original view is slightly larger than the screen both horizontally and vertically: and the status bar and edit mode button are partially off-screen, and the document doesn't fit completely inside the screen, either.

Screenshot:
![container](https://user-images.githubusercontent.com/19438782/56168316-179aac80-5fdb-11e9-8a24-47e032cf864d.jpg)

**Comment by juliushaertl** [comment]
@thebearon Unfortunately I cannot reproduce the issue with browserstack, which should be a real iOS device running in the background.

**Comment by thebearon** [comment]
@juliushaertl Strange... can you please also check if, when the on-screen keyboard pops during editing, is the size of the document view adjusted so the status bar moves up to stay above the on-screen keyboard?

**Comment by thebearon** [comment]
> In some browsers the original view is slightly larger than the screen both horizontally and vertically: and the 

A correction here, the horizontal view is larger than screen width on purpose, it is not intended to zoom out all the way to fit on small screens, as it'd make the content harder to read.
The view not fitting on the screen vertically is a problem, though.

**Comment by IvanSanchez** [comment]
A quick & dirty fix is to add a `position: fixed` CSS rule to `#richdocumentsframe` at https://github.com/nextcloud/richdocuments/blob/330e75e6c653a1e4782df09ec1fbeb3a9e95f863/css/mobile.css#L14-L16
