### ISSUE TITLE
nextcloud hide download does not disable download option in collabora

### ISSUE THREAD

**Issue by tuxcrafter** [nextcloud/richdocuments#481]
When sharing a link and checking the hide download option it will hide the download option in nextcloud, but allows the user to download the file with the download as menu option in collabora.

Can we integrate this functionality to follow the hide download option in nextcloud?

nextcloud hide download does not disable download option in collabora

 sudo -u apache ./occ config:system:get version
15.0.4.0

LOOLWSD
4.0.3 (git hash: 81ea009)
LOKit
Collabora Office 6.0-27 (git hash: 8e005a5)

**Comment by juliushaertl** [comment]
We have already merged this for the next release with #475
