### ISSUE TITLE
File->Versions always shows a version from 1551294326000 

### ISSUE THREAD

**Issue by rainerjung** [nextcloud/richdocuments#486]
When looking at the version history from within the File menu, there is always a (non-existing) version shown with timestamp 1551294326000 .

This hard coded time stamp can be found in the commit

https://github.com/nextcloud/richdocuments/commit/24d59d73726dc552cea40e7b32ce22d19c4787f6

This looks like unfinished code? The timestamp should probably be dynamically determined.

**Comment by juliushaertl** [comment]
Yes, the timestamp should actually be the last saved versions timestamp. Thanks for reporting.

**Comment by juliushaertl** [comment]
Got fixed already.
