### ISSUE TITLE
Error after update to 3.3.1 PHP Undefined variable hideDownload TokenManager.php

### ISSUE THREAD

**Issue by ralcazar-oeg** [nextcloud/richdocuments#492]
**Describe the bug**
Collabora works fine, but every time I open a document this error is logged:

[PHP] Error: Undefined variable: hideDownload at /var/www/testnc/apps/richdocuments/lib/TokenManager.php#160

GET /testnc/index.php/apps/richdocuments/index?fileId=321&requesttoken=tokenchain
from MY_IP by ralcazar at 2019-05-08T14:16:37+00:00

Other 2 instances using older version of collabora app (older that 3.3.0) work fine and no error is logged. All instances access to a unique collabora instance.
Error seems to follow to version 3.3.1

**Client details:**
tested using windows 10 and android with firefox and chrome

## Server details

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** Mysql

**PHP version:** 7.0.33

**Nextcloud version:** 15.0.7

**Version of the richdocuments app** 3.3.1

**Version of Collabora Online**

**Comment by brtptrs** [comment]
We are also seeing the error and are experiencing problems on the Collabora server. 
The load is fluctuating and has just killed the server. 

Nextcloud version: 15.0.7
Version of the richdocuments app 3.3.1

**Comment by tobiasKaminsky** [comment]
@juliushaertl

**Comment by ChristophWurst** [comment]
Fix is at https://github.com/nextcloud/richdocuments/pull/491

**Comment by ralcazar-oeg** [comment]
Issue solved with 3.3.2 release
