### ISSUE TITLE
Frequent "EPIPE: Broken pipe" errors in loolwsd log

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/richdocuments#495]
Checking the server logs reveals a large amount of `EPIPE: Broken pipe` errors every day (see webserver error log).
Yet the app seems to work quite well, no issues, except low performance at some times, were reported by the users.

Can this be attributed to richdocuments app or is it a CODE issue? And could it be even somehow "normal" usage behaviour?

### Nextcloud Server configuration
Shared web hosting

**Web server:**
Apache

**Database:**
mysql 5.7.25
**EDIT:** Updated to 5.7.26

**PHP version:**
7.2.13
**EDIT:** Updated to 7.3.6

**Nextcloud version:** (see Nextcloud admin page)
15.0.5
**EDIT:** Updated to 15.0.10

**EDIT**: Forgot to state the Collabora app version
**Collabora Online version**
3.3.2 (occurred with several older versions, too)
**EDIT:** Updated to 3.3.14

**Are you using encryption:** yes/no
no

### Collabora Online Server configuration

**CODE version**
4.0.1-1
**EDIT**: Same after update to 4.0.4-3

**Web server:**
nginx 1.14.2

**Database:**
mariadb 10.3.13

**PHP version:**
7.3.3

### Client configuration
**Browser:**
Firefox (up to date)

**Operating system:**
Linux

#### Web server error log
<details>
<summary>
Excerpt from the log:
</summary>
`Mai 09 06:05:14 some-server loolwsd[695]: wsd-00695-11771 2019-05-09 04:05:14.424704 [ docbroker_555 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:14 some-server loolwsd[695]: wsd-00695-11771 2019-05-09 04:05:14.425316 [ docbroker_555 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:14 some-server loolwsd[695]: wsd-00695-11771 2019-05-09 04:05:14.426119 [ docbroker_555 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:14 some-server loolwsd[695]: wsd-00695-11771 2019-05-09 04:05:14.426493 [ docbroker_555 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:14 some-server loolwsd[695]: wsd-00695-11771 2019-05-09 04:05:14.427324 [ docbroker_555 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:24 some-server loolwsd[695]: wsd-00695-11900 2019-05-09 04:05:24.455875 [ docbroker_556 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:24 some-server loolwsd[695]: wsd-00695-11900 2019-05-09 04:05:24.456653 [ docbroker_556 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:24 some-server loolwsd[695]: wsd-00695-11900 2019-05-09 04:05:24.457602 [ docbroker_556 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:24 some-server loolwsd[695]: wsd-00695-11900 2019-05-09 04:05:24.458068 [ docbroker_556 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:24 some-server loolwsd[695]: wsd-00695-11900 2019-05-09 04:05:24.459215 [ docbroker_556 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:47 some-server loolwsd[695]: wsd-00695-12028 2019-05-09 04:05:47.448154 [ docbroker_557 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:47 some-server loolwsd[695]: wsd-00695-12028 2019-05-09 04:05:47.449048 [ docbroker_557 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:47 some-server loolwsd[695]: wsd-00695-12028 2019-05-09 04:05:47.450185 [ docbroker_557 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:47 some-server loolwsd[695]: wsd-00695-12028 2019-05-09 04:05:47.450697 [ docbroker_557 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:47 some-server loolwsd[695]: wsd-00695-12028 2019-05-09 04:05:47.451955 [ docbroker_557 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:58 some-server loolwsd[695]: wsd-00695-12155 2019-05-09 04:05:58.436506 [ docbroker_558 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:58 some-server loolwsd[695]: wsd-00695-12155 2019-05-09 04:05:58.437185 [ docbroker_558 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:58 some-server loolwsd[695]: wsd-00695-12155 2019-05-09 04:05:58.438004 [ docbroker_558 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:58 some-server loolwsd[695]: wsd-00695-12155 2019-05-09 04:05:58.438539 [ docbroker_558 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:05:58 some-server loolwsd[695]: wsd-00695-12155 2019-05-09 04:05:58.439699 [ docbroker_558 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:11 some-server loolwsd[695]: wsd-00695-12284 2019-05-09 04:06:11.736135 [ docbroker_559 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:11 some-server loolwsd[695]: wsd-00695-12284 2019-05-09 04:06:11.736911 [ docbroker_559 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:11 some-server loolwsd[695]: wsd-00695-12284 2019-05-09 04:06:11.737889 [ docbroker_559 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:11 some-server loolwsd[695]: wsd-00695-12284 2019-05-09 04:06:11.738366 [ docbroker_559 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:11 some-server loolwsd[695]: wsd-00695-12284 2019-05-09 04:06:11.739519 [ docbroker_559 ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:21 some-server loolwsd[695]: wsd-00695-12412 2019-05-09 04:06:21.226396 [ docbroker_55a ] ERR  #29: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:21 some-server loolwsd[695]: wsd-00695-12412 2019-05-09 04:06:21.227462 [ docbroker_55a ] ERR  #29: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:21 some-server loolwsd[695]: wsd-00695-12412 2019-05-09 04:06:21.228994 [ docbroker_55a ] ERR  #29: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:21 some-server loolwsd[695]: wsd-00695-12412 2019-05-09 04:06:21.229631 [ docbroker_55a ] ERR  #29: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:21 some-server loolwsd[695]: wsd-00695-12412 2019-05-09 04:06:21.231395 [ docbroker_55a ] ERR  #29: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:32 some-server loolwsd[695]: wsd-00695-12540 2019-05-09 04:06:32.236187 [ docbroker_55b ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:32 some-server loolwsd[695]: wsd-00695-12540 2019-05-09 04:06:32.236876 [ docbroker_55b ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:32 some-server loolwsd[695]: wsd-00695-12540 2019-05-09 04:06:32.237697 [ docbroker_55b ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:32 some-server loolwsd[695]: wsd-00695-12540 2019-05-09 04:06:32.238112 [ docbroker_55b ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:32 some-server loolwsd[695]: wsd-00695-12540 2019-05-09 04:06:32.239177 [ docbroker_55b ] ERR  #24: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:41 some-server loolwsd[695]: wsd-00695-12668 2019-05-09 04:06:41.901811 [ docbroker_55c ] ERR  #29: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:41 some-server loolwsd[695]: wsd-00695-12668 2019-05-09 04:06:41.902646 [ docbroker_55c ] ERR  #29: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:41 some-server loolwsd[695]: wsd-00695-12668 2019-05-09 04:06:41.903605 [ docbroker_55c ] ERR  #29: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058
Mai 09 06:06:41 some-server loolwsd[695]: wsd-00695-12668 2019-05-09 04:06:41.904086 [ docbroker_55c ] ERR  #29: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1058`
</details>

**Comment by juliushaertl** [comment]
Are you using HTTP2 on the webserver? Also is there a reason you still run collabora 3.3.2 ?

**Comment by bpcurse** [comment]
> Are you using HTTP2 on the webserver?

Yes, we are using http2 for the collabora subdomain on nginx. Should I try without?

> Also is there a reason you still run collabora 3.3.2 ?

No, I just didn't update the OP :smirk: It is 3.3.13 at the moment, updating to 3.3.14 today.

**Comment by juliushaertl** [comment]
Ok, yes at least last time I checked collabora unfortunately didn't work properly with http2.

**Comment by bpcurse** [comment]
- removed http2 support for the office subdomain
- restarted nginx 
- restarted loolwsd

It seems http2 does not cause the problem. The error is still shown in the log.

The actual nginx server block (IPv6 is completely blocked by iptables):

```
server {
      listen xxx.xxx.xxx.xxx:80;
      listen [::]:80;
      server_name office.server.xxxxx.de;
      return 301 https://$server_name$request_uri;
    }

server {
    listen xxx.xxx.xxx.xxx:443 ssl;
    listen [::]:443 ssl;
    server_name office.server.xxxxx.de;

    ssl_certificate /etc/letsencrypt/live/office.server.xxxxx.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/office.server.xxxxx.de/privkey.pem;

    # static files
    location ^~ /loleaflet {
      proxy_pass http://localhost:9980;
      proxy_set_header Host $http_host;
    }

    # WOPI discovery URL
    location ^~ /hosting/discovery {
      proxy_pass http://localhost:9980;
      proxy_set_header Host $http_host;
    }

    # Capabilities
    location ^~ /hosting/capabilities {
      proxy_pass http://localhost:9980;
      proxy_set_header Host $http_host;
    }    

    location ^~ /lool {
      # this parent location makes sure that a global PHP catch-all
      # won’t pre-empt the first two child locations below

      # main websocket
      location ~ ^/lool/(.*)/ws$ {
        proxy_pass http://localhost:9980;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $http_host;
        proxy_read_timeout 36000s;
      }

      # download, presentation and image upload
      location ~ ^/lool {
        proxy_pass http://localhost:9980;
        proxy_set_header Host $http_host;
      }

      # Admin Console websocket
      location ^~ /lool/adminws {
        proxy_pass http://localhost:9980;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $http_host;
        proxy_read_timeout 36000s;
      }
    }
  }
```

**Comment by juliushaertl** [comment]
Looks sane to me. @thebearon Maybe you can tell if that is an error to worry about?
