### ISSUE TITLE
Labeled as "1" in settings menus.

### ISSUE THREAD

**Issue by PriceChild** [nextcloud/richdocuments#497]
**Describe the bug**
After upgrading to 3.3.2 (from 3.2.4 I think?) the menu items for both users and admins are now simply "1" instead of "Collabora Online".

**To Reproduce**
Unknown

**Expected behavior**
Expected both menu items to remain "Collabora Online"

**Screenshots**
![image](https://user-images.githubusercontent.com/1044068/57518458-f3e43100-7310-11e9-8edb-d41a7b886e3a.png)

**Client details:**
 - Mac OSX
 - Firefox 66.0.5
 - Device: macbook

## Server details

**Operating system**: Ubuntu 18.04

**Web server:** Nginx

**Database:** mysql

**PHP version:** 7.2

**Nextcloud version:** 16

**Version of the richdocuments app** 3.3.2

**Version of Collabora Online**
LOOLWSD
4.0.4 (git hash: 305832f)

LOKit
Collabora Office 6.0-29 (git hash: 5a695a1)

**Comment by PriceChild** [comment]
Given https://github.com/nextcloud/richdocuments/blob/master/lib/Settings/Section.php#L57 I wonderered whether this was a missing translations issue - changed my locale & language from english (United Kingdom) & English (British English) to US versions and refreshed pages but no joy.

**Comment by PriceChild** [comment]
Can't help but notice this bit of the code has recently been touched though... guessing that means I'm on the right track: https://github.com/nextcloud/richdocuments/commit/455e1f260a5345114bf5f7563602f290af9c8bee#diff-1054c9008797466e0620e744ec476aecL54

**Comment by blizzz** [comment]
@juliushaertl

**Comment by juliushaertl** [comment]
@PriceChild A fix for this is in https://github.com/nextcloud/richdocuments/pull/498
Help with testing is appreciated :wink:

**Comment by PriceChild** [comment]
@juliushaertl looking better: 
![image](https://user-images.githubusercontent.com/1044068/57612744-4b7ed880-756d-11e9-823c-90a98892ec61.png) Thanks!

I'm left wondering where it gets the string from, not important but since it's grown from two words it's oversized compared to the rest.
