### ISSUE TITLE
Don't show template picker if there is only one empty template available

### ISSUE THREAD

**Issue by schiessle** [nextcloud/richdocuments#509]
If I create a new Office document in the Nextcloud web interface this window pops up:

![collabora](https://user-images.githubusercontent.com/1589737/58085808-b8bde980-7bbd-11e9-87cb-d9ef02cf188c.png)

I can just chose a empty template and then move on, because no other template exists.

If no template exists we should skip the template dialog.

**Comment by sebelk** [comment]
> If I create a new Office document in the Nextcloud web interface this window pops up:
> 
> ![collabora](https://user-images.githubusercontent.com/1589737/58085808-b8bde980-7bbd-11e9-87cb-d9ef02cf188c.png)
> 
> I can just chose a empty template and then move on, because no other template exists.
> 
> If no template exists we should skip the template dialog.

Same here but even worse :sad

![imagen](https://user-images.githubusercontent.com/4109256/60202342-c1d75180-9820-11e9-9a08-3390dd769d38.png)

Is on nextcloud 16.0.1 and richdocuments 3.3.10
