### ISSUE TITLE
Support opening encrypted files

### ISSUE THREAD

**Issue by pranavk** [nextcloud/richdocuments#51]
Currently the app is not able to open any files when the server-side encryption in enabled. The reason is that the API call made by Collabora Online server doesn't have a real user context => no private key available => no decryption of documents.

**Comment by pranavk** [comment]
cc @LukasReschke @schiessle

**Comment by mmeeks** [comment]
Interesting; so - given that the users are pleading for this feature =) what information can we transfer from the user-context outside the iframe, to add to the WOPI credentials we pass to make this fly ? I guess this is further complicated by multi-factor authentication (?) anyhow - worth talking through. Ultimately, if we have the right WOPI token, and the user is still logged into OC the server has all the information we need - if only it would share it with us (?)

**Comment by LukasReschke** [comment]
@schiessle is on holidays right now but I already talked to him about this and I can share some more insights on this.

So basically the encryption in Nextcloud works the way that every user has a private and a public key. The private key is stored encrypted by a derivative of the users' password and only stored unencrypted in memory when the user accesses Nextcloud logged-in. So we cannot access the users' file and modify it.

To work with publicly shared files we basically have a system public and private key which is accessible to the system obviously. What we should do here is have a possibility to generate such a key on-demand for single files and destroy it once used. So the workflow would be like:

1. User presses "open file in Collabora"
2. `DocumentController::index` gets called and would create a public sharing key for the file
3. When Collabora accesses the file via WOPI the public sharing key is used
4. When Collabora is closed the public sharing key is deleted

@schiessle Did I recap that correctly? If you would find some time to look into item 2 and 4 basically by just showing us a snippet creating and deleting the keys we could probably go a long way here. :)

**Comment by pranavk** [comment]
Spent some time reading code around it. There doesn't seem to be any provision of adding extra system public/private key pair that can be used in this case as you described above. The default encryption module and internal encryption library handles publicShareKey, recovery keys, master keys and user keys. It might be possible to create a random $uid everytime and then add it in KeyManager so it is used as a user key instead of a system key (?)

Thoughts ?

**Comment by ColdSphinX** [comment]
The nextcloud-drawio app seems to get the decrypted document as payload and sends that to the draw.io backend. Which is questionable if that backend is hosted by a third party...but I actually can't find a solution without temporary decrypting the document at some point. (More reasons to host everything yourself.)

https://github.com/pawelrojek/nextcloud-drawio/blob/master/drawio/js/editor.js#L43
