### ISSUE TITLE
CollaboraOnline plugin breaks Microsoft Office documents on iOS Nextcloud app

### ISSUE THREAD

**Issue by csware** [nextcloud/richdocuments#513]
**Describe the bug**
Opening a Microsoft Office Document fails on Nextcloud iOS app after installing CollaboraOnline plugin on Nextcloud server. Deactivating the CollaboraOnline plugin solves the issue.

**To Reproduce**
1. Install CollaboraOnline plugin on Nextcloud server
2. Open iOS app
3. Tap on Microsoft Office document
4. See error: "Request failed: not found (404)"

**Expected behavior**
I'm ask whether to download Microsoft Office document with the default iOS viewer or open CollaboraOffice in Safari browser.

**Client details:**
 - OS: iOS 12.2
 - Nextcloud app 2.23.5.1
 - Device: iPhone  5s

## Server details

**Operating system**: Debian

**Web server:** Apache 2.4

**Database:** MariaDB 2.4

**PHP version:** 7.3

**Nextcloud version:** 16.0.1

**Version of the richdocuments app** 3.3.5

**Version of Collabora Online** 6.0.10.29-29/4.0.4-3

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)

nothing

#### Browser log

Doesn't apply

#### Apache access log

> clientip - - [23/May/2019:23:57:00 +0200] "POST /ocs/v2.php/apps/richdocuments/api/v1/document?format=json HTTP/2.0" 404 77 "-" "Mozilla/5.0 (iOS) Nextcloud-iOS/2.23.5"

</details>

**Comment by juliushaertl** [comment]
This seems to be an issue with the iOS app. Please open an issue in the apps repository: https://github.com/nextcloud/ios
