### ISSUE TITLE
New setting to specify alternative URL to connect to Nextcloud

### ISSUE THREAD

**Issue by hostingnuggets** [nextcloud/richdocuments#516]
**Is your feature request related to a problem? Please describe.**
My Nextcloud web server requires SSL client certificate authentication and thus the Collabora Online server can not connect back to it.

**Describe the solution you'd like**
Add a new setting option in order to specify the alternative URL which Collabora Online has to use in order to connect to the Nextcloud server. On the web server side I would have this specific URL not requiring an SSL certificate but protected by limiting it to the IP of the Collabora Online server..

**Describe alternatives you've considered**
Tried to play with nginx ssl_verify_client and adding if checks as described here https://serverfault.com/questions/741990/nginx-client-certificate-authentication-how-to-exclude-an-ip-address but that it does not work for me and it really makes an ugly patchy web server config.

**Additional context**
n/a

**Comment by hostingnuggets** [comment]
Please do not close this feature request!

**Comment by juliushaertl** [comment]
#483 should help with that.

**Comment by hostingnuggets** [comment]
@juliushaertl is this already implemented and fully functional in version 3.4.2 of this app?
