### ISSUE TITLE
Save files as PDF

### ISSUE THREAD

**Issue by rollanders** [nextcloud/richdocuments#517]
Pdfs are faster to view and have advantages when shared. It would be handy if the file could be saved as a pdf. I can write out as a pdf on my local computer but not directly in the cloud.

**Comment by Thatoo** [comment]
Saving as pdf within the cloud would be a really nice feature instead of downloading it into our computer and then uplaod the pdf into the cloud...

**Comment by BrandonMFong** [comment]
I agree with @Thatoo.  I use nextcloud to mainly keep my resume updated.  As of lately I have been using OnlyOffice to run the backend but would love to continue to use Nextcloud Office as it is local and wouldn't require me to maintain another server to run OnlyOffice. @juliushaertl will there be any movement on this?

**Comment by juliushaertl** [comment]
This is actually possible already with Collabora Online 23.05.

<img width="381" alt="Screenshot 2023-06-15 at 23 11 43" src="https://github.com/nextcloud/richdocuments/assets/3404133/ebe13313-d9a2-481a-bef5-42c1951eff22">


It will allow you to save the document as PDF directly to your Nextcloud instance.
