### ISSUE TITLE
Is there a way to load faster?

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/richdocuments#518]
Opening a document means to wait 6 to 8 secons. 
Is there a possibility to do this faster?

**Comment by juliushaertl** [comment]
@jakobroehrl This seems to be setup related. Can you provide some details about that?

The average loading time I observed is more around 1 second.

**Comment by jakobroehrl** [comment]
@juliushaertl Ohh really, 1 sec sounds great!
Here the "proof" of my 6 seconds from creating the doc till start to edit: https://cloud.roehrl-online.de/s/Tzya9aHmZo8BmH2 

Its running in a virtual machine, 1 CPU, 2 gigs of RAM

**Comment by joergmschulz** [comment]
had slow performance like that as well - moved to faster machines, more cpu, more ram, separated collabora to another machine and now the loading time is fine

**Comment by jakobroehrl** [comment]
OK, thanks. 
I installed it on a better machine, now the speed is way better! :)
