### ISSUE TITLE
duplicate share and three dot menu at the top after clicking the file icon/preview in the sidebar

### ISSUE THREAD

**Issue by violoncelloCH** [nextcloud/richdocuments#528]
**Describe the bug**
duplicate share and three dot menu at the top after clicking the file icon/preview in the sidebar

**To Reproduce**
1. open a document
2. Click on the three dot menu in the top bar and choose e.g. detail
3. in the sidebar click on the file icon / preview
4. See collabora opening the same file again and additional sharing and three dot icons appearing in the top bar

**Expected behavior**
the sharing and three dot menu at the top should not be added additionally whenever repeating steps 2 - 4
or maybe better: don't open the document again, but do either nothing on click on the file icon / preview there or just close the sidebar (what it currently does as well, because it opens collabora again)

**Screenshots**
![image](https://user-images.githubusercontent.com/22591354/58721572-8d18db80-83d5-11e9-9d24-dfbc0604867e.png)

**Client details:**
 - Firefox 67

**Comment by dossantg** [comment]
Same issue on our infrastructure.

Version details:
- Nextcloud 16.0.3
- richdocuments 3.3.14
- collabora stable (not CODE): 4.0.5 (git hash: 1e4154c)

**Comment by juliushaertl** [comment]
Fixed with #562
