### ISSUE TITLE
Can't check "Enable external apps"

### ISSUE THREAD

**Issue by cent89** [nextcloud/richdocuments#538]
**Description**
On settings page, the check on "Enable external apps access" isn't saved 

**To Reproduce**
1. Go to '../index.php/settings/admin/richdocuments'
2. Check 'Enable access to external apps'
3. Click on 'Save'
4. On page reload, the check isn't saved.

Thanks

**Comment by juliushaertl** [comment]
Thanks for reporting. A fix is in #543
