### ISSUE TITLE
Fix code check errors

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/richdocuments#54]
* [x] Invalid language file found: l10n/zh_CN.json: Control character error, possibly incorrectly encoded
* [ ] Database schema error: Name of index richdocuments_wopi_token_idx on table *dbprefix*richdocuments_wopi is too long (18), max. 27 characters + *dbprefix* allowed

cc @nickvergessen

**Comment by MorrisJobke** [comment]
> Database schema error: Name of index richdocuments_wopi_token_idx on table dbprefixrichdocuments_wopi is too long (18), max. 27 characters + dbprefix allowed

This check is there for Oracle/OCI support.

**Comment by pranavk** [comment]
@MorrisJobke I guess no harm if we change that directly to something short like rd_wopi_token_idx in database.xml + bump the app version, right ? 

Anything one should be careful of besides this ?

**Comment by nickvergessen** [comment]
Well this recreates the index again on all other dbs. I hope there are not too many entries in the table, otherwise this could take a while

**Comment by pranavk** [comment]
Yes, that I expected. But there isn't a better option (?), this has to happen one day or other, so lets merge it then, I'd say :-)
