### ISSUE TITLE
Again with the "Failed to load Collabora Online - please try again later"

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/richdocuments#546]
**Describe the bug**
It seems that every other time I get an update to the Nextcloud app for Collabora, I can't open its own documents. Right now docs and spreadsheets don't open. It definitely worked before the update and I think it didn't about two updates ago. I have a reminder to update my Collabora Docker software every two weeks. Last update I did was Monday the 8th of this July.

**To Reproduce**
1. either create a new Collabora document then open it or just try to open and existing document.
2. Watch the loading screen:
![Screenshot from 2019-07-14 12-50-21](https://user-images.githubusercontent.com/28640985/61186729-ab116700-a636-11e9-95e2-bbe84e80ae8f.png)

3. Receive the failure message:
![Screenshot from 2019-07-14 12-50-31](https://user-images.githubusercontent.com/28640985/61186734-b6fd2900-a636-11e9-8867-f75c4b81047f.png)

4. Throw hands in air and give up.

**Expected behavior**
Open a document and get to edit it or just view it.

**Additional red-herrings**
When trying to open documents with the new Nextcloud mobile app for android the files opened correctly. I tested with a spreadsheet (ods) and with a text type open document (odt).

**Screenshots**
See above.

**Client details:**
 - OS: Ubuntu 18.04 Workstation
 - Browser: Both Chrome and Firefox
 - Version: Latest versions on Ubuntu 18.04
 - Device: Desktop

## Server details

Link: [https://cloud.ruppssites.com/index.php/s/GBb6PKdmHJKYAfe](https://cloud.ruppssites.com/index.php/s/GBb6PKdmHJKYAfe)
Password: `2fQZ3pT4rpOrq+qnskBA`

**Operating system:** Ubuntu 18.04.1

**Web server:** Apache 2.4.29

**Database:** MySQL 5.7.26

**PHP version:** 7.2.19

**Nextcloud version:** 16.0.3

**Version of the richdocuments app:** 3.3.13

**Version of Collabora Online** 3.3.13

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Error 
richdocuments 
GuzzleHttp\Exception\ServerException: Server error: `GET https://office.ruppssites.com/hosting/discovery` resulted in a `503 Service Unavailable` response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>503 Service Unavailable</title> </head><body> <h1 (truncated...)

0. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php - line 66: GuzzleHttp\Exception\RequestException::create(GuzzleHttp\Psr7\Request {}, "*** sensiti ... *")
1. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 203: GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")
2. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 156: GuzzleHttp\Promise\Promise::callHandler(1, "*** sensiti ... *", [ GuzzleHttp ... l])
3. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/3rdparty/guzzlehttp/promises/src/TaskQueue.php - line 47: GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}("*** sensiti ... *")
4. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 246: GuzzleHttp\Promise\TaskQueue->run(true)
5. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 223: GuzzleHttp\Promise\Promise->invokeWaitFn()
6. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 267: GuzzleHttp\Promise\Promise->waitIfPending()
7. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 225: GuzzleHttp\Promise\Promise->invokeWaitList()
8. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php - line 62: GuzzleHttp\Promise\Promise->waitIfPending()
9./home/support/domains/cloud.ruppssites.com/public_html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 131: GuzzleHttp\Promise\Promise->wait()
10. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/Http/Client/Client.php - line 161: GuzzleHttp\Client->request("get", "https://off ... y", { verify: "/ ... e})
11. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 106: OC\Http\Client\Client->get("https://off ... y", { timeout: 5})
12. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 78: OCA\Richdocuments\WOPI\DiscoveryManager->fetchFromRemote()
13. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/apps/richdocuments/lib/WOPI/Parser.php - line 41: OCA\Richdocuments\WOPI\DiscoveryManager->get()
14. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/apps/richdocuments/lib/TokenManager.php - line 177: OCA\Richdocuments\WOPI\Parser->getUrlSrc("application ... t")
15. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php - line 176: OCA\Richdocuments\TokenManager->getToken("*** sensiti ... *")
16. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: OCA\Richdocuments\Controller\DocumentController->index("*** sensiti ... *")
17. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\Richdocu ... {}, "index")
18. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/App.php - line 126: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Richdocu ... {}, "index")
19. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\Richdo ... r", "index", OC\AppFramew ... {}, { _route: "r ... "})
20. <<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "r ... "})
21. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { _route: "r ... "})
22. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/lib/base.php - line 975: OC\Route\Router->match("/apps/richdocuments/index")
23. /home/support/domains/cloud.ruppssites.com/public_html/nextcloud/index.php - line 42: OC::handleRequest()
```

#### Browser log
```
What?
```

</details>

**Comment by juliushaertl** [comment]
The error is pretty clear: 

> `GET https://office.ruppssites.com/hosting/discovery` resulted in a `503 Service Unavailable` response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>503 Service Unavailable</title> </head><body> <h1 (truncated...)

This means that your collabora service is probably not responding to the apache proxy. In case you have recently updated/restarted the collabora process you might also want to reload the apache service.

**Comment by WNYmathGuy** [comment]
Well, @juliushaertl that didn't fix things at all. Last night after some OS updates I rebooted the entire server. Today after reading your message I tried reloading Apache through the interface for the Virtual Server office.ruppssites.com proxy and then the cloud.ruppssites.com site, then the whole Apache server for the system. None of that made any difference.

Also (_this might be a red herring but_), I see that after the upgraded Collabora app, the creation of new files defaults to making *.pptx, *.xlsx and *.docx extensions instead of *.odp, *.ods & *.odt files.

**Comment by juliushaertl** [comment]
Can you check the logs for further messages, especially also the browser log:

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by WNYmathGuy** [comment]
This is a very focused set for you. Let me know if you want more variations. Just to be thorough I tried it on my wife's windows computer and it also didn't work. I'm wondering if redoing Docker would help.

### Chrome Browser on Ubuntu 18.04 Logs
#### Loading "Files" page in Nextcloud

[cloud.ruppssites.com-page-load.log](https://github.com/nextcloud/richdocuments/files/3398726/cloud.ruppssites.com-page-load.log)


#### Loading the `WordPress Domain Pricing.ods` file

[cloud.ruppssites.com-file-launch.log](https://github.com/nextcloud/richdocuments/files/3398733/cloud.ruppssites.com-file-launch.log)

**Comment by WNYmathGuy** [comment]
@juliushaertl GAAAHHH!!! I finally did an early update to the docker part of Collabora. Files open fine again in the web browser interface. 

The mobile app is still sending a new copy to Google Docs, Sheets, etc., each time a file is accessed on the device. Very strange. It does that even when you go to the "On device" section and tap on the local copy.

Any idea where I report the Nextcloud app errors?

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/android seems to be the right place :wink: 

Good to hear that it is working now.
