### ISSUE TITLE
Setting "Use OOXML by default for new files" not working

### ISSUE THREAD

**Issue by michag86** [nextcloud/richdocuments#55]
### Steps to reproduce
1. Enable "Use OOXML by default for new files" in settings
2. Create a new Spreadsheet or Document

### Expected behaviour
New Documents are created as OOXML (docx/xlsx)

### Actual behaviour
New Documents are created as ODF (odt/ods)

### Server configuration
**Operating system**: CentOS 7.3

**Web server:** Apache/2.4.6

**Database:** mysql 5.5.52

**PHP version:** 5.6.25

**Nextcloud version:** 11.0.3 (stable) - 11.0.3.2

**Collabora Version:** 1.11.27

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from NC10.0.5

**Where did you install Nextcloud from:** zip

cc: @MorrisJobke

**Comment by MorrisJobke** [comment]
cc @timar @kendy @pranavk

**Comment by pranavk** [comment]
This regressed with aa89c908a70dddabb39ea7d0a166e147e31d3f5d

@LukasReschke Is it okay to restore the behavior there or do you have some other better alternative in mind that should be there. The commit message says 'removing unrequired route'. It makes me think that calling getSettings route there is not necessary and I can get the value of 'doc_format' settings by some other way.

**Comment by MorrisJobke** [comment]
> @LukasReschke Is it okay to restore the behavior there or do you have some other better alternative in mind that should be there. The commit message says 'removing unrequired route'. It makes me think that calling getSettings route there is not necessary and I can get the value of 'doc_format' settings by some other way.

This could also be a wrong check for this "unrequired route" - maybe it was not obvious that this route is still needed. I'm fine with reverting this commit.

**Comment by timar** [comment]
Fixed in 1.11.30 and 1.12.30.
