### ISSUE TITLE
Error saving document opened via shared link

### ISSUE THREAD

**Issue by Zetman13** [nextcloud/richdocuments#550]
**Describe the bug**
Unable to save document that was opened via shared link (with editing allowed) while being authorized as a user in NextCloud

**To Reproduce**
1. Create a document as User1
2. Create a shared link with allowed editing as User1
3. Open that link as User2
4. Make any change in the shared file as User2 and try to save the file
5. Get an error "Document cannot be saved. Check yout permissions or contact the storage server administrator."

**Expected behavior**
File is saved.

**Screenshots**
![image](https://user-images.githubusercontent.com/25324264/61517051-fcdb3800-aa0e-11e9-817a-4ca947103c56.png)

**Client details:**
Bug happen on any client: any browser, any OS

## Server details

**Operating system**: Ubuntu 18.04

**Web server:** Apache2

**Database:** PostgreSQL

**PHP version:** PHP 7.3.7 (cli) (built: Jul 17 2019 22:29:15)

**Nextcloud version:** 16.0.3

**Version of the richdocuments app** v3.3.13

**Version of Collabora Online** LOOLWSD 4.0.4 (git hash: 305832f), LOKit Collabora Office 6.0-29 (git hash: 5a695a1)

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"iwv6L3td7Yw5lpcDULOv","level":3,"time":"2019-07-19T07:20:43+00:00","remoteAddr":"172.17.0.1","user":"--","app":"PHP","method":"POST","url":"\/index.php\/apps\en=joSSvwSa1jjH0lppLLWSazI731iY0uCO&access_token_ttl=0&permission=edit","message":"Undefined offset: 0 at \/var\/www\/html\/apps\/richdocuments\/lib\/Controller\/WopiCo:"16.0.3.0"}
{"reqId":"iwv6L3td7Yw5lpcDULOv","level":3,"time":"2019-07-19T07:20:43+00:00","remoteAddr":"172.17.0.1","user":"--","app":"index","method":"POST","url":"\/index.php\/appoken=joSSvwSa1jjH0lppLLWSazI731iY0uCO&access_token_ttl=0&permission=edit","message":{"Exception":"Error","Message":"Call to a member function getMTime() on null","Code"/Http\/Dispatcher.php","line":166,"function":"putFile","class":"OCA\\Richdocuments\\Controller\\WopiController","type":"->","args":["122","joSSvwSa1jjH0lppLLWSazI731iY0\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Richdocuments\\Controllervate\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Richdocuments\\Controlprivate\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Richdocuments\\Controller\ncyInjection\\DIContainer"},{"fileId":"122_oces6n10193h","_route":"richdocuments.wopi.putFile"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteAction:"richdocuments.wopi.putFile"}]},{"file":"\/var\/www\/html\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramewooute":"richdocuments.wopi.putFile"}]},{"file":"\/var\/www\/html\/lib\/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/r\/var\/www\/html\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/html\/apps\/richdocuments\/lib\/Controller\/WOOLWSD WOPI Agent 4.0.4","version":"16.0.3.0"}
```

</details>

**Comment by juliushaertl** [comment]
The first log entry seems to miss something. Is there a full message in the log file? Can you also report some details about the storage you are using? Anything special there like external storages?

**Comment by Zetman13** [comment]
Every time user tries to save file using link, only these two log messages are created. No external storage is used.

**Comment by hoellen** [comment]
I can confirm this. The storage is local on a xfs filesystem.
As a workaround User2 needs to use the "Private Browsing"-Feature or another browser (so he is not logged in) to edit and save the file.
Another workaround is to share the file not with a link but share it directly with the user.

**Comment by juliushaertl** [comment]
Ah ok, then this might be related to "Use actual user id if a logged in user browses a public share link" from https://github.com/nextcloud/richdocuments/pull/451

https://github.com/nextcloud/richdocuments/pull/505/files#diff-baf5c53411d5249f755ad0783df741f6R291

**Comment by pierreozoux** [comment]
@juliushaertl we are using 3.4.5, and the PR you reference are part of 3.4.5, but we still have this bug. If you need further debug information, I could provide you anything you need.

**Comment by juliushaertl** [comment]
@pierreozoux Are you having the exact same issue as described in https://github.com/nextcloud/richdocuments/issues/550#issuecomment-521988322 ?

**Comment by pierreozoux** [comment]
Yes, in my case the storage is ceph ObjectStore (s3 compatible)

**Comment by pierreozoux** [comment]
I actually tried with latest, and this is fixed. I'll close this then. Thanks :)

(I think 3.4.5 fixed it - https://github.com/nextcloud/richdocuments/releases/tag/v3.4.5 - `Always use the owner file owner to access for share links` )
