### ISSUE TITLE
Can't edit document when folder containing the file is read-only and file itself is shared as editable

### ISSUE THREAD

**Issue by supremesyntax** [nextcloud/richdocuments#554]
**Describe the bug**
A document can't be edited when it is shared with another user with edit permission + the superior folder is shared as read-only.

(Document can be opened and edited with local Libreoffice/MSOffice with sync client)

**To Reproduce**
1. Share a folder containing an xlsx file as read-only with user A
2. Share the document itself with edit permission also with user A
3. Open the document we shared on step 2 with collabora as user A
4. File can't be edited and is shown as read-only (can't click any cell)

**Expected behavior**
File should be editable

**Client details:**
 - OS: Windows 10
 - Browser FF, IE, Chrome
 - Version latest

## Server details

**Operating system**: 
Ubuntu 16.04.6 LTS
**Web server:** 
Apache 2.4.18-2ubuntu3.10
**Database:** 
MySQL 14.14 Distrib 5.7.27
**PHP version:** 
v7.0.33-0ubuntu0.16.04.5
**Nextcloud version:** 
15.0.8
**Version of the richdocuments app** 
 3.3.14
**Version of Collabora Online**
latest (4.0.5.2)

Can someone verify this issue? 
Looks to me like collabora mixes up permissions when a file is shared in 2 ways with the same user.

**Comment by juliushaertl** [comment]
Is the document opened in read only mode or is the save action just failing?

**Comment by supremesyntax** [comment]
It is opened in read-only mode. (Despite the fact that it has been shared with editing allowed)

**Comment by juliushaertl** [comment]
I would assume this is related to the way we access the file by file id and just pick the first result there. Ideally we should fetch by path (which would also be better performance wise) or we should take the file with the highest available permissions.

**Comment by joshtrichards** [comment]
Fixed in #2330
