### ISSUE TITLE
Error	richdocuments	GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 5000 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by samigoncu** [nextcloud/richdocuments#555]
GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 5000 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)/var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php - line 149:GuzzleHttp\Handler\CurlFactory::createRejection(GuzzleHttp\H ... l}, { errno: 28, ... 0})/var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php - line 102:GuzzleHttp\Handler\CurlFactory::finishError(GuzzleHttp\H ... {}, GuzzleHttp\H ... l}, GuzzleHttp\H ... {})/var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php - line 43:GuzzleHttp\Handler\CurlFactory::finish(GuzzleHttp\H ... {}, GuzzleHttp\H ... l}, GuzzleHttp\H ... {})/var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php - line 28:GuzzleHttp\Handler\CurlHandler->__invoke("*** sensiti ... *", "*** sensiti ... *")/var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php - line 51:GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensiti ... *")/var/www/html/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php - line 37:GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensiti ... *")/var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php - line 30:GuzzleHttp\PrepareBodyMiddleware->__invoke("*** sensiti ... *", "*** sensiti ... *")/var/www/html/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php - line 70:GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")/var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php - line 60:GuzzleHttp\RedirectMiddleware->__invoke("*** sensiti ... *", "*** sensiti ... *")/var/www/html/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php - line 67:GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")/var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php - line 277:GuzzleHttp\HandlerStack->__invoke("*** sensiti ... *", "*** sensiti ... *")/var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125:GuzzleHttp\Client->transfer("*** sensiti ... *", "*** sensiti ... *")/var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php - line 131:GuzzleHttp\Client->requestAsync("get", GuzzleHttp\Psr7\Uri {}, { verify: fa ... }})/var/www/html/lib/private/Http/Client/Client.php - line 161:GuzzleHttp\Client->request("get", "https://off ... y", { verify: fa ... e})/var/www/html/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 106:OC\Http\Client\Client->get("https://off ... y", { timeout: 5,verify: false})/var/www/html/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 78:OCA\Richdocuments\WOPI\DiscoveryManager->fetchFromRemote()/var/www/html/apps/richdocuments/lib/WOPI/Parser.php - line 41:OCA\Richdocuments\WOPI\DiscoveryManager->get()/var/www/html/apps/richdocuments/lib/TokenManager.php - line 177:OCA\Richdocuments\WOPI\Parser->getUrlSrc("application ... t")/var/www/html/apps/richdocuments/lib/Controller/DocumentController.php - line 176:OCA\Richdocuments\TokenManager->getToken("*** sensiti ... *")/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 166:OCA\Richdocuments\Controller\DocumentController->index("*** sensiti ... *")/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 99:OC\AppFramework\Http\Dispatcher->executeController(OCA\Richdocu ... {}, "index")/var/www/html/lib/private/AppFramework/App.php - line 126:OC\AppFramework\Http\Dispatcher->dispatch(OCA\Richdocu ... {}, "index")/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:OC\AppFramework\App::main("OCA\\Richdo ... r", "index", OC\AppFramew ... {}, { _route: "r ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "r ... "})/var/www/html/lib/private/Route/Router.php - line 297:call_user_func(OC\AppFramew ... {}, { _route: "r ... "})/var/www/html/lib/base.php - line 975:OC\Route\Router->match("/apps/richdocuments/index")/var/www/html/index.php - line 42:OC::handleRequest()
--

**Comment by thebearon** [comment]
There's nothing useful in this.

**Comment by juliushaertl** [comment]
The error shows that your collabora instance didn't respond withing the timeout of 15s when Nextcloud tried to connect to it. If you want to report a bug, please fill out the issue template so we know what the actual issue is.
