### ISSUE TITLE
problem vhost with virtualname including subdomain with dot / reproducible problem

### ISSUE THREAD

**Issue by adrienfr44** [nextcloud/richdocuments#56]
Error log:

```
wsd-00024-00032 17:39:00.279408 [ websrv_poll ] WRN  WOPI host did not pass optional access_token_ttl| wsd/FileServer.cpp:327
wsd-00024-00034 17:39:00.750445 [ docbroker_001 ] ERR  WOPI::CheckFileInfo is missing JSON payload| wsd/Storage.cpp:475
```

**Comment by pranavk** [comment]
Don't have LDAP backend, but can confirm that normal standard NC11.0.3 works fine with 1.11.27, so likely LDAP related.

**Comment by adrienfr44** [comment]
mmm. ok tks for this information, i will try other complementary test tonight with a new instance nc11.0.3 connected or not with backend ldap... I will report results tomorrow

**Comment by adrienfr44** [comment]
you're right,  fresh install nc 11.0.3 + no backend = collabora online app ok

I will try to reproduce the problem by moving step by step

**Comment by adrienfr44** [comment]
no problem with backend ldap

ok now i reproduce but i don't know if it's app collabora online or collabora online image docker or me (probably... in configuration apache or docker run)

Details : 

It's ok with : 

- collabora online image docker deploy on vhost office.toto.fr

`
sudo docker run -t -d -p 127.0.0.1:9980:9980 -e 'domain=test\\.toto\\.fr' --restart always --cap-add MKNOD collabora/code 

`

- fresh install nc11.0.3 on vhost **test.toto.fr** + conf app collabora online OK (https://office.toto.fr)


It's ko if : 

- collabora online image docker deploy on vhost office.toto.fr

`
sudo docker run -t -d -p 127.0.0.1:9980:9980 -e 'domain=test\\.test\\.toto\\.fr' --restart always --cap-add MKNOD collabora/code 

`
- fresh install nc11.0.3 on vhost **test.test.toto.fr** + conf app collabora online OK (https://office.toto.fr)

**Comment by adrienfr44** [comment]
i close this issue, i want to rewrite correctly this issue
