### ISSUE TITLE
Changelog is missing an entry for release 3.3.14

### ISSUE THREAD

**Issue by gohrner** [nextcloud/richdocuments#564]
The CHANGELOG.md file on trunk (and also on the 3.3.14 tag) is missing an entry for release 3.3.14, which is currently offered as an update in my NextCloud installations.

What are the notable fixes / differences which have gone into this maintenance release?

**Comment by juliushaertl** [comment]
Sorry, I forgot to add the changelog to the release, done that now: https://github.com/nextcloud/richdocuments/releases/tag/v3.3.14

**Comment by gohrner** [comment]
@juliushaertl : The changelog entry for 3.3.14 is still not contained in the CHANGELOG.md file (https://github.com/nextcloud/richdocuments/blob/master/CHANGELOG.md) and again a Changelog for 3.3.15 (which is currently offered by Nextcloud as an update) is missing completely. :-(
