### ISSUE TITLE
Changelog is missing an entry for release 3.3.15

### ISSUE THREAD

**Issue by gohrner** [nextcloud/richdocuments#571]
Similar to #564, which I'm apparently and unfortunately not allowed to re-open.

#564 also still is not fixed:

https://github.com/nextcloud/richdocuments/blob/master/CHANGELOG.md lacks changelog entries for *both* the 3.3.14 and 3.3.15 releases.

Meanwhile at least the changelog for 3.3.14 has been provided for the actual release (https://github.com/nextcloud/richdocuments/releases), however there's not public changelog for 3.3.15 whatsoever.

**Comment by juliushaertl** [comment]
The changelog is currently only in the stable branch, I'll update that later:

https://github.com/nextcloud/richdocuments/blob/stable-3.3/CHANGELOG.md

**Comment by gohrner** [comment]
Ok, thanks for the info! Shall I close this issue again then, or leave it open as a reminder?

**Comment by juliushaertl** [comment]
Done with https://github.com/nextcloud/richdocuments/commit/78683e22e1a2f8fadf187540d074fdd71defbe17
