### ISSUE TITLE
Timeout for thumbnail generation is too short

### ISSUE THREAD

**Issue by pielonet** [nextcloud/richdocuments#578]
**Describe the bug**
There is a timeout set to 10s in file `lib/Preview/Office.php` (function getThumbnail()) for the generation of thumbnail previews of office document by CollaboraOnline backend.
10s is too short for some large files (tested with 6MB files that require up to 20s to generate previews).

**To Reproduce**
1. Enable rcihdocuments in Nextcloud
2. Open a folder in the File app with large PDF files
3. Thumbnail previews for large do not get generated because of a 10s timeout
4. Each time you enter that folder the same request is launched (because thumbnail wasn't cached) and fails, putting pressure on CollaboraOnline backend.

**Expected behavior**
A bigger timeout (100s) would make it possible to render even very large files (esepecially PDFs)

**Screenshots**

**Client details:**
 - OS: All
 - Browser All
 - Version ?
 - Device: desktop

## Server details

**Operating system**: Linux

**Web server:**
Apache
**Database:**
Mysql
**PHP version:**
7.2
**Nextcloud version:**
16.0.4
**Version of the richdocuments app**
3.3.15
**Version of Collabora Online**
4.0.5

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by gitsan13** [comment]
Hi! Are you accepting a PR for this? I want to give it a try:)

**Comment by juliushaertl** [comment]
Would be glad to see a contribution for this. I'd say a timeout value of 25 seconds would be suitable to avoid running into webserver timeouts with values above that.

**Comment by gitsan13** [comment]
Thanks.
I got where the change in the code needs to be done. Have a look,

![Screenshot (65)](https://user-images.githubusercontent.com/57125943/202070033-db77a059-7258-4c92-97b1-0daa50ae8c76.jpg)

**Comment by juliushaertl** [comment]
> Can you tell me how should I test that whether this timeout value is giving correct results by not running into web server timeout errors? 

THere is no real way for that as the timeout may depend on what the admin has configured on those setups, but the change looks good to me, so feel free to open a pull request with that :)

**Comment by gitsan13** [comment]
Noted for action.
