### ISSUE TITLE
Can't copy and paste in Document on iOS devices

### ISSUE THREAD

**Issue by Bables55** [nextcloud/richdocuments#584]
**Describe the bug**
I can't copy and paste only in documents. *I can do that with spreadsheets.
The document doesn't have a pop-up menu and doesn't look like a magnifying glass.

**To Reproduce**
1. Open/Create (collabora)document.
2. Copy text on anywhere.
3. Touch and hold the location

**Expected behavior**
An iOS pop-up menu will appear and I can copy or paste.

**Client details:**
 - OS: iOS 12.4
 - Browser Safari, Brave, Nextcloud app
 - Version Latest.
 - Device: iPhone and iPad

## Server details

**Operating system**:
CentOS 7.6
**Web server:**
Nginx 1.16.1
**Database:**
MariaDB 10.2.26
**PHP version:**
PHP 7.3.8
**Nextcloud version:**
16.0.4
**Version of the richdocuments app**
LOOLWSD
4.0.6 (git hash: 79f3ef2)
LOKit
Collabora Office 6.0-29 (git hash: bcd9acf)
**Version of Collabora Online**
3.3.15

**Comment by juliushaertl** [comment]
There has been some work recently to make copy/paste behavior work better on mobile devices like #552 The fixes in collabora are still pending to be released as far as I know, so this should improve in the upcoming collabora versions.
