### ISSUE TITLE
Upgrade to v3.4.0 not working on nextcloud 16.0.4

### ISSUE THREAD

**Issue by ClCfe** [nextcloud/richdocuments#592]
Hello

On nextcloud 16.0.4, I tried to upgrade richdocuments to version 3.4.0
upgrade seems OK, but I can't enable the app

> 
> [no app in context] Error: OCP\AppFramework\QueryException: Could not resolve OCA\Federation\TrustedServers! Class OCA\Federation\TrustedServers does not exist at <<closure>>
> 
>  0. /opt/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 119
>     OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Federation\\TrustedServers")
>  1. /opt/nextcloud/lib/private/ServerContainer.php line 150
>     OC\AppFramework\Utility\SimpleContainer->query("OCA\\Federation\\TrustedServers")
>  2. /opt/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 385
>     OC\ServerContainer->query("OCA\\Federation\\TrustedServers")
>  3. /opt/nextcloud/apps/richdocuments/lib/AppInfo/Application.php line 111
>     OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Federation\\TrustedServers")
>  4. /opt/nextcloud/apps/richdocuments/appinfo/app.php line 66
>     OCA\Richdocuments\AppInfo\Application->updateCSP("*** sensitive parameters replaced ***")
>  5. /opt/nextcloud/lib/private/legacy/app.php line 262
>     undefinedundefinedrequire_once("/opt/nextcloud/ ... p")
>  6. /opt/nextcloud/lib/private/legacy/app.php line 155
>     OC_App::requireAppFile(OCA\Richdocuments\AppInfo\Application {})
>  7. /opt/nextcloud/lib/private/legacy/app.php line 128
>     OC_App::loadApp("richdocuments")
>  8. /opt/nextcloud/apps/dav/appinfo/app.php line 30
>     OC_App::loadApps(["dav"])
>  9. /opt/nextcloud/lib/private/legacy/app.php line 262
>     undefinedundefinedrequire_once("/opt/nextcloud/apps/dav/appinfo/app.php")
> 10. /opt/nextcloud/lib/private/legacy/app.php line 155
>     OC_App::requireAppFile("dav")
> 11. /opt/nextcloud/lib/private/legacy/app.php line 128
>     OC_App::loadApp("dav")
> 12. /opt/nextcloud/lib/base.php line 960
>     OC_App::loadApps()
> 13. /opt/nextcloud/index.php line 42
>     OC::handleRequest()
> 
> GET /apps/files
>

**Comment by taavit21** [comment]
I had exactly the same problem.
Had to downgrade to previous version.

**Comment by juliushaertl** [comment]
Hm right, that could happen if you have disabled the federation app. Is that the case? I'll look into preparing a fix.

**Comment by ClCfe** [comment]
yes federation app is disabled

**Comment by ebogaard** [comment]
The proposed PR #593 makes enabling the app possible again.
