### ISSUE TITLE
Can't open admin settings after updating to 3.4.0

### ISSUE THREAD

**Issue by Phoenixxx3** [nextcloud/richdocuments#597]
Collabora does not work. Getting "internal server error" page when trying to open admin settings of collabora.

Nextcloud 16.0.4
Ubuntu 18.04
Apache 2
PHP 7.2
mariadb 15.1

Log:

[index] Error: Error: Call to undefined method OCA\Richdocuments\AppConfig::getAppSettings() at <<closure>>

 0. /var/www/nextcloud/settings/Controller/CommonSettingsTrait.php line 115
    OCA\Richdocuments\Settings\Admin->getForm()
 1. /var/www/nextcloud/settings/Controller/AdminSettingsController.php line 74
    OC\Settings\Controller\AdminSettingsController->formatSettings([[OCA\Richdocuments\Settings\Admin {}]])
 2. /var/www/nextcloud/settings/Controller/CommonSettingsTrait.php line 126
    OC\Settings\Controller\AdminSettingsController->getSettings("richdocuments")
 3. /var/www/nextcloud/settings/Controller/AdminSettingsController.php line 65
    OC\Settings\Controller\AdminSettingsController->getIndexResponse("admin", "richdocuments")
 4. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    OC\Settings\Controller\AdminSettingsController->index("richdocuments")
 5. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\Cont ... {}, "index")
 6. /var/www/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\Cont ... {}, "index")
 7. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OC\\Settings\\C ... r", "index", OC\AppFramework\ ... {}, {section: "richd ... "})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({section: "richd ... "})
 9. /var/www/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {section: "richd ... "})
10. /var/www/nextcloud/lib/base.php line 975
    OC\Route\Router->match("/settings/admin/richdocuments")
11. /var/www/nextcloud/index.php line 42
    OC::handleRequest()

GET /index.php/settings/admin/richdocuments

**Comment by juliushaertl** [comment]
Hm, that error looks strange. Can you check if the file in apps/richdocuments/lib/AppConfig.php actually has that method defined:

https://github.com/nextcloud/richdocuments/blob/befa1ce66ee14971fba6cf3e4a9ce017e0565f98/lib/AppConfig.php#L89

**Comment by AdrianBadertscher** [comment]
Hello, everyone,

I noticed the same bug, even with the versions:

Nextcloud 16.0.4
Debian Buster 10.1
Apache 2
PHP 7.3
mariadb 10.3
Collabora 3.4.0

/etc/postfix # cat /var/www/cloud.webdienst.li/cloud/apps/richdocuments/lib/AppConfig.php | grep getAppSettings
	public function getAppSettings() {


`[no app in context] Error: OCP\AppFramework\QueryException: Could not resolve OCA\Federation\TrustedServers! Class OCA\Federation\TrustedServers does not exist at <<closure>>

 0. /var/www/clients/client1/web1/cloud/lib/private/AppFramework/Utility/SimpleContainer.php line 119
    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Federation\\TrustedServers")
 1. /var/www/clients/client1/web1/cloud/lib/private/ServerContainer.php line 150
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\Federation\\TrustedServers")
 2. /var/www/clients/client1/web1/cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 385
    OC\ServerContainer->query("OCA\\Federation\\TrustedServers")
 3. /var/www/clients/client1/web1/cloud/apps/richdocuments/lib/AppInfo/Application.php line 111
    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Federation\\TrustedServers")
 4. /var/www/clients/client1/web1/cloud/apps/richdocuments/appinfo/app.php line 66
    OCA\Richdocuments\AppInfo\Application->updateCSP("*** sensitive parameters replaced ***")
 5. /var/www/clients/client1/web1/cloud/lib/private/legacy/app.php line 262
    undefinedundefinedrequire_once("/var/www/client ... p")
 6. /var/www/clients/client1/web1/cloud/lib/private/legacy/app.php line 155
    OC_App::requireAppFile(OCA\Richdocuments\AppInfo\Application {})
 7. /var/www/clients/client1/web1/cloud/lib/private/legacy/app.php line 128
    OC_App::loadApp("richdocuments")
 8. /var/www/clients/client1/web1/cloud/apps/dav/appinfo/app.php line 30
    OC_App::loadApps(["dav"])
 9. /var/www/clients/client1/web1/cloud/lib/private/legacy/app.php line 262
    undefinedundefinedrequire_once("/var/www/client ... p")
10. /var/www/clients/client1/web1/cloud/lib/private/legacy/app.php line 155
    OC_App::requireAppFile("dav")
11. /var/www/clients/client1/web1/cloud/lib/private/legacy/app.php line 128
    OC_App::loadApp("dav")
12. /var/www/clients/client1/web1/cloud/lib/base.php line 960
    OC_App::loadApps()
13. /var/www/clients/client1/web1/cloud/index.php line 42
    OC::handleRequest()

GET /index.php/apps/files
from 82.220.94.131 by radrian at 2019-09-05T17:03:08+00:00`

**Comment by Phoenixxx3** [comment]
>  Can you check if the file in apps/richdocuments/lib/AppConfig.php actually has that method defined:

public function getAppSettings() {
                $result = [];
                $keys = $this->config->getAppKeys(Application::APPNAME);
                foreach ($keys as $key) {
                        $value = $this->getAppValueArray($key);
                        $value = $value === 'yes' ? true : $value;
                        $result[$key] = $value === 'no' ? false : $value;
                }

                $keys = $this->config->getAppKeys(self::WATERMARK_APP_NAMESPACE);
                foreach ($keys as $key) {
                        if (strpos($key, 'watermark_') === 0) {
                                $value = $this->getAppValueArray($key);
                                $value = $value === 'yes' ? true : $value;
                                $result[$key] = $value === 'no' ? false : $value;
                        }
                }
                return $result;
}

**Comment by juliushaertl** [comment]
@AdrianBadertscher Your error message is totally different, you are looking for https://github.com/nextcloud/richdocuments/issues/592

**Comment by juliushaertl** [comment]
In case you did not have the federation app enabled please try again with 3.4.1

**Comment by Phoenixxx3** [comment]
Federation app was and still is enabled. I updated to version 3.4.1, but still the same problem.

**Comment by Phoenixxx3** [comment]
Did a filesystem check. Now it works. Sorry my bad.
