### ISSUE TITLE
Rename Repository to "Documents"

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/richdocuments#6]
Because we do not longer have "documents" over here ... I think we can do this 😉

**Comment by LukasReschke** [comment]
I'm not entirely confident in doing so because the appid is also "richdocuments". That one we can't change because the old app had the same and we want automatic migration once people update to 11.

**Comment by MariusBluem** [comment]
Ah... okay :( I see ...

**Comment by LukasReschke** [comment]
:sadpandaface:
