### ISSUE TITLE
Files not opening in IE11 - just downloading

### ISSUE THREAD

**Issue by supremesyntax** [nextcloud/richdocuments#610]
**Describe the bug**
Since the last update files can't be edited in IE11 anymore. On click the file just gets downloaded.
(Firefox + Chrome work as expected)

**Expected behavior**
Collabora should open the file for editing

IE11 on Win10 latest updates

## Server details

**Operating system**:
Ubuntu 16.04
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
7.0.33
**Nextcloud version:**
15.0.11
**Version of the richdocuments app**
3.4.1
**Version of Collabora Online**
4.0.6.1

No errors in logs...

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/richdocuments/pull/613 fixes this, I'll prepare another release soon.

**Comment by thebearon** [comment]
I checked with 3.4.2 just now, and unfortunately don't see a difference, the file is still downloaded instead of getting opened in IE 11.

**Comment by supremesyntax** [comment]
same here, sill not opening collabora

**Comment by juliushaertl** [comment]
Any errors in the browser console? I just tried with yesterdays 3.4.2 and it worked fine for me on IE11.

**Comment by supremesyntax** [comment]
Undefined index: userId at /var/www/nextcloud/apps/richdocuments/templates/documents.php#8

**Comment by thebearon** [comment]
I'm getting an error here when reloading the file list:
https://github.com/nextcloud/richdocuments/blob/877a675c6838b3347cec2755f53462cc89defbc4/src/viewer.js#L43
`'Symbol' is undefined.`

**Comment by supremesyntax** [comment]
This is from the browser console:

```
Source-Map-Fehler: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://cloud.vollmer.de/apps/richdocuments/js/viewer.js?v=1c92e2ac-23
Source-Map-Adresse: viewer.js.map
```

**Comment by vpecinka** [comment]
I have the same problem with undefined index userId:

`Undefined index: userId at /www/nextcloud/apps/richdocuments/templates/documents.php#8`

The problem is with a specific .oid file, that is shared via public link. If I open it via public link, I got error in the libra office "Failed to read document from the storage" and I can see this "undefined index" error in the nextcloud.log. However, if I use the same public link with anonymous windows in the browser, it is displayed and works fine.

So I lues there is something wrong in the rich document when it comes to mixing public link shares and session of an logged user (however, logout does not help, only anonymous browser window).

**Comment by vpecinka** [comment]
correction: when I logged out, the richdocument plugin works over the public link share.

**Comment by supremesyntax** [comment]
it is still not working with 3.4.3
if i can provide some more logs or test something just tell

**Comment by supremesyntax** [comment]
can someone reassign this? we're in v3.5.1 now, this bug is still assigned to 3.4.3 milestone

**Comment by juliushaertl** [comment]
@supremesyntax I still cannot reproduce this anymore with 3.5.1 Could you try to provide some steps how you trigger the issue? Editing works fine here both logged in as well as on public share links with IE 11.

**Comment by supremesyntax** [comment]
When i click on the filename in IE11 a download is triggered.
In Firefox+Chrome+Edge the file opens in collabora.

Public links also just provide a preview and a download link.
Again in Firefox+Chrome+Edge the a nickname is asked for and the document opens in collabora.

#Client:

Win 10 Pro 10.0.18362
IE11 11.535.18362.0 (Upd-Vers. 11.0.165)

#Server:

Ubuntu 16.04.6 LTS
PHP 7.0.33-0ubuntu0.16.04.7 (cli) ( NTS )

Nextcloud v15.0.14

Collabora 4.2.0 (Docker container)

Installed Apss:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - announcementcenter: 3.4.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.6.6
  - checksum: 0.4.3
  - circles: 0.16.13
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.2
  - deck: 0.6.6
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_accesscontrol: 1.5.0
  - files_antivirus: 2.2.1
  - files_automatedtagging: 1.5.0
  - files_downloadactivity: 1.4.0
  - files_markdown: 2.1.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - groupfolders: 3.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - metadata: 0.10.0
  - nextcloud_announcements: 1.4.0
  - notes: 3.1.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - polls: 0.10.4
  - provisioning_api: 1.5.0
  - ransomware_protection: 1.3.1
  - richdocuments: 3.5.1
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.4
  - systemtags: 1.5.0
  - tasks: 0.11.3
  - theming: 1.6.0
  - theming_customcss: 1.5.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.2
  - updatenotification: 1.5.0
  - workflow_script: 1.0.1
  - workflowengine: 1.5.0

**Comment by thebearon** [comment]
I checked with different Nextcloud versions, seems like the bug is in NC 15 (which just reached its EOL), but 16 and 17 are fine.

On the other hand, I still can't open files in a local NC 16 instance when using a checked out richdocuments repo. This affects Chrome and Firefox as well.

**Comment by thebearon** [comment]
This should be fine now.
