### ISSUE TITLE
Feature request: support encryption for collabora

### ISSUE THREAD

**Issue by robstoll** [nextcloud/richdocuments#626]
**Is your feature request related to a problem? Please describe.**
Unfortunately the troubleshooting section on https://nextcloud.com/collaboraonline/ states: 

> Issue: Collabora Online doesn't work with Encryption.
Yes, this is currently unsupported.

There is #190 and I suspect this is the same problem but maybe we have a different situation as we share documents among a team? (I am new to nextcloud and I am not sure if this is also implemented as end-to-end encryption or if a team-key is stored on the server).

**Describe the solution you'd like**
We use encryption within a group of people and would like to use collabora. 

**Describe alternatives you've considered**
none so far

**Additional context**
nextcloud is selfhosted and we have sudo rights (no need for me that this works on shared hosting)

**Comment by juliushaertl** [comment]
> (I am new to nextcloud and I am not sure if this is also implemented as end-to-end encryption or if a team-key is stored on the server).

E2E encryption can by design never work with Collabora.

> We use encryption within a group of people and would like to use collabora.

This should work with https://github.com/nextcloud/richdocuments/pull/52 if a master key is setup.
