### ISSUE TITLE
Regression: Nextcloud Favorites cannot be opened in Collabora CODE

### ISSUE THREAD

**Issue by gohrner** [nextcloud/richdocuments#630]
**Describe the bug**

Yesterday I upgraded Nextcloud to 15.0.11 and Richdocuments to "Collabora Online 3.4.2" and since then, I cannot open office documents in CODE via the NextCloud favorites any more... :-/

Opening the documents from the file list works fine.

**To Reproduce**
1. Make sure CODE and Richdocuments is configured correctly and works.
2. Mark an office document, (ODT, ODS, ...) as favorite
3. Open the favorite list
4. Click the office document in the favorite list

**Expected behavior**
The office document should be opened with CODE.

**What happens actually**
The left sidebar containing the favorites disappears, nothing else happens.

Additionally, an exception is written to the JavaScript console:

```
viewer.js?v=468ce161-11:44 Uncaught TypeError: Cannot read property 'shareOwnerId' of null
    at viewer.js?v=468ce161-11:44
    at Object.onEdit [as actionHandler] (viewer.js?v=468ce161-11:44)
    at action (merged-index.js?v=468ce161-11:10227)
    at FavoritesFileList._onClickFile (merged-index.js?v=468ce161-11:5353)
    at HTMLTableSectionElement.dispatch (core.js?v=468ce161-11:3)
    at HTMLTableSectionElement.r.handle (core.js?v=468ce161-11:3)
```

**Client details:**
 - OS: happens with  Linux and Windows
 - Browser: happens with Chrome and Firefox

## Server details

**Operating system**: Debian 9.10

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** 7.0.33 (Debian version)

**Nextcloud version:** 15.0.11

**Version of the richdocuments app**: 3.4.2

**Version of Collabora Online**: 4.0.5

**Comment by gohrner** [comment]
I manually downgraded Richdocuments to version 3.3.15 on my production system, and opening office documents from the favorites list works fine again. So it's very, very likely a regression in Richdocuments 3.4.x.

I did some further tests on my test system, and it looks as if opening a document from the favorites list actually works if the document is located in the root folder, but it fails for all documents located in subfolders...

![image](https://user-images.githubusercontent.com/26199042/65411900-5b95a700-ddee-11e9-8ebd-88aa6f11f488.png)

**Comment by juliushaertl** [comment]
Fixed by https://github.com/nextcloud/richdocuments/pull/651
