### ISSUE TITLE
Rename the app with a vendor neutral name

### ISSUE THREAD

**Issue by deneb-alpha** [nextcloud/richdocuments#639]
**The app name is not vendor neutral**
The old **richdocuments** **Documents** app was renamed to **Collabora Online** but in the reality it's possible to use it also with other LibreOffice Online servers than Collabora. The current name could bring the users to the misleading information that for integrating the online open source suite in Nextcloud it's mandatory to have a Collabora Online server instance.

**Proposal**
Instead of forking the app and maintain a clone with a vendor neutral name, rename the app to **LibreOffice Online** or to the old **Richdocuments** or **Documents** and join the efforts for maintaining it in a vendor neutral context.

**Comment by timar** [comment]
This was originally called ‘Documents’ which was targetted at WebODF, and is overly generic, the naming has evolved here to be clearer.

We call it Collabora Online to protect and build our brand which ensures that people know where the hard work has come from. That helps people when they look for a support partner, and helps us to re-invest into improving the Online functionality.

We don’t believe using the LibreOffice brand on this separate project would be appropriate here without TDF’s explicit permission, particularly as there are ongoing discussions around brand usage at TDF anyway to ensure vendor neutral use of the brand. Currently we do not have the rights to apply the LibreOffice trademark to new bits of software even if we wanted to. The LibreOffice Online brand is already used for the project and source code of the server software cf. https://www.libreoffice.org/download/libreoffice-online/

Of course it is possible to use Collabora Online’s integration with re-compiled and/or re-branded backends, we’re happy to note this in the application description of course.

Furthermore – if a vendor compiles their own version, we have that data in the /hosting/capabilities file served by Online – and this can be used to present a different brand in the settings if so required. Patches to improve that can be proposed.

Michael also wrote a long paper (with pictures) on Vendor Neutral Marketing which you can enjoy here: https://people.gnome.org/~michael/data/vendor-neutral-marketing.html and paints the larger picture.
