### ISSUE TITLE
Fix parameter overwriting template file

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/richdocuments#646]
From https://github.com/nextcloud/server/issues/14330#issuecomment-476339722

@juliushaertl @rullzer mind to have a look? This is a regression from https://github.com/nextcloud/server/pull/8051

If you try to return an exception like in the DocumentController you override the name of the template with the error class.

https://github.com/nextcloud/richdocuments/blob/6b8bea5c98ade491f4b64628dfaf8509925f6cfd/lib/Controller/DocumentController.php#L215-L226

https://github.com/nextcloud/server/blob/3f4941e48aead48bacc7077e2819b492d1394778/lib/private/Template/Base.php#L162-L188

![Screenshot from 2019-03-25 19-36-52](https://user-images.githubusercontent.com/3902676/54946172-c9444180-4f37-11e9-8f03-777ceace5a87.png)
![Screenshot from 2019-03-25 19-37-09](https://user-images.githubusercontent.com/3902676/54946171-c9444180-4f37-11e9-9567-968a59e927c0.png)

If we pass `file` as additionalParams the value `$file` (which should be the name of the template) is overriden. We try to use `CurlFactory` as error template than.

**Comment by juliushaertl** [comment]
We probably should also have handling for that case in the server.

**Comment by kesselb** [comment]
Ref https://github.com/nextcloud/richdocuments/pull/465

I think the above patch improved the situation a bit. At least we don't try to load CurlFactory as error template. 

- https://github.com/nextcloud/server/blob/ad7d13a87ceb5d20559808cad2c63c445ee4047c/lib/private/legacy/template.php#L318
- https://github.com/nextcloud/server/blob/ad7d13a87ceb5d20559808cad2c63c445ee4047c/lib/private/legacy/template.php#L283

We could use one of the linked methods to set a proper response code too. For now it returns the error page with 200er status. Sorry I missed that with #465 :see_no_evil:

**Comment by nickvergessen** [comment]
"Fix" is in https://github.com/nextcloud/server/pull/26718/commits/c856c089d3d5ec030e78f34626e4a33a20b868ea

Note: `$file` in templates will not work anymore `$_['file']` is fine.
