### ISSUE TITLE
WS Handler Error

### ISSUE THREAD

**Issue by kevdogg** [nextcloud/richdocuments#647]
**Describe the bug**
Error finding ws/wss handler

**To Reproduce**
1. Error Log 

**Expected behavior**
Opening doc file with richdocuments client -- The actual toolbars of LibreOffice will be displayed but the actual document doesn't display for a while then the page times out

**Screenshots**
No real screenshots to show

**Client details:**
 iphone 8, Chrome browser all the same error will occur if trying to debug with client such as wscat

## Server details

**Operating system**:  Linux 18.04 Ubuntu

**Web server:**
Server version: Apache/2.4.29 (Ubuntu)

**Database:**
mysql  Ver 15.1 Distrib 10.2.26-MariaDB, for FreeBSD11.2 (amd64) using readline 5.1

**PHP version:**
PHP 7.2.22 (cli) (built: Sep  5 2019 01:14:54) ( NTS )

**Nextcloud version:**
16.0.4

**Version of the richdocuments app**
No idea -- downloaded from within Nextcloud on 10-2-2019

**Version of Collabora Online**
Collabora/Docker Image pulled 10-1-2019 
<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Doesnt show up in Nextcloud logs
```

#### Browser log

`[Fri Oct 04 14:39:06.560742 2019] [proxy:warn] [pid 986:tid 140481862297344] [client 10.0.1.158:11400] AH01144: No protocol handler was valid for the URL /lool/https:%2F%2Fnextcloud.xxxx.com%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F707_ocny42d5quk3?access_token=3vSpnVrTNZloGcANH1XHB1t4pITxnjpH&access_token_ttl=0&reuse_cookies=__cfduid%3Dd51b54b2fbb6ab34ef2050f57406949d71569814012&permission=edit/ws (scheme 'ws'). If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule.
`

</details>

My setup is a little bit strange 
I'm running apache/nextcloud on one instance
and apache/collabora docker on another.  The log file posted above was from apache/collabora.  The apache within this instance acts as a reverse proxy and does the SSL handling.  Loaded apache modules on apache/collabora:

Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 mime_module (shared)
 mpm_event_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_balancer_module (shared)
 proxy_connect_module (shared)
 proxy_html_module (shared)
 proxy_http_module (shared)
 proxy_wstunnel_module (shared)
 reqtimeout_module (shared)
 setenvif_module (shared)
 slotmem_shm_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
 xml2enc_module (shared)

My virtual host file on apache/collabora is the following (relevant sections):

```
# static html, js, images, etc. served from loolwsd
  # loleaflet is the client part of LibreOffice Online
  ProxyPass /loleaflet http://127.0.0.1:9980/loleaflet retry=0
  ProxyPassReverse /loleaflet http://127.0.0.1:9980/loleaflet

  # WOPI discovery URL
  ProxyPass /hosting/discovery http://127.0.0.1:9980/hosting/discovery retry=0
  ProxyPassReverse /hosting/discovery http://127.0.0.1:9980/hosting/discovery

  # Capabilities
  ProxyPass /hosting/capabilities http://127.0.0.1:9980/hosting/capabilities retry=0
  ProxyPassReverse /hosting/capabilities http://127.0.0.1:9980/hosting/capabilities

  # Main websocket
  ProxyPassMatch "/lool/(.*)/ws$" ws://127.0.0.1:9980/lool/$1/ws nocanon

  # Admin Console websocket
  ProxyPass /lool/adminws ws://127.0.0.1:9980/lool/adminws

  # Download as, Fullscreen presentation and Image upload operations
  ProxyPass /lool http://127.0.0.1:9980/lool
  ProxyPassReverse /lool http://127.0.0.1:9980/lool
```

**Comment by juliushaertl** [comment]
The error message indicates that the ws:// handler is not working, are you sure the apache modules are loaded properly. Please check that again. The following modules are required: proxy, proxy_wstunnel, proxy_http, and ssl

For further setup questions please head over to https://help.nextcloud.com as the github track is only for feature requests and bug reports related to the integration.

**Comment by kevdogg** [comment]
They are enabled on both proxies that I use to get the connection -- hence why I'm reporting the bug:  I do web--> reverse proxy #1 (apache)----> reverse proxy #2 (apache)---> Docker collabora.
Modules in #1
```
 core_module (static)
 so_module (static)
 http_module (static)
 mpm_prefork_module (shared)
 authn_file_module (shared)
 authn_core_module (shared)
 authz_host_module (shared)
 authz_groupfile_module (shared)
 authz_user_module (shared)
 authz_core_module (shared)
 access_compat_module (shared)
 auth_basic_module (shared)
 socache_shmcb_module (shared)
 reqtimeout_module (shared)
 filter_module (shared)
 xml2enc_module (shared)
 proxy_html_module (shared)
 mime_module (shared)
 log_config_module (shared)
 log_debug_module (shared)
 logio_module (shared)
 env_module (shared)
 headers_module (shared)
 setenvif_module (shared)
 version_module (shared)
 remoteip_module (shared)
 proxy_module (shared)
 proxy_connect_module (shared)
 proxy_http_module (shared)
 proxy_fcgi_module (shared)
 proxy_uwsgi_module (shared)
 proxy_wstunnel_module (shared)
 ssl_module (shared)
 unixd_module (shared)
 status_module (shared)
 autoindex_module (shared)
 vhost_alias_module (shared)
 dir_module (shared)
 alias_module (shared)
 rewrite_module (shared)
```
Modules in #2 

```
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 mime_module (shared)
 mpm_event_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_balancer_module (shared)
 proxy_connect_module (shared)
 proxy_html_module (shared)
 proxy_http_module (shared)
 proxy_wstunnel_module (shared)
 reqtimeout_module (shared)
 setenvif_module (shared)
 slotmem_shm_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
 xml2enc_module (shared)
```
Can ws not traverse two reverse proxies?

**Comment by juliushaertl** [comment]
> Can ws not traverse two reverse proxies?

No idea, but why do you have two proxies?
