### ISSUE TITLE
"Go to last sheet" in calc only moves one sheet.

### ISSUE THREAD

**Issue by felixgonsug** [nextcloud/richdocuments#659]
### Steps to reproduce
1. Open a spredsheet with many sheets in collabora
2. Press "go to last" arrow

### Expected behaviour
Move to the last sheet

### Actual behaviour
The sheets bar only move by one sheet.

### Server configuration

**Operating system**:
Freebsd
**Web server:**
Nginx
**Database:**
Postgres
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
16.0.4
**Where did you install Nextcloud from:**
Fresh Ports

### Client configuration
**Browser:**
All browsers

**Comment by thebearon** [comment]
This tracker is for the Nextcloud connector app named Collabora Online. For issues in the product, please open a bug report at: https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online
