### ISSUE TITLE
Collabora Online administration view PHP error messages

### ISSUE THREAD

**Issue by TP75** [nextcloud/richdocuments#665]
**Describe the bug**
The _Collabora Online_ adminstration window in the GUI and the _richdocuments_ App show an unclear code performance and an instable behaviour with PHP error messages.

**To Reproduce**

The 3.4.2 version of the App was installed and enabled from earlier NC configuration.  The App was configured before and the Collabora Online environment is working successfully.

The behaviour in case A was already oberserved in earlier (15.0.11.1, 16.0.4.1) NC versions.  Only after upgrade to the NC 16.0.5.1 server and due to an explicit code-check on the commandline the issue #664 was observed.

The behaviour was observed from an Administrator user account.

##### Case A

No changes to the configuration of the App after upgrade to NC 16.0.5.1 server.

1. GUI go to 'Settings -> Administration'
2. Click on 'Collabora Online' to select the view
3. No other action in this view
4. See error list in 'Logging' view 

(see Case A in the Nextcloud **Logs**  below)

Only afterwards and due to a code-check the issue #664 was observed.

##### Case B

Due to the a.m. observation a more thorough re-installation of the App was performed to avoid side effects from possibly incomplete earlier installations.

Steps to perform the re-installation:

- set the maintenance mode to ON
- manual removal of the App

```
$ sudo -u www-data bash -c ' cd /var/www/nextcloud && php occ app:remove richdocuments '
Nextcloud is in maintenance mode - no apps have been loaded

richdocuments disabled
richdocuments removed
```
- stop the Web server
- perform the following steps by help of an independent directory as applicable
- manually fetch the current version from the App store
```
$ wget https://github.com/nextcloud/richdocuments/releases/download/v3.4.2/richdocuments.tar.gz
```

- manually make an installation of the App as applicable
```
$ tar xf richdocuments.tar.gz

$ sudo cp -a richdocuments /var/www/nextcloud/apps/
```
- set the correct ownership to the App files
- start the Web server
- manually enable the App
```
$ sudo -u www-data bash -c ' cd /var/www/nextcloud && php occ app:enable richdocuments '
Nextcloud is in maintenance mode - no apps have been loaded

richdocuments enabled
```
- set the maintenance mode to OFF again

1. Perform the a.m. installation procedure.
1. GUI go to 'Settings -> Administration'
1. Click on 'Collabora Online' to select the view
1. No other action in this view
1. See error list in 'Logging' view

(see Case B in the Nextcloud **Logs**  below)

##### Case C
1. Perform the a.m. installation procedure or just continue from case B.
1. GUI go to 'Settings -> Administration'
1. Click on the 'Apply' button of the _URL (and Port) of Collabora Online-server_ entry in the 'Collabora Online' view but without input or changes to the URL (which was pre-configured)
1. No further action in this view
1. See error list in 'Logging' view

(see Case C in the Nextcloud **Logs** below)

Nevertheless the access to the already configured _Collabora Online CODE_ server and editing efforts on documents continue without apparent hassle.

**Expected behavior**
The _Collabora Online_ adminstration window in the GUI and the _richdocuments_ App should show a reliable code performance and a stable behaviour without PHP error messages.

**Screenshots**
_n.a._

**Client details:**
_n.a._

## Server details

**Operating system:** Debian 10.1 Buster -- Linux cloudX 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux

**Web server:** apache2-bin/stable,stable,now 2.4.38-3+deb10u1 amd64

**Database:** mariadb-server-10.3/stable,now 1:10.3.17-0+deb10u1 amd64

**PHP version:** php7.3/stable,now 7.3.9-1~deb10u1 all

**Nextcloud version:** 16.0.5.1 and earlier (15.0.11.1, 16.0.4.1)

**Version of the richdocuments app:** 3.4.2

**Version of Collabora Online:** collabora / code : 4.0.6.1 from docker
DIGEST: 1b53e1119f92

<details>
<summary>Logs</summary>

##### Case A

```
[PHP] Error: Undefined index: installed_version at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69

GET /index.php/settings/admin/richdocuments
from <local ip addr> by admin at 2019-10-13T03:21:56+02:00


[PHP] Error: Undefined index: types at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69

GET /index.php/settings/admin/richdocuments
from <local ip addr> by admin at 2019-10-13T03:21:56+02:00


[PHP] Error: Undefined index: wopi_url at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69

GET /index.php/settings/admin/richdocuments
from <local ip addr> by admin at 2019-10-13T03:21:56+02:00
```

##### Case B
```
[PHP] Error: Undefined index: enabled at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69

GET /index.php/settings/admin/richdocuments
from <local ip addr> by admin at 2019-10-13T10:47:39+02:00


[PHP] Error: Undefined index: installed_version at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69

GET /index.php/settings/admin/richdocuments
from <local ip addr> by admin at 2019-10-13T10:47:39+02:00


[PHP] Error: Undefined index: types at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69

GET /index.php/settings/admin/richdocuments
from <local ip addr> by admin at 2019-10-13T10:47:39+02:00


[PHP] Error: Undefined index: wopi_url at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69

GET /index.php/settings/admin/richdocuments
from <local ip addr> by admin at 2019-10-13T10:47:39+02:00
```

##### Case C
```
[PHP] Error: Undefined index: disable_certificate_verification at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69

GET /index.php/settings/admin/richdocuments
from <local ip addr> by admin at 2019-10-13T11:57:08+02:00


[PHP] Error: Undefined index: enabled at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69

GET /index.php/settings/admin/richdocuments
from <local ip addr> by admin at 2019-10-13T11:57:08+02:00


[PHP] Error: Undefined index: installed_version at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69

GET /index.php/settings/admin/richdocuments
from <local ip addr> by admin at 2019-10-13T11:57:08+02:00


[PHP] Error: Undefined index: types at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69

GET /index.php/settings/admin/richdocuments
from <local ip addr> by admin at 2019-10-13T11:57:08+02:00


[PHP] Error: Undefined index: wopi_url at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69

GET /index.php/settings/admin/richdocuments
from <local ip addr> by admin at 2019-10-13T11:57:08+02:00
```

#### Browser log
_n.a._

</details>

**Comment by TP75** [comment]
May be related to [Strange APP-config-Issue, Logging-Errors #17139](https://github.com/nextcloud/server/issues/17139).  At least @rgl1234 [comment](https://github.com/nextcloud/server/issues/17139#issuecomment-531703932) lists similar log enties.

**Comment by juliushaertl** [comment]
Tracked in https://github.com/nextcloud/richdocuments/issues/641 fixed in https://github.com/nextcloud/richdocuments/pull/645
