### ISSUE TITLE
When using a bright theme color some icons doesnt invert the color. 

### ISSUE THREAD

**Issue by small1** [nextcloud/richdocuments#680]
**Describe the bug**
Using a to bright color as a theme color the icons to open the sidebar doesn't invert to dark. The Open a document. The icons to open the sidebar is still white and hart to find.

**To Reproduce**
1. Go to theing and set f2f2f2 as a color
2. Open a document
3. the icons to open the sidebar is white and not inverted.

**Expected behavior**
Icons should be inverted as all the others are.

**Screenshots**
![Screenshot from 2019-11-06 10-14-10](https://user-images.githubusercontent.com/317830/68284693-3dbe9180-007e-11ea-8dac-457956befebd.png)

**Client details:**
 - Device: [e.g. iPhone6, desktop]

## Server details

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:**

**Version of the richdocuments app**

**Version of Collabora Online**

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by nivadis** [comment]
same here with nc 20.0.1 and CODE 6.4-10
<img width="284" alt="Bildschirmfoto 2020-11-17 um 09 13 41" src="https://user-images.githubusercontent.com/814064/99364169-f2a4a480-28b5-11eb-98c7-30a4044b6bff.png">

**Comment by g1smo** [comment]
+1 here NC 20.0.5
![screenshot-2021-01-26-04:49:37](https://user-images.githubusercontent.com/4154450/105798295-27a63500-5f92-11eb-9fa8-29da2d9bc3a4.png)

Even more problematic is the text colour of sheets in the spreadsheet
![screenshot-2021-01-26-04:49:49](https://user-images.githubusercontent.com/4154450/105798305-2bd25280-5f92-11eb-8d94-d17a8a126261.png)
