### ISSUE TITLE
feature request: let external users without account set their display name in the user list

### ISSUE THREAD

**Issue by DanScharon** [nextcloud/richdocuments#69]
When a file is shared by link and made editable, an external user currently connected is only listed as an empty string within the users list.

Please make it possible for such external users to set their own display name.

**Comment by nithom** [comment]
We (@JonasBlaesche and me) started working on this. You can find the current state
[here](https://github.com/nextcloud/richdocuments/compare/master...JonasBlaesche:development#files_bucket) (until now, we only tested it with CODE 2.5 and Nextcloud 12).

If a document is shared via link and the recipient is also a logged in member
of this NC instance, nothing changes. If the recipient is not logged in or does
not have an account, a textbox is displayed.

When the user submits his/her name, a cookie is set and the name is stored
in an additional column in the WOPI token relation.

![nextcloud-user-nickname](https://user-images.githubusercontent.com/13665755/35358151-f4a51272-0155-11e8-9b18-968801aa2730.png)


As long as the cookie exists, the form is not shown again. This allows to
join multiple documents via share link with the correct guest name everywhere.

The guest user names get a prefix ("Guest: ") which is localized in the TokenManager.

Regarding localization: There already exists a `"Guest %s"` string for the guest ID, is
there a way to duplicate this to get the additional colon? Manually doing this
would get overwritten by Transifex, would it?

We'd appreciate some feedback on this. After further testing, we'll open a PR.

**Comment by errotu** [comment]
I really like the idea! Thanks for your work!

Nevertheless, I'm not sure if it's the best idea to create a "gate" before accessing the document. I think I'd prefer a possibility to set the name while being in the editing mode of the document. Another option is using the same form but only display it when someone tries to edit the document. Therefore, a only-reader wouldn't necessarily need to enter a nickname.

**Comment by JonasBlaesche** [comment]
We tried to implement it they way you prefer but failed on the collabora side.

We also have some code for the read only case but from our point this code is not very nice at the moment. Our current code makes a xmlHttp request to apps/richdocuments/public?... and parses the resulting HTML for the read/write permission.
Does anyone know if there is a nice way to get information about read/write permissions in the viewer.js.

**Comment by pranavk** [comment]
@JonasBlaesche Maybe you can move your 'enter nickname' logic to `documents.js` where you can already know the permission of the file from the exported variable `richdocuments_permissions` ?

**Comment by nithom** [comment]
@pranavk In the beginning, our logic was executed at a later point in `viewer.js`. This led to the issue that an empty guest joined and left while the name was set, and it didn't work with all browsers. As to my understanding the logic in `documents.js` is called even later, this would likely occur again. But we'll try it.

So it seems there is no existing API (e.g. from the Nextcloud share logic) we could use to get that information in `viewer.js` already? At least, we didn't find any suitable method so far.

**Comment by nithom** [comment]
Moving the logic to `documents.js` succeeded and now the input is only shown for guests with write permissions (see pull request).

The only downside is that an additional token with an empty guest name is created before a name can be entered (as the `documents.js` is executed after a token was obtained). When the cookie is present (i.e. on subsequent loads), only one token is created as usual. We didn't find a way to avoid the additional token, but as they are quite short-lived, this shouldn't be a problem?
