### ISSUE TITLE
Detect or let user choose CSV delimiter

### ISSUE THREAD

**Issue by msklywenn** [nextcloud/richdocuments#692]
**Is your feature request related to a problem? Please describe.**
Right now, nextcloud correctly detects that a CSV file should be opened with Collabora, but it doesn't tell Collabora how to open it. 

For example, if I try to open the controller element identifier list of Rewired, available at http://guavaman.com/rewired/files/docs/RewiredControllerElementIdentifiersCSV.zip It will fail to tell Collabora that the fields are separated with ',' rather than ';' or ':' and the file opens up like this:
![image](https://user-images.githubusercontent.com/1546678/68599828-96889280-04a1-11ea-9e74-f2efc4ec7ff3.png)

**Describe the solution you'd like**
An automatic detection of delimiters (inside nextcloud or collabora ?) would be wonderful but if on opening the file a dialog popped up, asking which delimiter should be used, it would be perfect already.

**Describe alternatives you've considered**
The only solution I see at the moment would be to convert the CSV file to another format with a different software.

**Additional context**
On opening CSV/TSV files, google sheets asks like this:
![image](https://user-images.githubusercontent.com/1546678/68599955-dd768800-04a1-11ea-8423-dec7be5f0454.png)

**Comment by thebearon** [comment]
Working with CSV files is special, as you normally only want to import data from CSVs, and want to continue working in the native format (otherwise the saved file will remain CSV). This workflow is currently missing.

However, if you open the CSV in a text editor, copy its contents, and paste in Collabora Online, you will get a nice CSV import dialog, where you can specify several import parameters.

**Comment by msklywenn** [comment]
Oh that's great! Thanks for the tip!

CSV files can end being up pretty big so that wouldn't always be 
practical. It would be nice if we could drag & drop the CSV file into an 
existing spreadsheet and have that same copy/paste behavior. But 
perhaps, this is a request I should do to the Collabora team?

**Comment by juliushaertl** [comment]
Closing as this is out of scope of the Nextcloud app.

**Comment by juliushaertl** [comment]
I assume it makes sense to open a feature request for that at https://github.com/collaboraonline/online
