### ISSUE TITLE
The latest release is not the latest

### ISSUE THREAD

**Issue by enoch85** [nextcloud/richdocuments#71]
In the Nextcloud VM scripts we fetch the latest release with Github API. This means that we currently fecth 1.11.28 when we really should fetch 1.12.28. This causes the script to fail becuase 1.11.28 is not compatible with Nextcloud 12. 

Please always release the latest version last. Thanks!

If possible, make a new release that's compatible with Nextcloud 12.

cc @timar

**Comment by timar** [comment]
OK, good to know!

**Comment by enoch85** [comment]
Just as a reference this is the "failing" version command: https://github.com/nextcloud/vm/blob/master/lib.sh#L74

**Comment by enoch85** [comment]
```
root@cloud:~# curl -s https://api.github.com/repos/nextcloud/richdocuments/releases | grep "tag_name" 
    "tag_name": "1.11.28",
    "tag_name": "1.12.28",
    "tag_name": "1.11.27",
    "tag_name": "1.12.27",
    "tag_name": "1.1.26-nc11",
    "tag_name": "1.1.26",
    "tag_name": "1.1.25",
    "tag_name": "1.1.24",
    "tag_name": "1.1.23",
    "tag_name": "1.1.22",
```

**Comment by enoch85** [comment]
@timar Can you please release 1.12.29? But release 1.11.29 first so that 1.12.29 become the "latest release"?

**Comment by timar** [comment]
I tried to do what you suggested, but in fact the time of the tag creation counts, not the time of actual release creation. Anyway, now the latest release is 1.12.29, because I removed 1.11.29. Next time I'll make the version 11 tag first.

**Comment by enoch85** [comment]
Thank you!
