### ISSUE TITLE
Updating to 1.12.29 fails

### ISSUE THREAD

**Issue by enoch85** [nextcloud/richdocuments#72]
Thanks for the new release, just one small issue:
![screenshot from 2017-05-25 00-29-12](https://cloud.githubusercontent.com/assets/4511254/26428303/32a84d18-40e1-11e7-97a2-ad0223ed5697.png)

**Comment by enoch85** [comment]
cc @timar

**Comment by jmgiacalone** [comment]
I have the same error. It appears the link is incorrectly specified:
`Client error response [url] https://github.com/nextcloud/richdocuments/releases/download/1.12.29/richdocuments.tar.gz [status code] 404 [reason phrase] Not Found`

**Comment by enoch85** [comment]
Aah, the issue is that there is no tar, I'll take the one from the previous version for now as a workaround.

**Comment by enoch85** [comment]
Aand now it works (but it should be a new tar file really)

**Comment by enoch85** [comment]
I patched the old release and uploaded the new tar, everything is fine now.

**Comment by enoch85** [comment]
Nope, still same error :/

**Comment by enoch85** [comment]
This is fixed with 1.12.30. Thanks @timar!
