### ISSUE TITLE
there is no way to select a range of cells in mobile version of spreadsheets

### ISSUE THREAD

**Issue by RuralYak** [nextcloud/richdocuments#722]
When a spreadsheet opened in mobile version of collabora code it is incredibly frustrating not to be able to select a range of cells. Usuall swipe gesture doe not work.

**Describe the solution you'd like**
Add a possibility to select a range of cells by dragging selection box by the handles which will apear automatically or by double tap

**Describe alternatives you've considered**
A separate selection management button could be a plan b

**Additional context**
Please consider this as it ruins the whole user experience

**Comment by thebearon** [comment]
This should be working in the unstable Collabora Online snapshots, see https://www.collaboraoffice.com/code/
