### ISSUE TITLE
Android writing don't work

### ISSUE THREAD

**Issue by yodatak** [nextcloud/richdocuments#724]
Like i said in this post:
https://help.nextcloud.com/t/text-entry-duplicated-nc16-collabora-on-android/57850/3
and this post:
https://help.nextcloud.com/t/collabora-writes-on-mobile-and-tablet-all-text-double/57133

Writing on android is not working , so nextcloud and collabora is unusable on android and i think its a verry bad issue , because its a great functionality against Microsoft Office

**Comment by thebearon** [comment]
Since this issue isn't related to the connector app for Collabora Online in Nextcloud, let's keep this bug report in [tdf#123437](https://bugs.documentfoundation.org/show_bug.cgi?id=123437).
