### ISSUE TITLE
Switch file creation based on TemplateSource entry in CheckFileInfo

### ISSUE THREAD

**Issue by thebearon** [nextcloud/richdocuments#732]
Let's track #514 in a bug report.

In the upcoming 4.2 version there is the issue during file creation that it fails, and the user gets stuck in the template (eg. `document.ott`). While the cause of the problem is likely not the existing template-based file creation, switching to the new method would trivially eliminate this particular case.

**Comment by juliushaertl** [comment]
Released with 3.5.0
