### ISSUE TITLE
Secure view is closable

### ISSUE THREAD

**Issue by jhesketh** [nextcloud/richdocuments#733]
**Describe the bug**
When sharing an image with "secure view" the document is closable which then displays the image as per normal and therefore able to be easily downloaded.

**To Reproduce**
1. Create a link share for an image
2. Set Hide Download
3. Open the link
4. Able to close the document viewer

**Expected behavior**
Being able to close collabora online should not be possible

**Comment by jhesketh** [comment]
Could this be at least triaged?

**Comment by juliushaertl** [comment]
The downloadable preview image is actually created by the server itself, so this is not a richdocuments issue. @jhesketh Please open an issue in https://github.com/nextcloud/server
