### ISSUE TITLE
Update to 1.12.29 fails

### ISSUE THREAD

**Issue by loxK** [nextcloud/richdocuments#74]
Nextcloud 12. The error in logs is "App with id richdocuments has invalid signature"

**Comment by khanasif2** [comment]
I am using Nextcloud 12 with Collabora 2.1 and Collabora App 1.12.28, everything is working fine. Today I saw there is an update for Collabora app Update to 1.12.29 so when I try to update it says Couldn't update app.
In the Nextcloud Admin panel in logging I see this error App with id richdocuments has invalid signature

**Comment by manmis** [comment]
Same here. After update to nextcloud 12 collabora didn't function anymore.
Cleared from all old stuff, that is removing even collabora container and image, removing app, setting up image and container anew, downloading app failed with: 

App with id richdocuments has invalid signature

**Comment by enoch85** [comment]
Dup of #72
