### ISSUE TITLE
Copying cells from a local Excel and pasting in collabora spreadsheet doesn't work!

### ISSUE THREAD

**Issue by MarketingProximidad** [nextcloud/richdocuments#75]
### Steps to reproduce
1. Copy cells from a local Excel file
2. Try to paste in collabora Spreadsheet document
3. Anything happens and paste option is disabled

### Expected behaviour
Paste data

### Actual behaviour
Don't paste anything

### Server configuration

**Operating system**: Linux Ubuntu 16.04

**Web server:** Apache 2

**Database:** Mysql 5.7.18

**PHP version:** 7.0.15, 

**Nextcloud version:** 11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**Fresh Install

**Where did you install Nextcloud from:** Nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

<?php
$CONFIG = array (
//  'debug' => true,
  'theme' => 'probox',
  'passwordsalt' => '*****************************************',
  'secret' => '*****************************************',
  'trusted_domains' => 
  array (
    0 => '*****',
    1 => '*****',
    2 => '*****',
    3 => '*****',
  ),
  'datadirectory' => '/var/ncdata',
  'overwrite.cli.url' => '**********************',
  'dbtype' => 'mysql',
  'version' => '11.0.3.2',
  'dbname' => 'nextcloud_db',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '******',
  'dbpassword' => '*******',
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => 'ocirzo17brjb',
  'appstore.experimental.enabled' => 'true',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauth' => 1,
  'mail_smtpport' => '25',
  'mail_smtphost' => '******',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'noreply',
  'mail_domain' => '*****',
  'mail_smtpname' => '*****',
  'mail_smtppassword' => '*****.',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => true,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0,
    'dbindex' => 0,
    'password' => '#Ja5FY7BYZ4f*jmSkIbGWYreO5HcSfX',
  ),
  'htaccess.RewriteBase' => '/',
  'mysql.utf8mb4' => true,
  'maintenance' => false,
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
);

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:**no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Google Chrome / Firefox

**Operating system:** Windows 10

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by caroberto6** [comment]
I have the same issue with Mac and copying more cells from Google spreadsheets. It works when I copy one cell.

**Comment by ionics** [comment]
Same issue here. Ubuntu 16.04 Server + Ubuntu 16.04 Chrome Browser and Firefox.

**Comment by corkerss** [comment]
This is still broken. no joy

**Comment by yelloff** [comment]
that's really a pity.

**Comment by PifPof73** [comment]
Same Issue. Still not fixed after one year???
Ubuntu 18.04, Apache2, php 7.2, docker container collabora/code stable, ownCloud 10.0.9 (stable)

**Comment by alebeta90** [comment]
Hello friends,

someone got a solution to this issue?

**Comment by thebearon** [comment]
Yup, this is fixed in 3.4.0.

**Comment by alebeta90** [comment]
@thebearon I check the updates regarding RichDocuments and I just got the notification to update to 3.0.3. Or what do you mean should be in 3.4.0 version?

Thanks

**Comment by alebeta90** [comment]
@thebearon I got it, is the version of CODE 3.4.0

Thanks!
