### ISSUE TITLE
Cannot save document from within Collabora that were opened through shared link.

### ISSUE THREAD

**Issue by noikin** [nextcloud/richdocuments#753]
**Describe the bug**
If office document is open throuht shared link, the document is opened and edited, but can't save (Message "the document can't be saved to storage. Check your permissions or contact the storage server administrator").
If this document opened by user logged in nextcoud (without granting rights to that file!) through shared link, document succsessfully saved.
See logs next.

**To Reproduce**
1. Create test.docx
2. Create shared link with edit rights.
3. Paste and open shared link to another pc/browser, not logged in NC
4. Edit file in Collabora interface. Click Save.
5. Popup message "the document can't be saved to storage. Check your permissions or contact the storage server administrator".

**Expected behavior**
Document must saved.

**Client details:**
 - Browser chrome 79, Edge
 - Device: Windows10

## Server details

**Operating system**:
Debian 10
**Web server:**
nginx
**Database:**
MariaDB 10.3.18-MariaDB-0+deb10u1-log
**PHP version:**
PHP 7.3.11-1~deb10u1
**Nextcloud version:**
NC 17.0.2
**Version of the richdocuments app**
Collabora Online 3.5.0
**Version of Collabora Online**
loolwsd 4.0.8-2 amd64 LibreOffice Online WebSocket Daemon
code-brand 4.0-2 all  Collabora Online Development Edition (CODE) branding

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
[index] Error: Exception: Argument 1 passed to OCA\Richdocuments\Service\UserScopeService::setUserScope() must be of the type string, null given, called in /home/alpha/www/apps/richdocuments/lib/Controller/WopiController.php on line 449 at <<closure>>

0. /home/alpha/www/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Richdocument ... {}, "putFile")
1. /home/alpha/www/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Richdocume ... r", "putFile", OC\AppFramework\ ... {}, {fileId: "6679_o ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({fileId: "6679_o ... "})
3. /home/alpha/www/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {fileId: "6679_o ... "})
4. /home/alpha/www/lib/base.php line 997
   OC\Route\Router->match("/apps/richdocum ... s")
5. /home/alpha/www/index.php line 42
   OC::handleRequest()

POST /index.php/apps/richdocuments/wopi/files/6679_oc86qmy9nngc/contents?access_token=gKFw4iLkfdWdFQy5fCQO4XXpCNO2mtSz&access_token_ttl=&permission=edit
from 192.168.128.106 at 2019-12-25T09:30:42+00:00

</details>

**Comment by yodatak** [comment]
Hi i got the same issue ,
Operating system:
Debian 10
Web server:
nginx
Database:
PG
PHP version:
PHP 7.3.11-1~deb10u1
Nextcloud version:
NC 17.0.2
Version of the richdocuments app
Collabora Online 3.5.0
Version of Collabora Online ( Docker 4.2 snapshot version)
LOOLWSD
master.. (git hash: ce9ec5f2)

LOKit
Collabora Office 6.2-2 (git hash: deaf934)

**Comment by yodatak** [comment]
I just test the fix of #755  it works !

**Comment by t-markmann** [comment]
#755 works perfectly, please merge :-)
