### ISSUE TITLE
Collabora cannot open federated file

### ISSUE THREAD

**Issue by rollanders** [nextcloud/richdocuments#769]
### Steps to reproduce
1. Share a file by federation from server 1
2. Open the shared file on server 2 with Collabora
3. Open same file on server 2 with OnlyOffice

### Expected behaviour
Collabora should open the file. 
Only Office should open the file

### Actual behaviour
When trying to open the file in Collabora I get an error "Failed to load Collabora Online Development Edition - please try again later"
The file opens normally in Only Office
Collabora can open other non-shared  files. 
I see no  related notes in the logs. 

This and similar errors have been closed. They dont seem to identical

## Server configuration detail

**Operating system:** Linux 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64

**Webserver:** nginx/1.17.6 (fpm-fcgi)

**Database:** mysql 10.4.10

**PHP version:** 

7.3.12-1+ubuntu18.04.1+deb.sury.org+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache

**Nextcloud version:** 17.0.2 - 17.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.10.1
 - admin_audit: 1.7.0
 - apporder: 0.9.0
 - calendar: 1.7.1
 - cloud_federation_api: 1.0.0
 - cms_pico: 1.0.4
 - comments: 1.7.0
 - contacts: 3.1.6
 - dav: 1.13.0
 - external: 3.4.1
 - federatedfilesharing: 1.7.0
 - federation: 1.7.0
 - files: 1.12.0
 - files_markdown: 2.1.0
 - files_pdfviewer: 1.6.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_trackdownloads: 1.6.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - gallery: 18.4.0
 - groupfolders: 5.0.5
 - issuetemplate: 0.6.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - mail: 0.21.1
 - nextbackup: 19.12.1
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - onlyoffice: 4.0.0
 - password_policy: 1.7.0
 - printer: 0.0.1
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - registration: 0.4.7
 - richdocuments: 3.5.1
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - spreed: 7.0.2
 - text: 1.1.1
 - theming: 1.8.0
 - twofactor_backupcodes: 1.6.0
 - updatenotification: 1.7.0
 - viewer: 1.2.0
 - workflowengine: 1.7.0
Disabled:
 - accessibility
 - circles
 - encryption
 - files_external
 - files_videoplayer
 - firstrunwizard
 - nextcloud_announcements
 - ojsxc
 - recommendations
 - support
 - survey_client
 - systemtags
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "korskyrkan-intra.dedyn.io"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "17.0.2.1",
    "overwrite.cli.url": "https:\/\/korskyrkan-intra.dedyn.io",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "activity_expire_days": 14,
    "auth.bruteforce.protection.enabled": true,
    "blacklisted_files": [
        ".htaccess",
        "Thumbs.db",
        "thumbs.db"
    ],
    "cron_log": true,
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\Movie",
        "OC\\Preview\\PDF",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown"
    ],
    "filesystem_check_changes": 0,
    "filelocking.enabled": "true",
    "htaccess.RewriteBase": "\/",
    "integrity.check.disabled": false,
    "knowledgebaseenabled": false,
    "logfile": "\/var\/nc_data\/nextcloud.log",
    "loglevel": 2,
    "logtimezone": "Europe\/Berlin",
    "log_rotate_size": 104857600,
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "overwriteprotocol": "https",
    "preview_max_x": 1024,
    "preview_max_y": 768,
    "preview_max_scale_factor": 1,
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "quota_include_external_storage": false,
    "share_folder": "\/Shares",
    "skeletondirectory": "",
    "theme": "",
    "trashbin_retention_obligation": "auto, 7",
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "ojsxc"
    ],
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36

**Operating system:** Windows 10

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Client details:**
 - Device: [e.g. iPhone6, desktop]

## Server details

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:**

**Version of the richdocuments app**

**Version of Collabora Online**

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
Please check the notes on federated editing in the README and verify that your setup matches the described requirements: https://github.com/nextcloud/richdocuments#federated-editing--global-scale

Other than that, I've added the fallback to local editing to 
 https://github.com/nextcloud/richdocuments/issues/761

**Comment by rollanders** [comment]
In server 2 (the local where I want to open the document)  the following requirements are fulfilled: 
- requires richdocuments version 3.4 on all involved servers. This is OK
- Make sure the remote server is added as a trusted server. OK

The last rquirement is tricky - Allow any domain to embed Collabora Online in a frame: <frame_ancestors>https://*</frame_ancestors> must be set in loolwsd.xml. 
I find four loolwsd.xml in the docker folder. In none of them I find any mention of  frame ancestors. . Where should it be placed?  And I find nothing in the admin  set up page. This is on server 2 - the local. The first server has the same setup. 

If OnlyOffice works, why not Collabora?

**Comment by timar** [comment]
<frame_ancestors> setting is in the loolwsd.xml, in the <net> section. By default it reads:
`<frame_ancestors desc="Specify who is allowed to embed the LO Online iframe (loolwsd and WOPI host are always allowed). Separate multiple hosts by space."></frame_ancestors>`
You can pass any config item through the docker command line with the `--extra-params`, see: https://www.collaboraoffice.com/code/docker/

**Comment by Gordonfreeman882** [comment]
Hey,
i have two NC 18.0.3 Servers federated through the federation App on both sites. Both working with the same Collaboraserver, which is added through the Collabora App in NC. Opening local files on the NCs work great. But open a file from NC A on NC B give me the error "Failed to load Collabora Online Development Edition - please try again later".

Richdocuments Version: 3.5.1
Collabora Online Development Edition installed a few days ago
Added: <frame_ancestors>http://*</frame_ancestors> in loolwsd.xml -> in my case i access the ncs and the loolwsd over http.

Help would be really appreciated  :+1:
