### ISSUE TITLE
Collabora Online app stopped working after upgrading to 1.12.30

### ISSUE THREAD

**Issue by elpraga** [nextcloud/richdocuments#77]
### Steps to reproduce
1. upgrade Collabora Online app to 1.12.30 on NC12.0.0

### Expected behaviour
App works and I can edit documents.

### Actual behaviour
Error page is shown instead.

### Server configuration
**Operating system**:
Ubuntu 17.04
**Web server:**
Apache
**Database:**

First `1.12.29` cannot be installed, now `1.12.30` breaks everything. Great.

**Comment by elpraga** [comment]
Disabling the app. erasing it, replacing it with `1.12.28`, and enabling it again made it work intermediately again.

**Comment by timar** [comment]
Sorry about that. In 1.12.30 we introduced encryption support, but we forgot to guard it, i.e. when the encryption module is not present, it should not try to invoke it. 1.12.31 release is on the way.

**Comment by JSoko** [comment]
Dupe: https://github.com/nextcloud/richdocuments/issues/76

**Comment by elpraga** [comment]
confirm, `1.12.31` works.

**Comment by pranavk** [comment]
Great, sorry for the trouble.
