### ISSUE TITLE
Bad mime type after editing xlsx file

### ISSUE THREAD

**Issue by ClCfe** [nextcloud/richdocuments#779]
Hello

Xlsx mime type seems to be altered by online editing

**Client details:**
Nextcloud 17.0.2 
app Collabora 3.5.1
Libre office online 4.0.9
Libre office core 6.0-36

**To Reproduce**
1) Upload a xlsx file in a folder

Check the mime type:
```
# file -bi "/opt/nextcloud/data/__groupfolders/8/Folder/file.xlsx"
 application/zip; charset=binary
```

2) Online edit with collabora richdocument & save

`192.168.103.54 - - [13/Jan/2020:11:22:19 +0100] "POST /index.php/apps/richdocuments/wopi/files/1257675_oc0udnyy6rxv/contents?access_token=bcHjd0zlyUifplYOzsHPhLfI99CYFK4z&access_token_ttl=0&permission=edit HTTP/1.1" 200 5387 "-" "LOOLWSD WOPI Agent 4.0.9"`

3) File mime type has changed

```
# file -bi "/opt/nextcloud/data/__groupfolders/8/Folder/file.xlsx"
application/octet-stream; charset=binary
```

this can implicate some problems for example with file acces control app if you do some filtering based on mime type (e.g. : disable access to .exe files)

**Comment by juliushaertl** [comment]
Is this also an issue outside of groupfolders? Which version of Nextcloud and groupfolders are you running?

**Comment by ClCfe** [comment]
Hello

Yes, same problem in my personnal folder

Nextcloud 17.0.2
Group folders	5.0.5

**Comment by juliushaertl** [comment]
Could you share one of the files with me both before and after their mimetype was changed?
