### ISSUE TITLE
Document Page does not fit with sidebar on small screen

### ISSUE THREAD

**Issue by davodego** [nextcloud/richdocuments#782]
**Document Page does not fit with sidebar on small screen**
When I open a document on my 15 inch laptop, the sidebar and document overlap. The icon to hide the sidebar is not visible. Scrolling also looks strange. 

**To Reproduce**
1. Open any possible document with the App on a small screen.

**Expected behavior**
The document and sidebars are clearly legible next to each other. The sidebar can be hidden.

**Screenshots**
![Screenshot_20200115_051615](https://user-images.githubusercontent.com/6584744/72404643-54f0be00-3756-11ea-9bbd-62084b31e6a7.png)
![Screenshot_20200115_051648](https://user-images.githubusercontent.com/6584744/72404646-591cdb80-3756-11ea-89ac-626cf426feec.png)

**Client details:**
 - OS: Manjaro
 - Browser Firefox
 - Version 72
 - Device: Sony Vaio Laptop

## Server details

**Operating system**: Ubuntu 18.04 LTS

**Web server:** Apache 2.4.29

**Database:** Maira DB 15.1

**PHP version:** PHP 7.2.24

**Nextcloud version:** 17.02

**Version of the richdocuments app:** 3.5.1

**Version of Collabora Online:** 4.2.0

**Comment by davodego** [comment]
Update for more.
When I click the button to open or hide the menu, the document scrolls up. It looks strange with the grey bar on top.

**Comment by thebearon** [comment]
This tracker is for the Nextcloud connector app named Collabora Online. For issues in the product, please open a bug report at: https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online

Please include your resolution in the bug report.
