### ISSUE TITLE
Ability to drag rows and columns into a new position

### ISSUE THREAD

**Issue by lgnch** [nextcloud/richdocuments#783]
**Is your feature request related to a problem? Please describe.**
Users often request an ability to drag a row or column and have it switch with another so that they can quickly move information around. In google docs the ability to quickly drag a row and switch its position has seen it become very popular, In excel the function is achieved by a cut and insert paste which drops the row down below the cut row.

**Describe the solution you'd like**
User has the ability to click on the row or column name, ie row 16, and drag it to swap with the chosen row. Example, drag row 16 and put above row 7 by dragging it to that location.

**Describe alternatives you've considered**
Google docs editor see section To move a row or column:
https://edu.gcfglobal.org/en/googlespreadsheets/modifying-columns-rows-and-cells/1/
Freeze row/column is also a handy feature.

**Additional context**
Sometimes you may want to move a column or row to make it more accessible in your spreadsheet. In our example, we'll move a column, but you can move a row in the same way.

Select the column you want to move, then hover the mouse over the column heading. The cursor will become a hand icon.

Selecting a column to move
Click and drag the column to its desired position. An outline of the column will appear.

Moving a column
Release the mouse when you are satisfied with the new location.

The moved column
![modifying_move_drag](https://user-images.githubusercontent.com/4876162/72489380-c4f76500-3878-11ea-9479-e406a2a82b92.png)
![modifying_move_select](https://user-images.githubusercontent.com/4876162/72489381-c4f76500-3878-11ea-8d0b-2fb70697fadc.png)
![modifying_move_result](https://user-images.githubusercontent.com/4876162/72489382-c4f76500-3878-11ea-891b-86f0ed0e4b71.png)

**Comment by juliushaertl** [comment]
This tracker is for the Nextcloud connector app named Collabora Online. For issues in the product, please open a bug report at: https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online

**Comment by lgnch** [comment]
This is not an issue in the product it is a feature request for the collabora online connector nextcloud app as the software already has it but your app does not do it.

**Comment by thebearon** [comment]
Not sure what you mean by "the software already has it", but please use the link provided by @juliushaertl for reporting the feature request.

**Comment by christiansass** [comment]
this still hasn't been addressed. can we reopen? I have submitted the issue to Bugzilla as well
https://bugs.documentfoundation.org/show_bug.cgi?id=130211
https://help.nextcloud.com/t/feature-request-drag-drop-reordering-of-rows-columns-in-collabora-nextcloud-office-25-x/233342

Hi all,

I noticed there are still no improvements to column/row reordering in the latest Collabora release (Nextcloud Office 25.x, COOLWSD 25.04.5.2). This was raised before back in early 2023
, but it seems to have gone quiet.

On the desktop version of LibreOffice Calc, you can Alt+Drag columns and rows to reorder them quickly. In Collabora, however, the only current methods are:

Sorting (not always useful if you want a custom order)

Cut + Insert Cut Cells

Copy + Delete + Paste

This is a 4-step process for something that should be as simple as drag-and-drop.

Given that a lot of recent updates have been focused on UI color themes and UX polish, it would be fantastic to see this basic spreadsheet functionality addressed. For those of us who work in spreadsheets daily, being able to drag and reorder rows/columns is a huge quality-of-life improvement.

Is there any roadmap update or active discussion on whether this is planned for Collabora Online?

Thanks,
Christian
