### ISSUE TITLE
Freezing rows and columns

### ISSUE THREAD

**Issue by lgnch** [nextcloud/richdocuments#784]
**Is your feature request related to a problem? Please describe.**
Users have requested the ability to freeze rows and columns

**Describe the solution you'd like**
The ability to select a row/column and then freeze the pain. This feature is already available in Libre office and it would be a nice feature to have in collabora online.

**Describe alternatives you've considered**
Google docs

**Additional context**
To freeze a row:
Locate the row or rows you want to freeze. In this example, we'll freeze the top two rows. Note: You do not need to select the rows you want to freeze.

Deciding which rows to freeze
Click View in the toolbar. Hover the mouse over Freeze, then select the desired number of rows to freeze from the drop-down menu.

Freezing rows
The top two rows are frozen in place. You can scroll down your worksheet while continuing to view the frozen rows at the top.

The frozen rows
To freeze a column:
Locate the column or columns you want to freeze. In this example, we'll freeze the leftmost column. Note: You do not need to select the columns you want to freeze.

Choosing which column to freeze
Click View in the toolbar. Hover the mouse over Freeze, then select the desired number of columns to freeze from the drop-down menu.

Freezing a column
The leftmost column is now frozen in place. You can scroll across your worksheet while continuing to view the frozen column on the left.

The frozen column
To unfreeze rows, click View, hover the mouse over Freeze, then select No rows. To unfreeze columns, click View, hover the mouse over Freeze, then select No columns.

Unfreezing a row

![modifying_freeze_column_menu](https://user-images.githubusercontent.com/4876162/72489569-4e0e9c00-3879-11ea-96b1-0b3d8bbb2faa.png)
![modifying_freeze_column_result](https://user-images.githubusercontent.com/4876162/72489570-4ea73280-3879-11ea-9d28-35510111af06.png)
![modifying_freeze_column_select](https://user-images.githubusercontent.com/4876162/72489571-4ea73280-3879-11ea-85ec-103fc89b078b.png)
![modifying_freeze_no](https://user-images.githubusercontent.com/4876162/72489572-4ea73280-3879-11ea-8d08-1880c4677397.png)

**Comment by juliushaertl** [comment]
This tracker is for the Nextcloud connector app named Collabora Online. For issues in the product, please open a bug report at: bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online

**Comment by lgnch** [comment]
This is not an issue in the product it is a feature request for the collabora online connector nextcloud app as the software already has it but your app does not do it.

**Comment by thebearon** [comment]
The connector app is not what you see on the screen, it's only responsible for letting Nextcloud and Collabora Online/CODE work with each other. The feature is missing from Collabora Online/CODE.

The feature request is already logged upstream: https://bugs.documentfoundation.org/show_bug.cgi?id=116858

**Comment by lgnch** [comment]
You are right, Thanks I will update it with the above details to assist its development. Thanks also for the clarity as I was not aware that the application was nothing more than a front end connection. I will post feature requests not directly related to the connector to the suggested forum,

**Comment by numeropi** [comment]
Here is the exact bug if somebody wants to cheer up or encourage the developers to have this implemented in Collabora Online. https://bugs.documentfoundation.org/show_bug.cgi?id=116858
