### ISSUE TITLE
Can not open LOOL document after Upgrade to NC18 Release, fileActions is undefined

### ISSUE THREAD

**Issue by ralfi** [nextcloud/richdocuments#793]
**Describe the bug**
Open LOOL document fails - No FileActions Registration (Error in Browser DevConsole)
Works until yesterday with NC 18RC
https://LOOL-FQDN/hosting/discovery works whitout errors

**To Reproduce**
1. Go to 'Create new doc' - missing LOOL extensions
2. Try open a LOOL document downloads it, not open LOOL
3. See error FileActions is undefined in the Browser Dev Console

**Expected behavior**
Open LOOL document in LOOL inside

**Screenshots**
See attachments

**Client details:**
 - OS: Debian Linux
 - Browser FF 72, Chrome 75
 - Device: Linux Desktop

## Server details

**Operating system**: Linux
**Web server:** Apache 2.4
**Database:** MySQL
**PHP version:** 7.3
**Nextcloud version:** 18 Docker 20.01.20 (18.0.0.10)
**Version of the richdocuments app** 3.5.1
**Version of Collabora Online** LOOL Latest Docker Image 

#### Nextcloud log (data/nextcloud.log)

Lot of
... "app":"no app in context","method":"POST","url":" ...
And
... /richdocuments/ajax/admin.php ... Deprecated event Type for \\OCP\\Files::preWrite ... Generic Event and \\OCP\\Files::\postWrite

No relevant entries in LOOL Server log.

![grafik](https://user-images.githubusercontent.com/294423/72732663-73abe600-3b96-11ea-80e5-33ac9bf18523.png)

**Comment by intellirat** [comment]
Hi
Had the very same problem - turned out to be 'Group folders' that was interfering for me - just disabling it was enough to restore Collabora click-actions.

**Comment by ralfi** [comment]
Cooool, disabling group folders ... and everything fine!

**Comment by Fin3** [comment]
yes, it is nice we've found a starting point, because the same is happening here,  but i can't really let the group folder disabled, it is used in production by a lot of ppl

**Comment by juliushaertl** [comment]
I don't see why groupfolders would have an effect on the file actions, however files_fulltextsearch seems to overwrite default file actions and with that break the one that richdocument registers: https://github.com/nextcloud/files_fulltextsearch/blob/master/js/files.js#L74-L113

cc @daita

**Comment by ralfi** [comment]
@juliushaertl You'r right but files_fulltextsearch without groupfolders works ...

**Comment by daita** [comment]
fixed in files_fulltextsearch 1.4.1
