### ISSUE TITLE
Document freezes after 3 pinch/spread zoom on mobile

### ISSUE THREAD

**Issue by rollanders** [nextcloud/richdocuments#804]
1. Open a document in Collabora
2. Pinch/spread zoom and move the document. 
3. After 2-3 such maneuvers, the document freezes. It cannot be moved around. Not be edited

Server: NC17.0.2 on Ubuntu 18.0.4 with Nginx. Collabora server in docker - latest version. 
App on server side: Collabora On Line 3.5.1

Mobile Browser: Default Chrome in Android.  This issue is not seen in Firefox in Android

**Comment by juliushaertl** [comment]
This tracker is for the Nextcloud connector app named Collabora Online. For issues in the product, please open a bug report at: https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online

**Comment by rollanders** [comment]
Thanks. A bug report has been submitted to Libreoffice. Can you be sure this is related to the LOOL server or the connector?
