### ISSUE TITLE
"Save as" not working

### ISSUE THREAD

**Issue by ebogaard** [nextcloud/richdocuments#806]
**Describe the bug**
When trying to save a document as another file with "Save as", no file is saved and no dialog/error is shown in the user interface.

**To Reproduce**
1. Open any (LIbre)Office file
2. Click "File" > "Save as"
3. Fill in a name (tried with and without extension) and click "Save"
4. No file is saved, no dialog is shown. There is only an error in the browser console (attached below).

The added complexity in our setup is that Collabora runs on domain "collabora.x.y", while Nextcloud runs on another domain "nextcloud.x.y".
I checked all headers the webserver adds and removed them all, so I don't add any additional headers that should create cross origin issues.

All other functionality works, including renaming the file by changing the filename in the top menu bar.

**Expected behavior**
I'd expect to see an extra file in Nextcloud with the new name.
Or, if "Save as" didn't work, I'd expect to see an error dialog.

**Screenshots**

**Client details:**
 - OS: Fedora, Windows
 - Browser Chrome, Firefox
 - Version latest versions
 - Device: Desktop

## Server details

**Operating system**:
Centos

**Web server:**
Apache httpd 2.4

**Database:**
Mariadb 10.2

**PHP version:**
7.3

**Nextcloud version:**
17.0.2

**Version of the richdocuments app**
3.5.1

**Version of Collabora Online**
collaboraoffice6.2-6.2.10.3-3.x86_64

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
Message in browser console when opening the document (so even before "Save as"):
```
SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data 2 loleaflet.html:21:20
    PostMessageReadyListener https://collabora.x.y/loleaflet/fafb01f/loleaflet.html?WOPISrc=https://nextcloud.x.y/index.php/apps/richdocuments/wopi/files/1686643_milfMhphAzlZ&title=aa.ods&lang=en-nl&closebutton=1&revisionhistory=1:21
```

Message in browser console when "Save as":
```
SecurityError: Permission denied to access property "origin" on cross-origin object bundle.js:54
    _postMessageListener https://collabora.x.y/loleaflet/fafb01f/bundle.js:54
    handler https://collabora.x.y/loleaflet/fafb01f/bundle.js:52

```

</details>

**Comment by lgnch** [comment]
Confirmed. Opening a new document saves as the document name first entered. User uses the save as function, query appears and enters the new name, document does not save, only the original name is maintained.

Problem can easily be replicated.

1 create a new document
2 enter some text
3 save
4 choose save as
5 enter name
6 document does not save you continue work in the original name and the new file is not saved in the directory.

Collabora online Version tested 3.5.1
CODE version 4.2.0

**Comment by lgnch** [comment]
More info.
Tested on LOOLWSD 4.0.5 with 3.5.1 and Collabora Office 6.0-29, issue is not present. This seems to be related to the new LOOLWSD 4.2.0 and Collabora Online 6.2-3.

**Comment by juliushaertl** [comment]
Yes, this is a known issue with loolwsd 4.2.0 and Collabora is working on it.

**Comment by yostral** [comment]
Hello.
Do you have a link for this issue at Collabora? Today I upgraded CODE to 4.2.2 and still no working "save as...".

Thanks a lot.

**Comment by JB1985** [comment]
For me it is only not work with Firefox 75.0 64bit (without addons).

With Chrome (81.0.4044.122) it works fine.

Can anybody confirm this? 

Lool: 4.2.0 (git hash b889fbbf)
LOKit: Collabora Office 6.2-4
Collabora Online: 3.5.3
Nextcloud: 18.0.4

**Comment by yostral** [comment]
I can confirm. It doesn't work with Firefox (74, 75, ESR...), but works with Chromium (81) and Gnome-Web (Epiphany).

**Comment by thebearon** [comment]
I haven't encountered anything like this recently, let's assume it's been fixed.
