### ISSUE TITLE
Display design collapse on smartphone

### ISSUE THREAD

**Issue by Bables55** [nextcloud/richdocuments#823]
I updated to Collabora 6.2.4 today. Then, an abnormality occurred in the display. This happens with spreadsheets and Writer(document). Occurrences in spreadsheet are much worse.

The display collapses when the user displays the keyboard and hides the keyboard. The file list(files of NC) is displayed at the bottom. This can happen as soon as the user presses the Collabora blue input mode button at the bottom right.

I'm not sure if this is a problem with NC's Collabora Online app or Collabora itself. 
*This update solves the problem of 2-byte character input on PC.

---
Nextcloud 18, Collabora Online 1.8.0, Collabora 6.2-4, loolwsd 4.2.0
iPhone 5s (iOS 12.4.4), iPhone SE, 8 (iOS 13.3.1)

**Comment by thebearon** [comment]
This is an old issue, reported before eg. in #476, unfortunately the implemented fix didn't solve the issue.

**Comment by Bables55** [comment]
If this Collabora window collapses, the user has to give up editing.

Of course, this problem does not occur with CollaboraOffice's iOS app. And the iOS version was recently updated. Perhaps the base of Collabora is closer to ver.6.2. It's a workaround because I can put it in Nextcloud volume from this app.

**Comment by juliushaertl** [comment]
The main issue here is that Safari does not change the frame height when the keyboard is shown and will scroll up the view automatically. We worked around this in the iOS app integration with some dirty hacks, but for accessing Collabora from the browser, I've no idea how this could be solved.

https://blog.opendigerati.com/the-eccentric-ways-of-ios-safari-with-the-keyboard-b5aa3f34228d provides some details on what is happening here.

**Comment by juliushaertl** [comment]
Should be fixed with #1514 and follow ups
