### ISSUE TITLE
Search function in spreadsheets - "r" character does not work

### ISSUE THREAD

**Issue by tintofish** [nextcloud/richdocuments#824]
Apologies if this should instead be reported upstream.

**Description**
In any spreadsheet document (xlsx, ods, new or existing) opened in CODE via Nextcloud, the "r" character does not function as expected when typed directly into the search bar at the bottom of the CODE interface. Instead, focus is pulled to the cells and repeated typing of the "r" cycles through cells, with the "r" never appearing in the search box. No other character causes this behaviour, only "r". 

Searching for "r" is still possible (and works as expected) through the Find & Replace dialog

This behaviour did not appear on previous versions, and has only been detected running on at least two separate instances with the following setup:
Nextcloud v17.0.3
Collabora Online app v3.5.2
with latest (v4.2.0.4) collabora/code docker image behind nginx proxy
(Client side on multiple browsers types on both Linux and Windows).

Thanks!

**Comment by juliushaertl** [comment]
Thanks for the report, I could reproduce this, however this seems to be bug in Collabora Online. Could you report it upstream at https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online?

**Comment by tintofish** [comment]
Thanks and done!
(https://bugs.documentfoundation.org/show_bug.cgi?id=130594)
