### ISSUE TITLE
Saves are not recognized as changes in nextcloud 

### ISSUE THREAD

**Issue by Pisoko** [nextcloud/richdocuments#825]
**Describe the bug**
When changing a office document in onlyoffice nextcloud don't recognize the change and the file is not synchronized.
To be clear - the change is there - but don't triggers a sync because nextcloud don't know about it.
(it is independent from if a file is shared or not)

**To Reproduce**

1. Create a new office document
2. Change it - save it
3. wait some minutes
4. open the file again - change it - save it
5. nextcloud still shows the old (from (2) ) date of last modification
--> No sync is triggered.

You need to rename the file to trigger the sync.

## Server details

**Operating system**: Ubuntu 18.04.3

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.2

**Nextcloud version:** 16.0.7

**Version of the richdocuments app** 

**Version of Collabora Online** latest

Thx

**Comment by juliushaertl** [comment]
This is the issue tracker for the collabora online integration, but to answer your question, onlyoffice currently only saves if all users have closed the document.
