### ISSUE TITLE
sharing external storage and collabora files

### ISSUE THREAD

**Issue by ghost** [nextcloud/richdocuments#83]
### Steps to reproduce
1. Create Folder on external storage (sftp in my case)
2. Share that folder via link with write / upload permissions
3. Open that link in another tab
4. Hit the + button and click "new document" (test.odt)
5. "new document" has been created
6. Try to edit that document
7. Internal server error (actually the test.odt resides in the root folder of the user NOT in the external storage folder)

### Expected behaviour
I would expect that the created test.odt is in the external storage folder and can be edited.

### Actual behaviour
Internal server error.

### Server configuration

**Operating system**:
Linux

**Web server:**
Apache 2.4.25

**Database:**
MariaDB

**PHP version:**
7.1.5

**Nextcloud version:** (see Nextcloud admin page)
12.0.0

thanks and cheers

**Comment by busted-it-guy** [comment]
I have started a thread with this issue.  No one has responded but it is very similar.  I can get editing working fine with external storage but ONLY if the user is logged in.  If they use the "share link" option with read or read/write, I get the Unauthorized WOPI host.  Previously I would get the internal server error but the way I got around that was to mount a share local with chmod 766 (fstab with dir_mode and file_mode)

My issue is here:

https://help.nextcloud.com/t/unauthorized-wopi-host-using-share-link-on-any-files-folders-connected-via-the-external-storage-support-app/13423/7
