### ISSUE TITLE
Collabora typing not possible when saving document

### ISSUE THREAD

**Issue by VincentSC** [nextcloud/richdocuments#831]
**Describe the bug**
For 10 to 12 seconds it is not possible to type when the document is (auto) saved. Moving cursor neither works. Scrolling does work.

How can I debug this? I don't even know if this is caused by MySQL, Docker, Collabora, NextCloud or something else.

**To Reproduce**
1. Open document
2. Press save
3. Try to type or move the cursor - does not work for 10-12 seconds. 

**Expected behavior**
That saving does not disallow typing or moving the cursor.

**Screenshots**
N/A

**Client details:**
 - OS: Windows, Linux, OSX
 - Browser: Chrome, Firefox
 - Device: Desktop

## Server details

**Operating system**: Ubuntu 18.04.4 LTS

**Web server:** Nginx 1.14.0

**Database:** ysqld  Ver 5.7.29-0ubuntu0.18.04.1

**PHP version:** PHP 7.2

**Nextcloud version:** 18.0

**Version of the richdocuments app** Don't know

**Version of Collabora Online**: latest Docker

**Comment by juliushaertl** [comment]
Could you check the browser console, especially the network tab, if there is some requests going on during that time? Is just the collabora UI hanging or the whole browser tab?

**Comment by VincentSC** [comment]
Ah, I think I was not using the right words. So "UI hangs" is wrong. It should be "cannot type any text". I will update the ticket

**Comment by VincentSC** [comment]
Not sure if this could be a hint?

> {"reqId":"blSVbhrLKbsiqu4HhkEw","level":3,"time":"2020-02-19 19:24:36","remoteAddr":"62.251.112.99","user":"vincent","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":{"Exception":"TypeError","Message":"Argument 1 passed to OCA\\Sentry\\AppInfo\\Application::registerClient() must be of the type string, null given, called in /var/www/sites/xxx/nextcloud/apps/sentry/lib/AppInfo/Application.php on line 53","Code":0,"Trace":[{"file":"/var/www/sites/xxx/nextcloud/apps/sentry/lib/AppInfo/Application.php","line":53,"function":"registerClient","class":"OCA\\Sentry\\AppInfo\\Application","type":"->","args":[null]},{"file":"/var/www/sites/xxx/nextcloud/lib/private/ServerContainer.php","line":107,"function":"__construct","class":"OCA\\Sentry\\AppInfo\\Application","type":"->","args":[]},{"file":"/var/www/sites/xxx/nextcloud/lib/private/ServerContainer.php","line":133,"function":"getAppContainer","class":"OC\\ServerContainer","type":"->","args":["sentry","Sentry"]},{"file":"/var/www/sites/xxx/nextcloud/apps/sentry/appinfo/app.php","line":28,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OCA\\Sentry\\AppInfo\\Application"]},{"file":"/var/www/sites/xxx/nextcloud/lib/private/legacy/app.php","line":266,"args":["/var/www/sites/xxx/nextcloud/apps/sentry/appinfo/app.php"],"function":"require_once"},{"file":"/var/www/sites/xxx/nextcloud/lib/private/legacy/app.php","line":155,"function":"requireAppFile","class":"OC_App","type":"::","args":["sentry"]},{"file":"/var/www/sites/xxx/nextcloud/lib/private/legacy/app.php","line":128,"function":"loadApp","class":"OC_App","type":"::","args":["sentry"]},{"file":"/var/www/sites/xxx/nextcloud/ocs/v1.php","line":54,"function":"loadApps","class":"OC_App","type":"::","args":[["authentication"]]},{"file":"/var/www/sites/xxx/nextcloud/ocs/v2.php","line":24,"args":["/var/www/sites/xxx/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/sites/xxx/nextcloud/apps/sentry/lib/AppInfo/Application.php","Line":68,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0","version":"18.0.0.10"}

**Comment by juliushaertl** [comment]
That seems unrelated. As mentioned, could you check the browser console as well?

**Comment by VincentSC** [comment]
We've replaced Collabora by OnlyOffice
