### ISSUE TITLE
Can't copy and paste from external smartphone apps

### ISSUE THREAD

**Issue by Bables55** [nextcloud/richdocuments#832]
**Describe the bug**
Users can't copy text in emails, notes, or web browsers and paste it into Collabora.
Copy and paste inside Collabora is possible.

**To Reproduce**
1. Copy something in the smartphone app.
2. Open the file in Collabora from web browsers or Nextcloud app.
3. The user touches the screen for a long time to paste.
4. The user is prompted to work with the on-screen keyboard. 
- Please use the copy/paste buttons on your on-screen keyboard.
5. There is no on-screen keyboard or icon.

**Expected behavior**
Users can paste text with the OS paste function.

**Client details:**
 - OS: [e.g. iOS] iOS 13.3.1, 12.4.4
 - Browser [e.g. chrome, safari] Safari, iCab, Nextcloud 2.25.9.2
 - Device: [e.g. iPhone6, desktop] iPhone

## Server details

**Operating system**:
CentOS 7.7
**Web server:**
nginx 1.16.1
**Database:**
MariaDB 10.2.29
**PHP version:**
PHP7.3.14
**Nextcloud version:**
18.0.1
**Version of the richdocuments app**
loolwsd 4.2.0, Collabora 6.2-4
**Version of Collabora Online**
3.5.2

**Comment by juliushaertl** [comment]
This tracker is for the Nextcloud connector app named Collabora Online. For issues in the product, please open a bug report at: https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online

**Comment by Bables55** [comment]
> This tracker is for the Nextcloud connector app named Collabora Online. For issues in the product, please open a bug report at: https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online

So which side is this?
When I open a Collabora document from NC and display the iOS keyboard, the window collapses and the NC file list appears at the bottom of the screen.
