### ISSUE TITLE
111111

### ISSUE THREAD

**Issue by li2313561** [nextcloud/richdocuments#838]
TypeError: Return value of OCA\Richdocuments\Service\UserScopeService::setFilesystemScope() must be an instance of OCA\Richdocuments\Service\void, none returned/var/www/nextcloud/apps/richdocuments/lib/Controller/WopiController.php - line 396:OCA\Richdocuments\Service\UserScopeService->setFilesystemScope("admin")/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166:OCA\Richdocuments\Controller\WopiController->putFile("154806", "A2XIfrl9nWy ... v")/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:OC\AppFramework\Http\Dispatcher->executeController(OCA\Richdocu ... {}, "putFile")/var/www/nextcloud/lib/private/AppFramework/App.php - line 118:OC\AppFramework\Http\Dispatcher->dispatch(OCA\Richdocu ... {}, "putFile")/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:OC\AppFramework\App::main("OCA\\Richdo ... r", "putFile", OC\AppFramew ... {}, { fileId: "1 ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ fileId: "1 ... "})/var/www/nextcloud/lib/private/Route/Router.php - line 297:call_user_func(OC\AppFramew ... {}, { fileId: "1 ... "})/var/www/nextcloud/lib/base.php - line 987:OC\Route\Router->match("/apps/richd ... s")/var/www/nextcloud/index.php - line 42:OC::handleRequest()
--

**Comment by thebearon** [comment]
Probably solved by this commit: 2b4366a996c2bead73bba731c8e98874ddb67e61
As a workaround you can install PHP 7.1+.

**Comment by li2313561** [comment]
Thank you

**Comment by li2313561** [comment]
@thebearon  thank you
