### ISSUE TITLE
Freeze Rows and Columns

### ISSUE THREAD

**Issue by mattiaaeternity** [nextcloud/richdocuments#839]
**Is your feature request related to a problem? Please describe.**
I'm not able to freeze rows and columns in my spreadsheets.

**Describe the solution you'd like**
I'd like to be able to freeze certain rows and columns in order to work more efficiently on larger spreadsheets.

<img width="474" alt="Screenshot 2020-02-25 at 12 01 39" src="https://user-images.githubusercontent.com/43239393/75241584-a44ef300-57c6-11ea-8cc4-4ebf3724fc32.png">

**Comment by thebearon** [comment]
This has reported in the following feature request:
https://bugs.documentfoundation.org/show_bug.cgi?id=116858
