### ISSUE TITLE
document shared via link cannot be saved by external users with the save button

### ISSUE THREAD

**Issue by DanScharon** [nextcloud/richdocuments#84]
### Steps to reproduce
1. share a document via link (share its folder via share link and allow its editing)
2. the external user opens the document via link and edits the document
3. the external user clicks on the save button 

### Expected behaviour
The document is saved

### Actual behaviour
1. the external user gets the following message:

> Document cannot be saved to storage. Check your permissions or contact the "
"storage server administrator.

2. the document is not saved

This happens in Nextcloud 11.0.3 and 12.0.0

Collabora Online versions: 1.11.31 and 1.12.31 respectively

The following is logged within docker logs:

`wsd-00025-02754 15:44:35.709920 [ docbroker_113 ] ERR  Failed to save docKey [/index.php/apps/richdocuments/wopi/files/1691272_oc200xxrs5cv] to URI [https://<redacted>/index.php/apps/richdocuments/wopi/files/1691272_oc200xxrs5cv?access_token=nxR9QpNpmlbQic6JtgZGhCU6hX2UJCWm&access_token_ttl=0&permission=edit]. Notifying client.| wsd/DocumentBroker.cpp:672`

**Comment by pranavk** [comment]
Thanks for the report.
