### ISSUE TITLE
Spreadsheets have been freezing up

### ISSUE THREAD

**Issue by mattiaaeternity** [nextcloud/richdocuments#842]
**Describe the bug**
My spreadsheets have been freezing up and make it impossible to work on them reliably.

**To Reproduce**
1. Go to any spreadsheet
2. Start editing
3. The spreadsheet freezes
4. The spreadsheet appears blank once re-entering

**Expected behavior**
Spreadsheets should work smoothly.

**Screenshots**
<img width="1439" alt="Screenshot 2020-02-28 at 12 12 43" src="https://user-images.githubusercontent.com/43239393/75544144-a661bd80-5a23-11ea-8e7b-454168fa50f6.png">

**Client details:**
 - OS: MacOS
 - Browser: Brave (Chromium)
 - Version: 80.0.3987.116)
 - Device: MacBook Pro

## Server details

**Operating system**:
Ubuntu 18.04.4 LTS

**Web server:**
nginx/1.14.0 (Ubuntu)

**Database:**

**PHP version:**

**Nextcloud version:**
17.0.2.1

**Version of the richdocuments app**

**Version of Collabora Online**
latest Docker

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```

#### Collabora docker log
http://paste.ubuntu.com/p/rVCMNQncXc/


#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
Please fill out the complete issue template, especially checking the log files as otherwise there is no way we can guess what is going wrong here.

**Comment by strasharo** [comment]
@juliushaertl missing info filled in, so far we have the Collabora logs available on the pastebin we added, trying to obtain a copy of the Nextcloud one too. Is the Colllabora docker log of any use for the troubleshooting?

**Comment by strasharo** [comment]
Is there any other info that we may provide in order to contribute to the troubleshooting?

**Comment by juliushaertl** [comment]
```
[1m[31mwsd-00027-00035 2020-02-27 14:54:56.628092 [ websrv_poll ] ERR  Unknown resource: /hosting/capabilities| wsd/LOOLWSD.cpp:2261[0m

[1m[31mwsd-00027-00132 2020-02-27 14:56:28.381027 [ docbroker_005 ] ERR  Socket #18 SSL error: SYSCALL (5). (EPIPE: Broken pipe)| ./net/SslSocket.hpp:238[0m
[1m[31mwsd-00027-00132 2020-02-27 14:56:28.381168 [ docbroker_005 ] ERR  #18: Socket write returned -1 (EPIPE: Broken pipe)| ./net/Socket.hpp:1104[0m
[1m[31mwsd-00027-00132 2020-02-27 14:56:28.381305 [ docbroker_005 ] ERR  Socket #18 SSL BIO error: error:1420C0CF:SSL routines:ssl_write_internal:protocol is shutdown (ENOTCONN: Transport endpoint is not connected)| ./net/SslSocket.hpp:291[0m
[1m[31mwsd-00027-00132 2020-02-27 14:56:28.381516 [ docbroker_005 ] ERR  Error while handling poll for socket #18 in docbroker_005: error:1420C0CF:SSL routines:ssl_write_internal:protocol is shutdown| ./net/Socket.hpp:594[0m
[1m[31mwsd-00027-00132 2020-02-27 14:56:28.381763 [ docbroker_005 ] ERR  No socket associated with WebSocketHandler 0x7fb3d0031450| ./net/WebSocketHandler.hpp:131[0m
```

Those look interesting, could you check if your reverse proxy is properly configured to access the hosting capabilities route and forward web socket requests?

**Comment by strasharo** [comment]
I'm using the sample configuration from here:

https://www.collaboraoffice.com/code/nginx-reverse-proxy/

```
server {
    listen       443 ssl;
    server_name  <scrubbed>;
    server_tokens off;
    #more_clear_headers Server;
    more_set_headers 'server: cloudflare';
    error_page 401 403 404 /404.html;
    client_max_body_size 1024M;

    ssl_certificate /etc/letsencrypt/live/<scrubbed>/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<scrubbed>/privkey.pem;

    # static files
    location ^~ /loleaflet {
        proxy_pass https://localhost:9980;
        proxy_set_header Host $http_host;
    }

    # WOPI discovery URL
    location ^~ /hosting/discovery {
        proxy_pass https://localhost:9980;
        proxy_set_header Host $http_host;
    }

    # Capabilities
    location ^~ /hosting/capabilities {
        proxy_pass https://localhost:9980;
        proxy_set_header Host $http_host;
    }

    # main websocket
    location ~ ^/lool/(.*)/ws$ {
        proxy_pass https://localhost:9980;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $http_host;
        proxy_read_timeout 36000s;
    }

    # download, presentation and image upload
    location ~ ^/lool {
        proxy_pass https://localhost:9980;
        proxy_set_header Host $http_host;
    }

    # Admin Console websocket
    location ^~ /lool/adminws {
        proxy_pass https://localhost:9980;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $http_host;
        proxy_read_timeout 36000s;
    }
}
```

Have I missed something there?

**Comment by juliushaertl** [comment]
Looks fine in general. Just beause of `more_set_headers 'server: cloudflare';` - is cloudflare involved anywhere in the connection to your server?

**Comment by strasharo** [comment]
Nope, just obscuring the banner against crawlers, Cloudflare is not involved at all in the setup.
