### ISSUE TITLE
Custom styles in conditional formatting are lost if saved as xlsx

### ISSUE THREAD

**Issue by errotu** [nextcloud/richdocuments#849]
**Describe the bug**
Custom styles which have been added as part of a conditional formatting are lost if the spreadsheet is saved as xlsx, not as ods.

This bug seems to have appeared with the release of CODE 4.2.0.

**To Reproduce**
1. Open xslx file with CODE
2. Click on 'Format -> Conditional -> Manage -> Add'
3. Click on 'Choose Style -> Additional Style'
4. Add a custom style
5. Save and close document
6. Open document; the custom individual style has been replaced by one of the default styles

**Expected behavior**
The custom individual style should not be lost after the document is closed.

**Client details:**
 - OS: Ubuntu
 - Browser: Firefox 
 - Version: 73
 - Device: desktop

**Comment by thebearon** [comment]
This tracker is for the Nextcloud connector app named Collabora Online. For issues in the product, please open a bug report at: https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online
