### ISSUE TITLE
White cells on calc when editing

### ISSUE THREAD

**Issue by unteem** [nextcloud/richdocuments#850]
**Describe the bug**
On a spreadsheet when selecting a cell to edit, some users do not see its content but a white cell. While the content is still visible on the top toolbar it can get a bit disturbing :)

**To Reproduce**
I have not been able to reproduce it yet as it does not happen systematically. I'll provide more info when I can replicate on my device.

**Expected behavior**
Content should be visible while editing the cell

**Client details:**
 - Browser: Firefox 68.5.0 ESR
## Server details
NC 16
Richdocuments 3.5.1
Collabora CODE 4.2.0

**Comment by thebearon** [comment]
This tracker is for the Nextcloud connector app named Collabora Online. For issues in the product, please open a bug report at: https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online
