### ISSUE TITLE
Nextcloud Android/IOS App ignores settings for limited access to LO-online

### ISSUE THREAD

**Issue by scroom** [nextcloud/richdocuments#851]
**Describe the bug**
As described above. We've installed the test version of LibreOffice-Online (docker) on our server and limited the access to a group of people (LDAP). If the users are using Nextcloud in the browser the limitation works. But if our users are using the Nextcloud app, the limitation is not working which means that all users can access the LibreOffice-Online-app, which is not desired.

**To Reproduce**
1. Install LO-online via docker and configure Nextcloud
2. limitate the access to a certain group of users

**Expected behavior**
The access is limited to the configured group.

**Client details:**
 - OS: IOS, Android
- Nextcloud App

## Server details

**Operating system**: Ubuntu 18.04

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7.2

**Nextcloud version:** 17.0.3

**Version of the richdocuments app** 3.5.2

**Version of Collabora Online** 6.2-4

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Nothing relevant in the log
```

**Comment by joshtrichards** [comment]
Fixed in #2328
