### ISSUE TITLE
Collabora new file in /0

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/richdocuments#857]
From iOS Nextcloud, if I create a new Collabora file in the directory 0/ the file is create in /

@tobiasKaminsky can you make a test ?

-1 create a new directory in root with the name 0 (zero) 
-2 enter in zero and here create a new document file with collabora
-3 close collabora and verify where the file has been created, in "/0" or in root "/"

**Comment by tobiasKaminsky** [comment]
Works fine here on Android:
/0/test.odt was created

https://github.com/nextcloud/android/blob/adae2e48da5464b3b3c33b96eedcfcd85a326492/src/main/java/com/owncloud/android/files/CreateFileFromTemplateOperation.java#L59

Path is absolute path.
Post method has setContentCharset("utf-8")

**Comment by marinofaggiana** [comment]
Thanks Toby I will try to understand where the problem is !

**Comment by juliushaertl** [comment]
@marinofaggiana Did you manage to find the issue?
