### ISSUE TITLE
Cannot copy-paste on Android

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/richdocuments#870]
If i open and edit a document on Android and i copy some data from it and i want to paste by long pressing and selecting the app's built in "paste" menu, i get the message that "Your browser has limited access to clipboard and use the copy and paste buttons from the keyboard". 
At this point i have no option, even tried keyboards that have ctrl keys and pressed ctrl-v but that didn't work.

1. Open a document (odt, docx)
2. Copy something from it
3. Try pasting

**Expected behavior**
The text gets pasted somehow

**Client details:**
 - OS: Android
 - Browser Android app
 - Version 9
 - Device: Xiaomi A1

## Server details

**Operating system**:
Debian stable
**Web server:**
Nginx
**Database:**
Mariadb
**PHP version:**
7.3
**Nextcloud version:**
18.03
**Version of the richdocuments app**
3.5.2
**Version of Collabora Online**
6.2.10.6-6

**Comment by juliushaertl** [comment]
This tracker is for the Nextcloud connector app named Collabora Online. For issues in the product, please open a bug report at: https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online
