### ISSUE TITLE
Drop down button (arrow) can not be activated

### ISSUE THREAD

**Issue by brtptrs** [nextcloud/richdocuments#871]
**Describe the bug**
Some users (Firefox on Linux not) can not click the arrow for a drop-down list.

**To Reproduce**
1. Go to cell linked to a range of cells as with "valid values"
2. Click on the arrow to open the drop-down list
3. Instead of the drop-down you end up moving to the cell below the cursor

**Expected behavior**
Hit the Arrow and a drop-down list opens

**Screenshots**

![grafik](https://user-images.githubusercontent.com/8102905/77787901-9c51cf80-7060-11ea-9893-90d4d49ea4f9.png)

![Peek 2020-03-27 19-13-collabora](https://user-images.githubusercontent.com/8102905/77787603-146bc580-7060-11ea-9dee-17a422976163.gif)

**Client details:**
 - OS: Windows 10
 - Browser. Chrome and Firefox
 - Device: Notebook
## Server details

**Operating system**:
CentOS
**Web server:**
Apache
**Database:**
MySql
**PHP version:**
7.2
**Nextcloud version:**
18.0.3

**Version of the richdocuments app**
3.5.2

**Version of Collabora Online**

LOOLWSD
4.2.0 (git hash: 48938d4)

LOKit
Collabora Office 6.2-6 (git hash: 7c4bddd)

**Comment by juliushaertl** [comment]
This tracker is for the Nextcloud connector app named Collabora Online. For issues in the product, please open a bug report at: https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online
