### ISSUE TITLE
remove document name in toolbar

### ISSUE THREAD

**Issue by schiessle** [nextcloud/richdocuments#882]
Not sure if this is the right place or if this should go directly to Collabora.

Maybe I'm the only one, but the document filename in the toolbar always feels wrong to me. Every time I see it, I ask myself "why?". The different font, size and the input field just feels out of place.

![image](https://user-images.githubusercontent.com/1589737/77921636-4ff4d280-72a0-11ea-9fd2-96dfa0e9de4c.png)

This looks so much better and more polished:

![image](https://user-images.githubusercontent.com/1589737/77921763-7a469000-72a0-11ea-807a-daa6bbb9ca7c.png)

The document name is already visible in the browser titlebar which is imho the perfect place and the document can already be renamed with "File -> Save as...". Therefore I don't see any need for the filename and the input field in the toolbar.

While on it, I also think the "Last modification: ..." would fit better in the status bar at the bottom than in the toolbar at the top.

**Comment by juliushaertl** [comment]
Yes, that is rather something for https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online 

I generally agree on this from a design perspective, but there is a slight difference between save as and rename. Rename moves the file while save as creates a copy.
