### ISSUE TITLE
latest CODE install removed the data entry ui from the menubar in spreadsheet

### ISSUE THREAD

**Issue by Luticus** [nextcloud/richdocuments#883]
See Screenshot:

![code_spreadsheet](https://user-images.githubusercontent.com/7807109/78023595-ebc82200-7324-11ea-88f6-62ae9be415af.png)

This used to work fine and would show a text area to edit cells with.  Now it's missing since upgrading.

**Comment by juliushaertl** [comment]
This tracker is for the Nextcloud connector app named Collabora Online. For issues in the product, please open a bug report at: https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online

**Comment by Luticus** [comment]
Well, after leaving the document open for a while and getting the "stale document" dialogue, the bar seems to have reappeared.  it's really weird.  Thanks anyway, I'll open a bug there if it persists.
