### ISSUE TITLE
App still using old packages

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/richdocuments#884]
```
		"nextcloud-auth": "0.0.3",
		"nextcloud-axios": "^0.2.0",
		"nextcloud-l10n": "0.1.1",
		"nextcloud-router": "0.0.9",
		"nextcloud-server": "^0.15.10",
		"nextcloud-vue": "^0.13.0",
```

@juliushaertl ? :)

**Comment by aszlig** [comment]
@juliushaertl: The tarball at https://github.com/nextcloud/richdocuments/releases/download/v3.5.3/richdocuments.tar.gz also isn't the same version as the one tagged as [`v3.5.2`](https://github.com/nextcloud/richdocuments/tree/v3.5.3) and the diff between them is rather huge.

**Comment by juliushaertl** [comment]
@aszlig This is not related at all to the issue, please open a new one in the future. Regarding your comment, yes the release differs from the git tag, as we build the javascript code with webpack to bundles and remove all unneeded files afterwards for the release package.

**Comment by juliushaertl** [comment]
Update added some notes on how to do that to the readme: https://github.com/nextcloud/richdocuments/blob/master/README.md#development-setup

**Comment by aszlig** [comment]
> @aszlig This is not related at all to the issue, please open a new one in the future.

Ah, you're right, the versions specified above are not showing up in the diff.

> Regarding your comment, yes the release differs from the git tag, as we build the javascript code with webpack to bundles and remove all unneeded files afterwards for the release package.

I already excluded the generated stuff from the diff and there are other differences which I highly doubt are generated, eg. `SettingsController.php`.
