### ISSUE TITLE
Source code differs between tarball and Git tag

### ISSUE THREAD

**Issue by aszlig** [nextcloud/richdocuments#886]
When diffing the source tarball for version 3.5.3 against the Git tag, I found a lot of differences in the source code (aka: **not** the generated files). Maybe something went wrong while building the release tarball?

So initially I thought #884 was the issue, but the differences I had in package.json had all sorts of dev dependencies but not the ones listed in #884.

One example of this is `SettingsController.php`:

https://gist.github.com/aszlig/dda3726313acadf3c27a109d6da40a34

**Comment by juliushaertl** [comment]
Ok, apparently I tagged the master branch instead of the stable-3.5 one, sorry about the confusion there. I'll see if I can update the tag later.

**Comment by juliushaertl** [comment]
The release was built from https://github.com/nextcloud/richdocuments/commit/2ed8a3421ab66e47d8233e15f24be652be2bb889

**Comment by aszlig** [comment]
> The release was built from [2ed8a34](https://github.com/nextcloud/richdocuments/commit/2ed8a3421ab66e47d8233e15f24be652be2bb889)

Ah, diffing that one looks way better, thanks :-)

**Comment by juliushaertl** [comment]
Tag updated.
