### ISSUE TITLE
ctrl+alt+c adds 3 comments instead of just one

### ISSUE THREAD

**Issue by DanScharon** [nextcloud/richdocuments#89]
### Steps to reproduce
1. open a document with richdocuments
2. enter ctrl+alt+c

### Expected behaviour
One comment should be added.

### Actual behaviour
Three comments are added.

Nextcloud 11.0.3
Collabora Online 1.11.31

**Comment by thebearon** [comment]
This issue is resolved in Collabora Online 2.1.1, please update (this is the main application, not to be confused with the Nextcloud app). For verification, it is the LOOLWSD version in the About box,
