### ISSUE TITLE
PDF file is 10 pixels when shared file doesnt has hide download option checked

### ISSUE THREAD

**Issue by taavit21** [nextcloud/richdocuments#893]
If you share a pdf file and you check the hide download box then opening the shared link you will see about 10 pixel size file.

**Screenshots**
![github_pdf](https://user-images.githubusercontent.com/47745930/78654724-a6c86080-78cd-11ea-8a1f-37bbf1240fee.PNG)

**Client details:**
 - Windows 10 64bit
 - Chrome/Firefox/IE
 - Desktop

## Server details

OS **Ubuntu 18.04.4 LTS Server**:

Web Server **Nginx**

Database **MariaDB 10.0.38**

**PHP 7.2.28**

**Nextcloud 18.0.3**

Richdocuments version **3.5.3**

Collabora online version **4.2.1.3**

**Comment by timar** [comment]
We have a fix for this, and it will be released in Collabora Online version 4.2.2 in the coming days.
