### ISSUE TITLE
collabora not show

### ISSUE THREAD

**Issue by lesar** [nextcloud/richdocuments#894]
**Describe the bug**
I have https://mysite.com  
on https://nextcloud.mysite.com I have installed nextcloud
using docker I have install `docker run -t -d -p 127.0.0.1:9980:9980 -e 'domain=nextcloud\\.mysite\\.com\' -e 'dictionaries=it en' --restart always --cap-add MKNOD collabora/cod`  
I have configure collabora online on my nextcloud to use this url:
`https://nextcloud.mysite.com:9980`  
I try this too  
`https://localhost:9980`

if I click on odt file I get the same message when collabora server is not install/run

> load collabora online &nbsp; - retry later

no log on apache error log  

I need help.
best regards,
Leonardo

**Comment by juliushaertl** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by lesar** [comment]
ok, thanks
