### ISSUE TITLE
Revision history shows only latest version

### ISSUE THREAD

**Issue by Jungingen** [nextcloud/richdocuments#9]
Ubuntu 16.04.1, Latest Nextcloud (11), latest Collabora online plugin (1.1.25), latest Collabora container from docker, everything is fresh installed according to manual, but revision history sidebar, despite of any changes in a file, shows only "Just now":

![revision_history](https://cloud.githubusercontent.com/assets/13748565/21719849/71d255ae-d428-11e6-8476-bc8208396aa7.jpg)

Same with other file types and with collaborative file editing with multiple users. 
Thanks for looking into!

**Comment by pranavk** [comment]
Are you sure there are actually revisions of this file in nextcloud ? Are you able to see the revisions of this file from the files app in the sidebar ?

**Comment by Jungingen** [comment]
No, I can't see any. Or maybe I'm looking in the wrong place?

**Comment by pranavk** [comment]
Yeah, I can reproduce as well. Looked at the code a bit. This[1] is where it should be fixed. We need some way to tell the files_version app that we have modified the document when Collabroa Online saves the document so that it can do its magic and store revisions for the file. The earlier code used to artificially login the user that did the job but now it has been changed (for the good I guess); not sure what could be the solution here  

[1] https://github.com/nextcloud/richdocuments/blob/master/lib/Controller/WopiController.php#L185

**Comment by Jungingen** [comment]
Any progress here?

**Comment by krodelabestiole** [comment]
+1 running latest stable nextcloud (11.0.1) and collabora online (1.1.25) on debian.
latest collabora with docker as well.
for any file, the only revision i can get from collabora online is "Just now".

**Comment by krodelabestiole** [comment]
Actually this is not only a big issue : it's a major bug considering people can loose hours or even days of work without saving or deleting any file.  And this is happening on latest stable versions of nextcloud ! 
https://help.nextcloud.com/t/collabora-revision-history-and-versioning/6527/7

Collabora Online has to be disabled on any  nextcloud 11 right now.

**Comment by morph027** [comment]
Any ideas whats causing this? Was this working before?

By the way...i'm not running the docker stack, i'm using [this](https://github.com/husisusi/officeonlin-install.sh) and got the same behaviour.

**Comment by michag86** [comment]
I've compared version 1.1.14 with 1.1.25

I think I found the relevant difference for creating the new file versions.
I've added the three lines before https://github.com/nextcloud/richdocuments/blob/1.1.25/lib/Controller/WopiController.php#L187

                try {
                        /** @var File $file */
                        $userFolder = $this->rootFolder->getUserFolder($res['owner']);
                        $file = $userFolder->getById($fileId)[0];
                        $content = fopen('php://input', 'rb');

                        // Setup the FS which is needed to emit hooks (versioning).
                        \OC_Util::tearDownFS();
                        \OC_Util::setupFS($res['owner']);

                        $file->putContent($content);
                        return new JSONResponse();
                } catch (\Exception $e) {

With this changes, the file versions are created. But they are not listed in Revision History in Collabora.

cc @LukasReschke @MorrisJobke 

BTW: there is no maintainer listed for richdocuments: https://github.com/nextcloud/server/wiki/Maintainers

**Comment by morph027** [comment]
Confirmed, at least there are versions now. History inside collabora would be nice, but right now, this makes it usable again, thank you!

**Comment by devz3r0** [comment]
I can confirm it too, it now works again with the patch. It even works via the shared-link. Thanks for the fix.

**Comment by MorrisJobke** [comment]
@michag86 Could you add your changes to a PR against this repo? :)

**Comment by pranavk** [comment]
I notice an exception when trying to save the file with above mentioned fix in the nextcloud logs.


{"reqId":"WNOZFQBU5lwflp3Np5UujgAAAAg","remoteAddr":"127.0.0.1","app":"no app in context","message":"Exception: {"Exception":"InvalidArgumentException","Message":"The given author user is invalidN;","Code":0,"Trace":"#0 /srv/nc/apps/activity/lib/FilesHooks.php(889): OC\\\\Activity\\\\Event->setAuthor(NULL)\\n#1 /srv/nc/apps/activity/lib/FilesHooks.php(182): OCA\\\\Activity\\\\FilesHooks->addNotificationsForUser('test', 'changed_by', Array, 76, '/test.odt', true, true, 0, 'file_changed')\\n#2 /srv/nc/apps/activity/lib/FilesHooks.php(122): OCA\\\\Activity\\\\FilesHooks->addNotificationsForFileAction('/test.odt', 'file_changed', 'changed_self', 'changed_by')\\n#3 /srv/nc/apps/activity/lib/FilesHooksStatic.php(53): OCA\\\\Activity\\\\FilesHooks->fileUpdate('/test.odt')\\n#4 /srv/nc/lib/private/legacy/hook.php(106): OCA\\\\Activity\\\\FilesHooksStatic::fileUpdate(Array)\\n#5 /srv/nc/lib/private/Files/View.php(614): OC_Hook::emit('OC_Filesystem', 'post_update', Array)\\n#6 /srv/nc/lib/private/Files/View.php(663): OC\\\\Files\\\\View->emit_file_hooks_post(true, '/admin/files/te...')\\n#7 /srv/nc/lib/private/Files/Node/File.php(54): OC\\\\Files\\\\View->file_put_contents('/admin/files/te...', Resource id #549)\\n#8 /srv/nc/apps/richdocuments/lib/Controller/WopiController.php(192): OC\\\\Files\\\\Node\\\\File->putContent(Resource id #549)\\n#9 [internal function]: OCA\\\\Richdocuments\\\\Controller\\\\WopiController->putFile('76', 'SU3uy26qvaPUfT8...')\\n#10 /srv/nc/lib/private/AppFramework/Http/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#11 /srv/nc/lib/private/AppFramework/Http/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Richdocuments\\\\Controller\\\\WopiController), 'putFile')\\n#12 /srv/nc/lib/private/AppFramework/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Richdocuments\\\\Controller\\\\WopiController), 'putFile')\\n#13 /srv/nc/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Richdocumen...', 'putFile', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#15 /srv/nc/lib/private/Route/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#16 /srv/nc/lib/base.php(1010): OC\\\\Route\\\\Router->match('/apps/richdocum...')\\n#17 /srv/nc/index.php(40): OC::handleRequest()\\n#18 {main}","File":"/srv/nc/lib/private/Activity/Event.php","Line":165}","level":3,"time":"2017-03-23T09:44:53+00:00","method":"POST","url":"\/nextcloud\/index.php\/apps\/richdocuments\/wopi\/files\/76_oc4zrq3339pu\/contents?access_token=SU3uy26qvaPUfT8CSNhK3jqn8xG3bdb6&access_token_ttl=0&permission=edit","user":"--","version":"11.0.0.10"}

Sorry for obfuscated logs.

Nevertheless, the above fix seems to work and stores the revisions of the file.

Regarding, revisions not showing up in the revision history sidebar, here's a quick fix that works - 
https://github.com/nextcloud/richdocuments/pull/33

**Comment by morph027** [comment]
Just put log output into

    ```
    your log....
    ```

**Comment by pranavk** [comment]
@morph027 Thanks. Sorry, I wanted to comment that on #27 , but commented it here by mistake. I have deleted the comment and its now in its correct place, with appropriate markup as you suggested

**Comment by morph027** [comment]
:) Also can confirm this works, thank you!

**Comment by oparoz** [comment]
Fixed via #27
