### ISSUE TITLE
Switching to a different tab and back after some time makes you jump to the first slide

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/richdocuments#90]
I had this issue with a presentation shared to me:

1. Viewing it in the Collabora app, then switching tabs for some time (30 seconds or a minute only)
2. Coming back to it, there was a grey overlay with text visible for a split-second, I think it said »Inactive document« or so.
3. The presentation then jumped back to the first slide instead of the 3rd or 5th I was on.

cc @pranavk @timar :)

**Comment by thebearon** [comment]
Does this happen regularly? Is it possible someone else made changes to the first slide in the meantime?

**Comment by jancborchardt** [comment]
I could reproduce it multiple times and no one else was working on the slides in the meantime.

Even of there was someone else, that should not mess up my own position in the slides. :)

**Comment by thebearon** [comment]
It should not, but since I can't repro the bug based on the description, I'm looking for other clues.
Please post the version info from Help -> About, and your OS and browser versions as well.
