### ISSUE TITLE
Sidebar gets in the way on small screen

### ISSUE THREAD

**Issue by lahwaacz** [nextcloud/richdocuments#907]
The Collabora Online editing page looks like this in my browser:
[![screenshot-2020-04-17-21-56-05.png](https://i.postimg.cc/908x9rMr/screenshot-2020-04-17-21-56-05.png)](https://postimg.cc/4Hcbk4pg)

The sidebar on the right totally gets in the way on small screen. How can I close it?

**Comment by thebearon** [comment]
It's the rightmost button on the toolbar. Please see the following bug report: [tdf#130650](https://bugs.documentfoundation.org/show_bug.cgi?id=130650)
