### ISSUE TITLE
Error if german "Umlaute" are in file name

### ISSUE THREAD

**Issue by THS-on** [nextcloud/richdocuments#91]
Hello,
I have some issues with files that have the letters "ö,ä or ü" in it. Tested with Firefox and Chrome using richdocuments 1.12.3 and LibreOffice online 2.1.0 (git hash: 0a8d112).

Error in LibreOffice online logs
```
kit-22833-23282 14:00:46.239638 [ lokit_164 ] ERR  Failed to load: file:///user/docs/22833/empf%C3%A4nger.odt, error: Unsupported URL <file:///user/docs/22833/empf%C3%A4nger.odt>: "type detection failed"| kit/Kit.cpp:1184
kit-22833-23282 14:00:46.239800 [ lokit_164 ] ERR  Failed to get LoKitDocument instance.| kit/ChildSession.cpp:347
```
Is this really an issue in richdocuments or is it in LibreOffice online?

### Steps to reproduce
1. Create a file with the name "empfänger.odt"
2. Try to open it
3. Get an error message like this: "Das Laden des Dokuments ist fehlgeschlagen. Bitte vergewissern Sie sich, dass der Dateityp unterstützt und die Datei nicht defekt ist, und versuchen Sie es dann erneut."

### Expected behaviour
The document opens normally.

### Actual behaviour
Error message:
```
Das Laden des Dokuments ist fehlgeschlagen. Bitte vergewissern Sie sich, dass der Dateityp unterstützt und die Datei nicht defekt ist, und versuchen Sie es dann erneut.
```

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache/2.4.10 (Debian) (apache2handler)

**Database:** mysql 5.7.18

**PHP version:** 5.6.30-0+deb8u1

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Where did you install Nextcloud from:**  Source

**Signing status:**

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

### Client configuration
**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0

**Operating system:** Linux

**Comment by THS-on** [comment]
Only my version is affected. I've tested it with the latest official Version and it's working.

**Comment by fwolfst** [comment]
Where and how did you change the locale? In the Collabora docker container?

**Comment by THS-on** [comment]
@fwolfst this installation was compiled from source and ran in Debian VM. I don't have that setup anymore, but I think I changed the locale of the vm or exported `LANG=C.UTF-8` in the systemd service.
