### ISSUE TITLE
Arrows to go from 1 sheet to the next are grayed out and don't work

### ISSUE THREAD

**Issue by albenak** [nextcloud/richdocuments#918]
**Describe the bug**
Arrows to go from 1 sheet to the next are grayed out and don't work

**To Reproduce**
1. I am using Chrome, but tried it on Brave and Firefox as well; cleared the cache, same thing.
2. I can't see different sheets in a spreadsheet doc, just the first one. 
3. The arrows at the bottom, next to "Sheet 1 of 2" are grayed out. 

**Expected behavior**

**Screenshots**
<img width="294" alt="Capture14" src="https://user-images.githubusercontent.com/64192592/80075497-716d7500-8553-11ea-9d0f-411daacd14fb.PNG">

**Client details:**
 - OS: Windows 10 Pro
 - Browser Chrome
 - Version 81.0.4044.113 (Official Build) (64-bit)
 - Device: Desktop

## Server details

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:**

**Version of the richdocuments app**

**Version of Collabora Online**

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
This tracker is for the Nextcloud connector app named Collabora Online. For issues in the product, please open a bug report at: https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online
