### ISSUE TITLE
option not to open OOXML and MS-Office files (docx, ..., doc, ...)

### ISSUE THREAD

**Issue by kolAflash** [nextcloud/richdocuments#928]
Please provide an option to disable opening OOXML and MS-Office files (docx, ..., doc, ...) by default.
This is needed, if another Nextcloud app like OnlyOffice is installed to open those files.

Currently, when installing LibreOfficeOnline and OnlyOffice, the behaviour is very confusing.
E.g. docx files open with OnlyOffice when logged into Nextcloud. But when an anonymous user clicks a shared link to a docx file, it's being opened with LibreOfficeOnline (this is not for link-shared folders, but only single link-shared files).

**Comment by juliushaertl** [comment]
cc @jancborchardt 

I remember we had some discussion about running both office suites together but I do not remember if there was any outcome on this.

**Comment by jancborchardt** [comment]
It seems @kolAflash's core issue is that the behavior is different for logged-in people vs guests. Of course this should be consistent.

Since with 19 our default is Collabora Online, that should also stay the default if both are installed.
