### ISSUE TITLE
option not to show New Document/Spreadsheet/Presentation

### ISSUE THREAD

**Issue by kolAflash** [nextcloud/richdocuments#929]
Please provide an option, not to show the `New Document`,  `New Spreadsheet` and `New Presentation` links in the `+` menu (add icon).

This is needed, if there are multiple editors installed. E.g. LibreOfficeOnline, OnlyOffice, Markdown-Editor.
In this case, users are being confused by three different possibilities to create a `New Document` (LibreOfficeOnline odt), `Document` (OnlyOffice docx) or `New text document` (Markdown-Editor).
Same for Spreadsheets and Presentations (except Markdown-Editor).
&nbsp;

Please forgive me, that I don't prefer ODF / LibreOfficeOnline in this case. But I need to keep my users away from using GoogleDocs and other stuff. So a clear UI is a must.
Nevertheless, I keep LibreOfficeOnline installed because it's just the best to open existing ODF files.

Related: #928

**Comment by juliushaertl** [comment]
Depends on the outcome of https://github.com/nextcloud/richdocuments/issues/928#issuecomment-626604253

**Comment by juliushaertl** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
As said: If both Collabora Online and OnlyOffice is installed, we should use one by default for simplicity. Since Collabora Online is the new shipped one with Nextcloud 19, that should be the default.

"New text document" for the Text app is different by filetype, icon and label, so that's fine.

**Comment by parrenin** [comment]
I would not say the problem with interaction between Collabora and OnlyOffice is completely solved.
For example, if both are installed, you have both "New document" from Collabora and "Document" from OnlyOffice, which is quite confusing.
Would not it be possible to label them ".odt document" and ".docx document", to better distinguish them?
