### ISSUE TITLE
Pandoc integration

### ISSUE THREAD

**Issue by sunjam** [nextcloud/richdocuments#930]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use Pandoc within Collabora to convert between [any number of document types and formatting](https://pandoc.org/).  This is extremely useful when writing documentation, drafting out a page for mediawiki, etc!

**Describe the solution you'd like**
Integration of the excellent [Pandoc](pandoc.org/try).

**Describe alternatives you've considered**
* You can convert documents using the hosted demo at pandoc.org/try
* You can install Pandoc on your local machine and call it from scripts of the command line.
* Perhaps connect with [this rest api](https://github.com/alphakevin/pandoc-api) version of pandoc.

**Additional context**
Pandoc allows you to convert between all major document formatting types.  Thanks for reading and considering.

**Comment by juliushaertl** [comment]
This is something for a separate app as richdocuments is just for integrating Collabora itself.
