### ISSUE TITLE
No connection with CODE instance if server seems to respond too slowly

### ISSUE THREAD

**Issue by schorsch2** [nextcloud/richdocuments#946]
**Describe the bug**
Documents are not opened in Nextcloud. There is a message: Collabora- Development Edition not available, try again later.

**To Reproduce**
Open existing odt- document

**Expected behavior**
document opens

**Screenshots**

**Client details:**
OpenSuse Linux LEAP 15.1, docker containers for Nextcloud and 

## Server details
Intel(R) Xeon(R) CPU E5-2407 0 @ 2.20GHz (4 cores); 15.6 GB 
OpenSuse Linux LEAP 15.1, docker containers for Nextcloud and CODE

Web server: nginx

Database: postgres 10

PHP version: 7.3.17

Nextcloud version: 18.0.4 - 18.0.4.2

Version of the richdocuments app: 3.5.3

Version of Collabora Online: 4.2.3

If the CODE server does not answer fast enough, the files
- capabilities.json
- discovery.xml
are not properly applied. 
I have made changes to the file
/lib/Service/CapapapapilitiesService.php was made:
$client = $this->clientService->newClient();
		$options = ['timeout' => 10];
new: $options = ['timeout' => 15];

and the file
/lib/WOPI/DiscoveryManager.php
$client = $this->clientService->newClient();
		$options = ['timeout' => 5];
new: $options = ['timeout' => 10];

After that the application worked properly.

**Comment by juliushaertl** [comment]
I don't see a reason why the discovery/capabilities requests would take that long. Are both Collabora and Nextcloud on the same server? Could you try to manually request https://yourcollabora/hosting/capabilities and see if that is responding slow as well?

**Comment by schorsch2** [comment]
Both are on the same server.
Manually request takes about 10 s. Ping to mycollabora acts immediately- but not from inside the nextcloud- container! The DNS configuration of the Docker Daemon was not correct. After correct entry of the responsible server, Collabora-Online now runs correctly. Thanks for your help!
