### ISSUE TITLE
Disable certificate check

### ISSUE THREAD

**Issue by mmaridev** [nextcloud/richdocuments#948]
**Describe the bug**
The check "disable certificate check" since the release of 2 hours ago is no longer working.

**To Reproduce**
1. Go to Collabora Online under admin panel
2. Check disable check certificate
3. Go to another tab then back to collabora

**Expected behavior**
The certificate check is disabled

**Screenshots**

**Client details:**
 - OS: Debian 10
 - Browser Firefox ESR
 - Version 68.7
 - Device: desktop

## Server details

**Operating system**: Debian

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7

**Nextcloud version:** 18.04

**Version of the richdocuments app** latest

**Version of LibreOffice Online** 6.

**Comment by paulvt** [comment]
For me, it even says "Could not establish connection to the Collabora Office server". Then I click Save, everything is ok without changing anything. Reload the page and it is back in the error state.

This is since the update of the app to 3.6.0 that I did just before the problems started.

**Comment by lipnotic** [comment]
Stoped working for me after last update hours ago (3.6.0)....
When trying to open a file It says "Collabora Online is not setup yet"....
Then I go to Settings> Collabora config. > save server config (returning green cheek). But looks its not persisting.

**Comment by juliushaertl** [comment]
Any errors in your browser console or nextcloud log when saving the configuration?

**Comment by lipnotic** [comment]
Julius,
Thanks for replying...
Don't realize any log related to collabora.
It was working fine until 2 days ago...
Noticed it stops working after 3.6.0 update.
FYI: I'm using collabora on a docker container. But... I don't make any
changes there... I've even restarted collabora server (docker) and retried
to configure the Collabora settings on nextcloud, tried to uninstall and
reinstall the Collabora Online nextcloud app with no success. 😕

Thanks in advance,
Felipe Garbin

Em ter, 12 de mai de 2020 03:04, Julius Härtl <notifications@github.com>
escreveu:

**Comment by weberhofer** [comment]
I see the same issue here at my installation.

**Comment by mmaridev** [comment]
> Any errors in your browser console or nextcloud log when saving the configuration?

Yes, a few.

```
Error: "Request failed with status code 500"
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:59
AdminSettings.vue:376

Error: "Request failed with status code 500"
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:59
AdminSettings.vue:376

Error: "Request failed with status code 500"
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:
```

**Comment by juliushaertl** [comment]
> Request failed with status code 500

So there was an error on the server:

> Any errors in your browser console **or nextcloud log** when saving the configuration?

Please check the nextcloud log as well then.

**Comment by mmaridev** [comment]
Sorry, I had to downgrade the plugin since that was is an in-production
server. I may check the nextcloud.log later.

Il Mar 12 Mag 2020, 12:00 Julius Härtl <notifications@github.com> ha
scritto:

**Comment by mmaridev** [comment]
At the moment, I can't find any information regarding 
* richdocuments
* my user
* my IP

in the log

**Comment by weberhofer** [comment]
There was nothing in the logs but only some inconsistent queries, you could try the changes from the pull request I have submitted.

**Comment by mmaridev** [comment]
refs #950
