### ISSUE TITLE
3.6.0: cannot switch back to own server from demo server

### ISSUE THREAD

**Issue by timar** [nextcloud/richdocuments#951]
At settings/admin/richdocuments I selected "Use a demo server". Then I wanted to switch back to "Use your own server". After pressing save the setting jumped back to "Use a demo server".

**Comment by juliushaertl** [comment]
Did you change the url do some other server? If the demo server url is saved as your own server i would assume it is expected to switch the UI to the demo mode. Otherwise I cannot reproduce that.

**Comment by timar** [comment]
OK, you are right. I fell into my own trap. Let's close this.
