### ISSUE TITLE
3.6.0 no warning about protocol mismatch

### ISSUE THREAD

**Issue by timar** [nextcloud/richdocuments#952]
For example when some used Nextcloud with http:// and entered a Collabora Online URL with https:// or vice versa, richdocuments gave a warning:

Saved with error: Collabora Online should use the same protocol as the server installation.

I don't see this warning any more.

**Comment by juliushaertl** [comment]
I think this got lost during the migration to vue for the settings components. We would need to re-add the check when configuring Collabora Online in the settings to match the current protocol with the one specified on the URL.

For some even further enhacement we could also make sure that the discovery urls use the same protocol as the nextcloud server (@luka-nextcloud this is the issue that you encountered on your setup).

**Comment by joshtrichards** [comment]
Fixed in #1833
