### ISSUE TITLE
3.6.0 - Collabora Online is not setup yet.

### ISSUE THREAD

**Issue by JB1985** [nextcloud/richdocuments#955]
Hi, 

today I have updated to 3.0.6 and now I get the error:

> Collabora Online is not setup yet.
> Click here to configure your own server or connect to a demo server.

I dont see anything in the logs. If I install the wopi App, it works again.

If I go to settings -> Collabora online I get the error:

> Es konnte keine Verbindung zum Collabora Online-Server hergestellt werden.

But when I click save, I get the message:

Collabora Online Server ist erreichbar.

But if I want to open a file again, I get the error Collabora Online is not setup yet.

**Comment by thebearon** [comment]
Please check #949.
