### ISSUE TITLE
Document creation not fully working in chromium

### ISSUE THREAD

**Issue by mmaridev** [nextcloud/richdocuments#956]
**Describe the bug**
From chromium, when creating a new document, the page of LOOL loads but shows "unsuccessful load of the document" message. The file is being created. Back to the folder and click on the file works fine. 

**To Reproduce**
1. Click the plus sign
2. Choose "new document"
3. Put a filename and confirm

**Expected behavior**
The document editing is opened

**Client details:**
 - OS: Debian 10
 - Browser: Chromium
 - Version: 81.0.4044.138
 - Device: desktop

## Server details

**Operating system**: Debian 10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** 18.04

**Version of the richdocuments app** 3.5.3

**Version of LOOL** 6.4

<details>
<summary>Logs</summary>

#### Browser log
```
bundle.js:54 Uncaught DOMException: Blocked a frame with origin "https://cloudpub-lool.continuity.space" from accessing a cross-origin frame.
    at NewClass._postMessageListener (https://lool.domain.tld/loleaflet/87fea7126/bundle.js:54:18860)
    at handler (https://lool.domain.tld/loleaflet/87fea7126/bundle.js:52:22366)
```

</details>

**Comment by thebearon** [comment]
This tracker is for the Nextcloud connector app named Collabora Online. For issues in the product, please open a bug report at: https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online

Also, please do check with a LOOL master build.

**Comment by mmaridev** [comment]
That's not a bug of LOOL or of Collabora but a problem that your WOPI connector is facing with Chormium. The fact that the same procedure is working on Firefox and not on Chormium is quite self-explaining.
Even Collabora users will be affected by this bug... do your calculations ;-)

**Comment by thebearon** [comment]
The exception is triggered in bundle.js, which is the bundled LOOL source, the problem is more likely on LOOL side. Not sure why the problem only affecting certain browsers would be self-explaining, do explain if you want.

**Comment by joergmschulz** [comment]
this https://bugs.documentfoundation.org/show_bug.cgi?id=135536 bug report is not really getting forward. I also think it is a lool issue and not a richdocuments issue. Some lool versions work, some not. No reason to reopen this one!
