### ISSUE TITLE
Updating to 3.6.0. don't save preferences

### ISSUE THREAD

**Issue by mickymadsystems** [nextcloud/richdocuments#957]
I have upgraded to version 3.6.0 and now it doesn't save my server preferences correctly

**Comment by juliushaertl** [comment]
The issue template is here for a reason. Please fill it out and provide more information especially if there is something in your browser and nextcloud log.

**Comment by thebearon** [comment]
Also, this is likely the same as #949.

**Comment by alxrdn** [comment]
hi guys,

I guess there is a real problem : I had the same "not saving prefs" behavior and noticed this in my logs : 
`Undefined index: templatesAvailable at /var/www/nextcloud/apps/richdocuments/templates/admin.php#10`

I works by adding 
`(**isset($_['settings']['templatesAvailable'])**) && ($_['settings']['templatesAvailable'] === true)`

**Comment by alxrdn** [comment]
> Also, this is likely the same as #949.

@thebearon, likely not the same as #949 because once added `isset` clause everything is back on rails and I already had both `hosting/discovery` and `hosting/capabilities` rp routes configured.

**Comment by juliushaertl** [comment]
Well I cannot see anything about the templatesAvailable error in the original report. In that case it is of course not the same one :wink: 

However I don't see how this error can even occur since the the templatesAvailable key should actually always be set to either true or false in https://github.com/nextcloud/richdocuments/blob/0bd69be42b242b651c25410d0cb6646042b7ff81/lib/Settings/Admin.php#L90 :confused:

**Comment by alxrdn** [comment]
obviously I never meant to support the lack of usage of issue template...

I'm not an expert neither regarding php neither richdocuments, so there I can't help any further, sorry

**Comment by iniOr** [comment]
Hi I confirm that after upgrading to 3.6.0 server preferences where not saved, rolled back into the previous version fixed the issue.

**Comment by benhartwich** [comment]
I´ve got the same issue at nginx 1.19.0, php7.3 at debian 10 on two different servers. Collaboraserver works as expected.

**Comment by meyca** [comment]
I had the same issue and could solve it by comparing my nginx reverse proxy config with [https://www.collaboraoffice.com/code/nginx-reverse-proxy/](https://www.collaboraoffice.com/code/nginx-reverse-proxy/)

It seems that the capabilities section came in later (and was not yet configured in my setup).

Adding the 
```
location ^~ /hosting/capabilities 
{...} 
```
section solved the problem for me.

**Comment by juliushaertl** [comment]
Closing as a duplicate of https://github.com/nextcloud/richdocuments/issues/949
