### ISSUE TITLE
19 RC1 -> 19 RC2 - Nextcloud can't find Collabora server

### ISSUE THREAD

**Issue by Dragon988** [nextcloud/richdocuments#960]
It locates it fine in the admin area but when trying to open a document as a regular user it can't find the server.

Worked fine in NC 19 RC1.

No errors are printed in the nextcloud.log, so I'm not sure if this is bug can be recreated. Either way I'll be doing a fresh install of 19 once it's officially stable.

![firefox_7dhwFXxjGE](https://user-images.githubusercontent.com/7935624/81968913-f4717080-95d1-11ea-844e-461778f367bf.png)

**Comment by thebearon** [comment]
Based on the information I can't tell if it's really related to updating to a new NC version, or to updating to richdocuments 3.6.0. Please check #949, especially [this comment](https://github.com/nextcloud/richdocuments/issues/949#issuecomment-627155533).

**Comment by stanelie** [comment]
I had the same issue.
Adding
```
# Capabilities
ProxyPass           /hosting/capabilities https://IP-of-my-collabora-server:9980/hosting/capabilities retry=0
ProxyPassReverse    /hosting/capabilities https://IP-of-my-collabora-server:9980/hosting/capabilities
```
to my apache reverse proxy config, as per @thebearon 's comment, fixed it for me.

**Comment by Dragon988** [comment]
> 
> 
> Based on the information I can't tell if it's really related to updating to a new NC version, or to updating to richdocuments 3.6.0. Please check #949, especially [this comment](https://github.com/nextcloud/richdocuments/issues/949#issuecomment-627155533).

The nginx config did not do anything for me. I also don't recall nextcloud saying it was updating collabora between RC1 and RC2 but it's possible. Pretty sure I was already on 3.6.0, there were no app updates prior to the upgrade.

No big rush, hopefully it's fixed by the time 19 is fully released.

**Comment by thebearon** [comment]
Can you check https://<reverse proxy address>/hosting/capabilities in your browser? It should result in JSON content.

**Comment by stanelie** [comment]
Btw, I'm still on Nextcloud 18.3. so, the issue is probably related to the Collabora app, or the docker Collabora server, not Nextcloud itself.

**Comment by juliushaertl** [comment]
I would expect that this is indeed a similar issue as #949 as we also check for the capabilities before opening a file now https://github.com/nextcloud/richdocuments/commit/315677f8102c1f11ee8cab1ddc74c6228a54f721#diff-113ff46cf15064abc1c127f2a79f9c14R39

**Comment by Dragon988** [comment]
> 
> 
> Based on the information I can't tell if it's really related to updating to a new NC version, or to updating to richdocuments 3.6.0. Please check #949, especially [this comment](https://github.com/nextcloud/richdocuments/issues/949#issuecomment-627155533).

The issue did end up being the nginx config mentioned on the comment. User error in my case. So this is #949.

Sorry! I'll go ahead and close this now.
