### ISSUE TITLE
 external collabora server detection does not work reliable

### ISSUE THREAD

**Issue by gpgmailencrypt** [nextcloud/richdocuments#971]
**Describe the bug**
Since version 3.6.0 the detection of external collabora servers does not work reliable any more.
**To Reproduce**

1. Go to 'settings/admin/richdocuments'
2. Click on 'Save' and it works
   Reload the page and there is no connection to the server. As the server can't be found, OO-documents can't be opened any more
3. Error messages: none in log

**Expected behavior**
hold permanent contact to the collabora server

**Screenshots**
After pushing Save button:
![collabora save button](https://user-images.githubusercontent.com/13087633/82154025-78925500-986b-11ea-86d7-c789bf14a36d.png)
After reloading the page:
![collabora reload](https://user-images.githubusercontent.com/13087633/82154032-8516ad80-986b-11ea-88f8-4eff9616e82b.png)

**Client details:**
 - OS: Ubuntu 18.04
 - Browser firefox
 - Version 76.0
 - Device: desktop
## Server details

**Operating system**: 
Ubuntu 18.04
**Web server:**
Apache 2.4.29-1ubuntu4.13
**Database:**
mariadb Ver 15.1 Distrib 10.1.44-MariaDB
**PHP version:**
7.2.24-0ubuntu0.18.04.4
**Nextcloud version:**
18.0.4
**Version of the richdocuments app**
3.6.0
**Version of Collabora Online**
6.2.10.12-12

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
none
```

#### Browser log
```
none.
```

</details>

**Comment by thebearon** [comment]
Please check #949, especially [this comment](https://github.com/nextcloud/richdocuments/issues/949#issuecomment-627155533).
