### ISSUE TITLE
"document can not be saved on storage" even when save works

### ISSUE THREAD

**Issue by PhieF** [nextcloud/richdocuments#98]
Issue reported here by many users
This popup appears even if saving works since last update 

https://help.nextcloud.com/t/collabora-document-can-not-be-saved-on-storage/13464/5

**Comment by thebearon** [comment]
Is there anything relevant in the logs?

**Comment by Phoenamandre** [comment]
I don't have access to my server right now, but to help you I can say it
was after updating the nextcloud app, not the docker. And updating the
docker didn't fix it. Once I have access to the server, is it the docker
log you need or anything dealing with nextcloud ?

**Comment by thebearon** [comment]
See @pranavk's comment/question in the linked thread.

**Comment by yoalieh** [comment]
This happens too with files inside group folders. The update time of the "unsaved" file is not changed, but if opened or downloaded the files has the changes. The only possible entry in the log file:


Error | index | Error: Call to a member function getId() on null/var/www/html/lib/private/Share20/ShareHelper.php - line 51: OC\Share20\Manager->getAccessList(Object(OC\Files\Node\File), true, true)/var/www/html/apps/activity/lib/FilesHooks.php - line 616: OC\Share20\ShareHelper->getPathsForAccessList(Object(OC\Files\Node\File))/var/www/html/apps/activity/lib/FilesHooks.php - line 196: OCA\Activity\FilesHooks->getUserPathsFromPath('/Projects/Activ...', 'dvelasco')/var/www/html/apps/activity/lib/FilesHooks.php - line 157: OCA\Activity\FilesHooks->addNotificationsForFileAction('/Projects/Activ...', 'file_changed', 'changed_self', 'changed_by')/var/www/html/apps/activity/lib/FilesHooksStatic.php - line 55: OCA\Activity\FilesHooks->fileUpdate('/Projects/Activ...')/var/www/html/lib/private/legacy/hook.php - line 106: OCA\Activity\FilesHooksStatic fileUpdate(Array)/var/www/html/lib/private/Files/View.php - line 617: OC_Hook emit('OC_Filesystem', 'post_update', Array)/var/www/html/lib/private/Files/View.php - line 666: OC\Files\View->emit_file_hooks_post(true, '/dvelasco/files...')/var/www/html/lib/private/Files/Node/File.php - line 64: OC\Files\View->file_put_contents('/dvelasco/files...', Resource id #12)/var/www/html/custom_apps/richdocuments/lib/Controller/WopiController.php - line 204: OC\Files\Node\File->putContent(Resource id #12)[internal function] OCA\Richdocuments\Controller\WopiController->putFile('1080', 'XgtU3OnvD6siE3e...')/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Richdocuments\Controller\WopiController), 'putFile')/var/www/html/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Richdocuments\Controller\WopiController), 'putFile')/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Richdocumen...', 'putFile', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)/var/www/html/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)/var/www/html/lib/base.php - line 1000: OC\Route\Router->match('/apps/richdocum...')/var/www/html/index.php - line 40: OC handleRequest(){main}
-- | -- | --

**Comment by maxtheaviator** [comment]
possible duplicate: #70
