### ISSUE TITLE
Nginx Link doesn't resolve

### ISSUE THREAD

**Issue by simonspa** [nextcloud/richdocuments#996]
**Describe the bug**
The link provided for missing nginx configuration in https://github.com/nextcloud/richdocuments/blob/b670f81c0913c4af666fa273c62cacd5ed27a28b/src/components/AdminSettings.vue#L31 does not resolve:

https://www.collaboraoffice.com/online/connecting-collabora-online-single-click-with-nginx/

**Comment by thebearon** [comment]
The content is being finalized, please check back tomorrow.

**Comment by simonspa** [comment]
This is now released as 3.7.0 but the link still points to nirvana...

**Comment by thebearon** [comment]
Thanks for the reminder! Fixed now.
